Job Menu Redesign
ParadiseSS13/Paradise pull request #13881
Opened 2020-07-20 14:58 UTC by AffectedArc07

## What Does This PR Do
This PR changes the job selection menu up to give it a new coat of paint, and redesign it to make it a lot less squished. This implementation was inspired by TG's, but re-written for our code. A button has been added to link players to the page with detailed info about job selection and assignment.
![image](https://user-images.githubusercontent.com/25063394/87960113-c1ed6380-caab-11ea-9c20-51d4ddd962d9.png)

There is also a condition for whether SSjobs has initialized, to avoid runtimes with jobs, as well as a few colour changes because our current one has like 500 accessibility violations
![image](https://user-images.githubusercontent.com/25063394/87952449-beed7580-caa1-11ea-9f02-5197f05a390e.png)

Before for comparison
![image](https://user-images.githubusercontent.com/25063394/87952811-26a3c080-caa2-11ea-805e-2bb9cf7de9d4.png)

Fixes #12148

## Why It's Good For The Game
The current job menu is just too squished and is a perfect example of how not to do web design

## Changelog
:cl: AffectedArc07
add: Remade the job selection menu to make it cleaner and more spaced out
/:cl:

2020-07-20 16:44 UTC, SteelSlayer commented on code/modules/client/preference/preferences.dm
> +	if(SSjobs.occupations.len <= 0)
I think we prefer `length()` now over `.len`. Also doing something like `if(!length(SSjobs.occupations))` *should* work unless you did the `<= 0` for a reason.

2020-07-20 16:45 UTC, SteelSlayer commented on code/modules/client/preference/preferences.dm
> +		for(var/datum/job/job in SSjobs.occupations)
Can you do a typeless loop here? Will there be anything other than job datums in the list?

2020-07-20 17:57 UTC, procdrone commented
nice

2020-07-21 05:59 UTC, taukausanake commented
The new menu seems a little wide. Any chance it can be made to size like the old one but still keep the same functionality? Is that just a window scaling thing?

2020-07-21 06:56 UTC, AffectedArc07 commented
It was made to be widescreen to combat this bullshit
![image](https://user-images.githubusercontent.com/25063394/88022627-8ee8b580-cb27-11ea-9c94-d16045431db2.png)
![image](https://user-images.githubusercontent.com/25063394/88022641-94460000-cb27-11ea-872c-6e18e0815cda.png)
![image](https://user-images.githubusercontent.com/25063394/88022662-9c05a480-cb27-11ea-83df-a2c407d5691b.png)
This amount of widescreen looks ***awful***

2020-07-21 10:01 UTC, Crazylemon64 commented on code/modules/client/preference/preferences.dm
>  	var/HTML = "<body>"
You want this to be a list(), and then use list.join() to avoid string concatenation overhead.

2020-07-21 10:26 UTC, AffectedArc07 commented
![image](https://user-images.githubusercontent.com/25063394/88043147-f6f9c480-cb44-11ea-8f07-a9a08b8af413.png)
Listing complete, working as intended

2020-09-27 04:40 UTC, Kyep commented
Please add Fixes https://github.com/ParadiseSS13/Paradise/issues/12148 to this PR's description, so merging it closes that issue.

2020-10-07 18:11 UTC, farie82 requested changes

2020-10-07 18:11 UTC, farie82 commented on code/modules/client/preference/preferences.dm
> +		for(var/i = 1, i < (limit - index), i += 1) // Finish the column so it is even
`for(var/i in 1 to limit - index)`

2020-10-07 18:11 UTC, farie82 commented on code/modules/client/preference/preferences.dm
> +					for(var/i = 0, i < (limit - index), i += 1)
`for(var/i in 1 to limit - index)`

2020-10-07 18:11 UTC, farie82 commented on code/modules/client/preference/preferences.dm
> +					if(alert("Would you like to open the Job selection info in your browser?",,"Yes","No")=="Yes")
Spacing

2020-10-07 20:03 UTC, farie82 approved these changes

2020-10-17 22:59 UTC, moxian commented
As an author of #12148 I am very happy to see this.

This looks oddly wide, so I checked it out on a small resolution, to see if it's problematic there. The answer is - it's kinda broken, but not in a way I expected:
![zt8LOdB6n1](https://user-images.githubusercontent.com/7831163/96354951-e61d0880-10cb-11eb-9b6f-de989bda314e.png)

- The rightmost (grey) section somehow becomes one row taller than the rest (I have no idea why)
- the "Learn more about job selection" becomes sneakily hidden. (Removing extra `<br>`s inside `div`s, and rearranging the text so that `Save` button is not sandwiched between two sentences would make the content shorter horizontally, and allow for that extra button even on smol screens)

2020-10-25 17:37 UTC, Crazylemon64 approved these changes

2020-10-25 18:05 UTC, merged