Adds Earmuffs providing immunity to Changeling shriek
ParadiseSS13/Paradise pull request #14033
Opened 2020-08-07 21:45 UTC by warior4356

## What Does This PR Do
For consistency this makes it so earmuffs protect against changeling shriek just like they do the vampire shriek

## Why It's Good For The Game
Earmuffs are supposed to provide immunity to all sonic attacks, it is inconsistent that they don't protect against this one.

## Changelog
:cl:
add: Earmuffs now provide immunity to changeling shriek
/:cl:

2020-08-07 23:13 UTC, TheMaveran commented
While this is for consistency purposes - I do wonder, why do these provide protection from the shrieks whilst giving no downsides? Seems like a balance oversight, especially given that the vampire version is extremely costly to use.

2020-08-07 23:31 UTC, Spacemanspark commented
They do have downsides. You can't wear any headsets with them equipped and it has a chance for you to not hear what people around you are saying.

It's a very situational item.

2020-08-08 16:57 UTC, TheSardele commented
I don't remember the effects spark describe being a thing, I don't think they actually have any downsides. Quick search of the code for the earmuffs didn't turn up anything.

2020-08-08 17:59 UTC, Denthamos commented
@TheSardele I do remember the not hearing anything being a thing, but the not wearing headsets I do not.  I wonder if that downside of the earmuffs was lost in the fix to them which made them protect against vampire screech again.

2020-08-08 18:10 UTC, MRgaty commented
I normally wear earsmuffs as sec officer because they really have no downsides, have never experienced deafness or any kind of downsides and I could wear my headsets pretty well.

2020-08-08 21:32 UTC, Qwertytoforty commented
I thought the only catch earmuffs had was you couldn't wear two headsets.

2020-08-09 07:23 UTC, TheMaveran commented
Yeah - As earmuffs currently are, they have literally no downside. They just take one ear slot and as far as I've seen, do not prevent your ability hear.

2020-08-25 18:27 UTC, Dumbdumn5 commented
If those changes do what I think they did @warior4356 then you got yourself a :+1: , would like some confirmation on that refactoring and deafness bit though is all since I can't read wizard speak.

2020-08-25 20:55 UTC, farie82 commented on code/modules/mob/living/carbon/human/human.dm
> +	if(!src.can_hear())
src is implied. Can remove `src.`

2020-08-25 20:55 UTC, farie82 commented on code/modules/mob/living/carbon/human/human.dm
> +	if(l_ear && istype(l_ear, /obj/item/clothing/ears/earmuffs))
Can simplify this one and the one on line 948 to just an istype. `istype(null)` will return FALSE

2020-09-09 14:37 UTC, farie82 requested changes
You're also missing quite some other tweaks due to the changes.
Deaf people now won't be affected by quite some things. Like the honk mech and explosions (for ear damage) etc.

2020-09-09 14:37 UTC, farie82 commented on code/modules/mob/living/carbon/human/human.dm
> +			if(src.check_ear_prot() < HEARING_PROTECTION_TOTAL)
`src.` can be omitted here

2020-09-09 14:37 UTC, farie82 commented on code/modules/mob/living/carbon/human/human.dm
> +			if(src.check_ear_prot() < HEARING_PROTECTION_TOTAL)
Same

2020-09-16 15:17 UTC, variableundefined requested changes
Approved design-wise. Please address Farie's review above.

2020-09-19 06:03 UTC, warior4356 commented
Requested changes have been made, changelog has been updated, and more information was added to the PR.

2020-09-19 06:52 UTC, farie82 approved these changes

2020-09-19 06:53 UTC, Kyep approved these changes

2020-09-20 22:32 UTC, merged