Adds extra spess ruins
ParadiseSS13/Paradise pull request #14149
Opened 2020-08-26 01:54 UTC by Nazsgull

## What Does This PR Do
Adds the following space ruins:

> Syndicakes Factory
> debris1
> debris2
> debris3
> maze

## Why It's Good For The Game

Adds more variety to the pool of possible space ruins you can find when spacefaring. This can lead to new roleplay options, like gathering an exploration crew to scout the labyrinth or discovering the terrible secret of the Syndicakes.
## Images of changes
Please notify me If any of the following cannot be visualized.

**Syndicakes Factory**:
_"Syndicate used to get funds selling corgi cakes produced here. Was it hit by meteors or by a Nanotrasen comando?"_
This ruin is built like a puzzle, there's a room with loot and machines that will only work if powered. To do that you have to gain access to the northern room, fight a very angry corgi (alien sentinel) and feed the generator with the plasma sheets. Once powered, the room has an autolathe, a telecomms array, and suit storage containing a full syndicate suit.
![Syndicakesv1](https://user-images.githubusercontent.com/10063083/91220846-14f6ae00-e71d-11ea-803e-ed99b66372d9.png)

**debris1**:

![debris1v1](https://user-images.githubusercontent.com/10063083/91221390-df9e9000-e71d-11ea-9316-a51e484d75eb.png)
Loot:
- Random toolbox
- Random tool x2
- Metal
- Rods

**debris2**:
![debris2v1](https://user-images.githubusercontent.com/10063083/91221433-edecac00-e71d-11ea-9629-fac3374ddf9a.png)
Loot (space):
- Biosuit helmet
- Biosuit
- Large beaker
- Metal
- Rods
Inside (vault zone):
- Bluespace beaker
- Bananium sheets x50
- Refined bluespace crystal x10
- DNA injector (telekinesis)

**debris3**:
![debris3v1](https://user-images.githubusercontent.com/10063083/91221478-fd6bf500-e71d-11ea-8231-6d0f69164092.png)
Loot:
- Variety pills bottle
- Arcade machine board
- Random tool x2
- Random official poster
- Random contraband poster
- Glass shards
- Metal
- Rods

**maze**:
mazeA:
![mazeAv1](https://user-images.githubusercontent.com/10063083/91221489-0230a900-e71e-11ea-87a4-b4221e693c78.png)

mazeB:
![mazeBv1](https://user-images.githubusercontent.com/10063083/91221499-05c43000-e71e-11ea-99bc-071e7871ede3.png)

mazeC:
![mazeCv1](https://user-images.githubusercontent.com/10063083/91221755-68b5c700-e71e-11ea-9cec-c9d8fba9e3b0.png)

Loot:
- Anomaly core
- Plasma, diamond, gold, mime and mythril coins

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2020-08-26 02:28 UTC, ZomgPonies commented
Mazes would work better as gateway destinations due to the fact they take a whole z-level and are only accessible from one side.

2020-08-26 02:39 UTC, SabreML commented
To fix the map compilation issue, run `Prepare Maps.bat` with the changes already in, then `mapmerge.bat` on the added ruins. The Mapmerge tool needs a 'before' file to reference, so this just tricks it into working.

2020-08-26 02:57 UTC, taukausanake commented
Wow those mazes. Yeah, they would definitely go better as away missions but the problem with that is they can be traced, ruins or missions, and cheesed easily. I barely see any difference between the images provided but that could work slightly with confusing the players with them. They also look pretty cubical, at least half of the map, so you could probably work it out in sections. Not well designed in my opinion

2020-08-26 03:02 UTC, Kyep commented
Factory/debris1/debris2 are fine.
Debris3: what's in the variety pillbottle?
Mazes: might be better as a big gateway mission. Also, how do you stop people just welding through the walls?

2020-08-26 08:53 UTC, AffectedArc07 commented
Im really not sold on the whole maze ones. If they are pre-generated each time, someone will just draw the line in the map editor and figure it out. It also feels really out of place in space since its just a square, not an asteroid or anything. Other two seem like good concepts though.

2020-08-26 10:13 UTC, Kyep commented
AA is right. Static mazes aren't really viable. People will memorize the solutions, or have the maps up on a second monitor. Probably best to axe the mazes completely from this PR.

2020-08-26 11:52 UTC, Nazsgull commented
Axing the mazes, probably will add another thing to replace them, something not that massive

2020-08-26 12:46 UTC, Nazsgull commented
> To fix the map compilation issue, run `Prepare Maps.bat` with the changes already in, then `mapmerge.bat` on the added ruins. The Mapmerge tool needs a 'before' file to reference, so this just tricks it into working.
> 
> Edit: Also, you seem to have a loose map file, `enygma.dmm` is in the main directory.

What do you mean with "before file"?

2020-08-26 14:55 UTC, SabreML commented
> What do you mean with "before file"?

`Prepare Maps.bat` makes a backup of all the map files, and `mapmerge.bat` looks for changes between the 'before' and 'after' versions, and tidies up the code around them.
That way, if you're just editing one item, it only changes the part of the file with said item in it.
Saving the map through DM remakes the entire file, which makes Travis unhappy.

Since you're adding new maps, there's no 'before' file to reference from.
So,
 1. Run `Prepare Maps.bat` on the branch with the new ruins, this'll make a copy of the files to reference from later.

 2. Run `mapmerge.bat` and select the new files.
It'll look for changes between the 'before' and 'after' states, find none, and tidy the code up for you. Which sould fix the travis issue.

2020-08-26 18:02 UTC, AffectedArc07 commented
```
_maps/map_files/RandomRuins/SpaceRuins/debris1.dmm
_maps/map_files/RandomRuins/SpaceRuins/debris2.dmm
_maps/map_files/RandomRuins/SpaceRuins/debris3.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeA.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeB.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeC.dmm
```
This can be fixed with `tools/mapmerge2/dmm2tgm.bat`

```
loading ./map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm:389:error: bad type or variable: corgiGibber
_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm:389:error: expected )
Failed to load map file /home/travis/build/ParadiseSS13/Paradise/_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm.
```
This is likely an issue with var settings

2020-08-26 18:53 UTC, SabreML requested changes
The SMES in the Syndicakes Factory doesn't get power from the generator in the current configuration:
![Capture1](https://user-images.githubusercontent.com/57483089/91344541-f86a7c80-e7d5-11ea-8367-57b8ad9faba5.PNG)

The terminal is the power input, so it'd work better like this:
![Capture](https://user-images.githubusercontent.com/57483089/91344552-faccd680-e7d5-11ea-892f-c9623a9077cc.PNG)

Wires:
![Capture2](https://user-images.githubusercontent.com/57483089/91344526-f4d6f580-e7d5-11ea-9083-6e5e8c78c9bf.PNG)

2020-08-26 18:59 UTC, AffectedArc07 requested changes
Few things

2020-08-26 18:59 UTC, AffectedArc07 commented on code/datums/ruins/space.dm
> +	always_place = FALSE
Default to false

2020-08-26 18:59 UTC, AffectedArc07 commented on code/datums/ruins/space.dm
> +	allow_duplicates = TRUE
Defaults to true

2020-08-26 18:59 UTC, AffectedArc07 commented on _maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
> +	network_id = "STORAGE-RELAY"
Change this ID to something else.

2020-08-26 20:45 UTC, AffectedArc07 commented
```
$ tools/travis/check_grep.sh
_maps/map_files/RandomRuins/SpaceRuins/mazeA.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeB.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeC.dmm
ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!
The command "tools/travis/check_grep.sh" exited with 1.
```
Still fails on maze

2020-08-26 21:21 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	always_place = FALSE
Which one?

2020-08-26 21:24 UTC, AffectedArc07 commented on code/datums/ruins/space.dm
> +	always_place = FALSE
`always_place`

2020-08-26 21:31 UTC, Nazsgull commented on _maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
> +	network_id = "STORAGE-RELAY"
Done

2020-08-26 21:32 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	allow_duplicates = TRUE
Same as above, what do you mean?

2020-08-26 21:37 UTC, AffectedArc07 commented
```
loading ./map_files/RandomRuins/SpaceRuins/mazeC.dmm
_maps/map_files/RandomRuins/SpaceRuins/mazeC.dmm:8:error: bad type or variable: To
_maps/map_files/RandomRuins/SpaceRuins/mazeC.dmm:8:error: expected )
```

2020-08-26 21:39 UTC, Nazsgull commented
Allright, Travis is now less angry (linters do pass yay!) but there's a "To" var messing up mazeC somewhere, I'll look into it tomorrow.

2020-08-31 02:17 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	always_place = FALSE
solved

2020-08-31 02:17 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	allow_duplicates = TRUE
solved

2020-08-31 09:11 UTC, AffectedArc07 commented
CL is malformed, please edit
![image](https://user-images.githubusercontent.com/25063394/91703498-2fdc7e80-eb72-11ea-887d-b3e46c51cf76.png)
:cl:
add: New ruins (a, b, c, etc)
/ :cl:

2020-08-31 09:12 UTC, AffectedArc07 requested changes
Please remove the overrides for `allow_duplicates` and `cost`

2020-08-31 09:12 UTC, AffectedArc07 commented on code/datums/ruins/space.dm
> +	allow_duplicates = TRUE
`allow_duplicates` defaults to `TRUE`

2020-08-31 09:12 UTC, AffectedArc07 commented on code/datums/ruins/space.dm
> +	cost = 1
`cost` defaults to `1`

2020-08-31 14:14 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	allow_duplicates = TRUE
Removed

2020-08-31 14:14 UTC, Nazsgull commented on code/datums/ruins/space.dm
> +	cost = 1
Removed

2020-09-01 16:54 UTC, AffectedArc07 approved these changes
Code side is fine, though ill let a head have a final vote on the maps

2020-09-01 19:45 UTC, Nazsgull commented
> Code side is fine, though ill let a head have a final vote on the maps

Understood

2020-09-02 10:15 UTC, Kyep approved these changes

2020-09-06 10:06 UTC, AffectedArc07 approved these changes

2020-09-06 10:07 UTC, merged