Fixes listening outpost by adding relay
ParadiseSS13/Paradise pull request #14170
Opened 2020-08-28 15:56 UTC by Kyep

## What Does This PR Do
Adds a hidden telecomms relay to the "listening outpost" space ruin.

## Why It's Good For The Game
Without this, the ruin is useless, as its meant to be a listening outpost... but you can't listen if you have no telecomms.

## Images of changes
![dreammaker_dh4gEswH6I](https://user-images.githubusercontent.com/16434066/91587939-f7a52800-e946-11ea-9e77-36f07d0c91fa.png)

## Changelog
:cl: Kyep
fix: fixed listening outpost space ruin not having telecomms.
/:cl:

2020-08-28 15:57 UTC, AffectedArc07 requested changes

2020-08-28 15:57 UTC, AffectedArc07 commented on _maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
>  "Y" = (
Mix of `/area/ruin/powered` and `/area/ruin/unpowered`

2020-08-28 15:58 UTC, Pyrodes commented
cant wait to see this merged

2020-08-28 16:23 UTC, AffectedArc07 approved these changes

2020-08-29 18:44 UTC, AffectedArc07 approved these changes

2020-08-29 18:44 UTC, merged