Fixes T_Scanner visual bug
ParadiseSS13/Paradise pull request #14189
Opened 2020-08-29 23:42 UTC by kugamo

## What Does This PR Do
Things under a floortile that if were revealed by the t_scanner, and that floor tile removed while being revealed, would permanently look as the t_scanner reveals them (half invisible). This PR fixes this issue, so now regardless of when you pull up tiles while t_scannering the underfloor stuff remains SOLID.

## Why It's Good For The Game
Ghost pipes are bad.

## Images of changes
**BEFORE:**
![k4SIBOyBWE](https://user-images.githubusercontent.com/16618648/91647968-20045380-ea27-11ea-862e-11fbdbcf2f65.gif)

**AFTER:**
![G9JDw6Arbm](https://user-images.githubusercontent.com/16618648/91647970-2397da80-ea27-11ea-9905-03dced5a09c7.gif)

## Changelog
:cl:
fix: Fixes T_Scanner visual bug.
/:cl:

2020-08-30 00:11 UTC, kugamo commented
In case the comments on my commits left any doubt, the underfloor objects will appear immediately solid with this fix.

2020-08-30 20:06 UTC, AffectedArc07 requested changes

2020-08-30 20:06 UTC, AffectedArc07 commented on code/game/objects/items/devices/scanners.dm
> +				if(O)		O.alpha = 255
Please multiline this if statement

2020-08-30 20:45 UTC, kugamo commented on code/game/objects/items/devices/scanners.dm
> +				if(O)		O.alpha = 255
yes ok.

2020-08-31 15:42 UTC, AffectedArc07 approved these changes

2020-08-31 15:42 UTC, merged