Adds the ability for the chaplain to change their null rod mid round
ParadiseSS13/Paradise pull request #14206
Opened 2020-09-01 06:48 UTC by warior4356

## What Does This PR Do
This PR allows the chaplain to change their null rod after initially selecting it by being in the chapel and "praying" for two minutes.

## Why It's Good For The Game
There are a few null rods that are situationally very useful but seldom selected because they are not as "Cool" as the swords and other "weapons". Specifically the rosary beads in a cult or vampire round. This would give the chaplain the opportunity to change to something more suited to the situation without letting them easily change their equipment.

## Changelog
:cl:
add: Added the ability for the chaplain to change their null rod after praying for two minutes in the chapel
/:cl:

2020-09-01 07:12 UTC, ppi13 commented
Blessed pr, now I can grayscale the clown, bless people from car'sie and slamdunk vampires without having to kill them!

2020-09-01 19:29 UTC, warior4356 commented on code/game/objects/items/weapons/holy_weapons.dm
> +				to_chat(user, "<span class='warning'>You lost your concentration! Try again.</span>")
I did consider that, but it wouldn't be all that friendly to more logic being added to the check, having something like that in the generic else case. If someone ever wanted to add more checks they would have to do what I did anyway.

2020-09-01 20:27 UTC, Kyep requested changes
Yikes.
This is an incredibly huge buff to chaplain.
Vampires/cult found on station? Select prayer beads.
Shadowlings? Select godhand (for burn damage).
Carp everywhere? Carp rod.
Etc.
Not only can you always be using the most powerful nullrod for any given situation, but you can now also change your rod to give you the most powerful advantage no matter what the situation is. No longer do you have to make a choice at the start of the round, or wait a bit and select it later once you know more. Now you can go with a generic choice up-front and then specialize later to counter the exact situation you face.

Chaplains already get a huge variety of powerful nullrods that counter lots of different threats. This would be a VERY large buff to them. Not just for the rarer nullrods, either, but for all of them.

Its not automatically bad, but it is a BIG buff for chaplains.

2020-09-01 22:06 UTC, TheMaveran commented
I personally think the role should be entirely RP focused, its already played too often as an assistant with a free weapon and office, and this change will likely encourage it.

2020-09-02 01:48 UTC, Pennwick commented
More of a minor issue compared to what Kyep brought up but wouldn't this allow dropping of the undropable weapons? If you give yourself a chainsaw hand you ought to be dealing with it all shift.

2020-09-02 03:25 UTC, warior4356 commented
> More of a minor issue compared to what Kyep brought up but wouldn't this allow dropping of the undropable weapons? If you give yourself a chainsaw hand you ought to be dealing with it all shift.

Fun fact, the chainsaw has the same stats as all the other swords.

2020-09-14 11:43 UTC, AffectedArc07 commented
This has a head objection, 2 maintainer objections, and no one in favour from either groups. It removes the need for the "choose wisely" decision on the nullrod, which is a key part of it, not to mention removing the "situational usefulness but otherwise not useful" concept like kyet mentioned.

Closing PR.

2020-09-14 11:43 UTC, closed without merging