Fixes Huge Air Scrubber wrenching bug
ParadiseSS13/Paradise pull request #14226
Opened 2020-09-03 17:51 UTC by kugamo

## What Does This PR Do
This PR fixes a bug that didnt allow Huge Air Scrubbers to be wrenched. A proc in its parent was overriding the logic that determined how wrenches interacted with the device.

## Why It's Good For The Game
Being able to use the huge air scrubbers outside of just the toxins storage room is good, and was the intended design of the objects.

## Images of changes
**Before:**
![jHMqnCY2Vq](https://user-images.githubusercontent.com/16618648/92149757-0dea3280-ede4-11ea-8df9-fd5888a5d615.gif)

**After:**
![38kW8T5fih](https://user-images.githubusercontent.com/16618648/92149784-15114080-ede4-11ea-888e-a0e90990d6c8.gif)

## Changelog
:cl:
fix: Fixes bug preventing wrenching of the Huge Air Scrubbers.
/:cl:

2020-09-03 18:12 UTC, farie82 requested changes

2020-09-03 18:12 UTC, farie82 commented on code/game/machinery/atmoalter/scrubber.dm
> +	if(!I.use_tool(src, user, 0, volume = I.tool_volume))
This one already plays a sound. It's therefore best to place this after the other checks.
`volume = I.tool_volume` says that it should play a sound

2020-09-03 18:12 UTC, farie82 commented on code/game/machinery/atmoalter/scrubber.dm
> +	return
Non required return here

2020-09-03 18:12 UTC, farie82 commented on code/game/machinery/atmoalter/scrubber.dm
> +	playsound(loc, I.usesound, 50, 1)
Can be removed due to the prev comment

2020-09-03 18:12 UTC, farie82 commented on code/game/machinery/atmoalter/scrubber.dm
> +	to_chat(user, "<span class='notice'>You [anchored ? "wrench" : "unwrench"] \the [src].</span>")
`\the` can be removed I believe. Just `[src]` will already put that there

2020-09-04 17:46 UTC, AffectedArc07 approved these changes

2020-09-04 17:46 UTC, merged