Makes CNS rebooter stun on EMP
ParadiseSS13/Paradise pull request #14234
Opened 2020-09-04 18:05 UTC by Qwertytoforty

## What Does This PR Do

This PR makes CNS rebooter stun the user when EMP'D, instead of just being temporarily disabled. 

## Why It's Good For The Game

For the base code of head implants, they stun the user when emp'd. This makes sense, emps and wires in the brain wont end well. Grey translator implants are not included, which makes sense, as making greys get stunned by every emp due to a translator implant is a bit silly. However, the other implant that does not stun the user is... cns. Currently, cns is temporarily disabled when emp'd, but otherwise the host is not affected. This seems a bit silly, as most other implants have a downside to the host when emp'd, not just disabled. More so, a combat implant in your brain when emp'd should be much more dangerous then the clown implant, which does currently stun you when emp'd. Thus, this PR changes the code to make cns stun you AND be disabled temporarily. Now there is a risk to having cns, rather then, its emp'd and disabled temporarily, at no risk to the user.

## Changelog
:cl:
tweak: CNS rebooter now stuns the user on EMP, instead of just being temporarily disabled. 
/:cl:

2020-09-04 18:49 UTC, procdrone commented
Sounds like a reasonable counter to mass produced CNS implanted sec officers.

2020-09-05 23:27 UTC, SteelSlayer approved these changes

2020-09-06 00:33 UTC, farie82 approved these changes

2020-09-08 16:22 UTC, Tokorizo commented
me likey nerf to power-gaming seccies

2020-09-16 19:32 UTC, Kyep approved these changes

2020-09-16 19:33 UTC, Kyep requested changes
Objection.
If you're going to do this, then you need to distinguish between science-printable implants, and CC/ERT/etc versions.

2020-09-16 20:18 UTC, Kyep approved these changes

2020-09-18 14:44 UTC, variableundefined approved these changes

2020-09-18 14:44 UTC, merged