[TGUI] Solar Control
ParadiseSS13/Paradise pull request #14258
Opened 2020-09-07 18:42 UTC by RedWolfie

## What Does This PR Do
This PR replaces Nano with TGUI for the Solar Control. It also refactors solar control a bit. 

## Why It's Good For The Game
Gets rid of nano

## Images of changes

## Changelog
:cl:
add: Added TGUI for Solar Control
/:cl:
![solar-demo1](https://user-images.githubusercontent.com/13683223/92411924-26db4680-f14a-11ea-9172-e150ea8ecde7.png)
![solar-demo2](https://user-images.githubusercontent.com/13683223/92411923-26db4680-f14a-11ea-8fb2-9297a6214d1c.png)
![solar-demo3](https://user-images.githubusercontent.com/13683223/92411920-2642b000-f14a-11ea-8cc3-97f9d330bbe1.png)
![solar-demo4](https://user-images.githubusercontent.com/13683223/92411973-59853f00-f14a-11ea-9501-eb8c0fe54bc9.png)

2020-09-08 00:49 UTC, SteelSlayer commented
Judging from the screenshots, the power progress bar gets completely full at just 15,000 W. But the station's starting solar arrays have the capacity to go up to 90,000, and I think the bar actually has the potential to go up to 200,000 currently. Why does your UI not allow for numbers higher than 15,000?

2020-09-08 07:09 UTC, RedWolfie commented
It depends on the amount of panels. Each panel has a maximum of 1500W. As I connected only 10 panels for testing, it maxes out at 15000

2020-09-08 11:01 UTC, AffectedArc07 requested changes

2020-09-08 14:27 UTC, SteelSlayer commented
@RedWolfie Ah gotcha. That's cool that the max size scales with the amount of power you can have :+1:

2020-09-08 18:14 UTC, RedWolfie commented on code/modules/power/solar.dm
> +	if(TRACKER_TIMED && trackrate) //we're manual tracking. If we set a rotation speed...
fixed

2020-09-15 21:02 UTC, AffectedArc07 approved these changes

2020-09-15 21:26 UTC, merged