Fixes incorrect TS gibbing [WIP]
ParadiseSS13/Paradise pull request #14268
Opened 2020-09-08 23:16 UTC by Kyep

## What Does This PR Do
Attempts to fix an issue where sometimes, terror spiders can gib while being alive, due to Life() being relied upon to always return TRUE if the mob is alive, but apparently it no longer does this, leading to the TS code thinking the spider is dead when it isn't.

NOTE: This PR is WIP and requires more discussion / confirmation with AA before being merged. Don't merge it until we're sure this fix is exactly what we want.
Things we need to confirm:
- That the gibbing is really caused by this, and not caused by people changing TS factions
- That this is really the correct way to fix it, and not, say, changing simple_animal/Life or mob/living/Life (which I'd rather not do without maint confirmation that its the right way)

## Changelog
:cl: Kyep
fix: fixed terrors sometimes wrongly decomposing(gibbing) for no good reason while alive.
/:cl:

2020-09-09 21:14 UTC, farie82 requested changes
Doing an analysis myself as well:
`/mob/living/simple_animal/hostile/Life`:
Can return `FALSE` if the return of the parent was already `FALSE`

`/mob/living/proc/Life`:
can return `FALSE` if `notransform` is `TRUE`. Which I doubt it is
returns `FALSE` when `loc` is null. Same here should not really happen.
returns `null` if a chem qdels the spider.
returns `null` if a virus or anything else in between qdels the spider
returns `null` if `forced_look` is not null and that value is a UID of an atom and that atom is out of view distance. The logic here is ... flawed at best if you ask me. Probably needs some relooking
Will return `TRUE` if the spider is not dead. Else it'll return `null`

Only causes I can see here are:
- The `notransform` causing the issue here. The timestop effect can in theory currently kill the terrors since it sets notransform to TRUE while it's active.
Something with the `view_portal` object can also cause it but I have no clue what this is.
- The `forced_look` if you force look (ctrl shift middle click) on something and that thing gets out of sight.
- `loc` somehow being null. But that would have caused more issues.

Can use this to debug some more. The current proposed solution with the death check should work but there might be some other things you might want to look into as well

2020-09-09 21:14 UTC, farie82 commented on code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
> +	..()
Still needs to be `. = ..()`

2020-09-09 21:14 UTC, farie82 commented on code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
> +	if(QDELETED(src))
Can't ever happen here.

2020-09-11 10:06 UTC, Kyep commented
@farie82 Insight: most of the cases of this bug happening seem to happen in space. I've not been able to reproduce it yet, but that's the best lead we have thus far.

2020-09-11 10:49 UTC, farie82 commented
> @farie82 Insight: most of the cases of this bug happening seem to happen in space. I've not been able to reproduce it yet, but that's the best lead we have thus far.

Do they perhaps die in space and get instantly gibbed upon dying? I can't remember if terrors take pressure/cold damage from space

2020-09-13 05:39 UTC, Kyep commented
Updated.
@farie82 that is possible, but its only a 2% chance per life tick, so unlikely.

2020-09-13 06:58 UTC, farie82 approved these changes

2020-09-15 13:52 UTC, AffectedArc07 approved these changes

2020-09-15 13:52 UTC, merged