Turn off xenobiology camera acceleration
ParadiseSS13/Paradise pull request #14285
Opened 2020-09-12 17:10 UTC by Sinestia

## What Does This PR Do

By default, the eye that the console derives itself from has acceleration turned on, this overrides that default to turn it off. 

## Why It's Good For The Game

Acceleration makes sense for the station AI due to A. the large distance it has to cover and B. most AI interactions (opening doors, bolting, etc.) will involve the use of their mouse, requiring less eye precision.

Xenobiology lacks both of those justifications, the space is small, and it seems pretty common for people to operate it by moving over slimes and clicking on the top buttons. If you do it in that manner, you want precise movement, and that's where acceleration causes unnecessary problems. 

## Changelog
:cl:Froststahr
tweak: Disable default camera acceleration for Xenobiology's Management Console
/:cl:

2020-09-12 20:53 UTC, AffectedArc07 requested changes

2020-09-12 20:53 UTC, AffectedArc07 commented on code/modules/research/xenobiology/xenobio_camera.dm
> +	eyeobj.acceleration = 0
```suggestion
	eyeobj.acceleration = FALSE
```

2020-09-13 14:39 UTC, farie82 approved these changes

2020-09-13 19:59 UTC, Pixelzilla commented
This doesn't seem to really consider the potential impacts of how this would negatively impact those who do choose to expand the console range well outside of its default parameters. It would be terrible trying to actually use the console in that situation due to how large the station is. It isn't difficult to use the console the way that it currently exists and I don't really see it as being a particularly difficult thing to get used to.

2020-09-13 21:11 UTC, AffectedArc07 approved these changes

2020-09-14 00:16 UTC, Kyep approved these changes

2020-09-15 23:36 UTC, merged