Ports TG's topic limiting
ParadiseSS13/Paradise pull request #14330
Opened 2020-09-16 16:49 UTC by AffectedArc07

## What Does This PR Do
This PR ports TG's system for handling topic spam prevention. Our current system only allows 1 topic per tick, which is imperfect to say the least. It even breaks TGUI wires. It also doesnt inform admins of topic spam.

The new system has 2 topic limiter buckets, one which caps at 100 topics per minute, and 10 topics per second respectively.
![image](https://user-images.githubusercontent.com/25063394/93367634-a3ee7600-f844-11ea-8e6e-985e4e9a7615.png)

## Why It's Good For The Game
TGUI wires should work, also our current topic spam system is less than perfect.

## Changelog
:cl: AffectedArc07
fix: Fixed TGUI wires
/:cl:

2020-09-16 19:43 UTC, Kyep approved these changes

2020-09-17 07:41 UTC, farie82 requested changes
Looks good logic wise. Some minor styling things

Also I'm curious if hardcore chemist players would reach the minute limit. Would be fun to find out

2020-09-17 07:41 UTC, farie82 commented on code/modules/client/client procs.dm
> +	var/mtl = 100 // 100 topics per minute
can make this var more verbatim so you don't have to make a comment

2020-09-17 07:41 UTC, farie82 commented on code/modules/client/client defines.dm
> +	var/list/topiclimiter
can you make this snake_case?

2020-09-17 07:41 UTC, farie82 commented on code/modules/client/client procs.dm
> +			to_chat(src, "<span class='danger'>[msg]</span>")
`userdanger` will be even more noticeable for the end user

2020-09-17 07:41 UTC, farie82 commented on code/modules/client/client procs.dm
> +	var/stl = 10 // 10 topics a second
Same here. More verbatim will mean you don't have to write a comment

2020-09-18 16:47 UTC, merged