Gives engi/medical borgs an abductor tool upgrade from the exosuit fabricator
ParadiseSS13/Paradise pull request #14341
Opened 2020-09-16 23:51 UTC by Qwertytoforty

## What Does This PR Do

This PR gives engineering / medical borgs the ability to get an abductor equipment upgrade. This upgrade replaces the tools the borg gets with the equivalent abductor tool, and with the case of medical, replaces the laser scalpel with IMS, due to lack of an abductor laser scalpel. They can be produced in the exosuit fabricator for approximately the price of all the tools if printed for a human.

Also fixes borg upgrades like the diamond drill for mining borg leaving a ghost item slot when upgraded.

## Why It's Good For The Game

This is good for the game as it adds an upgrade to borgs other than security or miner that helps them specifically. It is not something that will happen every round, due to the requirement of abductor 4, which will require either very productive miners with the abductor ruin, traders, or actual abductors.  These tools are not combat oriented, and does not give the security borg the abductor baton either. This does not make borgs stronger then crew in these areas, as they are the exact same tools crew get, for the same price.

## Images of changes

Already in the code, but unused, is the new sprite for the module: 
![image](https://user-images.githubusercontent.com/52090703/93403443-85dd4180-f855-11ea-9680-f258259a88fc.png)

## Changelog
:cl:
add: Allows medical / engineering borgs to get abductor tool upgrades from the exosuit fabricator with a new upgrade.
fix: Fixes modules like diamond drill upgrade for mining borgs having a ghost slot filled with the old drill.
/:cl:

2020-09-17 03:34 UTC, SteelSlayer commented
What happens if the borg loses this upgrade? Do their abductor tools remain?

2020-09-17 05:59 UTC, Aquilar commented
don't give medical module the IMS, use the tier 3 laser scalpel instead.

2020-09-17 07:26 UTC, farie82 requested changes
Tested and works. Resetting the borg works as expected.
Minor nitpick styling wise

I also noticed something odd while testing but it's not due to the PR I believe. The newly added modules were not clickable on the inventory slot. But only on the item itself. After equiping and un-equiping the item it did become clickable. Quite annoying to have to accurately click on an item but yeah. Out of the scope of this PR though

2020-09-17 07:26 UTC, farie82 commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/abductorengi
minor nitpick. Can you make this snake_case? Bit easier to read like that. Same for the other path

2020-09-18 10:59 UTC, farie82 approved these changes

2020-09-18 23:54 UTC, variableundefined approved these changes

2020-09-25 19:29 UTC, Kyep approved these changes

2020-09-25 20:13 UTC, merged