Properly genders Araneus
ParadiseSS13/Paradise pull request #14352
Opened 2020-09-17 17:03 UTC by EmilyFontaine

## What Does This PR Do
This PR properly genders Araneus in the code, as SHE is very often misgendered when referred to in game. 

## Why It's Good For The Game
As mentioned above, Araneus very often gets called a "he" rather than a "she". While this doesn't change anything game-play wise, I think it's time to finally put the discussion about which gender Araneus is to rest. To do so, I'm going to provide some proof that Araneus is actually female. It's pretty simple anatomy. Female spiders generally have larger abdomens, whereas males have smaller abdomens and longer legs. 

![image](https://user-images.githubusercontent.com/26614471/93501746-28f59000-f916-11ea-8faa-1756b6656029.png)
In the image above, we see the guard- and hunter spider variants. Araneus uses the guard spider model, which is seen to have a very large abdomen. Hunter spiders on the other hand, have a smaller abdomen and long, thin legs.

In the image below, we see an image comparing a female spider to a male spider. Notice how the male spider has those little hooks on the ends of it's palps? Looks very similar to the one the hunter spider sprite has, yes? The female ones are straighter and lacks these spiky hooks, as they're used in *REDACTED*. 
![image](https://user-images.githubusercontent.com/26614471/93502020-783bc080-f916-11ea-92f0-7ba6a1df1ae5.png)

With this, I think we can all agree that Araneus is a female and finally put this discussion to rest. Thank you.

## Changelog
:cl:
tweak: Araneus is now female, as she should be
/:cl:

2020-09-17 17:14 UTC, FreeStylaLT commented
This PR isn't the one Paradise needs, but the one it deserves.

2020-09-17 17:17 UTC, AffectedArc07 requested changes

2020-09-17 17:17 UTC, AffectedArc07 commented on code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
> +    gender = FEMALE
```suggestion
	gender = FEMALE
```

2020-09-17 17:23 UTC, AffectedArc07 approved these changes

2020-09-17 19:00 UTC, Kyep approved these changes

2020-09-18 12:40 UTC, Spacemanspark commented
Man that Araneus, he sure is popular with the kids these days.

2020-09-18 22:49 UTC, merged