Changes cryoxadone to check external temp instead of internal temp
ParadiseSS13/Paradise pull request #14440
Opened 2020-09-26 05:04 UTC by warior4356

## What Does This PR Do
Cryoxadone now checks the temperature of the atmosphere or cryo cell around you rather than your body temperature.

## Why It's Good For The Game
The code from dropping or raising your body temp via chems was never designed for cryoxadone pills. It was made to do damage, not to heal. Currently, if you consume a reagent that is at 0 kelvin it drops your body temp by 250 kelvin per chem tick. This system needs to be reworked, but until that happens this PR is a bandaid measure to remove the exploit of 0 kelvin cryoxadone pills.

## Changelog
:cl:
tweak: Cryoxadone checks your external temperature instead of your internal temperature.
/:cl:

2020-09-26 05:07 UTC, Mitchs98 commented
If this affects ghetto cryo showers, which is definitely something I don't want it to effect as it's fairly niche, then I'd rather not.

I'm not sure which a cold shower effects. Otherwise if it doesn't I'm fine with it.

2020-09-26 09:29 UTC, Cocacolagua commented
I do like the idea of nerfing cryoxpills, but i am unsure if this is the way to go about it

2020-09-27 01:06 UTC, Pennwick commented
> 
> 
> I do like the idea of nerfing cryoxpills, but i am unsure if this is the way to go about it

Some other alternatives would be making it so hot/cold items don't chill your body that much unless there is a lot of them. The fact that 5u is more than enough to bring you to cryo temps is a little weird.

Also weird that pills retain their near absolute zero temp when just sitting in your pocket. I thought chems were supposed to drift toward ambient temperature unless in an insulated container? Not sure if it just happens very slowly or if its not happening to pills at all.

2020-09-29 15:39 UTC, farie82 requested changes

2020-09-29 15:39 UTC, farie82 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		var/turf/T = M.loc
`loc` can be a locker as well here. You'd want to use `get_turf(M)` here instead

2020-10-01 21:09 UTC, farie82 approved these changes
Code will work

2020-10-04 02:49 UTC, Necaladun commented
I'd prefer to see a bigger more holistic fix, but sometimes you need to use a bandaid. 

Would like a bit of time to wait for people to think up what else this may affect. If shower-ghetto-cryo is hurt by this...well, not really bothered by a feature that is barely ever used or known about.

2020-10-04 17:19 UTC, AffectedArc07 approved these changes
I hear the chemists reeeing in the distance

2020-10-04 17:19 UTC, merged