Codebase Cleanup - 2020-09-27
ParadiseSS13/Paradise pull request #14472
Opened 2020-09-27 16:17 UTC by AffectedArc07

## What Does This PR Do
Cleans up some old pieces of the codebase. Everything done in this PR is listed below in bulk, to save diff reading

- Removed DLLSocket from the bay12 era before Paradise even existed
- Repathed `/obj/vox/win_button` to `/obj/machinery/vox_win_button` (MAP EDIT). This is to remove an almost top-level path which shouldnt exist
- Renamed a bunch of filenames which had spaces to remove their spaces (Spaces in filenames are bad)
- Tweaked stack crafting so it uses `obj/result` instead of `/obj/result`, which caused the game to have a literal definition for `/obj/result` ingame
- Removed `/obj/crate` and `/obj/crate/fireworks`. These dont exist ingame, dont work, and have not been touched in **7 years**
- Removed POS (Its not used anywhere, defines a `/line_item` top level path which shouldnt exist, and was a half-implemented port that was never finished
- Removes `UnstandardnessTestForDM` from tools. This has been replaced with `DreamChecker`. 
- Moves `Runtime Condenser` to `RuntimeCondenser` since spaces in filenames are a pain, especially with things which are shell automated, such as the runtime condenser 

## Why It's Good For The Game
No ingame change, purely a github/maintenence improvement

## Changelog
No ingame change

2020-09-27 16:19 UTC, AffectedArc07 commented on code/game/area/dynamic_areas.dm
> -/area/dynamic // Do not use.
No idea why this changed line endings

2020-09-27 17:57 UTC, AffectedArc07 commented on _maps/map_files/MetaStation/z2.dmm
> -/obj/vox/win_button,
These are the only map edits in the entire thing

2020-09-28 00:27 UTC, Kyep approved these changes

2020-10-07 18:57 UTC, farie82 requested changes
Minor nitpick

2020-10-07 18:57 UTC, farie82 commented on code/game/objects/items/stacks/stack_recipe.dm
> +/datum/stack_recipe/proc/post_build(var/obj/item/stack/S, obj/result)
Can you remove the other `var/X`s from this file as well? Atleast for the procs you touched

2020-10-08 08:47 UTC, farie82 approved these changes

2020-10-15 17:22 UTC, merged