Add door speed changes to remotes
ParadiseSS13/Paradise pull request #14495
Opened 2020-09-30 18:25 UTC by FlattestGuitar

:cl: Flatty
add: Door remotes can now be used to change the speed of airlocks.
:cl:

2020-09-30 18:31 UTC, farie82 requested changes

2020-09-30 18:31 UTC, farie82 commented on code/game/objects/items/control_wand.dm
> +#define WAND_SPEED "Change Door Speed"
"Change Closing Speed"?

2020-09-30 18:31 UTC, farie82 commented on code/game/objects/items/control_wand.dm
> +				to_chat(user, "Now in [D.normalspeed ? "normal" : "fast"] mode.")
Needs spans here. notice will do as class.
Text also needs some more flavor. "Now in X mode" is a bit flavorless if you know what I mean

2020-09-30 21:17 UTC, farie82 approved these changes

2020-09-30 23:37 UTC, variableundefined approved these changes
Approved for design

2020-09-30 23:42 UTC, Kyep approved these changes

2020-10-01 11:32 UTC, AffectedArc07 approved these changes
Stop bugging me for hacktoberfest

2020-10-01 11:32 UTC, merged