Sniper Holster Fix
ParadiseSS13/Paradise pull request #14501
Opened 2020-10-01 18:54 UTC by DevL-Whats-a-jpg

## What Does This PR Do
Stops you from placing a sniper in your holster, because you shouldnt be able to put a 60 inch gun in your iphone sized pocket under your armpit.

## Why It's Good For The Game
Just no.
## Changelog
:cl:
add: Made isHandgun() return 0 because again, a 60 inch sniper is NOT a handgun.
/:cl:

2020-10-01 18:55 UTC, AffectedArc07 requested changes

2020-10-01 18:55 UTC, AffectedArc07 commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	return 0 // False
```suggestion
	return FALSE
```

2020-10-01 18:56 UTC, SabreML commented
You could probably fix #14048 too while you're at it

2020-10-01 20:09 UTC, farie82 commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	return FALSE // False
Comment can be removed

2020-10-02 08:31 UTC, farie82 approved these changes

2020-10-02 09:46 UTC, AffectedArc07 commented
Looking deeper in the code
```dm
/obj/item/gun/projectile/automatic/isHandgun()
	return 0

```
This should already not be possible

Requesting you do sort the LWAP out, as well as other guns which shouldnt class as handguns

2020-10-02 20:34 UTC, Qwertytoforty commented
You guys are confusing the physical projectile sniper, and the LWAP sniper. The physical projectile sniper already can not be holstered, but the _energy sniper_ can be. You are changing the wrong thing

2020-10-02 20:45 UTC, AffectedArc07 commented
> You guys are confusing the physical projectile sniper, and the LWAP sniper. The physical projectile sniper already can not be holstered, but the _energy sniper_ can be. You are changing the wrong thing

I am aware the regular sniper cant be holstered, hence why I pasted that piece of code. We already have the code I pasted in the codebase, hence why I asked him to do it for the LWAP.

2020-10-09 15:32 UTC, AffectedArc07 commented
Please update this within 7 days, or it will be closed.

2020-10-09 18:56 UTC, DevL-Whats-a-jpg commented
> Please update this within 7 days, or it will be closed.

Going back to my dads today so i should be able to finish this.

2020-10-10 19:39 UTC, AffectedArc07 commented
Requesting you edit your changelog to say something like "You can no longer holster LWAP sniper rifles.", to make it more clear and to the point for the ingame population

2020-10-15 12:25 UTC, variableundefined commented
Taking the liberty of doing the changelog change myself in the interest of making this simple PR goes by faster.

2020-10-15 12:25 UTC, merged