Reduce Water Stun/Weaken Time
ParadiseSS13/Paradise pull request #14514
Opened 2020-10-02 18:31 UTC by matttheficus

## What Does This PR Do
Reduces the stun time and weaken time of TURF_WET_WATER by half.

## Why It's Good For The Game
Water is basically as good as slapping somebody with a baton in some cases, which logically makes absolutely zero sense. Should it knock you over and make you drop items? Yes. But should it knock you down for 6-8 seconds? No.

While this also nerfs the usage of water tanks by simplemobs (such as Terrors) there REALLY shouldnt be a reason that they can use a free 8x8 tile stun for 6-8 seconds.

## Changelog
:cl:
tweak: tweaked stun and weaken amounts in TURF_WET_WATER
/:cl:

2020-10-02 18:57 UTC, Mitchs98 commented
You should include specifically in the changelog how much you tweaked/changed the values imo. Otherwise though, nice change.

2020-10-02 18:58 UTC, Dashsora commented
This is FOR SURE a good change - but there's one thing i'd like to propose : What if all slips displace you one tile, and lube/acid naners three tiles, for the short stun duration, BUT if you hit an object like a wall/ closed locker/machine/table/etc, you get stunned for longer ?

It could check how many tiles you should've displaced, and how many tiles you actually displaced, and then handle the stun accordingly (More remaining tiles = longer stun, so if you slip on lube and immediately bonk your head on a wall you get stunned for longer than if it's on the end of the slide, water potential bonk stun would always be the same since it displaces only one tile)

2020-10-02 19:10 UTC, matttheficus commented
> You should include specifically in the changelog how much you tweaked/changed the values imo. Otherwise though, nice change.

fixed

2020-10-04 02:07 UTC, Necaladun commented
I'll miss being able to robust sec with just a bucket of water in perma but this is a needed change imo.

2020-10-06 03:57 UTC, MRgaty commented
I think this will increment the amount of people that use space lube.

2020-10-09 13:23 UTC, matttheficus commented
> I'll miss being able to robust sec with just a bucket of water in perma but this is a needed change imo.

you still CAN, it just wont stun for as long, so make sure to yoink their dropped weapons and stun them ASAP!

2020-10-11 09:02 UTC, Kyep approved these changes
This doesn't need my approval, as it already has a head voting for it.
Just for the record though, I approve too.

2020-10-15 00:56 UTC, variableundefined requested changes
Since this is an important variable that might be tweaked in the future, do you mind making a constant say, called 

#def WATER_STUN_TIME 
and 
#def WATER_WEAKEN TIME

And refer to that constant in the lines, and then #undef them at the end?

2020-10-15 12:30 UTC, matttheficus commented
> Since this is an important variable that might be tweaked in the future, do you mind making a constant say, called
> 
> #def WATER_STUN_TIME
> and
> #def WATER_WEAKEN TIME
> 
> And refer to that constant in the lines, and then #undef them at the end?

Is it worth separating the values twice? The slip effect (at least the one changed here) is already only being applied to TURF_WET_WATER, implying that it only changes

2020-10-15 12:58 UTC, variableundefined commented
@matttheficus 
Yes, magic number should be avoided. 

While this number is not reused anywhere, a meaningful name is going to be helpful for a maintainer, future contributor or you in the future to recall the **intent** behind the code. It also makes it easier for a layman to understand what is going on. 

If, for some reason I want to change the code for stun, I go into this file and I can see WATER_STUN_TIME in all caps at the top. I can search for the variable and quickly find the code responsible and debug it. 

Without it, I will have to search thoroughly for the code in this file that affects the water slip before I know what to do, and if a subtle typo is made, I will have a hard time understanding whether that is the intent in the first place.

2020-10-17 17:27 UTC, variableundefined commented
@matttheficus 
Please enact requested changes within 4 days

2020-10-17 19:41 UTC, matttheficus commented
life slammed stuff to a halt, changes made (hopefully properly, havent worked with defines at all with DM, used to constants instead)

2020-10-21 04:23 UTC, variableundefined approved these changes
@matttheficus You did it correctly

2020-10-21 04:24 UTC, merged