Nerfs the bluespace wormhole projector
ParadiseSS13/Paradise pull request #14535
Opened 2020-10-05 01:01 UTC by Qwertytoforty

## What Does This PR Do

Nerfs the bluespace wormhole projector (portal gun) by giving it a 1 second fire delay, and 10 shots. However, allows it to self charge one shot every 10 seconds.

## Why It's Good For The Game

The bluespace wormhole is a fun tool. A nice portal reference, can be used cleverly. The issue is, people have been abusing it heavily in 2 ways. One: Due to its infinite ammo and low fire rate, you can spam fire it everywhere without it ever running out. This is problematic, as you can not reach a person spam fireing this gun, as anyone hit by one of its shots is randomly teleported in a 6 tile radius, often into another room, or space nearby, preventing them from reaching the person with a gun. 
Two: If you enter the portal, you get teleported to the other portal. Simple. However, if you have a bag of holding, you get teleported a large distance away from where you should end up. This may seem like a downside, but it is not. If you willingly enter a portal while security is chasing you, you will teleport a large distance away from security, with them having no way of telling where you have gone, and no way to follow, even if they have a bag of holding on as well, they go somewhere else.

This PR attempts to fix this, by lowering fire rate and giving it a power cause, so it can not be spammed, and if you do want to use this in combat, you have to aim carefully.
## Images of changes

## Changelog
:cl:
tweak: Gave the bluespace wormhole projector a 1 second fire delay, and changes it from infinite ammo to 10 shots, with a 1 shot per second recharge.
/:cl:

2020-10-05 08:13 UTC, AffectedArc07 commented
I recommend rebasing to get rid of that nanomap commit, and as a practice, always start a branch from `ParadiseSS13/master`, not your fork master.

2020-10-11 08:41 UTC, Kyep approved these changes

2020-10-11 09:14 UTC, AffectedArc07 requested changes

2020-10-11 09:14 UTC, AffectedArc07 commented on code/modules/projectiles/guns/energy/special.dm
> +	selfcharge = 1
```suggestion
	selfcharge = TRUE
```

2020-10-11 13:15 UTC, AffectedArc07 approved these changes

2020-10-11 13:15 UTC, merged