Craftable syndicate boxes
ParadiseSS13/Paradise pull request #14550
Opened 2020-10-06 12:35 UTC by Cocacolagua

## What Does This PR Do
You can now craft black and red boxes with one cardboard.
Also changes spelling-checks some other boxes.

## Why It's Good For The Game
As we all know, syndicate fashion is just better than nanotrasen fashion, not allowing us to craft these OUTSTANDING boxes is an outrage, we deserve better.
Also spellchecking = good.

## Changelog
:cl:
add: Black and red boxes can now be crafted with cardboard.
spellcheck: Added the words "box" on mouse traps, light bulbs and light tubes' cardboard crafting option.
/:cl:

2020-10-06 20:38 UTC, McRamon commented
Can you also add ability to rename boxes like papers, so an empty syndie box is no longer a meta reason to suspect or arrest someone (also nice prank material)

2020-10-06 23:00 UTC, Cocacolagua commented
done, clown is getting some new prank arsenal

2020-10-11 08:47 UTC, Kyep requested changes
I dislike this.
I predict it'll get used a lot to make false syndie boxes to annoy/misdirect sec.
I also don't like the idea of adding verbs for objects - make it a hud button if you really must.

2020-10-13 12:24 UTC, MRgaty commented
I agree that this will very much be used to "prank" and divert sec's attention cuz now theres a random guy with a syndicate box called "Holoparasite" or something like that.

2020-10-15 15:14 UTC, variableundefined reviewed
Objection on the same ground as Kyet

2020-10-15 15:17 UTC, AffectedArc07 commented
I really dont like the idea of regular crew being able to make syndicate boxes, since the amount of distractions it will create for security is ludicrous. Please revert that part of the PR, but we will gladly take the spelling fixes.

2020-10-15 16:22 UTC, variableundefined commented
Closing due to two maintainers objection

2020-10-15 16:22 UTC, closed without merging

2020-10-16 18:35 UTC, kugamo commented
This could be done in a better way: the way clown boxes are made. Using the appropriate stamp! Since theres a chance a chameleon stamp spawns in maint, theres a small chance you would have the ability to make it a syndie stamp and then turn boxes into syndie boxes with it.