Gives golem shuttle always a valid destination
ParadiseSS13/Paradise pull request #14573
Opened 2020-10-09 23:43 UTC by TDSSS

## What Does This PR Do
The free golem shuttle used to have 2 destinations (besides its origin on lavaland). z5, near a medium-sized asteroid, and z6, near the old USSP station. With the randomisation of space z levels, the z5 destination was removed, while the USSP base was turned into a fairly rare spawn that is not guaranteed. The result of this was that sometimes, the only valid destination for the golem shuttle didn't spawn.
Golems ended up buying the circuitboard but being unable to go anywhere, with only a very unhelpful 'shuttle locked'.

This PR adds a new, guaranteed space ruin. It consists of a small handful of asteroids that can be mined for some minerals and a docking port for the golem shuttle. This allows them to go to space and start space exploration from there.

fixes #13844

## Why It's Good For The Game
Golems always get _something_ for their effort and can go to space, from where they can go on to explore and look for other ruins.

## Images of changes

## Changelog
:cl:
fix: The Free Golem shuttle should now always have at least one valid destination.
/:cl:

2020-10-10 08:00 UTC, AffectedArc07 requested changes

2020-10-10 08:00 UTC, AffectedArc07 commented on code/modules/shuttle/shuttle.dm
> +	possible_destinations = "freegolem_lavaland;freegolem_space;freegolem_z6"
```suggestion
	possible_destinations = "freegolem_lavaland;freegolem_space;freegolem_ussp"
```

If youre going to change this, also update `_maps\map_files\RandomRuins\SpaceRuins\ussp.dmm` to change `freegolem_z6` to `freegolem_ussp`

2020-10-11 08:55 UTC, Kyep approved these changes

2020-10-11 09:05 UTC, AffectedArc07 approved these changes

2020-10-11 09:05 UTC, merged

2020-10-11 09:10 UTC, Kyep commented
@TDSSS Please add this to example/spaceRuinBlacklist.txt in your next PR (it should be there, even commented out).