Make conveyor belts cinematic
ParadiseSS13/Paradise pull request #14655
Opened 2020-10-19 03:37 UTC by moxian

## What Does This PR Do
Makes it possible to slow down conveyor belts up to 50x, with a multitool.

## Why It's Good For The Game
Sushi belts become usable, you can actually grab food from them under no pressure.

## Images of changes
Left to right: default speed (same as live), 5x slow, 20x slower.
![xvxcYXMpNi](https://user-images.githubusercontent.com/7831163/96398785-3a9fb100-11bc-11eb-9770-c2fe1413c85f.gif)

TGUI Menu:
![XiSIOcGKrW](https://user-images.githubusercontent.com/7831163/96398816-4ab79080-11bc-11eb-8892-0515683f728b.png)

## Changelog
:cl:
tweak: Conveyor belts can now be slowed by using multitool on the switch.
/:cl:

2020-10-19 03:50 UTC, moxian commented
In the interest of transparency, I should note that there is a minor issue: if you're using extremely low speeds, it takes a while (specifically - the time it takes for the item to travel one tile) for the item to start moving. See the gif:
![xort0lOk9H](https://user-images.githubusercontent.com/7831163/96399410-c49c4980-11bd-11eb-93a2-e6473482f0fd.gif)

This was the reason for limiting the speed to only 50x. Might be a good idea to reduce this further to something like 25x. Although I'd argue that if you're using that big of a slowdown, you have a reason to, and can live with the minor visual discrepancy.

2020-10-19 04:18 UTC, Carthusia commented
As someone who will be using this for sushi bars, I can live with it as the conveyor will be under tables, and thus nearly invisible

2020-10-19 07:49 UTC, AffectedArc07 requested changes
First pass

2020-10-19 07:49 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/ConveyorSwitch.js
> +            <LabeledList.Item label="lever position">
```suggestion
            <LabeledList.Item label="Lever position">
```

2020-10-19 07:49 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/ConveyorSwitch.js
> +            <LabeledList.Item label="allow reverse">
```suggestion
            <LabeledList.Item label="Allow reverse">
```

2020-10-19 07:49 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/ConveyorSwitch.js
> +            <LabeledList.Item label="slowdown factor">
```suggestion
            <LabeledList.Item label="Slowdown factor">
```

2020-10-19 07:49 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/ConveyorSwitch.js
> +              <Flex >
```suggestion
              <Flex>
```

2020-10-19 13:25 UTC, Cocacolagua commented
how does this look on mobs?

2020-10-19 21:54 UTC, Kyep approved these changes

2020-10-19 21:56 UTC, SteelSlayer commented
I'd be interested in seeing a profile of the conveyor pushing procs that has your new logic, compared to what we currently use.

2020-10-19 23:43 UTC, Kiyahitayika commented
Conveyer belts are barely used currently, this PR will make them much more worthwhile.

2020-10-20 03:51 UTC, moxian commented
> First pass

Thanks, addressed.

> how does this look on mobs?

Same as on items, with the same caveat that on high slowdown it takes a bit to start moving. The gifs below are on 5x:
![hXQfpVWDdJ](https://user-images.githubusercontent.com/7831163/96537292-6a66bb80-1285-11eb-8b37-94e53f075694.gif)
![aHZcqXnZI0](https://user-images.githubusercontent.com/7831163/96537300-6dfa4280-1285-11eb-98b6-48d9ff1c8677.gif)

> I'd be interested in seeing a profile of the conveyor pushing procs that has your new logic, compared to what we currently use.

I honestly don't know how to get one. But honestly, I don't see how it would be much different from what we have today. Compared to live I do now calculate the `loc.contents - affecting` set, but it's `O(len(loc.contents))` complexity anyway, same as `for(var/atom/movable/AM in loc.contents)` on the very next line.
But for slow belts I do now spawn a bit less callbacks. Though that's only because items get moved less (over the same time frame).

2020-10-21 01:31 UTC, SteelSlayer commented
> I honestly don't know how to get one. But honestly, I don't see how it would be much different from what we have today. Compared to live I do now calculate the loc.contents - affecting set, but it's O(len(loc.contents)) complexity anyway, same as for(var/atom/movable/AM in loc.contents) on the very next line.
But for slow belts I do now spawn a bit less callbacks. Though that's only because items get moved less (over the same time frame).

You're right, I ran a short test and profiled your changes vs master, having the belts run at their normal speeds. The difference was extremely minimal, and nothing to fuss over so :+1:

2020-10-21 22:23 UTC, variableundefined approved these changes

2020-10-21 23:46 UTC, procdrone commented
Will you run at standard speed on top of a slow conveyor if you try to move on your own?

PS. What about reverse only position for levers?

2020-10-22 02:15 UTC, moxian commented
> Will you run at standard speed on top of a slow conveyor if you try to move on your own?

You will be slightly faster/slightly slower (depending on your heading), but not noticeably so.
Compare:
![20201022-021257-oxqDxaOMp1](https://user-images.githubusercontent.com/7831163/96814124-379aff80-140c-11eb-8280-96f1750cf08e.gif)
![20201022-021336-gUUiRKJGE3](https://user-images.githubusercontent.com/7831163/96814168-3a95f000-140c-11eb-9d87-e4f4a10f3fd2.gif)
![20201022-021501-hcuPxlXnGp](https://user-images.githubusercontent.com/7831163/96814749-6618da80-140c-11eb-9e1e-23029e80c34a.gif)


> PS. What about reverse only position for levers?

Currently on live attacking the lever with a multitool switches it between one-way, and two-way.
In two-way (default):
- toggle to start the belt moving items in the direction of the arrows
- toggle again to stop
- toggle once more to make it go the opposite direction
- toggle finally to stop again
- repeat
In one-way:
- toggle to start the belt moving items in the direction of the arrows
- toggle to stop
- repeat
This PR simply preserves this functionality.

2020-10-25 03:19 UTC, merged