Command amplification on telecomms no longer allows for empty messages (Now with 99% less sprites)
ParadiseSS13/Paradise pull request #14752
Opened 2020-10-27 16:50 UTC by Adrer

## What Does This PR Do
When you try to speak over radio as a member of command while silenced by mute sting/slingglare/chems/etc. you will no longer broadcast an empty message like `[Common] [Captain] Praxis Chailer says, ""`

fixes: #14133

## Why It's Good For The Game
Makes muting abilities less useless against department heads.

## Changelog
:cl:
fix: Silenced department head radio messages are no longer broadcast
/:cl:

2020-10-27 17:02 UTC, farie82 approved these changes

2020-10-27 17:28 UTC, dearmochi approved these changes

2020-10-27 17:36 UTC, AffectedArc07 requested changes

2020-10-27 17:36 UTC, AffectedArc07 commented on code/game/machinery/tcomms/nttc.dm
> +				if(S.message != "")
```suggestion
				if(S.message)
```
This is cleaner

2020-10-27 20:36 UTC, Kiyahitayika commented
Fix that meta!

2020-10-28 15:42 UTC, variableundefined approved these changes

2020-10-28 15:42 UTC, merged