Bloodcrawling now has a blood-boiling animation
ParadiseSS13/Paradise pull request #14792
Opened 2020-10-30 13:54 UTC by Cocacolagua

## What Does This PR Do
Adds a blood sparkles animation to a blood turf when a mob is bloodcrawling out of it.
(This is a draft because i'm trying to figure out how to colour the animation depending on the blood colour)

## Why It's Good For The Game
The biggest reason why slaughter demons are considered "overpowered" is because the crew doesn't really know which blood tile they are coming from, which doesn't allow them to prepare and usually ends with one of them dead.
This change forces the demon to try different strategies, rather than the one that makes them basically unkillable.

## Images of changes
![2aw0Mt9m1q](https://user-images.githubusercontent.com/48032385/97713078-1dad8c80-1a9e-11eb-9e61-653832a83da3.gif)

## Changelog
:cl:
add: Bloodcrawling out of blood now has an animation.
/:cl:

2020-10-30 13:57 UTC, AffectedArc07 commented
![image](https://user-images.githubusercontent.com/25063394/97713450-c6b4b100-1ab7-11eb-8089-d017e04a8a38.png)
Im going to request you do, because red EMP sparkles do not suit this *at all*

2020-10-30 13:57 UTC, Cocacolagua commented
fair enough

2020-10-30 13:58 UTC, Spacemanspark commented
Initially, before looking at the gif I thought this left a trail of sparkles whenever they moved. I was about to cry.

This seems... fine, though.

2020-10-30 14:07 UTC, farie82 requested changes

2020-10-30 14:07 UTC, farie82 commented on code/game/gamemodes/miniantags/slaughter/bloodcrawl.dm
>  		return
```suggestion
		qdel(uniquebloodcrawl)
		return
```
Currently the effect will stay even if the demon cancels the phasing or when the blood gets removed.

2020-10-30 14:07 UTC, farie82 commented on code/game/gamemodes/miniantags/slaughter/bloodcrawl.dm
> +	var/obj/effect/temp_visual/uniquebloodcrawl = new /obj/effect/temp_visual/bloodcrawl(B.loc)
```suggestion
	var/obj/effect/temp_visual/bloodcrawl/uniquebloodcrawl = new(B.loc)
```

2020-10-30 21:20 UTC, Kiyahitayika commented
Thank you. The worst is the blood under the Operating Table. One time, I made an incision on a patient, blood dripped, _oof_. All of a sudden, I'm on the floor, unconscious patient being dragged around for more blood. I'm pretty sure I AHELPed because I was so spooked and was like "WHAT! WHERE DID IT COME FROM! TH-TH-THIS IS POWERGAMING! REEE!" (spoiler: it wasn't and it's not) 😄 I would be concerned about giving people "too much" of a head's up, but the message to users in range/view of the blood spot is there for a reason. I definitely appreciate this!

2020-11-01 10:04 UTC, AffectedArc07 requested changes
![image](https://user-images.githubusercontent.com/25063394/97800028-9f7df100-1c29-11eb-9518-6147ffd7fb71.png)
Holding an objection until this sprite is changed to something which actually represents bubbling or something else, atleast something other than a reskinned EMP sparkle.

2020-11-01 16:37 UTC, farie82 approved these changes

2020-12-15 13:45 UTC, Cocacolagua commented
Closing this since i can’t make a good sprite for blood boiling, anyone’s free to remake this if they have one though

2020-12-15 13:45 UTC, closed without merging