[TGUI] Convert ATM to TGUI
ParadiseSS13/Paradise pull request #14799
Opened 2020-10-31 18:25 UTC by variableundefined

## What Does This PR Do

Convert over ATM to TGUI interfaces. Also one minor typo fix in the Account Uplink terminal, and added dollar sign to the transaction log. 

**There is one functional change in this PR:**
- All PIN number are standardized to 6 digit instead of 4 digit, and uses the full range of 6 digit number instead of only up to 111111, which is plain weird.

Transaction log code wholeheartedly copy-pasted from the Accounts Uplink.

## Why It's Good For The Game

## Images of changes

**New:** 
![image](https://user-images.githubusercontent.com/40092670/97786828-a141a900-1b84-11eb-8c2d-06b9610575d4.png)
![image](https://user-images.githubusercontent.com/40092670/97786830-a3a40300-1b84-11eb-9259-9b477a07365e.png)
![image](https://user-images.githubusercontent.com/40092670/97786832-a6065d00-1b84-11eb-96dc-bbd06f11cfa5.png)
![image](https://user-images.githubusercontent.com/40092670/97786835-a9014d80-1b84-11eb-9df4-ff14a08cea3a.png)
![image](https://user-images.githubusercontent.com/40092670/97786836-ab63a780-1b84-11eb-8d9a-b885e5ebf24c.png)
**Old:** 
![image](https://user-images.githubusercontent.com/40092670/97786846-b9b1c380-1b84-11eb-8c8c-1838ebfec6ad.png)
![image](https://user-images.githubusercontent.com/40092670/97786850-bc141d80-1b84-11eb-9359-6ef2f313955b.png)
![image](https://user-images.githubusercontent.com/40092670/97786853-be767780-1b84-11eb-912c-e571ebc882b3.png)
![image](https://user-images.githubusercontent.com/40092670/97786855-c0403b00-1b84-11eb-96dd-5bafaa5945c1.png)
![image](https://user-images.githubusercontent.com/40092670/97786856-c2a29500-1b84-11eb-8efe-7b51eb540c77.png)

## Changelog
:cl:
tweak: Updated ATM interface to TGUI.
tweak: All PIN number are now six digit.
/:cl:

2020-10-31 18:27 UTC, ppi13 commented
Will this require a test merge?

2020-10-31 18:29 UTC, AffectedArc07 commented
> Will this require a test merge?

No, why would it

2020-10-31 19:26 UTC, AffectedArc07 requested changes

2020-10-31 19:26 UTC, AffectedArc07 commented on code/modules/economy/ATM.dm
>  	user.set_machine(src)
```suggestion

```
TGUI removes the requirement for `set_machine()` (and so does nano, this is just super old code)

2020-10-31 19:26 UTC, AffectedArc07 commented on code/modules/economy/ATM.dm
>  	data["src"] = UID()
```suggestion

```
Not needed anymore

2020-10-31 19:26 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/ATM.js
> +      </Box>
```suggestion
      <Box>
        For all your monetary need!
      </Box>
```

2020-10-31 19:26 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/AccountsUplinkTerminal.js
> +import { Box, Divider, Button, Flex, Icon, Input, LabeledList, NumberInput, Section, Table, Tabs } from '../components';
Any reason for this import?

2020-10-31 19:26 UTC, AffectedArc07 commented on tgui/packages/tgui/interfaces/AccountsUplinkTerminal.js
> +          <LabeledList.Item label="Account Balance">
Technically this is a Bal~~a~~nce change

2020-11-01 14:34 UTC, dearmochi reviewed
A few things

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +								to_chat(usr, "[bicon(src)]<span class='warning'>Incorrect pin/account combination entered, [max_pin_attempts - number_incorrect_tries] attempts remaining.</span>")
```suggestion
								to_chat(usr, "[bicon(src)]<span class='warning'>Incorrect pin/account combination entered, [max_pin_attempts - number_incorrect_tries] attempt\s remaining.</span>")
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +								playsound(src, 'sound/machines/buzz-two.ogg', 50, 1)
```suggestion
								playsound(src, 'sound/machines/buzz-two.ogg', 50, TRUE)
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +								playsound(src, 'sound/machines/buzz-sigh.ogg', 50, 1)
```suggestion
								playsound(src, 'sound/machines/buzz-sigh.ogg', 50, TRUE)
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +						playsound(src, 'sound/machines/twobeep.ogg', 50, 1)
```suggestion
						playsound(src, 'sound/machines/twobeep.ogg', 50, TRUE)
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +						ticks_left_timeout = 120
Make that an option or define?

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +					playsound(src, 'sound/machines/chime.ogg', 50, 1)
```suggestion
					playsound(src, 'sound/machines/chime.ogg', 50, TRUE)
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +				playsound(loc, 'sound/goonstation/machines/printer_thermal.ogg', 50, 1)
```suggestion
				playsound(loc, 'sound/goonstation/machines/printer_thermal.ogg', 50, TRUE)
```

2020-11-01 14:34 UTC, dearmochi commented on code/modules/economy/ATM.dm
> +			playsound(loc, pick('sound/items/polaroid1.ogg', 'sound/items/polaroid2.ogg'), 50, 1)
```suggestion
			playsound(loc, pick('sound/items/polaroid1.ogg', 'sound/items/polaroid2.ogg'), 50, TRUE)
```

2020-11-01 17:18 UTC, AffectedArc07 commented on code/modules/economy/ATM.dm
> +	. = TRUE
Having `. = TRUE` and `return 1` is redundant here. Pick one or the other

2020-11-01 17:33 UTC, AffectedArc07 approved these changes

2020-11-01 17:34 UTC, merged