CC clothing armor buff + description and name changes
ParadiseSS13/Paradise pull request #14803
Opened 2020-10-31 22:36 UTC by E-MonaRhg

## What Does This PR Do

Gives the SolGov Lieutenant, SOO, Navy Officer, Navy Captain (+ other CC roles that use their uniforms) and Blueshield security officer's jumpsuit grade armor + job specific Formal Uniform names: "Formal Nanotrasen Representative's Uniform", "Formal Blueshield's Uniform" and "Formal Magistrate's Uniform" instead of just "Formal Nanotrasen Uniform".

## Why It's Good For The Game

CC uniforms had "It's got exotic materials for protection." in the description yet no armor, now have armor to be less confusing. And I consider that the fact that Formal Blueshield's Uniform didn't have any armor compared to the normal blueshield's uniform was somewhat of a noob-trap for the Blueshields that wanted to look fancy. It also has "It's got exotic materials for protection." in the description now.

## Changelog
:cl:
tweak: Gave armor to several CC uniforms
tweak: Changed the names and descriptions of karma CC role formal uniforms
/:cl:

2020-11-01 05:08 UTC, variableundefined approved these changes
I'm fine with this if it just brings the formal uniform in line with the normal one for protection

2020-11-02 15:59 UTC, farie82 requested changes
Small nitpick. Looks good otherwise

2020-11-02 15:59 UTC, farie82 commented on code/modules/clothing/under/miscellaneous.dm
> +	armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
Spacing issue here and the others:
```suggestion
	armor = list("melee" = 10, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```

2020-11-02 15:59 UTC, farie82 commented on code/modules/clothing/under/miscellaneous.dm
> +	armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```suggestion
	armor = list("melee" = 10, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```

2020-11-02 15:59 UTC, farie82 commented on code/modules/clothing/under/miscellaneous.dm
> +	armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```suggestion
	armor = list("melee" = 10, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```

2020-11-02 15:59 UTC, farie82 commented on code/modules/clothing/under/miscellaneous.dm
> +	armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```suggestion
	armor = list("melee" = 10, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)
```

2020-11-02 17:54 UTC, E-MonaRhg commented
Spacing issues near "energy" were due to me copying the armor line from the normal blueshield uniform

2020-11-04 16:05 UTC, farie82 approved these changes

2020-11-07 03:27 UTC, Kyep approved these changes

2020-11-07 21:51 UTC, merged