Nuka cola now gives radiation
ParadiseSS13/Paradise pull request #14815
Opened 2020-11-03 18:07 UTC by Varghh

## What Does This PR Do
Nuka cola will now give you radiation, you can no longer chug it like a free super fast potion.

## Why It's Good For The Game
People love to abuse stuff, nuka cola has been used A LOT lately for just free super meth speed without any kind of weakness, in this game speed is king so you should not be able to chug this out to fly around for free.

## Images of changes
![nuka](https://user-images.githubusercontent.com/26222480/98023821-37283e80-1de6-11eb-86d3-7331f8f8a726.png)
![nuka2](https://user-images.githubusercontent.com/26222480/98023823-38596b80-1de6-11eb-80da-966c668d6f69.png)
![nuke3](https://user-images.githubusercontent.com/26222480/98023825-38596b80-1de6-11eb-9e5c-06f9e10d556d.png)

## Changelog
:cl:
tweak: Drinking Nuka cola will now give radiation.
/:cl:

2020-11-03 18:14 UTC, moxian commented on code/modules/reagents/chemistry/reagents/drink_cold.dm
> +	M.apply_effect(2, IRRADIATE, negate_armor = 1)
```suggestion
	M.apply_effect(2, IRRADIATE, negate_armor = TRUE)
```

2020-11-03 22:08 UTC, procdrone commented
Good idea, though radiation can be easily sidestepped just taking an additional pottasium iode pill, which isn't very hard to obtain.

... maybe making nuka cola also being an addictive chemical?

2020-11-03 23:19 UTC, Mitchs98 commented
God yes.

2020-11-03 23:21 UTC, Spacemanspark commented
I'm going to laugh when we finally add nucleations and they get speed AND a heal off of this lmfao

2020-11-04 16:01 UTC, Kiyahitayika commented
I support this and have a few questions:
1.) What do you think about adding a warning message for players? "You don't feel so great after drinking that . . ."
2.) Can Radiation damage cause mutation or is that separate?
3.) How much radiation is it per sip? Two? (asking for Medbay)

@procdrone Potassium Iodine bottles are stocked in the NanoMed Vendors in Medbay and, yet . . . Baldbay doesn't know how to treat Radiation damage very often, soooo . . . x3

2020-11-04 17:43 UTC, Varghh commented
> 1.) What do you think about adding a warning message for players? "You don't feel so great after drinking that . . ."

Taste is already _"radioactive cola"_, the drink flash green lights, has a radioactive logo and it's literally a Fallout drink... I think there are enough warnings.. :p

> 2.) Can Radiation damage cause mutation or is that separate?

Yeah, depends on how much radiation you have, a bit of rad should not be a problem, a lot of rad will fuck you up.

> 3.) How much radiation is it per sip? Two? (asking for Medbay)

It should be 2 per cycle.

2020-11-04 17:55 UTC, SteelSlayer approved these changes

2020-11-06 17:03 UTC, farie82 approved these changes

2020-11-06 18:38 UTC, variableundefined approved these changes

2020-11-07 03:29 UTC, Kyep approved these changes

2020-11-07 05:28 UTC, Fox-McCloud commented
Why don't we try nerfing how much it makes you faster.

2020-11-08 23:00 UTC, Varghh commented
> Why don't we try nerfing how much it makes you faster.

On top of the radiation?

2020-11-16 15:44 UTC, hal9000PR commented
If it gave less speed then it wouldn't have the gottagofast flag and it would stack with meth again. Personally I think giving it radiation is perfectly fine from a balance standpoint because it means that orm access doesn't mean free speed.

2020-12-09 17:07 UTC, variableundefined requested changes
@Varghh We would prefer nerfing how fast it goes **instead** of giving it radiation for two reasons: 
- It is easy to counteract radiation 
- Going to medbay for a day to day drink is weird

2020-12-09 17:09 UTC, Darkmight9 commented
Going off of Ansari above, why does it give a speed boost in the first place anyway? None of the other uranium drinks do anything extra other than look neat and get you drunk.

2020-12-22 16:06 UTC, Varghh commented
Per request, Nuka cola now only speeds you up by 0.5 instead of 1, radiation removed
@variableundefined

2020-12-22 16:19 UTC, merged