Removes X-ray from non AI controlled cameras
ParadiseSS13/Paradise pull request #14878
Opened 2020-11-12 03:02 UTC by warior4356

## What Does This PR Do
This PR removes X-ray effects from all non-AI camera viewing.

## Why It's Good For The Game
The previous PR that made it so only malf AI can make cameras X-ray means that ability would reveal them to anyone on a security camera console. This PR removes security's unintended ability to spot a malf AI via cameras from #14816

## Changelog
:cl:
del: Removed the ability to X-ray via cameras from non AI as it is now a malf only effect
/:cl:

2020-11-12 04:06 UTC, Varghh commented
Absolutely agree, nice way to avoid metamancy

2020-11-12 06:45 UTC, variableundefined approved these changes

2020-11-12 08:24 UTC, farie82 approved these changes

2020-11-12 12:31 UTC, AffectedArc07 requested changes

2020-11-12 12:31 UTC, AffectedArc07 commented on code/game/machinery/computer/camera.dm
> +		for(var/turf/T in (view(C.view_range, get_turf(C))))
```suggestion
		for(var/turf/T in view(C.view_range, get_turf(C)))
```

2020-11-12 15:31 UTC, Spacemanspark commented
Oof

2020-11-13 05:30 UTC, Kyep approved these changes

2020-11-13 16:54 UTC, SteelSlayer approved these changes

2020-11-15 09:23 UTC, AffectedArc07 approved these changes

2020-11-15 09:23 UTC, merged