Fixes slaughter demon objectives, adds new slaughter / rev ones
ParadiseSS13/Paradise pull request #14889
Opened 2020-11-13 23:42 UTC by Qwertytoforty

## What Does This PR Do

This pr fixes slaughter demon objectives not generating, as it checked for if the demon had a mind before the ghost was put in it. Adds some new slaughter and revenant objectives, and removes the ones that go opposite the playstyle of them.

## Why It's Good For The Game

Having some fluff objectives for more demons is nice (and making it work), as well as having the slaughter demon info prompt coming up again. 

Removes:
"Attempt to make your presence unknown to the crew." (demon objective)
This is literally impossible for the demon to do, so it's a bit silly as a fluff objective. It also basically tells the demon not to kill people if there are 2 people in an area, which means it's not going to be killing very often if it wants to make it's presence unknown, which goes against the objective.

"Avoid killing in plain sight." (rev)
This has the same problem as the removed demon objective. You generally don't find dead or dying people lying around with no one watching as a rev. Generally people kill someone where they are watching the person they are killing, person is dying in medical around doctors, or they are in crit crawling to a hallway. Near impossible to kill in plain sight, and not fun for the player with this fluff objective to do.

## Changelog
:cl:
tweak: Adds and removes some demon and revenant objectives.
fix: fixes major event demons objectives not generating.
/:cl:

2020-11-14 03:18 UTC, SteelSlayer approved these changes

2020-11-14 09:50 UTC, AffectedArc07 requested changes
Theres so many things I want to nitpick in this file but its just out of the scope of this PR, so ill just request this one for now

2020-11-14 09:50 UTC, AffectedArc07 commented on code/game/gamemodes/miniantags/slaughter/slaughter.dm
> +	if(boost<world.time)
```suggestion
	if(boost < world.time)
```

2020-11-17 15:29 UTC, AffectedArc07 approved these changes

2020-11-17 15:29 UTC, merged