Windowpainter
ParadiseSS13/Paradise pull request #14888
Opened 2020-11-13 19:40 UTC by thatdanguy23

## What Does This PR Do
Adds an item that changes the colors of basic windows, reinforced windows (as well as both of their fulltile variants) and windoors. It's based off of the pipe painter code, so you can only choose from the same presets as you would painting pipes, but it's a start.

## Why It's Good For The Game
It's just an extra something to make customizing a bit more fun.

## Images of changes
![image](https://user-images.githubusercontent.com/16391918/99113736-a6bcdb80-25e7-11eb-9a1a-548f67efb788.png)
![image](https://user-images.githubusercontent.com/16391918/99113927-ed123a80-25e7-11eb-9322-1da1833c36c9.png)
![image](https://user-images.githubusercontent.com/16391918/99113989-04512800-25e8-11eb-9ddd-0391bff79bcb.png)

## Changelog
:cl: thatdanguy23
add: added a window painting tool
/:cl:

2020-11-13 19:53 UTC, thatdanguy23 commented on code/game/objects/items/devices/pipe_painter.dm
> +	mode = input("Which colour do you want to use?", name, mode) in modes
Changed to ensure that it said "Window Painter" instead of "Pipe Painter".

2020-11-13 20:03 UTC, AffectedArc07 requested changes
Few minor things

2020-11-13 20:33 UTC, AffectedArc07 approved these changes

2020-11-14 03:30 UTC, SteelSlayer commented on code/game/objects/items/devices/window_painter.dm
> +	if(!(istype(A,/obj/structure/window/reinforced) || istype(A,/obj/structure/window/basic) || istype(A,/obj/machinery/door/window) || istype(A,/obj/structure/window/full/reinforced) || istype(A,/obj/s
Having so many conditions like this in 1 if statement makes it a bit hard to read, and annoying to add to later. I suggest putting all these types in a list on the window painter, i.e
```dm
var/list/paintable_windows = list(
	/obj/structure/window/reinforced,
	/obj/structure/window/basic
	// etc.
)
```
And then you can do:
```dm
if(!is_type_in_list(A, paintable_windows) || !in_range(user, A))
	return
```

2020-11-14 11:14 UTC, AffectedArc07 requested changes

2020-11-14 11:14 UTC, AffectedArc07 commented on code/game/objects/items/devices/window_painter.dm
> +		/obj/machinery/door/window)
```suggestion
	var/list/paintable_windows = list(
			/obj/structure/window/reinforced,
			/obj/structure/window/basic,
			/obj/structure/window/full/reinforced,
			/obj/structure/window/full/basic,
			/obj/machinery/door/window)
```
Needs to be indented to be part of the definition, not a global (unindented) list

2020-11-14 14:32 UTC, AffectedArc07 approved these changes

2020-11-14 16:51 UTC, SteelSlayer approved these changes

2020-11-19 09:47 UTC, Kyep approved these changes
Initially I was not in favor of this, as I felt it would be confusing to have windows that for example looked like plasmaglass but were not.

After thinking about it though, color-coding would be nice and opens up new design options. Not to mention it lets people customize their workspaces. And the available colors (non,red,blue,teal,green,yellow,purple) really don't seem that atrocious.

2020-11-23 19:07 UTC, AffectedArc07 approved these changes

2020-11-23 19:07 UTC, merged