Autolathe disable wire actually disables autolathe
ParadiseSS13/Paradise pull request #14903
Opened 2020-11-15 16:05 UTC by Adrer

## What Does This PR Do
Autolathe disable wire now actually disables the autolathe, making it impossible to open new autolathe windows and disabling any currently open autolathe windows.

fixes: #14894 

## Why It's Good For The Game
Previously the disable wire didn't actually... Disable the autolathe.

## Changelog
:cl:
fix: Autolathe disable wire now actually disable autolathe
/:cl:

2020-11-15 16:50 UTC, AffectedArc07 requested changes

2020-11-15 16:50 UTC, AffectedArc07 commented on code/game/machinery/autolathe.dm
> +		if(stat & (NOPOWER|BROKEN|disabled))
```suggestion
		if((stat & (NOPOWER|BROKEN)) || disabled)
```
This is a more sensible condition, and actually valid in this context

2020-11-15 21:55 UTC, AffectedArc07 requested changes

2020-11-15 21:55 UTC, AffectedArc07 commented on code/game/machinery/autolathe.dm
> +	else if(!disabled)
```suggestion
	else if(!disabled)
```
Should have mentioned this before. Spacing.

2020-11-16 10:14 UTC, AffectedArc07 approved these changes

2020-11-16 10:15 UTC, merged

2020-11-16 16:30 UTC, Kyep commented
Thank you for fixing this.