Make fluff items cheaper
ParadiseSS13/Paradise pull request #14997
Opened 2020-11-27 03:24 UTC by moxian

## What Does This PR Do
Fluff items are now 2x cheaper, claw game now costs 5cr.
This puts banjo at 250cr (slightly cheaper than a PDA) and synth at 500cr (slightly more expensive than a PDA)
This is a - hopefully - less controversial alternative to #14989 
This is not fiddling with account balance, since that seems to be a very touchy subject

## Why It's Good For The Game
The prices in the cargo shop are mostly arbitrary, since nobody particularly cared how much an item costs if you can spend 15 minutes spinning slots and get infinite money.
Now that #14953 is merged and infinite money is a thing of the past, being able to obtain a synth is no longer a given, and people are upset that they cannot play music and have fun.
This calls to re-evaluate the pricing (which, again, was set more or less arbitrarily in the first place).
Being able to buy a synth the moment you enter the station (even, potentially, having to spend ALL your money doing so) is a good thing

## Changelog
:cl:
tweak: Cargo shop fluff items are twice as cheap now.
/:cl:

2020-11-27 04:21 UTC, Necaladun requested changes
Claw game I think should be risky for the gambling and the house always wins - they're not meant to be prizes people should expect to get.

The other things being cheaper is generally good as it will encourage their use. 

Snap pops being that cheap might be a bit annoying but it's not big deal. Overall this is a good PR and my change requests aren't something I'm going to die on a hill for.

2020-11-27 04:42 UTC, moxian commented
With my claw game skills i get a prize 3 times out of ten.
Which means I need to play ~15 times to get a random non-carp plushie. (Or, likewise ~15 times if i *want* a carp plushie)
At 15cr/spin that makes the random(!) plushie cost 225cr. If you're aiming for something more specific you need to get more than one random plushie.
While I agree that claw game should not be a charity and there should be risk involved, I don't think 225cr is a fair price for something you don't *quite* want. (Compare, with, again, a 250cr guitar from which you *know* what to expect)
Also compare: if you want a figurine, you need to currently spend, again, 15 spins/225cr to get one. When you can buy *a box* of them from cargo for only 100cr.

I would honestly like to cut the claw game cost in half down from the current 15cr, but 7.5 is not a nice number. And 10 is still a bit too high for my tastes. Hence 5cr.

Let me know if this is not convincing enough, and I'll increase it back (preferably to 10cr though - a "rounder" number than 15).

2020-11-27 05:33 UTC, Necaladun commented
That's convincing, keep the price there.

2020-11-29 15:33 UTC, Kyep approved these changes

2020-11-30 16:06 UTC, AffectedArc07 approved these changes

2020-11-30 16:06 UTC, merged