10 new Diona "hair" styles
ParadiseSS13/Paradise pull request #15021
Opened 2020-11-30 11:32 UTC by ExusA

## What Does This PR Do
Adds 10 new hairstyles for dionea.

## Why It's Good For The Game
Hairstyle is the only customisation option avaliable to diona players. There needs to be lots of choices for characters to feel more unique! I felt there weren't enough unique-feeling hair-styles avaliable, so I made some more. I'm also an amateur spriter, so I hope they look okay!

## Images of changes
This is going to be long...

![sunflower](https://user-images.githubusercontent.com/67055922/100604380-6f696100-3341-11eb-9339-0cd0d17e46dd.PNG)
-Sunflower

![marigold](https://user-images.githubusercontent.com/67055922/100604416-7bedb980-3341-11eb-8f53-c2567fb968e0.PNG)
-Marigold

![lilies](https://user-images.githubusercontent.com/67055922/100604428-814b0400-3341-11eb-8856-b60f61ab35c0.PNG)
-Lilies

![frost](https://user-images.githubusercontent.com/67055922/100604468-8f992000-3341-11eb-8603-5e083733e544.PNG)
-Frost

![daisies](https://user-images.githubusercontent.com/67055922/100604483-958f0100-3341-11eb-9042-d84e9fad0853.PNG)
-Daisies

![bigrose](https://user-images.githubusercontent.com/67055922/100604496-99bb1e80-3341-11eb-8335-22785bd6d50c.PNG)
-Big Rose

![poppies](https://user-images.githubusercontent.com/67055922/100604508-9f186900-3341-11eb-8d2c-2bb1b2cfd64e.PNG)
-Poppies

![bigleaf](https://user-images.githubusercontent.com/67055922/100604527-a475b380-3341-11eb-8451-658f85712dec.PNG)
-Big Leaves

![field mushrooms](https://user-images.githubusercontent.com/67055922/100604556-a9d2fe00-3341-11eb-8d02-09c657535d2d.PNG)
-Field Mushrooms

![hydrangea](https://user-images.githubusercontent.com/67055922/100604619-bb1c0a80-3341-11eb-9dac-c00a19ce1b0d.PNG)
-Hydrangea

## Changelog
:cl:
imageadd: Added 10 diona hairstyles.

2020-11-30 12:00 UTC, ExusA commented
BEFORE I FORGET: The original "laurel" hairstyle had a few odd white pixels hanging out on the border of it, so I cleaned them up, and that's why the diff includes it.

2020-11-30 13:39 UTC, PacifistDalek commented
I'm a diona main and I love all of these

2020-11-30 14:41 UTC, Darkmight9 commented
Oh this is very lovely! ❤️ 
Maybe for a future PR you could make 'long hair' options such as vines(both bare green, covered in flowers, maybe tied into a ponytail, etc), a really big leaf that hangs off the back, possibly some others (still waking up)

2020-11-30 15:48 UTC, Spacemanspark commented
I wish nymphs could randomly spawn with a little flower on their head like this too

2020-12-02 19:02 UTC, Kyep approved these changes

2020-12-05 10:34 UTC, AffectedArc07 requested changes

2020-12-05 10:34 UTC, AffectedArc07 commented on code/modules/mob/new_player/sprite_accessories/diona/diona_hair.dm
> +	glasses_over = 0
```suggestion
	glasses_over = FALSE
```

2020-12-05 10:34 UTC, AffectedArc07 commented on code/modules/mob/new_player/sprite_accessories/diona/diona_hair.dm
> +	glasses_over = 0
```suggestion
	glasses_over = FALSE
```

2020-12-05 10:34 UTC, AffectedArc07 commented on code/modules/mob/new_player/sprite_accessories/diona/diona_hair.dm
> +	glasses_over = 0
```suggestion
	glasses_over = FALSE
```

2020-12-09 17:17 UTC, variableundefined commented
Pretty and unique

2020-12-09 17:17 UTC, merged