Donut box folding
ParadiseSS13/Paradise pull request #15027
Opened 2020-11-30 23:32 UTC by SabreML

## What Does This PR Do

Moves the box folding code into its own proc on `/obj/item/storage`, and makes the donut box foldable.

## Why It's Good For The Game

Less empy donut boxes clogging up the tables at Security, and the ability for more items in the future to also use this proc.

## Changelog
:cl:
add: Empty donut boxes can now be folded into cardboard
/:cl:

2020-12-01 02:18 UTC, SteelSlayer approved these changes

2020-12-02 20:31 UTC, Dumbdumn5 approved these changes
An easy quality of life approval, so long as the code is good! Just to be sure, we can make donut-boxes out of cardboard, right?

2020-12-02 23:35 UTC, SabreML commented
> An easy quality of life approval, so long as the code is good! Just to be sure, we can make donut-boxes out of cardboard, right?

Uh no, not currently.
Didn't really think of that part to be honest

2020-12-05 10:28 UTC, AffectedArc07 requested changes
Please add a method for creating new donut boxes so the existing ones cant be folded into oblivion.

2020-12-05 10:28 UTC, merged

2020-12-05 10:29 UTC, AffectedArc07 commented
Ok so clearly I havnt had enough coffee this morning.

@SabreML could you make a PR that allows donut boxes to be created by cardboard ASAP?

2020-12-05 10:45 UTC, Spacemanspark commented
Haha merge button go brrr