Swarmer Beacon EMP damage
ParadiseSS13/Paradise pull request #15032
Opened 2020-12-01 20:28 UTC by SabreML

## What Does This PR Do

Changes swarmer beacons (The lavaland kind) to take 50 damage from EMP pulses and Ion rifles.
This is one and a half ion rifles of ammo to kill it, assuming you never miss or have to target a swarmer instead.

Also added `del_on_death` to swarmer beacons, since currently they're just kinda sitting there with no sprite.

## Why It's Good For The Game

It's a bit counter intuitive that the best way to kill a Swarmer is to use an EMP, but the actual spawner itself is completely immune to them.

## Changelog
:cl:
tweak: Swarmer beacons now take damage from EMP pulses
fix: Swarmer beacons now actually get deleted on death
/:cl:

2020-12-02 19:03 UTC, Kyep approved these changes

2020-12-05 10:27 UTC, AffectedArc07 requested changes

2020-12-05 10:27 UTC, AffectedArc07 commented on code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
> +	var/swarmer_spawn_cooldown_amt = 15 SECONDS //Seconds between the swarmers we spawn
```suggestion
	/// Time between the swarmers we spawn
	var/swarmer_spawn_cooldown_amt = 15 SECONDS
```
Autodoc compliance and disambiguation

2020-12-05 10:27 UTC, AffectedArc07 commented on code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
> +	var/call_help_cooldown_amt = 15 SECONDS //Seconds between calling swarmers to help us when attacked
```suggestion
	/// Time between calling swarmers to help us when attacked
	var/call_help_cooldown_amt = 15 SECONDS
```
Autodoc compliance and disambiguation

2020-12-06 22:39 UTC, AffectedArc07 approved these changes

2020-12-06 22:45 UTC, merged