Removes the 0.1 second delay for window deconstruction
ParadiseSS13/Paradise pull request #15039
Opened 2020-12-02 16:05 UTC by SabreML

## What Does This PR Do

Removes the 1 decisecond delay when constructing or deconstructing directional window panes.

## Why It's Good For The Game

It's very irritating if you're trying to go quickly.

## Changelog
:cl:
tweak: Removed the 0.1 second delay when (de)constructing window panes
/:cl:

2020-12-02 16:18 UTC, KasparoVy commented
AFAIK this was added to stop macro memes and to make it so you can't just swooce your way through glass like it's nothing

2020-12-02 16:19 UTC, SabreML commented
> AFAIK this was added to stop macro/hyperspeed hotkey memes and to make it so you can't just swooce your way through glass like it's nothing
> 
> Can't locate the old PR but maybe @Kyep has an opinion on this

Text macros wouldn't be able to deconstruct stuff anyway, and something like an autoclicker would only be delayed by 0.3 seconds.

2020-12-02 17:46 UTC, SteelSlayer approved these changes

2020-12-03 03:40 UTC, Carthusia commented
So THIS is why when i rapidly try to attach or detach a window, it sometimes skips a step, or does no steps at all.

Its so frustrating when your doing an entire line of windows,and have to recheck each and every one of them because some may not have registered you were using tools on them, or they missed one tool and did not secure fully.

2020-12-04 09:53 UTC, farie82 requested changes

2020-12-04 09:53 UTC, farie82 commented on code/game/objects/structures/window.dm
> +	if((decon_speed == null) && fulltile)
```suggestion
	if(decon_speed == null && fulltile)
```

2020-12-04 23:32 UTC, farie82 approved these changes

2020-12-06 01:47 UTC, Kyep approved these changes

2020-12-06 12:35 UTC, Spacemanspark commented
Frankly I've always seen this as obnoxious, and causing me to accidentally smack a window with a wrench more than anything.

2020-12-06 15:52 UTC, Carthusia commented
I dono Dashora, I wouldnt really call it a skillcheck, as I swear sometimes it causes things to glitch out.

So say i have 3 reinforced windows in a row and I wish to secure them in place, if i screwdriver, crowbar, screwdriver on them, one window at a time, at a rapid pace there is a good chance that due to the .1 delay that some tools wont even register being used, it will SAY they got used, and it will show the timebar and make the sound, but it will have not applied some or any of the tools, leaving it unsecured and able to be pushed around.

This happens all the time when i try to build areas with lots of windows.

2020-12-07 11:14 UTC, S34NW commented
The 0.1 second delay can be extremely infuriating as a player, not to mention having two messages like "Starting to screw ..." "... was screwed" for each step just fills up your chat instantly when working on multiple windows.

2020-12-14 18:16 UTC, DevL-Whats-a-jpg commented
Yea i hate the delay, resulted in me burning my ass off twice when i was new to atmos and making burn chambers.

2020-12-16 18:54 UTC, merged