AIs can now toggle whether they wish to announce oncoming station arrivals or not
ParadiseSS13/Paradise pull request #15069
Opened 2020-12-08 19:26 UTC by Spacemanspark

## What Does This PR Do
See title.

## Why It's Good For The Game
As an AI, I generally wish I could delegate the arrivals messages to the automatic announcement system. This allows AIs who want to personalize their announcement system do so, while allowing others to opt out.

## Changelog
:cl:
add: Added a new command for AIs: "Toggle Arrivals Announcer". This will allow AIs to opt into or out of announcing all oncoming crew arrivals.
/:cl:

2020-12-08 19:27 UTC, Spacemanspark commented
ok travis don't make me have to take you out to the shed

2020-12-08 19:36 UTC, AffectedArc07 requested changes

2020-12-08 19:36 UTC, AffectedArc07 commented on code/modules/mob/living/silicon/ai/ai.dm
> +	var/announce_arrivals = TRUE //If our AI doesn't want to be the arrivals announcer, this gets set to 0.
```suggestion
	/// If our AI doesn't want to be the arrivals announcer, this gets set to FALSE.
	var/announce_arrivals = TRUE 
```

2020-12-08 19:49 UTC, Spacemanspark commented on code/modules/mob/living/silicon/ai/ai.dm
> +	var/announce_arrivals = TRUE //If our AI doesn't want to be the arrivals announcer, this gets set to 0.
you can't make m-

2020-12-08 20:03 UTC, AffectedArc07 requested changes
Autodoc complaince please

2020-12-08 20:03 UTC, AffectedArc07 commented on code/modules/mob/living/silicon/ai/ai.dm
> +	var/announce_arrivals = TRUE //If our AI doesn't want to be the arrivals announcer, this gets set to FALSE.
```suggestion
	/// If our AI doesn't want to be the arrivals announcer, this gets set to FALSE.
	var/announce_arrivals = TRUE 
```

2020-12-08 20:34 UTC, AffectedArc07 requested changes

2020-12-08 20:34 UTC, AffectedArc07 commented on code/modules/mob/new_player/new_player.dm
> +			if(A.announce_arrivals == TRUE)
```suggestion
			if(A.announce_arrivals)
```
Last things

2020-12-08 20:34 UTC, AffectedArc07 commented on code/modules/mob/living/silicon/ai/ai.dm
> +	///If our AI doesn't want to be the arrivals announcer, this gets set to FALSE.
```suggestion
	/// If our AI doesn't want to be the arrivals announcer, this gets set to FALSE.
```
Yes I am this picky

2020-12-08 22:03 UTC, AffectedArc07 approved these changes

2020-12-09 17:31 UTC, Kyep approved these changes

2020-12-10 09:00 UTC, merged