Firedoors open/close even for air alarms that don't report to computers
ParadiseSS13/Paradise pull request #15167
Opened 2020-12-21 06:51 UTC by Kyep

## What Does This PR Do
When a silent (report_danger_level=FALSE, IE /obj/machinery/alarm/monitor or /obj/machinery/alarm/syndicate) air alarm changes from "green" status to a warning status (orange/red), or the other way around, it will now close/open firedoors in its area.
In practice, what this means is that firelocks in space ruins and other areas that shouldn't show up on station alerts console will still work. 
These air alarms still won't generate alerts to consoles, but they will at the very least open/close firedoors in their area. So they won't be totally useless.

## Why It's Good For The Game
Currently, firelocks in these areas simply don't close automatically.
With this PR, they will.

## Changelog
:cl:
tweak: firelocks in offstation areas with air alarms will now open/close when the air alarm signals the air is safe/unsafe.
/:cl:

2020-12-22 16:38 UTC, farie82 requested changes

2020-12-22 16:38 UTC, farie82 commented on code/game/machinery/alarm.dm
> +		else if(alert_level != ATMOS_ALARM_NONE && !A.air_doors_activated)
```suggestion
		else if(alert_level != ATMOS_ALARM_NONE)
```
Same as above

2020-12-22 16:38 UTC, farie82 commented on code/game/machinery/alarm.dm
> +		if(alert_level == ATMOS_ALARM_NONE && A.air_doors_activated)
```suggestion
		if(alert_level == ATMOS_ALARM_NONE)
```
`air_doors_activated` is already checked in the `air_doors_open` proc itself

2020-12-23 09:19 UTC, farie82 approved these changes

2021-01-10 05:36 UTC, Dumbdumn5 approved these changes
Makes sense, yeah 👍  Don't see a reason why firelocks shouldn't work like that.

2021-02-21 21:35 UTC, AffectedArc07 approved these changes

2021-02-21 21:35 UTC, AffectedArc07 commented
Please resolve merge conflicts when you can

2021-02-23 20:14 UTC, Kyep commented
@AffectedArc07 Said it had a conflict, but apparently it did not. Updated.

2021-02-23 20:17 UTC, merged