Make NT Default possible roundstart lawset; add a small chance for meme lawsets as well
ParadiseSS13/Paradise pull request #15160
Opened 2020-12-20 16:47 UTC by moxian

## What Does This PR Do
This is an alternative to #15157

- Refactors the way lawsets are set as "eligible to be roundstart" - it is now encoded in law selection logic, rather than on the law itself; Also made the eligibility weighted, rather than a yes/no.
- NT Default is now roundstart default, along with what we had previously in Crewsimov and Corporate
- Added a small chance for meme laws (T.Y.R.A.N.T, Robocop, PALADIN, NT Agressive) to appear roundstart as well.

## Why It's Good For The Game
NT Default is an overall decent lawset that command seems to gravitate to roundstart anyway, so there's no reason not to have it in rotation.
The meme laws are there to add a bit of spice to the AIs lives. With a very low probability, of course.

As to probabilities:
- Crewsimov/Corporate/NT Default have 30% chance to appear each
- Paladin has 4%, TYRANT, Robocop, NT Agressive have 2% each; All meme laws combined amount to 10% total.

With a round being almost 2h on average (data: we've had 1158 rounds over the past 3 months, which averages to 113 minutes per round - note that it includes pre- and post-lobby times), we have ~12 rounds a day, and ~90 rounds a week; which means that:
- we'd get one meme law each day, on average
- each *specific* meme law would appear twice a week, on average (other than paladin - that'd be 4 times a week)
- 
A quick note on perception: you - personally - *won't* see a meme law every day unless you literally play/observe 24/7.

The probabilities are chosen as they are mostly because they are nice round numbers, I'm happy to alter them whichever way is preferred if these numbers are unideal.

## Images of changes
![dreamseeker-20201220-163115](https://user-images.githubusercontent.com/7831163/102718830-51f53a80-42e2-11eb-807c-1073252c41eb.png)

## Changelog
:cl:
add: NT Default is now roundstart lawset along with Corporate and Crewsimov
add: Added a small chance for T.Y.R.A.N.T., P.A.L.A.D.I.N., NT Agressive and Robocop to be roundstart lawsets.
/:cl:

2020-12-20 17:42 UTC, kenken244 commented
TYRANT should probably never ever appear, I can see NT experimenting with the others (this is a science station after all) but tyrant is just so bad it would prevent the station from functioning. and also invite the ai to murder people. I do like the idea of having a small chance of a very different lawset, but I think it would end up just being changed as soon as anyone realized what laws the ai is on

2020-12-20 18:03 UTC, moxian commented
> TYRANT should probably never ever appear

Happy to do this change if a second person (preferably, game admin, but not essential) agrees. I don't have a strong opinion of my own here.

> also, maybe have a chance of the ai being completely unlawed instead?

I'm not sure how it's any better than TYRANT.
(And also it would require a bit more refactoring, so I'd like to find an excuse not to :P)

2020-12-20 18:13 UTC, Marginalorb commented
T.Y.R.A.N.T. doesn't really invite unwarranted violence, in fact, it tells the AI to respect authority and to act with discipline. Granted, it does open up the possibility of the AI assisting someone in mutiny, but again, the laws specify the AI should punish those who disrespect authority, unless they're more fit to hold said authority.

Honestly I wouldn't mind seeing a higher chance for the other laws to come up, but y'know, I'm just a GA. Might want to see what a HA or Maint think before changing anything.

2020-12-20 18:39 UTC, kenken244 commented
tyrant pretty much blatantly encourages the ai to kill command and take control of the station if it thinks that it can do so.

2020-12-20 20:30 UTC, Spacemanspark commented
robocop and paladin are a bit much. They were actually removed from the rotation years back. They're very validhunty lawsets, fun in small doses and in certain situations... but not something to see on the daily. 

Tyrant... I don't know, bit iffy on it.

@kenken244 is wrong, however. It doesn't encourage an AI to murder command whatsoever, unless they decide to attack it first.

It does often end in an AI being at odds with at least a few command members, however. I'm not sure if it's a good idea.

2020-12-20 20:50 UTC, procdrone commented
I personally like the novelty of it. Command would probably quickly change the laws anyway if they did not find them to their liking. Having an unique thing to work with so rarely propably wouldn't be TOO much. + with this change almost everyone would question AI about their lawset immediately, given it can no longer be a cresimov/corpo only

2020-12-20 21:09 UTC, moxian commented
> They're very <..> fun in small doses <..> but not something to see on the daily

This is exactly the intent of this PR - introduce those lawsets in small doses.
Please, again, note that even if they *happen* once a day, you won't *see* them daily because you're not online 24/7.

It is fair to view the lawsets as "antaggy", and basically treat as a midround-lite. I just think that, essentially, midround that happens at the very start of the round is not a bad thing (especially if they don't require blob levels of station response).

If the proposed frequency is seen as too high, I'm more than happy to adjust it - just give me an idea what numbers you'd like to see.

2020-12-21 11:00 UTC, Kyep reviewed
I'm fine with adding NT Default to the possible laws at roundstart.
I'm not a fan of having any chance to load something like Tyrant or Robocop.

2020-12-21 11:24 UTC, Spacemanspark commented
I'd prefer robocop/ paladin were left as lawsets for the crew themselves to add

2020-12-22 16:58 UTC, farie82 requested changes

2020-12-22 16:58 UTC, farie82 commented on code/modules/mob/living/silicon/laws.dm
> +	var/weights = list(
```suggestion
	var/static/list/weights = list(
```

2020-12-22 22:41 UTC, moxian commented
Chatted with Kyet, gained a new perspective, and I now agree that having "meme" laws roundstart is probably not a good idea. (Or rather, I still think it *might* be a good idea, but it needs a completely different framing, and much more thorough justification than just "it might be fun, idk").
Either way, this part is now removed from the PR.

This now has the exactly gameplay impact as #15157 , just a slightly different implementation, that would allow to easily tweak lawset probabilities in the future (if need be).

2020-12-23 00:14 UTC, farie82 approved these changes

2020-12-28 18:40 UTC, Dumbdumn5 approved these changes
Considering the changes made and the roundstart list for AI lawsets including more or less the blandest of the bunch (which isn't necessarily a bad thing), consider this my approval, g o b l i n :+1:

2021-01-10 20:22 UTC, AffectedArc07 commented
Closed in favour of #15157

2021-01-10 20:22 UTC, closed without merging