Fixes visible message when showing paper
ParadiseSS13/Paradise pull request #15270
Opened 2021-01-10 00:30 UTC by SabreML

## What Does This PR Do

Swaps the `visible_message()` arguments around for showing someone a piece of paper, since they were backwards.
This meant that you'd get the `"You show the paper to [person]."` message when you're not the one doing it.

## Why It's Good For The Game

Bugfix.

## Changelog
:cl:
fix: Fixed the 'visible' and 'user' message being the wrong way round when showing a paper to someone.
/:cl:

2021-01-10 09:11 UTC, farie82 requested changes

2021-01-10 09:11 UTC, farie82 commented on code/modules/paperwork/paper.dm
> +			H.update_body()
```suggestion
```

2021-01-10 09:11 UTC, farie82 commented on code/modules/paperwork/paper.dm
>  				H.update_body()
```suggestion
			if(!do_after(user, 1 SECONDS, target = H) && do_after(H, 1 SECONDS, FALSE))	//user needs to keep their active hand, H does not.
				return
			user.visible_message("<span class='notice'>[user] wipes [H]'s face clean with \the [src].</span>",
		H.lip_style = null
		H.update_body()
```
Combine this with the above. This way you avoid dupe code for cleaning the lip style etc

2021-01-10 09:11 UTC, farie82 commented on code/modules/paperwork/paper.dm
> +			"<span class='notice'>You show the paper to [H]. </span>")
```suggestion
		user.visible_message("<span class='notice'>[user] holds up a paper and shows it to [H].</span>",
			"<span class='notice'>You show the paper to [H].</span>")
```
Weird extra space there after and before the sentence

2021-01-10 09:11 UTC, farie82 commented on code/modules/paperwork/paper.dm
> +		return
```suggestion
		return ..()
```

2021-01-10 21:46 UTC, farie82 commented on code/modules/paperwork/paper.dm
> +			if(!do_after(user, 1 SECONDS, target = H) && do_after(H, 1 SECONDS, FALSE)) // user needs to keep their active hand, H does not.
```suggestion
			if(!do_after(user, 1 SECONDS, target = H) || !do_after(H, 1 SECONDS, FALSE)) // user needs to keep their active hand, H does not.
```
It is a negative check now. So if either failed then it should return.
Sidenote. A bit odd to have the double `do_after` here but it was already there so why not

2021-01-11 16:28 UTC, farie82 commented on code/modules/paperwork/paper.dm
> +		H.update_body()
```suggestion
		H.update_body()
	else
		return ..()
```
Else you can't bap people with the paper anymore

2021-01-18 21:42 UTC, AffectedArc07 commented
Please deal with the requested change within 7 days or this PR will be closed.

2021-01-18 22:16 UTC, AffectedArc07 approved these changes

2021-01-18 22:16 UTC, merged