Allows Janitor borg's EMAG lube to refill in a charger
ParadiseSS13/Paradise pull request #15278
Opened 2021-01-11 03:34 UTC by warior4356

## What Does This PR Do
Janitor borg's get a lube spray bottle as their EMAG item, however, they can not refill it. This PR makes it so it refills at 5 units per tick in a recharger.

## Why It's Good For The Game
Having your EMAG item be limited use isn't fun, and janitor borgs don't get a particularly strong one anyway. I feel like this is nothing more than a QoL fix for them, with how infrequent it even comes up.

## Changelog
:cl:
add: Emaged janitor borg space lube now refills in a charger at 5 units per tick.
/:cl:

2021-01-11 16:53 UTC, farie82 approved these changes

2021-01-11 16:53 UTC, farie82 requested changes
Clicked to fast

2021-01-11 16:53 UTC, farie82 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/robot_module/janitor/respawn_consumable(var/mob/living/silicon/robot/R)
```suggestion
/obj/item/robot_module/janitor/respawn_consumable(mob/living/silicon/robot/R)
```
Minor thing

2021-01-11 22:58 UTC, warior4356 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/robot_module/janitor/respawn_consumable(var/mob/living/silicon/robot/R)
My bad for copying legacy code then.

2021-01-12 09:39 UTC, farie82 approved these changes

2021-01-18 23:24 UTC, Kyep approved these changes

2021-01-20 10:09 UTC, AffectedArc07 approved these changes

2021-01-20 10:10 UTC, merged