Updates code to be compatible with new lints
ParadiseSS13/Paradise pull request #15290
Opened 2021-01-14 13:34 UTC by AffectedArc07

## What Does This PR Do
Updates codebase to not error on the latest batch of vscode lints provided by the langserver extension. I will bump CI dreamchecker when a version of it comes out.

I have tested map saving, emote cooldowns and overlay compiling. Event stuff has *not* been tested but nothing should break. 

## Why It's Good For The Game
People shouldnt have false positives in the error list.

## Changelog
:cl: AffectedArc07
fix: Improved some code quality
/:cl:

2021-01-14 13:42 UTC, farie82 requested changes

2021-01-14 13:42 UTC, farie82 commented on code/modules/awaymissions/maploader/writer.dm
>  				break
```suggestion
		for(var/y_pos = 1; y_pos < length(z_block); z_pos = findtext(z_block, ";", y_pos) + 1)
```

2021-01-14 13:42 UTC, farie82 commented on code/modules/awaymissions/maploader/writer.dm
>  					break
```suggestion
			for(var/x_pos = 1; x_pos < length(y_block); x_pos = findtext(y_block, ",", x_pos) + 1)
```

2021-01-14 13:42 UTC, farie82 commented on code/modules/awaymissions/maploader/writer.dm
> +				x_pos = findtext(y_block, ",", x_pos) + 1
```suggestion
```

2021-01-14 13:42 UTC, farie82 commented on code/modules/awaymissions/maploader/writer.dm
> +		z_pos = findtext(template_buffer_text, ".", z_pos) + 1
```suggestion
```

2021-01-14 13:42 UTC, farie82 commented on code/modules/awaymissions/maploader/writer.dm
>  			break
```suggestion
	for(var/z_pos = 1; z_pos < length(template_buffer_text); z_pos = findtext(template_buffer_text, ".", z_pos) + 1)
```
Can all be made in one for loop

2021-01-15 18:05 UTC, variableundefined approved these changes

2021-01-15 18:05 UTC, merged