Makes toilet bashing apply damage to the head.
ParadiseSS13/Paradise pull request #15302
Opened 2021-01-16 19:06 UTC by hal9000PR

## What Does This PR Do
Makes slamming someone into a toilet apply damage only to the head

## Why It's Good For The Game
adds to the immersion, makes little sense to slam someone into a toilet and the damage to be equally distributed. slamming their head into a toilet makes a lot more sense. 

## Changelog
:cl:
tweak: makes slamming people into toilets do damage to the head
/:cl:

2021-01-16 19:15 UTC, dearmochi requested changes

2021-01-16 19:15 UTC, dearmochi commented on code/game/objects/structures/watercloset.dm
> +		swirlie.apply_damage(5,BRUTE,"head")
```suggestion
		swirlie.apply_damage(5, BRUTE, BODY_ZONE_HEAD)
```

2021-01-16 19:15 UTC, dearmochi commented on code/game/objects/structures/watercloset.dm
> +						GM.apply_damage(5,BRUTE,"head")
```suggestion
						GM.apply_damage(5, BRUTE, BODY_ZONE_HEAD)
```

2021-01-16 19:15 UTC, dearmochi commented on code/game/objects/structures/watercloset.dm
> +				GM.apply_damage(8,BRUTE,"head")
```suggestion
				GM.apply_damage(8, BRUTE, BODY_ZONE_HEAD)
```

2021-01-16 20:46 UTC, S34NW commented
what if you slam a headless IPC?

2021-01-20 22:54 UTC, Kyep approved these changes

2021-01-23 00:48 UTC, Kiyahitayika commented
> what if you slam a headless IPC?

@dearmochi 's suggested edits account for this by applying damage directly to the "head" body part.

2021-02-03 15:32 UTC, AffectedArc07 approved these changes

2021-02-03 15:32 UTC, merged