Gives some tells to using holy water on vampire thralls.
ParadiseSS13/Paradise pull request #15329
Opened 2021-01-21 20:32 UTC by Qwertytoforty

## What Does This PR Do

Adds a 10% and 5% chance for tells on vampire thralls that they are a thrall, when holy water has been in their system for over 60 seconds.

## Why It's Good For The Game

Vampire thralls have been in a problematic state for deconversion. While you give a vampire 5 units to see if they are a vampire, thralls currently require _35 units_ to deconvert, and have no tells that they are in the process of being deconverted. This leads to a few things happening, be it vampire thralls never being deconverted, put into perma for aiding when they are thralled, being executed as officers think they are a vampire, and they show no reaction to holy water, ect.

This way, at least after a bit of time, you start to get evidence the person is a thrall, and know that with more time and holy water they will be deconverted.

Could probably use some better reactions to holy water if people can think of them, but they can not be the same as vampires, as that would just make officers think the thrall is a vampire, and lead to the same issue.

## Changelog
:cl:
tweak: Vampire thralls now have a tell that they are being deconverted, after 60 seconds of having holy water in their system..
/:cl:

2021-01-21 20:44 UTC, hal9000PR commented
Thanks. this is really needed as it isn't very intuitive to dethrall vampire thralls.

2021-01-21 20:47 UTC, farie82 requested changes

2021-01-21 20:47 UTC, farie82 commented on code/modules/reagents/chemistry/reagents/water.dm
> +					O.show_message(text("<span class = 'warning'> A fog lifts from []'s eyes for a moment, but soon returns.</span>", M), 1)
```suggestion
				M.visible_message("<span class='warning'>A fog lifts from [M]'s eyes for a moment, but soon returns.</span>")
```
Should act the same

2021-01-21 21:03 UTC, dearmochi approved these changes

2021-01-21 21:04 UTC, farie82 approved these changes

2021-01-22 06:16 UTC, SteelSlayer approved these changes

2021-01-24 13:33 UTC, AffectedArc07 approved these changes

2021-01-24 13:33 UTC, merged