Improves Geiger Counters; Allows Toggle
ParadiseSS13/Paradise pull request #15366
Opened 2021-01-27 08:23 UTC by Fox-McCloud

Refactors Geiger counters a bit--they should be a hair bit more responsive than they previously were---this was partially inspired by TG, but they use a whole other system called `delta_time` to handle processing differently.

This also corrects a couple of issues @SteelSlayer brought up in the original radiation PR review.

And lastly, this also allows you to toggle a hardsuit helmet's geiger counter on or off--after having witnessed this, the past few days, there's definitely circumstances where you'd just not want to put up with it blaring out when it's obvious you or the things around you are emitting radiation and you just don't need to know anymore. The counter, though, defaults to `on` for hardsuit helmets, unlike regular geiger counters.

:cl: Fox McCloud
tweak: Geiger counters should be a hair bit more responsive
add: Can toggle hardsuit helmet's geiger counter on and off now
/:cl:

2021-01-27 08:38 UTC, farie82 requested changes

2021-01-27 08:38 UTC, farie82 commented on code/game/objects/items/devices/geiger_counter.dm
>  		to_chat(usr, "<span class='warning'>[src] must be on to reset its radiation level!</span>")
```suggestion
		to_chat(user, "<span class='warning'>[src] must be on to reset its radiation level!</span>")
```

2021-01-27 08:38 UTC, farie82 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +		loop.stop(loc)
```suggestion
	if(!scanning || !radiation_count)
		loop.stop(loc)
```

2021-01-28 21:39 UTC, farie82 approved these changes

2021-01-30 23:22 UTC, AffectedArc07 approved these changes

2021-01-30 23:22 UTC, merged