Gives shadowlings the ability to destroy mindshields
ParadiseSS13/Paradise pull request #15409
Opened 2021-02-01 13:26 UTC by ppi13

## What Does This PR Do

Alternative to #14956 and an attempt to fix the merge conflict in #14965
After #14521 was added over a month ago, we got a severe case of I ded pls nerf, where shadowlings lost every round, which honestly, was fine for me. However, on the forum there was a thread for this as well, and there was a pretty good suggestion, where destroying mind shields is part of the progressive powerup.  
Currently it takes 30 seconds to destroy an implant with a 90 second cooldown.
In an average round of 100 players a sling will learn this ability at somewhere between 6-7 thralls.

## Why It's Good For The Game

This is a better alternative to reverting #14521
This should also halt shadowling turning into murderboner security and then shadowlings lose. 

## Images of changes

## Changelog
:cl: ppi
add: Add a mindshield melt ability to shadowlings
/:cl:

2021-02-01 23:02 UTC, Cocacolagua commented
Good alternative, only complaint is that it would be better to have it be a passive ability instead of an active one (once you reach the power, the game would remove the mindshield for you), given that it would otherwise add to action buttons bloat

2021-02-01 23:22 UTC, Dafrek commented
It seems to me like this would make the shadowing skill floor and ceiling even farther apart as more experienced players would be able to thrall enough people to be able to destroy mindshields and thrall sec by the time they showed up, while new players would be unable to do so and be forced to kill or be killed by sec. However, with how badly #14521 changed slings over three months ago and now that #14956 is closed after an internal discussion, I wouldn't mind seeing this implemented.

2021-02-16 04:47 UTC, DinBlade commented
I have issues with this for simple fact it is 5 steps of ghetto surgery to remove a mindshield, and there are two table they can get from arrival maint or assembly line, to give them a better chance to succeed. This is just saying that the people playing Slings are too new/ or not learned enough to be trusted to do well and need a hard coded way to make them better to be in a better spot, Hell just saying to at shift start "dead bodies can't be converted" so they stop murderboning mindshields would be a hard code change to remind they need LIVING thralls. that is just a flavor line.

2021-02-20 11:02 UTC, AffectedArc07 requested changes

2021-02-20 11:02 UTC, AffectedArc07 commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +	var/enthralling = FALSE
```suggestion
	var/enthralling = FALSE
```
Please clean up the copypaste.

2021-02-20 11:02 UTC, AffectedArc07 commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +		target.setOxyLoss(0) //In case the shadowling was choking them out
Should they really get an insta heal here?

2021-02-21 11:47 UTC, ppi13 commented
![image](https://user-images.githubusercontent.com/21987702/108624096-e3983a00-7442-11eb-8a4a-75a5c9316783.png)
![image](https://user-images.githubusercontent.com/21987702/108624097-e98e1b00-7442-11eb-9118-63e754373418.png)

2021-02-21 21:39 UTC, AffectedArc07 requested changes

2021-02-21 21:39 UTC, AffectedArc07 commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +			mindshield_melt_acquired = 1
```suggestion
			mindshield_melt_acquired = TRUE
```

2021-03-08 15:53 UTC, dearmochi requested changes

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +		to_chat(user, "<span class='danger'>This target is mindshielded. You begin the destroying the implant.</span>")
```suggestion
		to_chat(user, "<span class='danger'>This target is mindshielded. You begin destroying the implant.</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +					user.visible_message("<span class='warning'>[user] places [user.p_their()] hands onto the sides of [target]'s head!</span>")
```suggestion
					user.visible_message("<span class='warning'>[user] places [user.p_their()] hands onto the sides of [target]'s head!</span>", "<span class='notice'>You place your hands to [target]'s head...</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +					user.visible_message("<span class='warning'>[user]'s palms flare a bright red against [target]'s temples!</span>")
```suggestion
					user.visible_message("<span class='warning'>[user]'s palms flare a bright red against [target]'s temples!</span>", "<span class='notice'>You are preparing to destroy [target]'s mindshield.</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +					to_chat(target, "<span class='danger'>A terrible red light floods your mind. Your mindshield implant becomes hot as it comes under attack!.</span>")
```suggestion
					to_chat(target, "<span class='danger'>A terrible red light floods your mind. Your mindshield implant becomes hot as it comes under attack!</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +					user.visible_message("<span class='warning'>[user] relaxes again.</span>")
```suggestion
					user.visible_message("<span class='warning'>[user] relaxes again.</span>", "<span class='notice'>The nanobots composing the mindshield implant have been rendered inert. Now to continue.</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +				to_chat(user, "<span class='warning'>The mindshield removal has been interrupted - the nanobots of your target's mindshields returns to its previous state.</span>")
```suggestion
				to_chat(user, "<span class='warning'>The mindshield removal has been interrupted - the nanobots of your target's mindshield return to their previous state.</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +				to_chat(target, "<span class='userdanger'>You wrest yourself away from [user]'s hands and compose yourself</span>")
```suggestion
				to_chat(target, "<span class='userdanger'>You wrest yourself away from [user]'s hands and compose yourself!</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +		target.visible_message("<span class='big'>[target] looks to have experienced a sense of liberation!</span>")
```suggestion
		to_chat(user, "<span class='shadowling'>You have destroyed the mindshield of [target]!</span>")
		target.visible_message("<span class='big'>[target] looks to have experienced a sense of liberation!</span>")
```

2021-03-08 15:53 UTC, dearmochi commented on code/game/gamemodes/shadowling/shadowling_abilities.dm
> +	if(ismindshielded(target))
I'd probably add this check to `valid_target`, so that the spell isn't cast and wasted on a non-mindshielded person.

2021-05-10 15:44 UTC, Daylight2 commented
_Pokes PR_

Is this thing going to get worked on, or...?

2021-07-26 17:56 UTC, variableundefined commented
No follow up for 90+ days, closing.

2021-07-26 17:56 UTC, closed without merging