Prevents the possessor crystal from possessing bots
ParadiseSS13/Paradise pull request #15424
Opened 2021-02-03 01:57 UTC by Qwertytoforty

## What Does This PR Do

Adds an isbot() check to the things that will make creatures the possessor crystal detects an invalid target.

## Why It's Good For The Game

We made sentient beepskys / ed209's impossible for a reason, and removed the PAI abilities. Let us NOT have sentient ones again, or a sentient depot bot, thanks.

## Changelog
:cl:
tweak: Possessor crystal can no longer possess bots.
/:cl:

2021-02-03 11:50 UTC, hal9000PR commented
How worth while is the anomalous crystal to keep around? It is a very problematic item in almost all regards, the only reason we still have it is because it is rare.

2021-02-04 16:39 UTC, farie82 requested changes

2021-02-04 16:39 UTC, farie82 commented on code/modules/mining/lavaland/loot/colossus_loot.dm
> +				if(A.melee_damage_upper > 5 || A.mob_size >= MOB_SIZE_LARGE || A.ckey || A.stat || isbot(A) )
```suggestion
				if(A.melee_damage_upper > 5 || A.mob_size >= MOB_SIZE_LARGE || A.ckey || A.stat || isbot(A))
```

2021-02-04 18:51 UTC, Kyep approved these changes

2021-02-06 16:22 UTC, farie82 approved these changes

2021-02-10 18:21 UTC, AffectedArc07 approved these changes

2021-02-10 18:21 UTC, merged