Re-adds engineering items to secure storage
ParadiseSS13/Paradise pull request #15458
Opened 2021-02-07 13:48 UTC by Cocacolagua

## What Does This PR Do
Re-adds six fifty-metal stacks, four fifty-glass stacks, two fifty-wood stacks, two engineering suit storages and four floodlights to secure storage.
(Half of the metal and glass was placed in engineering main storage to not overload the crate)

## Why It's Good For The Game
All of these items were removed from secure storage with the addition of the supermatter, i'm re-adding given that these are quite important for engineering, being it constructing anything else, repairing breaches or lighting a place up without having to build lights.

## Images of changes

Before:
![naNgAwRhe6](https://user-images.githubusercontent.com/48032385/107148397-917af300-6931-11eb-82f3-e9523c1f19e2.png)

After:
![OHgk3sJOzO](https://user-images.githubusercontent.com/48032385/107148396-9049c600-6931-11eb-9a4b-4ac18a1599f4.png)

## Changelog
:cl:
add: Adds three fifty-metal sheets stacks and two fifty-glass sheets stacks to engineering main storage.
add: Adds three fifty-metal sheets stacks, two fifty-glass sheets stacks, two fifty-wood planks stacks, two engineering suit storages and four floodlights to engineering secure storage.
/:cl:

2021-02-07 16:25 UTC, SteelSlayer approved these changes

2021-02-07 16:27 UTC, SabreML commented
The hardsuits are the most important part I think, since if an engineer cryoes with one there's no way to get it back.

2021-02-07 21:25 UTC, Kyep approved these changes

2021-02-07 22:18 UTC, DeusExVita commented
even with this, we are missing out on 2stacks of metal, 2stacks of glass, 2 hardsuits, a pacman, and two fireclosets, the maint stuff being the mats and the hardsuits, as those are rare early game and can help engies make fun things/ actually be able to build.

2021-07-09 22:46 UTC, SabreML commented
Since you're editing this area already, could you also add a button on the inside of Secure Storage? Currently there's only one on the outside so it's pretty easy to get trapped.

2021-07-11 01:43 UTC, Spacemanspark commented
But that's funny

2021-07-15 11:42 UTC, dearmochi approved these changes

2021-07-15 13:05 UTC, AffectedArc07 commented
This PR is currently conflicted, and is being skipped in the mapping queue. 

Please deconflict within 7 days.

2021-07-15 16:03 UTC, AffectedArc07 requested changes

2021-07-15 16:03 UTC, AffectedArc07 commented on _maps/map_files/cyberiad/cyberiad.dmm
> +/area/security/processing)
Something has fucked the keys up in this map with random moves, and a random diff off in the distance in medmaint.

Requesting you copy your edit to a temp file, grab the latest version of cyberiad, and then edit from there.

2021-07-15 21:20 UTC, AffectedArc07 approved these changes

2021-07-15 21:20 UTC, merged