Splits crewsimov law 1 into two, adds self-harm exception
ParadiseSS13/Paradise pull request #15478
Opened 2021-02-08 16:05 UTC by TDSSS

## What Does This PR Do
This PR changes crewsimov into being the following four laws:

1. "You may not harm a crew member."
2. "You must prevent crew members from being harmed except through self-harm, unless doing so would conflict with the First Law."
3. "You must obey orders given to you by crew members, except where such orders would conflict with the First or Second Law."
4. "You must protect your own existence as long as such does not conflict with the First, Second or Third Law."

Note that the original asimov lawset is unchanged.

## Why It's Good For The Game
The existing law 1 allows, in some circumstances, to harm crew to prevent greater harm, such as harmbatoning a traitor or shocking doors in his path. I think that strongly encourages Silicon players to see themselves as on the 'side' of sec against the antags and encourages validhunting. IMO, a crewsimov AI should not focus on stopping or finding antagonists, and definitely shouldn't be looking to kill them in the name of 'preventing harm'.

Putting 'don't harm people' in its own law that has priority over stopping harm should make it crystal clear that a crewsimov Silicon should never, ever be harming crew and help discourage validhunting and overly bloodthirsty Silicones. 

I also put in an exception for self-harm. Currently, self-harm is covered by ooc rules telling AIs they can ignore threats of self-harm and don't have to save people trying to commit suicide, but imo it can't hurt to have it written down while I was rewriting law 1 anyway.

**FAQ**

> This ruins the reference to asimov's laws >:

Yes, sadly it does. We've already modified them but I admit diverging from the original wording more makes them harder to recognise. But IMO, positive gameplay impact > neat reference. Also, the actual asimov lawset remains unchanged as a reference.

> Are sec borgs useless on crewsimov now?

No. Remember that stuns, disables and co are not considered harm. Sec borgs are still free to stun and cuff a murderous criminal. They are just barred from doorcrushing, doorshocking, harmbatoning and similar now.

> How will I, as an AI, now stop the murderous desword traitor!?

You don't. You're not security, getting the murderous desword traitor is not your task unless you get a law change to robocop or paladin.

> Seriously tho, the murderous desword traitor on adrenals with a holopara is causing crew harm in medbay and I can't doorcrush him now, what do?

Tell crew to run away. Lock doors in his path. Tell security where he can be found so they can stop him. Try to distract him. Get creative.
## Changelog
:cl:
tweak: Crewsimov law 1 has been split into two
/:cl:

2021-02-08 16:10 UTC, matttheficus commented
It may be nitpicky, but in my opinion Crewsimov should stay as slightly altered Asimov, due to it being such a staple of SciFi/SS13 culture is a MASSIVE portion of the Law's existence and shouldnt be ignored. If there is an issue with AIs causing Harm on this Lawset, they should be bwoinked or dealt with OOCly, as theyre actively breaking their Laws. If people cant understand "your Lawset LITERALLY says you cant cause harm", they shouldnt be playing AI in the first place.

2021-02-08 16:12 UTC, TDSSS commented
@matttheficus The thing is, the official interpretation is you **can** cause crew harm to prevent greater crew harm, as a last resort. Because preventing harm and not doing harm are in the same law, you can weigh one against the other.

2021-02-08 16:48 UTC, Gatchapod commented
I was nearly outright told it's expected from crewsimov AI to prevent massive crew harm, even at the cost of bending law 1. This leads me to believe admin team wants crewsimov AIs to validhunt extremely high profile antagonists.

I'm torn here. While I definitely support limiting silicons' ability to validhunt, I feel like certain degree of ambiguity is THE spirit of Asimov's laws. That spirit being undeniable individuality of positronic brains and their capacity to interpret the laws differently, based on circumstances and personal beliefs.

2021-02-09 00:00 UTC, Dashsora commented
> I was nearly outright told it's expected from crewsimov AI to prevent massive crew harm, even at the cost of bending law 1. This leads me to believe admin team wants crewsimov AIs to validhunt extremely high profile antagonists.


The big problem I see is that AIs will ONLY bend the rule 1 to prevent "massive crew harm" when it's to fight against antagonists, on the side of the station, never the opposite.

If I card an AI, tell them to cooperate or I kill everyone in my path, they'll either completely disregard my threats, or start shouting CREW HAAARM CREWWWW HARRRRMM the moment I defend myself against a seccie, potentially injuring them, and then the deal's off the table.

2021-02-24 00:15 UTC, Kyep requested changes
I don't like this.
It kinda ruins the reference, and it stops crewsimov AIs harming anyone even if that person is, say, delamming the supermatter.

2021-02-24 07:33 UTC, TDSSS commented
> It kinda ruins the reference, and it stops crewsimov AIs harming anyone even if that person is, say, delamming the supermatter.

I mean yes, that's the entire idea, imo a crewsimov AI should never be able to harm crew full stop, "preventing greater harm" feels like a huge copout

2021-05-13 04:58 UTC, LiberatedWaveMan commented
> I'm torn here. While I definitely support limiting silicons' ability to validhunt, I feel like certain degree of ambiguity is THE spirit of Asimov's laws. That spirit being undeniable individuality of positronic brains and their capacity to interpret the laws differently, based on circumstances and personal beliefs.

This is exactly how I feel regarding the matter, and it's certainly a tough split

2021-05-14 19:44 UTC, dearmochi approved these changes
Approved for code

2021-07-26 17:48 UTC, variableundefined commented
No head or maint approval, one objection. Been here for 120+ days. 

Closing.

2021-07-26 17:48 UTC, closed without merging