Small borg sound effect tweaks
ParadiseSS13/Paradise pull request #15488
Opened 2021-02-09 19:13 UTC by E-MonaRhg

## What Does This PR Do

This PR makes a previously unused sound effect play when a borg gets emagged. Also lengthens the emagging freeze for borgs a tiny bit so the sound effect can play properly.
Changes the destroyer and death squad to use Nanotrasen instead of Syndicate initialization sound effect.

## Why It's Good For The Game

A good sounding effect that is very appropriate to a borg getting emagged yet was used nowhere. Now it is.
Also it makes sense that Nanotrasen borgs would use Nanotrasen sound effects instead of Syndicate ones.

## Changelog
:cl:
tweak: Emagging a borg now plays a sound effect for them
tweak: Made the emagging freeze for borgs a bit longer for the sound effect to play better
tweak: Destroyer and death squad borgs now play the Nanotrasen initialization sound effect
/:cl:

2021-02-09 19:47 UTC, dearmochi requested changes

2021-02-09 19:47 UTC, dearmochi commented on code/modules/mob/living/silicon/robot/robot.dm
> +			playsound_local(src, 'sound/voice/aisyndihack.ogg', 75, 0)
```suggestion
			playsound_local(src, 'sound/voice/aisyndihack.ogg', 75, FALSE)
```

2021-02-09 19:47 UTC, dearmochi commented on code/modules/mob/living/silicon/robot/robot.dm
> +	playsound(loc, 'sound/mecha/nominalnano.ogg', 75, 0)
```suggestion
	playsound(get_turf(src), 'sound/mecha/nominalnano.ogg', 75, FALSE)
```

2021-02-09 19:47 UTC, dearmochi commented on code/modules/mob/living/silicon/robot/robot.dm
> +	playsound(loc, 'sound/mecha/nominalnano.ogg', 75, 0)
```suggestion
	playsound(get_turf(src), 'sound/mecha/nominalnano.ogg', 75, FALSE)
```

2021-02-10 02:11 UTC, SteelSlayer approved these changes

2021-02-24 00:05 UTC, Kyep approved these changes

2021-02-24 12:57 UTC, dearmochi approved these changes

2021-02-25 15:56 UTC, AffectedArc07 approved these changes

2021-02-25 15:56 UTC, merged