Allows blob mobs to move via blob tiles in zero-g
ParadiseSS13/Paradise pull request #15506
Opened 2021-02-12 05:23 UTC by warior4356

## What Does This PR Do
Allows blob tiles to work for stopping zero g drift for blob mobs and allows them to push off blob tiles when "stuck" in zero-g.

## Why It's Good For The Game
All other mobs are stopped by these tiles, however similar to spiders and webs, because the blob mobs don't collide with the blob tiles they are not stopped in zero g. This means blob mobs can be "stuck" floating on blob or float straight through the blob. This allows blob mobs to move around on blob in zero-g, as well as be stopped by them if they are drifting into them, instead of floating straight through.

## Changelog
:cl:
fix: Fixes blob mobs not interacting with blob tiles for zero-g movement
/:cl:

2021-02-14 09:41 UTC, Fox-McCloud commented on code/game/gamemodes/blob/blobs/blob_mobs.dm
> +/mob/living/simple_animal/hostile/blob/get_spacemove_backup()
This should be

```
/mob/living/simple_animal/hostile/blob/Process_Spacemove(movement_dir = 0)
	for(var/obj/structure/blob/B in range(1, src))
		return TRUE
	return ..()
	```

2021-02-14 09:42 UTC, Fox-McCloud requested changes

2021-02-14 09:42 UTC, Fox-McCloud commented on code/game/gamemodes/blob/blobs/blob_mobs.dm
> +/mob/living/simple_animal/hostile/blob/get_spacemove_backup()
This should be

```
/mob/living/simple_animal/hostile/blob/Process_Spacemove(movement_dir = 0)
	for(var/obj/structure/blob/B in range(1, src))
		return TRUE
	return ..()
```

2021-02-15 22:00 UTC, Kyep approved these changes

2021-02-26 15:30 UTC, AffectedArc07 approved these changes

2021-02-26 15:30 UTC, merged