Shaking the dead now gives a message indicating the person is dead
ParadiseSS13/Paradise pull request #15512
Opened 2021-02-12 16:27 UTC by Kepplerx

## What Does This PR Do
It fixes (https://github.com/ParadiseSS13/Paradise/issues/15504) by replacing the message for shaking someone with a message for shaking the dead (That being the dead who had not taken damage beyond crit).

## Why It's Good For The Game
Shaking the dead now no longer results in a weird message, if they were dead but not damaged beyond crit.

## Images of changes

## Changelog
:cl:
fix: Fixed a issue with response messages for a target being dead
/:cl:

2021-02-12 16:34 UTC, Kepplerx commented
This is my second ever coding work, and is somewhat more difficult than the previous one I did. As far as I understand this should work, as I added a check for if dead, then moved the rest of the help_shake under the new check. That said any tips or such are appreciated, this may after all be bad coding work.

2021-02-14 22:07 UTC, farie82 requested changes

2021-02-14 22:07 UTC, farie82 commented on code/modules/mob/living/carbon/carbon.dm
> +	if(stat == DEAD)
This currently does not check if `M` is the same as `src`. AKA if the dead guy is trying to shake himself up.
Currently you'll get a message saying X tries to shake himself up

2021-02-14 22:07 UTC, farie82 commented on code/modules/mob/living/carbon/carbon.dm
> +	else
Early returns are preferred over `else`'s if you can help it.
Example of one:
```dm
/proc/test(A, B)
 if(A != 420)
  to_chat(usr, "invalid A")
  return // This is an early return.
 to_chat(usr, "valid params")
 return B * A
```
And then how it looks with an else:
```dm
/proc/test(A, B)
 if(A != 420)
  to_chat(usr, "invalid A")
 else
  to_chat(usr, "valid params") // non early return
  return B * A
```

2021-02-15 21:59 UTC, Kyep approved these changes

2021-02-20 10:47 UTC, AffectedArc07 requested changes
Please look into Farie's changes

2021-03-14 10:38 UTC, AffectedArc07 approved these changes

2021-03-14 10:38 UTC, merged