Removes all access requirements from R&D consoles.
ParadiseSS13/Paradise pull request #15537
Opened 2021-02-16 00:05 UTC by warior4356

## What Does This PR Do
As the title states, this PR removes all access requirements from R&D consoles and all mechfabs. 

## Why It's Good For The Game
I brought up the idea previously of making the mechfab consistent with the R&D console and the mechanic's space pod fab where it would be locked to robotics. See #15524. This PR exists as an alternative to achieve consistency in the other direction, as I was given feedback in the comments of the other PR that doors should be a sufficient barrier to prevent access, and if someone gets into the room they should be able to make things on the mech fab. This brings R&D and mechanic in line with the robotics fabricator where if you can get into the room you can make anything you want on the fabricator.

## Changelog
:cl:
del: Removed access requirement for R&D computer
del: Removed access requirement for robotics computer
del: Removed access requirement for mechanic computer and fabricator
/:cl:

2021-02-16 00:06 UTC, AffectedArc07 commented
Absolutely fucking not.

2021-02-16 00:07 UTC, Coolrune206 commented
There already exists a "Public R&D Console" for a reason. 

Besides, if anyone could jump the desk in science and print whatever they want... jeez, can you just imagine how that'll go? Sec seeing an open window and deciding to hop over and print themselves a bunch of implants?

2021-02-16 00:12 UTC, Spacemanspark commented
The last thing we need is everyone having access to RnD. Please for the sake of sanity no.

2021-02-16 00:13 UTC, shmabuu commented
R&D has access to so much, it's locked behind a science ID for a reason. 

> if anyone could jump the desk in science and print whatever they want

This can go for all the consoles and machines.

2021-02-16 00:13 UTC, BryanPara commented
I understand the point you're trying to make but, I can't think of anyone on staff, heads or not, that would support this...

2021-02-16 00:13 UTC, optimumtact commented
What an incredibly dent headed and stupid idea, there's no reason to discuss this because it's patently obviously bad as soon as you view the title

2021-02-16 00:50 UTC, Fox-McCloud commented
If we are to do this, it should wait until after techwebs, given how it changes functionality of things.

2021-02-16 01:45 UTC, Kyep requested changes
Objection.
I prefer inconsistency over poor balance.

2021-02-18 20:22 UTC, warior4356 commented
Saving time and closing this. I was making the PR to act on Fox's comment on my other PR, but it's clear that if this is going to be added in some form it will be after tech webs.

2021-02-18 20:22 UTC, closed without merging