Adds a rad-proofing potion to xenobio
ParadiseSS13/Paradise pull request #15591
Opened 2021-02-22 22:10 UTC by hal9000PR

## What Does This PR Do
Adds a potion that can be used to rad proof an item of clothing, it has 3 uses and is made with water and a green slime extract

## Why It's Good For The Game
Rads are still really potent. There is only one rad  and fire proof suit on the station, the CEs. This is fine until the SM starts to delam in a spectacular fashion, spewing fire and rads everywhere. This makes this means that if the CE is dead/unavailable/incompetent, all of which happen alot there still might be a suit that is up to even stepping into engineering. 

Also it adds more ways for xenobio to contribute and help the  station that aren't armies of valid unga mobs.  

## Changelog
:cl:
add: Adds a water + green slime reaction that makes a rad-proofing potion
/:cl:

2021-02-22 22:12 UTC, TDSSS commented
Not a fan of science rendering all rad suits completely useless once they've bred some slimes.

2021-02-22 22:31 UTC, S34NW commented
Perhaps just rad-resistance? as opposed to rad-proof? Would be more balanced since sci already has a lot of strong stuff...

2021-02-22 22:43 UTC, kenken244 commented
I think rad resistance would be fine as long as it still can give immunity if used on a piece of gear that is already rad resistant. there isn't much functional difference between rad resistance and immunity, since rads are not used as a weapon. and the case of there being only one rad immune piece of gear still stands

2021-02-22 23:21 UTC, Leanfrog commented
I mean, this isn't even that much of a buff, radiation damage comes from like 4 things across the game, two of which are pitifully slow and the other is basically exclusive to one department

2021-02-22 23:44 UTC, PidgeyThePirate commented
As long as you can use it to dye gear green.

2021-02-22 23:49 UTC, dearmochi requested changes

2021-02-22 23:49 UTC, dearmochi commented on code/modules/reagents/chemistry/recipes/slime_extracts.dm
> +	required_other = 1
```suggestion
	required_other = TRUE
```

Seems to be a boolean from what I can tell

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +	desc = "A potent chemical mix that will radproof any article of clothing. Has three uses."
```suggestion
	desc = "A potent chemical mix that will radiation proof any article of clothing. Has three uses."
```

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +		to_chat(user, "<span class='warning'>[C] is already radproof!</span>")
```suggestion
		to_chat(user, "<span class='warning'>[C] is already radiation proof!</span>")
```

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +	to_chat(user, "<span class='notice'>You spread the green paste over [C], rad-proofing it.</span>")
```suggestion
	to_chat(user, "<span class='notice'>You spread the green paste over [C], radiation proofing it.</span>")
```

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +	uses --
```suggestion
	uses--
```

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +	C.color = "#00FF00"
```suggestion
	C.color = COLOR_GREEN
```

2021-02-22 23:49 UTC, dearmochi commented on code/modules/research/xenobiology/xenobiology.dm
> +	C.armor.rad = 100
```suggestion
	C.armor.setRating(rad_value = 100)
```

2021-02-23 05:04 UTC, Wojz commented
This is good and allows you to make radproof hardsuits, which allows for interesting high-energy SM setups that can be maintained by more than one person (also have you seen what the singulo does now, in an event someone sets one up?). 

For those who say this is a science buff, not really, it gives the most annoying, validhunty area of science something to do that does not increase the chaos of the round. Which with the kind of pops we've been having, is a blessing, and I'll take it. This isn't a combat upgrade, you cannot really weaponize it, so it does not make science antags more powerful. It is also on the opposite side of slime genealogy from gold slimes, and quite far away from the two other common ones, yellow and red. So it makes xenobio have more to do in general.

2021-02-23 09:25 UTC, Fox-McCloud commented
>Not a fan of science rendering all rad suits completely useless once they've bred some slimes.

Yeah, I don't like this either---the SM entering failure state is something that is supposed to be a big challenge to fix---engineers can do it for a little bit until rads overcome them, or someone in a radsuit can try to attend to it but take damage from space and other sources----the CE is the man to be when it comes to handling the SM, which is by design.

Having everyone able to do everything or near everything with a modicum of effort is not where I want the game to be; some things should be soft-locked or at least you have to put a lot of effort into it.

I'm not a big fan of this, personally. 👎

2021-02-23 09:40 UTC, hal9000PR commented
> > Not a fan of science rendering all rad suits completely useless once they've bred some slimes.
> 
> Yeah, I don't like this either---the SM entering failure state is something that is supposed to be a big challenge to fix---engineers can do it for a little bit until rads overcome them, or someone in a radsuit can try to attend to it but take damage from space and other sources----the CE is the man to be when it comes to handling the SM, which is by design.
> 
> Having everyone able to do everything or near everything with a modicum of effort is not where I want the game to be; some things should be soft-locked or at least you have to put a lot of effort into it.
> 
> I'm not a big fan of this, personally. 👎

1) this will not happen every round
2) giving all the power to fix the station to one person isn't the best idea. The stations fate riding on a single person who is potentially incompetent or dead isn't exactly ideal. 
3) xenobio can already fire proof items, but this doesn't create issues despite fire being able to be used in combat. I really don't see the issue of "making rad suits useless" when 1, rad suits happen every round, this will not 2, xenobio already makes firesuits useless and this isn't an issue 3,  radsuits are really ugly.

2021-02-23 23:58 UTC, Kyep commented
I don't like this either.

2021-02-24 13:36 UTC, hal9000PR commented
How about adding like 50 or so rad armour instead of rad immunity?

2021-02-24 19:57 UTC, S34NW commented
> 
> 
> How about adding like 50 or so rad armour instead of rad immunity?

That does make more sense, otherwise, you could walk up to the SM in a t-shirt or something silly and be fine.

2021-02-24 23:53 UTC, Sikroth commented
> 2. giving all the power to fix the station to one person isn't the best idea. The stations fate riding on a single person who is potentially incompetent or dead isn't exactly ideal.

Regardless of wether or not this PR gets merged (looking unlikely), I agree with this statement 100%. Hardly any role in the station is "irreplaceable" for a number of reasons. Not only because they might be unable to fix it (incompetent or dead), but also because the CE can roll antag (and honestly most head roles tend to be played by antag players more often than not), so having the CE exclusively being able to work with the SM is basically a free "fuck over the entire engi department" button if they decide to sabotage the SM.

And as repeatedly stated noone bats an eye to the fireproofing potions. The CE/Atmos hardsuits are already kinda powergamey suits because of being fireproofed, and fireproof extracts haven't been brought up as problematic. These won't be made nearly often enough to "trivialize" the SM anyway.

I would consider if this PR gets rejected as an alternative some sort of rad-removal extract that maybe cleanses irradiated objects in a largeish area. So you can clean rad contamination if it happens (which honestly I only have seen it happen when dumb CEs walk away from fixing a SM leaving a glowing green trail behind, anyway) which would benefit a lot of people if said contamination ever happens, but without making people straight up immune to rads (and would be more reactive instead of preemptive). idk just throwing ideas. I like adding stuff to xenobio that isn't immediately powergamey and that can benefit the station and the new rads is a good unexplored niche for that.

2021-02-25 08:17 UTC, TDSSS commented
Other engineers can work on the SM, even an energised SM about to go boom. They just take some radiation in the process. It gives it a very chernobyl vibe, imo. People sacrificing themselves to prevent the disaster, etc.

2021-02-25 08:40 UTC, hal9000PR commented
Clearly, radproofing isn't the way to go so, here's two alternative ideas, feel free to comment on which you think is better (or even if you dislike them both) - 

rad resistance potion - same thing but adds 50 rad armour instead of radproofing the item.

Rad purging potion - a chemical made by xenobio, removes a lot of rads and has a slow metabolization rate. Making people resistant to rads temporarily (by virtue of outhealing the rads). Could have some side affects like organ damage or addiction?

2021-03-15 02:43 UTC, Fox-McCloud commented
This has been rejected. We'd rather radiation be something that requires a far more specific instance to counter, the CE to play a big role in supermatter disasters, and for nice to not have yet another thing to completely shut out yet another status effect type with little effort.

For that reason, this is going to be closed.

2021-03-15 02:43 UTC, closed without merging