Soup Drinking (and custom soups!)
ParadiseSS13/Paradise pull request #15620
Opened 2021-02-26 15:44 UTC by SabreML

## What Does This PR Do

1. Changes the sound for eating a bowl of soup to be a drinking sound, rather than crunching.
2. Adds 20 custom soup bowls to the Chef's vendor.
3. Makes a couple of things improper.

## Why It's Good For The Game

1. Too many croutons.
2. Custom soups!
3. `"That's Plate."` vs `"That's the plate."`

## Changelog
:cl:
add: Added 20 soup bowls to the Chef's vendor, for making custom soups!
tweak: Changed the sound for eating soup to be slurping rather than crunching.
spellcheck: Made plates and snack bowls improper, so no more 'That's Plate'.
/:cl:

2021-02-26 18:11 UTC, dearmochi approved these changes
I'M AT SOUP

2021-02-26 18:47 UTC, Mitchs98 commented
What do you mean you don't crunch your soup?

2021-02-26 20:35 UTC, Carthusia commented
SOUP! SOUP! SOUP! SOUP!

I love soup

2021-03-04 11:20 UTC, S34NW approved these changes
so many soup

2021-04-15 13:20 UTC, AffectedArc07 requested changes
Yes I am this picky

2021-04-15 13:20 UTC, AffectedArc07 commented on code/modules/food_and_drinks/recipes/recipes_microwave.dm
> +	result= /obj/item/reagent_containers/food/snacks/soup/wishsoup
```suggestion
	result = /obj/item/reagent_containers/food/snacks/soup/wishsoup
```

2021-04-15 14:44 UTC, LordShekelstein commented
Would you not be able to add some kind of "soup bowl" crafting recipe from wood or metal? Seems rather annoying to have to pester cargo everytime I want to make a custom soup because Gary Greytide threw his bowl away when he was done too many times. Or will there be some kind of implementation to clean the dirty soup bowls we have in-game? Overall, I'm not going to object to more food, this is just a small nitpicky thing.

2021-04-15 18:40 UTC, SabreML commented
> Would you not be able to add some kind of "soup bowl" crafting recipe from wood or metal? Seems rather annoying to have to pester cargo everytime I want to make a custom soup because Gary Greytide threw his bowl away when he was done too many times. Or will there be some kind of implementation to clean the dirty soup bowls we have in-game? Overall, I'm not going to object to more food, this is just a small nitpicky thing.

The only way currently to get more soup bowls is from the vendor and leftover bowls after someone's eaten the soup.
I *could* add a crafting recipe or something along those lines, but I figured I'd wait and see if it's actually needed after it's merged. Could be that barely anyone makes soup at all, so 20 bowls is more than enough.

2021-04-15 21:04 UTC, AffectedArc07 approved these changes

2021-04-15 21:04 UTC, merged