Maps in the HoS hardsuit
ParadiseSS13/Paradise pull request #15637
Opened 2021-02-28 11:53 UTC by S34NW

## What Does This PR Do
Adds HoS hardsuit to the HoS office suit storage units.
Moves HoS SWAT mask to the SSU.
Maps SSU into cyberiad HoS office to bring it in line with the other maps.

This PR does not look at the balance of HoS hardsuits, but here are their armour values for reference:
`armor = list("melee" = 45, "bullet" = 25, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 100, "rad" = 50, "fire" = 95, "acid" = 95)`
Versus regular sec hardsuit:
`armor = list("melee" = 35, "bullet" = 15, "laser" = 30, "energy" = 10, "bomb" = 10, "bio" = 100, "rad" = 50, "fire" = 75, "acid" = 75)`

## Why It's Good For The Game
Gives more visual and item variety, makes use of the HoS hardsuit that is currently just sitting in the code unused.
The HoS gets more equipment than the standard officer in all other situations, their trenchcoat is more damage resistant and covers all limbs, they get two energy guns at roundstart, and a telescopic shield. Adding a unique hardsuit gives them a new situational tool that also helps distinguish them at a glance from other officers.

## Images of changes
![cyberiadssu](https://user-images.githubusercontent.com/12197162/109417008-958eb380-79b9-11eb-9198-eefaa5d5fccd.png)
![HoS-hardsuit_0000_2021-02-28-11_31_33-Paradise-Station-13](https://user-images.githubusercontent.com/12197162/109417360-4184ce80-79bb-11eb-916f-177f9ad37f22.png)![HoS-hardsuit_0001_2021-02-28-11_31_25-Paradise-Station-13](https://user-images.githubusercontent.com/12197162/109417362-4184ce80-79bb-11eb-8e7b-3e831520beb7.png)![HoS-hardsuit_0002_2021-02-28-11_30_55-Paradise-Station-13](https://user-images.githubusercontent.com/12197162/109417363-421d6500-79bb-11eb-9514-4231e521eaee.png)![HoS-hardsuit_0003_Layer-0](https://user-images.githubusercontent.com/12197162/109417365-421d6500-79bb-11eb-8d21-fed89954c839.png)

## Changelog
:cl:
add: Added HoS Hardsuit Storage to all maps
/:cl:

2021-03-01 20:11 UTC, Kyep approved these changes

2021-07-15 21:25 UTC, AffectedArc07 requested changes

2021-07-15 21:25 UTC, AffectedArc07 commented on code/game/machinery/suit_storage_unit.dm
> +	req_access = list(ACCESS_HOS)
```suggestion
	suit_type = /obj/item/clothing/suit/space/hardsuit/security/hos
	mask_type = /obj/item/clothing/mask/gas/sechailer/hos
	req_access = list(ACCESS_HOS)
```

2021-07-16 11:10 UTC, AffectedArc07 commented
Closing + Reopening to kick CI into working

2021-07-16 11:20 UTC, AffectedArc07 commented
```
StdErr:

thread 'main' panicked at 'no entry found for key', src/cli/main.rs:370:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This map is fucked too. Remake the edits.

2021-07-16 15:13 UTC, AffectedArc07 approved these changes

2021-07-16 15:13 UTC, merged