Refactors and tweaks krav maga disarms
ParadiseSS13/Paradise pull request #15722
Opened 2021-03-15 20:27 UTC by S34NW

## What Does This PR Do
Refactors krav maga disarms.
Stops krav maga disarming items with the ABSTRACT flag. (like kisses and slaps)

## Why It's Good For The Game
No more kiss cannon.
No more slap stealing.

## Changelog
:cl:
tweak: refactors krav maga disarm code
fix: krav maga cannot disarm "abstract" items
/:cl:

2021-03-16 09:37 UTC, AffectedArc07 commented
Reopening for CI

2021-05-27 07:48 UTC, SabreML approved these changes
Code looks good to me.

2021-07-22 13:30 UTC, dearmochi requested changes

2021-07-22 13:30 UTC, dearmochi commented on code/modules/martial_arts/cqc.dm
> +					A.put_in_hands(I)
```suggestion
			if(D.unEquip(I) && !(QDELETED(I) || (I.flags & ABSTRACT)))
				A.put_in_hands(I)
```

2021-07-22 13:30 UTC, dearmochi commented on code/modules/martial_arts/krav_maga.dm
> +			playsound(D, 'sound/weapons/thudswoosh.ogg', 50, 1, -1)
```suggestion
	if(prob(60) && D.unEquip(I) && !(QDELETED(I) || (ABSTRACT & I.flags))
		A.put_in_hands(I)
		D.visible_message("<span class='danger'>[A] has disarmed [D]!</span>", \
							"<span class='userdanger'>[A] has disarmed [D]!</span>")
		playsound(D, 'sound/weapons/thudswoosh.ogg', 50, TRUE, -1)
```

2021-07-22 13:45 UTC, S34NW commented on code/modules/martial_arts/krav_maga.dm
> +		if(!(QDELETED(I) || (ABSTRACT & I.flags)))
```suggestion
		if(!(QDELETED(I) || (I.flags & ABSTRACT)))
```

2021-07-22 13:46 UTC, S34NW commented on code/modules/martial_arts/cqc.dm
>  			playsound(get_turf(D), 'sound/weapons/cqchit1.ogg', 50, 1, -1)
```suggestion
			playsound(get_turf(D), 'sound/weapons/cqchit1.ogg', 50, TRUE, -1)
```

2021-07-22 13:59 UTC, dearmochi approved these changes

2021-07-29 11:57 UTC, variableundefined approved these changes

2021-07-29 11:57 UTC, merged