Bridge front firelock tweak
ParadiseSS13/Paradise pull request #15734
Opened 2021-03-19 15:03 UTC by Cocacolagua

## What Does This PR Do
Moves the firelocks in front of the bridge a tiny bit to make it symmetrical.

## Why It's Good For The Game
Once you see it, you can never unsee it.

## Images of changes
Before
![9YKjlKieBG](https://user-images.githubusercontent.com/48032385/111800632-eacc2f80-88aa-11eb-8515-55484c56dcf3.png)

After
![6JQGUnFC0K](https://user-images.githubusercontent.com/48032385/111800638-ec95f300-88aa-11eb-829e-a231ddf704a7.png)

## Changelog
:cl:
tweak: The firelocks in front of the bridge are now symmetrical between eachother.
/:cl:

2021-03-19 15:04 UTC, Qwertytoforty commented
Thank you. This has bothered me for ages.

2021-03-19 16:09 UTC, SabreML commented
It's probably important to note that this puts the firelocks into the 'Central Primary Hallway North' area, so they'll get triggered by the north fire alarm rather than the north east one.

*(This one)*
![NSS Cyberiad 2021-03-19 155150](https://user-images.githubusercontent.com/57483089/111808025-8077b700-88cb-11eb-8442-cbb812b70ec5.png)

*(Rather than this one)*
![NSS Cyberiad 2021-03-19 160412](https://user-images.githubusercontent.com/57483089/111809871-5921e980-88cd-11eb-9aee-3b6bd5afb737.png)

2021-03-30 18:27 UTC, Kyep approved these changes

2021-07-15 11:43 UTC, dearmochi approved these changes

2021-07-16 23:05 UTC, S34NW requested changes
please test this before committing, but this tag could be removed.

2021-07-16 23:05 UTC, S34NW commented on _maps/map_files/cyberiad/cyberiad.dmm
> +	tag = ""
```suggestion
```

2021-07-16 23:05 UTC, S34NW commented on _maps/map_files/cyberiad/cyberiad.dmm
> +	icon_state = "4-8";
```suggestion
	icon_state = "4-8"
```

2021-07-17 08:50 UTC, S34NW approved these changes

2021-07-20 14:21 UTC, AffectedArc07 approved these changes

2021-07-20 14:21 UTC, merged