Night Vision HUDs resprite
ParadiseSS13/Paradise pull request #15755
Opened 2021-03-26 21:27 UTC by E-MonaRhg

## What Does This PR Do

Ports Night Vision HUD sprites from /tg/.
Also adds an animation to the normal Night Vision for drask and vox sprites because they didn't have any before.

## Why It's Good For The Game

Night Vision HUDs were not really all that distinctive before, with this PR they will be.

## Images of changes

NV HUD obj sprites before:
![image](https://user-images.githubusercontent.com/71735193/112693752-703e7980-8e81-11eb-8295-597faebf37ae.png)
NV HUD obj sprites after:
![image](https://user-images.githubusercontent.com/71735193/112693790-7fbdc280-8e81-11eb-937a-f2164380e014.png)

On mob sprites, human and drask:
![HumanAndDrask](https://user-images.githubusercontent.com/71735193/112693823-906e3880-8e81-11eb-89e6-259417598f00.PNG)
On mob sprites, grey and vox:
![GreyAndVox](https://user-images.githubusercontent.com/71735193/112693835-98c67380-8e81-11eb-9482-ecb1b0b80efd.PNG)

## Changelog
:cl:
imageadd: Resprited Night Vision HUDs.
imagedel: Added animations to normal Night Vision for vox and drask sprites.
/:cl:

2021-03-26 22:07 UTC, Carthusia commented
I like, always saw it as weird that the combination of a set of NVG and a hud only covered one eye, as if it was reversed.

Its not NVG combined with a hud, its a hud combined with an NVG

2021-03-27 03:20 UTC, Wojz commented
This looks WAY cooler than the glowy vomit rectangle over one eye. I like it.

2021-03-30 18:35 UTC, Kyep approved these changes

2021-03-31 18:43 UTC, AffectedArc07 approved these changes

2021-03-31 18:44 UTC, AffectedArc07 requested changes
![image](https://user-images.githubusercontent.com/25063394/113194833-748bdd80-9259-11eb-9a90-dff526c51d1b.png)
Wrong button, you added a rogue pixel by accident

`glasses.dmi`

2021-04-02 12:09 UTC, AffectedArc07 approved these changes

2021-04-02 12:09 UTC, merged