Mobs can climb(and buckle) into seats while laying on the ground
ParadiseSS13/Paradise pull request #15782
Opened 2021-03-31 19:25 UTC by Sirryan2002

adds all the neccesary code to allow crew members to climb onto seats even if they're incapacitated.

## What Does This PR Do
Crew members who are laying on the floor are now able to climb into any seat that they are under or directly next to. Given that they are not stunned and have at least one hand. They can accomplish this by dragging their sprite onto the seat.

When they attempt to do this, one of three things happen:
- After a delay, they move onto the chair and buckle themselves to it: "
- They fail minorly and their mob still moves to the chair, but they are still on the ground
- They fail majorly and their mob still moves to the chair, they smack their head on the chair, take 15 brute damage to the head,
take 50 stamina damage, take 15 brain damage, and they are knocked out for 2-3 seconds.

If someone has **two hands**, they have a 75% chance of succeeding, a 20% chance of minorly failing, and a 5% chance of majorly failing. It will take them two full seconds in order to complete this action.

if someone has **one hand**, they have 25% chance of succeeding, a 55% chance of minorly failing, and a 20% chance of majorly failing. It will take them five full seconds in order to complete this action.

Messages sent:
"You pull yourself onto the chair" Attempting
"You fail to climb onto the chair. Come on you got this!" Minor Fail
"SHIT! Your hand slips and you slam your forehead into the chair!" Major Fail
"You pull yourself onto the chair" Success

This has been tested multiple times and it works with all chairs. Simple mobs aren't affected.

## Why It's Good For The Game
People who do not have legs(or cannot stand up for whatever reason) and are not stunned should still be able to climb into chairs/wheelchairs. Currently, If you unclip someone who has no legs from a wheelchair/seat they are left completely helpless. This feature would allow those people to have a chance to get back up and in cases where they are injured/in danger access their items (emergency injector, internals, etc). 

This feature, however, does not give a free pass/buff to players who intentionally start off their round as paraplegics. It takes time to climb back into a chair and there's a chance that you can fail or even injure yourself in the process. It makes wheelchairs have a lot more utility while also providing some form of risk.

## Changelog
:cl:
add: Mobs can now climb into chairs if they're incapacitated(but not stunned)
/:cl:

2021-03-31 21:34 UTC, S34NW commented
is your PR description accurate?

`Messages sent:
"You pull yourself onto the chair" Attempting`

2021-03-31 22:37 UTC, Sirryan2002 commented
> is your PR description accurate?
> 
> `Messages sent: "You pull yourself onto the chair" Attempting`

fixed

2021-04-05 15:32 UTC, Dumbdumn5 approved these changes
Though we don't have full blown crawling yet, I like this as a bit of a flavor change. Especially if it works for rolling beds and shit like the paramed carts. 👍

2021-04-12 09:51 UTC, S34NW requested changes
Grammar tweaks, everything else is fine grammar wise.

2021-04-12 09:51 UTC, S34NW commented on code/game/objects/buckling.dm
> +		"<span class='warning'>You fail to climb onto [src]. Come on you got this!</span>",\
```suggestion
		"<span class='warning'>You fail to climb onto [src]. Come on, you've got this!</span>",\
```

2021-04-12 09:51 UTC, S34NW commented on code/game/objects/buckling.dm
> +	M.visible_message("<span class='warning'>[M]'s hand slips and they slam their forhead on [src]!</span>",\
```suggestion
	M.visible_message("<span class='warning'>[M]'s hand slips and they slam their forehead on [src]!</span>",\
```

2021-04-12 09:51 UTC, S34NW commented on code/game/objects/buckling.dm
> +	M.visible_message("<span class='warning'>[M] looks like theyre attempting to pull [M.p_them()]self up onto [src].</span>",\
```suggestion
	M.visible_message("<span class='warning'>[M] looks like they're attempting to pull [M.p_them()]self up onto [src].</span>",\
```

2021-04-14 21:08 UTC, MRgaty commented
the chances of failing are pretty high and the punishment for it is way over the top IMO.

2021-04-15 09:28 UTC, dearmochi requested changes

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +/atom/movable/proc/user_buckle_minorfail(mob/living/M, mob/user)
I can't say I'm a fan of having two separate procs for a minor and major fail. Perhaps you could mimic the severity system EMPs and explosions have, using numbers?

```dm
/atom/movable/proc/user_buckle_fail(mob/living/M, mob/user, severity)
	switch(severity)
		if(1)
			// Minor fail
		if(2)
			// Major fail
		if(3)
			// target.dust()
```

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	playsound(src.loc, 'sound/items/trayhit1.ogg', 50, 0) //bonk
```suggestion
	playsound(src, 'sound/items/trayhit1.ogg', 50, FALSE) //bonk
```

In any case, `playsound` plays on the turf of whatever is passed.

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	M.visible_message("<span class='warning'>[M]'s hand slips and they slam their forehead on [src]!</span>",\
```suggestion
	M.visible_message("<span class='warning'>[M]'s hand slips and [M.p_they()] slam [M.p_their()] forehead on [src]!</span>",\
```

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	M.StopResting()
Curious, why stop resting to immediately rest after? For the animation?

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	M.visible_message("<span class='warning'>[M] looks like they're attempting to pull [M.p_them()]self up onto [src].</span>",\
```suggestion
	M.visible_message("<span class='warning'>[M] looks like [M.p_they()] [M.p_are()] attempting to pull [M.p_them()]self up onto [src].</span>",\
```

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +			return FALSE
Duplicate code!

I would define some variables beforehand, corresponding to the duration and fail chances depending on the user's presence of hands.

```dm
var/buckle_time = 2 SECONDS
var/minor_fail_chance = 5
var/major_fail_chance = 25
if(!user.has_both_hands())
	buckle_time = 5 SECONDS
	minor_fail_chance = 20
	major_fail_chance = 75

if(do_after(user, buckle_time, target = src, use_default_checks = FALSE))
	// ETC...
```

Also, the above numbers should be made into defines at the top of the file, as they are magic numbers.

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	if (M.get_num_legs()) //people shouldn't go back to resting after unbuckling
```suggestion
	if(M.get_num_legs()) //people shouldn't go back to resting after unbuckling
```

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +		"<span class='notice'>You pull yourself onto the [src].</span>",\
```suggestion
	M.visible_message("<span class='notice'>[M] pulls [M.p_them()]self up onto [src].</span>",\
		"<span class='notice'>You pull yourself onto [src].</span>",\
```

2021-04-15 09:28 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	else if (user.incapacitated())
```suggestion
	if((user.incapacitated() && !user.IsStunned()) && (user.has_right_hand() || user.has_left_hand()) && M == user)
		if(!user_buckle_incapacitated(M, user, TRUE))
			return FALSE
	else if(user.incapacitated())
```

2021-04-18 21:22 UTC, Sirryan2002 commented
Alright I've condensed the fails into one proc, moved some magic numbers into #define's and just cleaned up a lot of stuff.

2021-04-21 09:08 UTC, dearmochi reviewed
A few stylistic nits, mostly about spacing but the code looks fine otherwise

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +		if (1)
```suggestion
		if(1)
```

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +		if (2)
```suggestion
		if(2)
```

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +#define ONE_HAND_MULTIPLIER 3
```suggestion
#define ONE_HAND_MULTIPLIER 3

```

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +		if (buckle_chance <= MAJOR_FAIL_CHANCE)
```suggestion
		if(buckle_chance <= MAJOR_FAIL_CHANCE)
```

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +		if (buckle_chance <= MINOR_FAIL_CHANCE)
```suggestion
		if(buckle_chance <= MINOR_FAIL_CHANCE)
```

2021-04-21 09:08 UTC, dearmochi commented on code/game/objects/buckling.dm
> +	if(do_after(user, INCAPACITATED_BUCKLE_TIME * time_multiplier, target = src, use_default_checks=FALSE)) //Two hands
```suggestion
	if(do_after(user, INCAPACITATED_BUCKLE_TIME * time_multiplier, target = src, use_default_checks = FALSE)) //Two hands
```

2021-04-22 13:12 UTC, dearmochi approved these changes

2021-04-24 01:17 UTC, Sirryan2002 commented
> the chances of failing are pretty high and the punishment for it is way over the top IMO.

Sorry I haven't gotten to this, the only time where there's going to be a serious chance of failing is when you have one hand and no legs, otherwise you either have a very low chance of failing or you can just stand up. If my math is right, there's still only a 50% chance that after 4 attempts with the worst conditions you will majorly fail once. The punishment is some light head trauma and a 5-10 second stun. For someone who would otherwise be completely incapacitated without the climbing feature I believe this is a healthy tradeoff. If you really think this is over the top, please drop some values you think would be better.

2021-05-15 15:03 UTC, Fox-McCloud commented
This methodology is kinda messy, to be blunt. 

To be perfectly honest, I think I'd rather this be emergently fixed by the upcoming combat rework (which will add crawling and alter buckling, to a degree)---I'd rather not complicate a system that's likely to be ripped out soon, anyway.

2021-07-09 14:45 UTC, Sirryan2002 commented
One maintainet objection, as much as I like this feature it would probably be more beneficial for the server if I waited for foxes PR

2021-07-09 14:45 UTC, closed without merging