Deploys the nuke by default
ParadiseSS13/Paradise pull request #15793
Opened 2021-04-01 09:19 UTC by warior4356

Real PR, not April fools.

## What Does This PR Do
This PR makes three changes:
1. The crew's nuke and the nuclear operative's nuke starts deployed and anchored to the floor.
2. Changes the nuke so it can be anchored and unanchored with only the disk, the code is no longer required.
3. Adds a new, admin-only nuke type that is undeployed like the old nuke to be spawned for death squads, SSTs, ERTs, etc.

## Why It's Good For The Game
First and foremost, the nuke being stolen is fun for no one but the person who stole it. Regardless if it is a terror spider stealing the crew's nuke or someone taking the syndicate's off their ship by breaking through the engines, all the nuke being stolen does is delay the round and possibly deny an earned win.

The second change is so the crew can move their nuke if needed, but they need to take the disk to the vault first, which involves the captain, or at least the disk in the round further.

The third change is to make sure admin's don't have to mess with var editing if they are making a new nuke for an event or response team of some sort, in case, for example, a blob has eaten the nuke and they want to have an ERT deliver a nuke.

## Images of changes
![image](https://user-images.githubusercontent.com/6993506/113271678-a15ae780-928f-11eb-8563-126993c2e863.png)
![image](https://user-images.githubusercontent.com/6993506/113271694-a4ee6e80-928f-11eb-841c-e0d1e05ed944.png)

## Changelog
:cl:
tweak: All normal nukes start deployed by default
tweak: Nukes can be unanchored with the disk only, without the code
add: Added a new, admin only nuke that is undeployed
/:cl:

2021-04-02 07:40 UTC, ppi13 commented
Primary issue is is welder, crowbar, welder, wrench, crowbar, so the only one this would stop is blob and terrors from messing with the nuke.

While I do agree the nuke being stolen is somewhat of an issue, it is an imperfect solution as the bolts can be removed in a very short time, and while it does slow down stealing the nuke, it only takes 30 seconds to unbolt it. There is really no issues with this, and honestly not all that bad of an idea, but it is still an imperfect solution.

Short term this will work really well, as most people don't really know you can cut the bolts with tools, and terrors hiding the nuke is probably the biggest issue that will be fixed, so I can get behind that.

2021-04-02 08:18 UTC, DogsParadise commented
As I have just resprited the nuke, just out of curiosity.

Have you changed the states, because now there will be a constant animation played.
When the nuke gets bolted, it starts like a timer animation ( it's weird ).
Just checking.

2021-04-03 08:54 UTC, warior4356 commented
> As I have just resprited the nuke, just out of curiosity.
> 
> Have you changed the states, because now there will be a constant animation played.
> When the nuke gets bolted, it starts like a timer animation ( it's weird ).
> Just checking.

It becomes anchored true and extended true

2021-04-03 14:24 UTC, dearmochi requested changes

2021-04-03 14:24 UTC, dearmochi commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +	anchored = TRUE
```suggestion
	anchored = TRUE
	var/extended = TRUE
```

Inherited variables typically go first

2021-04-03 14:29 UTC, DogsParadise commented
> > As I have just resprited the nuke, just out of curiosity.
> > Have you changed the states, because now there will be a constant animation played.
> > When the nuke gets bolted, it starts like a timer animation ( it's weird ).
> > Just checking.
> 
> It becomes anchored true and extended true

But.. does this mean there is a constant animation playing.
I personally think it does, which would be weird?

2021-04-06 00:18 UTC, Kyep approved these changes

2021-04-06 12:59 UTC, AffectedArc07 approved these changes

2021-04-06 12:59 UTC, merged