Make the heat resistance trait fully fireproof
ParadiseSS13/Paradise pull request #15815
Opened 2021-04-02 18:13 UTC by datlo

## What Does This PR Do

Change the heat resistance trait to grant full fireproofing to whoever has it, by making the user immune to temperature raising from fire. This bug was caused by a missing check in /mob/living/carbon/human/proc/get_thermal_protection(), while this check is present in /mob/living/carbon/human/proc/get_heat_protection(temperature).

This affects the heat resistance mutation and skeletons. Skeletons used to be fireproof before the mutation into traits refactor, this was changed without documenting.

## Why It's Good For The Game

From the way it's used in the codebase, it seems that this mutation/trait is meant to make you completely fireproof. 

The opposite mutation make you completely cold proof (including from space, having the coldproof mutation make you entirely spaceproof), the gateway says it's supposed to make you 'fireproof', and it's a pretty useless trait/power to have if it doesnt do the one job it's supposed to do effectively.

## Images of changes

![image](https://user-images.githubusercontent.com/22121511/113442027-9323dd00-93ef-11eb-93a9-fd19f083c824.png)

## Changelog
:cl:
tweak: Heat resistance mutation now makes you completely fireproof.
tweak: Liches are once again completely fireproof.
/:cl:

2021-04-03 15:28 UTC, dearmochi requested changes

2021-04-03 15:28 UTC, dearmochi commented on code/modules/mob/living/carbon/human/life.dm
> +
```suggestion
```

2021-04-06 00:46 UTC, SteelSlayer approved these changes

2021-05-15 14:37 UTC, Fox-McCloud commented
I recall there being a reason for this, but if I figure that out, we can address that later--for now, this makes sense.

2021-05-15 14:37 UTC, merged