Adds more brain damage quotes
ParadiseSS13/Paradise pull request #15839
Opened 2021-04-05 20:44 UTC by hal9000PR

## What Does This PR Do
adds more quotes for when you are brain damaged

## Why It's Good For The Game
More variety, some funny memes for stupid brain hurt people to say. Currently the list isn't reaching its full potential 

## Changelog
:cl:
add: added more brain damage quotes
/:cl:

2021-04-05 20:52 UTC, S34NW reviewed
mostly fine, atrocious spelling and grammar but that _is_ the point... So I'll let it pass.

2021-04-05 20:52 UTC, S34NW commented on code/modules/mob/living/carbon/human/life.dm
> +							   "WHERE RECHAN BATONG?",
```suggestion
							   "WHERE I CHARGE BATONG?",
```

![image](https://user-images.githubusercontent.com/12197162/113625472-e2b91180-9658-11eb-94fb-eabca5194e8a.png)
just so the reference is more closely followed

2021-04-05 20:52 UTC, S34NW commented on code/modules/mob/living/carbon/human/life.dm
> +							   "HELP I'M MANTIS!!",
```suggestion
							   "HELP MANTIS!!",
```
I'm seems a bit nonsensical

2021-04-05 20:53 UTC, hal9000PR commented on code/modules/mob/living/carbon/human/life.dm
> +							   "HELP I'M MANTIS!!",
counter point
![image](https://user-images.githubusercontent.com/69320440/113625885-64a93a80-9659-11eb-96d7-f056bec9da30.png)

2021-04-05 21:02 UTC, Cocacolagua commented on code/modules/mob/living/carbon/human/life.dm
> +							   "HELP I'M MANTIS!!",
:trollface:

2021-04-05 21:04 UTC, S34NW commented on code/modules/mob/living/carbon/human/life.dm
> +							   "HELP I'M MANTIS!!",
![image](https://user-images.githubusercontent.com/12197162/113627079-e0f04d80-965a-11eb-9b98-9023c6609d9c.png)

2021-04-05 21:04 UTC, S34NW commented on code/modules/mob/living/carbon/human/life.dm
> +							   "HELP I'M MANTIS!!",
counterpoint accepted

2021-04-05 21:08 UTC, AffectedArc07 requested changes

2021-04-05 21:08 UTC, AffectedArc07 commented on code/modules/mob/living/carbon/human/life.dm
> +							   "qM blew my points on [pick("cOMbat Shtogun","inSuLated gloves","LOTS MASSHEEN!", "peNTa Smmmmmmmm")]",
This or pod tesla. Pick one self-meme reference.

2021-04-06 14:05 UTC, TheYeetster1 commented
Help I have dain bramage.

2021-04-09 23:34 UTC, Kyep reviewed
None of these memes seem particularly funny.
Certainly not at the level the others listed.

2021-04-09 23:38 UTC, closed without merging