Fix summoning multiple guardians exploit
ParadiseSS13/Paradise pull request #15882
Opened 2021-04-13 02:34 UTC by abyll

## What Does This PR Do
Check for existing guardian again after observer is picked, in case the user had used multiple guardian summoning items at the same time.

## Why It's Good For The Game
Players aren't supposed to have more than one guardian, this fixes an exploit to get around that restriction.

## Images of changes
![image](https://user-images.githubusercontent.com/4008584/114487663-3d102000-9bcd-11eb-95b3-7c010c24b8bb.png)

## Changelog
:cl:
fix: Prevent players from summoning multiple guardians at the same time.
/:cl:

2021-04-13 06:36 UTC, farie82 requested changes

2021-04-13 06:36 UTC, farie82 commented on code/game/gamemodes/miniantags/guardian/guardian.dm
> +			return
```suggestion
			used = FALSE
			return
```

2021-04-13 19:25 UTC, farie82 approved these changes

2021-04-14 13:03 UTC, AffectedArc07 approved these changes

2021-04-14 13:03 UTC, merged