Combat mode for ERT hardsuits
ParadiseSS13/Paradise pull request #15905
Opened 2021-04-17 17:58 UTC by E-MonaRhg

_This was tedious to make._

## What Does This PR Do

Adds a mechanic that was previously only available to Syndicate hardsuits to the ERT ones. For the ones that dont know what it is, it adds an option of changing the hardsuit to EVA mode to be spaceproof but slow, or combat mode to not have any slowdown but you lose spaceproofness.
Adds a new file for combat mode hardsuit helmets and refractors the code a tiny bit.
Removes the geiger counter from ERT and Syndicate hardsuits to lessen the upper toolbar bloat.

## Why It's Good For The Game

ERTs are slow... really slow, their hardsuits have the generic slowdown, having the speed of the engineering hardsuit. That is not ideal, they have to either:
1. Carry their hardsuits in their hands to get around quickly (which looks funky)
2. Beeline to RnD/xenobio hoping that they have red potions
3. Suffer the fate of being slown and outran by everything in existance

With this PR ERT members NOT going on the now almost required journey to RnD will not cripple them that much, making them able to respond to threats faster.

## Changelog
:cl:
add: Added a combat mode to ERT hardsuits.
tweak: ERT and Syndicate hardsuits no longer have an inbuilt geiger counter.
/:cl:

2021-04-17 20:13 UTC, S34NW requested changes
So uh, a number of grammar things.
Also some missed descriptions on the gamma suits for janitor and medical ERTs.
Featuring: stinky American English "armored"

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by security members of a Nanotrasen Emergency Response Team. Has red highlights. Armoured and space ready. It is in combat mode."
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by security members of Nanotrasen Emergency Response Teams. Has red highlights. Armored and space ready. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit helmet worn by security members of a Nanotrasen Emergency Response Team. Has red highlights. Armoured and space ready. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by security members of Nanotrasen Emergency Response Teams. Has red highlights. Armored and space ready. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit worn by security members of a Nanotrasen Emergency Response Team. Has red highlights. Armoured, space ready, and fire resistant. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by security members of Nanotrasen Emergency Response Teams. Has red highlights. Armored, space ready, and fireproof. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit worn by security members of a Nanotrasen Emergency Response Team. Has red highlights. Armoured, space ready, and fire resistant. It is in combat mode
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit worn by security members of Nanotrasen Emergency Response Teams. Has red highlights. Armored, space ready, and fireproof. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit helmet worn by engineers of a Nanotrasen Emergency Response Team. Has yellow highlights. Armoured and space ready. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by engineers of Nanotrasen Emergency Response Teams. Has yellow highlights. Armored and space ready. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by engineers of a Nanotrasen Emergency Response Team. Has yellow highlights. Armoured and space ready."
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by engineers of Nanotrasen Emergency Response Teams. Has yellow highlights. Armored and space ready."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit worn by the engineers of a Nanotrasen Emergency Response Team. Has yellow highlights. Armoured, space ready, and fire resistant. It is in combat mode
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit worn by the engineers of Nanotrasen Emergency Response Teams. Has yellow highlights. Armored, space ready, and fireproof. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit worn by the engineers of a Nanotrasen Emergency Response Team. Has yellow highlights. Armoured, space ready, and fire resistant. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by the engineers of Nanotrasen Emergency Response Teams. Has yellow highlights. Armored, space ready, and fireproof. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "An advanced, light suit, fabricated from a mixture of synthetic feathers and space-resistant material. A gun holster appears to be integrated into the suit. It is in EVA mode."
```suggestion
	desc = "An advanced and light suit, fabricated from a mixture of synthetic feathers and space-resistant materials. A gun holster appears to be integrated into the suit. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	alt_desc = "An advanced, light suit, fabricated from a mixture of synthetic feathers and space-resistant material. A gun holster appears to be integrated into the suit. It is in combat mode."
```suggestion
	alt_desc = "An advanced and light suit, fabricated from a mixture of synthetic feathers and space-resistant materials. A gun holster appears to be integrated into the suit. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "An elite version of the syndicate hardsuit, with improved armour and fire shielding. It is in EVA mode."
```suggestion
	desc = "An elite version of the syndicate hardsuit, with improved armor and fireproofing. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	alt_desc = "An elite version of the syndicate hardsuit, with improved armour and fire shielding. It is in combat mode."
```suggestion
	alt_desc = "An elite version of the syndicate hardsuit, with improved armor and fireproofing. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit worn by the janitorial of a Nanotrasen Emergency Response Team. Has purple highlights. Armoured, space ready, and fire resistant. It is in combat mod
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit worn by the janitorial of a Nanotrasen Emergency Response Team. Has purple highlights. Armoured, space ready, and fire resistant. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of a Nanotrasen Emergency Response Team. Has white highlights. Armoured and space ready. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored and space ready. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of a Nanotrasen Emergency Response Team. Has white highlights. Armoured and space ready. It is in combat mode."
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored and space ready. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit worn by medical members of a Nanotrasen Emergency Response Team. Has white highlights. Armoured and space ready. It is in combat mode."
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored and space ready. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit worn by medical members of a Nanotrasen Emergency Response Team. Has white highlights. Armoured and space ready. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored and space ready. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit helmet worn by janitorial members of a Nanotrasen Emergency Response Team. Has purple highlights. Armoured and space ready. It is in EVA mode."
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored and space ready. It is in EVA mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by janitorial members of a Nanotrasen Emergency Response Team. Has purple highlights. Armoured and space ready. It is in combat mode."
```suggestion
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored and space ready. It is in combat mode."
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
>  	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored, space ready, and fireproof. It is in EVA mode."
	alt_desc = "A dual-mode advanced combat hardsuit worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored, space ready, and fireproof. It is in EVA mode."
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
>  	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of Nanotrasen Emergency Response Teams. Has whitehighlights. Armored, space ready, and fireproof. It is in EVA mode."
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by medical members of Nanotrasen Emergency Response Teams. Has white highlights. Armored, space ready, and fireproof. It is in EVA mode."
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
>  	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```suggestion
	desc = "A dual-mode advanced combat hardsuit helmet worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in EVA mode."
	alt_desc = "A dual-mode advanced combat hardsuit helmet worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in EVA mode."
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```

2021-04-17 20:13 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
>  	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```suggestion
	desc = "A dual-mode advanced combat hardsuit worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in EVA mode."
	alt_desc = "A dual-mode advanced combat hardsuit worn by janitors of Nanotrasen Emergency Response Teams. Has purple highlights. Armored, space ready, and fireproof. It is in EVA mode."
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
```

2021-04-17 22:01 UTC, S34NW approved these changes
only minor fixes left

2021-04-17 22:01 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "Peering into the eyes ofthe helmet is enough to seal damnation."
```suggestion
	desc = "Peering into the eyes of the helmet is enough to seal damnation."
```

2021-04-17 22:01 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	desc = "A dual-mode advanced combat hardsuit worn by members of Nanotrasen Emergency Response Teams. Armored, space ready, and fireproof. It is in EVA mode."
not gamma, not fireproof (the fireproof flag isn't the same as the atmos/CE hardsuit one)

2021-04-17 22:01 UTC, S34NW commented on code/modules/clothing/spacesuits/ert.dm
> +	alt_desc = "A dual-mode advanced combat hardsuit worn by members of Nanotrasen Emergency Response Teams. Armored, space ready, and fireproof. It is in combat mode."
as above

2021-04-18 22:03 UTC, Pyrodes commented
I get the removal of the geiger counter for toolbar bloat, but maybe you could keep it for the engineering ERT suits? Seems kind of useful for them.

2021-06-28 23:15 UTC, Kyep approved these changes

2021-07-27 00:08 UTC, variableundefined commented
Two maint objections over further ERT buffs. 

Closing.

2021-07-27 00:08 UTC, closed without merging