Adds Ice to Daiquiri recipe
ParadiseSS13/Paradise pull request #15910
Opened 2021-04-18 17:44 UTC by Sirryan2002

## What Does This PR Do
Adds Ice to Daiquiri recipe(which is often a real life ingredient to this drink)
Fixes #15900 

## Why It's Good For The Game
You will no longer have issues with Daiquiri randomly being made when you're trying to whip up a Mohito for your patrons.

## Changelog
:cl:
fix: Fixes Daiquiri and Mohito recipe conflict
/:cl:

2021-04-18 18:44 UTC, farie82 approved these changes

2021-04-19 10:57 UTC, AffectedArc07 requested changes

2021-04-19 10:57 UTC, AffectedArc07 commented on code/modules/reagents/chemistry/recipes/drinks.dm
> +	required_reagents = list("limejuice" = 1, "sugar" = 1, "rum" = 2, "ice"= 1)
```suggestion
	required_reagents = list("limejuice" = 1, "sugar" = 1, "rum" = 2, "ice" = 1)
```
Nitpicking

2021-04-19 11:27 UTC, AffectedArc07 approved these changes

2021-04-19 11:27 UTC, merged