Window leak fix
ParadiseSS13/Paradise pull request #15927
Opened 2021-04-21 17:16 UTC by abyll

## What Does This PR Do
-     Finishes the windows fixes started by Kiyahitayika - credit to him for doing most of the work.
-     Fixes the window atmos leak issue when you move fulltile windows
-     Fixes the problem with atmos leaking under windows when you pry up their tile - resolves #2913
-     Deletes the fulltile variable, replaces the very few instances where this was referenced with is_fulltile()
-     Makes window/full a proper subtype with overrides (except for CanAtmosPass(), my arch nemesis)
-     Tidies up the Clockwork window types

## Why It's Good For The Game
Atmos blows, this makes it blow less.

## Changelog
:cl:
fix: Atmos permeability is now updated at screwdriver anchoring/unanchoring step of all windows. 
fix: Turf update (E.G. removing floor tile) doesn't pull gas from adjacent tiles if the adjacent tile doesn't allow atmos through.
/:cl:

2021-04-22 19:39 UTC, dearmochi requested changes

2021-04-22 19:39 UTC, dearmochi commented on code/__DEFINES/is_helpers.dm
> +#define is_fulltile(W) (istype(W, /obj/structure/window/full))
```suggestion
#define isfulltile(W) (istype(W, /obj/structure/window/full))
```

2021-04-22 19:39 UTC, dearmochi commented on code/__HELPERS/unsorted.dm
> +		if(is_fulltile(D))
```suggestion
		if(isfulltile(D))
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
> +					if(window && is_fulltile(window))
```suggestion
					if(window && isfulltile(window))
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	if(!anchored && !is_fulltile(src))
```suggestion
	if(!anchored && !isfulltile(src))
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	if(direct && !is_fulltile(src))
```suggestion
	if(direct && !isfulltile(src))
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	..()
The proc override can just be removed as it doesn't do anything new

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +/obj/structure/window/proc/Secured()
```suggestion
/obj/structure/window/proc/secured()
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	if(is_fulltile(src))	// This won't work with an override on /window/full
```suggestion
	if(isfulltile(src))	// This won't work with an override on /window/full
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +		return !Secured()
```suggestion
		return !secured()
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +		if(!Secured())
```suggestion
		if(!secured())
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	desc = "It looks thin and flimsy. A few knocks with ... anything, really, should shatter it."
```suggestion
	desc = "It looks thin and flimsy. A few knocks with... anything, really, should shatter it."
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +/obj/structure/window/full/CanPass(atom/movable/mover, turf/target, height=0)
```suggestion
/obj/structure/window/full/CanPass(atom/movable/mover, turf/target, height = 0)
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +		crack_overlay = mutable_appearance('icons/obj/structures.dmi', "damage[ratio]", -(layer+0.1))
```suggestion
		crack_overlay = mutable_appearance('icons/obj/structures.dmi', "damage[ratio]", -(layer + 0.1))
```

2021-04-22 19:39 UTC, dearmochi commented on code/game/objects/structures/window.dm
> +	desc = "It looks thin and flimsy. A few knocks with ... anything, really, should shatter it."
```suggestion
	desc = "It looks thin and flimsy. A few knocks with... anything, really, should shatter it."
```

2021-04-22 19:39 UTC, dearmochi commented on code/modules/admin/verbs/mapping.dm
> +					if(W.dir == turn(C1.dir,180) || is_fulltile(W))
```suggestion
					if(W.dir == turn(C1.dir, 180) || isfulltile(W))
```

2021-04-22 19:39 UTC, dearmochi commented on code/modules/mob/living/living.dm
> +	if(is_fulltile(AM))
```suggestion
	if(isfulltile(AM))
```

2021-04-22 19:39 UTC, dearmochi commented on code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
> +			if(is_fulltile(W))
```suggestion
			if(isfulltile(W))
```

2021-04-25 19:25 UTC, SteelSlayer commented
Does your PR fix issue #15768?

2021-04-25 21:20 UTC, abyll commented
> 
> 
> Does your PR fix issue #15768?

It should, all variations of reinforced windows, fulltile and regular, seem to be working as intended now.

2021-08-11 20:09 UTC, variableundefined commented
Conflicted since 2 months ago. Open new PR when deconflicted.

2021-08-11 20:09 UTC, closed without merging