FIxes apiary text for queen placement.
ParadiseSS13/Paradise pull request #15954
Opened 2021-04-27 06:12 UTC by Dragonkiller93

## What Does This PR Do
Changes apiary queen placement text to read "making it her new home" since queens are female bees. Fixes #15953 

## Why It's Good For The Game
Consistency in the descriptions of actions is good to have. Kind of annoying seeing minor issues like this, might as well fix them.

## Changelog
:cl: Iwanabeu
tweak: Apiary text upon placing a queen bee now uses her instead of his, since queens are female.
/:cl:

2021-04-27 06:21 UTC, farie82 requested changes
Every atom has a `gender` variable. The default is `NEUTER`. Changing that will properly change the her/his/their thing.

2021-04-27 06:21 UTC, farie82 commented on code/modules/hydroponics/beekeeping/beebox.dm
> +			visible_message("<span class='notice'>[user] sets [qb] down inside the apiary, making it her new home.</span>")
```suggestion
			visible_message("<span class='notice'>[user] sets [qb] down inside the apiary, making it her [qb.p_their()] home.</span>")
```

2021-04-27 06:54 UTC, Dragonkiller93 commented
Why replace "new" with the verb?

2021-04-27 07:14 UTC, Dragonkiller93 commented
This github stuff has got me real confused, I think the right changes happened in the end?

2021-04-27 07:31 UTC, farie82 approved these changes
> This github stuff has got me real confused, I think the right changes happened in the end?

Looks good to me!

2021-04-29 11:45 UTC, S34NW approved these changes

2021-05-08 21:09 UTC, AffectedArc07 approved these changes

2021-05-08 21:09 UTC, merged