Removes duplicate code from handle_status_effects
ParadiseSS13/Paradise pull request #15970
Opened 2021-05-01 20:32 UTC by Dragonkiller93

## What Does This PR Do
Fixes #15916, removes duplicate code for dizziness, drowsiness, and jitteriness lowering from the handle_status_effects function. The same functionality seems to be already present in carbon/human/life/handle_chemicals_in_body.

## Why It's Good For The Game
Hopefully stops these status effects going down faster than they should.

## Changelog
:cl:Iwanabeu
fix: Drowsiness, Dizziness, Confusion, and Jitteriness time is decreased properly.
/:cl:

2021-05-01 21:10 UTC, Dragonkiller93 commented
Could someone help me with these tests? I have no idea what they mean

2021-05-01 21:26 UTC, DeveloperLoser reviewed
I may be wrong because i'm pretty new to this but it seems like you just want to delete this to fix your error.

`code/modules/mob/living/carbon/life.dm:266:warning: restingpwr: variable defined but not used`

Can't do any testing myself but definitely do some things on your local server and make sure it doesn't blow up.

2021-05-11 21:12 UTC, Dragonkiller93 commented
Okay, I followed mochi's advice and removed the code from carbon/human, I tested it on drowsiness and jitteriness and both seem to function correctly, not sure if there was a reason for the code in handle_chemicals_in_body(). If there was, this PR probably isn't needed.

2021-05-12 08:13 UTC, dearmochi requested changes

2021-05-12 08:13 UTC, dearmochi commented on code/modules/mob/living/carbon/life.dm
> +
```suggestion
```

Unneeded. It's being done right above.

2021-05-14 09:54 UTC, dearmochi approved these changes

2021-05-15 14:23 UTC, merged