Update description text of tentacle, match reality
ParadiseSS13/Paradise pull request #15975
Opened 2021-05-02 21:00 UTC by nok-ko

## What Does This PR Do
Changes the description of the changeling tentacle ability.

Old:
> [...] and Harm will stun it, and stab it if we are also holding a sharp weapon. Cannot be used while in lesser form.

New:
> [...] and Harm will drag it closer, and stab it if we are also holding a sharp weapon. Cannot be used while in lesser form.

## Why It's Good For The Game
Removes misinformation about a nonexistent stun. Misinformation? Bad.

## Changelog
:cl: Nokko
del: Removed misleading changeling tentacle description that said it could stun.
/:cl:

2021-05-02 21:15 UTC, S34NW requested changes
Good change, this text was quite old so I'm glad you are giving it some love!

Small suggestions for readability below:
Perhaps you could split each intent onto a new line to make it easier to read, and use "target" instead of "it", as you can grab both living beings or items.

2021-05-02 21:15 UTC, S34NW commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	Help will simply drag it closer, Disarm will grab whatever the creature is holding, Grab will put the victim in our hold after catching it, \
```suggestion
	Help will drag the target closer. \
	Disarm will grab whatever the target is holding. \
	Grab will put the target in our grip after we catch it. \
```

2021-05-02 21:15 UTC, S34NW commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	and Harm will drag it closer, and stab it if we are also holding a sharp weapon. Cannot be used while in lesser form."
```suggestion
	Harm will drag the target closer and stab it. \
	Cannot be used while in our lesser form."
```

2021-05-22 20:16 UTC, Kyep approved these changes

2021-05-23 08:18 UTC, AffectedArc07 requested changes
Please resolve outstanding review

2021-05-23 15:33 UTC, dearmochi approved these changes

2021-05-24 15:27 UTC, AffectedArc07 approved these changes

2021-05-24 15:27 UTC, merged