Fixes #16019
ParadiseSS13/Paradise pull request #16021
Opened 2021-05-13 18:27 UTC by ppi13

## What Does This PR Do

Fixes #16019 

## Why It's Good For The Game

No more machine gun kissing.

## Images of changes

## Changelog
:cl: ppi
fix: Fixes the ability to fire infinity kisses as fast as you can click
/:cl:

2021-05-13 18:28 UTC, hal9000PR commented
well now you cannot get rid of them without kissing

2021-05-13 18:30 UTC, Wojz commented
Now make ranged holopara do this instead of crystal spray

2021-05-13 18:40 UTC, SabreML commented on code/game/objects/items/hand_item.dm
> +	flags = DROPDEL | ABSTRACT | NODROP
I mean this *works*, but it does mean that there's no way to cancel kissing someone.
Also makes the `DROPDEL` flag a bit redundant.

2021-05-13 18:52 UTC, S34NW commented
I feel like the better way to do this is to make you unable to move abstract items between hands

2021-05-14 18:46 UTC, dearmochi commented
> 
> 
> I feel like the better way to do this is to make you unable to move abstract items between hands

Agreed. I would look at checking for the `ABSTRACT` flag when picking up items, i.e. in `/obj/item/attack_hand()`

2021-05-14 22:26 UTC, ppi13 commented
Every other abstract item already got nodrop by default, this is the oddman out, but this here change should fix it, and any switching of hands of abstract items.

2021-05-15 06:07 UTC, dearmochi requested changes

2021-05-15 06:07 UTC, dearmochi commented on code/game/objects/items/hand_item.dm
> +	return
Again, I personally think from an user perspective it makes more sense to retain the drop functionality to cancel the emote, rather than using it.

2021-05-15 06:07 UTC, dearmochi commented on code/modules/mob/inventory.dm
> +	if(!l_hand && has_left_hand() && !ABSTRACT)
Absolutely not. `ABSTRACT` is a number (64) so doing `!64` will always evaluate to false, preventing you from putting *any* item in your hand. To check if an item has a flag, you need to do `W.flags & ABSTRACT`.

Either way, I think this is the wrong proc to put the check in. Switching the hand holding an item occurs in `/obj/item/attack_hand()`, so do take a look at that.

2021-05-15 06:07 UTC, dearmochi commented on code/modules/mob/inventory.dm
> +	if(!put_in_hand_check(W) && !ABSTRACT)
Ditto

2021-05-15 14:49 UTC, Drobe50 commented
This can also be done with the slap hand on a table, does this fix that as well?

2021-05-15 15:27 UTC, ppi13 commented
slapping on a table 3 times consumes the slap 👏 
also everything should be a working now.

2021-05-15 19:24 UTC, dearmochi approved these changes

2021-06-04 09:49 UTC, AffectedArc07 approved these changes

2021-06-04 09:50 UTC, merged