Logs pacman overheating
ParadiseSS13/Paradise pull request #16043
Opened 2021-05-17 17:25 UTC by Qwertytoforty

## What Does This PR Do

Adds a log for when pacmans overheat, and who touched it last.

## Why It's Good For The Game

Explosions with no logs of what caused them is not the best.

## Changelog
:cl:
add: Adds logging to pacmans overheating.
/:cl:

2021-05-17 17:26 UTC, AffectedArc07 requested changes

2021-05-17 17:26 UTC, AffectedArc07 commented on code/modules/power/port_gen.dm
> +		message_admins("Pacman overheated at [COORD(loc)]. Last touched by: [fingerprintslast ? "[fingerprintslast]" : "*null*"].")
```suggestion
		message_admins("Pacman overheated at [ADNIN_JMP(loc)]. Last touched by: [fingerprintslast ? "[fingerprintslast]" : "*null*"].")
```

2021-05-17 17:55 UTC, SabreML commented
![image](https://user-images.githubusercontent.com/57483089/118534728-76dec400-b741-11eb-876f-8c608481bfbe.png)

2021-05-29 16:04 UTC, Kyep approved these changes

2021-05-29 20:19 UTC, AffectedArc07 approved these changes

2021-05-29 20:19 UTC, merged