Removes the early classified announcement from the blob gamemode
ParadiseSS13/Paradise pull request #16049
Opened 2021-05-18 20:20 UTC by Qwertytoforty

##This does _not_ remove the level 5 bio hazard announcement.

## What Does This PR Do

Removes the classified announcement sent before the level 5 biohazard warning on blob rounds, and the paper that goes with it.
Also removes the declared variable, which does nothing.

## Why It's Good For The Game

Roundstart blob often has it hard, but often it is spotted quite fast. When it is not spotted fast, it has a larger issue.

![image](https://user-images.githubusercontent.com/52090703/118717628-4dcb3b80-b7f4-11eb-979b-b61394629acd.png)

This message will play. Without fail, even before anyone reads the paper, some crew will scream out blob, even if they do not see the paper and what it says. or the blob. This is silly, that crew instantly presume this message is a blob announcement. 
And of course, barring meta, this announcement can come really fast on a blob round.
Thus, this PR removes this announcement.

## Changelog
:cl:
tweak: Removes the early biohazard warning on blob rounds, but not the level 5 biohazard warning.
/:cl:

2021-05-18 20:22 UTC, AffectedArc07 requested changes
![image](https://user-images.githubusercontent.com/25063394/118718487-35244b00-b81f-11eb-886a-0e62aaf5331d.png)
Remove this too while you're at it

2021-05-18 20:33 UTC, AffectedArc07 approved these changes

2021-05-18 20:37 UTC, DogsParadise commented
I was trying to counter act this problem as well, by creating a similar biohazard message with my mosquito pr

2021-05-18 21:16 UTC, S34NW reviewed
Could you also move the other `sleep` calls in this proc to `addtimer` if possible?

2021-05-18 21:16 UTC, S34NW commented on code/game/gamemodes/blob/blob.dm
>  		stage(1)
```suggestion
		addtimer(CALLBACK(src, .proc/stage, 1), (wait_time * 2))
```

2021-05-18 21:45 UTC, Qwertytoforty commented on code/game/gamemodes/blob/blob.dm
>  		stage(1)
sure

2021-05-19 07:24 UTC, S34NW commented on code/game/gamemodes/blob/blob.dm
> +	addtimer(CALLBACK(src, .proc/burst_blob, blobmind), 600)
```suggestion
	addtimer(CALLBACK(src, .proc/burst_blob, blobmind), 60 SECONDS)
```

2021-05-19 07:26 UTC, S34NW commented on code/game/gamemodes/blob/blob.dm
> +		addtimer(CALLBACK(src, .proc/stage, 2), 30000)
```suggestion
		addtimer(CALLBACK(src, .proc/stage, 2), 50 MINUTES)
```

2021-05-20 12:50 UTC, dearmochi commented on code/game/gamemodes/blob/blob.dm
> +		addtimer(CALLBACK(src, .proc/burst_blobs), (wait_time * 2))
Shouldn't it be `wait_time / 2`?

2021-05-20 13:06 UTC, Qwertytoforty commented on code/game/gamemodes/blob/blob.dm
> +		addtimer(CALLBACK(src, .proc/burst_blobs), (wait_time * 2))
It should be, yeah.

2021-05-22 20:20 UTC, Kyep approved these changes

2021-05-22 20:53 UTC, AffectedArc07 approved these changes

2021-05-22 20:54 UTC, merged