Adds hardened versions of thermal and x ray eyes and replaces old ones bought by nuke ops
ParadiseSS13/Paradise pull request #16055
Opened 2021-05-20 18:34 UTC by Samman166

## What Does This PR Do
Adds EMP proof versions of thermal and x ray eyes and adds them to the autosurgeon kit of their respective type for nukies

## Why It's Good For The Game
Since eyes if nukies spent TC on thermals or X ray it would render them vulnerable to EMPs making it so a single one can permanently and fully blind them, people caught onto this and began Ioning nukies on purpose and it has lead to many nuke op rounds being ruined for the operatives who didn't know that the eyes would make them go blind if EMPed. Before the eye change they were EMP immune and since it was not the intended goal of that change this once again allows nukies to have thermal and X-rays without it being detrimental to them, it also stops a players round from being ruined and the fight with the operatives being quick and underwhelming. This does not remove the orignal EMP vulnerable ones and the new hardened ones are not available to be printed.

## Changelog
:cl:
add: Hardened thermal eyes and Hardened X ray eyes
del: Removed regular versions from nukie uplink

/:cl:

2021-05-20 18:37 UTC, Samman166 commented
Be gentle this is my first attempt at coding in a long time and my first attempt at DM ever.

2021-05-20 19:20 UTC, S34NW approved these changes
The rest of it is good, have a look at these changes and you're sorted.

2021-05-20 19:20 UTC, S34NW commented on code/modules/surgery/organs/eyes.dm
> +	desc = "These cybernetic eyes will give you X-ray vision. Blinking is futile.This pair has been hardened for special operations personnel"
```suggestion
	desc = "These cybernetic eyes will give you X-ray vision. Blinking is futile. This pair has been hardened for special operations personnel."
```

2021-05-20 19:20 UTC, S34NW commented on code/modules/surgery/organs/eyes.dm
> +	desc = "These cybernetic eye implants will give you thermal vision. Vertical slit pupil included.This pair has been hardened for special opertaions personnel"
```suggestion
	desc = "These cybernetic eye implants will give you thermal vision. Vertical slit pupil included. This pair has been hardened for special operations personnel."
```

2021-05-21 20:49 UTC, SteelSlayer commented
Reading `del: Removed regular versions from nukie uplink` on its own doesn't give us much information on what you removed. I recommend making it more descriptive.

2021-05-22 20:15 UTC, Kyep approved these changes

2021-05-23 08:17 UTC, AffectedArc07 requested changes
Make the last entry of your CL more descriptive, then this can be merged

2021-05-26 19:15 UTC, Samman166 commented
Requested changes made, I think that is better

2021-05-28 13:44 UTC, hal9000PR commented
`del: X-ray and thermal autoimplanter kits available to nuke ops now contain hardened version of their respective eyes instead of the previous EMP vulnerable ones` should probably be `tweak: stuff.....`

2021-05-28 19:05 UTC, Samman166 commented
@AffectedArc07 @hal9000PR Changes been made hope this is more suitable

2021-06-17 09:34 UTC, AffectedArc07 requested changes

2021-06-17 09:34 UTC, AffectedArc07 commented on code/modules/surgery/organs/eyes.dm
> +	desc = "These cybernetic eye implants will give you thermal vision. Vertical slit pupil included.This pair has been hardened for special opertaions personnel"
Please fix this too

2021-06-22 20:53 UTC, Samman166 commented
@AffectedArc07 Should be good now, sorry about that

2021-06-22 22:58 UTC, S34NW approved these changes

2021-07-19 15:01 UTC, SabreML approved these changes

2021-07-25 12:38 UTC, AffectedArc07 approved these changes

2021-07-25 12:38 UTC, merged