Player terror spiders now have their own orbit category
ParadiseSS13/Paradise pull request #16052
Opened 2021-05-19 15:53 UTC by dearmochi

## What Does This PR Do

- Adds a Terror Spider antagonist category in the Orbit menu. Unlike other antagonists, this category always shows regardless of AHUD.

## Why It's Good For The Game

- Helps distinguish how many player terror spiders there are alive.

## Images of changes

![image](https://user-images.githubusercontent.com/1496804/118844069-f1871b00-b8ca-11eb-95f4-75475838ed92.png)

## Changelog
:cl:
add: Terror spider category in the orbit menu
/:cl:

2021-05-19 16:13 UTC, Wojz commented
My oh my but without ahud? Now I will be able to meta that Red Terror spider (235) is an antag!

2021-05-22 16:56 UTC, BakKeener commented
any plans on doing this with the rest of the mid round antags so that players don't need to ahud for those? _assuming they show up in the first place_

2021-05-22 20:20 UTC, Kyep approved these changes

2021-05-22 20:51 UTC, AffectedArc07 requested changes

2021-05-22 20:51 UTC, AffectedArc07 commented on code/modules/mob/dead/observer/orbit.dm
> +					var/antag_serialized = serialized.Copy()
```suggestion
					var/list/antag_serialized = serialized.Copy()
```
Very nitpick I know, but may as well

2021-05-22 22:21 UTC, AffectedArc07 approved these changes

2021-05-22 22:21 UTC, merged