Mechs no longer spit out invisible air tanks.
ParadiseSS13/Paradise pull request #16075
Opened 2021-05-24 23:02 UTC by Dragonkiller93

## What Does This PR Do
Fixes mech wreckage so it properly outputs its internal air tank, instead of an invisible one. #15999 
Also changes mechs to properly null their internal air tank instead of nulling their power cell twice.

## Why It's Good For The Game
So players don't have to deal with invisible air tanks.

## Changelog
:cl: Iwanabeu
fix: Tank obtained by crowbarring mech wreckage is now visible.
/:cl:

2021-05-25 08:23 UTC, AffectedArc07 commented on code/game/mecha/mecha_wreckage.dm
> +		S.invisibility=0
```suggestion
		S.invisibility = 0
```

2021-05-25 11:28 UTC, S34NW requested changes
I'd also tidy up line 63 on `code/game/mecha/mecha_wreckage.dm` that denotes there is nothing to crowbar out. Apart from that and the AA comment, this looks fine.
```
to_chat(user, "<span class='notice'>You don't see anything that can be cut with [I]!</span>")
```
to be
```
to_chat(user, "<span class='notice'>You don't see anything that can be pried with [I]!</span>")
```

2021-05-26 09:08 UTC, dearmochi commented
I'm curious as to why the canister's `invisibility` is being set to `100` in the first place. In fact, after testing on a local server, it seems to delete itself from the salvage after a while.

![image](https://user-images.githubusercontent.com/1496804/119634128-b3ca4b00-be12-11eb-9667-bf47809bc0bc.png)

2021-06-12 11:20 UTC, farie82 approved these changes

2021-06-12 14:55 UTC, dearmochi approved these changes

2021-07-08 21:24 UTC, AffectedArc07 approved these changes

2021-07-08 21:24 UTC, merged