Fixes broken shuttle and escape pod rotation
ParadiseSS13/Paradise pull request #16154
Opened 2021-06-11 14:39 UTC by S34NW

## What Does This PR Do
This PR fixes a bug that was introduced in #15454 that caused incorrect shuttle wall dirs when the shuttle was rotated.
I also removed the names "burst", "left", and "right" from shuttle engines, because that got confusing with rotation.

## Why It's Good For The Game
Shuttles and escape pods should never look like a garbled mess.

## Images of changes
![2021-06-11 15_30_02-Window](https://user-images.githubusercontent.com/12197162/121703666-fa829b00-caca-11eb-9404-607fe5dd9133.png)
![2021-06-11 15_32_03-Window](https://user-images.githubusercontent.com/12197162/121703673-fb1b3180-caca-11eb-8a66-791e5c000efd.png)
![2021-06-11 15_32_22-Window](https://user-images.githubusercontent.com/12197162/121703676-fb1b3180-caca-11eb-9689-cc6d242a455e.png)
![2021-06-11 15_32_29-Window](https://user-images.githubusercontent.com/12197162/121703677-fbb3c800-caca-11eb-8c8d-5c4472530197.png)

## Changelog
:cl:
fix: Fixed a bug causing shuttle rotation to be broken
/:cl:

2021-06-11 15:13 UTC, AffectedArc07 requested changes

2021-06-11 15:13 UTC, AffectedArc07 commented on code/game/shuttle_engines.dm
>  /obj/structure/shuttle/shuttleRotate(rotation)
Put a return inside this empty proc instead of just a blank override, maybe even with a comment

2021-06-11 15:13 UTC, AffectedArc07 commented on code/game/turfs/simulated/walls_mineral.dm
> +/turf/simulated/wall/mineral/shuttleRotate(rotation)
Ditto

2021-06-12 15:12 UTC, dearmochi approved these changes

2021-06-13 14:41 UTC, AffectedArc07 requested changes

2021-06-13 17:08 UTC, AffectedArc07 approved these changes

2021-06-13 17:08 UTC, merged