Makes E-Bolas as they should be. Noncyborg variants.
ParadiseSS13/Paradise pull request #16168
Opened 2021-06-12 23:04 UTC by RadiantFlash7

## What Does This PR Do

This changes the type of snare given by the security bola to just be a normal energy snare.
Currently it's set to cyborg(?) variant. For some reason. 
## Why It's Good For The Game

This makes the limited supply Security bolas actually be better then ones you can make with stuff on station. Furthermore, this issue is well over 5 years old, and was likely made in a coding error and never realized.

## Images of changes

## Changelog
:cl:
tweak: Makes Energy bolas work like they should per code.
/:cl:

2021-06-12 23:07 UTC, S34NW commented
So, I don't know HOW #5328 broke this, considering it's not showing in the diff on the PR. But it definitely first appeared in this commit on that PR... https://github.com/ParadiseSS13/Paradise/pull/5328/commits/7d7c9aa6471c528b477e8d6a52326813cb44146b

2021-06-12 23:28 UTC, S34NW requested changes
Please add 
`breakouttime = 6 SECONDS` 
On a new line under line 131, so that ebolas are the proper 6-second snare, not 30!

2021-06-12 23:34 UTC, RadiantFlash7 commented
> Please add
> `breakouttime = 6 SECONDS`
> On a new line under line 131, so that ebolas are the proper 6-second snare, not 30!

Breakout time added to 131.

2021-06-13 09:51 UTC, AffectedArc07 requested changes

2021-06-13 09:51 UTC, AffectedArc07 commented on code/game/objects/items/weapons/legcuffs.dm
> +	breakouttime = 60
```suggestion
	breakouttime = 6 SECONDS
```

2021-06-13 17:06 UTC, RadiantFlash7 commented on code/game/objects/items/weapons/legcuffs.dm
> +	breakouttime = 60
RIP deciseconds. Change Applied.

2021-06-13 19:31 UTC, S34NW approved these changes

2021-06-14 11:24 UTC, hal9000PR commented
This is a pretty hefty buff to an already powerful item. They are already more powerful than makeshift bolas in a way because they fit into pockets. Also security gets what, 20 of these? So yes they are limited supply but they arent exactly rare.

2021-06-14 22:00 UTC, RadiantFlash7 commented
> This is a pretty hefty buff to an already powerful item. They are already more powerful than makeshift bolas in a way because they fit into pockets. Also security gets what, 20 of these? So yes they are limited supply but they arent exactly rare.

There is currently a total of 14 availible for security to grab. Thats about 2 per officer for a 2 hour shift. Half of these are within the wardens storage and have to be handed out by the warden, seemingly rarely done in practice.

It would be a bit of a buff, but security lacks a way of acquiring more, and several officers already just make makeshift ones instead of energy guns to use.

2021-06-17 09:25 UTC, AffectedArc07 approved these changes

2021-06-17 09:25 UTC, merged