Add blast doors and a camera to the syndicate base test chamber
ParadiseSS13/Paradise pull request #16261
Opened 2021-06-26 16:11 UTC by theo-3

## What Does This PR Do
Adds blast doors and a camera to the syndicate base test chamber. Adds a monitor outside to watch the camera.

## Why It's Good For The Game
Blast doors block foam and smoke. The camera allows players to safely watch smoke and foam grenades.

## Images of changes
![gif](https://user-images.githubusercontent.com/85434590/123519123-0ddc5b80-d6b2-11eb-98bf-258aba88271b.gif)

## Changelog
:cl:
add: Added blast doors, a camera and a camera monitor to the syndicate research base to safely test smoke and foam grenades.
/:cl:

2021-06-26 16:17 UTC, S34NW requested changes
Love the blast doors, that needed to happen!
However, we try to avoid floating cameras wherever possible. You could make two cameras, one east one west, this way you cover the whole chamber without having floating cameras!

2021-06-26 17:31 UTC, theo-3 commented
Done, thanks for the suggestion!

2021-06-26 18:03 UTC, S34NW approved these changes
Looks good now.

2021-06-28 22:59 UTC, Kyep approved these changes

2021-06-29 10:33 UTC, AffectedArc07 approved these changes

2021-06-29 10:34 UTC, merged