Adds blueprints and air analyzer to drones
ParadiseSS13/Paradise pull request #16350
Opened 2021-07-11 22:27 UTC by warior4356

## What Does This PR Do
This PR adds an air analyzer and a copy of the station blueprints to maintenance drones.

## Why It's Good For The Game
The air analyzer is good because it lets them actually check the air levels in a room or a pipe, which is good when trying to restore hull breaches or locate a broken pipe.

Speaking of broken pipes, having the blueprints means they can find areas where wires or pipes have been broken for doing repairs. It also lets them make new rooms when improving/expanding the station.

## Changelog
:cl:
add: Added station blueprints and air analyzer to maintenance drones
/:cl:

2021-07-11 23:19 UTC, SteelSlayer commented
:-1: is due to the blueprints. Air analyzer is fine.

2021-07-12 09:27 UTC, Flotilla-zz commented
Giving drones blueprints gives implicit encouragement for them to make significant expansions to the station, which can easily fall afoul of:

>Drones may not attempt to alter the course of the round with their actions.

2021-07-12 19:16 UTC, warior4356 commented
If a head admin or maintainer decides that the ability for drones to make extensions to the station is the veto point on this PR please let me know. I will happily make a version of blueprints that can't add new areas and can only view what the station is supposed to look like for repairs.

2021-07-17 00:42 UTC, S34NW commented
> If a head admin or maintainer decides that the ability for drones to make extensions to the station is the veto point on this PR please let me know. I will happily make a version of blueprints that can't add new areas and can only view what the station is supposed to look like for repairs, as trying to figure out where the piping and wiring was is a pain and maintenance drones probably should try to put a room back the way it was, as close as possible, instead of haphazard fixes.

I am neither of these things, but I really encourage you to implement this "read only" blueprint idea. The last thing anyone wants is the extra workload of dealing with drones who think renaming all the station areas to "maints" is a fun joke.

2021-07-18 07:44 UTC, dearmochi approved these changes
Approved for code. Not a fan of the blueprints, but while you're at it I think drones could use a floor painter.

2021-07-18 12:26 UTC, LiberatedWaveMan commented
As everyone else has said by now, the blueprints are _eh_ but the air analyzer is fine. Floor painter would be good as mochi said, and perhaps plasteel for repairing reinforced walls?

2021-07-18 19:48 UTC, warior4356 commented
I personally think drones having the ability to make rooms would be a positive for the round, not a negative but I'm not in the majority. Still, I'm going to refrain from tweaking the PR unless a head or maint would like it changed.

2021-07-24 23:31 UTC, Kyep commented
Do their blueprints let them build new rooms? If so, maybe give them a type that does not allow this?
They can maintain the existing station, but cannot make entirely new areas.

2021-07-25 08:42 UTC, warior4356 commented
> Do their blueprints let them build new rooms? If so, maybe give them a type that does not allow this?
> They can maintain the existing station, but cannot make entirely new areas.

Alright, I'll up the PR like that.

2021-07-25 09:39 UTC, warior4356 commented
Alright, a read only version of the blueprints has been given to drones, and set as a new variable within blueprints/area editors in general so it can be scaled as needed for other things, to avoid this being snowflake code. I hope this mollifies people's concerns.

2021-07-28 18:14 UTC, Fox-McCloud commented
Blueprints, I'm not a fan of.

Air analyzer is fine.

2021-07-28 23:27 UTC, warior4356 commented
> Blueprints, I'm not a fan of.
> 
> Air analyzer is fine.

As above, I updated the blueprints into being read-only. They can only view what the station is supposed to look like and is unable to modify rooms or make new ones.

2021-07-30 04:46 UTC, Kyep approved these changes

2021-07-30 21:49 UTC, variableundefined requested changes
What Fox said

2021-07-31 22:02 UTC, AffectedArc07 requested changes
Im with the others. 

Remove the blueprints.

2021-07-31 22:02 UTC, AffectedArc07 commented on code/game/objects/items/blueprints.dm
> +		if(get_area_type()==AREA_SPACE && !read_only) // Never trust user input
```suggestion
		if(get_area_type() == AREA_SPACE && !read_only) // Never trust user input
```

2021-07-31 23:33 UTC, warior4356 commented
Blueprints have been removed.

2021-08-01 01:56 UTC, variableundefined approved these changes

2021-08-01 02:16 UTC, merged