Delta Disposals - Fore Section + Minor Cargo fix
ParadiseSS13/Paradise pull request #16408
Opened 2021-07-22 01:37 UTC by Vi3trice

## What Does This PR Do
This is the start of fixing up Delta's disposal network. The various sorting pipes aren't set for Paradise's current list of tagger locations (It even had a pipe for Theater, which does not exist in the list.) This also cleans up where the pipes tend to go, as they had a bad tendency of going under walls when they don't need to, or seem to be laid out with limited types of junctions in mind.

## Why It's Good For The Game

Makes things go where they should, and if something breaks, you won't have to rebuild a wall in the process (usually). Map bloat is also reduced.

## Images of changes

<img src="https://user-images.githubusercontent.com/80771500/126578857-b0176d2e-9d9b-4541-a94f-5b0bfd01dd57.png" width="65%">

<img src="https://user-images.githubusercontent.com/80771500/126578870-8af58808-1014-4b9f-b21a-85b3042028d7.png" width="65%">

## Changelog
:cl:
add: Added a locker in Cargo
del: Removed redundant or unused sorting junctions
tweak: Reworked the layout of the pipes. Moved two disposal bins around in Cargo.
/:cl:

2021-08-04 10:27 UTC, S34NW requested changes
The disposal unit in the mining dock is not connected to the pipe network.
Apart from that, this looks fine.

2021-08-04 10:28 UTC, S34NW commented on _maps/map_files/Delta/delta.dmm
> +/obj/machinery/disposal,
This would fix it

2021-08-04 18:16 UTC, S34NW approved these changes
LGTM

2021-08-05 19:41 UTC, S34NW approved these changes

2021-08-10 19:47 UTC, variableundefined approved these changes

2021-08-10 19:47 UTC, merged