Removes Cling/Vamp CQC
ParadiseSS13/Paradise pull request #16493
Opened 2021-08-06 17:38 UTC by matttheficus

## What Does This PR Do

Removes the ability to get CQC as a Changeling or Vampire.

## Why It's Good For The Game

I am a very, very, very vocal user of CQC. I thoroughly enjoy using it as a stealth weapon as an Antagonist and use it quite literally every round I roll Traitor. It is a very strong skill and can easily destroy anyone who isnt expecting it or doesnt have ranged weapons to use to defend themselves at a distance. That being said, given that CQC has been changed recently to be much like CQC though with less combat focus and more utility, it seems odd that one martial art is barred from use while the other is not.

Cling and Vamps already have a myriad of stuns, stims, and combat buffs. Giving them more insta-stuns, combat buffs, and a free kidnapping if done right seems to go against the very ideal that Carp sets as a precedent by being unusable.

The only issue that I can see is a Cling/Tot or Vamp/Tot rolling the Bond Kit and being unable to use the CQC Manual inside. My argument would be they can ALSO pull Carp from a surplus/super surplus and be just as badly out of luck. If the Bundle is the only thing that causes issues I can look into a possible workaround with that specific one.

## Changelog
:cl:
add: Added check for vampire/changeling to CQC
/:cl:

2021-08-06 17:40 UTC, S34NW commented
Considering CQC is one of the strongest stealth tools available to an antag, piling it on top of what vamps and clings already get does lead to problematic situations. I think I like this.

2021-08-06 17:41 UTC, hal9000PR requested changes
You are gonna want to make CQC refundable like other items vamps/clings cannot use.

2021-08-06 17:43 UTC, Coolrune206 commented
> You are gonna want to make CQC refundable like other items vamps/clings cannot use.

Remove it from the Bond bundle and then yes. Otherwise, order null crates from cargo > refund CQC from bond crates > badda bing badda boom free TC.

2021-08-06 17:45 UTC, matttheficus commented
> > You are gonna want to make CQC refundable like other items vamps/clings cannot use.
> 
> Remove it from the Bond bundle and then yes. Otherwise, order null crates from cargo > refund CQC from bond crates > badda bing badda boom free TC.

This is the only big glaring issue I see, though I'm unsure what would replace CQC in the Bond Kit/how to get around the Null spam for free TC.

2021-08-06 17:55 UTC, Wojz commented
Changelings + CQC = near-instant sleep tentacle
Vampire + CQC = near-instant AoE sleep

Yeah no thanks. I have been a CQC changeling before and it's absolutely insane. But the issue of the Bond kit does remain. Personally I wouldn't mind it being replaced by something else, Bond is well known for using a myriad of gadgets. A sleepy pen and maybe something like chameleon thermals wouldn't be a bad replacement.

2021-08-06 18:16 UTC, Cocacolagua commented
> > You are gonna want to make CQC refundable like other items vamps/clings cannot use.
> 
> Remove it from the Bond bundle and then yes. Otherwise, order null crates from cargo > refund CQC from bond crates > badda bing badda boom free TC.

For clarification's sake, you can already do this with the implant bundle, which has an uplink implant. This does mean that vampires/clings would get two options that give TC

2021-08-06 19:35 UTC, Coolrune206 commented
> > > You are gonna want to make CQC refundable like other items vamps/clings cannot use.
> > 
> > 
> > Remove it from the Bond bundle and then yes. Otherwise, order null crates from cargo > refund CQC from bond crates > badda bing badda boom free TC.
> 
> For clarification's sake, you can already do this with the implant bundle, which has an uplink implant. This does mean that vampires/clings would get two options that give TC

Normal tots would also be able to refund it I believe, giving everyone more refund potential.

2021-08-07 22:06 UTC, Peakwastaken commented
> > > You are gonna want to make CQC refundable like other items vamps/clings cannot use.
> > 
> > 
> > Remove it from the Bond bundle and then yes. Otherwise, order null crates from cargo > refund CQC from bond crates > badda bing badda boom free TC.
> 
> This is the only big glaring issue I see, though I'm unsure what would replace CQC in the Bond Kit/how to get around the Null spam for free TC.

Would it be possible to make it so the one that comes in nulls is non-refundable ? Otherwize, the opposite, make a check for whether it was bought through pda/surplus to be refundable ?

This is honestly the only reason I didn't try making this PR myself, fixing that connundrum is kind of out of my reach, but this change is really needed - even if it's to risk the odd-once-in-a-blue-moon vamp/cling getting cqc in their surplus and potentially ahelping for a refund prior to finding an adequate fix to it.

2021-08-10 08:16 UTC, hal9000PR commented
Imma be honest, I'm not 100% sold on this. No matter what tot vamp/traitor will always have op stuff. Instead they will just buy an ebow and emp flash. Perhaps the issue isn't the items they can get, but instead the fact that a player can roll both. When a player rolls traitor vamp/cling they either get massively overwhelmed by the 7 objectives they get or they become next to unkillable.

2021-08-12 00:14 UTC, Kyep approved these changes

2021-08-12 12:10 UTC, AffectedArc07 requested changes

2021-08-12 12:10 UTC, AffectedArc07 commented on code/modules/martial_arts/martial.dm
> +			return
```suggestion
		if(user.mind && user.mind.changeling) //Changelings
			to_chat(user, "<span class ='warning'>We try multiple times, but we simply cannot grasp the basics of CQC!</span>")
		else //Vampires
			to_chat(user, "<span class ='warning'>Your blood lust distracts you from the basics of CQC!</span>")
		return
```

2021-08-13 08:54 UTC, dearmochi requested changes
Nit

2021-08-13 08:54 UTC, dearmochi commented on code/modules/martial_arts/martial.dm
> +		return
```suggestion
	if(user.mind) //Prevents changelings and vampires from being able to learn it
		if(user.mind.changeling) //Changelings
			to_chat(user, "<span class='warning'>We try multiple times, but we simply cannot grasp the basics of CQC!</span>")
			return
		else if(user.mind.vampire) //Vampires
			to_chat(user, "<span class='warning'>Your blood lust distracts you from the basics of CQC!</span>")
			return
```

Looks cleaner IMO

2021-08-13 22:29 UTC, matttheficus commented on code/modules/martial_arts/martial.dm
> +		return
agreed, less painful to read

2021-08-14 06:55 UTC, dearmochi approved these changes

2021-08-14 15:03 UTC, variableundefined approved these changes

2021-08-14 15:03 UTC, merged