Make bee hitbox much smaller, except if the bee attacks someone
ParadiseSS13/Paradise pull request #16510
Opened 2021-08-10 10:23 UTC by theo-3

## What Does This PR Do
Removes opacity from bees.
If a bee attacks someone, it will be made opaque for one minute.
If a bee becomes sentient, it will permanently become opaque.
Syndicate bees are STILL opaque.
## Why It's Good For The Game
Trying to do botany with bees is very annoying because you have to constantly alt-click when bees are on trays.
Since it's much rarer for someone to want to click on a bee than to want to click on a plant tray, it's better to make the bee hitbox smaller.
Hostile bees are temporarily made opaque, and syndicate bees are always opaque, so this won't make bees harder to fight.
Sentient bees are also made opaque so they can't cause too much trouble.

## Changelog
:cl:
tweak: Bee hitbox no longer covers the entire tile by default. If that bee attacks someone, it covers the tile for one minute. Queen, syndie and sentient bees are not changed and still cover the tile.
/:cl:

2021-08-10 11:14 UTC, dearmochi commented
Suggestion: rather than creating a timer, perhaps you could check in the bee's `Life` if its last attack is recent enough. This way you avoid the churn of constantly creating and overriding timers and its associated memory cost.

2021-08-10 16:32 UTC, theo-3 commented
Wouldn't doing this in Life cause way more checks?

2021-08-10 16:33 UTC, theo-3 commented
Right now it's one check per attack, Life would do it like 20 times per second, wouldn't it?

2021-08-10 16:56 UTC, theo-3 commented
Hold on, memory cost, not CPU cost? Do overridden timers remain in memory and take up space?

2021-08-10 17:07 UTC, dearmochi commented
Not really, but under the hood creating a timer is rather complex (see `SStimer`) and is way more than just "one check" -- with the `Life` method, all you'd be doing periodically is compare two numbers, which is pretty inexpensive compared to the various checks and calls associated with creating a timer.

2021-08-10 17:12 UTC, theo-3 commented
Alright, is it good like this?

2021-08-10 17:36 UTC, dearmochi requested changes

2021-08-10 17:36 UTC, dearmochi commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +	make_opaque()
This will be undone when enough time has passed, you'd need another variable or something for this case

2021-08-10 17:36 UTC, dearmochi commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +	if(diff >= opacity_time)
This will constantly set the mouse opacity back, better if it was set only once

2021-08-10 17:41 UTC, theo-3 commented
Whoops. Did that fix it? Sorry

2021-08-10 17:43 UTC, dearmochi approved these changes

2021-08-10 22:19 UTC, S34NW commented
🐝

2021-08-11 15:16 UTC, hal9000PR commented
> 🐝

oh god

2021-08-25 00:35 UTC, Kyep approved these changes

2021-09-07 00:12 UTC, variableundefined approved these changes

2021-09-07 00:12 UTC, merged