Remaps Kerberos Departures Security
ParadiseSS13/Paradise pull request #16546
Opened 2021-08-14 19:22 UTC by LightFire53

## What Does This PR Do

Moves the security holding are of departures of the NSS Kerberos to line up with the escape shuttle instead of being on the opposite end. This came at the cost of removing customs from departures to make a hallway/public area for people to get into departures still, as well as the removal of the security checkpoint way down at the bottom. ~~Because people are going to complain about the loss of security gear to steal due to that, there is a security locker in the security holding area.~~ As a result, I was able to add some additional seating where the previous security section had been. 

I also added a dedication plaque for extra seasoning.

## Why It's Good For The Game

Map parity, but also imagine being the security officers that have to move all the prisoners to the opposite end of the shuttle through the horde of greytide.

## Images of changes

**Old departures**
![Old Departures](https://user-images.githubusercontent.com/16112919/129457892-353d2a82-718f-4bf6-9ab1-716dd15d428c.png)

**New departures**
![New Departures](https://user-images.githubusercontent.com/16112919/129457903-db20dd09-1c15-489f-8298-7e8c56baf284.png)

## Changelog
:cl:LightFire53
del: Removes NSS Kerberos's customs from departures
tweak: Re-maps NSS Kerberos's departures to line security up with the shuttle.

/:cl:

2021-08-14 19:25 UTC, AffectedArc07 commented
For sake of clarity in future PRs, **please** use technical names (Box, Meta, Delta) in PR titles to save headaches.

2021-08-14 20:22 UTC, variableundefined approved these changes

2021-08-14 20:22 UTC, SteelSlayer commented
There's only one thing I don't like right now, and that's the 1 tile wide room to hold the air canister for the escape airlock. I would suggest something more like this:

![image](https://user-images.githubusercontent.com/42044220/129459094-6dc43c91-446c-4a70-88ce-a94af7713510.png)

2021-08-14 20:25 UTC, LightFire53 commented
> There's only one thing I don't like right now, and that's the 1 tile wide room to hold the air canister for the escape airlock. I would suggest something more like this:
> 
> ![image](https://user-images.githubusercontent.com/42044220/129459094-6dc43c91-446c-4a70-88ce-a94af7713510.png)

I wasn't sure if that I put it like that, it wouldn't suck the cannister around. Although, a glass pane would fix that as well.

2021-08-14 20:31 UTC, SteelSlayer commented
> I wasn't sure if that I put it like that, it wouldn't suck the cannister around. Although, a glass pane would fix that as well.

It *shouldn't* blow around because wrenching those onto connectors anchors them. Though it you do decide to add glass, a windoor would be nice so people can still access it if they need to.

2021-08-14 23:28 UTC, LightFire53 commented
Ignore green floor tile in the middle, that was just me executing poor screenshotting etiquette

2021-08-15 12:59 UTC, S34NW requested changes
This has some good bits and bad bits.

The good:
A nice little chill area north of departures, sec getting more seats for crims awaiting transfer. Sec actually having access to the right shuttle door.

The bad:
Weird airlock configuration in the bottom right, the loss of a recharger and sec records console from the checkpoint, checkpoint moved to a more prominent and visible position.

I think of the "bad" issues i listed, we really do need to add back the recharger. Everything else I can live with, but this would be a stealth nerf to antags on delta.

Also, please add a disposals somewhere near the south of departures if you can.

2021-08-15 17:47 UTC, LightFire53 commented
Escape flowers now look like this:
![image](https://user-images.githubusercontent.com/16112919/129487553-b4fda962-49b6-4361-b701-89675cd1cbc3.png)

I also relabeled 2 security cameras in the departures hallway (one was brig equipment storage, the other mining external access) while I was adding a camera to the departure lounge area.
I have also added a wall recharger, however since it's only a holding area and not a full on checkpoint, adding a security records console feels out of place.

2021-08-16 01:40 UTC, merged