Adds 3 new names when a hardhat is put on a corgi
ParadiseSS13/Paradise pull request #16553
Opened 2021-08-16 07:02 UTC by TheYeetster1

## What Does This PR Do
adds "Engineering corgi/Ian", "Chief engineer corgi/Ian" and "Fire chief corgi/Ian"

When you add any hardhat subtype(except white or red) to a corgi it changes their name to the above mentioned names and adds the following descriptions:
"Trust him, he's an engineer.", "Hasn't delamed the engine once." and "Some days you're the dog, some days you're the hydrant."
## Why It's Good For The Game

More corgi/Ian fun.
## Images of changes

## Changelog
:cl: The Yeetster add: Added 3 new hat descriptions to corgi's when they wear hardhats, firefighter helmets, and white hard hats.
/:cl:

2021-08-16 07:16 UTC, TheYeetster1 commented
also taking feedback for the descriptions

2021-08-16 07:18 UTC, farie82 requested changes
There are also some more hardhat subtypes. Such as `/obj/item/clothing/head/hardhat/atmos` that will now become a regular engineer hardhat variant. Not much of an issue but something to keep in mind.
`/obj/item/clothing/head/hardhat/reindeer` might be an issue though.

EDIT:
Also ensure your CL is properly spaced.
:cl: NAMES OF CONTRIBUTORS (optional, your github name will be used if left out)
add: some stuff
add: Some more stuff
/:cl:

2021-08-16 07:18 UTC, farie82 commented on code/datums/dog_fashion.dm
> +datum/dog_fashion/head/hardhat
```suggestion
/datum/dog_fashion/head/hardhat
```
Need to put a `/` in front of it so it is not relative

2021-08-16 07:18 UTC, farie82 commented on code/datums/dog_fashion.dm
> +	desc = "Hasn't delamed the engine once."
Not sure this is correct grammar @S34NW probably has a good alternative ;)

2021-08-16 14:22 UTC, warriorstar-orion commented
I am contractually obligated to approve of this PR.

2021-08-16 14:42 UTC, Spacemanspark commented
I approve

2021-08-16 16:21 UTC, TheYeetster1 commented
> There are also some more hardhat subtypes. Such as `/obj/item/clothing/head/hardhat/atmos` that will now become a regular engineer hardhat variant. Not much of an issue but something to keep in mind.
> `/obj/item/clothing/head/hardhat/reindeer` might be an issue though.

Atmos hardhat, and pumkinhardhat are set to `dog_fashion = null`
Reindeer antlers have their own dog fashion description

> EDIT:
> Also ensure your CL is properly spaced.
> 🆑 NAMES OF CONTRIBUTORS (optional, your github name will be used if left out)
> add: some stuff
> add: Some more stuff
> /🆑

Fixed I think?

2021-08-16 17:05 UTC, farie82 commented
> > There are also some more hardhat subtypes. Such as `/obj/item/clothing/head/hardhat/atmos` that will now become a regular engineer hardhat variant. Not much of an issue but something to keep in mind.
> > `/obj/item/clothing/head/hardhat/reindeer` might be an issue though.
> 
> Atmos hardhat, and pumkinhardhat are set to `dog_fashion = null`
> Reindeer antlers have their own dog fashion description

Ah indeed they are. I overlooked those. Just the orange and dbblue hardhat now functions the same as the yellow one. Which is fine.

> > Also ensure your CL is properly spaced.
> > 🆑 NAMES OF CONTRIBUTORS (optional, your github name will be used if left out)
> > add: some stuff
> > add: Some more stuff
> > /🆑
> 
> Fixed I think?

Yep looks good to me

2021-08-18 07:52 UTC, TheYeetster1 commented
> Ah indeed they are. I overlooked those. Just the orange and dbblue hardhat now functions the same as the yellow one. Which is fine.

Intended :P
I'm not entirely sure how you get those hardhats other than through loadout, but it seemed logical to allow them as well.

2021-08-24 23:31 UTC, SabreML approved these changes

2021-08-25 00:36 UTC, Kyep approved these changes

2021-08-25 14:57 UTC, AffectedArc07 approved these changes

2021-08-25 14:57 UTC, merged