Deletes attack_log_old and all related vars/procs
ParadiseSS13/Paradise pull request #16576
Opened 2021-08-20 16:21 UTC by farie82

## What Does This PR Do
Deletes the old attack log code which got replaced by the new system from #13115.

## Why It's Good For The Game
It seems no admins use it anymore, nor should they. Removing the code for this makes attack logging a bit more logical (no dupe log calls which looked weird) and will free up some memory per mob.

## Changelog
:cl:
del: Removes the old attack log code
/:cl:

2021-08-20 16:22 UTC, farie82 commented on code/modules/mob/mob_defines.dm
> -	var/last_log = 0
Was only used by the old attack logs weirdly enough

2021-08-20 16:35 UTC, AffectedArc07 requested changes
Dropped a ping for this in adminchat and 3 people instantly responded saying they use this. 

We're not deleting it.

2021-08-20 16:36 UTC, Spacemanspark commented
>It seems no admins use it anymore, nor should they.

I use this. It's actually faster than opening up the log panel in game and having to add a bunch of filters--especially while we have upwards of 150+ players at peak hours.
Please do not delete it.

2021-08-20 16:37 UTC, AffectedArc07 commented
Also as a general rule of thumb, don't go deleting admin features when you aren't aware of what we do or don't even use.

2021-08-20 16:38 UTC, Qwertytoforty commented
To be fair on henk, I was not aware anyone used this still

2021-08-20 17:41 UTC, farie82 commented
> Also as a general rule of thumb, don't go deleting admin features when you aren't aware of what we do or don't even use.

I did ask a few admins and never heard any other admin using it thus far. A ping seemed a bit overkill knowing this all.

2021-08-20 17:44 UTC, farie82 commented
> I use this. It's actually faster than opening up the log panel in game and having to add a bunch of filters--especially while we have upwards of 150+ players at peak hours.
> Please do not delete it. As well, if you haven't adminned like many of us, please don't try and say what we should and shouldn't do.

How exactly do you use this? Do you use the proc? Do you use the VV panel? If it is the proc, I can change it to load up the viewer with just the selected mob and the attack logs or another set of settings.

Having two logging systems in place doing the same thing is a bit stupid, so I'd rather get rid of the old one and improve the new one where needed. I'm open for improvements on the logging view as I've heard no issues with it so far other than the ones you've listed

2021-08-21 10:19 UTC, MarsM0nd commented
> How exactly do you use this? Do you use the proc? Do you use the VV panel? If it is the proc, I can change it to load up the viewer with just the selected mob and the attack logs or another set of settings.
I think it's using VV, especially while being a ghost, ctrl+shift+click opens it up, and can be quickly checked with ctrl+f, rather than opening up a persons player panel with ctrl+click, clicking the logs option in that window, and then removing the chat stuff before hitting search in another new window. VV also only takes up a part of your screen, while the log viewer does take most of it, so it's a bit harder to multi-task (watching chat/the person that's getting checked) with the log viewer in use.
Can't say for certain if it'll cover all usages, but a quick to open slim log viewer could be useful. Give one for chat, one for attacks, to cover the VV attack_log and say_log uses, and it only contains what happened. No link to anything, just the log lines who they attacked and who attacked them.

2021-08-21 12:42 UTC, farie82 commented
> I think it's using VV, especially while being a ghost, ctrl+shift+click opens it up, and can be quickly checked with ctrl+f, rather than opening up a persons player panel with ctrl+click, clicking the logs option in that window, and then removing the chat stuff before hitting search in another new window. VV also only takes up a part of your screen, while the log viewer does take most of it, so it's a bit harder to multi-task (watching chat/the person that's getting checked) with the log viewer in use.
> Can't say for certain if it'll cover all usages, but a quick to open slim log viewer could be useful. Give one for chat, one for attacks, to cover the VV attack_log and say_log uses, and it only contains what happened. No link to anything, just the log lines who they attacked and who attacked them.

Thanks for the response. The use cases given do make sense indeed. I'll think about ways of making the new way work better in these cases. For now, I'll close the PR and make a new one when I finalised those cases.

2021-08-21 12:42 UTC, closed without merging