All_In_One Grinder
ParadiseSS13/Paradise pull request #16673
Opened 2021-09-10 14:49 UTC by botka4aet

## What Does This PR Do
- Now can grind rods
- Don't use all grinding stack items. EX: you place 50 stack plasma. Grind only 5 of them for 100 Plasma dust
*changed code from //Sheets and rods(!)

## Why It's Good For The Game
- Grinder machine works as it shoud be

## Changelog
:cl:
fix: All-In-One Grinder can grind rods
fix: All-In-One Grinder don't use all stack items
/:cl:

2021-09-10 15:33 UTC, FlattestGuitar commented
If you're changing the indentation of a whole file you should put it in a separate commit. This is needlessly hard to review.

2021-09-10 22:40 UTC, variableundefined commented
A more informative PR title would be appreciated

2021-09-11 00:00 UTC, S34NW requested changes
This isn't really on you because of how the surrounding file is a big mess of spacing, but we generally don't include spaces after `if` and `for` checks. Best to tidy up the ones you touch here.

2021-09-11 00:04 UTC, Aurorablade commented
S34NW got that at least but the indenetation thing is fine after i weNT THROUGH it and everything it looks okay but does bare someone testing it just to make sure all wheels running at proper amount of squeakyness.

2021-09-18 02:48 UTC, variableundefined requested changes
Awesome PR, the grinder has always been very unintuitive and wasteful. This will improve QOL for chemistry tonnes. 

This is good to go once you fix up the styling issues. If you are on Discord, ping me within the weekend.

2021-09-18 02:48 UTC, variableundefined commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		while(O.amount) //Work untill hold something
Change the comment to "Grind until there's no more reagents"

2021-09-18 02:50 UTC, variableundefined commented
I'll take the liberty to change the changelog and PR title a bit if that is fine with you @botka4aet

2021-09-23 08:14 UTC, botka4aet commented
> I'll take the liberty to change the changelog and PR title a bit if that is fine with you @botka4aet

Sure. All for comfy game

2021-09-23 15:24 UTC, botka4aet commented
Syntax fix and move remove_object to cicle end

2021-09-23 23:58 UTC, variableundefined approved these changes

2021-09-23 23:58 UTC, merged