uplink update
ParadiseSS13/Paradise pull request #16778
Opened 2021-09-23 06:34 UTC by HMBGERDO

## What Does This PR Do
This PR is separating traitor and nuclear and sst uplinks from others. Now you can get nuclear uplink with nuclear items without gamemode. This doesnt change default uplinks with default gamemodes, you will not get nuclear items as traitor or something else. PR allows admins(if they want) for example to spawn nuclear squad with uplinks after two hours of boring traitor round.
You still need to set uplink uses(TC) after spawn by changing Uses value in Hidden uplink using VV

## Why It's Good For The Game
This PR doesnt change default game, but adds an opportunity to get any uplink shop in any gamemode

## Changelog
:cl:
tweak: uplink names now match their store
/:cl:

2021-09-23 14:26 UTC, Fox-McCloud commented
This is a step backwards. Basing it around a defined path, which will fail to compile if you typo, is far superior to having strings.

2021-09-23 14:26 UTC, Fox-McCloud requested changes
Strings are gross, at the very least use defines.

2021-11-10 17:46 UTC, hal9000PR commented
it also looks like the branch was deleted

2021-11-11 01:28 UTC, closed without merging

2021-11-11 02:00 UTC, HMBGERDO commented
sadly i cant have both forks from this rep and from russian rep(fork of this rep), they are unite, so my own fork of this repo was deleted including this branch. Im sorry.