Makes uncuttable chainlink fences deconstructable
ParadiseSS13/Paradise pull request #16790
Opened 2021-09-24 10:11 UTC by S34NW

## What Does This PR Do
This PR makes chainlink fences that don't support hole cutting (posts, ends, doors, corners) dismantleable.
This process takes the same time as cutting three holes in a regular fence, just in one step that deletes the fence.

## Why It's Good For The Game
Currently, if you place a chainlink fence post, end, door, or corner you are screwed and have to bash it with an object until it breaks.
This is not ideal, as it makes fences stronger than walls in some ways.

With this change, even though you can't cut holes in them, you can spend the extra time to take them apart, as opposed to breaking it with a toolbox or whatever you have on hand.

## Changelog
:cl:
tweak: Non-cuttable chainlink fences can now be taken apart with wire cutters after a delay.
/:cl:

2021-09-24 10:20 UTC, farie82 requested changes

2021-09-24 10:20 UTC, farie82 commented on code/game/objects/structures/fence.dm
>  	if(!cuttable)
I'd move this check below the `invulnerable` check. Else you can remove the corners of an `invulnerable` fence

2021-09-24 10:20 UTC, farie82 commented on code/game/objects/structures/fence.dm
> +			visible_message("<span class='notice'>\The [user] completely dismantles \the [src].</span>")
```suggestion
			visible_message("<span class='notice'>[user] completely dismantles \the [src].</span>")
```

2021-09-24 10:20 UTC, farie82 commented on code/game/objects/structures/fence.dm
> +		if(W.use_tool(src, user, FULL_CUT_TIME * W.toolspeed, volume = W.tool_volume))
Might want to give feedback when starting in the form of text. Probably a `visible_message` for others as well

2021-09-24 10:45 UTC, farie82 commented on code/game/objects/structures/fence.dm
> +		to_chat(user, "<span class='danger'>You start dismantling [src] with [W].</span>")
Could combine this into one `visible_message` send from the user with a self message.
I feel like `danger` is a bit overkill for what you're doing. `warning` is more suited I'd say.
I personally see `danger` as something that might or has hurt somebody other than the user directly. `warning` is something that might potentially be bad but also has a chance to be okay and just needs a bit more attention.

2021-09-24 10:45 UTC, farie82 commented on code/game/objects/structures/fence.dm
> +			to_chat(user, "<span class='info'>You completely dismantle [src].</span>")
Same here with combining them into one message

2021-09-24 11:11 UTC, hal9000PR commented
Does it drop materials now when you dismantle them?

2021-09-24 12:16 UTC, farie82 commented on code/game/objects/structures/fence.dm
> +		if(W.use_tool(src, user, FULL_CUT_TIME * W.toolspeed, volume = W.tool_volume))
```suggestion
		if(W.use_tool(src, user, FULL_CUT_TIME, volume = W.tool_volume))
```
The toolspeed is already processed in the proc itself

2021-09-24 17:55 UTC, farie82 approved these changes

2021-09-25 01:07 UTC, variableundefined approved these changes

2021-09-25 01:08 UTC, merged