Cyberiad standardisation and fixes
ParadiseSS13/Paradise pull request #17058
Opened 2021-11-07 20:32 UTC by S34NW

## What Does This PR Do
This PR standardizes box to the current standard, by replacing some shutters with electrochromic windows in the following locations:

- RD's office
- CMO's office
- CE's office (previously had no shutters)
- HoS' office
- NTR's office
- BS' office
- IAA office
- Magistrate's office
- OR1 and OR2
- Interrogation
- Processing
- Detective's office
- Head of Staff meeting room
- Execution

Fixes:

- Invisible crates in old vault
- Invisible locker in EVA maint

Adds:

- Security newscasters to Warden and HoS office (allowing wanted poster creation)

## Why It's Good For The Game
Map standardisation calls for these things to be relatively similar across all maps, Delta and Meta have electrochromic windows in more locations than before, including head offices. This makes the changes to box to bring it in line with the other maps.
Also fixes some minor issues with crates.

## Changelog
:cl:
tweak: Changed many boxstation shutters for electrochromic windows
fix: Fixed invisible crates and lockers on boxstation
/:cl:

2021-11-07 20:42 UTC, S34NW commented
I was not sure where standardisation compliance falls within the feature freeze scheme, so if this PR is unacceptable feel free to close it, no hard feelings.

2021-11-07 21:38 UTC, S34NW commented
Todo: psych office

2021-11-07 22:19 UTC, LightFire53 requested changes
- RD office has a glass airlock door still
- RD office and CMO office have their tags in capitals (`RD` and `CMO`), but your other locations aren't capitalized at all (`bs` and `hos` for instance)
- The window from the Detective's office towards processing facing security isn't a polarized window, not sure if that's intentional or not
- The airlock beside said window is glass
- HoS space facing window's aren't polarized either, again not sure if intentional or not

2021-11-07 22:27 UTC, S34NW commented
> 
> 
>     * RD office has a glass airlock door still
> 
>     * RD office and CMO office have their tags in capitals (`RD` and `CMO`), but your other locations aren't capitalized at all (`bs` and `hos` for instance)
> 
>     * The window from the Detective's office towards processing facing security isn't a polarized window, not sure if that's intentional or not
> 
>     * The airlock beside said window is glass
> 
>     * HoS space facing window's aren't polarized either, again not sure if intentional or not


Top two issues are unintentional, thanks for pointing them out.

Bottom three are intentional and unchanged from current map.

2021-11-07 23:34 UTC, Fox-McCloud commented
It should go without saying that during a freeze, you shouldn't be packaging tweaks with fixes.

2021-11-08 00:07 UTC, S34NW commented
> 
> 
> It should go without saying that during a freeze, you shouldn't be packaging tweaks with fixes.

I mean, I was not sure if map standardization was a fix or not. Since it's bringing outdated maps up to date.

2021-11-08 00:11 UTC, S34NW commented
This can come back later

2021-11-08 00:11 UTC, closed without merging