Remove commie vending machines
ParadiseSS13/Paradise pull request #17092
Opened 2021-11-13 13:26 UTC by datlo

## What Does This PR Do

Fixes https://github.com/ParadiseSS13/Paradise/issues/17089

Some vending machines on box and a single one on delta were set to the /free subtype. This PR replaces them by the regular credit required type. 

## Why It's Good For The Game

This subtype is AFAIK meant to be used for vendors in places that dont use the credit system like the syndicate researchers or for the permabrig, not for station machines.

## Changelog
:cl:
fix: Some vending machines on boxstation and delstation that were set to be free now cost credits to use.
/:cl:

2021-11-13 13:29 UTC, datlo commented
This PR is a super simple fix and it's mapping stuff so I understand if I dont get GBP for this one, it just bugged me when I was testing other stuff

2021-11-13 13:57 UTC, S34NW requested changes
The IAA hot drinks ones are traditionally free IIRC

2021-11-13 14:05 UTC, AffectedArc07 commented
> The IAA hot drinks ones are traditionally free IIRC

If I have to pay for my coffee, so do they

2021-11-13 14:42 UTC, UltraNumeron commented
detective ciggies are a necesarry bussiness expense shouldnt have to be paid for.

2021-11-13 14:57 UTC, datlo commented
Detectives can get free ciggies from their actual det vendor for free still

2021-11-14 21:33 UTC, variableundefined approved these changes

2021-11-14 21:33 UTC, merged