Creates a "Off" Preset for Air Alarms
ParadiseSS13/Paradise pull request #17248
Opened 2021-12-18 01:47 UTC by Kepplerx

## What Does This PR Do
This PR adds a System Preset for Air alarms, with all thresholds set to off. When this Preset is set, it does not affect vents or scrubbers connected to the air alarm, nor the System modes for those. If changed from "Disabled" the air alarm will cycle the air, as it would if you changed between Vox or Human.

## Why It's Good For The Game
Changing a air alarms thresholds to off, to not get constant alerts or firelocks is a pain, as there are a lot of them. This will make it easier to disable alarms, which will also make it easier for antagonists to utilise the air alarm settings, so the AI will not immidietly discover someone made a breach somewhere. Alternatively the AI could plasmaflood, with air alarms not triggering fire alerts, thereby not hindering the gas spreading. In essence this is a small quality of life change, which makes air alarms easier to use for antags mostly, but also for special engineering projects.

## Images of changes
![image](https://user-images.githubusercontent.com/65926304/146624955-69b6d363-72f6-40ce-8141-421309fb80a5.png)
The difference between setting all of these manually to -1

![image](https://user-images.githubusercontent.com/65926304/146624968-e1151e52-d11d-4e16-9117-c337918d5caf.png)
To clicking one button

## Changelog
:cl:
add: Added Disabled Air Alarm setting
/:cl:

2021-12-18 18:42 UTC, AffectedArc07 requested changes

2021-12-18 18:42 UTC, AffectedArc07 commented on code/modules/atmospherics/machinery/airalarm.dm
> +			TLV = list(
```suggestion
		if(AALARM_PRESET_DISABLED)
			no_cycle_after = TRUE
			TLV = list(
```

2021-12-18 18:42 UTC, AffectedArc07 commented on code/modules/atmospherics/machinery/airalarm.dm
> +	if(!no_cycle_after && preset != AALARM_PRESET_DISABLED)
```suggestion
	if(!no_cycle_after)
```

2021-12-19 22:33 UTC, Carthusia commented
Oh thank god, i kept having the alarms going off in my vox boxes because i couldnt get it to stop freaking out when i tried to change the alarm settings

2021-12-20 11:53 UTC, Kepplerx commented
Tested with the new small changes, still works as intended, now just waiting for approval.

2021-12-24 19:42 UTC, dearmochi approved these changes

2021-12-24 19:43 UTC, merged