Hyperion, a building event map
ParadiseSS13/Paradise pull request #17287
Opened 2021-12-31 02:26 UTC by png103

## What Does This PR Do

I've been working on for a week at this point, many thanks to Syrrian for giving feedback throught and S34N for doing the piping/wiring

After nanotrasen's engineering team failed to meet time frames on the construction of their next station, Instead of canceling the shift and giving everyone the day off they chose to disguise the unfinished station as a "fun" company event where they'd just let whoever the hell wanted to finish the construction for them, isn't unpaid labor sweet?

The map only contains the bare minimum for everything to not spiral instantly into complete anarchy,

- A kitchen, so not starve to death
- Botany (or Hydroponics if you prefer so)
- Janitor's closet to clean up the inevitable messes
- Cargo to order the usual silly things
- Engineering supply closet to generate power
- Brig to give security something to do
- RnD to make electronics
- A table and two chairs for bridge hobos

There's a list of things that the crew is assigned to build, included in a note that an admin would spawn in bridge at round start

`[center][logo][/center]Dear capt.,<br>We regret to inform you that our team of skilled engineers failed to meet our time frames to complete the station's construction in time, And as a result, you may have noticed that it is somewhat... incomplete.<br>So. after a few days of deliberation and planning, we are delighted to announce that Hyperion station has been cancelled, and on it's place, we present: project Build Your Own Nanotrasen Depot (B.Y.O.N.D.), Your goal is to encourage the crew to assist in the expansion and construction of the station; we have provided you with the necessary materials and tools and higger ups  will be sent later to review your progress and give the final score. If you require anything specific, please contact central command, but keep in mind that we will only accept requests once.<br>The station necessitates the following:<p>-Rooms with proper wiring/lighting/air flow</p><p>-A place for dining/drinking (preferably with actual food and drinks)</p><p>-A medical center</p><p>-A waste disposal system</p><p>-A conference room<br> <br><br>Extra points.<p>The features listed bellow are optional, however they will help improve your rating.</p><p>-A theatre or stage</p><p>-Dormitories</p><p>-A locker room</p><p>-A chapel or church</p><p>-A library</p><p>-A recreational room<br>So, without further ado, we wish you all the best of luck.<p><i>-Do not let us down!, Glory to Nanotrasen Inc!</i></p>`

I've ran the map several times, from what i've seen everything works as intended, but if any changes are needed i'll (try to) comply
## Why It's Good For The Game

Encouraging players to build stuff is fun
## Images of changes

Arrival shuttle (mining shuttle docking on the left and mini medbay on the right)
![image](https://user-images.githubusercontent.com/68801329/147798873-9bc42dae-b0ac-4b90-9600-a63329335b0d.png)
Station
![image](https://user-images.githubusercontent.com/68801329/147798863-462ad60c-b688-4d66-ac95-2d777be53af6.png)
Close ups
![image](https://user-images.githubusercontent.com/68801329/147798946-4d655d03-d063-4fee-8a00-240a82a5329d.png)
![image](https://user-images.githubusercontent.com/68801329/147798961-77c3d804-7dd4-44e0-9ce8-e7637e105a22.png)
![image](https://user-images.githubusercontent.com/68801329/147798969-21cbf8e5-6dc5-498a-822f-1fd908e14947.png)
![image](https://user-images.githubusercontent.com/68801329/147798975-6e6e7bbf-6183-463e-8679-5755560e14a8.png)
![image](https://user-images.githubusercontent.com/68801329/147799130-cd7978c7-e76b-41f4-8275-f1923f590bbb.png)

## Changelog
:cl:
add: Added Hyperion, an event map (many thanks to Syrrian and S34N)
/:cl:

2021-12-31 02:38 UTC, Sirryan2002 commented
Just to be clear to those unaware, if given the go ahead by maints/host, this will be TM'd once and then closed afterwards. This is not going to be a permanent feature addition.

2021-12-31 03:47 UTC, Denthamos commented
I like the idea, though considering how high traffic the arrivals shuttle will be already due to it being a spawn in location and the only functional on site medical area at the start, if the mining area is in a bad spot.  Having where miners will be constantly going back and forth through, where the station personnel will constantly be going to in order to get metal and glass, and such will make that area a bit too congested for such uses.  

At the same time however not sure where else would be a good spot for it to dock at.

2021-12-31 04:12 UTC, png103 commented
> I like the idea, though considering how high traffic the arrivals shuttle will be already due to it being a spawn in location and the only functional on site medical area at the start, if the mining area is in a bad spot. Having where miners will be constantly going back and forth through, where the station personnel will constantly be going to in order to get metal and glass, and such will make that area a bit too congested for such uses.
> 
> At the same time however not sure where else would be a good spot for it to dock at.

i've placed down plenty of metal in the station, you can see it in the tables on the first close up, so the orm would probably only be used for emergencies when they are REALLY out, or just for plasma and all that so i bet it wouldn't be that crowded

2021-12-31 06:36 UTC, png103 commented
if a host/maintainer is reading this, i'm still working on improving the map so the one currently on the branch is not that final but it's pretty close

2022-01-01 10:53 UTC, S34NW commented
Only minor mapping issues present, will be fine for an event shift.

2022-01-01 10:54 UTC, S34NW approved these changes

2022-01-01 10:59 UTC, hal9000PR commented
For changelogs you can put the names of all that worked on it next to the first :cl:
Eg. 
🆑 S34N, sirryan, png103
Add: new map
/ 🆑

2022-01-03 20:47 UTC, png103 commented
alright so, i fixed some mistakes with the map, added an atmos storage and made this better, also added an art vendor so crew can get crayons and all
![image](https://user-images.githubusercontent.com/68801329/147978622-0108b44d-50cd-498a-be8d-4907a5b3fed8.png)
![image](https://user-images.githubusercontent.com/68801329/147978508-676def15-597b-4c20-9def-97a1d49e13bc.png)
![image](https://user-images.githubusercontent.com/68801329/147978580-23f58628-afbd-4b36-a709-74d34b1f4231.png)

2022-01-04 23:21 UTC, Denthamos commented
It would be neat to see how this works out otherwise for a planned event.  Throwing my approval on it as long as you properly coordinate a planned event time for this to happen and arrange for it to be announced on discord for players to know when the test merge and event is happening.

2022-01-08 10:05 UTC, dearmochi requested changes
Please revert the Cyberiad changes -- the map `hyperion` datum will be used for the admin to force switch to it when it's event time.

2022-01-09 08:56 UTC, dearmochi requested changes

2022-01-09 08:56 UTC, dearmochi commented on code/modules/mapping/cyberiad.dm
> +	technical_name = "Project B.Y.O.N.D"
```suggestion
	fluff_name = "NSS Cyberiad"
	technical_name = "Cyberiad"
```

This still needs reverting.

2022-01-10 06:18 UTC, png103 commented
oops forgot about that

2022-01-15 13:25 UTC, png103 commented
borg recharging pod and like 5 rcds to avoid atleast a little bit of metal to be used up on the autolathes (also forgot to include some pictures of the cryo pods
![image](https://user-images.githubusercontent.com/68801329/149623130-394431c8-eedc-4ffa-ad56-d2da1ce86d05.png)
![image](https://user-images.githubusercontent.com/68801329/149623133-d018e0c8-31e9-4642-ba82-e9db717a1e2f.png)
![image](https://user-images.githubusercontent.com/68801329/149623203-ad667e28-754f-4b9f-ab9b-9ef3d2927830.png)

2022-01-15 14:58 UTC, AffectedArc07 commented on code/modules/mapping/hyperion.dm
> +	technical_name = "Project B.Y.O.N.D"
```suggestion
	technical_name = "hyperion"
```

2022-01-15 15:00 UTC, AffectedArc07 commented
![image](https://user-images.githubusercontent.com/25063394/149626399-6b42cce5-3f00-46f4-975d-c22a437ab475.png)

2022-01-15 17:26 UTC, png103 commented
i made some changes to fix the z/w issues and also fixed some spawn issues i'm testing it rn before i add it to the branch

2022-01-15 18:20 UTC, png103 commented
i still have a changes requested warning despite doing the requested change
![image](https://user-images.githubusercontent.com/68801329/149633239-bbc0c4f6-23fa-4152-8484-a8a617910d90.png)

2022-01-15 18:27 UTC, png103 commented
by the way this isn't coding related but i need 2/3 admins that would play as the inspectors at the end of the round
also if you're gonna be on the event dm me (Peterr#9201) so i can send you a google docs with some basic midround events and timings

2022-01-16 00:24 UTC, closed without merging

2022-01-16 00:24 UTC, png103 commented
that was really fun, i'm glad it went (mostly) well