Converts items / abilities that set alpha to zero, to use invisibility
ParadiseSS13/Paradise pull request #17280
Opened 2021-12-29 16:16 UTC by Qwertytoforty

## What Does This PR Do

Changes reactive stealth armor to use invisibility instead of alpha.

Changes abilities that after a while convert alpha to zero, to set invisibility to 90 after alpha reaches zero.

## Why It's Good For The Game

Being able to see people with zero alpha by rightclick / screentips is bad. As such, using invisibility to prevent this is good.

## Changelog
:cl:
tweak: Reactive stealth armor, darkness based stealth, and the chameleon gene now are fully invisible when fully active.
/:cl:

2021-12-29 16:40 UTC, S34NW commented
Suggestion:
Can we set it up in a way for ghosts to see it?

Setting it to invisibility 90 means ghosts cannot see it, perhaps we can change it to 60 and then also add some alpha. So its apparent to ghosts that the object is invisible, but still invisible to normal players?

2021-12-29 16:54 UTC, Qwertytoforty commented
> Suggestion: Can we set it up in a way for ghosts to see it?
> 
> Setting it to invisibility 90 means ghosts cannot see it, perhaps we can change it to 60 and then also add some alpha. So its apparent to ghosts that the object is invisible, but still invisible to normal players?

I could, however ghosts were not able to see them before (bar right click). 
Theoretically, I could make invisibility 60 and half the alpha for some abilities once alpha hits zero, although that is a little strange. Will think on it.

2021-12-29 18:47 UTC, S34NW commented
> > Suggestion: Can we set it up in a way for ghosts to see it?
> > Setting it to invisibility 90 means ghosts cannot see it, perhaps we can change it to 60 and then also add some alpha. So its apparent to ghosts that the object is invisible, but still invisible to normal players?
> 
> I could, however ghosts were not able to see them before (bar right click). Theoretically, I could make invisibility 60 and half the alpha for some abilities once alpha hits zero, although that is a little strange. Will think on it.

Yeah, it's just something I thought up when I saw the title. No pressure either way!

2022-01-09 08:55 UTC, dearmochi requested changes
Echoing what @S34NW said, ghosts (and particularly admin ghosts) should (need to) be able to see invisible players. 

Setting their invisibility to `INVISIBILITY_OBSERVER` and halving their alpha would be a good start. Perhaps even adding an `(invisible)` suffix to the screentip, but I'm just musing at this point.

2022-01-09 19:16 UTC, Denthamos commented
Approval given after requested changes done.

2022-01-09 19:18 UTC, dearmochi requested changes

2022-01-09 19:18 UTC, dearmochi commented on code/game/dna/mutations/powers.dm
> +		M.invisibility = 60
```suggestion
		M.invisibility = INVISIBILITY_OBSERVER
```

2022-01-09 19:18 UTC, dearmochi commented on code/game/dna/mutations/powers.dm
> +		M.invisibility = 60
```suggestion
		M.invisibility = INVISIBILITY_OBSERVER
```

2022-01-09 19:18 UTC, dearmochi commented on code/modules/clothing/suits/armor.dm
> +		owner.invisibility = 60
```suggestion
		owner.invisibility = INVISIBILITY_OBSERVER
```

2022-01-09 19:18 UTC, dearmochi commented on code/game/dna/mutations/powers.dm
> +		if(M.invisibility != 60)
```suggestion
		if(M.invisibility != INVISIBILITY_OBSERVER)
```

2022-01-09 19:18 UTC, dearmochi commented on code/game/dna/mutations/powers.dm
> +		if(M.invisibility != 60)
```suggestion
		if(M.invisibility != INVISIBILITY_OBSERVER)
```

2022-01-09 19:30 UTC, dearmochi approved these changes

2022-01-09 19:30 UTC, merged