Borg locker verb fix.
ParadiseSS13/Paradise pull request #17408
Opened 2022-02-15 21:14 UTC by Dragonkiller93

## What Does This PR Do
Borgs can now use the locker/crate verbs via right click or object menu, to toggle and open lockers/crate, since they already can by clicking the locker. Fixes #17371.

## Why It's Good For The Game
The ability is already there, but now players can use the verb if they want to, or right click.

## Changelog
:cl:
tweak: Borgs can use locker/crate verbs to open or lock.
/:cl:

2022-02-15 21:21 UTC, hal9000PR commented on code/game/objects/structures/crates_lockers/crates.dm
> +			src.togglelock(usr)
implied src. you don't need it  
```suggestion
			togglelock(usr)
```

2022-02-17 08:23 UTC, dearmochi requested changes

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/closets.dm
> +		return
```suggestion
```

You can get rid of this and add the check in the above `if` block. `add_fingerprint` is needed for hidden fingerprints for admins.

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
> +		return
```suggestion
```

Ditto

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +		playsound(loc, 'sound/items/poster_ripped.ogg', 75, 1)
```suggestion
		playsound(loc, 'sound/items/poster_ripped.ogg', 75, TRUE)
```

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +		return
```suggestion
```

Ditto

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +		playsound(loc, 'sound/items/poster_ripped.ogg', 75, 1)
```suggestion
		playsound(loc, 'sound/items/poster_ripped.ogg', 75, TRUE)
```

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +		broken = 1
```suggestion
		locked = FALSE
		broken = TRUE
```

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +			locked = 1
```suggestion
			locked = TRUE
```

2022-02-17 08:23 UTC, dearmochi commented on code/game/objects/structures/crates_lockers/crates.dm
> +			locked = 0
```suggestion
			locked = FALSE
```

2022-03-05 00:34 UTC, AffectedArc07 submitted a review, later dismissed
Please see to the requested changes within 7 days

2022-03-07 02:41 UTC, Dragonkiller93 commented
All fixed, sorry for the delay.

2022-03-08 11:23 UTC, AffectedArc07 reviewed
Merge-block removed.

Awaiting @dearmochi approval

2022-03-09 13:13 UTC, merged