Players can no longer exploit Meteorshot to throw anything that's not a turf
ParadiseSS13/Paradise pull request #17465
Opened 2022-03-06 00:09 UTC by Sirryan2002

## What Does This PR Do
Adds an additional anchored check to meteorshot to prevent anything thats not anchored from being thrown around.

## Why It's Good For The Game
Players should not have the ability to throw airlocks, shieldwalls, or any other seemingly immovable object off their hinges/anchors. Not to mention this will likely causes serious issues when knocking pacmans, APCs, or even cryodorm equipment off their anchorpoints. Also has serious balance implications because all a nukie needs to get passed a reinforced vault door, shieldwall, or window is a meteorshot or two

## Changelog
:cl:
fix: fixes an exploit with meteorshot
/:cl:

2022-03-06 00:13 UTC, AffectedArc07 commented on code/modules/projectiles/projectile/bullets.dm
> +			M.throw_at(throw_target, 3, 2)
@Fox-McCloud 
Im recalling a past incident where someone tried this and it had a bunch of adverse effects and we had to revert it.

I could be wrong though.

2022-03-06 00:20 UTC, Sirryan2002 commented
going to look into possibly using move_resist instead of this

2022-03-06 00:36 UTC, Sirryan2002 commented on code/modules/projectiles/projectile/bullets.dm
> +			M.throw_at(throw_target, 3, 2)
alright, I've changed it over to move_resist since using anchored actively takes away from the intentions of meteorshot rather than just fixing the exploitive stuff

2022-03-06 11:33 UTC, AffectedArc07 requested changes

2022-03-06 11:33 UTC, AffectedArc07 commented on code/modules/projectiles/projectile/bullets.dm
> +		if(!M.move_resist != INFINITY)
```suggestion
		if(!M.move_resist < INFINITY)
```

2022-03-08 11:39 UTC, AffectedArc07 approved these changes
What could go wrong

2022-03-08 11:39 UTC, merged