BRPED provides user feedback for range exchanges instead of admin logs
ParadiseSS13/Paradise pull request #17527
Opened 2022-03-26 20:28 UTC by Sirryan2002

## What Does This PR Do
BRPED now provides an error message to the player and makes a angry buzz noise when an out-of-range exchange is attempted.

## Why It's Good For The Game
I'd hardly consider this stuff to be an exploit, more so an unforeseen/unintended feature. Encouraging admins to note for this and labelling this as an "[EXPLOIT]" in admin logs doesn't take into account that no announcement have ever been made about abusing this feature by headmins and there is no in-game user feedback to indicate that this isn't allowed. It also gives off the vibe that this action was done with malice which is generally not the case.

This PR will inform players that their action was unsuccessful and reduce the amount of logs admins get for things we will likely never note players for.

## Changelog
:cl:
tweak: BRPED now provides user feedback and no longer admin logs for out-of-range exchange attempts.
/:cl:

2022-03-26 20:48 UTC, AffectedArc07 requested changes

2022-03-26 20:48 UTC, AffectedArc07 commented on code/game/objects/items/weapons/stock_parts.dm
> -			message_admins("\[EXPLOIT] [key_name_admin(user)] attempted to upgrade machinery with a BRPED via a camera console. (Attempted range exploit)")
This message was put in so we could note down the people previously using this exploit.

I would rather you fix the range thing to add +2 to it to handle people who move quickly as opposed to removing the exploit log.

2022-03-26 21:18 UTC, Sirryan2002 commented on code/game/objects/items/weapons/stock_parts.dm
> -			message_admins("\[EXPLOIT] [key_name_admin(user)] attempted to upgrade machinery with a BRPED via a camera console. (Attempted range exploit)")
requested changes implemented

2022-03-27 01:30 UTC, SteelSlayer commented on code/game/objects/items/weapons/stock_parts.dm
> +			to_chat(user, "ERROR: [M] is out of [src]'s range!")
Just one thing:
```suggestion
			to_chat(user, "<span class='notice'>ERROR: [M] is out of [src]'s range!</span>")
```

2022-03-27 01:41 UTC, Sirryan2002 commented on code/game/objects/items/weapons/stock_parts.dm
> +			to_chat(user, "ERROR: [M] is out of [src]'s range!")
oop yeah, I totally forgot to add that

2022-03-27 01:46 UTC, SteelSlayer approved these changes

2022-03-27 10:26 UTC, AffectedArc07 approved these changes

2022-03-27 10:27 UTC, merged