Removes "Bracket Pair Colorizer 2" from recommended VSCode extensions
ParadiseSS13/Paradise pull request #17631
Opened 2022-04-18 16:14 UTC by S34NW

## What Does This PR Do
This PR removes "Bracket Pair Colorizer 2" from the recommended extensions for VSCode.

## Why It's Good For The Game
This extension is now natively supported by VSCode.
See: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization

2022-04-18 16:26 UTC, lewcc commented
Could you modify `.vscode/settings.json` to enable the feature for the repo by default? Should be able to add

```json
{
    "editor.bracketPairColorization.enabled": true,
    "editor.guides.bracketPairs":"active"
}
```

2022-04-19 16:39 UTC, AffectedArc07 requested changes

2022-04-19 16:39 UTC, AffectedArc07 commented on .vscode/extensions.json
> -		"coenraads.bracket-pair-colorizer-2",
If you're modifying extensions please also add `usernamehw.errorlens` 

![image](https://user-images.githubusercontent.com/25063394/164053270-53549520-2ab3-492c-a6b1-68c047ac44d8.png)

It is amazing

2022-04-20 20:58 UTC, AffectedArc07 approved these changes

2022-04-20 20:58 UTC, merged