Shepard Station - MK I
ParadiseSS13/Paradise pull request #17710
Opened 2022-04-30 23:52 UTC by kugamo

This PR was OK'd by @dearmochi 

## What Does This PR Do

Adds the NSS Shepard as a playable station to the game. 

## Why It's Good For The Game

Another map in rotation adds dynamism to the game, a fresh experience. 
This is a completely newly designed map, and would be unique to Paradise. 
It is notably a few thousand more atmos turfs than the cyberiad, but also roomier.. arguably better for our high pop.

It was designed around giving each department its own space, offering some independence. But they are still well connected to the rest of the station through the main halls and a multitude of maintenance tunnels.
Four tile wide hallways form the main method of getting around in a large circuit that runs through each department in a big U.
I originally intended the departments to be separated by retractable space bridges, but I decided getting the map in a playable state first the better course of action.

There was alot of design decisions made throughout the course of the station's development, hopefully done in an appreciative sense to how our current staff wishes the game to be played. But I am my own person and I cannot help but have my own vision for the game that I used in the design of the station. Forgive me that. :0) Feedback is welcome, and I am happy to explain myself if and where needed.

## Images of changes

*Full Size Map* (forgive the jpg, 10mb limit)
![2022 04 30-17 42 30](https://user-images.githubusercontent.com/16618648/166126117-bafc83a1-cdb5-4e36-91ad-b9193aa3a0ea.jpg)

*comparison to the cyberiad*
![Shepard_Cyberiad_compared](https://user-images.githubusercontent.com/16618648/166126190-a3ab9fef-344a-4dd8-96ee-e00087a0cbb9.png)

## Changelog
:cl:
add: Added a new map: NSS Shepard.
imageadd: Added some additional variant sprites for floor tiles. 
/:cl:

2022-04-30 23:59 UTC, Mitchs98 commented
This map looks absolutely amazing overall. The only two things I don't like is the brig is quite less secure than Delta or Cyberiad with the multiple doors that can be hacked into from arrivals and maints, and the maint door leading into the ORs in medbay. But otherwise, it's really quite good and a marked improvement above Metastation, of course, likely it's not meant to beat a replacement for meta but it will serve as a good map alongside the rest.

2022-05-01 00:07 UTC, moxian commented on code/modules/mapping/shepardstation.dm
> +/datum/map/delta
```suggestion
/datum/map/shepard
```

2022-05-01 00:19 UTC, PopeDaveThe3th commented
Forgive me for my lack of mapping knowledge, but the entire AI sat looks like it's made of grille blocks. Am I missing something?

2022-05-01 01:26 UTC, atteria commented
Shame there isn't a Stanislaw Lem name for this map.

Finally, a map that isn't basically Boxstation hallways at its core.
I really like the green space, space vistas, and hall hierarchy. All the unique little bits I really want to get familiar with on a couple extended rounds.

2022-05-01 01:32 UTC, moxian commented
Some initial feedback. 

Medbay:
- somehow medbay gets depowered not 10 minutes after roundstart. I'm not sure why or if maybe that's a fluke.
- Southern chemical fridge being nearly inaccessible to chemists
- both chemists being visible from medbay proper is super great (for non-antag, at least)
- western chemist window (with the table) has a wall on the same tile
- in general a bit too many table-double-windoor setups. I'm not sure i like them.
- medbay lacks a guaranteed screwdriver. 
- ORs might be a bit too open/visible for antaggery. But maybe privacy shutters are good enough?.. Unsure.
- Big fan of chest drawers in surgery next to body scanner
- The small room with three beds south of paramedic feels.. weird, and very cramped. But i don't know how to fix it.
- To the west of Cryotubes there's a table with MedHUDs. I wonder if they need to be there, given that there are also MedHUDs in the south-west storage
- The "medical crate" (right next to the HUDs) has no contents in it. There's also one south of paramedic.
- Would be nice if there were extra monkey cubes that didn't require geneticist access. 
- The "open the main medbay doors" button in the reception is very awkwardly placed. It looks bad because the sprite supposed to be on the wall, but it's on the desk. And there's a disposals chute in front of it, which makes access unpleasant.
- It would also mean that doctors will need to camp outside of medbay if they want to let patients in (because, let's face it, nobody's going to man reception). But that might not be a bad thing?
- Speaking of reception, maybe doing something like this would make people man it... That is, *super* easy physical access to incoming patients. Because playing a mere receptionist clerk who only chats with patients, and then relays the same thing to actual doctors just doesn't work in practice. (and, yeah the door button is still there.. uh.. mapping is hard)
![20220501-010423-StrongDMM](https://user-images.githubusercontent.com/7831163/166127798-0cc34434-3b09-4dd1-a000-11e5ef3071ec.png)
- I want to point out that the coroner has to drag the bodies to/from morgue across the public hallway, and that the coroner's office has glass windows. Unlike all our other maps. I don't hate it, but it's definitely an interesting decision. 
- Double-walls north-east and north-west of CMO office. I believe we really dislike those, but not 100% sure.

Non-medbay:
- too many electrified windows in engineering for no apparent reason
- not a fan of tech storage (in engineering) looking like it was copy-pasted from box, space and all. It's easy for me to say, of course, but i'd like to see it completely revamped (or removed and scattered around maybe?)
- same for primary tool storage. Copying the homework is fine, just make it look a bit different.
- double-walls west of primary tool storage
- not a fan of medmanints being very long AND a dead end.
- airlocks above and below the bar have very weird walls with them.
![20220501-011955-StrongDMM](https://user-images.githubusercontent.com/7831163/166128093-a8bb8800-57d3-4776-8edc-44958848d4f5.png)
![20220501-012018-StrongDMM](https://user-images.githubusercontent.com/7831163/166128106-23a98bb1-e8ac-4e82-a27b-3efd92722057.png)
- engine is encircled in a wall, a double-wall, and another double-wall. Not that it matters for antaggery, but just feels excessive. Also, how are you supposed to eject delamming SM then?
- Bridge inner conference room being electrified looks weird, but i don't play enough command/antag to know if that's an issue.
- Processing being fully visible from the public hallway is great. Sec mains would probably hate this though.

Aaand that's it. At least for now.
Good job overall! More maps = more good!

2022-05-01 01:57 UTC, Mitchs98 commented
I actually didn't even notice that processing was fully visible and accessible from the public hallway...that actually is a really big problem in my opinion. It only compounds the issue I have with security being a deal less secure than other maps. 

Processing really shouldn't be so easy to break into and nab people/interfere with processing.

2022-05-01 02:03 UTC, moxian commented
Processing being easily accessible is good because: 
- that's where officers are most of the time and
- it being accessible means i can actually *get a hold of them* if i need to.

It's not easy to break into because the glass is electrified. But i won't object to the second glass wall around it.
As long as i can point to it from outside and get officer's attention that way, i'm happy

2022-05-01 03:16 UTC, Mitchs98 commented
> * it being accessible means i can actually _get a hold of them_ if i need to.

You can contact officers on comms or VIA PDA. Lessening the security of security, especially processing, isn't really worth making it easier to find an officer imo. 

And an electrified window _really_ doesn't stop people much at all, it actually is quite easy to break through it.

2022-05-01 07:47 UTC, AffectedArc07 requested changes
Please add this map datum to the CI workflow. Just find the line with a bunch of other map datums and add this to the rest of the list.

2022-05-01 09:22 UTC, S34NW commented
A big fan of the overall design. I do have multiple points of feedback and will give you a more in-depth review soon.

2022-05-01 10:14 UTC, Miraviel commented
Finally, we can detach science easily and just float into space! <3

Jokes aside, this looks amazing. I will take a look at it as well later, but at a first glance, I cannot wait to play it.

2022-05-01 10:16 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/166140376-fad26c81-ac76-4e5c-aad1-d2818f4ec4e4.png)
You use multiple wires with blank `tag` variables. These need to go.

![image](https://user-images.githubusercontent.com/12197162/166140394-5ca394fa-f196-4565-b172-8d73bddb00fc.png)
Avoid wiring setups like these as they cause confusion, putting a node down along the horizontal path here will work fine.

![image](https://user-images.githubusercontent.com/12197162/166140407-d2655e78-d26f-4643-aa29-2cec663061f6.png)
Run pipes together when possible, and do not run pipes across the same turf as scrubbers or vents. This is a common occurrence on the station, and needs tweaking.

![image](https://user-images.githubusercontent.com/12197162/166140453-185b2a2e-b1cb-4347-93cd-1a0345658642.png)
It is mostly accepted now that we use electrochromic windows for head offices, not shutters.

![image](https://user-images.githubusercontent.com/12197162/166140540-7f0f1c85-27ff-4609-b2e2-1d77d9d1a107.png)
Wires under walls are a no-go, please consider putting a tinted window down or something. I don't really see an easy way to fix this without compromising the area's security to be honest, unless you make the SMES room less secure.

![image](https://user-images.githubusercontent.com/12197162/166140584-a023aa45-b66c-4151-93f6-3db77d22244e.png)
We don't use these anymore

![image](https://user-images.githubusercontent.com/12197162/166140592-ab200fd7-161f-4975-b582-eb9ff4f36896.png)
This is a bit much, please run them under the window using nodes to connect them.

![image](https://user-images.githubusercontent.com/12197162/166140620-af6f533f-75d8-4881-b049-466bfc0fbbe4.png)
Same here

![image](https://user-images.githubusercontent.com/12197162/166140626-39e10a5b-8513-42d4-8c5d-4961cfdf9808.png)
More wires under walls, also please put catwalks under wires if you are running them through space.

![image](https://user-images.githubusercontent.com/12197162/166140665-e6bce139-8411-4847-9913-50975f0bd7e2.png)
Disposal to nowhere.

![image](https://user-images.githubusercontent.com/12197162/166140710-dac97ac5-6672-4775-88c8-2906e7cab90a.png)
thematically looks nice, but please consider making a new plasteel subtype with this icon, as opposed to using the plastitanium pod stuff.

![image](https://user-images.githubusercontent.com/12197162/166140742-c21300b6-d48f-4cc2-9c3e-41ff48a7cda7.png)
Wires under these three collectors are red, not yellow.

![image](https://user-images.githubusercontent.com/12197162/166140772-c4932adb-8fa2-4a17-9696-0231d16e851f.png)
We don't use blast doors as shutters, please swap these out.

![image](https://user-images.githubusercontent.com/12197162/166140831-b3f048ce-7dd0-4d8b-ad70-063e307c1d56.png)
more wall wires, also all red is a bit confusing here, can you separate the two nets visually with yellow wires please?

![image](https://user-images.githubusercontent.com/12197162/166140879-f9be3cda-0e1d-45a2-910e-36936af433df.png)
While I like the idea of a maze-like layout, you can currently snipe the AI without any risk of being sniped by thermite-ing 2 walls and hacking one door. This needs to change as I guarantee the AI will get blasted like this every time.

![image](https://user-images.githubusercontent.com/12197162/166140994-272e8d15-9221-4baf-9fe9-e9a6cc986a2d.png)
this needs addressing

![image](https://user-images.githubusercontent.com/12197162/166141018-b79329eb-36da-47ae-a98c-b4a886977844.png)
This return pump and pipe from the coolant will do nothing, as it is the same pipenet both sides of the pump, it's fine for this just to terminate under one of the servers

![image](https://user-images.githubusercontent.com/12197162/166141053-e7e2a5c7-c157-4953-97a4-c60b98dd6260.png)
double-wall in the south of this room is not ideal.

![image](https://user-images.githubusercontent.com/12197162/166141086-adbc5db3-5e80-4dbe-a54f-9006892327a7.png)
I don't think this doppler array is pointing the right direction

![image](https://user-images.githubusercontent.com/12197162/166141117-6970c621-c83f-473c-bfb8-6867835e98d9.png)
Again, this heat-pipe does not need to be returned.

![image](https://user-images.githubusercontent.com/12197162/166141166-01223faf-8269-4742-99ff-4bfcb0cb266e.png)
These are weirdly pixel offset and are not on the same tile. move them to the tile they are on and then pixel offset it negatively.

![image](https://user-images.githubusercontent.com/12197162/166141241-e89a1d01-7ae9-48fc-a315-0e80f0823abe.png)
Maybe it's just me but the mix and match here seems a bit off, good that these are actual trees and not overlays though :)

![image](https://user-images.githubusercontent.com/12197162/166141360-c0b87643-36fe-437a-8c30-8dfd0236a117.png)
this is still space area

![image](https://user-images.githubusercontent.com/12197162/166141390-934c5060-a399-44da-8865-ab61ef322b90.png)
holy mother of god, what the hell is going on here lmao, is there a way to make this more user-serviceable? Currently, anyone looking at this with a view to fixing/altering it will just pass out.

![image](https://user-images.githubusercontent.com/12197162/166141422-f0b765d5-8c44-4f29-b291-f72fb36ae0ea.png)
![image](https://user-images.githubusercontent.com/12197162/166141439-89b3b7af-ea72-418f-9e3d-4d6e2ec700bf.png)
![image](https://user-images.githubusercontent.com/12197162/166141448-e481f976-2c0a-4eac-89e0-56085aff0bd0.png)
this is far too much wire under wall, please no.

![image](https://user-images.githubusercontent.com/12197162/166141491-ed793c7e-2141-479f-a8a9-c6a92fa781e3.png)
more cryo-sleepers please!

![image](https://user-images.githubusercontent.com/12197162/166141584-ee8c43ff-d389-4bfa-a48f-531c6120502c.png)
I feel only the perimeter of secure areas should be r-walled unless there is a specific extra secure area within the main perimeter.

![image](https://user-images.githubusercontent.com/12197162/166141621-9de37ad4-dc64-4467-84d8-1bdfc5f2114a.png)
please yeet these lattices, we want to keep docking zones totally clear

2022-05-01 20:21 UTC, kugamo commented on code/modules/mapping/shepardstation.dm
> +	fluff_name = "NSS Shepard"
I thought Arrhodes would work well. Its from _The Mask_ , and sounds cool.

2022-05-01 21:03 UTC, moxian commented
Wandered around the station. Some doors don't quite work:

<details><summary>longtext</summary>
The science airlocks to space don't airlock (buttons do nothing, doors openable by hand)

![20220501-202841-dreamseeker](https://user-images.githubusercontent.com/7831163/166163866-7472cccb-789b-43a2-a0a3-cd76b7943c74.png)

science doors don't open at all (and there's no button i could find)
![20220501-202458-dreamseeker](https://user-images.githubusercontent.com/7831163/166163884-d94d1a87-cecf-48dd-8d3d-4e634b193fbc.png)
xeno doors also don't open, buton doesn't do anything
![20220501-202747-dreamseeker](https://user-images.githubusercontent.com/7831163/166163908-8198b676-06af-4c03-b8a7-b5dce008088b.png)

There is a number of opaque doors right next to windows. It makes sense if the windows can be tinted/shuttered, but looks weird otherwise:
![20220501-201840-dreamseeker](https://user-images.githubusercontent.com/7831163/166164062-59fd17e9-a418-4de8-a20f-2dbb51550223.png)
![20220501-202200-dreamseeker](https://user-images.githubusercontent.com/7831163/166164063-23470c0f-65d8-4b32-b470-b42e7c624301.png)
![20220501-202211-dreamseeker](https://user-images.githubusercontent.com/7831163/166164064-b5260cee-41e9-4225-8130-675c5b40db22.png)
![20220501-202713-dreamseeker](https://user-images.githubusercontent.com/7831163/166164068-223c417d-0ab9-490c-ad81-b012d683d256.png)
![20220501-202729-dreamseeker](https://user-images.githubusercontent.com/7831163/166164071-b07001a7-ee93-4495-b60c-c93bf470cb94.png)
![20220501-204734-dreamseeker](https://user-images.githubusercontent.com/7831163/166164072-fec44446-4699-4ea5-8b1a-4955d12612b5.png)
![20220501-205832-dreamseeker](https://user-images.githubusercontent.com/7831163/166164367-2e14f7fb-7066-4109-859d-c245e77b4bb3.png)


Atmosia having blast doors leading to common eng area is probably unjustified, when it has glass windows right next to it. One of the two probably has to go
![20220501-205048-dreamseeker](https://user-images.githubusercontent.com/7831163/166164114-9e2fadfd-e32e-44b5-868b-b700adb00270.png)

</details>

2022-05-01 21:35 UTC, S34NW requested changes
I really do feel that shutters for head offices should be limited to Research Director and Head of Personnel, the rest should use electrochromic windows.
Science is often at risk due to raging xenobio mobs and plasma fires, so the extra safety makes sense there. HoP also needs some additional layer of protection over just glass due to the nature of greytide-ing masses that congregate at the HoP line.

I feel the rest do not need them, protection wise head offices should not be bunkers. How would you feel if you went in to speak with your boss for a private chat and they close mechanical security shutters as opposed to closing the blinds?

2022-05-01 22:15 UTC, AffectedArc07 commented on .github/workflows/ci.yml
> +        maptype: ['/datum/map/cyberiad', '/datum/map/delta', '/datum/map/metastation','/datum/map/shepard']
```suggestion
        maptype: ['/datum/map/cyberiad', '/datum/map/delta', '/datum/map/metastation', '/datum/map/shepard']
```

2022-05-01 22:31 UTC, AffectedArc07 commented on .github/workflows/ci.yml
> +        maptype: ['/datum/map/cyberiad', '/datum/map/delta', '/datum/map/metastation','/datum/map/shepard']
Ignore this

2022-05-02 14:37 UTC, LightFire53 commented
> 

Seconded, we are currently in the process of moving to this in existing maps.

2022-05-04 18:23 UTC, Sikroth commented
i like some of the ideas here. Just a couple nitpicks / opinions from that posted picture.

Some of the areas seem to have a lot of airlocks. For instance to get from the hallway to medbay cryotubes you have to go through 4 airlocks. In the cyberiad you only need 1. Personally at least for medbay i'd prefer a more open design though that's mostly personal preference.

Also a lot of double tile airlocks around. I understand using them especially in the white connector areas, but they tend to be a little janky when they get damaged, plus they are not customizable or paintable, they're just white. I'd personally try to use less of those.

Not sure I like that the bridge is on a separate power net too, I think it should still be affected by powersinks and the like. The PDA server is also really hard to reach now but I don't know if that's a big problem.

The way the SM cooling loop goes into space is a little weird, with the pipes going under 2 tiles of windows, and then one of the HE pipes going into a normal one to go through a wall. I wonder if it'd be possible to leave a bit more space so that looks less scuffed. (Also, why's there a disposals bin in space near the cooling loop?)

2022-05-06 05:06 UTC, Bm0n commented
I stopped halfway through reviewing the map because I got exhausted but here we go

**MEDBAY**

RED: Lightswitch in a window, looks really weird, should be moved.

ORANGE: The APC is unconnected from the power grid and should be moved if

BLUE: The consoles are moved aft so that the plant isn't forever trapped behind machinery
![breakroom](https://user-images.githubusercontent.com/92271472/167067056-f52699a1-f3d7-49a3-b29e-e0461be2945a.png)

Two scrubbers under this OR computer in surgery, plus that vent off port side is unconnected
![OR2](https://user-images.githubusercontent.com/92271472/167067224-4f448df2-e008-4841-a015-819f023169be.png)

Unconnected vent
![CMO office](https://user-images.githubusercontent.com/92271472/167067460-1b45446d-c62b-434d-96b7-c5e972b74c3f.png)

Highlighted pipes lead to nowhere
![genetics](https://user-images.githubusercontent.com/92271472/167067508-5debb254-e795-40ae-b0b9-466d3f4026ad.png)

Why are there a pair of static spawned medhud sunglasses here? This is better served by a random spawner
![Geneticsmaints](https://user-images.githubusercontent.com/92271472/167067614-e4f32f09-367d-477e-a2ae-523501653e38.png)

**SERVICE**

Pipe lead to nowhere
![chapel](https://user-images.githubusercontent.com/92271472/167067679-e97cbcab-8f9f-492a-9531-95972c26b0c0.png)

Unconnected pipe
![library](https://user-images.githubusercontent.com/92271472/167067747-ea762383-86c5-4773-87bc-5af250202ec9.png)

Take my word that people will power game the shit out of this door and floor tile for diamonds on nuke ops, best replace it with something more normal
![aft maints](https://user-images.githubusercontent.com/92271472/167069019-57ebc2d2-63e2-41ae-8a92-cbd5c17dd692.png)

RED: Unconnected disposals chute

ORANGE:  4way scrubber pipe with one end leading to nowhere
![mining](https://user-images.githubusercontent.com/92271472/167068823-a0d12616-430b-417c-bafe-4dc8efe808d8.png)

The Theater has pipes and a wire leading to nowhere and there are no vents/scrubbers in any of the 3 rooms
![theater+clown+mime](https://user-images.githubusercontent.com/92271472/167067884-6fcb2423-79dd-4cb8-a846-82c3aed55cc2.png)

You will die if you go AFK in any of these small dorm rooms for an extended period of time. There are no vents or scrubbers in them.
![service hall](https://user-images.githubusercontent.com/92271472/167067970-1c8ff64e-8d6b-453a-9497-11b9f509d6e1.png)

**SCI**

Two power nodes under this APC for some reason
![server room](https://user-images.githubusercontent.com/92271472/167068130-0f9aaedf-135c-4606-8511-e7a8e502c1ba.png)

Unconnected disposals chutez
![tox launch](https://user-images.githubusercontent.com/92271472/167068205-c865b326-80b4-43ba-86ba-0c8b2f92a3d5.png)

**ENGI**

All these pipes are unconnected for some reason
![engi foyer](https://user-images.githubusercontent.com/92271472/167068308-18ac06b5-ce94-4543-97f0-0398ec6fa992.png)

Random firealarm under this engineering sign
![engi storage](https://user-images.githubusercontent.com/92271472/167068446-af7e6c40-9d87-4bb7-bf65-609f39ced6bb.png)

This is unconnected
![atmos maints](https://user-images.githubusercontent.com/92271472/167068953-83152e89-4889-4feb-86c3-97921624970a.png)

**SEC**

This room in perma has no vents despite being cut off from the rest of perma with a door.
![perma hydro](https://user-images.githubusercontent.com/92271472/167068556-02b06a37-a0cb-4837-8f4f-24a02fd7b5b2.png)

No vents/scrubbers in the bathroom
![sec bathroom](https://user-images.githubusercontent.com/92271472/167068636-c1d72b28-e1c5-4f54-ba1f-d4ce3c5049b9.png)

There is sand here for some reason
![sec lobby](https://user-images.githubusercontent.com/92271472/167068682-0f3c8d91-4a4a-41f5-9b23-05117b90542b.png)

RED: Two unconnected vents/scrubbers

ORANGE: Probably best to push this vent down by one tile so that it matches the other cells
![brig cell](https://user-images.githubusercontent.com/92271472/167068718-bd711caf-21e6-4adf-8eb9-f484cbe13d2a.png)

**COMMAND**

RED: Unconnected vent/scrubber in the vault
ORAGNE: These gold statues will be power gamed on nuke ops. Just put a single gold bar in the vault as the other stations do
![vault](https://user-images.githubusercontent.com/92271472/167069310-976a9d99-5163-46e2-b3e7-1523f4e29998.png)

Unconnected disposals chute
![captains office](https://user-images.githubusercontent.com/92271472/167069445-8bfcd7bd-c3be-4c68-aea0-5d21e636d0ea.png)

Three rwalls and the AI is dead, no turrets to defend you, nothing. You get full access to the AI with only 3 rwalls in your way.
![AI sat](https://user-images.githubusercontent.com/92271472/167069581-e946b5dd-2e49-4b58-917f-6405d98f71f1.png)


**HALLS**

Only two vents for this long hallway? Feels a little lacking to me
![centprime](https://user-images.githubusercontent.com/92271472/167067811-5d8f6d3f-ae0e-4700-834b-e130ce930ef1.png)

Unconnected disposals chute
![arrivals space](https://user-images.githubusercontent.com/92271472/167069251-a1d90b87-0cb8-47b0-aa25-116628d54155.png)

This really should be its own area... plus that light switch in there controls all the maints lights for that zone
![secEVA](https://user-images.githubusercontent.com/92271472/167069490-b247b300-f2f7-470b-aa3f-acce9381f64a.png)

**SPACE**

needs to be nearspace
![outside SM](https://user-images.githubusercontent.com/92271472/167069790-a6b40e59-7f69-4eb8-89d5-d0cd7b962239.png)

needs to be nearspace
![FOR ARRIVALS](https://user-images.githubusercontent.com/92271472/167069813-085ad04d-38c5-4769-9dec-aa626f38664b.png)

needs to be nearspace
![arrivals space](https://user-images.githubusercontent.com/92271472/167069830-2463687c-4b3c-4378-954a-930ec1543a62.png)

needs to be nearspace
![AFT PORT](https://user-images.githubusercontent.com/92271472/167069846-753aa568-a7c8-4c08-a07a-377b95f6ada7.png)

needs to be maints
![secEVA](https://user-images.githubusercontent.com/92271472/167069881-8bcf8ce7-97d1-4f05-bf13-83f026f9156f.png)

**BALLANCE**

This is the the total amount of loot spawners on Shepard station compared to box. You are about 100 short and should try to bring it more in line with Box
![loot](https://user-images.githubusercontent.com/92271472/167069913-e403910f-48f2-40b1-aca5-e1eb5cfbf03a.png)


Again I got exhausted so I stopped, there's probably more. There are also a lot of pipes running underneath scrubbers, vents windows and walls, something that I know other mappers would complain about but I really can't be asked to list them all and personally, I see it as a non-issue as Box is just as guilty of doing it

2022-05-06 05:10 UTC, Bm0n commented
Did I post a review just you updated the map? the timing... oh well some of that might be out of date as it pertains to sec

2022-05-06 17:02 UTC, Mitchs98 commented
The recent changes to the brig area with processing alleviated all my current concerns with the map. I'll give it another once over once I'm feeling better, but it already seems pretty improved from all the suggestions.

2022-05-07 09:08 UTC, moxian commented
<details><summary>tried to solo playtest it a bit</summary>
bottommost filter in the SM chamber should have `filter_type: 2` and not `filter_type: "2"`; it expects a number, not string.

![20220507-064820-StrongDMM](https://user-images.githubusercontent.com/7831163/167242470-af823d1a-baeb-4f6d-bf7b-956733460bdb.png)

This gas flow metter in atmosia *looks* like it measures  the flow of the brown pipe leading to SM, but it fact it is connected to distro, and is thus misleading

![20220507-064648-dreamseeker](https://user-images.githubusercontent.com/7831163/167242459-8a686b30-848b-4201-ad65-ffe79e9e0f66.png)

missing pipe (or it's not displayed? it's weird, when i tried to RPD a new pipe there it didn't show, but when i tried to RPD *again* i got told that the pipe of the same type is there already?.. weird!)

![20220507-070335-dreamseeker](https://user-images.githubusercontent.com/7831163/167243009-88f07e78-2723-4bec-9dc9-45135477f9dd.png)

Would be nice to get small lights in the solar power airlock lobbies

![20220507-083018-dreamseeker](https://user-images.githubusercontent.com/7831163/167246190-6d548c6e-32a8-45b6-be6f-1fd47561242f.png)

Probably not your fault but this airlock by medmaints doesn't let me in. Pump is not siphoning air. I encounterd the same problem with the NE airlock, but that one started working after a couple attempts. Again, probably not your fault, given that it's a standard mapping helper, but.... For what it's worth, Box is not using the helpers and instead places those by hand...

![20220507-083942-dreamseeker](https://user-images.githubusercontent.com/7831163/167246547-a32b2a7a-002a-4fda-b012-f44385fee2eb.png)

Medmaints, cable undeer solar tracker facing the wrong way.
I'd write it off as deliberate prank on the engineers, but the cable color doesn't match the rest of the solars, so looks more like a mapper oversight

![20220507-084509-dreamseeker](https://user-images.githubusercontent.com/7831163/167246731-5861f60d-7cfe-4730-883f-e46bac40b915.png)


The power ran out on the station in the first 15 minutes; I failed to set up SM (mostly due to personal incompetence, not so much map fault), and thought that i can maybe set up solars to compensate. Well, solars don't compensate at all. (why even have them at this point smh)
Maybe bump the initial charge on the engineering SMES so that power runs out at 30 minutes mark rather than 15?..
(I am also stil unsure what exactly causes the drain.. I was thinking the SMES on the bridge, but in the latest version it isn't even connected to anything..)

Anyhow, i'd think that once someone more competent than me manages to set up power in a reasonable time frame (and strictly before the station gets depowered), we can call the map playtest ready.

</details>

2022-05-09 14:10 UTC, S34NW commented
Will give it another review pass tonight now it's marked ready

2022-05-10 06:32 UTC, Bm0n commented
The lattice here should really be a catwalk, you can't run wires over lattice in-game.
![wire catwalks](https://user-images.githubusercontent.com/92271472/167560734-27e795c2-e7b9-40aa-8a84-291b0da5cc1e.png)

Fore solar, wire is a node instead of a straight.
![near ai say solars](https://user-images.githubusercontent.com/92271472/167561526-3517026e-5660-4c90-b0fc-e77999c94fc0.png)

Fore solar control, two wires here that are a different colour over top of the red ones.
![fore solar](https://user-images.githubusercontent.com/92271472/167561597-a4ec8069-4e77-479d-89e7-2c39badf1d26.png)

Using grille spawners in space is a bad idea, it has a chance to spawn plating that has air in space which is bad for atmos
![near SM](https://user-images.githubusercontent.com/92271472/167561010-3b3184d7-a819-4e75-be44-3e5e13531cf4.png)

Rogue wirecutters in the cryodorms
![cryodorms](https://user-images.githubusercontent.com/92271472/167561177-0b37a879-029d-4ee6-a607-af89ac6b4d16.png)

This long wall of firelocks is pretty useless and looks ugly. Also, you might want to consider using the no_creep version of grass tiles here and in the public garden.
![hydro](https://user-images.githubusercontent.com/92271472/167561229-b74fe4b3-bcd2-4585-b307-9963af6c27ec.png)

Miss matched directional windows.
![EVA](https://user-images.githubusercontent.com/92271472/167561960-ceef5e06-fd47-4257-bc42-eaec03508129.png)

Server room SMES has no terminal so it's broken.
![server room](https://user-images.githubusercontent.com/92271472/167562126-a6765ded-2765-45fa-8a0e-18f196c95786.png)

This red wire has a tag of "" for some reason and should be replaced with a tagless version.
![wire tag](https://user-images.githubusercontent.com/92271472/167562459-1f1aaefc-c925-49fb-8f37-9f72edf83c51.png)

Same could be said about this pipe which has an iritalization_direction of 10(we don't use that var on para, only dir).
![near public garden](https://user-images.githubusercontent.com/92271472/167562498-4031309f-ae8f-4603-b796-ddfe5857e5cd.png)

You're also using the 25000 power versions of APCs in random places where they shouldn't be used. I don't blame you though because whoever made those prefabs didn't give the APC a custom name.
![APC 25000 bump](https://user-images.githubusercontent.com/92271472/167562713-93c8bfe9-4cdd-4800-bea0-b49f96b0aa9b.png)

2022-05-10 11:34 UTC, S34NW requested changes
<details><summary>Review time, images within:</summary> 

![image](https://user-images.githubusercontent.com/12197162/167609894-2a1c913c-b69a-4597-bb63-9a934699d568.png)
Please run these over catwalks not lattices, so they are user-replicable 

![image](https://user-images.githubusercontent.com/12197162/167610098-2fad096e-58cf-4ffe-81ab-9439e0727d03.png)
The plating here should probably be reinforced floors!

![image](https://user-images.githubusercontent.com/12197162/167610347-1c9e41a6-ba6f-4748-b36f-a9048ca83180.png)
The pipes in this solar make it a bit hard to see the wires, when there is ample room for them next to the wire run.

![image](https://user-images.githubusercontent.com/12197162/167611000-97b19a26-afa4-4c6e-a69f-11e11e09174c.png)
These are missing r-floors

![image](https://user-images.githubusercontent.com/12197162/167611452-301e39a3-5a81-4c01-b367-1133bd0e235a.png)
An APC is required in the cold room

![image](https://user-images.githubusercontent.com/12197162/167611792-8f752998-f844-4013-bfb9-157084d576a2.png)
Please do a pass on all your shutters to ensure they use the `preopen` subtype as opposed to being var-edited to be open

![image](https://user-images.githubusercontent.com/12197162/167612044-e765a12e-882d-4efd-a035-f2214ff4249f.png)
The flooring here could do with being distinctly security themed so the plebs know they cant walk in. (They will anyway but at least they cant claim ignorance)

![image](https://user-images.githubusercontent.com/12197162/167612811-6d991f21-cfd5-4920-b15d-a3417c03fa8f.png)
These support directions, so can be put sideways

![image](https://user-images.githubusercontent.com/12197162/167613015-036b1be9-4884-4346-a6f8-61a9027c6e94.png)
These cameras are named the wrong way around, East should be "Right" and West should be "Left"

![image](https://user-images.githubusercontent.com/12197162/167613836-d3cfdad2-e31c-4a3b-a913-588cc46e59e4.png)
These blast doors have no buttons to control them nearby

![image](https://user-images.githubusercontent.com/12197162/167614236-ead646ab-c7c4-48dc-9d14-354264cd30ea.png)
The APC for this area is missing

![image](https://user-images.githubusercontent.com/12197162/167614355-496b95e6-3bbb-4f5d-8aae-b5c34b58bec8.png)
This needs intercoms otherwise they won't be able to hear anything said by the other.

![image](https://user-images.githubusercontent.com/12197162/167614570-96e76ad8-f135-4a79-843c-979da79027ce.png)
If you update your branch from master, please remove the `right` subtypes of these and use the regular one with a dir.

![image](https://user-images.githubusercontent.com/12197162/167614944-5df34f6a-c9b8-4334-8104-4b3f906aeeab.png)
As with shutters, please do a pass on blast doors to use the `preopen` subtype

![image](https://user-images.githubusercontent.com/12197162/167615062-a3d7507d-d645-4609-9fd9-aeacfbfd35ab.png)
I'm 99% sure this needs a node under it to work?

![image](https://user-images.githubusercontent.com/12197162/167615368-1fcb7ce3-c327-4351-bf24-611b151148ca.png)
This room needs a locker with exile implants

![image](https://user-images.githubusercontent.com/12197162/167615472-be3372e9-11ac-4298-b5dc-fe1aa060a1ce.png)
No air or fire alarms here, also what is the purpose of the electrified grilles on the exterior? Seems way overkill as nowhere else has these.

![image](https://user-images.githubusercontent.com/12197162/167615955-c4b0fed1-33f2-49fc-aead-536686f06d76.png)
Both shutters and blast doors here have this name

![image](https://user-images.githubusercontent.com/12197162/167616122-3a09c5c7-b91a-4d19-9f74-9b1e5591f72f.png)
![image](https://user-images.githubusercontent.com/12197162/167616174-49bd7f3a-7214-4c2b-b474-c249e1562eba.png)
There is no need for the quarantine lockdown blast doors on these bits as ones further out will stop movement

![image](https://user-images.githubusercontent.com/12197162/167616397-87afb64d-0648-4253-a99d-918954b917e6.png)
This floor does not match the rest

![image](https://user-images.githubusercontent.com/12197162/167616452-878a94f8-a341-42a3-922a-7a581b83716d.png)
The patterns here seem a bit random

![image](https://user-images.githubusercontent.com/12197162/167616721-ef503c2c-8bcb-440c-bb94-7cd68a159f0e.png)
This area has two APCs but no air alarms

![image](https://user-images.githubusercontent.com/12197162/167617020-2df8a4c7-f288-441b-b627-4a172c06b98f.png)
Once updated from master, consider having both of these face the wall

![image](https://user-images.githubusercontent.com/12197162/167617375-f61009dc-0893-45f6-aaa6-8705964a8fa8.png)
The blast doors here seem a bit needless considering the IAA room has them on their exterior also.

![image](https://user-images.githubusercontent.com/12197162/167617571-b117d2d3-9367-4c38-80e4-c3f405dfc27e.png)
Now that this is not a public hallway, consider electrochromics like the rest of the stations use.

![image](https://user-images.githubusercontent.com/12197162/167617976-7c3e83e4-0f67-46ea-8068-1f086e57da74.png)
0/10 no ducky

![image](https://user-images.githubusercontent.com/12197162/167618150-2a77bd71-74a9-4017-b814-fb2aec608109.png)
A cycler with nothing to cycle to? (If you do this make the exposed turf airless)

![image](https://user-images.githubusercontent.com/12197162/167618442-8a88bd18-0629-41ed-8891-40dcb912319a.png)
Electrified disposal trunk?

![image](https://user-images.githubusercontent.com/12197162/167618906-50a9eb37-f707-4a82-8fe6-99bc6c59b631.png)
Tcomms not wired into grid and no air alarm

![image](https://user-images.githubusercontent.com/12197162/167618970-b2452149-49a5-41de-a67e-f71756239f11.png)
Needs a bluespace gigabeacon

![image](https://user-images.githubusercontent.com/12197162/167619324-2e120bd0-f1f2-402a-b25e-8f7cca5fcfc2.png)
No air alarm for the entry area into the sat from tube.

</details>

Overall, very good work. I like the new AI sat a lot. Keep it up, just minor playability tweaks to go!

2022-06-16 09:10 UTC, S34NW requested changes
A quick review from what jumped out at me:

![image](https://user-images.githubusercontent.com/12197162/174030372-4f122dce-e930-4637-82b2-135bfe13592d.png)
Green virology airlocks.

![image](https://user-images.githubusercontent.com/12197162/174030440-f901e990-735d-4af6-bf68-4a6be0becb0e.png)
Tiny fans for arrival shuttle

![image](https://user-images.githubusercontent.com/12197162/174030569-c95a765f-62c4-4251-bfe9-34ee4742d292.png)
Use rust spawners, not rusted walls.

![image](https://user-images.githubusercontent.com/12197162/174030942-ce000574-927a-4e02-9d14-5a9e425627fa.png)
Ideally this could be run under the window, but not a major issue.

![image](https://user-images.githubusercontent.com/12197162/174031107-2313134d-883b-4791-b452-1796aea48487.png)
This is quite confusing, but the heater loop does not need a return so that can simplify things. 

![image](https://user-images.githubusercontent.com/12197162/174032423-8bc7712d-14a3-4182-bec1-1f2aeb35ad5b.png)
Distro to waste probably should not be on at roundstart.

![image](https://user-images.githubusercontent.com/12197162/174033309-2cc73da0-d198-430e-b7a1-ed1e9e076838.png)
Filter to external here is actually air to distro

![image](https://user-images.githubusercontent.com/12197162/174033588-f0131163-80fd-4176-871b-001bc966cbd1.png)
This also leads to minisat, should be labelled as such

![image](https://user-images.githubusercontent.com/12197162/174034636-a7e42bc9-ae23-4410-8371-b6fdaf176eed.png)
This permabrig needs a specific maints area over the maints room, including the door, so prisoners can take shelter during rad storms. This area is the exception to the rule when it comes to re-using existing areas, use the nearest main maints area here too. It can forgo requirements such as air alarm/APC/etc.

![image](https://user-images.githubusercontent.com/12197162/174035167-6f4d19b9-e170-4f9e-beed-8876dbcc4d06.png)
Only the perimeter walls here need to be rwalls, anything within a perimeter of rwalls can be a normal wall.

![image](https://user-images.githubusercontent.com/12197162/174035826-403db268-de37-4497-a926-44feb71e1ed2.png)
This area could do with more seating, perhaps a sofa or something along one window?

2022-06-17 20:17 UTC, lewcc commented
Just walked through, here are some things I've noticed

![image](https://user-images.githubusercontent.com/89928798/174391882-308f29bb-a8da-4cfe-85a4-8825d014980e.png)
There's a door in the arcade that's over a wall.

![image](https://user-images.githubusercontent.com/89928798/174392625-d47b72d0-dc85-4e42-ae54-dfccf1c0f2c3.png)
Not sure if it's deliberate or not, but the backup SMES in the bridge is not wired into anything, and the wiring around it strikes me as a little odd.

Also on the bridge, I feel like the identity computer being over past medical consoles feels a little odd. The bridge has two mining shuttle consoles for some reason (one by the supply section, one by cappie), and it feels like the one by the captain could be replaced with the ID computer.

![image](https://user-images.githubusercontent.com/89928798/174395643-4cd1de90-3faf-4f05-8009-3480464d472b.png)

The crew monitoring console on the shuttle doesn't seem to work. I don't know if this is something transient but I haven't seen it elsewhere.

2022-06-18 20:39 UTC, LightFire53 commented
<details><summary>Another Passthrough</summary>

## Areas

![image](https://user-images.githubusercontent.com/16112919/174447548-67544a59-ca07-4855-bfd9-814cd0ee5782.png)

AI cam needs to be the AI area, and the lattice should probably just be nearspace

![image](https://user-images.githubusercontent.com/16112919/174447637-4c71fc1d-7b3e-4357-91a1-6701af76eca9.png)

All the external wall/windows here should be part of the area

![image](https://user-images.githubusercontent.com/16112919/174447705-b212c910-efd7-4a88-9d6a-e05a656c897d.png)

Window should be maintenance, the girder nearspace

![image](https://user-images.githubusercontent.com/16112919/174447780-fe955b4f-117d-4852-832e-5e713f8e777e.png)

This maintenance airlock should be in the maintenance area

![image](https://user-images.githubusercontent.com/16112919/174447816-02c0efbc-c647-45a4-a83e-40d267bb5069.png)

Space is nearspace, girder is space

![image](https://user-images.githubusercontent.com/16112919/174447858-81ce2446-cf2f-40de-9caa-31b99f8b5064.png)

More maintenance doors needing maintenance area

![image](https://user-images.githubusercontent.com/16112919/174447898-9d70a237-3dc8-4605-bfdb-c8c06d23046b.png)

Same here. I won't post more pictures, but I'll start listing areas that need maintenance area here (if I remember):

1. Cargo Warehouse
2. Mining Storeroom
3. Mining Maintenance Access
4. Surgery backroom
5. Morgue foyer/hallway area (with the shutter)
6. Bar Maint Hallway
7. Hydroponics
8. Emergency Storage at Arrivals

![image](https://user-images.githubusercontent.com/16112919/174448136-681b92cd-3364-4e0c-8660-662240b5920b.png)

It makes more sense to have those walls here be part of the area rather than nearspace

![image](https://user-images.githubusercontent.com/16112919/174448160-961b653e-b127-41d3-8546-348bbc3bd6b6.png)

Need to clean this up a bit, keeping viro contained to the walls instead of bleeding into maintenance

![image](https://user-images.githubusercontent.com/16112919/174448180-b9d5039b-2c5f-4f37-91d9-3ac41409a69f.png)

The lower part that isn't actually in the secure storage should probably be maintenance area

![image](https://user-images.githubusercontent.com/16112919/174448343-3e26a0d6-96a1-4b9e-9ec7-c7e7d64c7c25.png)

Secure armory camera not only doesn't have power, but will get squashed by gamma armory. The one outside perma also doesn't have power. As jank as it sounds, you could probably just make the one on the perma side part of the secure armory, so it functions for both

![image](https://user-images.githubusercontent.com/16112919/174448504-242f1fc3-a1b6-41a2-b6bf-f58fc44327bf.png)

Camera should be gravity area

![image](https://user-images.githubusercontent.com/16112919/174448697-c9eddd9f-6774-4180-9696-80a4adf9160e.png)

One of these should at least be a maintenance access, and maintenance area

![image](https://user-images.githubusercontent.com/16112919/174452747-8e687fc3-e20e-4260-a0af-492f3681aabc.png)

The space stuff should be near space, and there should be a plating tile under the upper window

![image](https://user-images.githubusercontent.com/16112919/174456386-af54de9a-f615-4a63-8eca-7b589989666f.png)

Camera needs an area


## Piping/Wiring

DISCLAIMER: As I'm not someone who has done atmospherics, the atmospherics area itself I'm leaving alone, however I will still comment on stuff outside of atmos and egregious issues inside of engineering

![image](https://user-images.githubusercontent.com/16112919/174454774-c02c96aa-a454-4783-8673-84bcd94d37c2.png)

Like this one, can get messy with pipe nets super bad quickly. Should find another spot to put these.

![image](https://user-images.githubusercontent.com/16112919/174454801-93169359-4aa3-468e-a177-e0440f8fcc2c.png)

This realistically can just be connected directly to the vent south, no need to run out and back in.

![image](https://user-images.githubusercontent.com/16112919/174454836-ef645351-5b68-408b-8acf-19f089f59c46.png)

I think this gas meter will run into issues with both the cyan and the scrubber being on that tile?

![image](https://user-images.githubusercontent.com/16112919/174454874-6364eeb2-8952-4e5a-96f6-e8b112fc670b.png)

Same with this pump.

To fix the two above, Atmospherics/Engine is one of the only places that we really openly allow pipes to run under walls/windows due to the sensitive nature of those areas and atmospherics. Go as ham as you need (within reason).

![image](https://user-images.githubusercontent.com/16112919/174448467-e84d743d-8115-4f2c-bc59-878ab1f3b453.png)

These should run on the interior, not exterior running under walls and windows

![image](https://user-images.githubusercontent.com/16112919/174449195-c2db7fe1-0b17-416b-8356-7e7cdbcbaf8c.png)

The 2 APCs on either end (ignore the middle) control the same area, when there should only be one APC per area

![image](https://user-images.githubusercontent.com/16112919/174449299-37f1fe21-9521-4fb7-91e4-7446b2c0102a.png)

We discourage the use of pipes under walls/windows unless there is absolutely no other way possible. This window could probably just be a maintenance airlock.

![image](https://user-images.githubusercontent.com/16112919/174449364-1a4bea5d-84d3-40a9-a7eb-c2c33a13cddb.png)

Similar instance here, however you could have the pipe run up the door and then in

![image](https://user-images.githubusercontent.com/16112919/174450222-236e0a10-b005-4a50-ad90-093b7210a305.png)

This disposal should run through the corridor

![image](https://user-images.githubusercontent.com/16112919/174450310-2699bd2a-713b-420a-b78a-752e57fea4ec.png)

 Same here

![image](https://user-images.githubusercontent.com/16112919/174450411-fff3d87e-793f-4408-977f-2d07ebb6471d.png)

Same

![image](https://user-images.githubusercontent.com/16112919/174450419-00428130-a599-49e2-9bca-1048563bca7c.png)

Window heresy

![image](https://user-images.githubusercontent.com/16112919/174450485-6421f2ae-bfd7-490c-b257-5ff05046b31c.png)

I'm not sure this blob over by disposals actually works. It will push it past the sort junction, if I'm understanding this correctly. It should be something like this below:

![image](https://user-images.githubusercontent.com/16112919/174450853-2f271340-f491-42a0-9047-77a93049882a.png)

![image](https://user-images.githubusercontent.com/16112919/174450823-0e3bd4e8-b09e-4471-a4b0-4644e9540e59.png)

(POST SCRIPT: We actually have bigger issues regarding this layout, see further below)

![image](https://user-images.githubusercontent.com/16112919/174451120-4d968a96-5f61-44c9-b9e8-60c2c1c11df7.png)

This should probably not be hiding behind a wall spawner, it could just sit in a little nook on it's own. If you do that, the power cable should be re-routed to follow the disposal piping below it.

![image](https://user-images.githubusercontent.com/16112919/174451453-80fd8992-8582-47af-a626-0753e25bdf99.png)

Run under the airlock please

![image](https://user-images.githubusercontent.com/16112919/174451163-1e5a3eb7-7841-4a87-bba4-b38d50efee69.png)

So, two of things:
1. Lots of pipes under wall, bad.
2. That top disposal is supposed to act somewhat as fast travel from what I understand, I think? Either way, it's piping is super jank. If you really really want to keep this as a fast travel, something you could do is have it run out an external airlock into another and then pipe it beside the normal disposal pipe so it's not running too long on the exterior (does disposal piping in space maintain air/pressure?) while not running under/through walls.

![image](https://user-images.githubusercontent.com/16112919/174452928-d02a1529-1dba-4e4b-9d29-d4e9024cec7a.png)

This has to be a necessary evil, I guess, unless you run them under wooden barricades (which would be preferable IMO)

Regarding your other fast travel pipe where this one ends:

![image](https://user-images.githubusercontent.com/16112919/174452854-84dd25b5-7d70-4c2a-9fe4-4903a17461bc.png)

We can move pipe to not go under window easily. For the other  [...]

2022-06-21 12:52 UTC, AffectedArc07 commented
PR Will be TM'd after https://github.com/ParadiseSS13/Paradise/pull/17887 is merged or closed due to conflict concerns.

This PR is not dead, do not worry.

2022-06-29 19:29 UTC, S34NW commented
![image](https://user-images.githubusercontent.com/12197162/176520100-d4f551e4-3b4f-4e1d-a4ec-ea91d61d27e6.png)
only the conveyors before the first flap work automatically here

2022-06-29 19:33 UTC, S34NW commented
![image](https://user-images.githubusercontent.com/12197162/176520813-4ad1405c-1eea-4000-a5ed-0e511210aaf0.png)
ERT shuttle airlocks do not auto-unblot at docking

2022-06-29 19:49 UTC, S34NW commented
Solar flares kill people on arrival shuttle and at arrivals, despite those areas supposedly being solar-flare immune

2022-06-29 20:41 UTC, AffectedArc07 commented
![image](https://user-images.githubusercontent.com/25063394/176540606-080b97c1-6dc6-47b2-8eff-8c01dcf6ce5a.png)

This wall has a scuffed area

2022-06-29 20:49 UTC, DanteR03 commented
![Paradise Station NSS Arrhodes 2022-06-30 014617](https://user-images.githubusercontent.com/101640837/176541969-367e5ed0-0562-4564-b571-2f3822e94d6a.png)
This request console is blocked and can't be interacted with unless you climb into disposal.

2022-06-29 20:52 UTC, S34NW commented
![image](https://user-images.githubusercontent.com/12197162/176542604-dc93420c-7746-448d-986e-f6adecbd87af.png)
this smoothing issues

2022-06-29 21:51 UTC, Samman166 commented
Played the PR and my feedback would be to add some sort of Quantum pad hub like Ceres has, maybe not one in each departments segment but one in a central area around bridge between the arcade and barbers, with a pad in each segment that goes to the central area. Medbay is super spacious and I love that but I would remove some of the wall clutter status displays and no smoking signs by the sleepers in favor of some more mounted defib chargers, I could only find one and it was pretty tucked away. One big issue was solar flares, with so many windows when one hit half the station died, this leads to my other point that it could use more maints in between segments(Not necessarily connecting them) and remove some of the windows. One of my favorite things however is the limited access between segments how there is only one bridge going between them, it made them a popular target for bombings as it disrupted the station a lot and cut off security to those areas. I heard good and bad things about the atmos piping being split up mainly that it made repairs harder but I think that could be remedied with the pad hub. The sauna is a great detail that I love but I would lock the heater connected to it behind an atmos only door because otherwise you can easily sabotage it by turning it up causing the temperature to reach 200 C, you could also put a mini fan under the wooden door to it so heat doesn't escape from the sauna. The dwarf fortress mushroom wine room was a great reference btw(If that is what you intended). I would consider adding some vents to one or two maint rooms for terrors/blob because from what I can see all of the maint areas with vents are next to each other in service maints, maybe the abandoned bathrooms in science maints or one of the maint bars. I heard the RD say their locker didn't come with advanced welding goggles but in hindsight they may have been taken by an acting. Tom is missing from the vault too(Unless he was stolen too). My last note would be that some of the maints are only one wide at times and this can make combat a pain for both party's as it devolves into a lot of friendly fire and who clicked first since you can't dodge. Although I complain about a lot I want to be clear that I love the map overall and some of what I am saying is of course objective(Subjective?) it's easy to tell a lot of effort went into this and you deserve some recognition and thanks for all of the work, so thanks a  bunch!

2022-06-29 21:51 UTC, iantine commented
![frefrecfd](https://user-images.githubusercontent.com/26665535/176551621-4b9768d9-464c-4c28-9ae6-ebbab129fb5d.png)

These two airlocks need to be set to One, not All

2022-06-29 21:57 UTC, BrickTheHooman commented
Syringe gun location needs to be updated, as it's currently spawning in the supply room instead of CMO's locker. The CMO also seems to have way too much sec access, as from what I tried I had access to labour shuttle area and evidence at least, which would make stealing contraband way too easy for command with access, as I assume this isn't only for CMO.

2022-06-30 12:51 UTC, Komrad822 commented
> 

Command has access to evidence on all maps which is the norm. Labor shuttle access isn't though so that needs to be looked into.

2022-07-16 14:14 UTC, AffectedArc07 requested changes

2022-07-16 14:14 UTC, AffectedArc07 commented on tools/github-actions/nanomap-renderer-invoker.sh
> +cp "data/nanomaps/ShepardStation_nanomap_z1.png" "icons/_nanomaps"
Re-add the meta line, you deleted it by accident

2022-07-23 19:35 UTC, Asmerath commented
44,160 and 45,160 table is broken, can just walk ontop of it as if it didn't exist, also acts like its flipped.

2022-07-24 03:25 UTC, Denthamos commented
So heres a few things.

Do not put space suits in maintenance as they are a controlled/limited item.  You should not get them for free guaranteed besides EVA or random maint loot spawn with the boxed space suit kit.
![maint suit](https://user-images.githubusercontent.com/24213815/180630836-ef9f26c8-e383-4a6d-98bb-0937977f4800.png)

Same as above.  No free space suits, lying around where they are not secure.
![arrival suit](https://user-images.githubusercontent.com/24213815/180630847-3ac20264-6d50-4280-b4d3-d0951bdc8088.png)

This room is not rad proof.  If it is a maintenance door in its looks, players expect the area past it to be rad proof.
![not rad proof](https://user-images.githubusercontent.com/24213815/180630869-a11ca048-70d8-4e94-8b8b-646000ba23ea.png)

No medhud sunglasses for free.  Those need removed.
![medhud sunglasses](https://user-images.githubusercontent.com/24213815/180630874-97689710-49d1-4288-b2e6-1c7ccfd94cb3.png)

2022-07-24 04:41 UTC, FloFluoro commented
Played for a bit as NTR, good map! Noticed some quirks, though:

* Bridge Maintenance doesn't block radiation
* NTR office doesn't have a keycard swiper
* NTR office doesn't have wall terminal for announcements
* Station's gravity (or lack of it) applies to the mining shuttle, even on Lavaland

2022-07-24 04:59 UTC, BakKeener commented
![image](https://user-images.githubusercontent.com/42121019/180632903-a047963c-0a82-487e-aef0-62433ec3b157.png)
bartender cannot grab flasks on this table due to disposal bin and boozevendor

2022-07-24 14:52 UTC, Tourte-Yaya commented
The admin shuttle (Armory and medical one) is eating the ferry and ERT shuttle once all of them are docked on the station, also the vox shuttle can't go back to CC once they went on station, nor is the navigation console able to be used for custom location.

2022-07-24 14:56 UTC, AffectedArc07 commented
This map seems to perform than the others across the board, not regarding maptick, but the rest of the MC cycle.

I will attempt to use the experimental profiler later to capture all of this, but its gonna be a lot to look into.

2022-07-24 15:04 UTC, Komrad822 commented
Ok, from playing a few rounds in Science. Xenobio needs to start with a beaker box, 2 monkey boxes and a syringe box. These are core elements to the job.

Second, please put a toolbox in rnd so they can immediately get on it and not have to contest with people in like scichem for the tools.

2022-07-24 18:43 UTC, Christasmurf commented
Some notes with the HoP office:
-The equipment locker (one closest the door) apparently can't be opened with a Head of Personnel ID card, I had to get the Captain to get it for me.
-There is no light switch in the office.
-There is an AI display and ian figurine inside the wall making an odd image
![image](https://user-images.githubusercontent.com/25437893/180661405-d2b2b7e1-e22a-41ba-a5af-ccce421515fc.png)

2022-07-24 21:01 UTC, petermorck commented
The scrubber outside the SMES room by port fore solars is not connected to the pipe network.

2022-07-25 00:41 UTC, Alantodne commented
im not sure if this is intended but I found at least 1 pile of cardboard that seemed to be a 50 stack. I am not sure if this is intended since they are normally like 1 piece of cardboard rather than 50. 
![image](https://user-images.githubusercontent.com/44008012/180673217-fc10ad74-2e42-4f6e-883a-db68ef832271.png)

2022-07-25 00:45 UTC, Asmerath commented
Missing scrubbers pipe at 204,186
![pipe](https://user-images.githubusercontent.com/17059084/180673400-4594af85-14ca-4cb6-a907-0f2e6256ec1e.png)

2022-07-25 00:54 UTC, Denthamos commented
Area not properly defined here so that wall in that T section between command, science, and service is 'space' and not maintenance.
![image](https://user-images.githubusercontent.com/24213815/180673857-fc3d2b44-2145-430b-8e03-ae3b87ade3a3.png)

2022-07-25 01:00 UTC, rythenx commented
![image](https://user-images.githubusercontent.com/90358236/180674217-3932d377-94eb-41f1-a441-0e69990700cb.png)

These disposals pipes overlap.  Is this possible to do yourself without level editor?  If not then it could be an issue if anyone has to ever repair this.

Also secondly, it seems like the captain office is missing a floor safe.  He is also missing a note giving him the code for the floor safe and for the vault safe.

2022-07-25 01:01 UTC, Denthamos commented
The SIT shuttle docking point should be a wall, not a window.  Makes it harder to spot.
![image](https://user-images.githubusercontent.com/24213815/180674366-06428c19-49be-4737-88f3-312113a65f49.png)

2022-07-25 14:28 UTC, rythenx commented
I'm pretty sure the captain office is missing the hand tele that is supposed to spawn there.  The one in the teleporter room is there but I wasn't able to find one in the captain office and even used SDQL to try and search for it and only got one result.

2022-07-25 19:28 UTC, Sikroth commented
Since the map is now being played I noticed there's a bunch of cool new tiles being used in it.

I know it's not a high priority for this PR and I don't mind if it happens after it's merged, but I'd like to request that these new tiles are added to the modular/floor painter so we can use them ingame! 😄

2022-07-27 04:26 UTC, Christasmurf commented
Apologies for small image but
![image](https://user-images.githubusercontent.com/25437893/181161266-56277340-5436-4ffa-8731-7dab9ca400b5.png)
Detective has access to the shutter buttons on the morgue, but not the door next to them. After speaking with other admins it seems the detective is meant to have morgue access - the door next to the shutters might need access changing, but the internal one connecting to the rest of medbay is fine being inaccessible

2022-07-27 17:33 UTC, AffectedArc07 requested changes
Apologies for the delay on this, I needed to profile an entire round then got ahold of a server with 64GB of RAM just to open it (thank you Denghis).

I have 2 really big issues with this map, owing to both performance and map design.
---

### Map Design Woes

Here are some issues I have in no particular order

<details>
<summary>Expand</summary>

The ghost metagaming room needs to go
![image](https://user-images.githubusercontent.com/25063394/181309135-3d62d428-5469-4ca3-a950-dfcf0533c76d.png)

---

Medical storage is now the easiest room to loot in the world
![image](https://user-images.githubusercontent.com/25063394/181309230-bf53a15a-5033-416e-9ce6-359c1213c72f.png)

---

Maintenance being vented & scrubbered is going to make terrors even more of a pain in the ass to fight as its no longer a confined space for them
![image](https://user-images.githubusercontent.com/25063394/181309491-8873385f-d987-4c89-a5f3-9d4a23a36d22.png)

---

The positioning of the AI core makes it impossible to take down from range, making a malf AI almost unkillable
![image](https://user-images.githubusercontent.com/25063394/181309781-32a7b9a0-a639-41d5-8ef8-b4bd64a479b3.png)

---

Breaking into said core chamber now only requires dealing with a pane of glass and a single turret, which can easily be cheesed easily with a locker
![image](https://user-images.githubusercontent.com/25063394/181309874-40c4f3b8-31cb-4e26-9962-5cea5f5bccc0.png)

---

The station lacking a central loop means getting places quickly is incredibly inconvenient. If you arrive as a scientist its a good 2-3 minute walk to the department as opposed to 1-2 on box, especially if you're in toxins.
![image](https://user-images.githubusercontent.com/25063394/181310471-e9d5431a-f533-4f53-b939-eaaccfef3641.png)
And yes I know you can use maints as a shortcut here, but you shoulnd't have to, especially if theres a cult about or similar

---

The AI sat having *three* broken computers off the bat not only asks the question of why a state of the art research station's AI core would have broken equipment, but it also ends up turning into "Help what is this broken computer" tickets
![image](https://user-images.githubusercontent.com/25063394/181310823-748b0ecd-80ba-49ba-910b-a8f61c945c9e.png)

---

Atmos having a space loop is good, but why here?
![image](https://user-images.githubusercontent.com/25063394/181310936-eb76e83d-d4db-418d-abda-2323895c264a.png)


</details>

## Performance Issues

During testmerges of this map it has been found to have pretty bad performance. After doing a deep dive, the issue is clear.
Here is a random sample of ticks
![image](https://user-images.githubusercontent.com/25063394/181311151-573aaabb-533c-4423-8e9a-ee0ce957efbc.png)

If a tick is >50ms, its overran and will be perceived as lag. Notice how massive chunks of the tick are just `SendMaps`?

If you look deeper, you can see now why it lags so much
![image](https://user-images.githubusercontent.com/25063394/181311366-08a2aab3-579d-4374-8972-3b541f18dd14.png)
![image](https://user-images.githubusercontent.com/25063394/181311428-1d69e6b7-0ce8-4028-a909-935d75a71d91.png)
![image](https://user-images.githubusercontent.com/25063394/181311467-5db11150-d38a-4a0f-9d60-b89a3f6bad36.png)
![image](https://user-images.githubusercontent.com/25063394/181311504-a758ad5b-e83e-477f-b27f-5ccedde1424d.png)

As you can see here, most of the CPU is gone just on sending map updates, largely due to how dense areas can be here. 
![image](https://user-images.githubusercontent.com/25063394/181311929-26770c9e-27a7-4b43-b31e-ab5ac186ae01.png)

All of these objects need encoding and sending to the client, and a lot of areas on the map are denser than this. 

With the tick usage of sending maps being so high, the MC can be left with as little as **2ms** to do all its processing in. A mere 2 milliseconds to handle:
- Player input
- Lighting
- Atmospherics
- TGUI updates
- DB queries
- Mob life
- Machinery processing
- Backend timers
And everything else I havn't mentioned.

---

TLDR: The map needs a serious overhaul in order to even have a chance of being merged.

2022-08-01 01:52 UTC, Leanfrog commented
The various public access EVA kits need to go, while incentivizing exploration of space is nice it has much broader balance implications. EVA gear is normally locked behind having to do crimes or getting access to get it for jobs that don't have it by default, this is because space makes it very easy to escape from security, especially so if they have a free jetpack to go with the suit, we removed species being spaceproof by default for pretty much the same reason, it was too easy of an out for just about any situation, this is basically the same thing but anyone can get it if they just rush it right off the bat, normally at least security would be able to immediately prosecute if someone were to break into EVA and steal a suit, but since these various EVA suits are on public access that can't happen.

2022-08-21 10:26 UTC, kugamo commented
I am not happy with the redesign, I really should have closed this when the initial version was found to be unviable.  Maintaining this has been and is exhausting. Thank you to everyone who supported this project. But I am not willing to continue this much effort for something im not proud of, nor do I care to deal with the inevitable problems that will come from testing. Thanks again for everyone who supported it, sorry it couldnt work.

2023-04-08 06:49 UTC, closed without merging