A tad more descriptive Air Alarm interface (and valves)
ParadiseSS13/Paradise pull request #17715
Opened 2022-05-01 19:03 UTC by moxian

## What Does This PR Do
Makes air alarm show decimals of the gasses concentraion.
Makes examining a pipe valve tell you whether it's open or closed
Makes opening/closing a pipe tell you that you did so.

## Why It's Good For The Game
Currently the air alarm gas concentration % display is rounded to nearest even. When the difference between the default (21%) and unbreathable (16%) is 5, having the display be presented in steps of 2 is not very helpful.

As for valves, you already can glean their state if you stare at its sprite long enough, but that's very annoying, especially in a cluttered environment. There's no reason not to present this information in a more approachable way.

## Images of changes
![20220501-185608](https://user-images.githubusercontent.com/7831163/166160562-1c4c401b-ea38-4de1-915c-9d6c9a56de57.png)
![20220501-185713-dreamseeker](https://user-images.githubusercontent.com/7831163/166160563-b848237c-34e2-481e-972a-b313b94e14cc.png)

## Changelog
:cl:
tweak: Air alarm gets 0.1 precision to gas concentrations display
/:cl:

2022-05-01 19:09 UTC, AffectedArc07 commented
This PR has a valve and a pump attached to it

2022-05-03 03:25 UTC, dearmochi requested changes

2022-05-03 03:25 UTC, dearmochi commented on code/modules/atmospherics/machinery/components/binary_devices/valve.dm
> +	to_chat(user, "<span class='notice'>You [open?"open":"close"] [src]</span>")
```suggestion
	to_chat(user, "<span class='notice'>You [open ? "open" : "close"] [src].</span>")
```

2022-05-03 11:28 UTC, dearmochi approved these changes

2022-05-03 11:28 UTC, dearmochi commented
Fix TGUI conflicts then this can be merged

2022-05-03 16:19 UTC, AffectedArc07 approved these changes

2022-05-03 16:19 UTC, merged