Randomizes the reactive armor in the RD's office
ParadiseSS13/Paradise pull request #17888
Opened 2022-05-29 00:37 UTC by Qwertytoforty

## What Does This PR Do

Adds /obj/item/clothing/suit/armor/reactive/random, which spawns a random reactive armor in it's loc (AKA RD locker)

Replaces the teleport armor in the RD locker to a random reactive armor.

Changes the steal teleport armor objective to steal any reactive armor, which will include armor that is made **and** has a core installed. Scientists / robotics no longer get the armor as an objective, as people often dump the cores at science, not wanting them.

## Why It's Good For The Game

Quite a few people have been talking about the RD armor of late, complaining how it is always a get out of jail free card, especially on a vampire or captain on nukies, so it is now turned into something random, instead of the same teleport armor each shift.

Now instead of always having a teleporting armor that will never send you to a space tile (although it could send you to plating in space), you now only have a one in 5 chance to get the teleport armor, and instead have to work with (or just leave in your locker) some of the other reactive armor types, which have different risks/ benefits, and are generally less of a get out of jail free card. It also will encourage people to not always have the armor on, as tesla, repulse, and pyro armor is going to cause an issue if you are on the bridge and someone throws a donut at you.

## What about space law? Does this mean no one but the RD can wear the other armor types now?

I will point out with (most) high risk items, the head could give them out for certain reasons. Paramedic with the CMO defib. Someone working on the SM instead of the CE. No one arrests security officers with ablative armor, as they have _permission._ Someone can still wear these armors, if the RD gives them permission, who's access is needed for the frame of the armor anyway. As such, this won't change space law for these armors much, unless a security officer is given armor and someone steals it from them, then they could be brigged for grand theft.

## Changelog
:cl:
tweak: The RD starts with a random reactive armor in their locker.
tweak: The steal a reactive teleport armor objective is now for any reactive armor, and is no longer available to scientists and roboticists.
/:cl:

2022-05-29 00:43 UTC, Sirryan2002 commented on code/modules/clothing/suits/armor.dm
> +	var/list/types = list(/obj/item/clothing/suit/armor/reactive/teleport, /obj/item/clothing/suit/armor/reactive/fire, /obj/item/clothing/suit/armor/reactive/stealth, /obj/item/clothing/suit/armor/reac
I think this could just be
```var/list/types = subtypesof(/obj/item/clothing/suit/armor/reactive)```

2022-05-29 00:45 UTC, Qwertytoforty commented on code/modules/clothing/suits/armor.dm
> +	var/list/types = list(/obj/item/clothing/suit/armor/reactive/teleport, /obj/item/clothing/suit/armor/reactive/fire, /obj/item/clothing/suit/armor/reactive/stealth, /obj/item/clothing/suit/armor/reac
Yeah bubble suggested this, will do!

2022-05-29 02:50 UTC, matttheficus commented
Love variety and nuking the "give the Captain the armor" on Nukies.

2022-05-29 04:03 UTC, KittyNoodle commented
the problem is, pyro, and less so, tesla armor would be near useless to a non-antag RD as both cause direct harm to others.
the teleport armor is the only reactive armor that does not damage or effect those surrounding the wearer

2022-05-29 06:31 UTC, Carthusia commented
> the problem is, pyro, and less so, tesla armor would be near useless to a non-antag RD as both cause direct harm to others. the teleport armor is the only reactive armor that does not damage or effect those surrounding the wearer

One could argue thats all the more reason to not wear it unless its a situation that requires it, compared to the current standard of "Wear armor all the time, i literaly have no reason not to wear it, it will save me, so i should wear it forever"

2022-05-29 14:27 UTC, hal9000PR commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/reactive/random/New()
would you test if this works with `Initialize()` ?

2022-05-29 14:29 UTC, hal9000PR commented on code/modules/clothing/suits/armor.dm
> +	new A(loc)
you can do this a little cleaner without the `types` var. instead just do `var/spawn_path = pick(subtypesof(...))`

2022-05-30 18:17 UTC, AffectedArc07 requested changes
Please see outstanding review

2022-05-30 18:19 UTC, Sirryan2002 commented on code/modules/clothing/suits/armor.dm
> +	var/list/types = subtypesof(/obj/item/clothing/suit/armor/reactive)
```suggestion
	var/list/types = subtypesof(/obj/item/clothing/suit/armor/reactive) - /obj/item/clothing/suit/armor/reactive/random
```
one other nitpick, we need exclude the `/random` subtype from this list. It won't cause issues in the game b/c eventually the non-random subtype will roll but yeah.

2022-06-01 20:07 UTC, AffectedArc07 requested changes

2022-06-02 21:47 UTC, AffectedArc07 approved these changes

2022-06-02 21:47 UTC, merged