Move IPCs from being shown on medhud to diagnostic hud
ParadiseSS13/Paradise pull request #17897
Opened 2022-05-29 22:22 UTC by moxian

## What Does This PR Do
IPC healthbar is no longer shown when you have medhud on
IPC healthbar is now shown to you when you have diagnostic hud on

## Why It's Good For The Game
This was a requested change in discord.
I'll let the people in favour of this explain the reasoning in comments.

## Images of changes
![20220529-221514-dreamseeker](https://user-images.githubusercontent.com/7831163/170893516-93436fbd-15dd-47e7-b224-ccb3c69adbab.png)
![20220529-221521-dreamseeker](https://user-images.githubusercontent.com/7831163/170893517-110519aa-fc0c-4db2-a67d-609f5503b393.png)

## Changelog
:cl:
tweak: IPC health bar is now shown on diagnostic hud rather than medical
/:cl:

2022-05-29 22:28 UTC, AffectedArc07 requested changes
PR currently fails CI
```
[2022-05-29T22:24:48] Runtime in data_huds.dm,[174](https://github.com/ParadiseSS13/Paradise/runs/6646239290?check_suite_focus=true#step:9:175): Cannot modify null.icon_state.
  proc name: med hud set health (/mob/living/proc/med_hud_set_health)
  src: PBU-318 (/mob/living/carbon/brain)
  src.loc: the robotic brain (/obj/item/mmi/robotic_brain)
  call stack:
  PBU-318 (/mob/living/carbon/brain): med hud set health()
  PBU-318 (/mob/living/carbon/brain): prepare data huds()
  PBU-318 (/mob/living/carbon/brain): prepare huds()
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(PBU-318 (/mob/living/carbon/brain), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, 1)
  Atoms (/datum/controller/subsystem/atoms): Initialize(806881)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2022-05-29T22:24:48] Runtime in data_huds.dm,214: Cannot modify null.icon_state.
  proc name: med hud set status (/mob/living/carbon/med_hud_set_status)
  src: PBU-318 (/mob/living/carbon/brain)
  src.loc: the robotic brain (/obj/item/mmi/robotic_brain)
  call stack:
  PBU-318 (/mob/living/carbon/brain): med hud set status()
  PBU-318 (/mob/living/carbon/brain): prepare data huds()
  PBU-318 (/mob/living/carbon/brain): prepare huds()
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  PBU-318 (/mob/living/carbon/brain): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(PBU-318 (/mob/living/carbon/brain), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, 1)
  Atoms (/datum/controller/subsystem/atoms): Initialize(806881)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

2022-05-29 22:29 UTC, Sirryan2002 commented on code/game/data_huds.dm
> +	if(istype(dna?.species, /datum/species/machine))
```suggestion
	if(ismachineperson(dna?.species))
```
helper already exists for this
`#define ismachineperson(A) (is_species(A, /datum/species/machine))`

2022-05-29 22:29 UTC, Sirryan2002 commented on code/game/data_huds.dm
> +		else if(istype(dna.species, /datum/species/machine))
```suggestion
		else if(ismachineperson(dna.species))
```

2022-05-29 22:29 UTC, Sirryan2002 commented on code/game/data_huds.dm
> +	if(istype(dna?.species, /datum/species/machine) && health < 0)
```suggestion
	if(ismachineperson(dna?.species) && health < 0)
```

2022-05-29 22:29 UTC, Sirryan2002 commented on code/game/data_huds.dm
> +	if(istype(dna?.species, /datum/species/machine))
```suggestion
	if(ismachineperson(dna?.species))
```

2022-05-29 22:43 UTC, moxian commented
fails no more

2022-06-01 07:09 UTC, A-Medster commented
I requested this, this helps the game because it gives the ability to see an IPC's health to the people actually fixing them. A roboticist can see how close they are to a fully repaired IPC or just see that an IPC is damaged and need repairs. Taking them off of the med hud wasnt totally my idea but make sense given they cant repair IPCs any way.

2022-06-06 20:52 UTC, AffectedArc07 approved these changes

2022-06-06 20:52 UTC, merged