Robotic lungs can now be configured for vox and plasmamen
ParadiseSS13/Paradise pull request #17923
Opened 2022-06-06 17:25 UTC by Qwertytoforty

## What Does This PR Do

Allows cybernetic and upgraded cybernetic lungs to be configured to vox and plasmamen lung settings. The upgraded lungs will also give vox 20 oxygen as the max oxygen level, similar to the toxin and co2 bonus upgraded lungs already give, but it is **NOT** enough for them to safely breath station oxygen. It will however lower the toxin damage to 1 per cycle.

## Why It's Good For The Game

Being able to properly implant a species lungs into them when no organic replacements are available is good. Currently, nothing stops you from putting robotic lungs into a vox / plasmamen... which ends up being silly. Replacing someones lungs should not magically make them breath a different atmosphere. As such, this PR lets robotic and upgraded lungs be configured to plasmamen and vox settings with a multitool, so they still breath their gas after getting their lungs replaced.

## Changelog
:cl:
add: Cybernetic and upgraded cybernetic lungs can be configured with a multitool for vox or plasmamen settings.
/:cl:

2022-06-06 18:22 UTC, hal9000PR commented on code/modules/surgery/organs/lungs.dm
> +			user.show_message("You configure [src] to replace vox lungs.")
please add a span class for these. and, why are you using show_message instead of to_chat?

2022-06-07 16:20 UTC, procdrone commented
time for me to replace my lungs with vox cyber lungs, then have officers baited into manslaughter as they search me in sec and remove my voxxygen :star:

2022-06-08 14:41 UTC, AffectedArc07 requested changes

2022-06-08 14:41 UTC, AffectedArc07 commented on code/modules/surgery/organs/lungs.dm
> +		if("human")
```suggestion
		if("human") // from human to vox
```

2022-06-08 14:41 UTC, AffectedArc07 commented on code/modules/surgery/organs/lungs.dm
> +		if("plasmamen")
```suggestion
		if("plasmamen") // from plasmamen to human
```

2022-06-08 22:24 UTC, AffectedArc07 approved these changes

2022-06-08 22:25 UTC, merged