adds the falling emote
ParadiseSS13/Paradise pull request #17990
Opened 2022-06-17 09:12 UTC by Mooballoono

## What Does This PR Do
*fall makes you have the weaken effect for 4 seconds and say "falls." or if you are a mime it says "plays dead."

## Why It's Good For The Game
it adds some more roleplaying mechanics especially for the mime

## Changelog
:cl:
add: Added Fall emote
/:cl:

2022-06-17 13:24 UTC, AffectedArc07 requested changes

2022-06-17 13:24 UTC, AffectedArc07 commented on code/modules/mob/living/carbon/carbon_emote.dm
> +
```suggestion


```

This should fix
`file ./code/modules/mob/living/carbon/carbon_emote.dm is missing a trailing newline`

2022-06-17 22:25 UTC, lewcc commented
Happy to see new emotes emerging already!

I'd suggest making this a subtype of `/datum/emote/living/collapse`, or if not at least moving it to `living_emote.dm` as `/datum/emote/living/fall`.

2022-06-21 09:21 UTC, hal9000PR reviewed
Please address affected and luc's reviews within 3 days.

2022-06-24 09:42 UTC, closed without merging