Space ruins no longer have lava underneath them
ParadiseSS13/Paradise pull request #18047
Opened 2022-06-22 18:30 UTC by Contrabang

## What Does This PR Do
Changes the area of all space ruins to be part of /area/ruin/space. Adds a baseturf of space underneath to these areas. This should make it easier to add new space ruins.

## Why It's Good For The Game
Lava in space is not intended, fixes #16263

## Changelog
:cl: Contrabang
fix: Space ruins no longer have lava underneath floor tiles
/:cl:

2022-06-23 20:40 UTC, AffectedArc07 requested changes

2022-06-24 02:03 UTC, Contrabang commented on config/example/config.toml
> -	"_maps/map_files/RandomRuins/SpaceRuins/gasthelizards.dmm",
Reverted to previous state, will keep it in mind to touch the config

2022-06-24 04:30 UTC, SteelSlayer requested changes
It appears as though the syringe gun got re-added to the abandoned zoo:

![image](https://user-images.githubusercontent.com/42044220/175461434-3db7f1b6-e034-49fb-99b6-334d2ee01df5.png)

It also appears that the druglab got all of it's `/turf/template_noop` removed? Not really sure what these turfs do however.

![image](https://user-images.githubusercontent.com/42044220/175462368-4ce272c9-5d77-49c1-b5b9-cb63fd9b932b.png)

2022-06-24 05:22 UTC, Contrabang commented
This PR was made before the syringe gun PR was merged, I'll remove the syringe gun in the next commit/when merge conflict. Also, it seems like I accidently deleted /turf/template_noop on druglab, its basically just a turf that inherits whatever it spawns on from what I understand (basically an empty turf)

2022-06-24 07:05 UTC, SteelSlayer approved these changes

2022-06-24 09:50 UTC, AffectedArc07 approved these changes

2022-06-24 09:50 UTC, merged