New TEG sprites
ParadiseSS13/Paradise pull request #18085
Opened 2022-06-25 23:18 UTC by kugamo

## What Does This PR Do

Adds new sprites for the TEG. 

Also adds red indicator to TEG, akin to pumps.. showing direction setting it has.

## Why It's Good For The Game

I hate soul!

## Images of changes

Fully operational sprites.
![dreamseeker_EbAlWrYqhb](https://user-images.githubusercontent.com/16618648/175793151-34c5c2b5-7b78-4850-8eb8-c1fcbe15feb6.gif)

Heres most of the new sprites. (most are animated)
![image](https://user-images.githubusercontent.com/16618648/175793248-137700af-a145-44dc-944f-685401792fdc.png)

## Changelog
:cl:
imageadd: Added new sprites for TEG.
/:cl:

2022-06-25 23:27 UTC, moxian commented
This is wonderful!

However, may i complain a bit about the lights at the top part of it? The OP has them blinking between green and yellow, which are very similar colors, especially on the white background, which makes them hard to read. I've been looking at it for a minute straight, and i'm still not sure if they are blinking in a specific "direction", or independently, or even whether the lower of the two lights blinks at all. 
May i ask them to have the colors be more distinct (higher contrast I think it's called?)? Or maybe have them blink less rapidly? Or both?..

2022-06-28 20:06 UTC, hal9000PR requested changes
instead of doing `overlays += thing` please do `add_overlay(thing)`

2022-07-02 14:43 UTC, SteelSlayer requested changes
Also, can you remove the duplicate  proc for `/obj/machinery/power/generator/power_change()` at the bottom of `code\modules\power\generator.dm`?

2022-07-02 14:43 UTC, SteelSlayer commented on code/modules/power/generator.dm
> +	..()
```suggestion
	. = ..()
```

2022-07-02 14:43 UTC, SteelSlayer commented on code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
> +	if((stat & (BROKEN|NOPOWER)))
```suggestion
	if(stat & (BROKEN|NOPOWER))
```

2022-07-02 17:35 UTC, hal9000PR approved these changes
LGTM

2022-07-02 17:37 UTC, SteelSlayer approved these changes

2022-07-02 17:45 UTC, merged