Nerfs telekinesis
ParadiseSS13/Paradise pull request #18177
Opened 2022-07-01 23:29 UTC by GDNgit

## What Does This PR Do
Nerfs the cooldown of the TK genetic ability from .3 seconds to 3 seconds (the I fixed my branch edition) 

## Why It's Good For The Game
TK already does a lot; it lets you use items from range such as a flash and allows you to interact with some objects from a distance. However, TK is mostly used for its power in combat as you can very quickly destroy structures/kill mobs due to its extremely low cooldown. Its cooldown is being raised to 3 seconds from .3 seconds so that it still has the ability to move items for purpose of utility, but it's less powerful for combat related shenanigans.

## Images of changes

https://user-images.githubusercontent.com/96800819/176977420-91eb2a61-e44d-4da5-98ef-7e550cc47ebd.mp4

## Changelog
:cl:
balance: Nerfs the use time of TK from .3 seconds to 3 seconds
/:cl:

2022-07-02 04:16 UTC, Mitchs98 commented
100% in favor of nerfing telekinesis. It's one of the most game-breakingly OP things that is possible to do at the moment. You can essentially kill or severely maim anything you want ever with it with relative ease. It's been nerfed considerably with the removal of x-ray vision being a common thing, but overall it still remains problematic. Particularly against blobs that have a very hard time countering it.

It _desperately_ needs the cooldown.

2022-07-02 05:36 UTC, datlo commented
Yes. 

I hate to see genetics neutered even further but if you use TK optimally you will legit just get bwoinked for powergaming.

Needed change.

2022-07-02 10:09 UTC, Bm0n commented
I think nerfing TKs use speed from 0.3 to 3 seconds is far too extreme and makes the power nearly useless for what it is.

This is not helped by the fact that we have one of the most complex and RNGie genetics system out of any server and TKs instability cost is still 15

2022-07-02 10:56 UTC, hal9000PR requested changes

2022-07-02 10:56 UTC, hal9000PR commented on code/_onclick/telekinesis.dm
> +	if(last_throw + 3 SECONDS > world.time)
make this a define at the top of the file, and undef it at the bottom of the file.

2022-07-02 10:56 UTC, hal9000PR commented on code/_onclick/telekinesis.dm
>  /obj/item/tk_grab/afterattack(atom/target , mob/living/user, proximity, params)//TODO: go over this
```suggestion
/obj/item/tk_grab/afterattack(atom/target , mob/living/user, proximity, params)
```
if it hasn't been todone yet, it won't be

2022-07-02 12:48 UTC, roarbark commented
currently whenever telekinesis is in the mix it makes fights really fucking unfun. this isnt helped by the free TK you get in one of the gateways... i dont mind if this makes it hard to use as your main weapon, its a good change.

2022-07-02 14:21 UTC, moxian commented
Echoing what others have said here and on discord: 3 seconds is way too extreme.
1-1.5 seconds is a better number, and we can make another pass and nerf it further if that is still deemed to be problematic.

2022-07-02 16:49 UTC, GDNgit commented
CD will be lowered to 1.5 second, requesting a TM on this to see if that's too high (unless the queue is already too large, then don't TM it)

2022-07-02 16:53 UTC, TORE01 commented
I have done a lot of genetics and TK is busted to the point where I refuse to use it. 15 instability cost is barely a downside for an ability that allows you to do incredible amounts of brute damage in seconds. However 3 seconds is a little too long and makes it nearly useless for combat. I will however not thumb this down because the nerf is needed and I like the idea of it becoming more useful for utility. 
If you want it to be more useful for utility I think the range for interacting with consoles and machinery should be higher. Right now it is very short, and I do understand that because a lot of people use it to grief (writing announcement on the communication console etc).
You can also lower the cost of it to 5-10 instability.

2022-07-03 11:36 UTC, hal9000PR approved these changes

2022-07-03 12:25 UTC, AffectedArc07 commented
Im ok with this

2022-07-03 12:25 UTC, merged