Moves ED209 / security bots to stamina batons
ParadiseSS13/Paradise pull request #18232
Opened 2022-07-06 18:53 UTC by Qwertytoforty

## What Does This PR Do

Security bots / ED209's now deal 60 stamina and later cause crawling like batons in the baton TM.
They have a cooldown of 3.5 seconds between batons.
Now check stamina vs weaken.

## Why It's Good For The Game

If batons no longer instantly stun, sec bots should not either. Behaving the same way as current stunbatons makes sense.

## Changelog
:cl:
tweak: Secbots / ed209 batons deal 60 stamina and force crawling after 2.5 seconds, and have a 3.5 second cooldown between stuns.
/:cl:

2022-07-06 19:06 UTC, Coolrune206 commented
With this change, would someone be able to attack Beepsky with a conventional weapon (I.E. welder/toolbox) and kill it before the stamina crit kicks in?

2022-07-06 20:14 UTC, Qwertytoforty commented
> With this change, would someone be able to attack Beepsky with a conventional weapon (I.E. welder/toolbox) and kill it before the stamina crit kicks in?

At the moment, you can kill beepsky with a welder. Will ask around for ideas on how to make this not happen.

2022-07-06 20:46 UTC, Qwertytoforty commented
Bots now have increased health to make up for stamina batons, as well as secbots no longer have projectiles fly over them.

2022-07-07 10:56 UTC, hal9000PR commented
> Bots now have increased health to make up for stamina batons, as well as secbots no longer have projectiles fly over them.

add this to the changelog please

2022-07-15 13:46 UTC, hal9000PR requested changes

2022-07-15 13:46 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	environment_smash = ENVIRONMENT_SMASH_WALLS //Walls can't stop THE LAW //someone fix this please this is funny
make an issue report.

2022-07-15 13:46 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	addtimer(CALLBACK(src, .proc/reset_baton_cooldown), BATON_COOLDOWN)
you can make use of `VARSET_CALLBACK` here, so that you don't need a basically empty proc.

2022-07-15 13:46 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	addtimer(CALLBACK(src, .proc/reset_baton_cooldown), BATON_COOLDOWN)
VARSET_CALLBACK

2022-07-17 10:58 UTC, hal9000PR approved these changes

2022-07-17 14:32 UTC, merged