Pizza Overhaul 2022
ParadiseSS13/Paradise pull request #18278
Opened 2022-07-08 18:54 UTC by PacifistDalek

## What Does This PR Do
- ports pizza, pizza box, and pizza bomb sprites from TG (with a bunch of tweaks by yours truly)
- gives pizza bombs an active sprite (animated flashing lights to make it even more intense!)
- changes how pizzas are made, before you threw the components in the oven and that made a pizza. You now use the crafting menu to create a raw pizza, and you place that in the oven to make a cooked pizza. Raw pizzas are still edible if you don't have an oven, but give half nutrients and aren't sliceable.
- tweaks some recipies to make more sense either for their sprites or for how they're made in real life
- removes the syntipizza recipie which just duplicated the meat pizza and didn't even give it the name syntipizza
- adds **NEW PIZZAS**: Cheese, Pepperoni, Donk-Pocket, Dank, Garlic, Firecracker, and "Pesto". (I didn't think it was worth adding two new growables and everything that came with it just to create tg's realistic pesto pizza recipe, so instead I went with comedy and created a wasabi pizza, thus giving wasabi an extra food use as well)

## Why It's Good For The Game
![pizza-time](https://user-images.githubusercontent.com/32213277/178052572-8ed54638-6c6a-4e00-ab43-a9ebdfe55813.gif)

## Images of changes
![pizza1](https://user-images.githubusercontent.com/32213277/178052601-38b62ec4-dcf5-4345-a00d-61aa1784df96.PNG)
![image](https://user-images.githubusercontent.com/32213277/178053129-d6ae35e7-a1ce-4c4d-b9a4-25b04809e20f.png)
![pizza2](https://user-images.githubusercontent.com/32213277/178052614-8cba28dd-fc0d-41c4-8d3a-b14402408b0f.png)

## Changelog
:cl:
add: Seven new pizzas!
tweak: pizzas are now made using the crafting menu, then baking the resulting raw pizza
imageadd: New pizza, pizza box, and pizza bomb sprites

/:cl:

2022-07-08 18:56 UTC, Adrer commented
Okay, but real talk, donk-pockets are pizza turnovers, how do you make a pizza turnover pizza.

2022-07-08 19:06 UTC, Sirryan2002 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_table.dm
> +	subcategory = CAT_PIZZA
```suggestion
	subcategory = CAT_PIZZA

```
new line

2022-07-08 19:06 UTC, Sirryan2002 commented on code/modules/food_and_drinks/recipes/recipes_oven.dm
> +	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/garlicpizza
```suggestion
/datum/recipe/oven/cheesepizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/cheesepizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/cheesepizza

/datum/recipe/oven/pepperonipizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/pepperonipizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/pepperonipizza

/datum/recipe/oven/donkpocketpizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/donkpocketpizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/donkpocketpizza

/datum/recipe/oven/dankpizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/dankpizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/dankpizza

/datum/recipe/oven/firecrackerpizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/firecrackerpizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/firecrackerpizza

/datum/recipe/oven/pestopizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/pestopizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/pestopizza

/datum/recipe/oven/garlicpizza
	items = list(/obj/item/reagent_containers/food/snacks/rawpizza/garlicpizza)
	result = /obj/item/reagent_containers/food/snacks/sliceable/pizza/garlicpizza
```

2022-07-08 19:06 UTC, Sirryan2002 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_table.dm
> +	subcategory = CAT_PIZZA
oh I think you fixed this aleady

2022-07-08 19:35 UTC, Sirryan2002 commented
Also you're failing CL because you changed some pizza type paths but didn't edit the maps they were in

2022-07-08 19:55 UTC, KalevTait commented
While you are in pizza_bomb, do you want to change `timer = (input(user, "Set a timer, from one second to ten seconds.", "Timer", "[timer]") as num) * 10` to `timer = (input(user, "Set a timer, from one second to ten seconds.", "Timer", "[timer]") as num) SECONDS`?

2022-07-09 04:40 UTC, Bm0n commented
Why didn't you port TGs new pizza box inhands? A little weird that you'd port the new box sprite but not is inhands

2022-07-09 19:16 UTC, PacifistDalek commented
A whoops, the map issue and the in-hands were my bad.

@KalevTait will do!

Thanks @Sirryan2002 for the suggested changes and for catching what was failing CL

AND I've been informed in discord that crafting menu recipes don't carry forward the reagents from their ingredients the way they should, so I should possibly switch back to just throwing ingredients in the oven to make the pizzas.

2022-07-09 20:06 UTC, PacifistDalek commented
Made it a draft because i have to figure out what to do with the new pizza cooking method.

2022-07-09 20:47 UTC, Bm0n commented
you probably should have updated your branch before adding the new inhands, now a bunch of new weapon inhands from #18118 have been deleted

2022-07-24 21:45 UTC, PacifistDalek commented
Yes, I have merge conflicts to fix, but i've re-opened it from draft state because beyond that I think it should be ready to go.

2022-07-29 23:57 UTC, Sirryan2002 approved these changes
code looks good

2022-07-29 23:57 UTC, Sirryan2002 approved these changes

2022-07-30 10:40 UTC, AffectedArc07 requested changes

2022-07-30 10:40 UTC, AffectedArc07 commented on code/modules/food_and_drinks/food/foods/pizza.dm
>  	return ..()
Initialize has the parent call first, not last.

Please convert
```dm
/obj/item/pizzabox/margherita/Initialize(mapload)
	pizza = new /obj/item/reagent_containers/food/snacks/sliceable/pizza/margheritapizza(src)
	box_tag = "margherita deluxe"
	return ..()
```

to
```dm
/obj/item/pizzabox/margherita/Initialize(mapload)
	. = ..()
	pizza = new /obj/item/reagent_containers/food/snacks/sliceable/pizza/margheritapizza(src)
	box_tag = "margherita deluxe"
```

And do the same for the others.

2022-07-31 21:57 UTC, SteelSlayer approved these changes

2022-07-31 21:57 UTC, hal9000PR approved these changes

2022-07-31 22:23 UTC, merged