Code Readability - Game (misc)
ParadiseSS13/Paradise pull request #18280
Opened 2022-07-08 19:48 UTC by KalevTait

## What Does This PR Do
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable.
* Converts some stat_allowed = 0 to stat_allowed = CONSCIOUS
* Where bools are in if statements, uses them as bools

## Why It's Good For The Game
More readable code is easier to work with.

2022-07-08 19:54 UTC, Sirryan2002 commented on code/game/mecha/equipment/weapons/weapons.dm
>  				return 0
```suggestion
				return
```

2022-07-08 19:54 UTC, Sirryan2002 commented on code/game/mecha/equipment/weapons/weapons.dm
>  			return 1
```suggestion
			return TRUE
```

2022-07-08 19:54 UTC, Sirryan2002 commented on code/game/mecha/equipment/weapons/weapons.dm
>  			return 1
```suggestion
			return TRUE
```

2022-07-08 19:54 UTC, Sirryan2002 commented on code/game/mecha/equipment/weapons/weapons.dm
>  	return 0
```suggestion
	return
```

2022-07-08 20:39 UTC, KalevTait commented on code/game/mecha/equipment/weapons/weapons.dm
>  				return 0
Done, plus a bit more....

2022-07-09 10:20 UTC, hal9000PR requested changes

2022-07-09 10:20 UTC, hal9000PR commented on code/game/mecha/equipment/tools/other_tools.dm
> +			return
dangling return, (a return value at the end of a proc that returns nothing) is unneeded.

2022-07-09 10:20 UTC, hal9000PR commented on code/game/mecha/equipment/tools/other_tools.dm
> +
`#undef` these at the end of the file.

2022-07-09 10:20 UTC, hal9000PR commented on code/game/mecha/equipment/tools/work_tools.dm
> +
undef these

2022-07-09 10:20 UTC, hal9000PR commented on code/game/mecha/equipment/tools/work_tools.dm
>  					O.loc = chassis
```suggestion
					O.forceMove(chassis)
```

2022-07-09 10:20 UTC, hal9000PR commented on code/game/mecha/mecha_construction_paths.dm
>  	return
lots of dangling returns in this file. please remove.

2022-07-10 12:41 UTC, hal9000PR approved these changes

2022-07-10 13:01 UTC, merged