Add new Slime & Vulpkanin names
ParadiseSS13/Paradise pull request #18396
Opened 2022-07-15 21:12 UTC by ParaGitV

## What Does This PR Do

Changes Slime and Vulpkanin character name generation lists. Previously names were generated using speech verbs which resulted in a lot of similar and unpronounceable names. This adds new Slime/Vulpkanin male/female & last name lists.

## Why It's Good For The Game

Gives randomized character names a wider variety of themed options for their race/gender to hopefully make Slime/Vulp names more memorable than current Slime/Vulp randomized names.

Some examples of our current randomized names below for comparison:
Genagbaram Llbarammaktek
Vuhrurzwichsischt Woortchjarl
Entchauchschzein Cresthzlllnictzch
Zwichswatzchrawr Tchonnghzthvuh
Plopplopboop Popbopboop
Plopplopplop Plopplop
Plopblobblobpop Plopblobploppop
Booppoppopboop Boopboopplopplop

## Images of changes

![image](https://user-images.githubusercontent.com/109384402/179309399-ad251265-712c-430d-895a-08b55e5caa72.png)

![image](https://user-images.githubusercontent.com/109384402/179309466-f955bea3-d822-4446-b52e-61fcab66e033.png)

## Changelog
:cl:
tweak: Change from syllable-generation to custom lists
/:cl:

2022-07-15 21:55 UTC, atteria commented
I'm sorry, but these are really, really silly.

Just giving Vulps human names erases one of the interesting things they have, which is their language sound. 
>  They tend to sound harsh and guttural, and many a scholar has compared them to the names found in ancient Germanic and Semitic languages. 

And 'Fizzete'? 'Slimeton'? Really? If I saw someone name a character these in-game I would groan.

2022-07-15 22:14 UTC, roarbark commented
i like the idea but randomized names for vulpkanin shouldn't be just human names, it takes a lot of flavour out of the race to have vulpkanin predominantly run around with, well just human names.

2022-07-16 00:15 UTC, Inadvizable commented
The slime names are meant to be non-pronounceable. Most slimes adapt a name specifically for interacting with other humanoids - and several slime players have canon 'real' names which are those 'popping sound' names.

2022-07-16 06:27 UTC, Necaladun commented
People overwhelmingly use these kinds of names anyway, few quick tests showed over 90% of people do at least.

👍

2022-07-16 10:10 UTC, AffectedArc07 requested changes

2022-07-16 10:10 UTC, AffectedArc07 commented on code/modules/mob/language.dm
> +        new_name = "[pick(list("Abby","Acantha","Addilyn","Adela","Adele","Aderyn","Adley","Adriana","Aerona","Aileen","Alanis","Alberta","Alex","Alexandra","Alice","Alma","Amalie","Andromeda","Angel
Yeah these are gonna need to be a config.

Take a look at how other names do it with `code\_globalvars\lists\names.dm`

2022-07-18 00:55 UTC, Pixelzilla commented
> I'm sorry, but these are really, really silly.
> 
> Just giving Vulps human names erases one of the interesting things they have, which is their language sound.
> 

I can assure you that the current Vulp name generation was not the originally intended naming scheme and was a result of not having a name list in place which basically means it defaults to using the syllables from the Vulp language. Vulp were originally supposed to be a much more open race with a lot of creative freedom for players to do things they wanted instead of trying to shove them all into a very limited box. The current naming/lore is much more restrictive and doesn't allow for as much freedom as the majority of Vulp players clearly want.

Vulp names still have some german-ish options for those who want that but they also have a lot of star/galactic themed names which has always been part of Vulp. If you look at their original hairstyle names they are all galactic/star/constellation themed names. There are also some silly names (just like how humans have silly names like "Butterfill" in their name list). Obviously no one is obligated to change an existing character name or match the new randomized name theme, this is just for people who _wish_ to utilize it when making _new_ characters. It also does not change anything about what their spoken language sounds like.

> The slime names are meant to be non-pronounceable. Most Slimes adapt a name specifically for interacting with other humanoids - and several slime players have canon 'real' names which are those 'popping sound' names.

I am 99% sure that the original slime name generator was not what it currently is. A lot of races that lacked name list/config files defaulted to using their species language syllables. I'm pretty sure this was an unintentional side effect of some other changes and no one really bothered fixing any of the species negatively impacted by it except for Vox and Kidan. If we're gonna argue lore then the current name generation doesn't even fit the naming lore listed on the wiki. Only one of the options listed (pop) is even part of the name generation options and it specifically says most of the names are chosen in galactic common and include variations of certain phrases not that they exclusively use only those words. It even suggests that these alternate names are chosen for **sake of simplicity**. I don't think one can really argue that a name like "Booppoppopboop Boopboopplopplop" is even remotely simple.

2022-07-23 15:59 UTC, farie82 reviewed
Minor style stuff. You don't have to define a var to be something if you instantly define it afterwards in all cases.

2022-07-23 15:59 UTC, farie82 commented on code/modules/mob/language.dm
> +	var/new_name = ""
```suggestion
	var/new_name
```

2022-07-23 15:59 UTC, farie82 commented on code/modules/mob/language.dm
> +	var/new_name = ""
```suggestion
	var/new_name
```

2022-07-23 16:07 UTC, farie82 requested changes

2022-07-23 16:07 UTC, farie82 commented on config/names/first_female_slime.txt
> +Bloppella
This file has an empty line at the end. While this is normally what we want in DM files, this ain't what we want in config files like this. Here it'll cause DM to see an empty line and parse it as such. So there is a chance that an empty name will be picked for each of these files

2022-07-24 13:30 UTC, farie82 approved these changes

2022-07-24 13:44 UTC, merged