Clean up rechargers and add wall recharger panel sprite
ParadiseSS13/Paradise pull request #18474
Opened 2022-07-20 15:10 UTC by Vi3trice

## What Does This PR Do
Cleans up the code for rechargers and make it more consistent in the process. They'd also constantly update the icon even when the panel was open when processing.

## Why It's Good For The Game
Fixes #18470.

## Images of changes
![Charger_Panel](https://user-images.githubusercontent.com/80771500/180012146-354daf93-ccde-4fba-b932-17ac348311d2.PNG)
![Recharger_Loaded](https://user-images.githubusercontent.com/80771500/180012179-89c6dec1-700c-4a8a-bff4-33d95fd866cf.PNG)

## Changelog
:cl:
tweak: Added feedback for trying in insert an already loaded recharger
fix: Rechargers properly show an open panel when using a screwdriver
imageadd: Wall recharger open panel sprite
/:cl:

2022-07-20 15:25 UTC, AffectedArc07 submitted a review, later dismissed
Very minor nitpicks

2022-07-20 15:25 UTC, AffectedArc07 commented on code/game/machinery/recharger.dm
> +	var/area/a = get_area(src)
```suggestion
	var/area/A = get_area(src)
```

2022-07-20 15:25 UTC, AffectedArc07 commented on code/game/machinery/recharger.dm
> +	if(!isarea(a) || !a.power_equip)
```suggestion
	if(!istype(A) || !A.power_equip)
```
You already casted it to an area in the above

2022-07-20 15:25 UTC, AffectedArc07 commented on code/game/machinery/recharger.dm
> +	G.forceMove(src)
```suggestion
		return

	G.forceMove(src)
```
Readability

2022-07-20 15:25 UTC, AffectedArc07 commented on code/game/machinery/recharger.dm
> +	update_icon()
```suggestion
	if(charging)
		to_chat(user, "<span class='warning'>Remove the charging item first!</span>")
		return

	if(!I.use_tool(src, user, 0, volume = I.tool_volume))
		return

	panel_open = !panel_open
	if(panel_open)
		SCREWDRIVER_OPEN_PANEL_MESSAGE
	else
		SCREWDRIVER_CLOSE_PANEL_MESSAGE
	
	update_icon()
```
More readability

2022-07-20 20:49 UTC, Bm0n commented
I think you removed the anchored check on the screwdriver act meaning you can now get unanchored machine frames and half built things. not normally something you can do on paradise

2022-07-24 18:35 UTC, farie82 requested changes

2022-07-24 18:35 UTC, farie82 commented on code/game/machinery/recharger.dm
> +		to_chat(user, "<span class='notice'>[src] blinks red as you try to insert [G].</span>")
```suggestion
		to_chat(user, "<span class='warning'>[src] blinks red as you try to insert [G].</span>")
```

2022-07-24 18:35 UTC, farie82 commented on code/game/machinery/recharger.dm
> +	. = TRUE
Prob best to set this after the `allowed` check

2022-07-24 18:35 UTC, farie82 commented on code/game/machinery/recharger.dm
> -					return TRUE
You removed this check

2022-07-25 06:27 UTC, farie82 approved these changes

2022-07-25 06:28 UTC, merged