Removes the majority of brute/burn mods from species, replaces them with interesting downsides.
ParadiseSS13/Paradise pull request #18501
Opened 2022-07-21 23:16 UTC by hal9000PR

## What Does This PR Do
the only ones that remain are drask, and plasmamen

IPCS:
brute/burn mods gone
Shocks now cause brain damage and give you nutrition.
no longer immune to rads, rads cause brain damage and hallucinations.

Vox:
Brute mod replaced with oxyloss mod, they will die double as fast in crit.

Diona:
no more burn mod
they no longer heal burn damage
they take more damage from overheating

Drask:
burn mod from 2 to 1.5
heat mod from 2 to 3

Unathi:
Brute mod gone, it was a joke anyway

Grey:
brute mod gone
you require full syringe proof clothing (helm + exosuit slot) to protect from water now

Plasmamen:
still have a burn mod, I cannot think of a good idea for them. open to suggestions.

## Why It's Good For The Game
Brute/burn mods are an awful way to balance a species. they feel super backhanded and quite frankly, insulting to the people who play these races. they aren't fun and they don't offer any extra flavour to the species outside of the extreme case of drask. this is why I opted to keep the drask burn mod.

## Changelog
:cl:
tweak: removed the majority of species brute/burn mods, replaced them with different downsides. check the PR for more details.
/:cl:

2022-07-21 23:37 UTC, Qwertytoforty commented
Not sold on o2 damage for vox yet, due to yes, dying twice as fast in crit, which medical can *probably* handle, but mainly blood loss taking place at 15% earlier. Larger malus when combined with the crit combination. Any o2 multiplier greater that ~1.25 will cause this (although at a slower speed) Otherwise, great changes.

2022-07-22 00:30 UTC, Inadvizable commented
> Not sold on o2 damage for vox yet, due to yes, dying twice as fast in crit, which medical can _probably_ handle, but mainly blood loss taking place at 15% earlier. Larger malus when combined with the crit combination. Any o2 multiplier greater that ~1.25 will cause this (although at a slower speed) Otherwise, great changes.

As a counterpoint, salbutamol is one of the most ubiquitous chemicals on the station, found randomly in blue medkits inside O2 lockers scattered all over the place. It can be counteracted rather easily.

2022-07-22 01:17 UTC, LightFire53 commented
![image](https://user-images.githubusercontent.com/16112919/180340985-9d516e47-4ff6-4dee-ba04-448f2a995a2c.png)

2022-07-22 02:25 UTC, Qwertytoforty commented
> > Not sold on o2 damage for vox yet, due to yes, dying twice as fast in crit, which medical can _probably_ handle, but mainly blood loss taking place at 15% earlier. Larger malus when combined with the crit combination. Any o2 multiplier greater that ~1.25 will cause this (although at a slower speed) Otherwise, great changes.
> 
> As a counterpoint, salbutamol is one of the most ubiquitous chemicals on the station, found randomly in blue medkits inside O2 lockers scattered all over the place. It can be counteracted rather easily.

I don't think encouraging people to get salbutamol ahead of time is a good idea personally.

2022-07-22 03:08 UTC, Contrabang commented
I don't mean to to be mean or overly critical, but I don't think the IPC changes or Drask changes fit very well.

As someone who plays IPC engineering a lot --basically where the shocks and rads changes would affect the most -- I am slightly concerned about the IPC changes, especially after testing. Heres an image of an IPC mutating, their "hair" falling out in clumps, and gasping for air, because radiation can do that for some reason now that they're not immune.
![image](https://user-images.githubusercontent.com/91113370/180348437-66911dba-7565-4706-878e-6a34b5fb1391.png)
![image](https://user-images.githubusercontent.com/91113370/180348517-7627ca4c-c93b-4a39-abf5-f7cc07842924.png)
![image](https://user-images.githubusercontent.com/91113370/180348687-ca8b9337-217f-4784-9acc-8d77d5f4dd63.png)
(Ignore the name, I was roundstart IPC but I didnt care enough to change away from a non-human name in game prefs)

Also, getting shocked several times, something that you can usually heal with cable coil but will leave you with brain damage. Upon hitting 100 brain damage you'll be stuck on the floor and unable to move but conscious and able to talk, normally you would pass out at this point if you weren't an IPC. At 120 brain damage damage, whether from rads or some kind of horrific shock you will die, despite usually being conscious.
![image](https://user-images.githubusercontent.com/91113370/180349435-5b936279-7a4d-458a-b4ff-05c3baabccb0.png)


At the start of the round power levels, this takes about 4 shocks from a door to reach 100 brain damage. It takes about 10 minutes for an IPC to get to 100 brain damage in front of a default N2 set up and about 12 minutes to die. I think this is a fine amount of time but there's no easy way to gauge how much brain damage you have as an IPC, the only way being a robotic analyzer which you can't print in an autolathe like a health analyzer. You would need to specifically bother robotics or science for one, just to be able to tell if you have brain damage.

I think moving away from 150% damage is good for IPCs, but I don't think brain damage is the solution. I also encountered a weird bug with ahealing and IPC brain damage but I was not able to reproduce it later.

I'm also concerned with the Drask change to heat, especially with the Spanish flu since the only visible symptoms show up when on the last stage, where they are already dying. Doing some testing, it takes about 90 seconds to reach stage 3 (the last stage) and about 10-20 seconds to deal 100 damage and 30-80 seconds to kill them with 300 or so burn damage. Spanish flu gives you about 73C temperature, which is extremely lethal to drasks. Compared to humans, where they can comfortably sit at 74C and only take 5 burn damage from the occasional "You're burning in your own skin!" which only deals 5 damage, taking about 10 minutes from infection to deal 65 damage. Drasks do not even have the time to see the "You're burning in your own skin!" from the virus because they are already unconscious or dead by the time it activates.
![image](https://user-images.githubusercontent.com/91113370/180352498-4a49f277-e1aa-4689-ae96-7dcd2b96c7ef.png)
(screenshot of the longest timed test with laps for stage 3 activation, 100 damage, and death.)

2022-07-22 11:30 UTC, hal9000PR commented
@Contrabang 
the rad stuff has been completely re-written. values, everything.

being in brain damage state now causes a bunch of error messages to get set to you, and you incur more brain damage, so you arent perma stunned, you get the sweet release of death eventually.

(ignore the name)
![image](https://user-images.githubusercontent.com/69320440/180430159-5570e49c-0264-4c38-aafc-b8b9c8cbc6e7.png)

As for shocks, just dont shock yourself 3-4 times? its like a slime person complaining that walking into space kills them? just dont do it? I can get getting shocked once, maybe even twice.

2022-07-22 11:44 UTC, alex-gh commented on code/modules/mob/living/carbon/human/species/machine.dm
> +		var/list/error_messages = list("Error 196: motor functions failing.",
Here are some more messages for variety:

Error while displaying the error message.
Error 6344: Cannot delete file ~/²tmp⅛³³sy%³²¼ - No space left on device

2022-07-22 11:47 UTC, Miraviel commented
All I ask for is to please get rid of the burn mod of drasks and plasmamen. I would rather we do not have any straight up damage multipliers - we are not a TDM server like CM, but we _are_ big on PvP. Someone shouldn't go horizontal a few shots too early just because they are spooky plasma skeletons rather than spooky jelly skeletons. Some races being factually much worse in antag/security positions is very discouraging, I think - I know some people enjoy that, but they are a minority.

Heat mods are fine because it is rarely weaponized, I am only concerned about projectiles.

As for what else drasks could have racially, some ideas:
- The spikes on their arms are sensory organs as well. Consider making them an actual organ or factor into how they see or hear. You can do this as a buff or as a nerf, depending on how you want to approach it.
- Their heart is literally next to their brain in their skull. This can be both a positive or a negative thing, depending on what kind of feature you are looking for. Positive: they could get less brain damage from bad oxygenation, for example, because whatever little blood their heart is pumping, it first always goes through their brain. Negative: since their heart is so close to their ear, they could get a temporary deafness when their pulse is skyrocketing (or when their blood is too low, whichever is easier to track).
- Lore-wise, their metabolism is based on the temperature they are in. Be careful with this one, as it can be powergamed.

2022-07-22 15:30 UTC, Inadvizable commented
> I don't think encouraging people to get salbutamol ahead of time is a good idea personally.

They don't have to grab it ahead of time, it's everywhere. Bleeding? Grab a salb pill from an O2 emergency locker (you are having such an emergency) and head to medical.

2022-07-22 15:36 UTC, Coolrune206 commented
But how am I supposed to collapse at a gentle breeze as an IPC now?

2022-07-22 20:21 UTC, A-Medster commented
its going to be a little odd not collapsing to a gentle breeze and not being immune to rads, but the change is not unwelcome. if anything, the shock damage should also damage the micro-battery a little due to being over charged or something along those lines.

2022-07-23 11:26 UTC, Spacemanspark commented
What in the fu-

2022-07-23 22:36 UTC, Asmerath commented
I actually like the look of this PR, Buffs to IPC are strange and always will be to me. The other alterations seem to be interesting to handle. As with any changes I'll always be skeptical of them at first, being a vox that doesn't get crushed as easily will be a change for sure. I also like the oxyloss thing a lot as it really brings in that idea of heavy nitrogen dependancy or else. The unique thing with drask and grey there is also super interesting to see, though poor greys I'm not sure what they do now to protect themselves from the fire extinguisher wheelchair people.

2022-07-23 22:37 UTC, Bm0n commented
for plasmamen I would just remove the 50% burn mod, the helmet welding shield and the plasma dust healing thing. for their downsides, keep everything the same but make plasma dust their blood.

radiation immunity isn't that useful on paradise due to murderbone rules + radiation just sucking on para, really this is only for that one rad storm event or if you're an SM goober

plasmamen already cant hide their identity or wear headgear items so I think that's enough downsides for radiation immunity... at least they'd be more balanced than vulp/taj with free night vision for an easily negatable downside lmao

2022-07-24 05:28 UTC, TORE01 commented
Hey. I dont really have an opinion on most of the changes because I just play human but I do think robotics should have access to some liquid solder. It's nice that it will finally have some use 👍

2022-07-24 10:43 UTC, roarbark commented
ipc's neither suffer from bone breaks nor IBs. this is pretty strong now without the damage mod, compared to having their healing be centralized into two small items that are more widely available than automenders.

2022-07-24 22:57 UTC, hal9000PR commented
> ipc's neither suffer from bone breaks nor IBs

but they do. just in a different form. over a certain damage threshold the limb is practically broken, however they can just be repaired.

and, they arent going to become this super powerful tank, they have old crit and get 2 tapped by ions.

2022-07-26 01:39 UTC, KittyNoodle commented
make drask take organ damage from being on fire and make them have double firestacks or something instead of a damage mod

2022-07-27 18:37 UTC, Inadvizable commented
> ipc's neither suffer from bone breaks nor IBs. this is pretty strong now without the damage mod, compared to having their healing be centralized into two small items that are more widely available than automenders.

And then they catch three stechkin shots on top of chip damage and go to forever sleep.

2022-07-27 20:49 UTC, AffectedArc07 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +								"Errror 0: Operation completed successfully.",
Is this intentional

2022-07-27 22:25 UTC, rythenx commented
I like a lot of these changes.  Seems like a pretty big buff to IPCs overall though considering they have one of the longer lists of boons and positive mechanics in general.  Not necessarily a bad thing but just sort of surprised to see since I've often heard comments saying they don't need a buff.  This change would make me want to play my IPC more often though for sure since the main reason I don't play it is that I'm so unrobust that I can't handle dying any quicker!

Feels a bit strange that burn mod would be left for Drask and Plasmaman though.  I sort of think if the raw damage mods are being removed then just remove them across the board.

I like the idea of making drask more sensitive to heat though since I agree that a big part of their flavour is that they are cool creatures.  The coolest you might even say.  I'd just prefer that this sensitivity to heat have impacts other than just raw damage because I agree with the overall opinion that just taking more damage isn't a particularly fun mechanic.  @Miraviel had some really interesting ideas.

2022-07-28 03:35 UTC, Mochikokiko commented
For the vox change, you do understand removing something a player can control (taking more damage and playing around it) and adding something a player can't control (dying faster due to a lack of medical intervention) isn't a good thing, right?
What exactly is the goal of just base lining everything to act the same? (minus the ipc changes, which are still bizarre)

2022-07-28 08:34 UTC, Sneedstar commented
Can IPC's be overfed and become fat from this nutrition door shock change, what if they are placed in a human body? I'm curious for the sake of in what ways I can bully a IPC now, I like this change overall. 👍 

Would anything change for robotic brains as well?

2022-07-28 10:59 UTC, hal9000PR commented
> Feels a bit strange that burn mod would be left for Drask and Plasmaman though. 

Plasmamen remain due to the fact I've not had time to code a change for them. And drask remain due to the reasons i drew out in the PR.

> For the vox change, you do understand removing something a player can control (taking more damage and playing around it) 

I don't quite understand? How do you play around taking more damage from the most common damage source? By the same logic cant you just play around not being in crit? As I've said in other places the vox change is not exactly ideal. I'd prefer something better, but this is what i had time to produce.

2022-07-28 11:31 UTC, BakKeener commented
> For the vox change, you do understand removing something a player can control (taking more damage and playing around it) and adding something a player can't control (dying faster due to a lack of medical intervention) isn't a good thing, right? What exactly is the goal of just base lining everything to act the same? (minus the ipc changes, which are still bizarre)

I can see where you're coming from with the vox part, double O2 damage does seems a bit crazy in crit, I wonder how it fares in medbay and how well do chems react to it like salb and epi but personally I don't think it'll be an issue due to the handheld defibs just deleting O2 Damage in addition to in the event they do die, a single defib can just get rid of all the O2 damage and some cases all the external damage too. 

I think the goal of base lining everything is to help spread the playerbase a bit more out for species instead of picking something purely based on their stats, I could be wrong about that reason but it does sound like a good one for this.

2022-07-29 18:25 UTC, Mochikokiko commented
> > For the vox change, you do understand removing something a player can control (taking more damage and playing around it)
> 
> I don't quite understand? How do you play around taking more damage from the most common damage source? By the same logic cant you just play around not being in crit? As I've said in other places the vox change is not exactly ideal. I'd prefer something better, but this is what i had time to produce.

Example: The main time you'll take brute damage is when someone or something is directly coming at you with the intent to harm, random shit flying down hallways aside. You can make the active choice to run, engage, or gather something to help deal with it. Those are active in the moment gameplay choices the player makes.
O2 crit example: You are going down, the only thing to help you *before* you go down is to just have the correct meds on you (the autopen you start with does help with this if you act accordingly) and have someone come nab you when you call out and go down. Your choices as a player stops the moment you fall to the ground, regardless of what choices you made to end up in that situation.

My whole problem with a change like this, is that it moves things you can do to other players, not to mention that having unique racial features is like, a solid selling point for I dunno. a role playing game?

2022-07-29 23:52 UTC, hal9000PR commented
> The main time you'll take brute damage is when someone or something is directly coming at you with the intent to harm

And the main time you are in crit is after someone came at you with the intent to harm.

> O2 crit example: You are going down, the only thing to help you before you go down is to just have the correct meds on you 

By the same logic cant you just avoid crit if you can chose to avoid brute damage?

> not to mention that having unique racial features is like, a solid selling point for I dunno. a role playing game?

Is it really a unique feature if half of the species have a super similar version of it?

2022-07-30 23:46 UTC, AffectedArc07 requested changes

2022-07-30 23:46 UTC, AffectedArc07 commented on code/datums/weather/weather_types/radiation_storm.dm
> +		domutcheck(H, MUTCHK_FORCED)
```suggestion
	if(!prob(60))
		return

	if(!ishuman(L))
		return

	var/mob/living/carbon/human/H = L
	if(HAS_TRAIT(H, TRAIT_RADIMMUNE))
		return

	if(prob(max(0, 100 - resist)) && !HAS_TRAIT(H, TRAIT_GENELESS))
		randmuti(H) // Applies bad mutation
		if(prob(50))
			if(prob(90))
				randmutb(H)
			else
				randmutg(H)

		domutcheck(H, MUTCHK_FORCED)
```

2022-07-30 23:46 UTC, AffectedArc07 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +								)
```suggestion
		var/list/error_messages = list(
			"Error 196: motor functions failing.",
			"Error 32: Process %^~#/£ cannot be reached, being used by another file.",
			"Error 39: Cannot write to central memory unit, storage full.",
			"Error -1: isogjiohrj90903744kfgkgrpopK!!",
			"Error -1: poafejOIDAIJjamfooooWADm!afe!",
			"Error -1: PIKFAjgaiosafjiGGIGHasksid!!",
			"Error 534: Arithmetic result exceeded 512 bits.",
			"Error 0: Operation completed successfully.",
			"WARNING, CRITICAL COMPONENT ERROR, attempting to troubleshoot....",
			"runtime in sentience.dm, cannot modify null.som, STACK TRACE:",
			"master controller timed out, likely infinite recursion loop.",
			"Error 6344: Cannot delete file ~/2tmp1/8^33, no space left on device",
			"Error 42: Unable to display error message.",
			"Daisy.... Daisy...."
		)
```

2022-07-31 05:44 UTC, Mightykitten81 commented
The vox rework part is a little broken, it basically makes any level of crit lethal for vox. This translates to 'oh hey I can one tap that vox if I really wanted to' because once they are in crit, they have absolutely no way of helping themselves.

2022-07-31 11:52 UTC, farie82 requested changes

2022-07-31 11:52 UTC, farie82 commented on code/modules/mob/living/carbon/human/species/grey.dm
> +		if(H.head?.flags & THICKMATERIAL && H.wear_suit?.flags & THICKMATERIAL) // fully pierce proof clothing is also water proof!
```suggestion
		if((H.head?.flags & THICKMATERIAL) && (H.wear_suit?.flags & THICKMATERIAL)) // fully pierce proof clothing is also water proof!
```
Not required to make it work. But it makes it a bit more clear that this is a bitwise operation and not a logical operation

2022-07-31 11:52 UTC, farie82 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	brute_mod = 1.52 // 1 * 0.66 (robolimbs) * 1.51 = 1
```suggestion
	brute_mod = 1.52 // 1 * 0.66 (robolimbs) * 1.52 = ~1
```
Since it ain't exactly 1. But `1.0032`

2022-07-31 11:53 UTC, farie82 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +		var/list/error_messages = list(
```suggestion
		var/static/list/error_messages = list(
```
One bonus refactor

2022-07-31 12:21 UTC, farie82 approved these changes

2022-07-31 12:28 UTC, merged

2022-07-31 15:51 UTC, warriorstar-orion commented
I don't think I'm a fan of the IPC changes. In general I dislike the brain damage modifier because I genuinely cannot stand when my character says something I explicitly didn't tell it to say, but I also don't think getting shocked from a vendor that dispenses soda should cause a sophisticated positronic machine to start babbling and drooling uncontrollably.

I'm also not sure why rad immunity was taken away, is that meant to be a balance change against the damage percentage? It's such a random, minor unique buff that only affects being an engineer IPC or being an IPC in a radstorm (plasmen are the only other selectable species with rad immunity), and removing it feels orthogonal to the purpose of the PR. Why not let IPCs keep this unique trait?

2022-08-02 05:59 UTC, Sneedstar commented
I feel like the relevancy of rad immunity does come into question here, why not just make rads reduce the IPC's "hunger" when they are effected by rads at a rapid rate. They are inconvenienced in such a way that it will make them be a bit more cautious but not lean so much towards death. I'm not against the idea of rad immunity removal, but I think with all the comments on this PR overall says that there could be future prospects from this if touched on more. I want to see this merged for a taste of spice in my space man experience really.