Adds Robotic Storage to Central Command and Reduces CC Toxicity
ParadiseSS13/Paradise pull request #18515
Opened 2022-07-23 05:01 UTC by LightFire53

## What Does This PR Do
 Adds robotic storage for ERT Cyborgs with the ERT cryodorms.

Also changes the instances of `/turf/simulated/floor/plasteel/dark/nitrogen` to be `/turf/simulated/floor/plasteel/dark` so CC personnel stop being poisoned by the atmosphere. <strike>This is a Certified™ S34N moment.</strike>

## Why It's Good For The Game
 Sleepy borgs want to go to bed. Steve wants to stop suffocating.

## Images of changes

![image](https://user-images.githubusercontent.com/16112919/180591124-902fe4e0-178c-4dd2-8b1e-7c3e0325375f.png)

## Changelog
:cl:
add: Added robotic storage units to CC Cryodorms
fix: Central Command no longer has a toxic atmosphere in places. Note: Personnel may remain toxic.
/:cl:

2022-07-23 08:04 UTC, S34NW commented
https://youtu.be/sTMgX1PDGAE

2022-07-23 09:48 UTC, Contrabang commented
Just wondering, are these robotic storages silent like the other cryo storages? Like the normal ones at CC wouldnt say that the ERT has cryod, but these robotic ones might.

2022-07-24 03:37 UTC, LightFire53 commented
> Just wondering, are these robotic storages silent like the other cryo storages? Like the normal ones at CC wouldnt say that the ERT has cryod, but these robotic ones might.

Not in the latest commit now. Thanks for mentioning!

2022-07-24 17:44 UTC, Miraviel requested changes
Tested it, I could not find anything else problematic other than the robotic console. In case anyone would like to test these, I've done so:

- If I cryo in CC, will my character show up in the cryostorage on the station? - no
- Is the cryogenic console on the wall linked to these cryopods? - yes
- Is the on-station console linked to these cryopods in any way? - no
- Is the area lit? - yes
- Do airlocks need any kind of access? - no
- Do people properly despawn? - yes

Dunno what else could be tested, it just works.

2022-07-24 17:44 UTC, Miraviel commented on code/game/machinery/cryopod.dm
> +
When you cryo as a cyborg, it does not show up on the local Robotic Storage Console (neither on the on-station one):

![image](https://user-images.githubusercontent.com/33333517/180659427-cb46b57f-df96-4bef-b726-34c36e6dc582.png)

...

It shows up in the Cryogenic Oversight Console instead:

![image](https://user-images.githubusercontent.com/33333517/180659441-97dcbc0d-8e72-44fd-8bab-afadf11edac4.png)

2022-07-25 15:22 UTC, S34NW approved these changes
map is fine

2022-07-26 07:11 UTC, Miraviel approved these changes
Apparently, the cryo storage thing is a code-related issue, I will try to fix that. Map is neat!

2022-07-26 14:27 UTC, hal9000PR approved these changes

2022-07-26 14:42 UTC, merged