Armour Refactor
ParadiseSS13/Paradise pull request #18547
Opened 2022-07-24 20:43 UTC by Edan52

## What Does This PR Do
Applies the idea proposed in #18521

Refactors the armour calculation & modifies some of the existing armour values to be more in line with these changes.

This is not finished yet, but please comment with anything that I've missed or things that should be changed as it's easy to miss things here.

I need to reconsider armour penetration.

## Why It's Good For The Game
See reasoning on the project discussion.

## Changelog
:cl: CornMyCob
tweak: Armour now uses a new calculation, stacking lots of armour is now less effective
/:cl:

2022-07-24 20:52 UTC, hal9000PR commented on code/modules/mob/living/carbon/human/species/_species.dm
> +			var/damage_amount = (damage/(1+(blocked/ARMOUR_CONSTANT))) * brute_mod * H.physiology.brute_mod
this line is written multiple times just with different mods.
might it be good to make a define like
```
#define ARMOUR_EQUATION(damage, armour, modifier) (damage / (1 + (armour / ARMOUR_CONSTANT)) * modifier
```
and then pass the damage, blocked and mod1 * mod2 into the params.

2022-07-24 21:05 UTC, Qwertytoforty commented
I am not sure I am a fan of this formula, that makes armor under 50 stronger and over 50 weaker. I feel like addressing the sources of stacking, sec jumpsuit, armored accessories, and bone bracers, may be better than this. This means we can keep the armor values simple to read, with reading 20 melee being a 20% reduction, vs actually being ~29% reduction. Also keeps it more consistent with how the rest of the armor works in the game. Alternatively, we make stacking armor items multiplicitive, vs additive.

2022-07-28 03:35 UTC, Rurik123 commented
I'm an idiot when it comes to this sort of thing, so feel free to disregard/correct this if I've made a mistake.

If I'm reading this right, the armor value for anything above 50 is nerfed, even if it is not relying on stacking armor. Like Elite Syndicate HS being lowered from 60 soley cause it stands alone above 50, not cause of any additional armor.

Wouldn't it be superior if the formula made the largest armor value flat, and instead adjusted the efficiency of the smaller stacking armor values? This way the established armor value of inquis/ERT/syndicate/etc armor is kept, as well as the armor stacking problem being solved?

Apologies if I misread or misunderstand something.

2022-07-28 18:20 UTC, SpringSkipper commented
The current armor system is entirely fine except for the additive stacking.

If you change the formula then you're taking it on yourself to change the armor amount of every armor item in the game. That seems like a hard requirement to me. Otherwise you're blindly nerfing and buffing a lot of items without regard to the game effect those changes will have.

Changing stacking to multiplicative would work just as well at fixing the stacking mining armor problem, plus it would remove the requirement to readjust every armor value in the whole game.

2022-07-29 11:08 UTC, Edan52 commented on code/modules/mob/living/carbon/human/human.dm
> +	var/bomb_armor = 100 - (100/(1+(getarmor(null, BOMB)/50)))
Gonna change this calculation to a define (and add a couple more defines for people to use) and apply it to a couple more cases I found after work.

2022-07-30 16:31 UTC, hal9000PR requested changes

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	return FALSE
much clearner. good stuff.

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/living_defense.dm
> +			armor = max(0, (armor * ((100-armour_penetration_percentage) / 100)) - armour_penetration_flat)
```suggestion
			armor = max(0, (armor * ((100 - armour_penetration_percentage) / 100)) - armour_penetration_flat)
```

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +				L.apply_damage(25, BRUTE, limb_to_hit, L.run_armor_check(limb_to_hit, MELEE, null, null, armour_penetration_flat))
dont you want to pass percentage armour pen into this?

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
> +			L.apply_damage(10, BRUTE, limb_to_hit, L.run_armor_check(limb_to_hit, MELEE, null, null, armour_penetration_flat))
dont you want to pass percentage armour pen into this?

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	armour_penetration_flat = INFINITY
armour pen percentage of 100

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +			L.apply_damage(12.5, BRUTE, limb_to_hit, L.run_armor_check(limb_to_hit, MELEE, null, null, armour_penetration_flat))
same here

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/syndicate.dm
> +	armour_penetration_flat = 28
why the fuck is this 28 armour pen??

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/armour_penetration_percentage = 0 //How much armour they ignore, as a percentage of their total armour
```suggestion
	/// How much armour they ignore, as a flat reduction from the targets armour value. calculated after percentage armour pen
	var/armour_penetration_flat = 0
	/// How much armour they ignore, as a percentage of their total armour. calculated before flat armour pen.
	var/armour_penetration_percentage = 0
```

2022-07-30 16:31 UTC, hal9000PR commented on code/modules/projectiles/projectile/magic.dm
> +	armour_penetration_flat = INFINITY
percent armour pen

2022-07-30 18:14 UTC, Edan52 commented on code/datums/weather/weather_types/radiation_storm.dm
> +				if(prob(max(0, 100 - ARMOUR_VALUE_TO_PERCENTAGE(resist))))
done

2022-07-30 18:17 UTC, Edan52 commented on code/__DEFINES/armour.dm
> +#define ARMOUR_PERCENTAGE_TO_VALUE(percentage) ((5000 / (100 - percentage)) - 50)
added a check

2022-07-30 18:17 UTC, Edan52 commented on code/game/gamemodes/cult/cult_items.dm
> +	armor = list(MELEE = -25, BULLET = -25, LASER = -25, ENERGY = -25, BOMB = -25, BIO = -25, RAD = -25, FIRE = 0, ACID = 0)
added a check, so this should never occur

2022-07-30 18:17 UTC, Edan52 commented on code/game/objects/items.dm
> +	var/armour_penetration_percentage = 0 //percentage armour reduction
applied

2022-07-30 18:17 UTC, Edan52 commented on code/game/objects/items/weapons/batons.dm
> +	var/armour = target.run_armor_check("chest", armour_penetration_flat = stamina_armour_pen) // returns a % of their chest melee armour
done

2022-07-30 18:18 UTC, Edan52 commented on code/game/objects/items/weapons/batons.dm
>  	target.adjustStaminaLoss(stamina_damage * factor)
added a human check, uses the percentage calculation & is the same as before.

2022-07-30 18:18 UTC, Edan52 commented on code/game/objects/items/weapons/melee/energy.dm
> +	armour_penetration_flat = INFINITY
done

2022-07-30 18:18 UTC, Edan52 commented on code/game/objects/items/weapons/staff.dm
> +	armour_penetration_flat = INFINITY
done

2022-07-30 18:18 UTC, Edan52 commented on code/game/objects/items/weapons/twohanded.dm
> +	armour_penetration_flat = INFINITY
done

2022-07-30 18:18 UTC, Edan52 commented on code/__DEFINES/armour.dm
> +#define ARMOUR_VALUE_TO_PERCENTAGE(value) (100 - (100 / (1 + (value / ARMOUR_CONSTANT))))
added a check

2022-07-30 18:19 UTC, Edan52 commented on code/modules/mob/living/simple_animal/hostile/syndicate.dm
> +	armour_penetration_flat = 28
changed it to 30 :)

2022-07-30 18:40 UTC, hal9000PR commented on code/datums/weather/weather_types/radiation_storm.dm
> +			if(!HAS_TRAIT(H, TRAIT_RADIMMUNE) || resist != INFINITY)
shouldnt this be an `&&` ?

2022-07-30 18:42 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +			L.apply_damage(12.5, BRUTE, limb_to_hit, L.run_armor_check(limb_to_hit, MELEE, null, null, armour_penetration_flat))
and you missed this one.

2022-07-31 15:26 UTC, AffectedArc07 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +#define BLOCK_CHANCE_CALCULATION(hand_block_chance, armour_penetration_flat, armour_penetration_percentage, block_chance_modifier) clamp((hand_block_chance * ((100-armour_penetration_percentage) / 10
Should this go in the `armour.dm` defines file?

2022-08-01 17:59 UTC, hal9000PR approved these changes

2022-08-01 19:23 UTC, merged