prevents alt from being passed from TGUI to byond
ParadiseSS13/Paradise pull request #18619
Opened 2022-07-28 13:45 UTC by hal9000PR

## What Does This PR Do
title.
means alt tabbing while having a TGUI menu focused wont break your hotkeys.
Fixes #18617

## Why It's Good For The Game
breaking hotkeys is bad

## Testing
Used hotkeys, worked,
opened TGUI menu, focused it
Used hotkeys worked,
alt tabbed, 
tabbed back in,
used hotkeys with the TGUI focused and with the game window focused, both worked.

## Changelog
:cl:
fix: alt tabbing no longer breaks hotkeys when using TGUI
/:cl:

2022-07-28 14:48 UTC, SteelSlayer reviewed
Just to be safe: can you still use the TGUI hotkeys `ctrl alt +` and `ctrl alt -` for debug mode and the kitchen sink with your changes?

2022-07-28 15:03 UTC, hal9000PR commented
`ctrl alt +` works

`ctrl alt =` doesn't appear to work, and it appears that it never worked/wasn't working before the passthrough stuff was added.

2022-07-28 15:49 UTC, S34NW requested changes
You need to update the comment on lines 153-156

2022-07-31 20:48 UTC, SteelSlayer approved these changes

2022-07-31 20:50 UTC, merged