BoxStation: Unresctricted sides in medbay airlocks
ParadiseSS13/Paradise pull request #18625
Opened 2022-07-28 20:26 UTC by DogeDogIs

Added unresctricted sides in surgery airlocks for people that might be stuck inside the surgery room or even to get out of there faster.

## What Does This PR Do

This PR add some unresctriced sides in surgery airlocks.

## Why It's Good For The Game

Thoses sides can save a lot of time and make someone that is stuck inside the surgery rooms get out of there. Is not cool mid surgery your doctor run away from you and don't ever return. 

And I know that this can maybe make the prisioners escape, but security officers are there to don't allow the prisioner to escape.
## Images of changes

![image](https://user-images.githubusercontent.com/62888630/181630895-8cbfe589-e2f2-4f9d-8925-3489ad720742.png)

## Testing

Map was tested in my local host server. 

## Changelog
:cl:
tweak: Added unresctricted sides in 4 airlocks in surgery room in medbay. 

/:cl:

2022-07-28 21:01 UTC, matttheficus commented
As someone who plays a decent chunk of Surgeon, I’ve never had an issue with people getting “stuck” in an OR. The outer doors are all-access I’m fairly sure so they don’t even need the access.

From a Security standpoint I also don’t really like the idea of people undergoing implant surgery/decap of Changelings to be able to slip out so easily.

That, and you really shouldn’t be able to leave an OR without a Doctor giving you the okay, which is usually letting you out of the door.

2022-07-28 21:03 UTC, Inadvizable commented
> From a Security standpoint I also don’t really like the idea of people undergoing implant surgery/decap of Changelings to be able to slip out so easily.

aside from decapping changelings instead of cremating them (yuck) this is kind of traitors getting to use the TC they spent on those freedoms

2022-07-28 21:07 UTC, DogeDogIs commented
> As someone who plays a decent chunk of Surgeon, I’ve never had an issue with people getting “stuck” in an OR. The outer doors are all-access I’m fairly sure so they don’t even need the access.
> 
> From a Security standpoint I also don’t really like the idea of people undergoing implant surgery/decap of Changelings to be able to slip out so easily.
> 
> That, and you really shouldn’t be able to leave an OR without a Doctor giving you the okay, which is usually letting you out of the door.

I always get stuck in there, mostly when have spiders or a lot of EoCs. And about the doctor permission, probably someone that is under surgery want to be under surgery, and if they don't want, its their fault. When I am stuck insde the OR I don't want to break the windows to get out, but at the same time, doctors don't appear to open the door for me.

2022-07-28 22:54 UTC, Bm0n requested changes
The two north-facing doors are already public. Why did you add one-way access helpers to them? 

![image](https://user-images.githubusercontent.com/92271472/181650480-9def310a-8232-4305-8ef3-b05a9e5b5bd7.png)

2022-07-29 00:06 UTC, DogeDogIs commented
> The two north-facing doors are already public. Why did you add one-way access helpers to them?
> 
> ![image](https://user-images.githubusercontent.com/92271472/181650480-9def310a-8232-4305-8ef3-b05a9e5b5bd7.png)

oh, when i was in game they aren't probably someone set another access in game, i am going to change this, didn't noticed

2022-07-29 00:27 UTC, Bm0n approved these changes
Mapping changes are fine

2022-07-29 11:49 UTC, S34NW commented
> Is not cool mid surgery your doctor run away from you and don't ever return.

I don't think this PR solves any actual issue unfortunately. The one potential use case you describe us not a real use case because if a doctor runs away during surgery you are still not going to be able to escape due to being anesthetized for surgery.

2022-07-29 11:54 UTC, S34NW requested changes
Also, if this was to be approved it should be standardised across all maps.

2022-07-29 11:57 UTC, Bm0n commented
Personally, I find this PR kinda useless since if I ever get stuck in one of the OR rooms I just jump into the disposals chute to get out

2022-07-29 14:25 UTC, DogeDogIs commented
> Personally, I find this PR kinda pointless since if I ever get stuck in one of the OR rooms I just jump into the disposals chute to get out

I guess jumping in the disposal chute is more pointless than add a access helper.

2022-07-29 14:30 UTC, DogeDogIs commented
> > Is not cool mid surgery your doctor run away from you and don't ever return.
> 
> I don't think this PR solves any actual issue unfortunately. The one potential use case you describe is not a real use case, because if a doctor runs away during surgery you are still not going to be able to escape due to being anesthetized for surgery.

Anesthesia is rarely used, from my point of view, and this access aid can also make even working in various situations faster, for example, if there are terror spiders and many people are infected with terror eggs, the doctor can call people to wait in the next room while performing the surgery on one, and after finishing the surgery of that person, he/she gets up, and leaves the room without needing the doctor's help to open the door for him, and at the same time At the same time, making life easier for someone else who wants to get the eggs out of themselves.

2022-07-29 14:36 UTC, DogeDogIs commented
> Also, if this was to be approved it should be standardised across all maps.

Going to make.

2022-07-30 00:56 UTC, Bm0n commented
> I guess jumping in the disposal chute is more pointless than add a access helper.

well with the chutes it makes players think on their feet if they want to escape the OR room, this is especially true for clings or even a traitor who's getting an implant removed.

you can still get out if you need to via the chute, no one is technically "stuck" in an OR room and if they take the chute they have to travel on a set path(the disposals network) to get out.

besides that, locked doors are one of the main reasons we have an AI, to open doors for people.

2022-07-30 12:03 UTC, DogeDogIs commented
> > I guess jumping in the disposal chute is more pointless than add a access helper.
> 
> well with the chutes it makes players think on their feet if they want to escape the OR room, this is especially true for clings or even a traitor who's getting an implant removed.
> 
> you can still get out if you need to via the chute, no one is technically "stuck" in an OR room and if they take the chute they have to travel on a set path(the disposals network) to get out.
> 
> besides that, locked doors are one of the main reasons we have an AI, to open doors for people.

The AI can make more important things than opening the OR door, when you can make it by yourself, if we had the access helpers. The chute, yes, is a escape to traitors, but not a escape for non-antags personnel that just want to get out of there. I'm sorry, but for me, its don't make any sense you go into a chute go get out of a room and end in cargo.

2022-08-06 23:08 UTC, lewcc commented
I feel like it should be the doctor's choice for when to let patients out. As a doctor, if I'm running off mid-surgery, it's usually to fetch something else for a patient, and I don't really want patients to just walk themselves out if they still have an open incision, for instance. If someone's in a hurry to get their surgery done and they're just hydrocodoned or something, they might not realize that they're done and leave with IB or something, without the doc being able to do anything to stop them.

If they get stuck in the room, they can still signal by bashing the door, climb into the disposals chute if they get completely forgotten in an opaque surgery room, or as sean said just call on the radio for the AI or someone else to let them out.

Also, given how often people tend to already run off without their bags, it feels like it would only get worse if they had a one-way door out of the surgery room.

2022-08-07 18:44 UTC, closed without merging