Converts MO19 from gateway to ruin
ParadiseSS13/Paradise pull request #18660
Opened 2022-07-31 20:03 UTC by AffectedArc07

## What Does This PR Do
Converts the MO19 gateway mission to a space ruin. Mapping was initially done by @S34NW until I stole it and shrunk it a bit.

The station part of the map is the same base template, but with xenos moved into the main part of the map as opposed to a hive on the top left. The escape room on the top right has also been removed due to being entirely superfluous. 

The asteroid is also dug out on the bottom to provide access to the external airlocks on the aft side.

## Why It's Good For The Game
Gateway bad, ruins good.

## Images of changes
See MDB or MDB2. Sidenote, I need to kill MDB1 soon.

## Testing
Untested yet, I am PRing this on a timecrunch. Will edit when I have chance.

## Changelog
:cl: AffectedArc07
tweak: The MO19 gateway is now a random space ruin instead of a gateway destination.
/:cl:

2022-07-31 20:14 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/182043360-97c93d89-1bdc-409e-b292-7f53349e3f84.png)
No `/mob/living/simple_animal/hostile/alien/queen/large`?

![image](https://user-images.githubusercontent.com/12197162/182043385-43bc05ae-46d6-4ec3-a70a-d594b59d81e9.png)
You should probably put some decoration outside the windows like here, there are 6 such windows areas. Not sure what you could put there but it would look better than just sand.

![image](https://user-images.githubusercontent.com/12197162/182043429-010c5e63-0e3a-42be-96b6-ef6602e640ea.png)
Your air vents are the wrong subtype and var edited to be on.

![image](https://user-images.githubusercontent.com/12197162/182043453-15aa6174-4dc3-4408-a98e-a3827f64d602.png)
![image](https://user-images.githubusercontent.com/12197162/182043464-a758963f-55f6-4b4f-b983-3698d8d7a089.png)
![image](https://user-images.githubusercontent.com/12197162/182043469-15d364ee-f3f2-4b1e-b7ea-ae2900a5d1d9.png)
![image](https://user-images.githubusercontent.com/12197162/182043478-49568711-e2bf-4c59-917f-861d983a3535.png)
Consoles are wrong dir

![image](https://user-images.githubusercontent.com/12197162/182043499-17b6cf64-5c92-408f-a758-fe34eb9527d0.png)
This injector is var edited to be on instead of subtype

![image](https://user-images.githubusercontent.com/12197162/182043517-1e18d2cf-a365-47ff-9f24-f34fa24da054.png)
These stools are all lacking dir

![image](https://user-images.githubusercontent.com/12197162/182043560-57b8d338-9624-49f0-ab4e-85d63a64c237.png)
Some of the floors in this hallway are properly airless, but others are not.

2022-07-31 20:46 UTC, AffectedArc07 commented
<details>
<summary>Sean's comment</summary>

> ![image](https://user-images.githubusercontent.com/12197162/182043360-97c93d89-1bdc-409e-b292-7f53349e3f84.png) No `/mob/living/simple_animal/hostile/alien/queen/large`?
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043385-43bc05ae-46d6-4ec3-a70a-d594b59d81e9.png) You should probably put some decoration outside the windows like here, there are 6 such windows areas. Not sure what you could put there but it would look better than just sand.
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043429-010c5e63-0e3a-42be-96b6-ef6602e640ea.png) Your air vents are the wrong subtype and var edited to be on.
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043453-15aa6174-4dc3-4408-a98e-a3827f64d602.png) ![image](https://user-images.githubusercontent.com/12197162/182043464-a758963f-55f6-4b4f-b983-3698d8d7a089.png) ![image](https://user-images.githubusercontent.com/12197162/182043469-15d364ee-f3f2-4b1e-b7ea-ae2900a5d1d9.png) ![image](https://user-images.githubusercontent.com/12197162/182043478-49568711-e2bf-4c59-917f-861d983a3535.png) Consoles are wrong dir
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043499-17b6cf64-5c92-408f-a758-fe34eb9527d0.png) This injector is var edited to be on instead of subtype
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043517-1e18d2cf-a365-47ff-9f24-f34fa24da054.png) These stools are all lacking dir
> 
> ![image](https://user-images.githubusercontent.com/12197162/182043560-57b8d338-9624-49f0-ab4e-85d63a64c237.png) Some of the floors in this hallway are properly airless, but others are not.

</details>

All of these are things you could have fixed when you did the map on your own PR :smork:

2022-07-31 20:47 UTC, S34NW commented
> All of these are things you could have fixed when you did the map on your own PR :smork:

You maade me close it prematurely, so I blame you :P

2022-08-01 12:34 UTC, Komrad822 commented
Will the stechkin still be there next to the queen or no?

2022-08-04 20:23 UTC, AffectedArc07 commented
> Will the stechkin still be there next to the queen or no?

Nope

2022-08-13 12:19 UTC, hal9000PR commented on code/datums/ruins/space.dm
> +	description = "A now-defunct lunar outpost, with the last received signal being that of distress."
its not longer on a moon, its an asteroid.

2022-08-13 12:42 UTC, hal9000PR approved these changes

2022-08-13 12:44 UTC, merged