Blood crawling (not the one you're thinking of)
ParadiseSS13/Paradise pull request #18759
Opened 2022-08-10 00:22 UTC by ParaGitV

## What Does This PR Do

When you move or are moved through blood while lying down you will become bloody. This works alongside footprints and requires blood puddles that aren't already drained.

## Why It's Good For The Game

More immersive to actually become bloody when pulled through puddles of blood. Also encourages people to clean their outfits if they choose to be a floor-dweller.

## Images of changes

![giphy (1)](https://user-images.githubusercontent.com/109384402/183779491-10d55a96-c3bd-4cdc-84d0-9c78583bc8e9.gif)

## Testing

Tested with different combinations of species, outfits, and mob states. Behaved as expected.

## Changelog
:cl:
add: Become bloody when prone and moving through blood
/:cl:

2022-08-10 00:22 UTC, lewcc commented on code/game/objects/effects/decals/cleanable.dm
> +			if(bloodiness > 0 && blood_DNA && blood_DNA.len)
```suggestion
			if(bloodiness > 0 && blood_DNA && length(blood_DNA))
```

2022-08-10 04:00 UTC, Sirryan2002 requested changes

2022-08-10 04:00 UTC, Sirryan2002 commented on code/game/objects/effects/decals/cleanable.dm
> +			if(bloodiness > 0 && blood_DNA && length(blood_DNA))
```suggestion
			if(bloodiness > 0 && length(blood_DNA))
```
length will return FALSE if blood_DNA is null already

2022-08-14 01:19 UTC, hal9000PR approved these changes

2022-08-14 04:32 UTC, Sirryan2002 approved these changes

2022-08-14 11:42 UTC, merged