Heaters/Freezers now conserve energy instead of producing it
ParadiseSS13/Paradise pull request #18765
Opened 2022-08-10 15:48 UTC by NethIafin

## What Does This PR Do
Electronic heaters and freezers no longer produce energy by consuming x10 less energy then they should have to convert given amount.

**Definitely needs a testmerge**, but it will affect at most 3-4 atmos players and will make their life a bit more interesting

## Why It's Good For The Game
Conservation of energy is good for the game, and while breaking the physics is fun, breaking it with "Cooler<-TEG->Heater" is very easy and very not fun.
Currently this affects power draw for Toxins and Medbay, but shouldn't be that much. Biggest effect is its usage to generate energy. Atmos already has space so they can easily cool using spaceloop, leaving freezers to deal with emergencies.

## Testing
1. Load the master branch
2. Build a TEG with 1 heater on one side, 1 cooler on the other.
3. Pipe it, fill stuff with plasma, disconnect the cold from hot loop.
4. Turn TEG and heater/freezer on
5. Watch power going up
6. Load this branch
7. Do steps 2-4
8. Watch batteries drain pretty fast (or slower if you maxed out the manipulators on heater/freezer)

## Changelog
:cl:
tweak: Removed Pipe Heater/Freezer's ability to generate infinite energy.
/:cl:

2022-08-10 15:49 UTC, AffectedArc07 commented
Please test how this interacts with the syndicate space research base, because that (for some reason) relies on the violating the laws of thermodynamics to produce power. I hate it too, dont worry.

2022-08-10 15:50 UTC, NethIafin commented
> Please test how this interacts with the syndicate space research base, because that (for some reason) relies on the violating the laws of thermodynamics to produce power. I hate it too, dont worry.

WilCo

2022-08-10 16:00 UTC, AffectedArc07 requested changes

2022-08-10 16:00 UTC, AffectedArc07 commented on code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
>  	var/temperature_delta= abs(old_temperature - air_contents.temperature)
```suggestion
	var/temperature_delta = abs(old_temperature - air_contents.temperature)
```
May as well

2022-08-10 16:00 UTC, AffectedArc07 commented on code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
>  		parent.update = 1
```suggestion
		parent.update = TRUE
```

2022-08-10 16:10 UTC, NethIafin commented on code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
>  		parent.update = 1
fixed

2022-08-10 16:10 UTC, NethIafin commented on code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
>  	var/temperature_delta= abs(old_temperature - air_contents.temperature)
fixed

2022-08-10 16:11 UTC, NethIafin commented
Confirmed, this fucks the syndicate base into 0-power state

To fix that a separate PR with a different engine will be provided

2022-08-10 16:28 UTC, GuiltyNeko commented
How much spaceloop would syndicate base need to have a working TEG?

2022-08-10 16:44 UTC, NethIafin commented
> How much spaceloop would syndicate base need to have a working TEG?

Problem is that Syndicate base will require both cold loop and heat loop for it to work.

Entire syndicate base consumes 27kW (sic!) which can be provided by few PACMANs if you want them actively feeding sheets of plasma, or a single upgraded SUPERPACMAN which you can feed with 12sheets of uranium round start and have it feed the power of entire syndicate station for 200+ minutes

2022-08-10 17:10 UTC, meow20 commented
I think the syndie space base could have a different engine provided than pacmans, people go there to learn stuff including engineering and they wont learn much with pacmans. Maybe max upgraded turbine because sm/tesla/singulo are much more dangerous than TEG which is comparable to a turbine but a base one wouldnt have enough power for the station.

2022-08-10 17:46 UTC, NethIafin commented
> I think the syndie space base could have a different engine provided than pacmans, people go there to learn stuff including engineering and they wont learn much with pacmans. Maybe max upgraded turbine because sm/tesla/singulo are much more dangerous than TEG which is comparable to a turbine but a base one wouldnt have enough power for the station.

Turbine will work but it will require a bigger map rework than just one room. It will need large storage of plasma and oxygen, a mixer, a turbine burner room, an airlock to turbine (unless we want inaccessible turbine)... at that point a **proper** TEG setup with inaccessible space loop and a burner (especially since one for toxins exists nearby)

Fun fact - proper turbine setup assumes you have pump on the OUTSIDE of the turbine, not on the same side as inlet.

2022-08-10 20:15 UTC, Sirryan2002 commented
I like this change due to it balancing power usage, however the syndicate space base needs to work and shouldn't have to be fixed in a separate PR. Consider adding alternative forms of power to the space base or reconfiguring/adding subtypes so that the TEG on the space base function properly.

2022-08-10 20:17 UTC, NethIafin commented
> I like this change due to it balancing power usage, however the syndicate space base needs to work and shouldn't have to be fixed in a separate PR. Consider adding alternative forms of power to the space base or reconfiguring/adding subtypes so that the TEG on the space base function properly.

I have discussed this with @AffectedArc07 and it's better to solve it in a separate PR.
Now if that PR is to be merged before this one - that's a different question - probably yes?

2022-08-10 23:11 UTC, NethIafin commented
The Syndicate Outpost is fixed here: https://github.com/ParadiseSS13/Paradise/pull/18770

2022-08-11 13:08 UTC, hal9000PR approved these changes

2022-08-11 14:32 UTC, AffectedArc07 approved these changes
Death to violations of the laws thermodynamics.

2022-08-13 10:44 UTC, NethIafin commented
This needs a small rework because power and atmos ticks are separate

2022-08-13 13:16 UTC, closed without merging