Tweaks DeltaStation Engineering
ParadiseSS13/Paradise pull request #18794
Opened 2022-08-13 01:59 UTC by LightFire53

## What Does This PR Do

- Areas the DeltaStation SMES to use the engine_smes area, and adds the appropriate infrastructure
- Areas the DeltaStation Engineering Secure Storage to use the equipmentstorage area and adds the appropriate infrastructure
    - This is changing it from the `engine_smes` area it was before for some reason
- Areas the DeltaStation Hardsuit Storage to use the hardsuitstorage area
    - This was also using `engine_smes` for some reason
- Adds a few more light tubes to the main area of Engineering and Atmospherics to make it less dark during nightshift lighting
- Cleans up the Atmospheric technician locker area so the lockers are one side and the hardsuit storage is on the other
- Adds a light switch to the Engineering Breakroom

## Why It's Good For The Game
We have these areas for a reason, we should actually use them then. In addition, tidiness and ease of sight are good.

## Images of changes

Atmospherics lockers/hardsuit storage and light changes
![image](https://user-images.githubusercontent.com/16112919/184464088-1725c44e-dfc4-4bd7-bc33-6151968273a9.png)

Light switch!
![image](https://user-images.githubusercontent.com/16112919/184464108-29b50bf1-5b4d-46bc-9ac0-f45c2b75df24.png)

Engineering with Areas
![image](https://user-images.githubusercontent.com/16112919/184464123-666cac34-9809-45ba-a434-bb9e0148c24f.png)

Without Areas
![image](https://user-images.githubusercontent.com/16112919/184464190-2c24d126-2766-4310-8e3d-e4fd960ef490.png)

## Testing

Loaded local server
Viewed runtimes to ensure there were no pipe areas
Tested the fire alarms/lights/air alarms/APCs to ensure they worked as intended
Shifted the lighting to night mode to see how it fared compared to before

## Changelog
:cl:
tweak: DeltaEngineering and DeltaAtmospherics have more light tubes for better lighting during night shift
tweak: DeltaAtmospherics locker area is more organized
tweak: DeltaEngineering Areas are a bit more sane now
tweak: DeltaEngineering Breakroom now has a light switch as well
/:cl:

2022-08-31 13:01 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/187684107-0ad58c68-17f3-41ca-8ae3-a66019186da8.png)

Re-route this wire and its good to go

2022-09-02 18:16 UTC, S34NW approved these changes

2022-09-03 05:58 UTC, SteelSlayer reviewed
While looking everything over, I noticed that there's two consoles on this tile (unrelated to your change). Could you fix that while you're here? I'm thinking since there's already a power monitoring console one tile to the left, the power monitoring console on this tile should be removed then the station alert console face should be made to face north.

![image](https://user-images.githubusercontent.com/42044220/188257889-6be1a017-b3ff-4761-b402-317bf465ef91.png)

Other than that, LGTM.

2022-09-03 18:07 UTC, SteelSlayer approved these changes

2022-09-03 18:24 UTC, merged