Buffs his grace
ParadiseSS13/Paradise pull request #18817
Opened 2022-08-14 20:50 UTC by PopeDaveThe3th

## What Does This PR Do
Buffs His Grace, greatly increasing the death timer on it, and slightly buffing its damage.

## Why It's Good For The Game
At its current state, it is nigh-impossible to reach ascension as the bloodthirst timer simply ticks down too fast.

Now, while the timer still increases rapidly near ascension, it is far more lenient to begin with, giving players some needed room for error.

The damage was buffed to put it in line with the traitor toolbox, and because numbers divisible by 5 make me happy.

## Testing
- Loaded into test server
- Spawned the funny toolbox
- Beat numerous vox to death
- Countdown is now nice and slow to start with, still fast once you go into the double digits
## Changelog
:cl:
tweak: Buffed his grace, increasing his timer and damage
/:cl:

2022-08-17 15:21 UTC, hal9000PR requested changes

2022-08-17 15:21 UTC, hal9000PR commented on code/game/objects/items/his_grace.dm
> +		adjust_bloodthirst(0.5 + FLOOR(length(contents) * 0.25, 1)) //Maybe adjust this?
```suggestion
		adjust_bloodthirst(0.5 + FLOOR(length(contents) * 0.25, 1))
```
TODO comment

2022-08-18 03:55 UTC, Sirryan2002 approved these changes
code is fine

2022-08-18 10:49 UTC, hal9000PR approved these changes

2022-08-18 13:39 UTC, merged