Legion Rework
ParadiseSS13/Paradise pull request #18819
Opened 2022-08-14 23:02 UTC by Edan52

WIP as I still need to add a couple things & a crusher trophy

## What Does This PR Do
Tweaks the legion megafauna quite a bit, making the fight more difficult and more interesting.

Here is what has changed:

- It still charges
- It summons mini legion skulls each time it gets hit
- It fires a 50 tile long death laser at you, giving you less time to react as it gets lower
- It summons the "big legion" mob, which I have tweaked to push players away with its melee attack, it is quite a strong summon
- It will also summon regular legions as the fight goes on

## Why It's Good For The Game
The current fight is lacklustre, and needs some sauce

## Images of changes
Coming soon

## Changelog
:cl: CornMyCob
tweak: Buff legion (i will fill this later)
/:cl:

2022-08-25 22:08 UTC, hal9000PR approved these changes

2022-08-25 22:08 UTC, hal9000PR commented on code/datums/status_effects/debuffs.dm
> +	latest_attacker = null
```suggestion
	latest_attacker = null

```

2022-08-25 22:08 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm
> +		. = ..()
```suggestion
	if(!G)
		L.apply_status_effect(STATUS_EFFECT_GROUNDPOUND, 1, src)
		return ..()
	if(G.add_stacks(stacks_added = 1, attacker = src))
		return ..()
```

2022-08-25 22:08 UTC, hal9000PR requested changes
missclick

2022-09-04 15:53 UTC, Sirryan2002 reviewed
I don't know enough about mob/megafauna/effects code to be much help here so here's a few formatting suggestions

2022-09-04 15:53 UTC, Sirryan2002 commented on code/modules/mining/equipment/kinetic_crusher.dm
> +			user.visible_message("<span class='warning'>[usr] dashes!</span>")
```suggestion
			user.visible_message("<span class='warning'>[user] dashes!</span>")
```

2022-09-04 15:53 UTC, Sirryan2002 commented on code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
> +	for(var/turf/t in getline(src,location))
```suggestion
	for(var/turf/t in getline(src, location))
```

2022-09-04 23:45 UTC, hal9000PR approved these changes

2022-09-05 00:11 UTC, merged