Moves chainsaw buff application to afterattack()
ParadiseSS13/Paradise pull request #18820
Opened 2022-08-15 02:03 UTC by Gatchapod

## What Does This PR Do
fixes #18787
Moves the actual application of the Syndicate chainsaw buff to `afterattack()` to prevent it from triggering on attempted surgery. This prevents exploiting it to maintain indefinite buff without harming anyone.
Removes some redundant code, like playing a sound effect for unwielded chainsaw, which is played anyway.
Slightly unintended, but sadly unavoidable, side-effect is that attempting a surgery on a valid target using a chainsaw will knock them prone for 8 seconds. I consider this an acceptable behaviour, given the fact this PR fixes an exploit. Attempting surgery with a Syndicate chainsaw is more likely to be a user error than actual intended choice, so it could even be considered a feature.

## Why It's Good For The Game
One less exploit is good.

## Testing
Spawned in with a bunch of greys.
Killed a standing grey using a Syndicate chainsaw on all four intents.
Successfully butchered the grey.
Buckled another grey to a roller bed.
Could perform surgery on help intent, both wielded and unwielded.
Could attack on the other three intents and successfully butchered the buckled grey on harm intent.
Could not get the buff from attacking robots, simple mobs and inanimate objects.
Successfully killed everything and destroyed whatever was meant to be destroyable.

## Changelog
:cl:
fix: Syndicate chainsaw no longer grants its buff upon attempting a surgery
/:cl:

2022-08-15 15:52 UTC, hal9000PR requested changes

2022-08-15 15:52 UTC, hal9000PR commented on code/game/objects/items/weapons/twohanded.dm
> +	return
dangling return is unneeded 
```suggestion
```

2022-08-15 15:52 UTC, hal9000PR commented on code/game/objects/items/weapons/twohanded.dm
> +	if(wielded)
make this an early return like the proximity check

2022-08-15 15:52 UTC, hal9000PR commented on code/game/objects/items/weapons/twohanded.dm
> +			return
this needs to early return if hitting a silicon as it does currently on master.

2022-08-15 15:52 UTC, hal9000PR commented on code/game/objects/items/weapons/twohanded.dm
> +	return
dangling return 
```suggestion
```

2022-08-15 17:12 UTC, Gatchapod commented
This is currently broken and doesn't even fix the exploit. Quite the opposite, now you can run around with a surgery window and trigger the buff at will by closing the window, making the exploit stronger. It also makes unwielded chainsaw incapable of harming living mobs, but that's an easily fixable oversight.
I'll think a bit more about how to approach this, but I'm close to just giving up.

2022-08-22 18:26 UTC, hal9000PR approved these changes

2022-08-22 22:06 UTC, merged