Clarifies that DNA injectors cannot be used with syringe guns
ParadiseSS13/Paradise pull request #18846
Opened 2022-08-17 03:44 UTC by GDNgit

## What Does This PR Do
Adds an alert and an examine message to the syringe gun, dart pistol, and the oldRSG stating that you cannot use DNA-Injectors with them.

Adds the line "Not compatible with DNA-Injectors." to the three syringe-based syringe guns 

Adds the alert text "[Syringe gun type] is incompatible with DNA-Injectors." Upon attempting to add a DNA-Injector to these weapons. 

Fixes #18844 

## Why It's Good For The Game
Injectors do look similar to syringes, and currently gives no feedback upon denying one from use. This adds visual feedback, so the player knows that this is intended behavior. 

## Testing
Compiled code and ran, attempted both interactions, text showed up when it should, attempted normal syringe interactions, correct text showed up and no behavior was altered. 

## Changelog
:cl:
spellcheck: Adds messages for the DNA-Injectors not being useable with the syringe gun 
/:cl:

2022-08-17 08:03 UTC, Sinestia requested changes

2022-08-17 08:03 UTC, Sinestia commented on code/modules/projectiles/guns/syringe_gun.dm
> +	desc = "A modification of the syringe gun design, using a rotating cylinder to store up to six syringes. Not compatible with DNA-Injectors"
forgot a period

2022-08-17 08:03 UTC, Sinestia commented on code/modules/projectiles/guns/syringe_gun.dm
> +	desc = "A small spring-loaded sidearm that functions identically to a syringe gun. Not compatible with DNA-Injectors"
same here

2022-08-17 16:15 UTC, GDNgit commented on code/modules/projectiles/guns/syringe_gun.dm
> +	desc = "A modification of the syringe gun design, using a rotating cylinder to store up to six syringes. Not compatible with DNA-Injectors"
Fixed

2022-08-17 16:15 UTC, GDNgit commented on code/modules/projectiles/guns/syringe_gun.dm
> +	desc = "A small spring-loaded sidearm that functions identically to a syringe gun. Not compatible with DNA-Injectors"
Fixed

2022-08-18 18:11 UTC, Sirryan2002 commented on code/modules/projectiles/guns/syringe_gun.dm
>  		return ..()
```suggestion
		return

	return ..()
```

2022-08-20 23:36 UTC, GDNgit commented on code/modules/projectiles/guns/syringe_gun.dm
>  		return ..()
Implemented

2022-08-23 20:46 UTC, Sirryan2002 approved these changes
code looks good

2022-08-25 15:37 UTC, hal9000PR approved these changes

2022-08-25 15:38 UTC, merged