Adds syndicate logo pencode
ParadiseSS13/Paradise pull request #18850
Opened 2022-08-18 12:37 UTC by S34NW

## What Does This PR Do
Adds a `[syndicatelogo]` pencode so nefarious individuals can make the syndie logo on papers/forms like they can with NT logo.

## Why It's Good For The Game
I don't know, roleplay? It's weird we don't have this when it can be used in a variety of situations (and pranks)

## Testing
Paper tests.
![image](https://user-images.githubusercontent.com/12197162/185396493-487bd711-0569-4ccc-97f1-7e92a98c3d20.png)

## Changelog
:cl:
add: Added [syndicatelogo] pencode to allow syndicate logo on paperwork
/:cl:

2022-08-18 15:28 UTC, AffectedArc07 requested changes
Pain

2022-08-18 15:28 UTC, AffectedArc07 commented on code/__HELPERS/text.dm
> +		text = replacetext(text, "\[syndielogo\]", 	"&ZeroWidthSpace;<img src = syndielogo.png>")
```suggestion
		text = replacetext(text, "\[logo\]",	"&ZeroWidthSpace;<img src='ntlogo.png'>")
		text = replacetext(text, "\[syndielogo\]", 	"&ZeroWidthSpace;<img src='syndielogo.png'>")
```

2022-08-18 22:50 UTC, Pckables commented
You have no idea how much I needed this a year ago when I was making a bunch of fun "Contractor Paperwork".
I spent 2-3 hours figuring out how to format ASCII art in SS13 just to make an "official" syndicate logo.

2022-08-19 10:45 UTC, AffectedArc07 approved these changes

2022-08-19 10:46 UTC, merged