Makes that Turbine Scrubbers no longer fight against Turbine itself
ParadiseSS13/Paradise pull request #18879
Opened 2022-08-21 19:10 UTC by NethIafin

## What Does This PR Do
Repositions Turbine Scrubber behind Turbine so that it no longer reduces pressure in the burn room, and instead scrubs exhaust if you want to do something fancy with it (like clean it out of CO2 and put it back into the burn room).

Also adds valve between Turbine Exhaust pipe and Turbine intake pipe on other stations (already exists on Cyberiad) so you can  put the exhaust back into intake (which never 100% burns so it still have 85% of old burn mix).

Optimization will still take time and effort, but no-brain "just mix 50-50 Plasma-Oxygen and let it burn" now produces 100kW instead of 60-70, and consumes stuff slower. Also fully upgraded Turbine gives 600kW.
Before to achieve that you needed to disable or unwrench that scrubber.

## Why It's Good For The Game
Turbine is rarely used and the scrubber action is really dumb and not in any way like it should be

## Images of changes
Should be autogenerated, will include later

## Testing
Start Box station. Spawn as Atmosian.
Go to atmos, max pumps from O2 to mix, and from Plasma to Mix.
Disable Mix to Scrubber pump, max Mix to Turbine Pump
Enable Mixer valve in Turbine, Enable and max all pumps except for Mix to Exhaust.
Ignite
See that it scrubs now behind the Turbine and there is a space behind Turbine where exhaust gas is collected instead of being immediately spaced.

## Changelog
:cl:
tweak: changed turbine exhaust and scrubber on all stations so that scrubber no longer fights against the turbine input and instead lets you reuse (and filter if you want) the unburned parts of exhaust
/:cl:

2022-08-21 20:28 UTC, NethIafin commented
do we keep the changes that DM automade for the Meta?

2022-08-24 20:19 UTC, Bm0n commented
> do we keep the changes that DM automade for the Meta?

Did you run mapmerger2?

Also, did you make this in SDMM or just normal DM?

2022-08-24 22:48 UTC, NethIafin commented
> > do we keep the changes that DM automade for the Meta?
> 
> Did you run mapmerger2 before committing?
> 
> Also, did you make this in SDMM or just normal DM?

I used normal DM
I did run mapmerger
Seems that DM doesn't like formatting in the Meta

2022-08-25 09:19 UTC, S34NW commented
I'd ideally like these pipes to finally be taken from under walls, but it does mean you'd have to use a scrubbers pipe and a universal adapter, alongside the regular normal pipe.

2022-08-25 09:21 UTC, S34NW commented on _maps/map_files/MetaStation/MetaStation.dmm
> -/mob/living/simple_animal/pet/dog/corgi/borgi,
You have unrelated inter-key changes on meta still, we do not want more key content shuffling.

2022-08-25 09:22 UTC, S34NW requested changes

2022-08-25 09:22 UTC, S34NW commented on _maps/map_files/MetaStation/MetaStation.dmm
> -	sensors = list("n2o_sensor"="Tank")
This needs to be reverted, the other maps are in this format and meta should not be any different.

2022-08-25 09:22 UTC, S34NW commented
> do we keep the changes that DM automade for the Meta?

No, the three maps should be in the same style/format

2022-08-25 11:09 UTC, NethIafin commented
reworked everything with SDMM

2022-08-25 15:17 UTC, S34NW approved these changes

2022-09-04 23:59 UTC, hal9000PR approved these changes

2022-09-05 00:12 UTC, merged