Adds config option to prevent repeating maps
ParadiseSS13/Paradise pull request #18950
Opened 2022-09-01 18:22 UTC by S34NW

## What Does This PR Do
Adds a config option that, when enabled, prevents the current map from showing up in the map vote options

## Why It's Good For The Game
More flexibility to allow different map rotation styles

## Testing
All i hear is the map vote noise now

## Changelog
:cl:
add: Added a config option to prevent repeating maps
/:cl:

2022-09-01 18:25 UTC, YoureNotTheSharpest commented
Do it

2022-09-01 18:25 UTC, Scribble-Sheep commented
Do it, u wont

2022-09-01 18:26 UTC, russetdapone commented
merge

2022-09-01 18:27 UTC, AffectedArc07 requested changes

2022-09-01 18:27 UTC, AffectedArc07 commented on code/controllers/configuration/sections/vote_configuration.dm
> +	var/non_repeating_maps = FALSE
Default this to true.

2022-09-01 18:29 UTC, S34NW commented on config/example/config.toml
> +non_repeating_maps = false
```suggestion
non_repeating_maps = true
```

2022-09-01 18:32 UTC, Samman166 commented
Forever box is dead 🦀

2022-09-06 00:01 UTC, Hematoma commented
I want to play but after three box rounds in a row it just hurts.

2022-09-06 09:20 UTC, hal9000PR approved these changes

2022-09-06 09:21 UTC, AffectedArc07 approved these changes
Seems fine but I reviewed this on a phone on a train so good luck.

2022-09-06 09:31 UTC, merged

2022-09-06 11:54 UTC, Scribble-Sheep commented
Omg he actually did it