BoxStation: Medbay Button
ParadiseSS13/Paradise pull request #19000
Opened 2022-09-09 00:39 UTC by DogeDogIs

Added again the button that opens all the medbay entrace doors again in BoxStation.

## What Does This PR Do

This PR add again the button that opens all the entrance doors in medbay. 

## Why It's Good For The Game

This can save a lot of time and it was in the old medbay, and almost everyone was using it. People can be let in quickly. 

## Images of changes

![image](https://user-images.githubusercontent.com/62888630/189248972-a92b61d0-fd32-42af-b1fa-69edf11f8eb8.png)

## Testing

Started dream deamon.
Local host server
Entered as CMO and clicked the button, it worked. 
## Changelog
:cl:
add: Added a button to open the medbay entrance doors.
/:cl:

2022-09-09 10:33 UTC, CinnamonSnowball commented
To be honest, this button is.. kind of extraneous? To click it, you need to be next to the airlocks anyway, so you might as well open them manually, you don't really save enough time for it to be a noteworthy factor.
Secondarily, this kind of button that opens all 3 airlocks at once already exists, in reception - speaking of which, don't think we should further disincentivize people from manning it, as it's already somewhat rarely done.

2022-09-09 17:01 UTC, LightFire53 requested changes
![image](https://user-images.githubusercontent.com/16112919/189402494-7c29ce69-9015-4f87-bf55-98d36ee830df.png)

This button will no longer work as the id is now `medbayfoyerport` compared to the button's current `MedbayFoyerPort`.

![image](https://user-images.githubusercontent.com/16112919/189402906-f48a2f17-1d7a-4132-baa2-d5b44c706959.png)

In addition, please move the light so it's not sharing a wall with the button or other wall furniture. 

As for it's need or lack of, I'm indifferent personally. It existed before, it's minor QOL. You still have the option of opening a single airlock if you wanted to, so.... ¯\_(ツ)_/¯

2022-09-12 09:46 UTC, S34NW commented
> Secondarily, this kind of button that opens all 3 airlocks at once already exists, in reception - speaking of which, don't think we should further disincentivize people from manning it, as it's already somewhat rarely done.

This TBH, the button already exists. Unsure of the benefit of putting one right next to the doors that you can just cick to open.

2022-09-22 01:04 UTC, SteelSlayer approved these changes

2022-09-22 01:40 UTC, merged