Ants will no longer spawn on food that is on racks
ParadiseSS13/Paradise pull request #19023
Opened 2022-09-11 06:27 UTC by Contrabang

## What Does This PR Do
Ants will now longer spawn on food that is stored on racks, similar to tables.

## Why It's Good For The Game
A LOT of people forget that racks do not count to keep food safe, which is weird because they act so similarly to tables for storing items. Being able to use rack to store food would be nice, without it being infested by ants.

## Testing

![image](https://user-images.githubusercontent.com/91113370/189515245-fb265f5b-6472-424e-90bb-286201a57142.png)
soup debugging. Tomato soup has no chance of spawning ants (as intented), soup on the ground may spawn ants (as intended).

## Changelog
:cl:
tweak: Ants will no longer spawn on food items that are on racks.
/:cl:

2022-09-11 12:26 UTC, hal9000PR requested changes

2022-09-11 12:26 UTC, hal9000PR commented on code/modules/food_and_drinks/food.dm
>  				if(!locate(/obj/effect/decal/cleanable/ants) in T)
would you make this an early return?

2022-09-11 23:56 UTC, Sirryan2002 commented on code/modules/food_and_drinks/food.dm
> +	var/ant_location = null // location checked every 5 minutes. If its the same place, the food has a chance to spawn ants
```suggestion
	var/ant_location // location checked every 5 minutes. If its the same place, the food has a chance to spawn ants
```

2022-09-12 14:35 UTC, Sirryan2002 commented on code/modules/food_and_drinks/food.dm
> +	if((locate(/obj/structure/table) in T) || (locate(/obj/structure/rack) in T) || !isturf(loc))
can you do the `!isturf()` check first just to save on searching the turf for tables/racks

2022-09-13 04:46 UTC, Sirryan2002 approved these changes
code looks good

2022-09-14 18:54 UTC, hal9000PR requested changes

2022-09-14 18:54 UTC, hal9000PR commented on code/modules/food_and_drinks/food.dm
> +	var/ant_location // location checked every 5 minutes. If its the same place, the food has a chance to spawn ants
```suggestion
	/// location checked every 5 minutes. If its the same place, the food has a chance to spawn ants
	var/ant_location
```

2022-09-22 01:45 UTC, SteelSlayer approved these changes

2022-09-22 01:58 UTC, merged