Adds an NNO-specific gas mask, the "nanotrasen navy officer gas mask".
ParadiseSS13/Paradise pull request #19081
Opened 2022-09-16 21:33 UTC by Miraviel

## What Does This PR Do

Adds a new NNO-specific gas mask, "nanotrasen navy officer gas mask".

The inventory icon is just a slight resprite of the warden mask.

## Why It's Good For The Game

I wanted to have a fitting gas mask for an NNO vox, and all the black masks are more grey than black - and the NNO uniforms are much darker than those. Figured all races could use this.

It is accessible via the chameleon projector.

## Images of changes

![image](https://user-images.githubusercontent.com/33333517/190780040-214e8b7b-a73d-4c67-8c21-baa84cdc336c.png)

![image](https://user-images.githubusercontent.com/33333517/190787075-115a1440-61a2-44e9-8922-9aed18b9bcf6.png)

## Testing

Made the screenshot above.

## Changelog
:cl:
add: Added "nanotrasen navy officer gas mask", a gas mask specifically for NNOs.
/:cl:

2022-09-16 22:02 UTC, Miraviel commented
Have to test the other races tomorrow, seeking feedback in the meantime.

2022-09-17 01:58 UTC, matttheficus commented
If you think I'm not using this with EVERY Chameleon mask you're grossly mistake 👀

2022-09-17 10:19 UTC, Miraviel commented
Done for all races, ready to be reviewed.

2022-09-17 19:29 UTC, Sirryan2002 approved these changes
Code and sprite diffs look good

2022-09-18 21:42 UTC, hal9000PR requested changes

2022-09-18 21:42 UTC, hal9000PR commented on code/modules/clothing/masks/gasmask.dm
> +	strip_delay = 60
```suggestion
	strip_delay = 6 SECONDS
```

2022-09-19 18:29 UTC, Komrad822 commented
> all races

Forgive me if im wrong but does Kidan need a sprite change for theirs? (would point out diona and plasmaman aswell)
Obviously this is only if there isnt a lore reason as to why they cant be NNO but idk >.>

>If you think I'm not using this with EVERY Chameleon mask you're grossly mistake
Also, same.

2022-09-20 14:11 UTC, Miraviel commented
> > all races
> 
> Forgive me if im wrong but does Kidan need a sprite change for theirs or missing out? (would point out diona aswell) Obviously this is only if there isnt a lore reason as to why they cant be NNO but idk >.>
> 

Diona and kidan use the same mask.dmi as humans, that's why there are no racial variants for them.

2022-09-25 16:32 UTC, AffectedArc07 approved these changes

2022-09-25 16:32 UTC, merged