Adds "Highlights" to the Orbit menu
ParadiseSS13/Paradise pull request #19168
Opened 2022-09-24 22:36 UTC by Contrabang

## What Does This PR Do
Adds "Highlighting" to the observer's orbit menu, if a living player is followed by more than 20% of all observers they'll show up on this menu. The antagonist menu is shown above this panel, for both administrators and antagHUD users.
I'm considering a preference option for this, but I only want to implement it if someone would want this off. Also, very flexible with this PR, constructive criticism is appreciated.

## Why It's Good For The Game
 Its annoying to have to search through this list if you want to constantly keep an eye on two things (like a nuke disc and a nukie, or two antagonists demolishing security). This is a nice quality of life for people who want to be able to swap between both of them.

Now, there may be some concern about how this could be misconstrued as an antag hud. All this does is highlights what is already in the menu and puts it at the top if the bar. If someone was going to metagame this, they could do it already with just a bit more effort before. Plus, ghosts may be orbiting someone as a non-antag, but is doing something interesting (see that assistant that keeps running himself into that grille? Hilarious!)

## Images of changes

![image](https://user-images.githubusercontent.com/91113370/192120662-b0fbd510-0281-4616-bbf5-224a424db95b.png)

## Testing

Spawned skrell, put a blank mind in skrell, orbited skrell, opened menu, skrell was on the menu (delicious).

## Changelog
:cl:
add: A new "Highlights" section has been added to the observer orbit menu, showing what other fellow observers are looking at.
/:cl:

2022-09-24 22:49 UTC, lewcc requested changes
I like the idea, just needs fixing with implementation details. I feel like there should already be a proc that handles getting observers, but then again that's always the case with these helper functions

2022-09-24 22:49 UTC, lewcc commented on code/modules/mob/dead/observer/orbit.dm
> +				if(length(orbiters) >= 0.2 * length(get_observers())) // They're important if 20% of observers are watching them
This outer loop already iterates over pretty much every mob, please call this `get_observers()` function before the loop.

2022-09-24 22:49 UTC, lewcc commented on code/modules/mob/dead/observer/orbit.dm
> +			if(length(orbiters) >= 0.2 * length(get_observers())) // If a bunch of people are orbiting an object, like the nuke disk.
same here.

2022-09-25 16:29 UTC, lewcc commented
One more thing, do you think you could sort this section by observer count? I think you might be able to do that on the js side, but it's been a while since I looked there.

2022-09-25 17:50 UTC, Contrabang commented
Yeah, I tried that to no such luck, I'm no TGUI wizard yet. I tried some stuff with .sort and stuff, but with the info being transfered a list inside of a list which contains the number we want to search for, I couldnt figure it out.

2022-10-02 04:49 UTC, Sirryan2002 approved these changes
code looks good

2022-10-03 20:39 UTC, SteelSlayer approved these changes

2022-10-03 20:41 UTC, SteelSlayer commented
Please rebuild TGUI to fix the conflict, then this can be merged.

2022-10-03 23:06 UTC, lewcc commented
Looks good to me

2022-10-03 23:59 UTC, lewcc approved these changes

2022-10-04 00:02 UTC, merged