(Attempt to) fix some Box issues.
ParadiseSS13/Paradise pull request #19213
Opened 2022-09-30 03:01 UTC by warriorstar-orion

## What Does This PR Do

This PR addresses what I believe to be issues with Box surfaced by the unit tests in https://github.com/ParadiseSS13/Paradise/pull/19204.

I'm uncertain about the changes for pipes/vents in atmos/scichem so let me know if they're not great fixes.
I'm also uncertain about which parts of the turbine actually need center nodes, so I kept both.

## Why It's Good For The Game

If these are all legit issues, then fixing them is good, and it makes it more likely that https://github.com/ParadiseSS13/Paradise/pull/19204 can get in alongside the tests it adds.

## Images of changes

Not all of these have before and afters, in the cases where the fix was rote.

### Multiple center cable nodes

171,50 maints rage cage
![paradise dme  cyberiad dmm  - StrongDMM-22_31_46](https://user-images.githubusercontent.com/59303604/193179195-5675b1d5-56e2-4e2b-9a39-f6f5e684e459.png)

152,56 turbine
![paradise dme  cyberiad dmm  - StrongDMM-22_33_38](https://user-images.githubusercontent.com/59303604/193179248-57e10f88-d47e-45b8-bddb-69e895a149c3.png)

79-85,152 vault electrified grilles
![paradise dme  cyberiad dmm  - StrongDMM-22_35_11](https://user-images.githubusercontent.com/59303604/193179325-d069c248-f344-4695-b4b2-569f62d165c4.png)

183,154 eng maintenance 

![paradise dme  cyberiad dmm  - StrongDMM-22_50_56](https://user-images.githubusercontent.com/59303604/193179757-de84e0a7-4fa7-4eba-b087-0f4d1c045831.png)

Before (computer removed for clarity):
![paradise dme  cyberiad dmm  - StrongDMM-22_38_02](https://user-images.githubusercontent.com/59303604/193179461-0848c9d8-f18a-49da-887b-8cb8e36022b8.png)
After:

![paradise dme  cyberiad dmm  - StrongDMM-22_49_57](https://user-images.githubusercontent.com/59303604/193179681-27431095-12cf-42aa-982f-d2fdb4f915d4.png)

### Pipes overlapping vents/scrubbers/ports/injectors

127,89 atmos

Before (lockers removed for clarity):

![paradise dme  cyberiad dmm  - StrongDMM-22_24_52](https://user-images.githubusercontent.com/59303604/193179851-df206847-026a-4d56-bf7e-c3a5ba489cc1.png)
After:
![paradise dme  cyberiad dmm  - StrongDMM-22_26_00](https://user-images.githubusercontent.com/59303604/193179869-872f709b-dd11-4e7c-99be-140915e8899f.png)

205,106 scichem
Before:
![paradise dme  cyberiad dmm  - StrongDMM-22_55_01](https://user-images.githubusercontent.com/59303604/193180572-1f9ebf12-1861-4b1c-9119-69c99eb5d8ec.png)
After:
![paradise dme  cyberiad dmm  - StrongDMM-22_54_17](https://user-images.githubusercontent.com/59303604/193180650-9af7c23a-19e8-450d-a140-9de128e2e930.png)

## Testing

Ran unit tests.

## Changelog
:cl:
fix: Small Meta fixes.
/:cl:

2022-10-10 08:27 UTC, S34NW requested changes
Changelog says meta.

Also, elec maints needs wires under walls fixed at some point, not in-scope for your PR though.

2022-10-10 15:08 UTC, warriorstar-orion commented
> Changelog says meta.
> 
> Also, elec maints needs wires under walls fixed at some point, not in-scope for your PR though.

Whoops! Fixed.

2022-10-10 16:47 UTC, S34NW approved these changes

2022-10-15 03:17 UTC, SteelSlayer approved these changes

2022-10-15 03:23 UTC, merged