Adds wedding/costume/bloody armor crates and other tweaks
ParadiseSS13/Paradise pull request #19231
Opened 2022-10-01 16:40 UTC by Henri215

## What Does This PR Do

Makes a non super hero version of E-N suit.
Changed costume crate name to "Service Costume crate".
Added Costume crate (30 points), Wedding crate (50 points), Bloody armor crate (contraband,80 points).
Tweaks Justice crate by adding 1 helmet justice escape variation.
Contents at images of changes.
Suggestions of items to be added or removed are welcome.
## Why It's Good For The Game

Its good because gives usage to items that only existed in code and that could be used as new crates contents.
A benefit of adding the bloody armor crate is to give more options for the cargo console contraband setting (wich currently only has 2 crates).

## Images of changes

Costume crate (minus the salmon suit, has been removed)
![costume crate](https://user-images.githubusercontent.com/77684085/193418478-ea1ae7fe-36f3-4b61-82e6-1d971f71f460.png)

Wedding crate
![weddingcrate](https://user-images.githubusercontent.com/77684085/193418485-6ea17ef1-7bbf-49f7-9188-e13b1d97c097.png)

Bloody Armor crate
![bloodyarmor](https://user-images.githubusercontent.com/77684085/193418476-90adb989-fad6-45e1-8457-6da585a2e483.png)

Justice crate
![justice crate](https://user-images.githubusercontent.com/77684085/193418481-532d9ec3-daf5-4c4c-881e-54432a3adbd9.png)

## Testing

- Ordered the crates and verified the contents.
## Changelog
:cl:
add: Added costume and wedding crates
add: Added bloody armor crate as contraband
add: Added justice helmet variation to standard justice enforcer crate
tweak: Old costume crate renamed to "service costume crate"
/:cl:

2022-10-01 17:01 UTC, ElorgRHG commented
**Soul**

but anyways, the wedding, costume stuff and adding that random justice helmet rename are all fine,
the bloody vest and lord admiral stuff are... 

They're... not great and should be slated for removal rather than put front and center like this. They also do not have species variants so will look likewise pretty bad on less humanoid species, mainly vox. 

And adding just a, opinion time, worse looking vest, sprite quality wise and onmob security wise, crate that's 80 points that's ALSO in the contraband section and will come in a locked box...  that's an interesting decision
<details>

![image](https://user-images.githubusercontent.com/71735193/193419992-45dc19c6-a903-47ce-aae2-1698add4a914.png)

![image](https://user-images.githubusercontent.com/71735193/193420059-ab194e06-f62c-4a10-8de4-8a91c42ecf71.png)

</details>

then again, aspriring spriters yells at cloud so whatever.

2022-10-04 20:33 UTC, Sirryan2002 reviewed
I worry this will contribute to supply pack bloat, at some point we need to start breaking up the security and misc sections, they both have like 10-20 crates

2022-10-04 20:33 UTC, Sirryan2002 commented on code/datums/supplypacks.dm
> +	contraband = 1
```suggestion
	contraband = TRUE
```

2022-10-04 21:08 UTC, Sirryan2002 approved these changes
code is fine

2022-11-22 04:24 UTC, SteelSlayer requested changes

2022-11-22 04:24 UTC, SteelSlayer commented on code/modules/clothing/head/misc.dm
> +
This seems to be already defined under a different path:

![image](https://user-images.githubusercontent.com/42044220/203220744-67331632-0e28-43b4-9ca5-42258d1c2e6b.png)

2022-11-22 04:24 UTC, SteelSlayer commented on code/modules/clothing/suits/miscellaneous.dm
> +
Same here:

![image](https://user-images.githubusercontent.com/42044220/203220903-3317a5ed-d921-4f5e-8cca-997734c43944.png)

2022-11-22 04:31 UTC, SteelSlayer approved these changes

2022-11-22 04:43 UTC, merged