Magistrate deskside office door button
ParadiseSS13/Paradise pull request #19268
Opened 2022-10-03 21:31 UTC by procdrone

## What Does This PR Do
It adds convenience for the magistrate. Now, his front doors have a deskside door button and a window tint button. front doors are also glassed and tinted.

## Why It's Good For The Game
All other Heads and VIPs get this, Magistrate should too.

## Images of changes
Box:
![1](https://user-images.githubusercontent.com/46283583/193686592-46003f68-9dc5-4864-b97c-2ea9a02cafd7.PNG)
Delta:
![2](https://user-images.githubusercontent.com/46283583/193686787-5a0480f5-321c-436e-b844-be7c2a2b2919.PNG)
Meta:
![3](https://user-images.githubusercontent.com/46283583/193686830-87a4f089-7e0a-4aa1-8272-2dd3e32d2631.PNG)

## Testing
Launched every map through test server, joined as Magi, went to the office and tested the buttons.

## Changelog
:cl:
add: Added an office button to the magistrate's office, front doors are now glassed and tinted.
/:cl:

2022-10-03 21:38 UTC, procdrone commented
I messed up the offset on the buttons on meta station, updated now:
![4](https://user-images.githubusercontent.com/46283583/193689928-25c99f36-f4d1-44f7-9da4-512738aac80f.PNG)

2022-10-03 21:57 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/193693190-107260cf-2752-4d5c-9b0b-8b8c433101b0.png)
Please use glass subtypes, not var editing non-glass airlocks

![image](https://user-images.githubusercontent.com/12197162/193693351-9618b219-6635-4537-92b1-b30b1c4eb86f.png)

2022-10-03 22:43 UTC, procdrone commented
updated, as per request 🙏

2022-10-07 08:49 UTC, S34NW approved these changes

2022-10-15 16:45 UTC, SteelSlayer approved these changes

2022-10-15 16:45 UTC, merged