Fixes some Issues with Delta
ParadiseSS13/Paradise pull request #19281
Opened 2022-10-04 15:06 UTC by Contrabang

## What Does This PR Do
 Fixes #19235, Fixes #19228

ERT Shuttle now unbolts when it arrives and bolts when it departs.
Jetpack and Magboots are now properly locked behind EVA Access, while the RCD crate is locked behind ACCESS_CONSTRUCTION access.

## Why It's Good For The Game
 Fixing issues is good

## Images of changes
 Nothing physically changed, just var edits.

## Testing

Opened game, ERT Shuttle works, EVA windoors have proper access.

## Changelog
:cl:
fix: ERT shuttle now properly docks with Delta
fix: Delta's EVA Windoors now have proper access.
/:cl:

2022-10-04 15:23 UTC, hal9000PR commented
would you convert the doors to using access door helpers instead of VVs?

2022-10-10 08:34 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/194826535-2fe54392-8e6e-4720-a920-e85881378400.png)

The top set of doors in this image also need adjusting with the `"ferry_home"` id_tag var

2022-10-10 17:42 UTC, S34NW approved these changes

2022-10-15 17:16 UTC, SteelSlayer approved these changes

2022-10-15 17:17 UTC, merged