Syndicate spacebase overhaul
ParadiseSS13/Paradise pull request #19293
Opened 2022-10-05 18:48 UTC by radarseas

**todo**

- [ ] optimise the map a bit more, it still has a fair bit of stuff laying around that needs a cleanup.
- [ ] - [ ] optimise the map a bit more, it still has a fair bit of stuff laying around that needs a cleanup.
- [ ] - [ ] optimise the map a bit more, it still has a fair bit of stuff laying around that needs a cleanup.

## What Does This PR Do

A complete rework of the syndicate space base, including several of the following and more*

- a better redesign, using FOV and other means to limit vision slightly while not making it too crammed to give the old-paranoia feel the lavaland base had once again, even including bulbs instead of tubes outside of the medical bay, it _really really_ does have that bunker in the middle of _**nowhere**_ feel now.
- a better stocked engineering department, with its own crate of suits outside of the armory and magboots for dealing with **REALLY** bad breaches and plasmafires, plus an extra holofan for a bit more experimentation, this one is near the canisters to encourage pre-emptively avoiding mistakes.
- more vendors and maintenance fungus to encourage people to learn about more of the lesser known reagents as well as giving experienced players more to work with, on top of a more occupied and lived in feel.
- a split up of the botany and bar design, it feels more spacious now instead of crammed, even the kitchen was reworked to not fit in more as a permanent looking kitchen than a few tables and a bunch of vendors stacked on top.
- a secret mime costume and expanded tactical clowning gear. **HONK!**
- an expanded communcations office, even complete with a photocopier, syndicate stamp **and** tactical bunny... no don't think of printing your ass on it agent, we've already _conveniently_ pre-emptively emagged it, _we know you too well.._
- authentic-grade plastainium glass windows, because we _**simply can**_ afford it, unlike nanotrasen bargin bin design, the syndicate cares about the looks and practicality more. (_sometimes_).
- a better stocked custordial closet, complete with signs to point at when people inevitably try to murder you for slipping them, galoshes for waddling away laughing at them while they flail around trying to shoot you and a biosuit to boot!
- a forensics and autopsy scanner by the range, for a complete _**murder and get away with it training**_ or for the ace detective to be! actual crime not included or encouraged!
- a beer nuke we have shamely stolen from nanotrasen and stuffed in maintenance without even bothering to change the design, simply because we at the syndicate _**can**_, and _**we will.**_

## Why It's Good For The Game

I'll be honest, the syndicate space base was a pretty neat idea, its out of the way unlike lavaland, its got a good concept in mind, catering for newbies and some experienced players alike to dabble with some minor atmos as well as chemical reagents with a way to ask for additional stuff from admins.

but uhhh- it felt kind of bland, very focused on mechanics over anything related to RP and some of the design just didn't click right, such as the reinforced glass on plastainium, the bar and botany being one open combined area with the kitchen just crammed in.

having six slots only that don't refill over the course of a long round combined with lack of armor vests to test against armored individuals, such as security officers, which you may want to be making chem grenades to deal with since, as an antag, you're primarily fighting security anyway.

some of the cargo gear and armory gear was massively redundant, since the agents just spawn with seclites now, plus they already have turtlenecks and syndicate masks from spawn, having extras rarely means much, and if they do somehow melt their mask, there are still fire lockers with gasmasks for them to take, which there are more of now.

plus for a newbie friendly area, I thought I might as well slap in a few things you don't see often like a forensic scanner and autopsy scanner, as it turns out stealth traitoring is difficult, moreso when you're a new player looking to dabble and expand your methods when its so easy to get caught and arrested for most of the round, especally with contraband, or perhaps even run a gimmic with it, for the sake of RP, make a murder scene and try and get someone to figure it out on the outfit, a whole lot potental.

to compliment this, I've added nitriles to medical and viro, both for the sake of RP with more sterile gloves and for the sake of teaching people how to use nitriles to avoid prints effectively, as well as further encouraging detective work.

while not having a disposal system already setup may have encouraged newbies to build one themselves, or experienced players to do so, it usually made the base experience worse as you'd spent a lot of time just running over to throw stuff away or half of the round building it only for it not to matter, time and time again.

the aesthetic of the base has been given a massive overhaul with a bit more grime and dirt feeling more lived in, maintenance areas that are worn down, using bulb lighting outside of medical, botany, bar, kitchen and medical to give the base a more, darker feel making it seem more like the hostile military bunker inside of the rock that it is than just an empty generic research facility, especally if you intrude into it, since the agents inside are more geared and armed now.

it has clothing vendors and costume vendors to encourage varity and outfit style as well as keeping the experience fresh each time around as well as encouraging new players to dabble in the art of style-fu.

hopefully this new redesign should appeal to players new and old! as well as breathing a lot of life into the place for the foreseeable future, as well as adding some more stuff that newer players probably don't even know exists like the autopsy scanner to mess with.

## Images of changes

![2022 10 05-18 27 05](https://user-images.githubusercontent.com/109446367/194133544-8380fc17-d1e3-44b5-8d1a-01e6a31ec2c5.png)

## Testing

- by loading up the map time and time again in dreamseeker, adjusting the lighting to get it picture perfect as well as running around trying to get to every single room as well as making sure that the spasebase spawned correctly.
- spawning in a killbot and letting it pass the animals and not kill them.
- using the barsign with the default researcher IDs from spawning in as one and being able to alter it, then throwing the ID on the floor and being unable to use it without ID, picking it up again and once more being able to alter it.

## Changelog
:cl:
add: A completely new design on top of the old syndicate base, including extra gear, maintenance tunnels, a cute rabbit, extra office equipment, a more functional kitchen, a full-disposals system, a better stocked armory, more thematic lighting and even a photocopier, don't try to assfax the syndicate, they've already pre-emptively modified it to disencourage such...
del: redundant armory gear like the turtlenecks and masks that researchers already spawn with as well as the fire extingisher and flashlight crate.
tweak: basic medical huds have been swapped out for night vision ones because the syndicate are simply too tacticool to acknowledge those exist in any shape or form.
tweak: Completely reworked the syndicate base's overall layout.
tweak: Increased the amount of ghost role slots from 6 to 9 to make up for the redesign increasing the space, as well as keeping the base usable over the course of a long round with a lot of signups and cryoing.
fix: The animals in the syndicate space biolab now use the syndicate faction so that adminspawned syndicate faction hostile mobs don't murder them all, like syndicate patrol bots.
fix: The bar sign actually uses the correct ID, that syndicate agent IDs have, instead of barkeep access.
fix: The booze taps now face the right direction instead of towards the wall at roundstart until someone corrects it, rejoice!
experimen [...]

2022-10-05 18:54 UTC, S34NW commented
I like this, but I don't know if the syndicate secret forward operating base would have a fully equipped barbershop that takes up more floorspace than their chem labs

2022-10-05 19:28 UTC, radarseas commented
> I like this, but I don't know if the syndicate secret forward operating base would have a fully equipped barbershop that takes up more floorspace than their chem labs Edit: 9 players is too many for this ruin, even with changes. 6 i feel was a good point.

that is a good point on the barbershop, I'll probably see to nudging viro and medical to the left a bit and expanding those labs with a touchup as well as knocking the barbershop down a tiny nudge to keep the top of the base flat, I don't want to tamper with moving the range since it tends to get maxcapped **_breaching the asteroid wide open_** and I want to avoid the risk of breaches to the outside as much as possible.

as for the player count, usually it sits around 3-4 players average when people sign up, only really spiking during events, long extended rounds or maybe when the rare intruder breaks in and the inevitable congaline of agents run out of cryo to kill or capture them.

I might nudge it down to 8, trying to keep it somewhat able to stay mid populated throughout rounds where people disconnect or cryo out without overdoing it as well as letting a few more people experiment at once. but it _shouldn't be too_ overpopulated on average, outside of exceptional cases like above, where it spikes into syndie central.

2022-10-05 20:29 UTC, Henri215 commented
Changelog is too big, you dont have to describe every little thing there

2022-10-05 20:48 UTC, radarseas commented
good point, I'll snip it down.

2022-10-05 22:32 UTC, DogeDogIs commented
![image](https://user-images.githubusercontent.com/62888630/194175825-70a3d327-48fa-4dfd-9229-9e64fa87467d.png)

Pipes running over vents and scrubbers is not good

2022-10-05 22:50 UTC, DogeDogIs commented
![image](https://user-images.githubusercontent.com/62888630/194176451-218c69d5-185b-44c6-8d41-06d2dff8ab17.png)

Random cable and pipes touching the walls and both APCs and vents/srubbers are not connected to wires and pipes inside the viro and med room.

![image](https://user-images.githubusercontent.com/62888630/194177152-050deb55-2e92-45ce-aef8-0fd265836bc3.png)
![image](https://user-images.githubusercontent.com/62888630/194177506-dee18161-0a32-4213-be64-a349bcddbb3b.png)

I do not recomend putting walls like unless is very necessary to make it, make it just one tile wall 

![image](https://user-images.githubusercontent.com/62888630/194177265-ade1ab9a-d2a6-4298-8481-18d051844009.png)

I feel that is better putting the vent there with a bent pipe 

![image](https://user-images.githubusercontent.com/62888630/194177692-adc7d084-63fd-4768-8c67-87d34eea0acb.png)

It should have windows here? If no I guess that window door is not necessay.

I am not a map master but I try to help :)

2022-10-10 08:41 UTC, S34NW requested changes
![image](https://user-images.githubusercontent.com/12197162/194827738-9134bf91-3740-4322-9eb8-6b2e1ad8158e.png)
Missing scrubber pipe, red cable run turns into yellow cable run randomly.

![image](https://user-images.githubusercontent.com/12197162/194827807-b8f4cf1e-24f0-40b9-ac59-7c5c44cc4006.png)
This power cable has been pixel bumped.

![image](https://user-images.githubusercontent.com/12197162/194827910-a437c2bf-832d-4d75-b7fb-3fe743225659.png)
You have a lot of duplicate cable instances with the redundant `tag` variables, please clean them up.

![image](https://user-images.githubusercontent.com/12197162/194828044-14a83694-b52c-474e-ab71-0edecf30fd19.png)
You have duplicate pipe instances with the redundant `initialize_directions` variable.

![image](https://user-images.githubusercontent.com/12197162/194828147-4f708354-7ee7-4671-a675-10bcf74e756d.png)
![image](https://user-images.githubusercontent.com/12197162/194828172-ef867ffd-c16a-4018-9f8e-218ea5656e27.png)

Please try to space these out at least somewhat, to improve the room air flow.

![image](https://user-images.githubusercontent.com/12197162/194828446-e863fbcc-9984-494c-9d36-6d5befde547e.png)
These have a subtype that flips them around to push against the wall, please use it

![image](https://user-images.githubusercontent.com/12197162/194828605-539ee96e-f1d9-40ae-bfa8-1c0b68b32a4a.png)
This should be on the wall to the room, not an external wall

![image](https://user-images.githubusercontent.com/12197162/194828975-94db831a-0589-4720-a0ef-0b24927de3d3.png)
These are not aligned

![image](https://user-images.githubusercontent.com/12197162/194829562-42f33202-a464-4ba0-95a7-4cb0e88a0dad.png)
This room is too "busy", there are multiple different colour schemes and such that make it visually hard to look at, I count 6 different floor types visible from the room, 3 different table types, and a host of random tat including a bottler that is sat on the floor.


Please also add syndie fire alarms, they are strangely absent despite the use of firelocks

2022-10-10 08:54 UTC, S34NW commented
In addition to the above, please remember that this is a clandestine research outpost, not a lavish and well-furnished hub of activity.
Rooms should be spartan, luxuries such as nice carpets, fancy tables, overly-stocked and furnished barber shops, etc. should be kept to a minimum.
This outpost is currently too lavish and too well equipped with luxuries, you might need to scale back on on the non-essentials to keep the theme intact.
I am a big fan of QoL changes and additional mechanics for new players to experiment with in relative safety, but I do feel there has been a bit of creep in terms of redundant items.

2022-10-10 17:24 UTC, S34NW commented
> as for the bottler, I added it with experimentation in mind so people can experiment with lesser-used bottler chems, which have some very interesting effects that very few people actually see in action, like Apple-pocalypse or Blackeye Brew. mostly to encourage more experienced players to give the base a shot and opening up more reagent varity, same as the design idea behind adding the changs vendor and the soda vendor which has extra regents with hacked, since thirteen loko cans _aren't pure thirteen_.

The bottler was fine, don't get me wrong. It's just that it was not on a table :P

2022-10-11 09:14 UTC, S34NW requested changes
Your branch has conflicts due to https://github.com/ParadiseSS13/Paradise/pull/19192
Your changes mostly overwrite that PR, so when you resolve conflicts please double check to ensure you have reflected the changes made in that PR where relevant. (Namely: animal factions, stamp addition, crates to racks in certain places, keg changes)

See https://hackmd.io/@tgstation/ry4-gbKH5#Assured-Merge-Conflict-Resolution for help with merge conflict resolution

2022-10-11 20:22 UTC, closed without merging

2022-10-11 20:25 UTC, radarseas commented
ack I broke something, one second- fuck

2022-10-11 20:31 UTC, radarseas commented
I actually don't know what I just did but I managed to break everything trying to fix it, I underestimate my utter stupidity.

2022-10-11 20:48 UTC, SteelSlayer commented
You don't need to close a PR in order to make changes to it/fix conflicts by the way. And in fact I would recommend against it because weird stuff can happen.

2022-10-11 20:48 UTC, radarseas commented
yeah, git desktop somehow merged the entirety of para into the branch, I'll probably have to make a few one.