Fixes engine monitor having the wrong circuit board when deconstructed
ParadiseSS13/Paradise pull request #19307
Opened 2022-10-06 17:50 UTC by Henri215

## What Does This PR Do

Turns the engine monitor into a proper item.
## Why It's Good For The Game

If you deconstruct the engine monitor it will have the telescreen circuit board (wich has all cameras access), it should be the engine monitor circuit board.

## Testing

- Deconstructed the engine monitor, it has the correct circuit board now.
## Changelog
:cl:
fix: Engine monitor now has the correct circuit board when deconstructed
/:cl:

2022-10-10 09:05 UTC, S34NW approved these changes
Map edits seem fine to me

2022-10-15 17:28 UTC, SteelSlayer requested changes
Can you make this computer and all the others you added below have lowercase names?

2022-10-15 17:28 UTC, SteelSlayer commented on code/game/machinery/computer/camera.dm
> +	name = "Engine Monitor"
```suggestion
/obj/machinery/computer/security/telescreen/engine
	name = "engine monitor"
```

2022-10-15 17:46 UTC, SteelSlayer approved these changes

2022-10-15 17:51 UTC, merged