[WIP] Reworks block chance into Parrying.
ParadiseSS13/Paradise pull request #19334
Opened 2022-10-09 15:30 UTC by hal9000PR

## What Does This PR Do
Adds a parrying component.
no block chance has actually been converted yet. I need to settle on numbers.

now, instead of blocking with an item, you will **resist** while holding an item that can block, this will raise your guard. 

your guard will be raised for a duration. if you get hit during this duration, one of two things can happen.

Either, the time since you parried is lower than the perfect parry window, and then you will block the attack completely. [and stagger whoever attacked you (WIP)]

Or, the time since you parried is greater than the perfect parry window, then you will take a small amount of stamina damage, the amount of stamina damage is relative to time since you parried, the quality of the blocking item and the damage the item would have dealt.

I also decreased the resist cooldown as I dont see a reason why resisting should prevent you from acting for 2 full seconds. 
I might make it use its own unique button instead of resist.

## Why It's Good For The Game
Shields have been in a poor state for a long time.

they take zero skill to use and effectively double your health (on average), something about them needs changing, and this will be a fun experiment to see how people perform with it. 

Making shields take skill to use means that you are rewarded for being good at using a shield. but you can also be heavily punished for using it poorly. 

## Testing
needs more testing

## Changelog
:cl:
experiment: WIP
/:cl:

2022-10-12 02:10 UTC, Leanfrog commented
So, is this _just_ shields? Changing them is definitely a step in the right direction but I wonder how other passive block chance items will be handled, for example the various chaplain weapons and eswords, in particular the eswords as they already have an in hand use in the form of turning them on or off.

2022-10-12 19:26 UTC, trololiver112 commented
nice

2022-10-13 20:34 UTC, Qwertytoforty commented on code/game/objects/items/weapons/shields.dm
> +
Did you mean /obj/item/shield/energy/add_parry_component() ?

2022-10-13 23:18 UTC, Qwertytoforty commented
cursed katana / pyro gloves do not block. 
Cursed should block only melee, pyro should block all.

2022-10-13 23:24 UTC, AzuleUtama commented
From testing on mentorbox:

- Already ID'd as a bug, but it blocks most magic attacks which it really shouldn't do.
- Some kind of sound or visual cue for when you activate the parry or drop your parry after attacking would be nice, but not a priority.
- Armor penetration needs to be factored in, we discussed either flat stamina damage bonus or leaking damage through the block.
- Cooldown between resists is also needed, as you can spam and block literally everything thrown at you - should be rewarded for timing it well instead.
- Should it be less/ineffective if you're crawling as well?
- Should projectiles with an 'explosive' effect (BSG, rocket, frag-12 etc.) bypass the block entirely?

2022-10-20 00:00 UTC, SteelSlayer reviewed
Everything looks fine, but the use of `GetComponent` is what I'd like to avoid if possible, and so far I've failed to come up with a solution to replace it's use with signals. I'm aware that we have a lot of components that use it but it's not good practice, since signals should be the only way things interact with components (the guide to signals/components goes into this into more detail).

2022-10-20 20:51 UTC, AzuleUtama commented
From more testing:

- Spamming is less effective than before.
- Not sure if it's intended, but all mobs can see if you're parrying with the little animation that plays on your character.
- Seems to no longer block all magic projectiles now (wands, staffs, meat hook etc.).
- Cursed katana still doesn't block anything.
- Projectiles that pass through mobs and structures (xray, penetrator rounds etc.) can be blocked - but keep going through the mob despite doing no damage.
- There is a massive difference now with anything that's armor piercing. You can block a carp user all day long, but easily go down with about 4-5 AP stechkin rounds.
- Anything that has an "effect on hit" such as immolator beams will prevent the effect so long as it's blocked.
- Cling tentacle can be blocked regardless of the intent when fired.
- Rockets cannot be blocked.
- Ranged holoparasite/guardians crystal spray attack cannot be blocked at all - regular melee can.
- Pulse rifle can easily be blocked without much stamina loss, probably due to lack of AP.

2022-10-28 16:01 UTC, Somniworld commented
I've unironically been looking forward to something like for a while now, super glad someone more talented than I is working on it!

When you mean "resist", will it mean the *resist* button that is currently in the game (and which I do not remember having a cooldown, hence my confusion)? If that is so, how will it handle being buckled / resisting out of a grab, will it prevent you from getting out of a chair fast, or prevent from blocking while doing that?

Either way, looking forward to this being added!

2022-10-30 00:40 UTC, LordMadness commented
Will the Captain's Rapier, Energy Sword and Double Energy Sword (etc) melee blocks also be turned into Parry?
Because if so, it's a pretty rough nerf.

I get the point that the current block takes no skill, but the Desword is 16TC item.
With the passive buff gone, which, like it or not is a big reason for its cost- What can we expect for these items?
It'd be rather cool if the cost went down and maybe add the energy shield to the Uplink?

2022-10-30 09:35 UTC, hal9000PR commented
> What can we expect for these items?

I would be happy with a follow up pr that tweaks the values of the esword.

2022-11-08 23:37 UTC, hal9000PR commented
after some feedback I have increased the cooldown and reduced the parry window. to help prevent people just spamming it.

2022-11-09 16:35 UTC, SteelSlayer approved these changes
GetComponent shall live, for now

2022-11-10 20:22 UTC, farie82 approved these changes
Minor styling things. Looks good otherwise

2022-11-10 20:22 UTC, farie82 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	if((right_hand_parry && left_hand_parry))
```suggestion
	if(right_hand_parry && left_hand_parry)
```

2022-11-10 20:22 UTC, farie82 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	return (right_hand_parry && right_hand_parry.parent) || (left_hand_parry && left_hand_parry.parent) // parry with whichever hand has an item that can parry
```suggestion
	return right_hand_parry?.parent || left_hand_parry?.parent // parry with whichever hand has an item that can parry
```

2022-11-10 20:22 UTC, farie82 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	if(shield && shield.hit_reaction(src, AM, attack_text, 0, damage, attack_type))
```suggestion
	if(shield?.hit_reaction(src, AM, attack_text, 0, damage, attack_type))
```

2022-11-10 20:30 UTC, farie82 requested changes

2022-11-10 20:30 UTC, farie82 commented on code/datums/components/parry.dm
> +	RegisterSignal(parent, COMSIG_ITEM_EQUIPPED, .proc/equipped)
Whoops missed these

2022-11-12 00:44 UTC, hal9000PR commented
UPDATE TWO:
Decreased the parry window further, 1 Second now. increased the cooldown based on the OLD BLOCKCHANCE OF THE ITEM.
if a weapon had a 75% block chance, it has a maximum parry uptime of 75%, 50% blockchance? 50% uptime. etc. 

Training wheels are off.

2022-11-12 07:48 UTC, farie82 approved these changes

2022-11-12 07:49 UTC, merged