Makes cult spear not an instant stun.
ParadiseSS13/Paradise pull request #19343
Opened 2022-10-10 14:09 UTC by Qwertytoforty

## What Does This PR Do

Cult spear no longer instant stuns and does 40 damage.

It now does 30 damage, and marks a person similar to cult spell. If it hits a person who was cult marked, it will trigger the stun.

Recall of the spear has been improved, and will hit threats on the way back that are lying down, or go into a knocked down cultist hand.

## Why It's Good For The Game

A 6 second instant stun is not great. A cult knockdown spell / mark trigger is much better, 

Recall is good if you miss a throw, or as a trap, but could use a bit of help. Adding undodgeable to the throw flag on recall means it will go into the hand more consistently, or can be used to trigger marks, if you want to give up the 150 blood spear.

## Testing

Spawned in.
Confirmed damage was correct
Confirmed it marked on hit.
Confirmed recall worked on user if lying down.
Confirmed recall worked on knocked down victims.
Confirm it triggered mark.

## Changelog
:cl:
tweak: Cult spear now marks or applies the cult stun effect to a person on hit, instead of weakening them for 6 seconds. Also does less damage on throw, and recall action is more reliable.
/:cl:

2022-10-10 14:50 UTC, FloFluoro commented
Probably doesn't need to be said, but this advances #18179 (and is the last thing left on the list!)

2022-10-12 18:17 UTC, farie82 reviewed
Few small things. Looks good otherwise

2022-10-12 18:17 UTC, farie82 commented on code/game/gamemodes/cult/cult_items.dm
> +				var/datum/status_effect/cult_stun_mark/S = L.has_status_effect(STATUS_EFFECT_CULT_STUN)
Can you make this into an early return?

2022-10-12 18:17 UTC, farie82 commented on code/game/gamemodes/cult/cult_items.dm
> +				if(S)
Same here

2022-10-12 18:17 UTC, farie82 commented on code/game/gamemodes/cult/cult_items.dm
> +					if(issilicon(hit_atom))
```suggestion
					if(issilicon(L))
```
best to use your most recent cast to avoid confusion

2022-10-12 18:17 UTC, farie82 commented on code/game/gamemodes/cult/cult_items.dm
> +					else if(iscarbon(hit_atom))
```suggestion
					else if(iscarbon(L))
```

2022-10-14 23:25 UTC, hal9000PR requested changes

2022-10-14 23:25 UTC, hal9000PR commented on code/game/gamemodes/cult/cult_items.dm
> +						B.emp_act(EMP_HEAVY)
emp act is defined on L, so there is no need to typecast it.

2022-10-14 23:25 UTC, hal9000PR commented on code/game/gamemodes/cult/cult_items.dm
> +						C.Jitter(16 SECONDS)
same here. no need to typecast

2022-10-29 16:30 UTC, Qwertytoforty commented on code/game/gamemodes/cult/cult_items.dm
> +				var/datum/status_effect/cult_stun_mark/S = L.has_status_effect(STATUS_EFFECT_CULT_STUN)
Done!

2022-10-29 16:30 UTC, Qwertytoforty commented on code/game/gamemodes/cult/cult_items.dm
> +						C.Jitter(16 SECONDS)
done

2022-11-02 09:48 UTC, S34NW approved these changes
Seems fine code-wise now

2022-11-02 19:23 UTC, farie82 commented on code/game/gamemodes/cult/cult_items.dm
> +				if(S)
Sorry for the late response, I somehow managed to miss this comment. But it looks good as is for now

2022-11-02 19:23 UTC, merged