[TGUI] Temp gun
ParadiseSS13/Paradise pull request #19350
Opened 2022-10-10 18:06 UTC by Contrabang

## What Does This PR Do
 TGUI's the temperature gun

## Why It's Good For The Game
We are moving away from Topic and into the age of TGUI

## Images of changes

![image](https://user-images.githubusercontent.com/91113370/194927529-e8775e15-6e91-44c2-816e-a6dafd9e79cb.png)
![image](https://user-images.githubusercontent.com/91113370/194927548-6c0b4630-1bf0-491c-b36f-86051d803e57.png)
![image](https://user-images.githubusercontent.com/91113370/194927563-d2ef60d3-f5e8-40b3-965e-717434430770.png)
![image](https://user-images.githubusercontent.com/91113370/194927573-406f7786-f704-4cd7-b1bb-3621b49b60d2.png)
![image](https://user-images.githubusercontent.com/91113370/194927583-6286d7a4-9b0e-48f7-a60f-70f4eef2b086.png)

Emagged and above the previous max temp point (bolded)
![image](https://user-images.githubusercontent.com/91113370/194927632-51cfd89f-374a-4ec0-b6ad-b85d277eb373.png)

## Testing

Compiled and ran game, no runtimes. Menu works and responds as expected.

## Changelog
:cl:
tweak: The temperature gun now uses TGUI
/:cl:

2022-10-10 18:20 UTC, Sirryan2002 requested changes

2022-10-10 18:20 UTC, Sirryan2002 commented on code/modules/projectiles/guns/energy/special.dm
> +	add_fingerprint(usr)
```suggestion
	add_fingerprint(user)
```

2022-10-10 18:20 UTC, Sirryan2002 commented on code/modules/projectiles/guns/energy/special.dm
> +			target_temperature = clamp(text2num(params["target_temperature"]) + T0C, min_temp, max_temp) //Retrieved as a celcius number, convert to kelvin
```suggestion
	if(action == "target_temperature")
			target_temperature = clamp(text2num(params["target_temperature"]) + T0C, min_temp, max_temp) //Retrieved as a celcius number, convert to kelvin
```

2022-10-10 18:20 UTC, Sirryan2002 commented on code/modules/projectiles/guns/energy/special.dm
> +	var/powercost = "Low"
this method of displaying power cost should be moved out of DM and into the TGUI menu

2022-10-10 18:20 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/TempGun.js
> +
```suggestion
```

2022-10-10 18:20 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/TempGun.js
> +        </LabeledList>
fix your indentation here

2022-10-10 18:20 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/TempGun.js
> +        label="Current Temperature">
```suggestion
        <LabeledList.Item label="Current Temperature">
```

2022-10-10 18:20 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/TempGun.js
> +        label="Power Cost">
```suggestion
        <LabeledList.Item label="Power Cost">
```

2022-10-11 21:17 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/TempGun.js
> +  const {target_temperature, temperature, max_temp, min_temp} = data;
```suggestion
  const { target_temperature, temperature, max_temp, min_temp } = data;
```

2022-10-12 03:25 UTC, Sirryan2002 approved these changes
code looks good

2022-10-12 15:56 UTC, SteelSlayer approved these changes

2022-10-12 15:57 UTC, merged