Smoke spells readability
ParadiseSS13/Paradise pull request #19387
Opened 2022-10-14 12:15 UTC by S34NW

## What Does This PR Do
Tweaks the parts of code that define smoke types when casting spells, to make it more readable.
Uses defines for smoke types now, as opposed to random numbers not properly documented anywhere.

## Why It's Good For The Game
12 year old messy code that makes no sense to anyone looking at it is bad.

## Testing
I make my wizard sleep due to his own smoke

## Changelog
No player facing changes, hooray?

2022-10-14 12:31 UTC, Contrabang commented on code/game/objects/effects/effect_system/effect_system.dm
> +		location = get_turf(source)
Is there any reason why we're not just `get_turf(source)` for this check? wouldn't that do the same thing if source was a turf?

2022-10-14 12:31 UTC, Contrabang commented on code/game/objects/effects/effect_system/effects_smoke.dm
> +		location = get_turf(source)
same question here, is this isturf check needed?

2022-10-14 14:07 UTC, Contrabang commented on code/game/objects/effects/effect_system/effect_system.dm
> +/datum/effect_system/proc/set_up(amount = 3, only_cardinals = 0, source)
```suggestion
/datum/effect_system/proc/set_up(amount = 3, only_cardinals = FALSE, source)
```

2022-10-14 14:09 UTC, Contrabang commented on code/datums/spell.dm
> +			smoke.set_up(smoke_amt, 0, location)
```suggestion
			smoke.set_up(smoke_amt, FALSE, location)
```

2022-10-14 14:11 UTC, Contrabang commented on code/game/objects/effects/effect_system/effect_system.dm
> +		amount = 10
Would this be better as a clamp? I'm not sure

2022-10-14 14:12 UTC, Contrabang commented on code/game/objects/effects/effect_system/effects_smoke.dm
> +/datum/effect_system/smoke_spread/freezing/set_up(amount = 5, only_cardinals = 0, source, desired_direction, blasting = 0)
ditto about boolean only_cardinals

2022-10-14 15:26 UTC, Contrabang requested changes
src.loc review, if any of these are out of scope, leave em be

2022-10-14 15:26 UTC, Contrabang commented on code/game/objects/items/weapons/grenades/smokebomb.dm
>  	playsound(src.loc, 'sound/effects/smoke.ogg', 50, 1, -3)
out of scope maybe but...
```suggestion
	playsound(loc, 'sound/effects/smoke.ogg', 50, 1, -3)
```

2022-10-14 15:26 UTC, Contrabang commented on code/game/objects/items/weapons/tanks/watertank.dm
>  	var/obj/effect/decal/cleanable/flour/F = new /obj/effect/decal/cleanable/flour(src.loc)
```suggestion
	var/obj/effect/decal/cleanable/flour/F = new /obj/effect/decal/cleanable/flour(loc)
```

2022-10-14 15:26 UTC, Contrabang commented on code/modules/atmospherics/machinery/pipes/simple/pipe_simple.dm
>  	playsound(src.loc, 'sound/effects/bang.ogg', 25, 1)
```suggestion
	playsound(loc, 'sound/effects/bang.ogg', 25, 1)
```

2022-10-14 15:26 UTC, Contrabang commented on code/modules/atmospherics/machinery/pipes/simple/pipe_simple.dm
> +	smoke.set_up(1, FALSE, src.loc)
```suggestion
	smoke.set_up(1, FALSE, loc)
```

2022-10-14 15:26 UTC, Contrabang commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
>  	playsound(src.loc, 'sound/effects/empulse.ogg', 25, 1)
```suggestion
	smoke.set_up(5, FALSE, loc)
	smoke.start()
	visible_message("<span class='danger'>[src] warps in!</span>")
	playsound(loc, 'sound/effects/empulse.ogg', 25, 1)
```

2022-10-14 15:26 UTC, Contrabang commented on code/modules/power/smes.dm
>  			explosion(src.loc, -1, 0, 1, 3, 1, 0)
```suggestion
			smoke.set_up(3, FALSE, loc)
			smoke.attach(src)
			smoke.start()
			explosion(loc, -1, 0, 1, 3, 1, 0)
```

2022-10-14 15:26 UTC, Contrabang commented on code/modules/power/smes.dm
> +			smoke.set_up(3, FALSE, src.loc)
```suggestion
			smoke.set_up(3, FALSE, loc)
```

2022-10-14 15:31 UTC, S34NW commented on code/modules/atmospherics/machinery/pipes/simple/pipe_simple.dm
>  	playsound(src.loc, 'sound/effects/bang.ogg', 25, 1)
out of scope

2022-10-14 15:32 UTC, S34NW commented on code/game/objects/items/weapons/grenades/smokebomb.dm
>  	playsound(src.loc, 'sound/effects/smoke.ogg', 50, 1, -3)
out of scope

2022-10-14 15:32 UTC, S34NW commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
>  	playsound(src.loc, 'sound/effects/empulse.ogg', 25, 1)
partially out of scope

2022-10-14 22:30 UTC, lewcc commented on code/modules/projectiles/projectile/magic.dm
> +			smoke.set_up(max(round(10 - teleammount),1), FALSE, stuff.loc) //Smoke drops off if a lot of stuff is moved for the sake of sanity
```suggestion
			smoke.set_up(max(round(10 - teleammount), 1), FALSE, stuff.loc) //Smoke drops off if a lot of stuff is moved for the sake of sanity
```

2022-10-15 07:33 UTC, farie82 commented on code/game/mecha/mecha.dm
> +	smoke_system.set_up(3, FALSE, src)
So this one basically just didn't work before? Can you add this to the CL if that were the case?

2022-10-15 15:03 UTC, farie82 commented on code/modules/projectiles/projectile/magic.dm
> +			smoke.set_up(max(round(10 - teleammount),1), FALSE, stuff.loc) //Smoke drops off if a lot of stuff is moved for the sake of sanity
```suggestion
			smoke.set_up(max(round(10 - teleammount), 1), FALSE, stuff) //Smoke drops off if a lot of stuff is moved for the sake of sanity
```
You mean like this @lewcc ?

2022-10-15 15:59 UTC, farie82 approved these changes

2022-10-15 16:05 UTC, merged