Nerfs Cult Juggernaut. Removed reflection
ParadiseSS13/Paradise pull request #19461
Opened 2022-10-21 18:46 UTC by HMBGERDO

## What Does This PR Do

This PR removes Cult Construct Juggernaut ability to reflect lasers

## Why It's Good For The Game

In default cult round its VERY VERY easy to get juggernaut. You kill one cyborg or  one officer or any other mindshielded person and sacrifice it, then put it in shell. 
To play against it security will ALWAYS order WT auto rifles to have a chance to play against it. Without this nerf cult juggernaut has 76 fucking percent to reflect default security lasers. 
Security does NOT have any weapons to fight juggernaut and they NEED order WT rifles. 

In other side, WT rifles is kinda OVERKILL against default cultists. You can easily get cultist using disabler, rubber shotgun and other guns, same as they can easily fight you. When security get WT rifles, game balance dies. Cult need to fix fractures and IBs, cult dies very easily and all that shit.

And the reason of all that shit is fucking Juggernaut that can just push and do nothing. They have 250 health and 76% to reflect laser and get only 0.5 damage. So it means we need 20 in middle successful laser hits to kill it and not die. Add that this shitter will reflect lasers right in your face, it will dance to avoid hits, it will place his wall spell and it will get healed by other cultists and pylons. 

Prince of Terror, who is dangerous Mid Round needs 30 lasers. And you can just get better then prince shit for so low cost.

After that PR Juggernaut will not reflect lasers. It will take 12.5 lasers to die. So you cannot just push security alone, they WILL kill you.
After that PR security will not start cult round with ";Cargo, order auto rifles".
After that PR Juggernaut maybe will stick to their team(as team antags designed for) and use their wall instead of just clicking.

After all, it was designed weird. Their reflect chance is less if you have more damage in your laser projectile BUT. The only way you can get BIG laser damage is laser accelerator cannon(in distance)(up to 40% reflect chance), Pulse rifle(60%) and Charged plasma pistol(70%), still sounds like a shit. 

## Testing

compiled and runned, shoot jugger

## Changelog
:cl:
del: Construct Juggernaut cant reflect lasers any more
/:cl:

2022-10-21 19:05 UTC, FloFluoro commented
You should _probably_ update your changelog to show that you effectively removed the Juggernaut's 50% brute/burn resistance to energy weapons, since that's the big change in this PR.

>After that PR Juggernaut will not reflect lasers. It will take 12.5 lasers to die. So you cannot just push security alone, they WILL kill you.

![image](https://user-images.githubusercontent.com/3611705/197268917-0d123958-7073-40e8-a25e-0bf19357a644.png)

Juggernaut being tanky is the point; they are strong, slow, and force inadequately-equipped targets to flee. Significantly reducing their effective HP pool doesn't seem like a good idea, since you're veering dangerously close to defeating the whole point of their design.

2022-10-21 19:32 UTC, GDNgit commented
Couple of things:
This PR was made right after two cult rounds, and you openly salted about the reflect chance.

> Security does NOT have any weapons to fight juggernaut and they NEED order WT rifles.

Yes, juggers are difficult to take down, that's the entire point of a jug. Although it's difficult you can take down a jug using a laser rifle or two, but the way you can effectively deal with jugs comes down to exploiting their extremely low movement speed.


> In other side, WT rifles is kinda OVERKILL against default cultists. You can easily get cultist using disabler, rubber shotgun and other guns, same as they can easily fight you. When security get WT rifles, game balance dies. Cult need to fix fractures and IBs, cult dies very easily and all that shit.

Absolutely not, WTs are effective for breaking mirror shields, dealing IB, and have easily replenishable ammo. People will not stop using autorifles.



> After all, it was designed weird.

This is a good reason to change how it's designed to make it more consistent, rather than outright removal. 


> Prince of Terror, who is dangerous Mid Round needs 30 lasers. And you can just get better then prince shit for so low cost.

IDK where this comes from, prince is better by a mile and is far more consistent. 



> After that PR Juggernaut will not reflect lasers. It will take 12.5 lasers to die. So you cannot just push security alone, they WILL kill you.

You can't push shit if this is the case, making the tank unable to tank sounds like a bad time for the jug.

I fail to see how this makes the already middling jug any more enjoyable or fun to play against, just damn near useless.

2022-10-21 19:49 UTC, HMBGERDO commented
> You should probably update your changelog to show that you effectively removed the Juggernaut's 50% brute/burn resistance to energy weapons, since that's the big change in this PR.

they had 50% resist to brute/burn in case they successfully reflect projectile. if they didnt reflect it, they get 100% damage. 

> Absolutely not, WTs are effective for breaking mirror shields, dealing IB, and have easily replenishable ammo. People will not stop using autorifles.

thats what im talking about. Good security officer will not take more guns than they need to. You always can go unga gamer and get thermals, cns rebooter, pulse shotgun shots and a lot of shit around in this game. Current juggernaut state just forces you to get it.

> This PR was made right after two cult rounds, and you openly salted about the reflect chance.

Yes. Does it make sense? I suggest changes that i feel like they should be. Juggers were designed when we had access to buckshot and slugs. Now we dont have it. 
My first round was as cult side, second as security so whats the problem?

> Juggernauts being tanky is the point; they are strong, slow, and force inadequately-equipped targets to flee. Significantly reducing their effective HP pool doesn't seem like a good idea, since you'd be veering dangerously close to defeating the whole point of their design.

They are still very good at getting damage. They can just take a lot of shots, they can place wall that will eat all shots, they can crash anything blocking their way.
Making em weaker just forces em to stick to their team as i think it supposed to be in this gamemode

2022-10-21 20:13 UTC, GDNgit commented
> they had 50% resist to brute/burn in case they successfully reflect projectile. if they didnt reflect it, they get 100% damage.
> 
> >

You still neglected to mention that this was being removed, you only cover the reflection itself in the pull request. I'd update that for clarification





> thats what im talking about. Good security officer will not take more guns than they need to. You always can go unga gamer and get thermals, cns rebooter, pulse shotgun shots and a lot of shit around in this game. Current juggernaut state just forces you to get it.
> 
> >

You're not forced to do anything as an officer, and you're not forced to instantly order autorifles during a cult round due to a jug. The point I'm making is that this won't stop anyone from ordering autorifles due to them already being so powerful against cult.


> Yes. Does it make sense? I suggest changes that i feel like they should be. Juggers were designed when we had access to buckshot and slugs. Now we dont have it.
> My first round was as cult side, second as security so whats the problem?

This seems to be a reactionary change due to the performance of a jug in round judging by your description, did you talk to any balance/design team members before going for this change?



> They are still very good at getting damage. They can just take a lot of shots, they can place wall that will eat all shots, they can crash anything blocking their way.

No you really can't unless you have a pocket artificer. A slow easy to hit target dying quickly will just make the role frustrating to play.

I support ditching the RNG reflect for something else, but this just way too much

2022-10-21 22:50 UTC, Rurik123 commented
> Yes, juggers are difficult to take down, that's the entire point of a jug. Although it's difficult you can take down a jug using a laser rifle or two, but the way you can effectively deal with jugs comes down to exploiting their extremely low movement speed.

It takes 2-3 laser guns to bring one down. Assuming it stands still for you. Between pylon healing, wall placement, overall delay tactics while using the wall smash for mobility, it will take more because you aren't going to hit every shot. All that's assuming its alone. It wont be.

Now with all that in mind, remember that officers typically have 1 laser gun. 

Dealing with jugs effectively doesn't really come down to exploiting movement speed at all, it comes down to one of two things.
- The Juggernaut misplays and walks into the open without support because they are new.
- You, the officer, ordered ballistics the second cult was announced and the problem is over. 

A game of hard counters isn't interesting. Having an item check for a WT Rifle, and making so a particular enemy is nigh unkillable without it isn't the best design route. While you can argue there's better ways to fix this (there probably is), I do think there's merit it an argument that juggers need a change in some way.

As it currently stands, juggers are the best possible construct outside of (1) wraith to kill the AI. After that, the wraith construct as a whole is no longer more valuable than juggers.

2022-10-22 00:49 UTC, Mitchs98 commented
While I agree that Juggernauts need a change, this really isn't it. You're removing the tank part of the Juggernaut in almost its entirety. Having personally played Juggernaut several times I can tell you lasers aren't fully useless against them and I have been brought down low, nearly died, and even died to lasers before. Yes it requires officers and/or ERT to co-ordinate...but I feel they should have to? 

Hard counters are in some instances a _good_ thing. Officers should have to use strategy in order to overcome certain obstacles, even if the strategy is primarily to order rifles. This imposes the risk of the rifles being stolen and put into enemy hands who can _also_ use them effectively(and it's been done many times in the past).

The PR itself reads very much as an 'I ded pls nerf' in my opinion the way it's written and with the merits displayed for merging it without really taking into account the cons or the fact that juggernauts are _meant_ to be tanky.

Comparing them to Prince also isn't really terribly valid sans their health. Prince is stronger and better in practically every way to begin with. And I'm also not quite sure comparing the two is the way to go about it in general.

Pylons are mentioned, as are artificers. Artificers are easily killed and pylons heal incredibly slowly. Pylons require you to stay within them to receive their pretty slow healing and artificers require co-ordination to not get easily murdered. Usually in the form of a Juggernaut shielding it while the artificer desperately tries to heal their spooky Eldritch shield. Which, again, can be dealt with by using tactics properly. 

Juggernauts can't attack from range, they move very slowly. If one outplays you then well gg they deserved it.

2022-10-22 02:44 UTC, Edan52 commented
I don't think this change is very necessary however I'm not a particularly big fan of the RNG involved in it or the fact that lasers are so nerfed against it and other projectiles aren't. I'm open for discussion but I don't want to outright remove this feature, objecting.

2022-10-22 10:08 UTC, Coolrune206 commented
Give them some decent resistance to account for the removal of their 0.5* damage modifier, and this is a lovely change. Otherwise, it's a bit heavy handed in terms of nerfs, and I'm the guy that always whines about cult needing nerfs :P

2022-10-22 11:56 UTC, HMBGERDO commented
Alright.

Changed their laser resist to get only 60% of laser damage, still not reflecting. 
Why 60% and not 50%? Before this PR they had chance to reflect lasers. If they reflect it, they get 50% damage, if not, they get 100%. Chance to reflect laser from default laser gun was 76%. In middle you needed 20,16 hits with default security laser gun. With static 60% resist to lasers you need 20,8 hits with laser gun. Both needs 21 shots so that is why.

Their health is not changed, their resist against bullets(WT auto rifle) is not changed, they just doesnt reflect lasers any more.

2022-10-22 21:56 UTC, Dafrek commented
I've never really had a problem with juggernauts as sec, they are certainly tougher than most constructs, but even without ballistics they usually don't take too much effort to kill. Unlike wraiths and regular cultists, however, they don't have any get-out-of-jail-free cards for when they get caught out of position, which is especially common for juggernauts due to their insanely slow speed.

2022-10-25 13:48 UTC, S34NW requested changes
minor tweaks to code

2022-10-25 14:17 UTC, GDNgit commented
> Alright.
> 
> Changed their laser resist to get only 60% of laser damage, still not reflecting. Why 60% and not 50%? Before this PR they had chance to reflect lasers. If they reflect it, they get 50% damage, if not, they get 100%. Chance to reflect laser from default laser gun was 76%. In middle you needed 20,16 hits with default security laser gun. With static 60% resist to lasers you need 20,8 hits with laser gun. Both needs 21 shots so that is why.
> 
> Their health is not changed, their resist against bullets(WT auto rifle) is not changed, they just doesnt reflect lasers any more.

Good compromise on taking the rng out

2022-10-25 21:24 UTC, S34NW approved these changes

2022-10-30 15:48 UTC, AffectedArc07 approved these changes

2022-10-30 15:49 UTC, merged