Fixes issue with tooltips/blockhair flag conflict
ParadiseSS13/Paradise pull request #19470
Opened 2022-10-22 14:36 UTC by Raven567

## What Does This PR Do

Fixes an issue with tooltips not displaying for hats using the "BLOCKHAIR" flag, Caused by a conflict another flag.
https://github.com/ParadiseSS13/Paradise/pull/19468
## Testing

![image](https://user-images.githubusercontent.com/28615254/197344860-f0a4d565-f1dd-4965-b71e-ba3e0eaceb84.png)
I tested to make sure it didn't break anything, now tooltips display, and the hats still hide hair. 
## DISCLAIMER
I am very new to this project, and this is an issue that went way deeper than my expertise. It seems solid though
I tested quite thoroughly.

2022-10-28 18:01 UTC, Sirryan2002 requested changes
This will cause other issues, there's a better solution than setting this flag to `32`.

2022-10-28 18:01 UTC, Sirryan2002 commented on code/__DEFINES/clothing.dm
> +#define BLOCKHAIR				32	// temporarily removes the user's hair, facial and otherwise.
this will make it so anything with the BLOCKHAIR flag conducts electricity (so energy zaps).

2022-10-28 18:26 UTC, farie82 commented
Turning this PR into a draft till the above reviews are solved.

2022-11-09 23:03 UTC, hal9000PR commented
reviews have not been resolved in over 7 days. moving to closed. feel free to re-open the PR with requested changes.

2022-11-09 23:03 UTC, closed without merging