[GBP NO UPDATE] Fixes the basetype of .../under/suit spawning
ParadiseSS13/Paradise pull request #19471
Opened 2022-10-22 14:39 UTC by ElorgRHG

## What Does This PR Do

Fixes https://github.com/ParadiseSS13/Paradise/issues/19432

## Why It's Good For The Game

Missing sprite suit bad :(

## Testing

Spawned `/obj/effect/landmark/costume/butler`
No missing sprite.

## Changelog
:cl:
fix: Fixed a sprite-less suit spawning when it shouldn't.
/:cl:

2022-10-22 17:43 UTC, Sirryan2002 commented on code/game/objects/effects/landmarks.dm
> +	new /obj/item/clothing/under/suit/black(src.loc)
```suggestion
	new /obj/item/clothing/under/suit/black(loc)
```

2022-10-25 13:52 UTC, S34NW requested changes
good to go, just apply the suggested change by sirryan to remove explicit src

2022-10-26 23:37 UTC, Sirryan2002 approved these changes

2022-10-28 18:19 UTC, farie82 approved these changes

2022-10-28 18:20 UTC, merged