Standardizes alien code to use Alien over xeno/xenos/xenomorph
ParadiseSS13/Paradise pull request #19628
Opened 2022-11-07 00:02 UTC by GDNgit

## What Does This PR Do
Standardizes alien code to use Alien over xeno/xenos/xenomorph
Does not convert items that would conflict with #19209 (There's like 4)
TODO:
Preference/DB stuff

## Why It's Good For The Game
Having one standard is better than four, pretty much all of this is backend and won't affect players
This does not affect: Xenomorph mentions in moon19 
Some clothing (Pretty much just stuff that conflicts with the econ PR)

## Testing
Currently this compiles and runs fine with aliens
That does not mean it's ready 

## Changelog
:cl:
spellcheck: Standardizes mentions of xenomorphs to aliens 
/:cl:

2022-11-07 04:11 UTC, FloFluoro commented
![image](https://user-images.githubusercontent.com/3611705/200222998-0b43e085-4c95-4886-b400-d1241a03758d.png)
![image](https://user-images.githubusercontent.com/3611705/200223132-ae1eb9f3-be46-4ab6-ae94-58a3863f380c.png)
![image](https://user-images.githubusercontent.com/3611705/200223425-31c33e3f-cde6-4a4a-8b91-c7ae138980be.png)

Abductors still use "alien" for lots of stuff internally, not a fan of cramming more stuff under this moniker since basically no one calls Abductors *or* Xenomorphs "aliens". If you really insist that the name not be Xenomorphs out of fear that Paradise could get Weston Yamada'd, maybe consider what CM13 did and refer to them as xenonids internally instead?

2022-11-07 04:27 UTC, GDNgit commented
> ![image](https://user-images.githubusercontent.com/3611705/200222998-0b43e085-4c95-4886-b400-d1241a03758d.png) ![image](https://user-images.githubusercontent.com/3611705/200223132-ae1eb9f3-be46-4ab6-ae94-58a3863f380c.png) ![image](https://user-images.githubusercontent.com/3611705/200223425-31c33e3f-cde6-4a4a-8b91-c7ae138980be.png)
> 
> Abductors still use "alien" for lots of stuff internally, not a fan of cramming more things under this moniker since basically no one calls Abductors _or_ Xenomorphs "aliens". Something to consider if you really want this to be the one standard.

We're not going to use xenos/xenomorphs
If you want to come up with a third option, feel free to

2022-11-07 04:36 UTC, FloFluoro commented
> > ![image](https://user-images.githubusercontent.com/3611705/200222998-0b43e085-4c95-4886-b400-d1241a03758d.png) ![image](https://user-images.githubusercontent.com/3611705/200223132-ae1eb9f3-be46-4ab6-ae94-58a3863f380c.png) ![image](https://user-images.githubusercontent.com/3611705/200223425-31c33e3f-cde6-4a4a-8b91-c7ae138980be.png)
> > Abductors still use "alien" for lots of stuff internally, not a fan of cramming more things under this moniker since basically no one calls Abductors _or_ Xenomorphs "aliens". Something to consider if you really want this to be the one standard.
> 
> We're not going to use xenos/xenomorphs If you want to come up with a third option, feel free to

CM13 refers to their aliens as xenonids internally, and I'd personally prefer that over lumping the odds and ends of two antags into "alien".

I'd also be fine if all the abductor references under 'alien' were changed to 'abductor', since the alien name would then be reserved for a single antag, but that's out of scope of this PR.

2022-11-07 04:44 UTC, GDNgit commented
> > We're not going to use xenos/xenomorphs If you want to come up with a third option, feel free to
> 
> CM13 refers to their aliens as xenonids internally, and I'd personally prefer that over lumping the odds and ends of two antags into "alien".
> 
> I'd also be fine if all the abductor references under `alien` were changed to `abductor`, since the alien name would then be reserved for a single antag, but that's out of scope of this PR.

Moving alien items to abductor items was something I was gonna throw up to staff after this pr

I'll keep xenonoids in mind... I like that

2022-11-10 05:14 UTC, Sirryan2002 requested changes

2022-11-10 05:14 UTC, Sirryan2002 commented on code/_globalvars/lists/misc.dm
> +	"Alien",
please check to make sure this doesn't break maps/camera nets

2022-11-10 05:14 UTC, Sirryan2002 commented on code/datums/diseases/transformation.dm
> +	desc = "This disease changes the victim into an alien hunter."
```suggestion
	desc = "This disease changes the victim into an alien."
```
just keep this vague/generic

2022-11-10 05:14 UTC, Sirryan2002 commented on code/datums/outfits/outfit_admin.dm
> +/datum/outfit/admin/greytide/alien/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
change this typepath back if you're leaving the ID the same

2022-11-10 05:14 UTC, Sirryan2002 commented on code/game/machinery/portable_turret.dm
> +			if("authalien")
this will break the turret TGUI button for this action

2022-11-10 05:14 UTC, Sirryan2002 commented on code/game/machinery/turret_control.dm
> +			if("authalien")
same here

2022-11-10 05:14 UTC, Sirryan2002 commented on code/modules/mob/dead/observer/orbit.dm
> +					antag_serialized["antag"] = "Alien"
can you test the orbit menu to make sure this doesn't break things

2022-11-10 05:16 UTC, GDNgit commented on code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
> +/mob/living/carbon/alien/humanoid/sentinel/verb/evolve() // -- TLE /// The related should be removed
Ye

2022-11-10 05:16 UTC, GDNgit commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	R.add_language("Alien", 1)
It doesn't

2022-11-10 05:17 UTC, GDNgit commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_ALIEN				"alien"
SQL stuff is being altered, this is in draft for a reason

2022-11-20 22:32 UTC, GDNgit commented on code/__DEFINES/misc.dm
> +#define BLOOD_STATE_ALIEN			"alien"
broken on master, appears to never have worked

2022-11-26 06:46 UTC, closed without merging

2022-11-26 06:47 UTC, GDNgit commented
Just being closed until I finish this pr to make map queue more readable