Unequip gib victims earlier in the process.
ParadiseSS13/Paradise pull request #19626
Opened 2022-11-06 22:09 UTC by warriorstar-orion

## What Does This PR Do
This PR unequips human types on gib, tossing their equipment around randomly in the same way that their organs are. This adds to the list of equipment that may possibly survive an explosion, and ensures indestructible items are not wiped out of reality on gib.

This has several consequences and, depending on how you look at it, balance implications.

## Why It's Good For The Game

1. When a human type is gibbed, their internal and external organs are removed, and 'thrown' about in the area of the gib. This process does not consider certain things. The primary issue here is that objects, even indestructible ones, are simply deleted on gib when the human entity itself is deleted. Their damage resistance is completely ignored. This is a problem.

2. Typically, removing a limb will pop off any relevant worn clothing. Lose a foot, your shoes are removed. These items remain after a gib, but are not affected in the same way that organs are. Organs are tossed about in a random direction anywhere from 1 to 3 tiles away. The clothing simply remain on the same tile like the person was just raptured. Now, these items will be tossed about. It's not a huge thing, but it "feels" better.

As I said, this has all kinds of weird spooky-action-at-a-distance balace implications. Two examples:

- If a nukie manages to cause an explosion that gibs the Captain, the NAD, if in their bag, is "destroyed", and the game, in order to prevent that, moves it to specified spawn markers randomly dotted throughout the station. (That's right, NAD teleports are not totally random. Did I just blow your mind?) Now, if the nukies manage an explosion on the bridge that gibs the Captain, the NAD will be right there.

- PDAs and IDs are in slots that gets them deleted on gib. Now, if characters gib, their IDs, if they don't get caught up in a subsequent explosion, is up for grabs. Or the CE's toolbelt. Or other similar items. Basically, the loot table for explosions strong enough to cause gibbing has been buffed.

I don't know enough about balance/design to think through if these are good things.

## Testing
Lots of explosions. This is an initial writeup and if it's good then I'll have testing videos and such.

## Changelog
:cl:
fix: Gibbed players are unequipped entirely. This increases the chances that their items survive larger explosions, but does not guarantee it.
fix: Indestructible items will no longer be destroyed when in a container worn by a gibbed person, and will properly be affected by explosions.
/:cl:

2022-11-07 03:31 UTC, roarbark commented
will this let people get more nukie items should one of those die? thats a biiiig nukie nerf. i'd give some special behaviour to minibombs to still delete those bags.

2022-11-07 03:51 UTC, warriorstar-orion commented
> will this let people get more nukie items should one of those die? thats a biiiig nukie nerf. i'd give some special behaviour to minibombs to still delete those bags.

Yeah, since the explosive implant calls gib independently, it might be a good idea to delete some of their worn equipment before the gib, either randomly, or some specific set of slots.

2022-11-08 16:04 UTC, warriorstar-orion commented
@roarbark as a follow-up, i tested syndie micro- and macro-bombs. Macro-bombs have a high severity explosion radius of 4, which, given items are tossed about post gib anywhere from 1-3 tiles away, all but guarantees the majority of their equipment will be destroyed in the blast wave. The micro-bomb is not powerful enough to do this.

I'm going to chat with balance team about all the changes that may need to occur due to this, or if this is the best approach.

2022-11-10 09:57 UTC, S34NW requested changes

2022-11-10 09:57 UTC, S34NW commented on code/modules/mob/living/carbon/human/death.dm
> +		I.throw_at(get_edge_target_turf(src, pick(GLOB.alldirs)), rand(1,3), 5)
```suggestion
		I.throw_at(get_edge_target_turf(src, pick(GLOB.alldirs)), rand(1, 3), 5)
```
Minor formatting tweak

2022-11-12 22:49 UTC, closed without merging