Reticence now deals stamina damage
ParadiseSS13/Paradise pull request #19764
Opened 2022-11-23 23:57 UTC by GDNgit

## What Does This PR Do
The Reticence's gun once again deals stamina damage rather than brute damage
All other traits are untouched
40 brute -> 40 stamina 
## Why It's Good For The Game
The silly little mime mech shouldn't be murdering people left and right, especially if the pilot doesn't know that the silly little mime mech is very, very lethal.
The whole gimmick of it draining the charge of the honk mech is kind of null if it just kills them.
I've been told this is also unintended, and that fox didn't mean for this to deal brute. Makes sense as it turns a fun item that a mime can use into something that isn't going to ever end well for them.
You can still easily kill people with this as a tot, it has combat mecha punches, but a nonantag mime isn't gonna get a nasty surprise. 

## Testing
skrell murder :>

## Changelog
:cl:
tweak: Mime mech's primary weapon now deals stamina damage again
/:cl:

2022-11-24 00:02 UTC, FloFluoro commented
I was gonna do this later tonight, thank you for saving me the time!

Reticence is such a rare mech that Robotics shouldn't have to worry about running afoul of self-antag rules in the few chances they get to make it.

2022-11-24 01:14 UTC, Sirryan2002 commented
Honestly, instead of make a nonlethal type, just make this change to the base type. I don't believe this projectile type is used anywhere else than in the reticence

2022-11-24 01:40 UTC, GDNgit commented
> Honestly, instead of make a nonlethal type, just make this change to the base type. I don't believe this projectile type is used anywhere else than in the reticence

it's used in the mime finger gun, hence why it was changed on accident

2022-11-24 01:42 UTC, Sirryan2002 commented
That makes sense, thank you for clarifying

2022-11-24 01:42 UTC, Sirryan2002 approved these changes

2022-11-24 01:42 UTC, Sirryan2002 requested changes
I did not mean to approve this, oops

2022-11-25 02:08 UTC, Sirryan2002 approved these changes
code looks good

2022-11-27 00:49 UTC, merged