Buffs and cleans up atomic panacea
ParadiseSS13/Paradise pull request #19904
Opened 2022-12-10 20:25 UTC by BiancaWilkson

## What Does This PR Do

Changes the changeling ability atomic panacea to not just be chemical-based. Now it uses INVOKE_ASYNC to make it work similarly to how vampire rejuvenate.

Keeps the mutadone injection, because it would be much messier code-wise if I just copy-pasted the mutadone code into the proc.

Gets  #19848 going along as well.
## Why It's Good For The Game

Atomic panacea has been a really weird ability for a while. It feels like it should work the same way fleshmend does, but healing toxin damage instead of brute/burn. But how it ACTUALLY worked was that it would just inject charcoal, potassium iodide, mutadone, mannitol, and antihol. Not only is this a weird way to do it, but it's also very ineffective. Charcoal heals toxins and purges reagents quite slowly, and potassium iodide is laughably bad at dealing with high amounts of radiation. These changes make panacea both better, and more intuitive in how it works.

## Testing

Got drunk, got irradiated, poisoned myself, then logged onto my private server and did the same thing as a changeling. Panacea got me all healed up.

## Changelog
:cl:
tweak: Buffs atomic panacea to work faster and more efficiently
/:cl:

2022-12-10 20:38 UTC, Sirryan2002 commented on code/modules/antagonists/changeling/powers/panacea.dm
> +		user.radiation = (max(0, user.radiation-70)) //Same radiation healing as pentetic
```suggestion
		user.radiation = max(0, user.radiation - 70) //Same radiation healing as pentetic
```

2022-12-12 21:07 UTC, Sirryan2002 approved these changes
code looks good

2022-12-19 14:35 UTC, hal9000PR requested changes

2022-12-19 14:35 UTC, hal9000PR commented on code/modules/antagonists/changeling/powers/panacea.dm
> +		sleep(2 SECONDS)
IK this is rich coming from me who left vamp rejuv the way it is, but would you make this a status effect?

2022-12-29 11:18 UTC, S34NW approved these changes

2022-12-29 15:28 UTC, farie82 approved these changes

2022-12-29 15:31 UTC, merged