Removes RnG from the Ablative Trenchcoat and Armor
ParadiseSS13/Paradise pull request #19958
Opened 2022-12-19 12:19 UTC by Coolrune206

## What Does This PR Do

Removes the reflect chance from the Ablative Armor and Trenchcoat in favour of a cooldown system. Every four seconds, the Ablative items can fully deflect one laser/energy projectile. This deflection period lasts a decisecond, so that if someone decides to use the really cool lasershot on you or some other type of scatter laser that's all deflected in the first hit.
## Why It's Good For The Game

The Ablative armorpieces previously had an RnG chance to reflect attacks. Combat RnG is generally bad, especially when it's a passive bonus. This keeps the Ablative Armor strong at fighting people with energy weapons (deflecting at least one shot, probably more) guaranteed is a boon, especially against what the Ablative Armor is intended to be facing (things like E-Bows), while removing the random chance to reflect projectiles. Also, previously the two ablative armors had different reflect chances - I've just flattened them to the same cooldown for now, but am willing to change this if necessary.
## Testing

I shot the shit out of a skrell wearing the Ablative. The first shot was blocked, the rest went through until four seconds had passed. Ditto with the scatter-laser, except all the projectiles in the first shot were reflected.
## Changelog
:cl:
tweak: Changes the Ablative Armor from an RnG reflect chance to a cooldown-based guaranteed reflect
/:cl:

2022-12-19 14:02 UTC, hal9000PR requested changes
all of these reviews for the trenchcoat and the armour please

2022-12-19 14:02 UTC, hal9000PR commented on code/modules/clothing/suits/miscellaneous.dm
>  		return 1
comment for why this is needed please.

2022-12-19 14:02 UTC, hal9000PR commented on code/modules/clothing/suits/miscellaneous.dm
> +		return 1
make the `4 SECONDS` a variable please

2022-12-19 14:02 UTC, hal9000PR commented on code/modules/clothing/suits/miscellaneous.dm
> +	var/lastreflect
would you rename this to `last_reflect_time`

2022-12-19 14:16 UTC, Coolrune206 commented on code/modules/clothing/suits/miscellaneous.dm
>  		return 1
fuck I forgot the comments

2022-12-19 21:21 UTC, Bm0n commented
Make sure you change the ablative vest as well. Probably also make it a little bit weaker

2022-12-21 10:15 UTC, hal9000PR commented on code/modules/clothing/suits/armor.dm
> +	var/reflect_cooldown = 4 SECONDS
Would you make this one 5 seconds?

2022-12-21 10:15 UTC, hal9000PR commented on code/modules/clothing/suits/armor.dm
> +		return
This should return false

2022-12-24 15:42 UTC, Sirryan2002 approved these changes
code looks good

2022-12-24 15:42 UTC, Sirryan2002 commented on code/modules/clothing/suits/armor.dm
> +		return 0
I hate that these don't use defines :/

2022-12-28 04:41 UTC, SteelSlayer approved these changes

2022-12-28 04:42 UTC, SteelSlayer commented
Needs a deconflict, then it can be merged.

2022-12-28 19:02 UTC, hal9000PR approved these changes

2022-12-28 19:02 UTC, merged