Projectiles now orbit blackholes
ParadiseSS13/Paradise pull request #19999
Opened 2022-12-23 22:08 UTC by hal9000PR

## What Does This PR Do
Projectiles will now curve around singulos. 
I planned on doing more for this but this took me ages. hardest PR to lines written ratio ever.
If I get more time I will do more reworking so its actually an interesting engine.

## Why It's Good For The Game
neat feature

## Images of changes

![dreamseeker_zbUYinyVa1](https://user-images.githubusercontent.com/69320440/209409090-4a048147-7695-433a-a1a3-b8823b8ddded.gif)

## Testing
you dont want to fucking know what I have been through.

## Changelog
:cl:
experiment: projectiles now curve around black holes. 
/:cl:

2022-12-24 03:45 UTC, procdrone commented
to clarify, what happens to emitter shots that power containment? will they also orbit, miss the shield gens, and make the singularity engine loose every time?

2022-12-29 14:16 UTC, S34NW requested changes

2022-12-29 14:16 UTC, S34NW commented on code/modules/power/singularity/singularity.dm
> +	if(istype(AM, /obj/item/projectile))
Exclude `/obj/item/projectile/beam/emitter` from this

2023-01-19 15:57 UTC, S34NW commented on code/modules/power/singularity/singularity.dm
> +	if(istype(AM, /obj/item/projectile))
Note: This is so that you can actually have a functional containment for singulos

2023-01-30 13:13 UTC, S34NW commented
Any update on this? Currently sat in limbo for a little while.

2023-02-01 23:35 UTC, hal9000PR commented
> to clarify, what happens to emitter shots that power containment? will they also orbit, miss the shield gens, and make the singularity engine loose every time?

[ezgif.com-gif-maker.webm](https://user-images.githubusercontent.com/69320440/216192011-0ac0676a-7f84-4d9f-99e8-3da74aef180e.webm)

2023-02-01 23:39 UTC, S34NW approved these changes

2023-02-04 04:05 UTC, SteelSlayer approved these changes

2023-02-04 04:36 UTC, merged