Brains act more like dead humans on examine.
ParadiseSS13/Paradise pull request #20074
Opened 2023-01-02 15:42 UTC by Qwertytoforty

## What Does This PR Do

If a ghost is in it's brain, it will now indicate that the spark is very bright in the brain.

If the ghost is still connected, it will give the faint spark of life message.

If the brain is dnr / not a valid brain / ghost not connected, it will do the lifeless message.

## Why It's Good For The Game

Makes it more similar to the messages on dead people. Right now, people mainly look if a ghost is in a brain to tell if they want to revive someone, as they can only see if someone is in the brain or not.
Now people can see if someone is in the brain (good to revive), ghost connected (probably good to revived), or unrevivable, like the soulless body on examine

## Testing

Confirms that then brain worked with ghost in brain, ghost in round but not in brain, and ghost dnr / a brain without a ghost.

## Changelog
:cl:
tweak: Brains are more clear in if they are having a ghost available for revival or not.
/:cl:

2023-01-19 16:11 UTC, S34NW requested changes
guard clause my beloved

2023-01-19 16:11 UTC, S34NW commented on code/modules/mob/living/carbon/brain/brain_item.dm
> +		. += "You can feel a bright spark of life in this one!"
```suggestion
		. += "You can feel a bright spark of life in this one!"
		return
```

2023-01-19 16:11 UTC, S34NW commented on code/modules/mob/living/carbon/brain/brain_item.dm
> +	else if(brainmob && brainmob.mind)
```suggestion
	if(brainmob && brainmob.mind)
```

2023-01-19 20:11 UTC, Sirryan2002 commented on code/modules/mob/living/carbon/brain/brain_item.dm
> +				if(G.can_reenter_corpse == 0)
```suggestion
				if(G.can_reenter_corpse == FALSE)
```

2023-01-19 20:11 UTC, Sirryan2002 commented on code/modules/mob/living/carbon/brain/brain_item.dm
> +	if(brainmob && brainmob.mind)
```suggestion
	if(brainmob?.mind)
```

2023-01-20 23:37 UTC, Sirryan2002 approved these changes

2023-01-23 10:14 UTC, S34NW approved these changes

2023-01-28 08:36 UTC, farie82 approved these changes

2023-01-28 08:36 UTC, merged