Cyberiad: Maintenances Rework (and other little changes)
ParadiseSS13/Paradise pull request #20130
Opened 2023-01-08 12:41 UTC by Venuska1117

## What Does This PR Do
This PR changes:
- Fore-Port Secondary Maintenance
- Port Maintenance
- Aft-Port Maintenance
- Aft-Port Secondary Maintenance
- Aft Maintnenance
- Aft-Starboard Maintenance
- Aft-Starboard Secondary Maintenance

Important Notes:
- As payment for making **Aft Maintnenance** near _psychiatrist_ and _Janitor_ bigger, i moved **Engineering Control** room 
  and **Construction Area** to _**Abandoned Assembly Line**_ (Please Main Engineers don't be mad at me for this i needed spaace >.<)
  
- All Maintenances Mentioned Above have their own **separate Air system** and vents with can be controlled by people with Engineer access or above, so now you can disable air flow to whole maintenance if there is breach made by meteors and don't want to lost oxygen or to separate threat.

- All APC's in this maintenances were moved to "(Maintenance name) Atmospherics Maintenance" room (except Aft-Starboard Maintenance where APC is in "Toxin Testing EVA Maintenance" room).

- Removed Vents in med-sci mantienance from walk paths and moved them to side rooms, so now you don't get attacked by "vent-camping antagonist like spiders".

- Changed **Locker Room** shape, so mainenance have little more space to add room.

- Added Missing APC in Aft-Starboard Maintenance (Sci Mantienance)
- Removed double disposal pipe under maintenance door (it was spoken in issues but can't find it).

## Why It's Good For The Game
It will add more dynamics to maintenances, now you have better access to most of maintenance rooms by using vents but as payment you can be locked in specific maintenance if someone close valve, so more accessibility for threat of be locked in choosed maintenance, as for other antags, it give them more rooms to hide themselfs or bodies.

## Images of changes
![Maintenance1](https://user-images.githubusercontent.com/89580971/211175892-9daa3a94-2de9-4b31-8322-8f60f64a5612.png)
![Maintenance2](https://user-images.githubusercontent.com/89580971/211175895-a348b3ce-6d99-4e1a-bccb-7d00e3658bf6.png)
![Maintenance3](https://user-images.githubusercontent.com/89580971/211175897-2225f87d-e0f6-4e4e-ad93-e5d7c3b4f06a.png)
![Engineering Move](https://user-images.githubusercontent.com/89580971/211176138-d2f65156-5823-4172-999a-4fa55d73d352.png)
(Please Engineers don't be mad for this)

##Side Note
This PR have electric mantis too, but i hear there will be service rework later so i dont touch maintenance there, so it will be ONLY maintenance, what is still connected to main atmos system.

## Testing
Tested on Test server and it seem fine.

I BROKE SOMETHING IN PROCESS SO HERE IS PREVIOUS PULL: https://github.com/ParadiseSS13/Paradise/pull/20126

## Changelog
:cl:
add: Changes Maintenance
/:cl:

2023-01-08 12:44 UTC, Venuska1117 commented
> [CinnamonSnowball](https://github.com/CinnamonSnowball)

> The new Engineering Control room looks a lil bit scuffed:
> 
> * there's a 2x2 table in the corner of the room, meaning the goggles are inaccessible without climbing onto the table;
> * the room is kinda stuffy - the way to the counter is a tight 1-tile wide path.
> 
> Does the hardsuits room _have_ to be a separate room? Feels like they'd be fine just standing freely, maybe with some glass windows grouping them together like the portable vent pumps/scrubbers in the engineering lobby, and it would open up a bit more space to solve the second issue.

Here i changed it this way, is it better? 
![f1](https://user-images.githubusercontent.com/89580971/211196678-30eec8cc-88b2-46b6-87a3-42a404af7744.png)

2023-01-08 16:57 UTC, Carthusia commented
Kinda feel the old factory line should be left as a maint zone and not an engineering zone, people really like to make use of it for RP builds

2023-01-08 23:29 UTC, Venuska1117 commented
> Kinda feel the old factory line should be left as a maint zone and not an engineering zone, people really like to make use of it for RP builds

I understand what you mean, yes i saw people rebuild this room for "something" but i played once whole day, and see engineers building something in this room once or twice (on 10 shifts what lasted longer than 30minutes), most people build stuff above departures (in space) like Disco room, BSA or any other objective or project, so i tough about it when i moved it there, in exchange for little more maintenance space (what was like 1 gap tunnels) should be worth it?

2023-01-09 08:15 UTC, Mitchs98 commented
Kind of agreeing that the assembly line should remain as it is. Even if people don't use it every single round, I do see it get used for some neat projects. Including BSH hell harvesting sometimes. Don't personally think it'd be worth removing it just to increase the size of specific maint spots a bit.

Otherwise the rest of it looks neat.

2023-01-10 18:17 UTC, Venuska1117 commented
I returned it back, is it better now?
![image](https://user-images.githubusercontent.com/89580971/211630727-ab3ec401-5f55-452f-8c58-ddcb0f7810fd.png)

2023-01-22 18:51 UTC, S34NW requested changes
There are a _lot_ of doors in some areas of maints, please consider cutting back that figure.

Also, blocking issue: You need to apply all the changes from https://github.com/ParadiseSS13/Paradise/pull/19867 as you now have a mangled map file

2023-01-30 19:31 UTC, Venuska1117 commented
Please do not merge util i find issue, if i find it and fix it i will write comment.

2023-02-01 19:16 UTC, Venuska1117 commented
what...

2023-02-03 00:40 UTC, Venuska1117 commented
How its that possible

2023-02-04 02:36 UTC, Venuska1117 commented
Okay i think this PR can be tested to be merged, and i fixed double disposal pipe under one specific door, there was issue about it but i can't find it. 

~ "double pipe at this tile, litellary unpleyable"

2023-02-06 22:34 UTC, closed without merging