Wallets now show their front ID on examine
ParadiseSS13/Paradise pull request #20250
Opened 2023-01-19 05:20 UTC by Contrabang

## What Does This PR Do

Allows you to see the front ID on a wallet when examining someone. Also minorly refactors colored wallets. Idea comes from TG wallets.

## Why It's Good For The Game
Makes it easier to understand what ID card someone is wearing without using a security HUD

## Images of changes

Has an ID
![image](https://user-images.githubusercontent.com/91113370/213361299-5b725bf1-8129-4aa1-9de1-809e91815541.png)
No ID
![image](https://user-images.githubusercontent.com/91113370/213361316-d78e6a28-1d37-45a3-82a2-5deb541bcada.png)

## Testing

See above. Using arcade wallets, they appear exactly as before but also have the new functionality.

## Changelog
:cl:
tweak: You can now see a Wallet's front ID when examining someone.
/:cl:

2023-01-23 14:09 UTC, S34NW commented on code/game/objects/items/weapons/storage/wallets.dm
> +	return initial(name)
```suggestion
		name = initial(name)
```
Seems like a needless proc jump to me

2023-01-23 14:14 UTC, S34NW approved these changes

2023-01-23 22:33 UTC, farie82 requested changes

2023-01-23 22:33 UTC, farie82 commented on code/modules/mob/living/carbon/human/human.dm
> +		var/obj/item/pda/pda
```suggestion
		var/obj/item/pda/pda = wear_id
```

2023-01-25 19:13 UTC, farie82 approved these changes

2023-01-25 19:13 UTC, merged