You can no longer push people into fireaxe cabinets.
ParadiseSS13/Paradise pull request #20279
Opened 2023-01-22 16:37 UTC by Adrer

## What Does This PR Do
You can no longer push people into fireaxe cabinets.

## Why It's Good For The Game
This is very funny but unintentional.

## Testing
Tried to push someone into a fireaxe cabinet, didn't work

## Changelog
:cl:
fix: You can no longer push people into fireaxe cabinets.
/:cl:

2023-01-22 16:39 UTC, hal9000PR approved these changes
merging this one cos its fork is clean

2023-01-22 16:41 UTC, hal9000PR requested changes
please do this for `/obj/structure/closet/critter, /obj/structure/closet/crate, and /obj/structure/closet/statue`

2023-01-22 16:46 UTC, hal9000PR approved these changes
for real this time

2023-01-22 17:03 UTC, lewcc commented on code/game/objects/structures/crates_lockers/crates.dm
> +	return FALSE
This is re-defined, the override for crates already exists lower in the file.

2023-01-22 17:05 UTC, lewcc requested changes

2023-01-22 17:05 UTC, lewcc commented on code/game/objects/structures/crates_lockers/crates.dm
> +
Please remove this one, there's already a definition for `/obj/structure/closet/crate/shove_impact` later in this file.

2023-01-23 22:08 UTC, farie82 approved these changes

2023-01-23 22:08 UTC, merged