Fixes disconnected APCs in research department on Deltastation.
ParadiseSS13/Paradise pull request #20280
Opened 2023-01-22 17:08 UTC by Adrer

## What Does This PR Do
Fixes disconnected APCs in research department on Deltastation.
fixes: #20278

## Why It's Good For The Game
Disconnected APCs not good.

## Images of changes
Before
![image](https://user-images.githubusercontent.com/19361017/213929312-aca9e1dd-9e88-41ff-8c51-5656ebe5d08d.png)

After
![image](https://user-images.githubusercontent.com/19361017/213928836-fbad1370-e527-4a1d-af3c-98cc1f781b5d.png)

## Testing
Enter Deltastation, power the SMESes, the RD's office is now getting charged.

## Changelog
:cl:
fix: All APCs now in research department on Deltastation are now propely connected.
/:cl:

2023-01-23 10:02 UTC, S34NW approved these changes
Larger diff is fine here, whoever made the previous edit has some wonky var orders due to their mapediting tool 😠

2023-01-23 10:24 UTC, S34NW requested changes
What mapping tool did you use for your two map PRs? And did you run mapmerge?

There are a lot of variable shuffling edits here.

2023-01-23 11:55 UTC, S34NW approved these changes

2023-02-15 20:18 UTC, farie82 approved these changes

2023-02-15 20:19 UTC, merged