janicart (pimpin' ride) tweaks
ParadiseSS13/Paradise pull request #20369
Opened 2023-02-05 21:04 UTC by Henri215

## What Does This PR Do

You can now add trash directly to a trashbag attached to the pimpin' ride.
You can no longer waste multiple bags and upgrades by inserting lots of them.

## Why It's Good For The Game

Having to remove the trashbag from the vehicle to use it is too clunky, it should work like the janicart.

## Testing

- Tried to insert more than one trashbag, received failure message
- Deposited lots of trash while riding the pimpin' ride
## Changelog
:cl:
tweak: You can now add trash directly to a trashbag attached to the pimpin' ride
fix: Pimpin' ride: You can no longer waste multiple bags and upgrades by inserting lots of them
/:cl:

2023-02-08 15:30 UTC, S34NW requested changes

2023-02-08 15:30 UTC, S34NW commented on code/modules/vehicle/janicart.dm
> +			to_chat(user, fail_msg)
same here

2023-02-08 15:45 UTC, Henri215 commented on code/modules/vehicle/janicart.dm
> +			to_chat(user, fail_msg)
Done.

2023-02-08 15:48 UTC, S34NW approved these changes

2023-02-25 06:36 UTC, SteelSlayer approved these changes

2023-02-25 06:37 UTC, merged