Suppressors now can be attached to toy guns
ParadiseSS13/Paradise pull request #20415
Opened 2023-02-12 20:06 UTC by Henri215

## What Does This PR Do

Suppressors now can be attached to the foam force enforcer, SMG, pistol and donksoft SMG.

Sprites by @ATP-Engineer 
## Why It's Good For The Game

Hopefully this will make suppressors more valuable to antags and non-antags.
## Images of changes

https://user-images.githubusercontent.com/77684085/218334163-1f79dd7a-ef2a-4e06-b167-bdfa997fc7c8.mp4

## Testing

- See video above
## Changelog
:cl: Henri237, ATP Engineer
tweak: Suppressors now can be attached to toy guns
/:cl:

2023-02-12 23:26 UTC, Bm0n commented
I don't think a toy gun should make the same sound as a suppressed firearm because someone screwed a suppressor onto it

If anything it should still sound like a toy.

2023-02-13 01:04 UTC, Henri215 commented
> I don't think a toy gun should make the same sound as a suppressed firearm because someone screwed a suppressor onto it
> 
> If anything it should still sound like a toy.

It is now the same sound but with the volume lowered because of suppression, check the new video.

2023-02-13 05:34 UTC, procdrone commented
> I don't think a toy gun should make the same sound as a suppressed firearm because someone screwed a suppressor onto it
> 
> If anything it should still sound like a toy.

Aint like all the toy's normal sounds exactly the same as their real versions? Esword deploying for instance, these shots sound real too.

2023-02-13 05:38 UTC, Bm0n commented
> > I don't think a toy gun should make the same sound as a suppressed firearm because someone screwed a suppressor onto it
> > If anything it should still sound like a toy.
> 
> Aint like all the toy's normal sounds exactly the same as their real versions? Esword deploying for instance, these shots sound real too.

ah probably me conflicting my memory of tg with para again

they sound like actual nerf guns on TG, all of them

2023-02-13 10:21 UTC, Henri215 commented
> > > I don't think a toy gun should make the same sound as a suppressed firearm because someone screwed a suppressor onto it
> > > If anything it should still sound like a toy.
> > 
> > 
> > Aint like all the toy's normal sounds exactly the same as their real versions? Esword deploying for instance, these shots sound real too.
> 
> ah probably me conflicting my memory of tgTGwith para again. they sound like actual nerf guns on TG, all of them
> 
> i still think that's probably the right way to go, make them not sound like actual guns

We have no proper toy gun sounds, they simply have different sounds from their real versions to differentiate.

2023-02-15 14:50 UTC, GDNgit requested changes

2023-02-15 15:00 UTC, Henri215 commented on code/modules/projectiles/guns/projectile/toy.dm
> +	can_suppress = TRUE
Done

2023-02-27 21:56 UTC, SteelSlayer approved these changes

2023-03-04 08:44 UTC, farie82 approved these changes

2023-03-04 08:44 UTC, merged