tweaks the MK-II (stock) Ripley to be quicker then the specialized, fire-fighting variant
ParadiseSS13/Paradise pull request #20466
Opened 2023-02-21 11:25 UTC by githubuser4141

## What Does This PR Do
Changes the MK1 Ripley's indoors and outdoors speeds to be 3 and 1.75 respectively.

## Why It's Good For The Game

Gives robo's a reason to build the regular (yellow) Ripley over the Firefighter - which is supposed to be a specialized variant for fighting fires, not outright superior in almost all respects to the stock model. (The firefighter has, more HP, much more armour and is lavaproof over the MK1. Let's make the MK1 a little speedier.)

## Testing
None.

## Changelog
:cl:
tweak: Aliens fans rejoice! The yellow, stock 'powerloader Ripley' is moderately quicker compared to it's more specialized cousin.
/:cl:

2023-02-21 13:18 UTC, Sirryan2002 commented on code/game/mecha/working/ripley.dm
> +	var/slow_pressure_step_in = 3 //step_in while in better pressure conditions
```suggestion
	/// step_in while in normal pressure conditions
	var/fast_pressure_step_in = 1.75
	/// step_in while in better pressure conditions
	var/slow_pressure_step_in = 3
```

2023-02-24 21:50 UTC, farie82 commented
> githubuser4141

Be sure to get your account linked so the PR can get handled properly. Shouldn't take too long

2023-02-24 23:45 UTC, Denthamos commented
How much quicker is quicker?  Two gif's/video's showing the speed differences would help in understand just how this would impact in game as speed is the strongest tool/weapon available in game.

2023-02-26 13:25 UTC, githubuser4141 commented
> How much quicker is quicker? Two gif's/video's showing the speed differences would help in understand just how this would impact in game as speed is the strongest tool/weapon available in game.

Er.. the Ripley's current speed is 4, this changes it to 3, same speed as a Gygax on slowmode.

For reference, the APLU's speed in lavaland/space is 2, same as the Phazon's speed. Mechs don't have strafe here, so.. this is mostly a flavour change and shouldn't have significantly affect combat balance.

2023-03-30 00:02 UTC, Sirryan2002 commented
placing approval on this PR, would like to see videos showing the new speed of the ripley preferably before merge

2023-03-30 00:23 UTC, Henri215 commented
> placing approval on this PR, would like to see videos showing the new speed of the ripley preferably before merge


https://user-images.githubusercontent.com/77684085/228696844-b032e6de-1daf-4f84-ad52-d2acdf1b53ff.mp4

2023-03-30 00:28 UTC, Henri215 requested changes
Fire-fighting version is using MK-II speeds too, please override it with these values.
![image](https://user-images.githubusercontent.com/77684085/228697337-9d76757c-dcab-4466-9a3e-81147c7ff301.png)

2023-04-23 18:08 UTC, hal9000PR commented
No response in 2 weeks. Filing as closed

2023-04-23 18:08 UTC, closed without merging