Fixes gamma armoury hatch cheese
ParadiseSS13/Paradise pull request #20479
Opened 2023-02-23 12:51 UTC by S34NW

## What Does This PR Do
Changes gamma armoury hatches from weird airlock subtypes to impassable blast doors, operated solely when the shuttle is moved.
Makes impassable blast doors unable to be pried when power is off. (why was this a thing?)

## Why It's Good For The Game
Being able to bypass armoury rwalls by tinkering with a single door is a no-no. This finally fixes it.

## Testing
Tried prying blast doors

## Changelog
:cl:
tweak: Tweaked gamma armoury hatch to be a blast door
/:cl:

2023-02-25 10:25 UTC, Miraviel requested changes
The Door Runtime medium event affects this blast door and nobody (AI, door remote, crowbarring) can interact with it, meaning that once the event runs, the armory is permanently spaced by the new hatch. Once all the other airlocks close, this hatch remains open.

To reproduce:

1. (Optional) Set the timer in `/datum/event/door_runtime/start()` from `90 SECONDS` to something like `5 SECONDS`
2. Go to Event Manager
3. Set medium event to Door Runtime
4. Run event

2023-02-26 21:36 UTC, S34NW commented
> The Door Runtime medium event affects this blast door and nobody (AI, door remote, crowbarring) can interact with it, meaning that once the event runs, the armory is permanently spaced by the new hatch. Once all the other airlocks close, this hatch remains open.
> 
> To reproduce:
> 
>     1. (Optional) Set the timer in `/datum/event/door_runtime/start()` from `90 SECONDS` to something like `5 SECONDS`
> 
>     2. Go to Event Manager
> 
>     3. Set medium event to Door Runtime
> 
>     4. Run event

Thanks, I forgot this affected ALL door subtypes that are powered. This has now been fixed.

2023-03-19 21:56 UTC, lewcc approved these changes
Looks good

2023-03-26 20:07 UTC, SteelSlayer approved these changes

2023-03-26 20:08 UTC, merged