fixes a forcebolt runtime
ParadiseSS13/Paradise pull request #20501
Opened 2023-02-26 04:20 UTC by GDNgit

## What Does This PR Do
fixes this runtime:
```
[2023-02-25T22:20:10] Runtime in force.dm,16: undefined proc or verb /turf/simulated/wall/indestructible/syndicate/throw at(). 
   proc name: on hit (/obj/item/projectile/forcebolt/on_hit)
   src: the force bolt (/obj/item/projectile/forcebolt)
   src.loc: the floor (225,139,1) (/turf/simulated/floor/plasteel)
   call stack:
   the force bolt (/obj/item/projectile/forcebolt): on_hit
   the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
   the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
   the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
   the force bolt (/obj/item/projectile/forcebolt): Bump
   the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): Enter
   the force bolt (/obj/item/projectile/forcebolt): Move
   the force bolt (/obj/item/projectile/forcebolt): pixel_move
   the force bolt (/obj/item/projectile/forcebolt): process
   Projectiles (/datum/controller/subsystem/processing/projectiles): fire
   Projectiles (/datum/controller/subsystem/processing/projectiles): ignite
   Master (/datum/controller/master): RunQueue
   Master (/datum/controller/master): Loop
   Master (/datum/controller/master): StartProcessing
```
## Why It's Good For The Game
turfs? Never heard of them

2023-02-28 19:01 UTC, S34NW approved these changes

2023-03-08 19:33 UTC, farie82 approved these changes

2023-03-08 19:33 UTC, farie82 requested changes

2023-03-08 19:33 UTC, farie82 commented on code/modules/projectiles/projectile/force.dm
> +/obj/item/projectile/forcebolt/on_hit(atom/movable/target, blocked = 0)
```suggestion
/obj/item/projectile/forcebolt/on_hit(obj/target, blocked = 0)
```
Why not fully make it an `/obj`?

2023-03-08 19:35 UTC, GDNgit commented on code/modules/projectiles/projectile/force.dm
> +/obj/item/projectile/forcebolt/on_hit(atom/movable/target, blocked = 0)
Because mobs are affected by it

2023-03-08 19:37 UTC, farie82 commented on code/modules/projectiles/projectile/force.dm
>  		T.throw_at(get_edge_target_turf(target, throwdir),10,10)
```suggestion
		var/throwdir = get_dir(firer, target)
		target.throw_at(get_edge_target_turf(target, throwdir), 10, 10)
```

2023-03-13 22:18 UTC, AffectedArc07 approved these changes

2023-03-13 22:18 UTC, merged