Helper crystal is now a point of interest
ParadiseSS13/Paradise pull request #20516
Opened 2023-02-27 22:37 UTC by GDNgit

## What Does This PR Do
See title, becomes a POI when activated by someone (spawns you in as a lightgeist on click)

## Why It's Good For The Game
ghosts should actually know that it exists

## Changelog
:cl:
tweak: Helper crystal is now a point of interest
/:cl:

2023-03-08 10:37 UTC, S34NW requested changes

2023-03-08 10:37 UTC, S34NW commented on code/modules/mining/lavaland/loot/colossus_loot.dm
> +	GLOB.poi_list.Remove(src)
```suggestion
	GLOB.poi_list -= src
```

2023-03-08 17:41 UTC, Sirryan2002 reviewed
see S34N's requests otherwise this is good

2023-03-08 21:31 UTC, S34NW approved these changes

2023-03-13 20:57 UTC, farie82 approved these changes

2023-03-13 21:36 UTC, merged