Adds a cooldown for setting alert level through comms console
ParadiseSS13/Paradise pull request #20539
Opened 2023-03-04 07:01 UTC by lewcc

## What Does This PR Do
Adds a 1 minute cooldown for changing the alert level at a comms console.

## Why It's Good For The Game
Players can currently change the alert level really really fast and it's really really annoying, borderline deafening and spamming chat.

## Testing
Tried to change the alert level, got cooled down.

## Changelog
:cl:
tweak: The communications console now has a 1m delay between changes of alert level.
/:cl:

2023-03-08 18:30 UTC, Sirryan2002 approved these changes

2023-03-08 18:30 UTC, Sirryan2002 commented on code/game/machinery/computer/communications.dm
> +	var/alert_level_cooldown
```suggestion
	var/alert_level_cooldown = 0
```

2023-03-13 22:32 UTC, AffectedArc07 requested changes
Do Sirryan's change please

2023-03-15 19:37 UTC, lewcc commented on code/game/machinery/computer/communications.dm
> +	var/alert_level_cooldown
Addressed

2023-03-18 17:32 UTC, lewcc commented
Changes addressed

2023-03-22 21:36 UTC, merged