Allows admins to freeze the SM
ParadiseSS13/Paradise pull request #20616
Opened 2023-03-11 07:03 UTC by Coolrune206

## What Does This PR Do

Allows the admin freeze verb to also affect Supermatter Crystals, both the primary engine and shards, which prevents it from processing (and thus decreasing in integrity). Additionally, if frozen while in the 30-seconds before delamination, it returns the crystal to a single damage point before the explosion point is reached, so that the timer fully restarts after being unfrozen. Nothing changes to the integrity upon being unfrozen, so admins can change it back up while frozen if they determine the SM was sabotaged by a griefer or whatnot. 
It also gives a message over engineering comms (where the SM normally announces) indicating that an unknown force has frozen the SM, and overlays the crystal itself with an adminfreeze overlay. Hopefully this is sufficient to indicate to players that admin-stuff is happening.
## Why It's Good For The Game

Admins being able to handle people sabotaging the SM when they're not supposed to is good. From what I can tell, previously either you'd VV the processes variable to FALSE if you understood how the SM worked code-wise or you'd just delete it and make a new one if you had to fix it for admin reasons.
## Testing

Tested it, it works.
## Changelog
:cl:
tweak: Admins can now Freeze the SM Crystal
/:cl:

2023-03-14 14:55 UTC, Komrad822 commented
SM monitoring computer should also have an indicator or something for if its frozen, Mainly since while delamming, its a key way to see whats up without having to go into the chamber which can be quite the hostile environment with anomalies and the heat they generate. 

Side note thats likely out of scope of this PR: Griefing of the SM and thus freezing basically means "this shouldnt have happened, we arent allowing it to continue nor negatively affect the round." THUS if lets say a thermo-anomaly appeared and a slime was spawned, the sm is frozen at this state, whats everyone's thoughts on those persisting in the round and causing grief?

2023-03-15 11:39 UTC, S34NW approved these changes

2023-03-26 11:01 UTC, hal9000PR requested changes

2023-03-26 11:01 UTC, hal9000PR commented on code/modules/admin/verbs/freeze.dm
> +		overlays += freeze_overlay
use add_overlay and remove_overlay please

2023-03-27 19:10 UTC, farie82 commented on code/modules/admin/verbs/freeze.dm
> +		GLOB.frozen_atom_list += src
You'll need to ensure this also gets removed when the crystal gets destroyed.

2023-04-09 19:52 UTC, Sirryan2002 commented
Could you please address Farie's requested changes?

2023-04-13 14:36 UTC, farie82 approved these changes

2023-04-13 14:37 UTC, merged