constructs can no longer change intents
ParadiseSS13/Paradise pull request #20624
Opened 2023-03-12 02:52 UTC by GDNgit

## What Does This PR Do
constructs can no longer change intents

## Why It's Good For The Game
Not only does this seem unintended because they don't have the ability to use an on screen intent changer, but using help intent as a construct does literally nothing. People accidently swapping intents through hotkeys and becoming fucking useless as a construct sucks, so let's yeet it!
## Testing
Compiled and ran
## Changelog
:cl:
tweak: Constructs can no longer change intents
/:cl:

2023-03-12 14:51 UTC, lewcc commented
Why not just make intent visible for constructs (and any other simple mobs where it isn't)? Sometimes you want the help movement swapping

2023-03-12 14:53 UTC, GDNgit commented
> Why not just make intent visible for constructs (and any other simple mobs where it isn't)? Sometimes you want the help movement swapping

I thought about it and realized a construct constantly nuzzling people and going "hehe im a friendly construction" would give me an aneurysm.

And honestly they can just crawl under you or just position better

2023-03-13 22:43 UTC, Fox-McCloud requested changes
seconding @lewcc

2023-03-14 01:04 UTC, matttheficus commented
Agree with Lewcc and Fox. Being able to Help Move in a constricted cult base is VERY much required.

2023-03-14 01:54 UTC, GDNgit commented
closing in favor of #20636

2023-03-14 01:54 UTC, closed without merging