Corrects cash input text for arcade machines
ParadiseSS13/Paradise pull request #20827
Opened 2023-04-06 05:08 UTC by silverplatedelta

## What Does This PR Do
Fixes #20408 
Arcade machines now show the proper amount of space cash when cash is inserted.

## Why It's Good For The Game
Players should not panic thinking they sacrificed their life savings to THE CLAAAAWWWW.

## Testing
Insert cash into claw machine. VV edit claw machine to change token cost. Confirm cash inserted value is changed. 

## Changelog
:cl:
When inserting cash to arcade machines, the amount inserted is now properly shown.
/:cl:

2023-04-06 05:48 UTC, Sirryan2002 requested changes
just change Line 80 in economy_machinery.dm to this:
```dm
visible_message("<span class='info'>[user] inserts [amount_to_insert] credits into [src].</span>")
```
it'll do exactly what you want without changing base behavior so you don't have to use duplicate code. Also in the future, you can just override the `insert_cash` proc on the arcade level instead of creating a whole new proc on the economy machinery base.
```dm
/obj/machinery/economy/arcade/insert_cash()
```

2023-04-06 06:16 UTC, silverplatedelta commented
> 

That is a much easier way of doing things. Ill keep this in mind in the future!

2023-04-06 11:13 UTC, Henri215 commented
Fix: When inserting cash to arcade machines, the amount inserted is now properly shown
Changelog should have the "Fix:".

Doing like this wont allow for "inserts 1 credits"?

2023-04-06 12:10 UTC, Sirryan2002 approved these changes

2023-04-06 12:11 UTC, Sirryan2002 commented
> Fix: When inserting cash to arcade machines, the amount inserted is now properly shown Changelog should have the "Fix:".
> 
> Doing like this wont allow for "inserts 1 credits"?

they would just need to specify a trinary check
`[amount_to_insert == 1 ? "[amount_to_insert]" credit : "[amount_to_insert]" credits]"

2023-04-07 13:29 UTC, hal9000PR commented
would you update your changelog to be in the proper form? check other fix PRs for examples.

2023-04-22 07:27 UTC, farie82 approved these changes

2023-04-22 07:43 UTC, merged