Update reagentgrinder.dm - fixes #20841
ParadiseSS13/Paradise pull request #20853
Opened 2023-04-10 15:55 UTC by Peterrrrrrrr

## What Does This PR Do

Updates the juicer to create blumpkin juice when blumpkins are juiced, rather than pumpkin juice

changed the listing on blumkin juice to be above pumpkin juice

fixes #20841

## Why It's Good For The Game

fixes issue #20841

## Images of changes

## Testing

tested on local setup
## Changelog
:cl:

fix: Fixed a few things - fixes #20841

/:cl:

2023-04-14 20:06 UTC, S34NW approved these changes

2023-04-22 07:38 UTC, farie82 commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		/obj/item/reagent_containers/food/snacks/grown/pumpkin = list("pumpkinjuice" = 0),
Can you add a comment telling the reader why the order is important here? I also noticed line 77 and 78. The lather probably isn't needed right?

2023-05-22 19:43 UTC, farie82 commented
Please handle the review comment within a week or the PR will be closed for inactivity. You can reopen the PR at a later date if this happens.

2023-06-02 19:01 UTC, S34NW requested changes
Stale PR, please see other comments.

2023-06-03 00:45 UTC, SteelSlayer commented
Closing this PR due to it being stale. Feel free to reopen or make another PR if you'd like.

2023-06-03 00:45 UTC, closed without merging