[WIP] Lets the rnd server controller actually have use in blacklisting
ParadiseSS13/Paradise pull request #21034
Opened 2023-05-05 18:14 UTC by Qwertytoforty

## What Does This PR Do

Research datums have 2 new lists. The blacklisted list, and the unblacklisted list.
Instead of deleting a design (which currently does nothing RND wise, since once the servers link, the tech levels restore the design), RD can blacklist designs with the R&D server controller. This prevents a design from being printed from linked protolathes / circuit imprinters. A new rnd setup could still build said design.

The console can also unblacklist a design, allowing rnd to have it once again once the rnd console syncs again.

## Why It's Good For The Game

The delete functioning being changed to something that works is useful. It allows silent sabatoge by an antagonistic traitor or AI, who can delete a certain design from rnd, to prevent the crew from making it. Shame that the illegals tech doesnt let security get a silencer. Shame that there is no ai upload board design. Crew building a phazon that will screw you over? Shame there is no weapon control board design for the phazon anymore. ect.

It also allows the RD / captain to restrict items that are being abused. Scientists trespassing everywhere with jaws of life? Blacklist it. Quantum pads everywhere and people are spacing themself with bags of holding? Blacklist it.

This is more or less what the delete function is for, now it mostly(*tm) works.

## TODO

- [ ] Somehow, after blacklist is reverted, after 2 syncs from the rnd console, it returns. I suspect it is the blacklist surviving on the robotics server? CC server? Look into this.

## Testing

Ensured deleting and restoring, as well as rnd in general, worked. (See TODO)

## Changelog
:cl:
tweak: The RND server computer can now blacklist rnd designs from protolathes, circuit imprinters, and mech fabricators.
/:cl:

2023-05-07 15:23 UTC, AffectedArc07 commented
I'll need to take this into account in the rework
---
Maybe this will motivate me to continue the damn rework

2023-05-19 06:03 UTC, Sirryan2002 commented on code/modules/research/research.dm
> +				known_designs -= v
I wonder if you could just instead do this here
```dm
	if(length(blacklisted_designs)) //No need to run this unless there are blacklisted designs
		known_designs -= blacklisted_designs
```

2023-05-19 16:06 UTC, Sirryan2002 commented on code/modules/research/rdconsole.dm
> +		temp_unblacklist += v
```suggestion
	var/list/temp_unblacklist = files.unblacklisted_designs
```
pretty sure you can just do this

2023-05-19 16:06 UTC, Sirryan2002 commented on code/modules/research/rdconsole.dm
> +				S.files.blacklisted_designs -= v
```suggestion
			S.files.blacklisted_designs -= temp_unblacklist
```

2023-05-19 16:06 UTC, Sirryan2002 commented on code/modules/research/research.dm
> +		other.blacklisted_designs += v
```suggestion
	other.blacklisted_designs += (blacklisted_designs - other.blacklisted_designs)
```

2023-06-05 14:05 UTC, S34NW requested changes
Please see outstanding review suggestions

2023-06-05 22:11 UTC, Sirryan2002 approved these changes

2023-06-07 19:32 UTC, S34NW approved these changes

2023-06-07 19:32 UTC, merged