Removes bio resist from the code
ParadiseSS13/Paradise pull request #21108
Opened 2023-05-16 23:15 UTC by DGamerL

## What Does This PR Do
Removes all mention of bio resist, as it's not used for any kind of damage afaik.

## Why It's Good For The Game
Less useful code is good, saves work for newer items and sets of armour.

## Testing
Booted up a test server, compiled with no errors or warnings.

## Changelog
:cl:
del: Removed unused bio resist code
/:cl:

2023-05-18 07:56 UTC, S34NW commented
Well how dumb, all this time I assumed this was what prevented disease spread, but no. That is handled by `permeability_coefficient` on the item defending against disease. Good work finding this.

2023-05-23 01:45 UTC, Sirryan2002 approved these changes

2023-06-02 17:50 UTC, S34NW requested changes
Please deconflict

2023-06-03 08:49 UTC, S34NW approved these changes

2023-06-03 08:50 UTC, merged