Adds Atmos Access to SM chamber doors
ParadiseSS13/Paradise pull request #21120
Opened 2023-05-18 16:59 UTC by Bjamcham

## What Does This PR Do
Atmospherics access has now been added to the two SM chamber doors on Meta, Cere, and Box. Delta SM chamber doors already had both atmospherics and engineering access. Door placement and all other features remain the same, only the door access should have changed. 

## Why It's Good For The Game
The SM is heavily based in atmospherics while the air alarm that controls the chamber devices and access to the chamber is locked to atmos techs, preventing them from fully setting the engine up or correcting issues in a pinch without hacking through one or two doors. This standardizes the chamber access across all of the maps to align with delta.

## Images of changes
Access change, maps are unchanged visually

## Testing

## Changelog
:cl:
tweak: Tweaked the SM chamber doors to now include atmospherics access
fix: Fixed a few things
/:cl:

2023-06-07 15:04 UTC, Git-GoR commented
It would be better if instead of varediting the access to the airlocks directly, you replaced it with the mapping helpers for it. They are the "new" way of doing it, for futureproofing. 
You can find them under `obj/effect/mapping_helpers/airlock/access/any/engineering/`. There's `general` for Engineering access, and `atmos` you can imagine what it is for. Keep in mind that there is `.../access/any/...`, which requires one of the listed accesses, and `...access/all/...` which requires them all. For this you would want to use the former.
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/9b574004-a1c3-4591-b936-101b84895203)


In fact, in Metastation there is already an `all` mapping helper on those airlocks for Engineering access. Remember to remove it before you replace it by the `any` versions, as having both types on the same airlock causes problems.
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/2d57d7c6-4cf0-4d70-8196-b8fec11a3ea6)

2023-06-19 19:09 UTC, Sirryan2002 requested changes
yes, please use the map helpers

2023-06-21 22:23 UTC, S34NW requested changes
Need those mapping helpers please. You now lead the queue.

2023-06-21 22:25 UTC, S34NW approved these changes
User cannot access their PC to make requested changes. @warriorstar-orion plans to sweep up missing helpers soon anyway. Merging to move queue.

2023-06-21 22:26 UTC, merged