Digital Camouflage now makes you fully invisible to the AI
ParadiseSS13/Paradise pull request #21184
Opened 2023-05-27 03:49 UTC by GDNgit

## What Does This PR Do
Digital Camouflage now makes you fully invisible to the AI, as well as untrackable

## Why It's Good For The Game
Complete meme ability rn, not useful in the slightest. Congrats on your worse agent ID that marks you off as being KOS if the AI realizes what's up. It's bad, so let's make it better.

Peak shot me this idea over discord and I thought it was pretty good, having counterplay against the AI as an antag is nice, but not too powerful if sec is doing well (especially in an antag like cling that's so melee focused). This will force up sec and the AI to change up tactics a bit, and it should be fun for both parties. Won't help you too much in an ai steal situation though, you can't hide thermite and tool sounds. 

## Testing
"oh no where did mr cling go :("
## Changelog
:cl:
tweak: Digital Camouflage now makes you fully invisible to the AI
/:cl:

2023-05-27 22:34 UTC, procdrone commented
does the camouflage also makes the clings invisible to cyborgs (and drones)?

2023-05-27 22:34 UTC, GDNgit commented
> does the camouflage also makes the clings invisible to cyborgs (and drones)?

no

2023-06-02 08:49 UTC, S34NW requested changes

2023-06-02 08:49 UTC, S34NW commented on code/modules/antagonists/changeling/powers/digitalcamo.dm
> +		user.invisibility = 25
```suggestion
		user.invisibility = SEE_INVISIBLE_LIVING
```

2023-06-05 18:07 UTC, Sirryan2002 approved these changes

2023-06-14 20:43 UTC, S34NW approved these changes

2023-06-14 20:43 UTC, merged