New sprite for the inflatables box
ParadiseSS13/Paradise pull request #21196
Opened 2023-05-29 17:48 UTC by DGamerL

## What Does This PR Do
Adds a new sprite for the inflatables box.

## Why It's Good For The Game
Old sprite looked shitty, other server made better sprite, so why not use that?

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/3fa5371f-eae1-4af2-8e4c-78b1e4177536)

## Testing
Loaded up ye olde server, my eyes didn't need bleach.

## Changelog
:cl:
imageadd: Added new inflatable box sprite
imagedel: Deleted old inflatable box sprite
/:cl:

2023-06-02 08:41 UTC, S34NW approved these changes

2023-06-03 01:28 UTC, DGamerL commented
This deleted the nanny bag sprites, I'll re-add them tomorrow when I have time and it's not 3 AM.

2023-06-03 10:03 UTC, DGamerL commented
Sprites are added back, it should all be fine now

2023-06-16 16:52 UTC, Sirryan2002 requested changes
will approve this PR once my concerns are addressed:

- I'm guessing this was yoinked from a server with an cc-by-sa 3.0 license
- IF so, you need to credit the author in the changelog and credit the author / server codebase in the PR description so we are being license compliant

2023-06-16 18:32 UTC, merged