Makes Farragus MedChem slightly bigger
ParadiseSS13/Paradise pull request #21258
Opened 2023-06-06 23:34 UTC by DGamerL

## What Does This PR Do
Adds an extra tile of length to Farragus Medchem. Also pushes maints down one tile.

## Why It's Good For The Game
Currently, medchem on Farragus is very tiny and you have a 1 length path that you can walk through. Making medchem not tiny is a simple but effective QOL change for chemists.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/2ec4f693-557c-4dc5-a84e-47977622e9fe)
Note: The crate has been moved two tiles up, but this screenshot was made before that

## Testing
Went into DreamMaker, compiled maps and checked if my changes went through.
VSC had a compiling issue and didn't show half the map.

## Changelog
:cl:
tweak: Farragus Medchem is now slightly bigger.
/:cl:

2023-06-21 22:40 UTC, S34NW requested changes
- Two light switches here
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/cfba1294-800e-4d04-8557-0fbe927f0030)

- Please pull the requests console up one, hard to see right now in editor
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/aed6effd-4e47-43ab-8666-8f73143aa208)

2023-06-22 17:24 UTC, Sirryan2002 approved these changes

2023-06-22 17:28 UTC, S34NW approved these changes

2023-06-22 17:28 UTC, merged

2023-06-22 17:28 UTC, SynthTwo commented
WE WON!!!!!!!