Adds the name of the occupant to the examine text of sleepers and body scanners
ParadiseSS13/Paradise pull request #21324
Opened 2023-06-13 08:06 UTC by Divulf

## What Does This PR Do
Adds the name of the occupant to the examine text of sleepers and body scanners.   The new description also tells you if the occupant inside is dead or not.  Concealed identities will remain concealed.

## Images of changes
![sleeper1](https://github.com/ParadiseSS13/Paradise/assets/134484326/3f88b6f0-cfaf-46e3-ae4c-1ecca4807201)
![sleeper2](https://github.com/ParadiseSS13/Paradise/assets/134484326/85f66bb9-4aca-4145-b1fc-f3763dacb92b)

## Testing
Stuffed Pun Pun into sleeper and body scanner while both alive and dead.

## Changelog
:cl:
add: Name of the occupant to the examine text of sleepers and body scanners 
/:cl:

2023-06-13 08:08 UTC, Contrabang requested changes
Good idea

2023-06-13 08:08 UTC, Contrabang commented on code/game/machinery/Sleeper.dm
> +			. += "You see [occupant.name] inside."
Could you use `<span class='notice'>` here to differentiate this from the rest of the examine text?

2023-06-13 08:08 UTC, Contrabang commented on code/game/machinery/adv_med.dm
> +			. += "You see [occupant.name] inside."
same here

2023-06-13 08:52 UTC, Divulf commented
![cryo-cell](https://github.com/ParadiseSS13/Paradise/assets/134484326/dacec4db-ec40-43e3-9367-a3f999ed127c)

2023-06-27 22:49 UTC, Denthamos commented
Does it only show the name of the person if their face and/or ID is present and visible?  Does it show a persons name despite having a full mask on and no ID?

2023-06-30 04:09 UTC, Divulf commented
> Does it only show the name of the person if their face and/or ID is present and visible? Does it show a persons name despite having a full mask on and no ID?

It uses their apparent name, same as examining the subject normally.

2023-07-05 22:47 UTC, lewcc reviewed
Denth si

2023-07-05 22:47 UTC, lewcc commented on code/game/machinery/Sleeper.dm
> +			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE, FALSE)] is dead!</span>"
I did some diving, and `occupant.name` itself is indeed updated on human life, so we thankfully don't need to check if they're hidden or not.
Only other thing is that I'm not sure why you're passing `FALSE` in for the temp gender (second argument). For humans, it gets overridden by `get_visible_gender()` anyway, so I'm pretty sure it's unnecessary.

Anyway, please make these sorts of changes through all the instances in the PR.
```suggestion
			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE)] [occupant.p_are()] dead!</span>"
```

2023-07-05 22:47 UTC, lewcc commented on code/game/machinery/adv_med.dm
> +			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE, FALSE)] is dead!</span>"
```suggestion
			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE)] [occupant.p_are()] dead!</span>"
```

2023-07-05 22:47 UTC, lewcc commented on code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
> +			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE, FALSE)] is dead!</span>"
```suggestion
			. += "<span class='warning'>You see [occupant.name] inside. [occupant.p_they(TRUE)] [occupant.p_are()] dead!</span>"
```

2023-07-06 02:17 UTC, Divulf commented
![are](https://github.com/ParadiseSS13/Paradise/assets/134484326/d4c4a31e-eab3-4142-9336-03ce9fea864e)

2023-07-07 12:56 UTC, S34NW approved these changes

2023-07-07 12:56 UTC, merged