adds a little extra security to shuttle manip var-editing
ParadiseSS13/Paradise pull request #21374
Opened 2023-06-17 20:05 UTC by GDNgit

## What Does This PR Do
See title, makes sure that the vars or var_edited variables are never edited

## Why It's Good For The Game
Intended functions are good, although this shouldn't happen in normal gameplay

## Changelog
NPFC

2023-06-19 18:40 UTC, Sirryan2002 approved these changes

2023-06-19 18:41 UTC, Sirryan2002 requested changes

2023-06-19 18:41 UTC, Sirryan2002 commented on code/modules/shuttle/shuttle_manipulator.dm
>  		if("shuttle_and_preview_cooldown")
actually... on the `vv_edit_var` base proc please add this line of code to the very first line
```dm
SHOULD_CALL_PARENT(TRUE)
```

2023-06-19 18:48 UTC, Sirryan2002 approved these changes

2023-06-21 22:15 UTC, S34NW approved these changes

2023-06-21 22:16 UTC, merged