The Mediborgs can now evil chem
ParadiseSS13/Paradise pull request #21401
Opened 2023-06-19 05:11 UTC by Alantodne

## What Does This PR Do

## Why It's Good For The Game

## Images of changes

## Testing

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: Tweaked a few things
fix: Fixed a few things
wip: Added a few works in progress
soundadd: Added a new sound thingy
sounddel: Removed an old sound thingy
imageadd: Added some icons and images
imagedel: Deleted some icons and images
spellcheck: Fixed a few typos
experiment: Added an experimental thingy
/:cl:

2023-06-28 14:35 UTC, S34NW requested changes

2023-06-28 14:35 UTC, S34NW commented on code/game/objects/items/robot/robot_upgrades.dm
> +		F.emag_act()
```suggestion
/obj/item/borg/upgrade/abductor_medi/after_install(mob/living/silicon/robot/R)
	. = ..()
	if(!R.emagged) // Emagged Mediborgs that are upgraded need the evil chems.
		return
	for(var/obj/item/reagent_containers/borghypo/F in R.module.modules)
		F.emag_act()
	
```

You could probably simplify this and remove the need for a timer by letting the parent chain work first? Please do test this first before committing.

2023-06-29 21:06 UTC, S34NW approved these changes

2023-06-29 21:09 UTC, S34NW commented
Approved but still needs sprite team approval since you touch on sprites

2023-07-01 07:58 UTC, farie82 approved these changes

2023-07-01 08:41 UTC, merged