Ear Organ Refactor + Deafness is a status effect
ParadiseSS13/Paradise pull request #21405
Opened 2023-06-19 22:05 UTC by BiancaWilkson

## What Does This PR Do

This PR brings ears in line with how other organs deal, and heal from damage. They can now die like any other organ, and won't work until healed via surgery if they do die.

Additionally, temporary deafness has been changed to be a status effect.
## Why It's Good For The Game

Consistency in how organs work is good, and being able to actually see how damaged ears are when scanning is also good. 
The justification for removing natural healing is that even though ears do take (invisible) damage, you would never notice because by the time you get un-deafened most of the damage you'd already taken has healed up.

## Testing

Made sure things that dealt ear damage still did, killed the ears of a few skrells, then fixed them back to make sure they worked again. Also made sure I didn't accidentally make everyone deaf permanently.

After the status effect changes, more testing needs to be done.
## Changelog
:cl:
del: Ears no longer heal passively.
Fix: Ears now take damage like every other organ, and ear damage shows up on body scanners.
/:cl:

2023-06-22 20:20 UTC, lewcc requested changes

2023-06-22 20:20 UTC, lewcc commented on code/modules/surgery/organs/ears.dm
>  /obj/item/organ/internal/ears/proc/AdjustEarDamage(ddmg, ddeaf)
As you're moving away from this ear damage system, you should do away with `AdjustEarDamage` and `RestoreEars` entirely, and instead replace all their instances with typical organ damage code to keep it standardized. They seem to be fairly snowflaked procs for handling this weird edge case of organ damage. Heads up, there are two different procs for it under `/mob/living/carbon` and `/obj/item/organ/internal/ears` (: 

I think you'll probably want to replace the uses with procs like `E.heal_internal_damage()`, `E.receive_damage()`, and move the deafness stuff into respective overrides.

2023-07-01 08:02 UTC, farie82 approved these changes

2023-07-01 08:04 UTC, farie82 commented
> The scope of this increased a whole lot very fast, it compiles and seemingly works, but I still have a ton of testing I need to do.

Did you manage to test the PR? If so it can be merged, the code as is looks fine as far as I can see. But just be sure that you've tested it as well

2023-07-05 23:02 UTC, lewcc approved these changes
Looks good! I really like how you handled "passive ear healing" to just make it a status effect. Makes a lot more sense now.

2023-07-07 12:54 UTC, merged