Adds tools to all Prisons
ParadiseSS13/Paradise pull request #21426
Opened 2023-06-22 14:47 UTC by DGamerL

## What Does This PR Do
Adds a crowbar in a laundry cart and a screwdriver, wrench and wirecutter in the little maints area of Kerberos and Cerebron, which did not have this.

## Why It's Good For The Game
Consistency across perma is very nice, and sometimes prisoners need an extra boost to escape.

## Images of changes
Soon:tm:

## Testing
Went into DreamMaker, checked if the tools were there.

## Changelog
:cl:
add: Added tools to the permanent prisons of the Kerberos and Cerebron
/:cl:

2023-07-01 20:37 UTC, Sirryan2002 requested changes
Code Review objection until you cleanup the various other edits across the station unrelated to the PR

2023-07-01 20:44 UTC, S34NW commented
You just need to update from master to resolve sirryan's comments

2023-07-01 22:12 UTC, DGamerL commented
Should be all fixed now?

2023-07-19 14:54 UTC, S34NW approved these changes

2023-07-20 18:03 UTC, merged