Adds Hydrocodone to the Syndi Med Duffel
ParadiseSS13/Paradise pull request #21472
Opened 2023-06-26 21:06 UTC by matttheficus

## What Does This PR Do
Adds 30u of Hydrocodone to the Syndi Med Duffel.

## Why It's Good For The Game
If an Agent spends money on surgery tools, they should be able to do said surgery without having to ALSO get Medical Access to steal painkillers. This should make this item SOMETIMES worth taking if in a pinch.

## Testing
Spawned in some bags, it had drugs in it.

## Changelog
:cl:
add: Adds hydrocodone to the syndicate medical duffel bag.
/:cl:

2023-06-26 21:08 UTC, Contrabang requested changes
LGTM

2023-06-26 21:12 UTC, matttheficus commented
Dropped the amount of hydrocodone to 30u.

2023-07-05 23:53 UTC, lewcc approved these changes

2023-07-07 12:41 UTC, S34NW approved these changes

2023-07-07 12:41 UTC, merged