Buffs most stamina drugs. Nerfs meth stamina ***SLIGHTLY***
ParadiseSS13/Paradise pull request #21478
Opened 2023-06-27 02:27 UTC by Qwertytoforty

## What Does This PR Do

Crank heals more stamina and gives less confusion. 25 to 40, with confusion halfed.
Pump up will get you out of stam crit each cycle, but uh, still not great.
Meth now heals 30 stamina per cycle instead of 40.
Bath salts is now craftable realistically with reworked economy, requiring salt instead of mugwort.
Arsnep now gives50% stamina resist instead of 30%. This may make it see use. Maybe.
Surge gets a buff as lets be real, ipcs need it.

## Why It's Good For The Game

None of the other drugs are used.
Crank doesnt heal enough stamina, and confusion is hard to work with.
Pump up already decays fast enough.
Arsnep needs to be combined with other drugs, and could be done better with just meth + crank + hydro for more managable downsides.
Bath salts are perfect.
But require mugwort so you more or less needed to buy money briefcases to make a practical volume of it.

By preforming the above buffs, these drugs may see use. May. Speed is war after all, but I am not reworking meth. Speed is needed. And I don't want to have to rebalance meth donks either. However, it does have 10 less stamina healing than before.

## Testing

I shot myself with disablers while high.

## Changelog
:cl:
tweak: Many drugs have been buffed, with meth taking a nerf. Look at the pr for details.
/:cl:

2023-07-01 08:43 UTC, farie82 commented
Unit tests failing. Can ya fix it, then it can be merged

2023-07-07 12:40 UTC, S34NW requested changes
`Unknown chemical id "salt" in recipe /datum/chemical_reaction/bath_salts`

2023-07-07 17:25 UTC, Qwertytoforty commented
missed the review, sorry!

2023-07-09 16:30 UTC, SeanSproston commented
Seems reasonable to me. Arnesp in particular needs a buff.

2023-07-09 18:37 UTC, SpringSkipper commented
Seems reasonable to me. Arnesp in particular needs a buff.

2023-07-12 16:52 UTC, S34NW approved these changes

2023-07-12 16:52 UTC, merged