Contort body day 1 changes
ParadiseSS13/Paradise pull request #21512
Opened 2023-06-29 22:34 UTC by GDNgit

## What Does This PR Do
Ups the chemical cost from 5 to 25 chemicals (People were swapping this mid combat, which seemed to not be super great)
Takes 2 seconds of staying still to go under an airlock now, windoors can still be gone under easily, both because I can't find a good way to apply a timer there and because most windoor locations are a lot less favorable for break in vs an airlock
Clings with contort form are on a high layer now, so they don't fit under stuff like conveyer belts which can spammed nonstop

## Why It's Good For The Game
Bit overtuned, mostly fine but people using it in active combat has been a little much

## Testing
I hate semidense objects

## Changelog
:cl:
tweak: Contort form costs 25 chems to use compared to 5
tweak: Contort form takes an extra 2 seconds to go under doors now
tweak: Contort form costs can no longer fit under conveyers and some other objects
/:cl:

2023-07-01 07:48 UTC, tipoima commented
Is there really a point to increasing the chemical cost if there is (seemingly) no downside to just turning it on and never turning it off?

2023-07-01 18:04 UTC, GDNgit commented
> Is there really a point to increasing the chemical cost if there is (seemingly) no downside to just turning it on and never turning it off?

Yeah, because it makes it a lot harder to realize someone is a ling while using the ability, or swapping it mid combat to make it a lot harder to hit you

2023-07-05 02:20 UTC, Contrabang requested changes

2023-07-05 02:20 UTC, Contrabang commented on code/modules/antagonists/changeling/powers/contort_body.dm
>  	desc = "We contort our body, allowing us to fit in and under things we normally wouldn't be able to. Costs 5 chemicals."
```suggestion
	desc = "We contort our body, allowing us to fit in and under things we normally wouldn't be able to. Costs 25 chemicals."
```

2023-07-05 02:20 UTC, Contrabang commented on code/modules/mob/living/living_status_procs.dm
> +			layer = BLASTDOOR_LAYER
Im pretty sure this means they won't be able to go under firelocks. Not sure if you want that or not.

2023-07-05 02:20 UTC, Contrabang commented on code/__HELPERS/mob_helpers.dm
> +		if((!drifting && user.loc != user_loc) || target.loc != target_loc || user.get_active_hand() != holding || user.incapacitated() || (requires_upright && L && IS_HORIZONTAL(L)) || check_for_true_call
(general comment) God, this is such a terrible line. It really should be split up into multiple if statements imo

2023-07-07 12:30 UTC, S34NW approved these changes

2023-07-07 12:30 UTC, merged