Pimp my drip
ParadiseSS13/Paradise pull request #21527
Opened 2023-06-30 23:17 UTC by McRamon

## What Does This PR Do
Adds a very expensive coat for crewmembers to wear (costs 1000 cerdits in cargo)

## Why It's Good For The Game
Its very drippy

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/31545294/8cad8f79-93ff-4dbc-9bcc-c0b42aff078c)

## Testing
testing

## Changelog
:cl:
add: New drip for rich guys - expensive coat, can only be ordered i ncargo for 1000 credits
/:cl:

2023-06-30 23:43 UTC, ppi13 commented
Is it so that skrell, taj, vulp, slime, plasma and nian cant wear this? If so, I fully support it!

2023-06-30 23:43 UTC, McRamon commented
> Is it so that skrell, taj, vulp, slime, plasma and nian cant wear this? If so, I fully support it!

they use human sprites :(

2023-06-30 23:51 UTC, ppi13 commented on code/modules/clothing/suits/misc_suits.dm
> +	min_cold_protection_temperature = FIRE_SUIT_MIN_TEMP_PROTECT
```suggestion
	min_cold_protection_temperature = FIRE_SUIT_MIN_TEMP_PROTECT
	species_restricted = list("Human", "Vox", "Drask", "Grey", "Kidan" )
```

2023-07-03 22:42 UTC, Sirryan2002 approved these changes

2023-07-03 22:43 UTC, Sirryan2002 approved these changes

2023-07-07 12:27 UTC, S34NW requested changes
consistency

2023-07-07 12:27 UTC, S34NW commented on code/modules/clothing/suits/misc_suits.dm
> +	body_parts_covered = UPPER_TORSO|ARMS|LOWER_TORSO
```suggestion
	body_parts_covered = UPPER_TORSO | LOWER_TORSO | ARMS
```

2023-07-09 09:08 UTC, S34NW approved these changes

2023-07-25 15:06 UTC, S34NW requested changes
Three weeks with no de-conflict, please get this done so we can merge it

2023-07-31 18:12 UTC, S34NW approved these changes

2023-07-31 18:12 UTC, merged