Makes anomalies deadlier. Again.
ParadiseSS13/Paradise pull request #21525
Opened 2023-06-30 20:42 UTC by Qwertytoforty

## What Does This PR Do

Gravitational anomalies no longer throw items at people inside them as much, meaning they will be more deadly when someone is dead in the middle of it.
Gravitational anomalies from events will short out the gravity generator if not defused, meaning engineering will have to repair it. Fun for the whole family!

Flux anomalies (not from supermatter / vetus) are MUCH deadlier. You will require insulated gloves to defuse this safely. If you have a flux anomaly and you do not have gloves, my advice is to get out of there. It *will* kill you if you don't get away from it.

Bluespace anomalies will now teleport unanchored structures / machines, rather than just items passively, and increases the range of selecting things to teleport by one tile.

Pyro anomalies produced a near meaningless ammount of plasma every 10 seconds. It now produces 4x more plasma each cycle every 8 seconds. As such, it will be slightly more dangerous to be around, but most crew will still be able to defuse it.

Vortex... Well it will break turfs more often, and trip people, stunning them occassionally if event spawned, but due to how it works (look at the grav proc, it's special), you'll probably still be able to disarm it unless you are a slime person

## Why It's Good For The Game

Anomalies should be dangerous. You shouldn't be standing gawking at them while barely being affected.

Gravity was nice and deadly, but a person dying in it kinda defused it's throw mechanic. The for loop over locate should help. As well, if not defused, it forces gravity off for a bit, meaning the station will have to deal with no pain slowdown for a bit and loss of control, for better or worse.

Flux anomalies only were a danger if you touched them. the zap did a pathetic amount of damage. Now, one should have insulated gloves (and a hardsuit / modsuit that is shock proof) to deal with them. Engi borgs probably still defuse it easily.

Bluespace naturally isn't deadly, but this should make it re-organise a room more, and *slightly* harder to defuse. Really have to run for it if you want to not get teleported away when trying to defuse.

Pyro kinda, lit people on fire, but unless it exploded, the heat / fire didn't do much damage. Increasing the volume / how often the plasma spurts should increase the danger.

Vortex isn't deadly unless you are a slime. It still isn't that deadly, but with RNG feeling mean it might be cruel to someone, and it will break apart an area better, forcing engineering to do some repairs, which is good.

## Images of changes

## Testing

Spawned the anomaly types, watch their effects, have them kill skrells / spew plasma / break gravity.

## Changelog
:cl:
tweak: All anomalies are deadlier. Flux anomalies are much stronger, grav anomalies defuse gravity, pyro anomalies are hotter, and vortex might pull your feet out from under you.
/:cl:

2023-06-30 20:50 UTC, Sadhorizon commented
> Flux anomalies (not from supermatter / vetus) are MUCH deadlier. You will require insulated gloves to defuse this safely. If you have a flux anomaly and you do not have gloves, my advice is to get out of there. It will kill you if you don't get away from it.

This feels like it makes it _necessary_ for science to have insuls they _don't_ start with. Just in case flux anomaly spawns.
Unless the idea is adding engineering into the bag, which is fair, but anomalies always were more of science thing to defuse.

2023-06-30 21:01 UTC, Qwertytoforty commented
> > Flux anomalies (not from supermatter / vetus) are MUCH deadlier. You will require insulated gloves to defuse this safely. If you have a flux anomaly and you do not have gloves, my advice is to get out of there. It will kill you if you don't get away from it.
> 
> This feels like it makes it _necessary_ for science to have insuls they _don't_ start with. Just in case flux anomaly spawns. Unless the idea is adding engineering into the bag, which is fair, but anomalies always were more of science thing to defuse.
> 
> I like it being buffed, just curious how that would play out.

Engineering can also disarm anomalies. Analyses and signalers are in engineering, as well as the autolathe they often have for more analyzers, or a signaler. Engineers can also analyse it, while a scientist can ping it. Teamwork.

2023-07-04 15:42 UTC, Sirryan2002 commented
part of me wonders if the vortex anomaly will become significantly more unfun to deal with with this. I like all the other changes but could you record a video of the vortex anomalies buffed effects in action?

2023-07-04 21:02 UTC, Qwertytoforty commented
Video was posted in pr_review on discord

2023-07-11 02:57 UTC, JimKil3 requested changes
looks good to me, just one early return thing

2023-07-11 02:57 UTC, JimKil3 commented on code/game/objects/effects/anomalies.dm
> +			G.set_broken() //Requires engineering to fix the gravity generator, as it gets overloaded by the anomaly.
```suggestion
	if(!drops_core)
		return
	var/turf/T = get_turf(src)
	if(T && GLOB.gravity_generators["[T.z]"])
		var/obj/machinery/gravity_generator/main/G = pick(GLOB.gravity_generators["[T.z]"])
		G.set_broken() //Requires engineering to fix the gravity generator, as it gets overloaded by the anomaly.
```

2023-07-24 14:03 UTC, merged