Fixes inaccuracy in changeling chemical storage UI element.
ParadiseSS13/Paradise pull request #21583
Opened 2023-07-07 04:29 UTC by Divulf

## What Does This PR Do
Currently the changeling UI element for chemical storage updates before they generate chemicals causing it to be one step outside of what it should be (this can be easily observed by comparing it with the status panel, which does not suffer from this error).  This PR fixes this issue and also makes it so the UI element updates whenever a power takes it's cost, making it immediately accurate.

## Why It's Good For The Game
More accurate UI

## Testing
Grew and ungrew lots of armblades and used my eyeballs.

## Changelog
:cl:
tweak: Changeling storage now immediately updates when powers take chemicals
fix: Issue where the changeling chemical storage UI element would display incorrectly
/:cl:

2023-07-07 12:19 UTC, S34NW requested changes

2023-07-07 12:19 UTC, S34NW commented on code/modules/antagonists/changeling/datum_changeling.dm
> +/datum/antagonist/changeling/proc/update_chem_charges_ui(var/mob/living/carbon/human/H = owner.current)
```suggestion
/datum/antagonist/changeling/proc/update_chem_charges_ui(mob/living/carbon/human/H = owner.current)
```

2023-07-09 09:06 UTC, S34NW commented
Accounts now linked

2023-07-16 16:25 UTC, SteelSlayer approved these changes

2023-07-16 16:26 UTC, merged