Merge the mediborg gripper into the hugging module
ParadiseSS13/Paradise pull request #21590
Opened 2023-07-07 09:28 UTC by togglejoy

## What Does This PR Do

Removes the medical gripper module from mediborgs and moves the helping-up functionality to the hugging module. Helping people up is no longer special-cased for mediborgs and instead just reuses the regular help intent code, making the behavior more consistent.

## Why It's Good For The Game
The medical gripper doesn't really do much and is a source of confusion. The description indicates that it can "substitute for hands in surgical operations", however in almost all relevant cases (implants, organ transplants) it cannot actually do this. The only thing it's commonly used for is getting people up from the ground, and even then it doesn't always work properly.

We might as well just remove the gripper and put that basic help-intent functionality in the hugging module, which has the icon of the help intent and already does other help intent-ish things. Slightly simpler!

## Testing
Did various unethical medical experiments with fire and morphine on a monkey

## Changelog
:cl:
tweak: Mediborg can now pat out fire or help people wake up with the hugging module
tweak: Removed the largely-unused medical gripper from mediborg
/:cl:

2023-07-14 02:20 UTC, DGamerL reviewed
This is all I can find rn, I'll try to check it again later

2023-07-14 20:12 UTC, togglejoy commented on code/modules/mob/living/carbon/carbon.dm
> +	playsound(loc, 'sound/weapons/thudswoosh.ogg', 50, 1, -1)
Ah good catch! I moved the highfive part above it. It's supposed to (I think?) play the sound for hugs, shakes, pats etc hence why it's before the if chain

2023-07-14 20:13 UTC, togglejoy commented on code/modules/mob/living/carbon/carbon.dm
>  				)
I made that whole bit a single if-else chain so it shouldn't need any more early returns, I think?

2023-07-14 21:03 UTC, DGamerL commented on code/modules/mob/living/carbon/carbon.dm
>  				)
Whoops my bad, I am blind, good to go!

2023-07-17 20:13 UTC, lewcc requested changes
Please update from master, https://github.com/ParadiseSS13/Paradise/pull/21606 is going to be a significant conflict with your code.

2023-08-06 19:46 UTC, lewcc commented
As before, please update and address merge conflicts. If the conflicts are too much work to address cleanly (trust me, I've been there), you're free to make a new PR with the changes, or just revert and merge, make your new changes, and force push.

2023-08-16 18:40 UTC, S34NW requested changes
PR stale, please address lewcc's comments. Reach out on discord if you need help.

2023-08-24 18:19 UTC, S34NW commented
Over a week has passed with no additional changes. Feel free to make a new PR if you plan on carrying on with these changes.

2023-08-24 18:19 UTC, closed without merging