There is now a visual indicator if you can't use your hand
ParadiseSS13/Paradise pull request #21598
Opened 2023-07-08 05:41 UTC by Contrabang

## What Does This PR Do

There is now a visual indicator if you can't use your hand. Also refactors some code so that we use a consistent update proc. Idea is from TG, code wasn't a clean port so I made it work with our system.

Tried using just normal calls with delimbs, and didnt work. Neither did async. So I had to do a 0 tick callback (fun)

## Why It's Good For The Game
Giving the player knowledge about their body is good

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/ca4f8754-b85f-4510-be9b-9514d61fe122)

## Testing

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/eac8c5fb-0835-4dd4-9c0c-419a9b829846)
Handcuffs still work, swapping active hands still works.

## Changelog
:cl:
add: Your hands now have a "blocked" symbol if you can't use them (i.e. no hand, dead hand)
/:cl:

2023-07-09 16:02 UTC, hal9000PR requested changes
Might it be a good idea to apply the overlay when `TRAIT_HANSABLOCKED` is added?

2023-07-09 16:05 UTC, Contrabang commented
> Might it be a good idea to apply the overlay when `TRAIT_HANSABLOCKED` is added?

Most of those are like a whole body thing (stuns, weakens, etc). I think it would be a better visual indicator for just situations like these. (And I guess I could use signals for it, because traits support that, but I think it would be kinda messy.)

2023-07-24 14:08 UTC, S34NW approved these changes

2023-07-26 22:51 UTC, lewcc approved these changes

2023-07-27 14:04 UTC, Sirryan2002 approved these changes

2023-07-28 20:49 UTC, lewcc commented on code/modules/surgery/organs/subtypes/standard_organs.dm
> +	addtimer(CALLBACK(owner, TYPE_PROC_REF(/mob/living/carbon/human, update_hands_hud), 0))
Any reason why you're adding a timer and not just async invoking (or calling the proc itself)?

2023-08-12 17:45 UTC, merged