Remakes the Syndi Cakes Factory space ruin.
ParadiseSS13/Paradise pull request #21611
Opened 2023-07-09 19:47 UTC by ArcZelf

## What Does This PR Do
Completely remakes the syndi cakes factory space ruin into an upgraded version, welcome to Syndi-Cakes Eridani! (SC-Eridani).
Map is still 40x40 in size.

This new updated version notably features
>Three different areas to explore, the Production Lines where the magic happens, the Packaging Area where Syndi-cakes are packaged and sent, and the Control Room guarded by four turrets, a Syndicate Commando and their friendly bunny 'Flippers'.

>Buttons that control blast doors which players must use in order to unlock the areas mentioned above.

>Syndicate Airlocks, which normal explorers/people will not be able to access therefore hacking through or slicing through walls is required.

>An introductory paper to the history of the ruin that is found in the Reception area: "A reminder to all stationed personnel that the production lines are strictly off-limits after the contamination incident. In the case that the decontamination team fails, do not approach nor provoke the corgis and contact management immediately."

>New threats such as four angry corgi's instead of one, a Syndicate Commando, four turrets

>Two non hostile mobs, an Exotic Corgi and Flippers the Bunny

>An overabundance of Syndi-Cakes

>Loot carried over from the old ruin such as the black and red toolbox and the bloodred but with minor additions like the tactical turtleneck and a tiny armor vest.

>A recycler that functions like an emagged recycler which was used to grind up those corgis. It deals 120 damage compared to 1000 (this recycler is already in the code)

## Why It's Good For The Game

The old version of the ruin was rather out-dated and didn't pose much threat in order to get a free blood-red suit. This revamped version gives the place some new lore and threats in place to avoid people easily obtaining loot.

## Images of changes

Before and After
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/785342c4-9dc4-4d57-941c-1f67217cfe9b)
A closer look
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/0167c2e6-b8a1-4a36-9ed0-5e7bc65d4de8)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/49b84307-dcee-462e-9c84-5cfeedd3c5f2)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/6d53aaa6-495b-4c21-87da-0c5c5659c868)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/e1a5d170-1e0f-4c72-9faa-0fc65cab5cc6)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/038340ce-05e8-4ae3-b661-db0f39894b21)

## Testing

Slapped the finished product onto the official paradise test server (a version without the papers because the papers don't exist in the files so it would bork the map placing). Died to a bunch of angry corgis and then turrets and a commando. Everything worked fine including the buttons and power.

Also made sure the Syndicate Commando was the /autogib version because I sure as shit wouldn't want people to get a free weapon out of them.

## Changelog
:cl:
tweak: Remakes the Syndi Cakes Factory space ruin.
/:cl:

2023-07-10 13:52 UTC, ArcticValor commented
wanted to ask, but what if this spawned on the same sector as syndicate depot would killing the commando affect the depot's sec level (saying this cause the locker on the old one did cause the syndicate depot to do the ID lock out thing to the agent log in console)

2023-07-12 21:38 UTC, Miraviel requested changes
Looks cool, here is a review:

(1) Here, the blast doors are layered below airlocks, so you cannot see whether they are open or not
![image](https://github.com/ParadiseSS13/Paradise/assets/33333517/05fa018b-2712-4c33-91fe-6b8845838d57)

(2) The paper says "For fuck sake I can't", it should be "For fuck's sake I can't", minor typo. Hilarious note tho

(3) Turn these tiles from `/turf/space` into `/turf/template_noop` and its area into `/area/template_noop`. Same for the space tiles around it, the area should be `/area/template_noop`.

![image](https://github.com/ParadiseSS13/Paradise/assets/33333517/05acb254-d4f4-4828-8cf0-401a1cfd451a)


(4) These suit storages are empty, not sure if it's intentional. I assume it's because people left?

![image](https://github.com/ParadiseSS13/Paradise/assets/33333517/946e1d5e-61ac-4723-abe2-36d91fd2bf2a)

(5) Nitpick you can safely ignore: there are blood drips in the reception area leading up to (or from) a corpse, but the corpse has no blood around it. It has insect blood instead, next to a human body. You might have put down the wrong decal there

(6) Not sure if you are aware, but you can trap the syndicate commando in the O2 locker in the 4 turret room, run out of sight and it will stop bashing its way out. If you want to allow that, feel free to leave it there, but this is a possibility of exploiting this place

overall a sick ruin, I wasn't able to complete the 4 turret room but that's because I'm unrobust

> wanted to ask, but what if this spawned on the same sector as syndicate depot would killing the commando affect the depot's sec level (saying this cause the locker on the old one did cause the syndicate depot to do the ID lock out thing to the agent log in console)

I spawned these two ruins next to each other on z level 4, killed the commando, it did not affect the syndiedepot

2023-07-14 15:58 UTC, ArcZelf commented
Sorry for the late response, I don't have an excuse I'm just simply lazy
1) 
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/84a565e0-ab66-48ba-8681-96adf9843b42)
Outright removed the airlocks
2) Fixed 
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/b6bd8506-4f54-4c51-99e0-131c72edd9bd)
3)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/8137239d-8146-4512-8633-8f29cf4fc27c)
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/fae48692-f8fb-4df2-8f37-2bf5b092ac8e)
4) Intentional
5) 
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/794c63b2-9e6b-416b-9f4b-37c502101aaf)
Added some extra blood splats/drips
6) Removed the oxygen locker

Thanks for the review, if anything appears to be added wrong just say so.

2023-07-15 18:22 UTC, Miraviel approved these changes

2023-07-22 10:28 UTC, S34NW requested changes
Please replace the rwalls surrounding the "inner room" with the indestructible `/turf/simulated/wall/indestructible/riveted` variant. Currently this is way too easy to cheese for a blood red.

2023-07-22 11:02 UTC, ArcZelf commented
> Please replace the rwalls surrounding the "inner room" with the indestructible `/turf/simulated/wall/indestructible/riveted` variant, to force users to fight the turrets and commando for loot. Currently this is way too easy to cheese for a blood red.

Donezo, thank you for the feedback
![image](https://github.com/ParadiseSS13/Paradise/assets/108688684/64b522e6-1af5-4f2e-a2a1-5a240424da5f)
Tested (a version without the papers) on the paradise test server and all rwalls were indestructible versions.

2023-07-23 21:41 UTC, S34NW approved these changes
Just needs another master update due to changes in windoor paths

2023-07-23 21:59 UTC, merged