Only malf AI can hack doors with cut ai wires, flash emps cameras
ParadiseSS13/Paradise pull request #21610
Opened 2023-07-09 18:14 UTC by Qwertytoforty

## What Does This PR Do

Only malf AI can hack doors with cut AI control wires. Otherwise, an AI can no longer interface with a door that has its ai control wires cut, period. Malf AI however can now hack these doors faster, taking only 30 seconds.

Flashes can be used to to now emp cameras, either weakly emping camers around the user when flash is used in hand, or a strong emp when used directly on a camera. Naturally, emp proof cameras are immune to it.

Weaker emps last 45 seconds on disabling cameras, as a bit of counter balance.

## Why It's Good For The Game

AI is strong, and while I do not agree with the door bolt / shock delay PR, I do think there should be more options against ais.

If someone goes through the effort of cutting ai control wires, they should have to be fixed. AI should not be able to hack the airlock and be able to access it whenever, unless they are malf.
If you go for the effort of preparing against the AI, it should be stopped.

As for the flash changes, this lets an antagonist quickly disable the cameras temporarily in a room, visibly, without using an EMP which will set off power and fire alarms quickly getting ai / engi attention.

## Images of changes

## Testing

Hacked doors, flashed cameras

## Changelog
:cl:
tweak: Only malf AI can hack doors with cut AI wires now.
add: Flashes can now emp cameras like laser pointers, the AOE flash does a weak emp effect to cameras close by, a direct flash does a strong emp effect.
/:cl:

2023-07-11 02:12 UTC, JimKil3 requested changes
the "images of changes" section in your PR description is blank

2023-07-11 02:12 UTC, JimKil3 commented on code/game/machinery/doors/airlock.dm
> +		sleep(50)
```suggestion
		sleep(5 SECONDS)
```

2023-07-11 02:12 UTC, JimKil3 commented on code/game/objects/items/devices/flash.dm
> +		add_attack_logs(user, C, "EMPd with [src]", ATKLOG_ALL)
```suggestion
	if(!istype(target, /obj/machinery/camera))
		return
	if(!try_use_flash(user))
		return
	var/obj/machinery/camera/C = target
	C.emp_act(1)
	to_chat(user,"<span class='notice'>You hit the lens of [C] with [src], temporarily disabling the camera!</span>")
	log_admin("[key_name(user)] EMPd a camera with a flash")
	user.create_attack_log("[key_name(user)] EMPd a camera with a flash")
	add_attack_logs(user, C, "EMPd with [src]", ATKLOG_ALL)
```

2023-07-17 18:55 UTC, lewcc commented on code/game/objects/items/devices/flash.dm
> +		C.emp_act(1)
```suggestion
		C.emp_act(EMP_HEAVY)
```

2023-07-17 18:55 UTC, lewcc commented on code/game/objects/items/devices/flash.dm
> +		C.emp_act(2)
```suggestion
		C.emp_act(EMP_LIGHT)
```

2023-07-17 18:55 UTC, lewcc commented on code/game/machinery/doors/airlock.dm
> +	return ((aiControlDisabled == AICONTROLDISABLED_ON) && (!hackProof) && (!isAllPowerLoss()) && user.mind.special_role)
```suggestion
	return ((aiControlDisabled == AICONTROLDISABLED_ON) && (!hackProof) && (!isAllPowerLoss()) && user.mind?.special_role)
```

2023-07-24 14:38 UTC, Qwertytoforty commented on code/game/objects/items/devices/flash.dm
> +		C.emp_act(1)
done

2023-08-12 17:42 UTC, S34NW approved these changes

2023-08-12 17:43 UTC, merged