Make air alarms start with the correct default state when placing the…
ParadiseSS13/Paradise pull request #21635
Opened 2023-07-12 19:17 UTC by benjicoots

## What Does This PR Do
Hopefully Fixes#21492, where an air alarm will incorrectly appear as finished when just being placed on the wall.

https://github.com/ParadiseSS13/Paradise/issues/21492

## Why It's Good For The Game

It fixes a visual bug.

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/11049499/fe8ff134-1023-45b0-abeb-f96c38a928b9)

## Testing

Tried several times to construct new air alarms, could not get the visual bug to happen again after the changes. (I did manage to replicate the bug before the code change.) 
And, as shown in the image above, the build progression appears to work as intended now.

## Changelog
:cl:Panasonicp2
fix: Air alarms now appear in the correct unfinished state when placing them on the wall
/:cl:

2023-07-16 16:58 UTC, DGamerL reviewed
code/modules/atmospherics/machinery/airalarm already has AIR_ALARM_FRAME defined which is causing it to not pass CI

2023-07-17 20:11 UTC, lewcc requested changes

2023-07-17 20:11 UTC, lewcc commented on code/game/objects/items/mountable_frames/air_alarm_frame.dm
> +
```suggestion
```

This macro is already defined elsewhere, so you can't redefine it here.

2023-08-04 05:11 UTC, Henri215 commented
Please add "Fixes" before the link of the issue being fixed by this PR.

2023-08-12 18:27 UTC, S34NW approved these changes

2023-08-12 18:27 UTC, merged