[FEAT/TGUI] Better Gas Analyzer AND TGUI!
ParadiseSS13/Paradise pull request #21645
Opened 2023-07-13 07:03 UTC by larentoun

## What Does This PR Do

New:
- Adds Gas Analyzer TGUI
- Gas Analyzer provides tiny bit more info
- Gas Analyzer can be now used on turfs
- Gas Analyzer TGUI history with kPa/mol switch

Other:
- Gas Analyzer TGUI has toggleable auto-scan
- Gas scan messages no longer spam into the chat

## Why It's Good For The Game

Better visuals, less spam in chat

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/31931237/4e298f89-227d-4875-a74f-81dacfd16655

## Testing

See video

## Changelog
:cl:
add: Gas Analyzer TGUI
add: More info in Gas Analyzer
tweak: Ghost Gas Scan can now click on objects instead of scanning surroundings
del: Gas Scan messages in the chat when using Gas Analyzer
/:cl:

2023-07-13 07:04 UTC, Sirryan2002 commented
please post a working image of the TGUI

2023-07-13 09:10 UTC, Gatchapod commented
How does this affect analyzing anomalies, if at all?

2023-07-13 17:19 UTC, larentoun commented
> please post a working image of the TGUI

The video isn't enough?

2023-07-13 17:19 UTC, larentoun commented
> How does this affect analyzing anomalies, if at all?

It should not affect them

2023-07-13 18:17 UTC, Sirryan2002 commented
The link seemed to be broken when the PR was opened

2023-07-14 23:58 UTC, TrashDoxx commented
:trollface:

2023-08-04 04:26 UTC, 1080pCat commented
does the history get saved through menu closing? if so does it start to lag on opening if you've scanned hundreds of tiles?

2023-08-18 01:36 UTC, lewcc requested changes
Please address merge conflicts and linters

2023-08-18 01:36 UTC, lewcc commented on code/__HELPERS/atmospherics.dm
> +/** A simple rudimentary gasmix to information list converter. Can be used for UIs.
This file needs to be renamed, perhaps to `atmospherics_helpers.dm`. It's failing linters

2023-09-06 11:44 UTC, S34NW approved these changes
Deconflict for merge

2023-09-08 00:35 UTC, SteelSlayer requested changes

2023-09-08 00:35 UTC, SteelSlayer commented on code/game/objects/items/devices/scanners/gas_analyzer.dm
> +	SIGNAL_HANDLER
This isn't called via a signal. Please clean up the arg from this and from all calls of the proc.
```suggestion
/obj/item/analyzer/proc/on_analyze(atom/target, save_data = TRUE)
```

2023-09-08 00:35 UTC, SteelSlayer commented on code/modules/pda/utilities.dm
> +	atmos_scan(user=user, target=A, silent=FALSE, print=TRUE)
```suggestion
	atmos_scan(user = user, target = A, silent = FALSE, print = TRUE)
```

2023-09-08 00:35 UTC, SteelSlayer commented on code/__HELPERS/atmospherics_helpers.dm
> +//TODO: Port gas_mixture_parser from TG
Is this something you were going to do in this PR?

2023-09-08 00:35 UTC, SteelSlayer commented on code/_onclick/observer_onclick.dm
> +			return TRUE
Styling
```suggestion
	if(user.client && user.gas_scan && atmos_scan(user = user, target = src, silent = TRUE))
		return TRUE
```

2023-09-08 00:35 UTC, SteelSlayer commented on code/game/objects/items/devices/scanners/gas_analyzer.dm
> +	var/atom/scan_target
This needs to be nulled in `Destroy`

2023-09-08 00:35 UTC, SteelSlayer commented on code/game/objects/items/devices/scanners/gas_analyzer.dm
> +	addtimer(CALLBACK(src,/obj/item/analyzer/proc/ping), cooldown_time)
```suggestion
	addtimer(CALLBACK(src, PROC_REF(ping)), cooldown_time)
```

2023-09-08 00:35 UTC, SteelSlayer commented on code/game/objects/items/devices/scanners/gas_analyzer.dm
> +	on_analyze(source=user, target=get_turf(src), save_data=!auto_updating)
Spacing around the `=` please.

2023-09-08 00:35 UTC, SteelSlayer commented on code/game/objects/items/devices/scanners/gas_analyzer.dm
> +	on_analyze(source=user, target=(target.return_analyzable_air() ? target : get_turf(src)), save_data=!auto_updating)
More spacing

2023-09-08 04:52 UTC, larentoun commented
No reason to support upstream if they can't do a little thing to support downstream.

2023-09-08 04:52 UTC, closed without merging