[TWEAK] Activate and Drop now Extend and Retract arm implants in THE ARM
ParadiseSS13/Paradise pull request #21665
Opened 2023-07-13 18:53 UTC by larentoun

https://github.com/ss220-space/Paradise/pull/1438

## What Does This PR Do

Now, when you actiavte you empty hand with an implant, a radial menu opens. When you drop your hand with an implant active, it retracts

Also, it adds an ability to use an empty hand. So, probably, add xeno's spit into the hand by using it? :eyes:

## Why It's Good For The Game

More straight-forward arm implant usage?

## Testing

Implant armtoolset, use it all the ways possible

## Changelog
:cl:
tweak: Activate and Drop now Extend and Retract arm implants in THE ARM. Z/Q (by defaults) Extend and Retracts.
/:cl:

2023-07-13 21:04 UTC, matttheficus commented
I dont really like the idea of misclicking an open hand giving a radial menu to be honest. Dropping already drops the current tool and reopens the radial.

2023-09-06 11:27 UTC, S34NW commented
No commits in three weeks, marking as stale.

2023-09-08 01:03 UTC, SteelSlayer requested changes

2023-09-08 01:03 UTC, SteelSlayer commented on code/modules/surgery/organs/augments_arms.dm
> +	INVOKE_ASYNC(src, .proc/ui_action_click)
```suggestion
	INVOKE_ASYNC(src, PROC_REF(ui_action_click))
```

2023-09-08 04:52 UTC, larentoun commented
No reason to support upstream if they can't do a little thing to support downstream.

2023-09-08 04:52 UTC, closed without merging