Chem Dispensers no longer work while unanchored
ParadiseSS13/Paradise pull request #21685
Opened 2023-07-14 18:41 UTC by Bjamcham

## What Does This PR Do
Chem dispensers now need to be anchored in order to be used.

## Why It's Good For The Game
Requiring the dispenser to be anchored prevents on the fly chem mixing and low prep smoke bombs that previously required little effort for the user

## Images of changes

## Testing
Tried to use an anchored chem dispenser: Worked
Tried to use an unanchored chem dispenser: Did not work

## Changelog
:cl:
tweak: Chem dispensers must be anchored to use
/:cl:

2023-07-14 18:44 UTC, DGamerL approved these changes
Looks good, I'd suggest either putting something in the images of changes section or remove it

2023-07-16 16:27 UTC, Sirryan2002 requested changes

2023-07-16 16:27 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		visible_message("<span class='warning'>[src] must be anchored first!</span>")
this should be a to_chat instead

2023-07-23 23:02 UTC, DGamerL approved these changes
LGTM if you checked that you can't interact with the TGUI once unwrenched

2023-07-24 14:31 UTC, S34NW approved these changes

2023-07-24 14:31 UTC, merged