Floodlights can now only be turned on if they are anchored
ParadiseSS13/Paradise pull request #21680
Opened 2023-07-14 12:22 UTC by DGamerL

## What Does This PR Do
Floodlights can now only be turned on if they are anchored to the ground.

## Why It's Good For The Game
Running around with a lit floodlight in maints is silly, also it can really steamroll an unprepared shadow demon. There's some more here that I really can't remember off of the top of my head right now.

## Testing
Tried to turn an unanchored floodlight on, could do it when I wrenched it down

## Changelog
:cl:
tweak: you can now only turn on a floodlight if it's wrenched down
/:cl:

2023-07-16 16:28 UTC, Sirryan2002 requested changes

2023-07-16 16:28 UTC, Sirryan2002 commented on code/game/machinery/floodlight.dm
> +			visible_message("<span class='warning'>[src] must be anchored first!</span>")
this should be a to_chat

2023-07-16 17:15 UTC, DGamerL commented on code/game/machinery/floodlight.dm
> +			visible_message("<span class='warning'>[src] must be anchored first!</span>")
Tested it and it works still!

2023-07-17 18:26 UTC, lewcc commented on code/game/machinery/floodlight.dm
> +		update_icon(UPDATE_ICON_STATE)
Easier to just call the existing proc which does the same thing
```suggestion
		extinguish_light()
```

2023-07-17 21:02 UTC, lewcc approved these changes

2023-07-24 00:05 UTC, lewcc approved these changes

2023-07-24 00:06 UTC, Contrabang approved these changes

2023-07-24 09:12 UTC, merged