Fix malfunctioning drones failing to GC
ParadiseSS13/Paradise pull request #21693
Opened 2023-07-14 22:56 UTC by FridgeBurns

## What Does This PR Do

Fixes #20487
This is my first time doing gc stuff, I hope this is the correct way to do it
## Why It's Good For The Game

Fixes a gc fail
## Testing

I ran the event and deleted a drone. It was removed from the list.

2023-07-15 03:13 UTC, GDNgit requested changes

2023-07-15 03:13 UTC, GDNgit commented on code/modules/events/rogue_drones.dm
> +	drones_list -= D
```suggestion
	SIGNAL_HANDLER
	drones_list -= D
```
Outside of that this should be alright

2023-07-16 16:25 UTC, Sirryan2002 approved these changes

2023-07-17 09:52 UTC, hal9000PR approved these changes

2023-07-17 09:52 UTC, merged