Cyborgs and Drones dust when interacting with Supermatter Slivers
ParadiseSS13/Paradise pull request #21750
Opened 2023-07-19 16:55 UTC by Burzah

## What Does This PR Do
Fixes: #21316 where modules were deleted from drones and cyborgs who interacted with Supermatter Slivers instead of dusting them.

## Why It's Good For The Game
Cyborgs and Drones that interact with Supermatter Slivers should be dusted while interacting with a sliver with one of their modules.

## Images of changes
![dreamseeker_O2Jw14eRha](https://github.com/ParadiseSS13/Paradise/assets/116982774/dbcf2a55-8092-4537-8df0-4b5360b34fcb)

## Testing
Spawned in Supermatter Slivers. 
Tested multiple modules on both Drones and Cyborgs.
Checked for dusting.

Tested with regular mobs using tools.
Checked to make sure they didn't dust.

## Changelog
:cl:
fix: Cyborgs and Drones dusting when using modules
/:cl:

2023-07-19 22:59 UTC, Contrabang requested changes

2023-07-19 22:59 UTC, Contrabang commented on code/game/objects/items/theft_items.dm
> +		if(issilicon(usr))
```suggestion
		if(issilicon(user))
```

2023-07-19 22:59 UTC, Contrabang commented on code/game/objects/items/theft_items.dm
> +			to_chat(user, "<span class='danger'>You try to touch [src] with one of your modules. Error!</span>")
```suggestion
			to_chat(user, "<span class='userdanger'>You try to touch [src] with one of your modules. Error!</span>")
```

2023-07-20 17:02 UTC, ArcticValor commented
i did this once in a round an was like "oh oh no my grabber is gone*

2023-07-24 14:00 UTC, merged