Gives Vampires Stronger Night Vision at 500 Blood
ParadiseSS13/Paradise pull request #21764
Opened 2023-07-20 20:58 UTC by matttheficus

## What Does This PR Do
Extends Vampire Night Vision from `3` to `5` tiles once they reach 500 blood.

## Why It's Good For The Game
For a creature that attacks from the darkness, you have absolute PISS poor night vision until you reach Full Power.

This gives Vampires a slight bonus when they reach 500 blood.

## Testing
1. Ran around in the dark at various blood levels.

## Changelog
:cl:
add: Adds Advanced Vampire Night Vision at 500 Blood as a passive.
/:cl:

2023-07-21 08:37 UTC, hal9000PR requested changes

2023-07-21 08:37 UTC, hal9000PR commented on code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm
> +	gain_desc = "Your vampiric vision now allows you to see in the dark!"
```suggestion
	gain_desc = "Your vampiric vision now allows you to see everything in the dark!"
```
makes it more clear as it already let you see in the dark.

2023-08-18 01:29 UTC, lewcc requested changes
Please follow up with hal on this, the last review was a month ago. If hal isn't available, please reach out to other developers (myself included), who'd be happy to help you get this moving

2023-08-22 05:04 UTC, matttheficus commented
These are still broken, working to get it to function right.

2023-08-22 17:14 UTC, matttheficus commented on code/modules/mob/living/carbon/human/species/_species.dm
>  			H.see_in_dark += 1 // base of 2, 2+1 is 3
Right, this took immensely too long. Sorry for the wait. Should be good to go now.

2023-08-22 17:51 UTC, hal9000PR requested changes

2023-08-22 17:51 UTC, hal9000PR commented on code/modules/antagonists/vampire/vamp_datum.dm
> +		owner.current.update_sight() // Life updates conditionally, so we need to update sight here in case the vamp gets new vision based on his powers. Maybe one day refactor to be more OOP and on the va
make this occur on `passive.on_apply()`

2023-08-22 17:51 UTC, hal9000PR commented on code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm
> +	vision_flags = SEE_MOBS
these see_in_dark values need to be reduced because each value is added rather than just the highest value being added

2023-08-22 17:51 UTC, hal9000PR commented on code/modules/mob/living/carbon/human/species/_species.dm
> +			H.sight = buffs.vision_flags
```suggestion
			H.sight |= buffs.vision_flags
``` this way the vision passives will never decrease the vision flags.

2023-09-01 21:36 UTC, S34NW approved these changes

2023-09-01 21:36 UTC, merged