NutrimentPump
ParadiseSS13/Paradise pull request #21789
Opened 2023-07-23 15:37 UTC by Baredolf

## What Does This PR Do
Changes Nutriment item description and typo in name
 - Reworded description
- Changed nutrient to nutriment
Fixes #21569

## Why It's Good For The Game
Changed slightly confusing description wording and fixed a typo that led to the item not being properly searchable in certain menu's
## Testing
Loaded test server, spawned all versions of nutriment pumps and viewed their names and description with no issues.

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: Changed Nutriment Pump description wording
fix: Typo, Changed "nutrient" to "nutriment"
/:cl:

2023-07-23 15:55 UTC, Henri215 commented on code/modules/surgery/organs/augments_internal.dm
> +	desc = "This implant will synthesize a small amount of nutriment and pump it directly into your bloodstrean, when you are starving."
```suggestion
	desc = "This implant will synthesize a small amount of nutriment and pump it directly into your bloodstream, when you are starving."
```

2023-07-23 15:57 UTC, Henri215 commented
"fix: Fixed nutriment pump typos"

That should be enough for your changelog.

2023-07-24 02:12 UTC, DGamerL commented on code/modules/surgery/organs/augments_internal.dm
> +	desc = "This implant will synthesize a small amount of nutriment and pump it directly into your bloodstream when you are hungry."
```suggestion
	desc = "This implant will synthesize a small amount of nutriment and pumps it directly into your bloodstream when you are hungry."
```

2023-07-24 02:12 UTC, DGamerL commented on code/modules/surgery/organs/augments_internal.dm
> +	desc = "This implant will synthesize a small amount of nutriment and pump it directly into your bloodstream when you are starving."
```suggestion
	desc = "This implant will synthesize a small amount of nutriment and pumps it directly into your bloodstream when you are starving."
```

2023-07-24 02:19 UTC, DGamerL approved these changes
LGTM

2023-07-26 04:22 UTC, Sirryan2002 approved these changes

2023-07-26 10:49 UTC, hal9000PR requested changes
one thing before merge

2023-07-26 10:49 UTC, hal9000PR commented on code/modules/surgery/organs/augments_internal.dm
>  /obj/item/organ/internal/cyberimp/chest/nutriment/hardened
```suggestion
	origin_tech = "materials=4;powerstorage=3;biotech=3"

/obj/item/organ/internal/cyberimp/chest/nutriment/hardened
```
spacing

2023-07-27 14:21 UTC, hal9000PR approved these changes

2023-07-27 19:17 UTC, merged