Gives flares the same attack sounds and attack message as lighters.
ParadiseSS13/Paradise pull request #21829
Opened 2023-07-26 03:38 UTC by Divulf

## What Does This PR Do
Gives flares the same attack sounds and attack description as lighters.

## Why It's Good For The Game
Currently flares use a whack sound and a fairly generic "attacked" verb in it's attack message.  Since flares only do damage when they're turned on and do burn damage, it's more appropriate for them to use a different sound and message.

## Testing
Hit things with flares.

## Changelog
:cl:
tweak: Flares now use the same attack sounds and attack message as lighters.
/:cl:

2023-07-27 14:14 UTC, hal9000PR commented on code/game/objects/items/devices/flashlight.dm
> +	attack_verb = initial(attack_verb)
`initial` doesn't work on lists
![image](https://github.com/ParadiseSS13/Paradise/assets/69320440/fc1e2f9d-0a2c-4450-aeab-25010ef75af0)

2023-08-18 01:42 UTC, lewcc requested changes
Please address hal's outstanding review

2023-08-21 18:38 UTC, S34NW requested changes
No update in a month, please implement changes requested. The initial proc does not work on lists.

2023-08-30 20:45 UTC, closed without merging

2023-08-30 20:45 UTC, S34NW commented
Still no changes, sadly. Closed due to inactivity. Please make a new PR if you want to continue with this project.