Remove "Forsaken" Cat from Gold Slime extract spawn.
ParadiseSS13/Paradise pull request #21852
Opened 2023-07-28 16:50 UTC by Venuska1117

## What Does This PR Do
Remove "Forsaken" feral cat from gold slime spawn.

## Why It's Good For The Game
No more ambush from "Forsaken" cat.

## Testing
Added one line from other mobs with use it, no testing done.

## Changelog
:cl:
tweak: Removed "Forsaken" Cat from Gold Slimes Spawning.
/:cl:

2023-07-28 19:43 UTC, lewcc approved these changes
Code looks good

2023-08-11 14:38 UTC, hal9000PR requested changes

2023-08-11 14:38 UTC, hal9000PR commented on code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	gold_core_spawnable = NO_SPAWN //Xenobio got eaten by this custom cat... (forgot to add this before, oops.)
```suggestion
	gold_core_spawnable = NO_SPAWN
```
dont add code comments about what the code used to be, we have git history for that.

2023-08-14 18:16 UTC, DGamerL approved these changes

2023-08-14 18:53 UTC, Henri215 approved these changes

2023-08-15 12:38 UTC, CinnamonSnowball approved these changes

2023-08-15 13:51 UTC, merged