[ADMIN] Allows saving of JSON datums server side
ParadiseSS13/Paradise pull request #21860
Opened 2023-07-29 10:22 UTC by AffectedArc07

This PR is an admin-only tool. Feel free to ignore.

---

## What Does This PR Do
Adds a system to allow saving of JSON datums to a database table with slot names. This means that you can now save your JSON character saves to the DB and load them as slots. Yes, this means no more text files littered all over your documents.

### I must stress that if you want to import all your existing saves, you **MUST** test that the JSON still works on a local server before importing it into the live server. If you brick the live server by spawning broken JSON I will not hesitate to nuke your rights as per policy.

TODO - Make the server automatically strip JSON of broken stuff that shouldnt save like scuffed implants or similar.

As for the implementation, when asking to serialise an object you are now given this menu
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/27e2a781-bdb3-4480-afac-1868f0002ba9)

`PC` will dump the JSON to chat as it does now.
`Server` will bring up this menu.
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/94f0d1ec-740a-4182-aff4-dce1bf823e9f)

Selecting an existing slot will update that slot. Selecting `--NEW--` will allow you to type a name for a new one.

You can then spawn future ones and delete them from the `Spawn Saved JSON Datum` verb.
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/b5dfa081-e76d-4453-a609-e5cfbe65ed33)

## Why It's Good For The Game
Not having documents full of cluttered files is nice, easier organisation of chars, not having to send massive files to and from BYOND is nice, not copying out of the chat window is nice.

## Images of changes
See above

## Testing
- Created a JSON save
- Updated a JSON save
- Spawned a JSON save
- Deleted a JSON save

## Changelog
:cl: AffectedArc07
add: [ADMIN] Added a system to save/load JSON character saves from the DB
/:cl:

2023-08-06 20:20 UTC, Sirryan2002 requested changes

2023-08-06 20:20 UTC, Sirryan2002 commented on code/modules/admin/topic.dm
> +		qdel(dbq)
extra qdel here? There's already one on L3381

2023-08-06 20:20 UTC, Sirryan2002 commented on code/modules/admin/topic.dm
> +			qdel(dbq)
```suggestion
			qdel(dbq2)
```

2023-08-06 20:20 UTC, Sirryan2002 commented on code/modules/admin/topic.dm
> +		qdel(dbq)
```suggestion
		qdel(dbq2)
```

2023-08-06 20:20 UTC, Sirryan2002 commented on code/modules/admin/verbs/serialization.dm
> +			var/datum/db_query/dbq2 = SSdbcore.NewQuery("INSERT INTO json_datum_saves (ckey, slotname, slotjson) VALUES(:ckey, :slotname, :slotjson)", list(
this query won't be cleaned up if it passes the next if check, add in another qdel please :D

2023-08-06 20:20 UTC, Sirryan2002 commented on code/modules/admin/verbs/serialization.dm
> +			var/datum/db_query/dbq2 = SSdbcore.NewQuery("UPDATE json_datum_saves SET slotjson=:slotjson WHERE slotname=:slotname AND ckey=:ckey", list(
same here

2023-08-16 19:09 UTC, S34NW requested changes
Please see reviews

2023-08-16 22:59 UTC, AffectedArc07 commented
Am aware, need to reclone the repo when I can because I have the CUDAAlights branch in progress and I hate stashing.

2023-08-21 18:43 UTC, S34NW approved these changes

2023-08-21 18:44 UTC, merged