Fixed Trick Revolver, Added Trick minibomb
ParadiseSS13/Paradise pull request #21915
Opened 2023-08-04 20:26 UTC by HMBGERDO

## What Does This PR Do

This PR
1: Moves trick revolver from subtype of russian revolver to subtype of actual 357 revolver. Now it acts the same as default revolver whatever you do with it, but if you try shoot, you will die.

2: Makes trick revolver bring recognisable with clumsy trait. If you examine it with clumsy, you will see "Its mechanism looks like it shots backwards."

3: Adds Trick minibomb. That is minibomb as actual one, but once you activate it, it will gain NODROP flag makes it impossible to throw at target. If you examine it with clumsy gene, you will see text "There is small glue ejectors all over the bomb."
After activating the bomb, you will see text "As you activate the bomb, it emits super glue and sticks to your hand." and "Uh oh."

## Why It's Good For The Game

Trick revolver supposed to looks like real one, but its nature of being subtype of russian revolver makes it not acting like real one. Making trick revolver harder to identify is good by my sight.

Adding more trick uplink items is good, trick bomb sounds fun(for me).

Making clown being able to identify clown uplink fake items is cool for me.

## Testing

Compiled, tested shooting revolver and throwing nade

## Changelog
:cl:
add: Trick Minibomb - Clown uplink item for 1 TC which is actual syndicate minibomb, but once you activate it, you cant throw it away. Clowns(or others with clumsy gene) can identify it.
tweak: Trick Revolver - Now clowns(or others with clumsy gene) can identify it.
fix: Trick Revolver - Now its acts as actual revolver in all ways instead of shooting it. Its harder to identify, no more "Has 4 rounds remaining."
/:cl:

2023-08-05 06:07 UTC, Henri215 commented on code/datums/uplink_items/uplink_traitor.dm
> +	desc = "Syndicate Minibomb with glue ejectors that will stick bomb to user's hand on activation."
```suggestion
	desc = "Syndicate Minibomb with glue ejectors that will stick it into the user's hands on activation."
```
Think like this is better?

2023-08-05 06:07 UTC, Henri215 commented on code/game/objects/items/weapons/grenades/syndieminibomb.dm
> +		. += "<span class='sans'>There is small glue ejectors all over the bomb.</span>"
```suggestion
		. += "<span class='sans'>There are small glue ejectors all over the bomb.</span>"
```

2023-08-05 06:07 UTC, Henri215 commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		. += "<span class='sans'>Its mechanism looks like it shoots backwards.</span>"
```suggestion
		. += "<span class='sans'>Its mechanism seems to shoot backwards.</span>"
```

2023-08-05 06:07 UTC, Henri215 commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	playsound(src, 'sound/weapons/gunshots/gunshot_strong.ogg', 50, 1)
```suggestion
	playsound(src, 'sound/weapons/gunshots/gunshot_strong.ogg', 50, TRUE)
```

2023-08-06 20:30 UTC, TORE01 commented
Nice change. Only one thing thats bugging me. Does the trick minibomb come in a box with a label like the trick revolver? It would be pretty shitty to throw a minibomb from your surplus crate only to get gibbed by your own grenade.

2023-08-06 22:18 UTC, HMBGERDO commented
> Nice change. Only one thing thats bugging me. Does the trick minibomb come in a box with a label like the trick revolver? It would be pretty shitty to throw a minibomb from your surplus crate only to get gibbed by your own grenade.

Yes, it comes in a box named Trick Minibomb, if you dont remove it from the box, you will know its fake

2023-08-07 11:29 UTC, DGamerL commented
I like the trick grenade, but:
1. The trick revolver was fixed already
2. Not so sure on having people with clumsy be able to see that they're fake. I'd assume it's funnier if the clown didn't know it was fake, and allows people to meta it by having clumsy and clean SEs

2023-08-20 23:37 UTC, Burzah requested changes

2023-08-20 23:37 UTC, Burzah commented on code/datums/uplink_items/uplink_traitor.dm
> +	cost = 1
```suggestion
	cost = 5
```
This will need to be updated to account for the new TC Inflation PR that was just merged.

2023-08-21 18:56 UTC, S34NW approved these changes

2023-08-21 18:56 UTC, merged