No random critical/vomit stuns
ParadiseSS13/Paradise pull request #21952
Opened 2023-08-09 12:57 UTC by HMBGERDO

## What Does This PR Do

This PR replaces all Weaken and Paralyse procs in /mob/living/carbon/human/handle_critical_condition() with AdjustConfused() and KnockDown()
Same happened to /mob/living/carbon/proc/vomit, no more vomit stuns, instead you're being slowed down and confused

## Why It's Good For The Game

Random stuns while two IBs, random stuns while toxin damage, random stuns while total damage > 100, this all sounds awful. Just with some RnG you gonna loose the fight with no chance to fight back. You either fix the issue, either hope for RnG. 

Having no random stuns is good for me so i think this PR should be fine.

## Testing

Compiled, got damage

## Changelog
:cl:
tweak: Your character wont get stunned by vomiting anymore.
tweak: Your character wont get stunned randomly in critical state unless your health is less than -100.
/:cl:

2023-08-09 17:43 UTC, matttheficus commented
Unsure how I feel about this.

We already have a rough time with people in DEEP CRIT being able to keep fighting for what feels like an eternity. If youre sub-100 HP you dont deserve to keep fighting without possible downsides IMO.

The easiest way to avoid getting RNG maluses is to just never get there in the first place.

2023-08-09 20:17 UTC, HMBGERDO commented
Okay so, updated it
Now if you have -50 - 0 health, you recieve lesser crit, you get knockdown instead of weaken, you get confused instead of stuns
If you have less than -50 health, your life becomes pain, you have more chance to get stunned or paralysed.

It makes crit lighter at start and harder at end, so unless you get 150+ damage you're safe from RNG.

2023-08-11 23:20 UTC, Henri215 commented on code/datums/diseases/critical.dm
> +					affected_mob.emote(pick("groan"))
```suggestion
					affected_mob.emote("groan")
```

2023-08-11 23:20 UTC, Henri215 commented on code/datums/diseases/critical.dm
> +					affected_mob.emote(pick("groan"))
```suggestion
					affected_mob.emote("groan")
```

2023-08-17 11:17 UTC, HMBGERDO commented
PR was splitted into vomit stun change and crit stuns changes

2023-08-20 13:30 UTC, hal9000PR requested changes

2023-08-20 13:30 UTC, hal9000PR commented on code/modules/mob/living/carbon/carbon.dm
> +		Slowed(8 SECONDS)
slowed needs a second parameter for the amount it should slow you down by.

2023-08-20 13:30 UTC, hal9000PR commented on code/modules/mob/living/carbon/carbon.dm
>  	if(stun)
would you change the name of the parameter (also set the bools to TRUE/FALSE while you are at it)

2023-08-28 12:24 UTC, hal9000PR approved these changes

2023-08-28 12:53 UTC, merged