Using medicine on yourself on activate
ParadiseSS13/Paradise pull request #21955
Opened 2023-08-09 21:12 UTC by HMBGERDO

## What Does This PR Do

This PR allows you to click patch/pill/autoinjector(or just activate it with button Z) to apply it on yourself.

## Why It's Good For The Game

What if your screen is shaking, you have little sprite and you're in the locker with 20 other people, how do you heal self? Alt click and looking for your name?
It should not be hard, so now you can just press Z with medicine in hand to apply it on yourself.

## Testing

Compiled, activated various medicine

## Changelog
:cl:
tweak: Patches, pills, autoinjectors, trauma kits and other now can be used in hand to apply it on yourself.
/:cl:

2023-08-10 04:06 UTC, Contrabang requested changes

2023-08-10 04:06 UTC, Contrabang commented on code/game/objects/items/stacks/medical_packs.dm
> +	attack(user, user)
Please move the code out of attack, making a new proc with a new name, and call that instead
```suggestion
	start_apply(user, user)
```

2023-08-10 04:06 UTC, Contrabang commented on code/modules/reagents/reagent_containers/applicator.dm
> +	attack(user, user)
ditto here

2023-08-10 04:06 UTC, Contrabang commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	attack(user, user)
ditto here

2023-08-10 04:06 UTC, Contrabang commented on code/modules/reagents/reagent_containers/patch.dm
> +
This can be removed because patches are a subtype of pills
```suggestion
```

2023-08-10 04:06 UTC, Contrabang commented on code/modules/reagents/reagent_containers/pill.dm
> +	attack(user, user)
Make this also do the new proc, rather than calling attack also here

2023-09-01 22:02 UTC, S34NW approved these changes

2023-09-01 22:02 UTC, merged