Thermite tweak
ParadiseSS13/Paradise pull request #21950
Opened 2023-08-09 11:39 UTC by HMBGERDO

## What Does This PR Do

This PR changes thermite melting logic. Now melting time and melting progress is on thermite volume. Now it uses 100 units to melt r wall and 20 units to melt default wall. Melting r wall is 20 seconds, melting basic wall is 4 seconds.
When you start melting, it doesnt remove the wall, instead it is damaging it every second, making welder sound.

This does not affect T4, it still melts wall in 3 seconds(or whatever its time is)

## Why It's Good For The Game

I really dont like the idea of 3chem reagent being able to melt everything in one drop. This PR forces you to at least get MORE thermite to melt r walls, making raiding shit like AI sat harder. 

## Testing

Compiled, thermitted

## Changelog
:cl:
tweak: Thermite now requires volume to melt walls. 20 units to basic metal wall, 100 units to reinforced wall. Its melting time now is also based on wall type and its health. Every second thermite applies 30 damage to a wall and uses 5u of it. Thermite now is also making welding sounds every second instead of melting wall silently.
/:cl:

2023-08-09 11:44 UTC, 1080pCat commented
How does this effect the phlog flash fire interaction, if at all?
(splash termite then phlog onto a wall melting it considerably faster than normal termite)

2023-08-09 12:07 UTC, HMBGERDO commented
> How does this effect the phlog flash fire interaction, if at all? (splash termite then phlog onto a wall melting it considerably faster than normal termite)

this PR doesnt affect fireflash_sm proc if you're talking about that(instantly melting walls in blue fire) so means it will do the same

2023-08-16 18:28 UTC, matttheficus approved these changes

2023-08-16 19:43 UTC, S34NW requested changes

2023-08-16 19:43 UTC, S34NW commented on code/game/turfs/simulated/walls.dm
> +	if(O)	qdel(O)
```suggestion
	if(O)
		qdel(O)
```

2023-08-17 21:39 UTC, YoureNotTheSharpest commented
Wait this wasnt already merged?

2023-08-18 01:45 UTC, lewcc commented on code/game/turfs/simulated/walls.dm
> +	var/melting = FALSE
Please autodoc this

2023-08-18 01:45 UTC, lewcc commented on code/game/turfs/simulated/walls.dm
> +			break
```suggestion
	while(reagents.get_reagent_amount("thermite") > 0)
```

2023-08-25 15:48 UTC, merged