Adds crutches
ParadiseSS13/Paradise pull request #21959
Opened 2023-08-10 12:06 UTC by Contrabang

## What Does This PR Do

Adds crutches, a direct medical-grade upgrade to canes for those with missing or damaged legs. They remove slowdown from missing/damaged legs better than canes when wielded. They can be found in medical closets or made at the protolathe.

## Why It's Good For The Game
More flavor and options for those with disabilities is cool. (And more medical content)

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/1cfd7ca6-7107-49a1-8349-37192cfedc36)

## Testing

Cut off my legs, got crutches, then it wasn't so bad. Started up an ss13 server and did the same thing

## Changelog
:cl:
add: Medical crutches, to help people with missing/damaged legs.
/:cl:

2023-08-10 17:36 UTC, Henri215 commented on code/game/objects/items/weapons/misc_items.dm
> +	desc = "A medical device to help those walk who have injured or missing legs."
```suggestion
	desc = "A medical device to help those who have injured or missing legs to walk."
```
Like this is better?

2023-08-10 17:36 UTC, Henri215 commented on code/modules/research/designs/medical_designs.dm
> +	desc = "A pair of crutches to help those walk who have injured or missing legs."
```suggestion
	desc = "A pair of crutches to help those who have injured or missing legs to walk."
```

2023-08-13 22:49 UTC, Probablyjay19 commented
Can I use it like an axe? 👀

2023-08-16 18:02 UTC, McRamon commented
Inhands are not good enough, try to improve them using the example i sent

2023-08-19 14:28 UTC, Contrabang commented
> Inhands are not good enough, try to improve them using the example i sent

In hands updated

2023-08-19 14:29 UTC, Contrabang commented
> Can I use it like an axe? 👀

Nope, if you want a crutch for combat, use a chainsaw :)

2023-09-01 11:26 UTC, Henri215 commented on code/game/objects/items/weapons/misc_items.dm
> +/obj/item/cane/get_crutch_efficency()
efficiency*

2023-09-09 17:33 UTC, Henri215 approved these changes
LGTM (Lets Gamble, Try Mexico)

2023-09-09 17:33 UTC, Henri215 commented on code/game/objects/items/weapons/misc_items.dm
> +/obj/item/crutches // someone move these out of lockers into the map once the freeze is over :) (so we can get a consistent amount for each map)
Map freeze is over :)

2023-09-10 11:46 UTC, Git-GoR requested changes
Mapping changes look good, apart from Cyberiad where design does not align with floor decorations. I would suggest something like this (cleaner does not deserve a rack only for one item tbh)
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/5c1d0731-6cc0-40f0-b124-e281cbf33b80)

2023-09-10 14:51 UTC, Contrabang commented
> Mapping changes look good, apart from Cyberiad where design does not align with floor decorations. I would suggest something like this (cleaner does not deserve a rack only for one item tbh) ![imagen](https://user-images.githubusercontent.com/58085266/266833529-5c1d0731-6cc0-40f0-b124-e281cbf33b80.png)

Changes applied

2023-09-11 17:41 UTC, SteelSlayer approved these changes

2023-09-11 17:50 UTC, merged