Reduces the Universal Gun Kit's price to 5tc.
ParadiseSS13/Paradise pull request #21989
Opened 2023-08-14 21:05 UTC by PopeDaveThe3th

## What Does This PR Do
Reduces the Universal Gun Kit's price to 5tc from 8.

## Why It's Good For The Game
The UGK is very overpriced at double what a Stechkin costs for roughly equal performance, not even counting getting to the gun kit of your choice. This should make it slightly more palatable for agents.

## Testing
Loaded in, purchased gun kit, it was 5tc. 

## Changelog
:cl:
tweak: Changed UGK price to 5tc.
/:cl:

2023-08-15 10:19 UTC, Burzah approved these changes

2023-08-16 22:45 UTC, ItsMarmite commented
I really think you should keep in mind that none of these weapons are contraband, meaning at best you can get a restricted weapon charge for possessing them.

2023-08-18 13:19 UTC, DGamerL approved these changes
Code looks good, but I do agree with Marmite that it should maybe be like 1 TC more expensive

2023-08-20 23:27 UTC, Burzah requested changes

2023-08-20 23:27 UTC, Burzah commented on code/datums/uplink_items/uplink_general.dm
> +	cost = 5
```suggestion
	cost = 25
```
This will now have to be changed in order to conform to the new TC inflation PR that was merged.

2023-08-21 18:41 UTC, DGamerL approved these changes

2023-08-21 18:44 UTC, Henri215 commented
Update the PR title and description with the new TC values (damn inflation)

2023-08-21 18:45 UTC, Sadhorizon commented
This should probably be updated to be in-line with the TC inflation

2023-08-26 22:06 UTC, Henri215 approved these changes

2023-08-26 23:37 UTC, Burzah approved these changes

2023-08-28 12:35 UTC, S34NW approved these changes

2023-08-28 12:35 UTC, merged