The TC Inflation Act of 2023 - No Balance Changes This Time
ParadiseSS13/Paradise pull request #22024
Opened 2023-08-18 14:32 UTC by matttheficus

## What Does This PR Do
Multiplies most TC costs, rewards, and totals by five.
`20TC` Traitor Uplinks > `100TC` etc etc etc.
Contractor payouts and totals multiplied by `5`.
Nuclear Operatives total TC multiplied by `5`.
Uplink Items and such all multiplied by `5`.

## Why It's Good For The Game
This has been discussed by most of the Dev Team for a few months now. This will allow for more variance in Uplink/Operative items in the future, as well as allow us to fine-tune items that are over/underperforming in a more slight way.

This will lead to people having to add bigger numbers together. I do hope everyone is capable of basic math. If not, your phone or computer has a calculator if you cant count to 100 (Operatives on the other hand get a LOT more TC to work with, so I wont fault you there).

In the future, we've discussed adding a "checkout" system, especially for Operatives, so that you can add stuff to a "cart" and check out your items in bulk, perhaps with some discounts that way for Traitors too. But, as that touches TGUI and would build upon this, Ill leave that for later/someone else to do it. 

## Testing
1. Spawn in.
2. Purchase warcrimes from various uplinks.
3. Double check that Contracts are paid out correctly.

## Changelog
:cl:
tweak: Tweaked TC economy to work from a 100TC budget for Traitors and radiating changes to all other Uplink systems.
/:cl:

2023-08-18 17:54 UTC, hal9000PR requested changes

2023-08-18 17:54 UTC, hal9000PR commented on code/datums/uplink_items/uplink_nuclear.dm
> -	cost = 12 // normally 18
12 * 5 = 60 not 75

2023-08-18 17:54 UTC, hal9000PR commented on code/datums/uplink_items/uplink_nuclear.dm
> -	cost = 12 // normally 18
12 * 5 is 60

2023-08-20 12:15 UTC, hal9000PR approved these changes

2023-08-20 13:35 UTC, Henri215 approved these changes
MLGTM

2023-08-20 13:51 UTC, DGamerL approved these changes
The math seems to be mathing

2023-08-20 16:36 UTC, SteelSlayer approved these changes

2023-08-20 23:20 UTC, merged