Removes Stun Arm from Safety Override, Adds Proto Emitter
ParadiseSS13/Paradise pull request #22076
Opened 2023-08-23 01:02 UTC by matttheficus

## What Does This PR Do
Removes Stun Arm from the Safety Override for EngiBorgs.
Adds the Proto Emitter Gun to the Safety Override for EngiBorgs.

## Why It's Good For The Game
There is no reason for the Crew to be able to make pseudo-SecBorgs. We dont need more insta-stuns for Antags to deal with. This was discussed with GAs/HAs before being made, as we see this as an issue.

Given that some Antag Roboticists used this for evil, I gave them a ranged emitter that's slightly weaker than the Malf AI one.

## Testing
Tested the Safety Override on myself, it works.

## Changelog
:cl:
add: Added Proto Cyborg Emitter to the EngiBorg Safety Override.
del: Removed Stun Arm from the EngiBorg Safety Override.
/:cl:

2023-08-23 15:56 UTC, matttheficus commented
> Just to clarify, does this leave the stunarm for emmaged cyborgs, or is it removed entirely?

This ONLY effects the Safety Override Module that the Crew can make at Robotics, it doesnt touch emag/malf AI.

2023-08-28 12:11 UTC, S34NW requested changes
Safety Override here also adds another RCD, this is not documented.

2023-08-28 16:10 UTC, matttheficus commented
> Safety Override here also adds another RCD, this is not documented.

Ack, my bad. Left over from brainstorming. Will remove.

2023-09-01 22:13 UTC, S34NW approved these changes

2023-09-01 22:13 UTC, merged