Burn wound surgery
ParadiseSS13/Paradise pull request #22105
Opened 2023-08-25 14:03 UTC by HMBGERDO

## What Does This PR Do

reopening this https://github.com/ParadiseSS13/Paradise/pull/21801

## Testing

compiled, did surgery

## Changelog
:cl:
add: Adds burn wounds surgery to fix critical burns, similar to internal bleeding surgery. Scalpel -> Hemostat -> Retractor -> Advanced burn kit -> Cautery.
/:cl:

2023-08-25 15:56 UTC, farie82 commented
Please add the original description or your own, so it is easier to see at a quick glance what this PR does.

2023-09-09 22:58 UTC, lewcc requested changes

2023-09-09 22:58 UTC, lewcc commented on code/modules/surgery/other.dm
> +		"<span class='warning'>Your hand slips, slicing an artery inside [target]'s [affected.name] with \the [tool]!</span>"
```suggestion
		"<span class='warning'>[user]'s hand slips, slicing an artery inside [target]'s [affected.name] with [tool]!</span>",
		"<span class='warning'>Your hand slips, slicing an artery inside [target]'s [affected.name] with [tool]!</span>"
```

2023-09-09 22:58 UTC, lewcc commented on code/modules/surgery/other.dm
> +		"You start to treat affected tissue in [target]'s [affected.name] with [tool]."
```suggestion
		"[user] starts to treat the scorched tissue in [target]'s [affected.name] with [tool].",
		"You start to treat the scorched tissue in [target]'s [affected.name] with [tool]."
```

2023-09-09 22:58 UTC, lewcc commented on code/modules/surgery/abstract_steps.dm
> +	to_chat(user, "<span class='warning'>The skin on [target]'s [parse_zone(affected)] seems to be in perfect condition, it doesn't need treatment.</span>")
I'm pretty sure you don't need this here and can let the begin step handle the message. Sending messages in the `can_start` is a little bit of a no-no.
```suggestion
```

2023-09-16 21:26 UTC, lewcc requested changes
From what I can see, the surgery logic looks good. Just one note on the name of the surgery.

2023-09-18 00:17 UTC, lewcc approved these changes

2023-09-18 00:17 UTC, merged