Parallax in Darkness
ParadiseSS13/Paradise pull request #22136
Opened 2023-08-27 13:54 UTC by HMBGERDO

## What Does This PR Do

This PR allows you to toggle parallax in darkness which will render parallax instead of dark tiles if you wear nightvisions or other item that adjusts your vision

## Why It's Good For The Game

This was a bug from widescreen PR when you could seen parallax instead of dark tiles with nightvisions
Bug was fixed because its disorientating but i find this thing really cool and beauty
So here i add this thing back.

## Images of changes

https://youtu.be/JWh8ru8avFc
![image](https://github.com/ParadiseSS13/Paradise/assets/61080616/58eb01fb-7a80-4073-98a1-b4c3e05cbe01)

## Testing

compiled, changed settings, saw parallax, no SQL errors

## Changelog
:cl:
add: Added toggleable parallax in darkness.
/:cl:

2023-08-27 16:00 UTC, GDNgit commented
this is certainly a cool idea, but I don't personally love the super bright version we got here, previously the Parallax would be darkened when viewing it from indoors, maybe you could allow for a brightness setting?

2023-08-27 16:05 UTC, HMBGERDO commented
> this is certainly a cool idea, but I don't personally love the super bright version we got here, previously the Parallax would be darkened when viewing it from indoors, maybe you could allow for a brightness setting?

It is still darker than space turf parallax and its brightness depends on your nightvision, with thermals parallax would be darker.
Sadly i dont think there is easy way to make darkness on it but i will think about it later

2023-08-27 18:54 UTC, AffectedArc07 submitted a review, later dismissed
This needs to be a bitflag toggle in the regular `toggles_2` column, not an entire extra DB column for a binary toggle.

2023-08-27 20:10 UTC, HMBGERDO commented
No longer requires SQL update, moved to toggles2

2023-08-28 18:08 UTC, hal9000PR requested changes

2023-08-28 18:08 UTC, hal9000PR commented on code/__DEFINES/preferences_defines.dm
>  #define TOGGLES_2_TOTAL 			262144 // If you add or remove a preference toggle above, make sure you update this define with the total value of the toggles combined.
change the total. as per the comment

2023-09-23 15:29 UTC, Contrabang reviewed
I'm no master of plane masters, but this looks good to me. Just one requested change

2023-09-23 15:29 UTC, Contrabang commented on code/modules/client/preference/link_processing.dm
> +					parent?.mob?.hud_used?.update_parallax_pref()
If a holder somehow has no client, it should probably runtime while running this.
```suggestion
					parent.mob?.hud_used?.update_parallax_pref()
```

2023-09-23 15:29 UTC, Contrabang commented on code/__DEFINES/preferences_defines.dm
> +#define TOGGLES_2_TOTAL 			524287 // If you add or remove a preference toggle above, make sure you update this define with the total value of the toggles combined.
Thank you for properly fixing this. For any other reviewers, this number is correct. The formula is `(1 << LATEST+1 ) - 1`

2023-10-01 11:05 UTC, S34NW approved these changes

2023-10-01 11:06 UTC, merged