Removes All CamelCase'd "NanoTrasen"
ParadiseSS13/Paradise pull request #22156
Opened 2023-08-29 03:05 UTC by matttheficus

## What Does This PR Do
Standardizes all mentions of Nanotrasen to not be CamelCase'd as per Lore Team.

Adds a reminder to the Other Notes section of the Contributor's Guide.

## Why It's Good For The Game
Standardization good.

_Why the FUCK is there a VAR EDITED mention of this on MetaStation god damn that map makes me WANT to hate it._

## Testing

## Changelog
:cl:
spellcheck: ensures proper standardizations for all mentions of "Nanotrasen".
/:cl:

2023-08-29 11:05 UTC, Burzah approved these changes

2023-09-01 20:58 UTC, Contrabang approved these changes
LGTM

2023-09-03 14:17 UTC, Contrabang commented on tools/ci/check_grep2.py
>  TO_CHAT_WITH_NO_USER_ARG_RE = re.compile(r"to_chat\(\"")
```suggestion
        if NANOTRASEN_CAMEL_CASE.search(line):
            return Failure(idx + 1, "Nanotrasen should not be spelled in the camel case form.")
            
TO_CHAT_WITH_NO_USER_ARG_RE = re.compile(r"to_chat\(\"")
```

2023-09-03 20:50 UTC, Contrabang reviewed
One last change, glad I made the CI lol (manuals.dm 152)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/07c3da62-7143-4343-886e-7a0be58b8d00)

2023-09-04 02:07 UTC, Contrabang approved these changes
LGTM

2023-09-04 22:44 UTC, dearmochi approved these changes
Not sure how I feel about going as far as adding a check in CI, but LGTM

2023-09-07 09:57 UTC, S34NW requested changes
I don't think we need to spend CI time on this sort of thing, rest looks fine though

2023-09-07 09:59 UTC, AffectedArc07 commented
> I don't think we need to spend CI time on this sort of thing, rest looks fine though

The CI time is minimal, especially when considering this proble will happen again without it.

Keep the CI.

2023-09-07 10:18 UTC, S34NW approved these changes

2023-09-07 10:18 UTC, merged