Verb cleanup
ParadiseSS13/Paradise pull request #22224
Opened 2023-09-03 01:34 UTC by GDNgit

## What Does This PR Do
Removes the vast majority of object verbs, replaced with click combinations that are displayed on examine (Did you know glasses had an adjust verb? If not, you can probably see the first issue with object verbs). Mostly done with this, if I don't finish this today, I will tomorrow.
I haven't done this yet because I'm looking for feedback, but this pr will also be overhauling the admin verb UI to have less duplicate verbs/duplicate procs, along with just better organization.
Deletes a few admin only items that don't work
It's time we damn these to hell, outdated as fuck

## Why It's Good For The Game
A couple of reasons
1. The vast majority of these don't work (such as having unfulfillable activation conditions) or have direct alternatives within the same player area (did you know holster had a verb?), these aren't being maintained and they quite frankly won't be. 
2. Depending on your PC, you may be unable to move while focusing the object verb menu, this is bad for obvious reasons and click combinations are better in general.
3. Players are taught rather early on to examine everything to gain information about it, not right click everything. Most people won't know these features and there's no reason to keep it from them.
4. Fucking hell man these are clunky what do you even want me to say?

Admin UI needs an overhaul, pull up the admin verbs menu and tell me otherwise.

## Testing
So far so good, lots of clicking on items

## Changelog
:cl:
tweak: Most object verbs have been replaced with click combinations, examine the object to view the required combination 
/:cl:

2023-09-08 16:33 UTC, Sirryan2002 commented
Can you make a list of the removed verbs? I want to double-check that we're not removing something that has an important (but rare) use.

2023-09-08 17:16 UTC, GDNgit commented
> Can you make a list of the removed verbs? I want to double-check that we're not removing something that has an important (but rare) use.

Of course, once I'm done with the PR I'll slap it in there

2023-09-21 00:45 UTC, GDNgit commented
This pr now only handles specific datum verbs, admin verbs and pref verbs will come in another pr

2023-10-27 00:04 UTC, larentoun requested changes
This is what I noticed in 30 minutes of quick glance

2023-10-27 00:04 UTC, larentoun commented on code/modules/projectiles/guns/projectile/revolver.dm
> +		user.visible_message("[usr] spins [src]'s chamber.", "<span class='notice'>You spin [src]'s chamber.</span>")
why not the first one is `notice` too?

2023-10-27 00:04 UTC, larentoun commented on code/modules/reagents/reagent_containers.dm
> +	if(!ishuman(user) || HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
Not sure if `ishuman()` is needed here

2023-11-04 15:31 UTC, GDNgit commented on code/game/machinery/rechargestation.dm
>  	go_out()
Yeah this is a helper for admin procs

2023-11-04 15:33 UTC, GDNgit commented on code/game/machinery/washing_machine.dm
> +	if(state != 4)
The washing machine is a little shit already and I'm touching as little of it as possible

2023-11-04 15:35 UTC, GDNgit commented on code/game/objects/structures/crates_lockers/crates.dm
> +		if(HAS_TRAIT(user, TRAIT_HANDS_BLOCKED) || user.stat ) // Don't use it if you're not able to! Checks for stuns, ghost and restrain
adjacent two lines above that

2023-11-04 15:36 UTC, GDNgit commented on code/game/objects/structures/reflector.dm
> +	dir = turn(dir, 90)
yeah

2023-11-04 15:37 UTC, GDNgit commented on code/modules/clothing/clothing.dm
> +	if(user.stat || HAS_TRAIT(user, TRAIT_HANDS_BLOCKED) || !Adjacent(user) || !istype(user))
doesn't really matter

2023-11-04 15:42 UTC, GDNgit commented on code/modules/reagents/reagent_containers.dm
> +	if(!ishuman(user) || HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
input menu, sleeps

2023-11-04 15:49 UTC, GDNgit commented on code/modules/mob/mob.dm
> +// Nobody in their right mind will have this enabled on the production server, uncomment if you want this for some reason
right now you ALWAYS get this verb in the ooc tab so it's just kinda silly

2023-11-12 20:13 UTC, Sirryan2002 approved these changes
lets get this through, what's the worst that could happen. If no one notices these being removed then they probably needed to go anyway.

2023-11-12 20:14 UTC, S34NW approved these changes
Deconflict for merge

2023-11-12 20:19 UTC, merged

2023-11-14 09:48 UTC, Dafrek commented
> lets get this through, what's the worst that could happen. If no one notices these being removed then they probably needed to go anyway.

The most noticeable part for me is not being able to toggle suit sensors the old way and pointing at objects that you try to pick up because the bar is one higher than it used to be.