AI in mech now uses mech cell instead of area power
ParadiseSS13/Paradise pull request #22241
Opened 2023-09-04 12:34 UTC by Adrer

## What Does This PR Do
When an AI controls a mech, either through an AI beacon or with the Mech Domination power, they are no longer dependant on the area the mech is standing in being powered by an APC; Instead, the cell inside the mech is used to check if the AI has powered or not.
Fixes: #11968

## Why It's Good For The Game
It doesn't make sense that the AI should need a separate power source to be powered when inside of a mech.

## Testing
Be a malfunctioning AI
Use the mech domination power on a Durand
Enter an unpowered area, I remain functional as normal
Set the power of the Durand's cell to 0
I cease functioning as normal

## Changelog
:cl:
tweak: AI controlling a mech now uses the mech cell for power instead of the area's APC.
/:cl:

2023-09-04 12:46 UTC, Contrabang commented on code/modules/mob/living/silicon/ai/ai_life.dm
> +		return(!(controlled_mech.get_charge() > 0))
```suggestion
		return (!(controlled_mech.get_charge() > 0))
```

2023-09-04 13:36 UTC, Contrabang commented on code/modules/mob/living/silicon/ai/ai_life.dm
> +		return (!(controlled_mech.get_charge() > 0))
mostly just a personal pref, feel free to not change this. LGTM
```suggestion
		return !(controlled_mech.get_charge() > 0)
```

2023-09-06 17:05 UTC, lewcc requested changes

2023-09-06 17:05 UTC, lewcc commented on code/modules/mob/living/silicon/ai/ai_life.dm
> +		return !(controlled_mech.get_charge() > 0)
More concise

```suggestion
		return controlled_mech.get_charge() <= 0
```

2023-09-07 10:15 UTC, merged