The degrilling: map windows no longer have grilles under them unless electrified
ParadiseSS13/Paradise pull request #22273
Opened 2023-09-07 10:07 UTC by Git-GoR

## What Does This PR Do
This PR removes the grilles from most of the **roundstart windows**. Only the ones that have an actual gameplay difference have been kept, which are those with a cable node under them. These are usually located in high security areas, for safety reasons.

In order to keep mapping changes to a minimum, the base window spawner has been modified to not spawn grilles by default. New `/grilled` subtypes of each window variant have been added, and new `icon_state`s have been made for grille-free windows.

The mapping changes have been done automatically with the help of @warriorstar-orion. And the are paths have been updated following #21681 changes by using the supplied UpdatePaths.

## Why It's Good For The Game
Honestly? :sparkles: *Aesthetics* :sparkles: 

But the other main reason is that, as of right now, all windows have grilles under them. This offers no gameplay difference besides a couple more hits to destroy a window, or no effort if you have wirecutters with you. It only adds visual clutter.

With this change, players can gain a visual representation of what is a **high security area**, on top of new antag players being able to recognize what windows will shock them (bridge, head offices, brig etc.).

On top of that, this is part one of the window changes I've planned. The idea is to **stop using reinforced windows everywhere**, and keep them only for secure areas + space adjacent windows. Most likely, this will include a buff to normal windows, because currently they are weaker than wet paper.

I am aware that the plating under the windows, now that it's nicely visible, might not look the best as it clearly marks the breaks between each window tile instead of giving the illusion of one continuous window. Honestly, each time I see it I have a different opinion. Whether basic flooring is preferred under all windows or not is something that might have to be discussed in this PR's comments. It is also possible to make some flooring decal that would fit the window floors better?

## Images of changes
Couple of images showing both types:

![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/cbc09ba5-4aa3-4e71-aead-520500a2e3e7)
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/cd19427e-b1f9-4635-a22a-f563281f6442)

Check that all spawners work correctly:

![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/8ec6c618-dde5-4da0-94fd-10733bcfcc65)

## Testing
- Log into game, create all types of window spawners and ensure they work properly
- Check that most windows do not have grilles
- Ensure that areas such as Bridge, Brig, Heads offices etc. **do** maintain their grilles
- Start making some nice hamb- wait no

## Changelog
:cl: GoR, warriorstar
tweak: Removes grilles from most windows in all maps, keeping them only on electrified ones.
/:cl:

2023-09-07 13:45 UTC, 1080pCat commented
I love this, next step is to remove all the fun Rwindows that really should be normal!

2023-09-09 16:30 UTC, matttheficus commented
To be honest, any space-facing window should still have grilles IMO. It would prevent people from getting sucked out into space.

Interior windows are fine, however.

2023-09-17 11:28 UTC, matttheficus commented
The RCD also probably needs a setting for non-grilled windows as well.

2023-09-21 19:52 UTC, Git-GoR commented
> I love this, next step is to remove all the fun Rwindows that really have no use of being reinforced!

Yes, that would be the idea. As the PR body mentions, it would most likely be paired with a buff to normal windows!

>To be honest, any space-facing window should still have grilles IMO. It would prevent people from getting sucked out into space.
Interior windows are fine, however.

Done, all windows that lead to space are now back to being grilled. I've done the main stations for now, will see if I can take a look at the ruins. But I imagine they would be less crucial.

> The RCD also probably needs a setting for non-grilled windows as well.

🔬 [IIIIIIIIIIIIIIII:::::::::::::::::::::::::::::::::::::::::::] 🔭 
WARNING: SCOPE SIZE KEEPS INCREASING

I'll see what I can do! I imagine it can always be tacked on the following window health/armor/tool changes PR, which would be free from mapping queue. Specially if design/balance team decides to make reinforced windows stronger (like requiring a welder, for example) and therefore only normal windows are to be RCD'd.

2023-10-03 15:57 UTC, S34NW requested changes

2023-10-03 15:57 UTC, S34NW commented on _maps/map_files/Delta/delta.dmm
Do double check under signs, delta has some unintended changes under those
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/d16fad33-b4ac-468d-b4fe-8fc9a4f0a5e2)

2023-10-03 16:00 UTC, S34NW commented on _maps/map_files/Delta/delta.dmm
Same with these plasma glass windows on delta
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/e27964bf-1f2c-42cc-bdd8-0162d6a2db01)

2023-10-03 16:02 UTC, S34NW commented on _maps/map_files/cerestation/cerestation.dmm
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/1022da34-fbff-44ed-9217-5d03684440ca)
Cere sci teleporter

2023-10-04 08:25 UTC, Git-GoR commented on _maps/map_files/cerestation/cerestation.dmm
Fixed.

2023-10-05 18:35 UTC, S34NW approved these changes

2023-10-05 18:35 UTC, merged

2023-10-06 05:09 UTC, Beepsquad commented
but... why