Removes Bluespace Tile Speed, Replaces It With Anti-Slowdown
ParadiseSS13/Paradise pull request #22271
Opened 2023-09-07 06:00 UTC by matttheficus

## What Does This PR Do
Removes the insanely fast speedboost that Bluespace Tiles give you.

They now remove various slowdowns that the Crew deals with - giving you some decent QoL while on these tiles.

**Currently Affected**
- Pulling

**WIP Affected**
- Suit/Gear Slowdown
- JaniCart/Ambulance Slowdown

## Why It's Good For The Game
The Bluespace Tiles are a massive headache. They stack with things like meth, changeling speedlegs, and xenomorphs.

I have quite literally charged Xenobiologists with Aiding and Abetting EoCs for constantly putting these tiles down. Its a combat nightmare (Speed = Winning in SS13) and make chasing antagonists/targets/etc on our larger maps a nightmare.

Changing it to a QoL item instead of a ZOOOOOOOOOM item retains its usefulness for Xenobio to make without making every player have to play Sonic the Hedgehog Simulator for any sort of chase.

## Testing
Ran about like a chicken with my head cut off.

## Changelog
:cl:
tweak: Bluespace Tiles now affect slowdown instead of increasing your movespeed.
/:cl:

2023-09-07 06:16 UTC, matttheficus commented
There are only two pieces of gear I can see that would get de-speed'd due to this:

- Ninja Shoes
- The Admin Suit

Considering these are both admin-only, I frankly do not care for them.

2023-09-08 22:45 UTC, matttheficus commented on code/modules/mob/living/carbon/human/human_movement.dm
> -		. += pulled.pull_speed
Outta scope for this PR, would need to be in a PR dedicated to pulling stuff.

2023-09-08 22:48 UTC, matttheficus commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	if(!istype(get_turf(H), /turf/simulated/floor/bluespace))
Thought a bit more on traits. Unsure if I want to add a trait that EVERY SINGLE MOB has to check/have for this to work. Doing a type check is fine here IMO (also cleaned the pulling one up a bit). If for some reason there's more of a push toward using traits instead from Headcoders/PRRs Ill look into swapping it.

2023-09-09 06:11 UTC, GDNgit commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	if(!istype(get_turf(H), /turf/simulated/floor/bluespace))
Matt you can put the trait on the turf

2023-09-09 16:25 UTC, matttheficus commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	if(!istype(get_turf(H), /turf/simulated/floor/bluespace))
`if(!has_trait(get_turf(H), TRAIT_WHATEVER))` is basically the exact same kind of check IMO - just replacing an `istype` with a `has_trait`. I dont see a massive benefit from one to the other.

2023-09-22 03:31 UTC, Dimach commented on code/game/turfs/simulated/floor.dm
> +	var/buffs
```suggestion
```
Useless code

2023-09-22 10:14 UTC, Henri215 commented on code/modules/mob/living/carbon/human/human_movement.dm
>  /mob/living/carbon/human/Process_Spacemove(movement_dir = 0)
```suggestion
	. += dna.species.movement_delay(src)

/mob/living/carbon/human/Process_Spacemove(movement_dir = 0)
```

2023-09-23 16:34 UTC, Contrabang commented on code/__HELPERS/trait_helpers.dm
> +#define TRAIT_BLUESPACE_SPEED "bluespace_speed_trait"
Add this to the global init list of `traits_by_type` please

2023-10-01 11:18 UTC, S34NW requested changes
One thing then good for merge

2023-10-01 11:18 UTC, S34NW commented on code/modules/mob/living/carbon/human/species/_species.dm
> +	if(!HAS_TRAIT(T, TRAIT_BLUESPACE_SPEED))
```suggestion
	if(istype(T) && !HAS_TRAIT(T, TRAIT_BLUESPACE_SPEED))
```
No point typecasting if we don't check the result

2023-10-01 16:38 UTC, S34NW approved these changes

2023-10-01 16:41 UTC, merged