Heads/sec/legal can no longer join after revolutionaries have won + Refactor
ParadiseSS13/Paradise pull request #22328
Opened 2023-09-10 17:39 UTC by Contrabang

## What Does This PR Do

Heads/sec/legal have their total positions set to 0 after revolutionaries have won. Also does a refactor of the `is_supply, is_service, is_command...` vars on jobs, and turns them into bitflags. This does NOT touch the database bitflags, because I am scared of those. It also introduces a job banned gamemode var on jobs, just in case somehow the total_positions are altered. Cryoing as gamemode banned role will not free your slot

## Why It's Good For The Game
In the revolution gamemode, the gamemode ends right after the heads die, so it doesn't really matter. But as we make our way towards dynamic, we will need a system to stop more heads/sec from joining once the station is rev controlled. This is my preposed solution.

## Testing

Compiles, joining as roles worked, newscasters worked. The code for revs winning and setting all heads/sec/legal jobs to zero and preventing them from being seen on the menu seems to have worked.

## Changelog
:cl:
tweak: Heads of staff, security, IAAs, and magi cannot join after revolutionaries have won
/:cl:

2023-09-10 20:41 UTC, Contrabang commented on code/game/gamemodes/nuclear/nuclear.dm
/datum/game_mode/nuclear/check_win() was removed because im also trying to cut down on check_win. And this doesnt actually do anything.

2023-09-18 14:39 UTC, Sirryan2002 commented on code/game/jobs/job/job.dm
> +	var/job_banned_gamemode = FALSE
please document this variable

2023-09-18 14:39 UTC, Sirryan2002 commented on code/modules/antagonists/revolutionary/team_revolution.dm
> +	var/msg = "The revolutionaries have won! All command, security, and legal jobs have been removed. You can change this with the \"Free Job Slot\" verb."
this seems directed at admins during the round, could you create a second msg that is better suited for adding logs. I.e. something like "Revolutionary win conditions met, command, security, and legal jobs are now closed."

2023-09-19 21:48 UTC, Sirryan2002 approved these changes

2023-09-25 22:35 UTC, lewcc requested changes
Make sure the QM is marked as a head here, owing to the recent changes.

2023-09-25 22:35 UTC, lewcc commented on code/game/jobs/job/support.dm
> +	job_department_flags = DEP_FLAG_SUPPLY
```suggestion
	job_department_flags = DEP_FLAG_SUPPLY | DEP_FLAG_COMMAND
```

2023-09-25 22:56 UTC, lewcc approved these changes
Looks good

2023-09-25 23:03 UTC, merged