Ports Humans from TG - Soul Massacre
ParadiseSS13/Paradise pull request #22361
Opened 2023-09-11 21:33 UTC by Alecksohs

## What Does This PR Do

Ports TG's Human Sprites to Paradise

## Why It's Good For The Game

The human sprites are shit. These are less shit. What greater justification do you need? What you want an essay? Okay.

Paradise's Human Sprites are very very old. Their age shows, as they are closer to Yellow Goblins than anything human. TGStation takes the silhouette and implements hue shifting, shading, and implication into the sprite, allowing it to be compatible with all clothes yet look better.  I don't wanna write an essay thats what you get I'm tired

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/9b02aadb-fee0-45e9-89b0-bffaefd917bb)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/47f53a71-5655-4718-84cc-f42bdbf8acc9)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/8f5c3af6-ca89-4615-a100-794a354d2519)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/8d7f2e7a-67c0-402c-bfa4-73d3476d9173)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/8bfc5a17-f9cb-4ad5-a147-7580d22806d8)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/80ee7885-d9c7-4287-875a-a475edb21106)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/11c82be4-2aab-42ba-85b0-3efa4431373d)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/67ea9315-93f4-49b9-a52c-3e3b5abd5777)

## Testing

I loaded it into the game. I played with the skintones and they work for the shitcode we employ, still its better though. Everything works fine.

## Changelog
:cl:
tweak: Ported TG Humans
/:cl:

2023-09-11 21:35 UTC, A-Medster commented
They feel so..
Fleshy..

2023-09-11 21:36 UTC, JimKil3 approved these changes
lgtm :) can't wait to get emails for all the discussion on this

2023-09-11 21:38 UTC, Contrabang approved these changes
code is fine

2023-09-11 21:39 UTC, Alecksohs commented
I did it I saved the server

2023-09-11 21:40 UTC, Henri215 requested changes
Some cardboards from ```icons/obj/cardboard_cutout.dmi``` will have to be updated now that humans look different.

2023-09-11 21:40 UTC, DGamerL approved these changes
The two sides of reviewers
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/6315cf20-7b96-42c4-a2e2-550a682c1635)

2023-09-11 21:42 UTC, Alecksohs commented
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/7bede5c0-e9ac-4ddc-a92a-3b835f10031e)
WAIT IS THIS ONE ALREADY USING TG SPRITES LMFAO

2023-09-11 21:50 UTC, Alecksohs commented
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/7324eeec-5505-439a-9b1e-d4d9552d936e)
Fixed

2023-09-11 22:43 UTC, Alecksohs commented
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/9a9481ba-903f-4ba6-951a-5a7e93001742)
Simplemobs fixed

2023-09-11 22:49 UTC, Henri215 approved these changes
Its looking good to me now.

2023-09-11 23:30 UTC, Mitchs98 commented
These just look extremely off to me, very changeling flesh suit-y but less bloated. They just look fake, too shiny and smooth looking, while also being kinda wrinkly and fat roll-y in certain spots. What we have isn't exactly the peak in spriting but it looks better to this to me. 

It could be a coding issue, it could not be. I have no idea. But this just looks like a downgrade in its current state regardless of how bad our current sprites may or may not be.

2023-09-11 23:32 UTC, Alecksohs commented
> These just look extremely off to me, very changeling flesh suit-y but less bloated. They just look fake, too shiny and smooth looking, while also being kinda wrinkly and fat roll-y in certain spots. What we have isn't exactly the peak in spriting but it looks better to this to me.
> 
> It could be a coding issue, it could not be. I have no idea. But this just looks like a downgrade in its current state regardless of how bad our current sprites may or may not be.

As stated in the discord, it could be a contrast issue and likely is. I'd request assistance from any coder who would like to assist, create a human skin preset system with skin colors having their own sprites. If said coder would like to be a baller, he could just port the skin tone code itself. However my coding knowledge isn't that far.

2023-09-11 23:49 UTC, Alecksohs commented
Working on the skincode now, also fixing a few gripes with the TG sprite itself

2023-09-12 01:09 UTC, Alecksohs commented
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/243e33a6-cd36-4d0f-9f4f-a6ca578c0dd8)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/1d2cb6c0-5eb9-4a6f-8ad2-d52d7ab4a9dd)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/5d91cdc3-4556-48e0-a1c4-99aa90df4351)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/6c05a8b3-c55e-4324-bd35-594f9ca7991e)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/a42ecdd6-54e5-4dad-87e1-d1db7e8d3dd7)

Using preset skintones, here are the ones I've created.

2023-09-12 01:31 UTC, Alecksohs commented
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/4afe3ca4-e53d-4d4b-9592-65bf4a18ced2)
the classic tm
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/61962bc5-304a-405d-8550-9a01e3307d06)

2023-09-12 04:29 UTC, Alecksohs commented
I'm ruining vox too but thats a separate pr

2023-09-12 06:22 UTC, Mitchs98 commented
Looks quite a bit better than the original implementation of the port, by far.

2023-09-12 13:24 UTC, Alecksohs commented
This is quite feature complete, now.

2023-09-12 15:59 UTC, S34NW commented on code/modules/mob/living/carbon/human/species/human_species.dm
You've changed this file to CRLF instead of our standard of LF. CI failing.

2023-09-12 16:15 UTC, Alecksohs commented on code/modules/mob/living/carbon/human/species/human_species.dm
I used the DM editor, strange. How do I fix that?

2023-09-12 16:24 UTC, Alecksohs commented on code/modules/mob/living/carbon/human/species/human_species.dm
I imported it into notepad++ changed it to UnixLF and then saved that as a dm and just pushed it.

2023-09-12 17:48 UTC, DT2399 commented
the new sprites looks so good

2023-09-25 01:59 UTC, TerraTheUnwise commented
please don't

2023-10-07 10:14 UTC, S34NW approved these changes

2023-10-07 10:16 UTC, merged

2023-10-07 19:08 UTC, Alecksohs commented
I forgot to fix the butt pixels chat on the chestnut skin tone this is my fault please put down your pitchforks idk how to put out the fire (fix it)