Port TG Backpacks, Duffelbags and Satchels - can't stop addicted to the shindig
ParadiseSS13/Paradise pull request #22373
Opened 2023-09-12 17:48 UTC by Alecksohs

## What Does This PR Do

Ports the backpacks duffelbags and satchels from TG

## Why It's Good For The Game

better

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/63c34a19-0fb8-465b-8b2f-b6f5cca2e21f)

Okay now just imagine the rest heres the spritesheet this took 40 minutes to setup and I'm not doing it again for other backpacks lmfao

![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/b2441b92-6f76-4771-9360-728ff31e9c07)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/16dbbadf-f5d6-41eb-8334-b367bb7696bd)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/fbef8f40-7230-42d1-a55f-1d989b120858)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/db7c7ed1-a1b6-4031-ad96-3c847ab3c21c)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/7ded66b0-e396-4e60-84ab-d0f96702d8d9)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/3c73628e-f012-43d9-9e93-31bc4d67d744)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/65b029a4-9233-4bf5-b53c-ec3cfd906d78)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/ee1f2a86-86de-49f2-89a7-d46b32102711)
![image](https://github.com/ParadiseSS13/Paradise/assets/32783144/5a7724c4-8d15-4f39-b0f7-f96a96992534)

## Testing

## Changelog
:cl:
tweak: Ported TG Backpacks
/:cl:

2023-09-12 17:49 UTC, Alecksohs commented
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

ugly

2023-09-12 17:50 UTC, Henri215 commented
"imageadd:" instead of "tweak:" over your changelog

2023-09-12 17:56 UTC, DT2399 commented
Nicee!

2023-09-12 18:01 UTC, Burzah commented
I see that the testing field is empty. Were all the sprites that are included get examined in game?

2023-09-12 18:05 UTC, Alecksohs commented
> I see that the testing field is empty. Were all the sprites that are included get examined in game?

idk what you mean its not empty smh my head

2023-09-13 06:25 UTC, ATP-Engineer commented
Can you do the same for holder bags such as viro, chem, and botany.

2023-09-18 12:44 UTC, DGamerL commented
Science uses a different icon than the `!` here, could you update it to our job icons?

2023-09-19 06:25 UTC, Christasmurf commented
While I'm here I should also suggest swapping the red cross on the syndiemed duffel to either white or green, we don't use red crosses for medical symbols as it's a war crime

2023-09-29 13:31 UTC, Henri215 commented
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/db05f116-ca4c-46a0-8ec3-327515b39ab5)
Any idea why the diff bot is showing everything inside the file?

2023-10-01 12:03 UTC, S34NW commented
> ![image](https://user-images.githubusercontent.com/77684085/271604447-db05f116-ca4c-46a0-8ec3-327515b39ab5.png) Any idea why the diff bot is showing everything inside the file?

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/8fd72dc7-317d-40ba-b4da-666f12b4f2e6)
these two files are top-level copies likely left in error

2023-10-01 12:04 UTC, S34NW requested changes
Please properly address where the files are and make sure the changes are working, things are in the wrong folders as pointed out above.

2023-10-12 14:17 UTC, S34NW requested changes
PR stale, please address reviews within a week or the PR will be closed

2023-10-16 15:18 UTC, Alecksohs commented
Will be updating, had been burntout when it was made.

2023-10-21 18:21 UTC, S34NW requested changes

2023-10-21 18:21 UTC, S34NW commented on back.dmi
You still add this file to the root of the codebase structure, please address this

2023-10-23 19:06 UTC, Alecksohs commented on back.dmi
For now, I'm going to be closing this as I am busy with other projects, I may reopen it at another date.

2023-10-23 19:06 UTC, Alecksohs commented
For now, I'm going to be closing this as I am busy with other projects, I may reopen it at another date.

2023-10-23 19:06 UTC, closed without merging