makes action buttons bindable to keybinds
ParadiseSS13/Paradise pull request #22390
Opened 2023-09-13 17:14 UTC by GDNgit

## What Does This PR Do
Makes action buttons able to be binded to keybinds
Pressing CTRL-SHIFT on a action button will open a menu up that allows for a keybind to any key you input. You cannot bind an action button to multiple keys (mostly because this would just cause confusion with binding a key to the same button twice). 

## Why It's Good For The Game
Not everyone has a great mouse, you should have the option to just hit a button if you want to use an ability. Accessibility is important and we've already pretty much moved away from focusing on legacy mode. 

## Testing
I clicked quite a few buttons as a ling
## Changelog
:cl:
tweak: Action buttons can now be binded to keybinds, CTRL+SHIFT click an action button to bind a key to it
/:cl:

2023-11-02 12:14 UTC, S34NW requested changes
Please fix merge conflicts for TM viability. This PR is very stale.

2023-11-04 15:09 UTC, GDNgit commented
> Please fix merge conflicts for TM viability. This PR is very stale.

resolved

2023-11-06 02:06 UTC, matttheficus commented
- Multi-binding leads to some odd behavior - for example, you can pop cling armor + armblade in one keypress instantly activating both abilities.
- There's no way to unbind the keys.
- There's no way to specify numpad vs number keys.
- If possible, it would be neat if you could see a little icon/character/whatever on the action button for what the keybind is set to.
- There should be a way to blacklist certain abilities from being keybound. Not sure which yet, if any, but certain admin-only items, dust implants, Evolution/Vamp Subtype Menu, etc probably should be able to be keybound.

2023-11-06 03:10 UTC, GDNgit commented
> * Multi-binding leads to some odd behavior - for example, you can pop cling armor + armblade in one keypress instantly activating both abilities.

You cannot, click delays are respected. It does let you retract it very quickly but that's all. 

> * There's no way to unbind the keys.

Added in latest commit, just don't enter anything and it'll clear your active bind

> * There's no way to specify numpad vs number keys.

Code limitation as of now, I'll see if I can figure a way around it
> * If possible, it would be neat if you could see a little icon/character/whatever on the action button for what the keybind is set to.

Binded key added to the mouseover of action buttons

> * There should be a way to blacklist certain abilities from being keybound. Not sure which yet, if any, but certain admin-only items, dust implants, Evolution/Vamp Subtype Menu, etc probably should be able to be keybound.

I think it's very *stupid* to bind these but I'm not sure if this is an actual issue. Anyways I guess this means suicide macros are real again.

2023-11-24 13:50 UTC, Lazyman310 commented
Did this PR also _remove_ the ability to right-click things to do things? I would be okay with both just to have to think about hotkeys a little less, but would rather right-clicking to do things stay

2023-11-24 14:25 UTC, GDNgit commented
> Did this PR also _remove_ the ability to right-click things to do things? I would be okay with both just to have to think about hotkeys a little less, but would rather right-clicking to do things stay

No, that was a different pr

2023-12-02 22:56 UTC, Gaxeer commented on code/_onclick/hud/action_button.dm
> +			to_chat(user, "<span class='info'>Your active keybinding on [src] has been cleared.</span>")
```suggestion
	else if(linked_keybind)
		clean_up_keybinds(user)
		to_chat(user, "<span class='info'>Your active keybinding on [src] has been cleared.</span>")
```

2023-12-02 23:01 UTC, Gaxeer commented on code/modules/input/keybindings_procs.dm
> +				active_keybindings[linked_bind.binded_to] += list(linked_bind)
Let's rewrite using guard clause, what do you think? 
```suggestion
	if(!mob) // Clients can join before world/new is setup, so we gotta mob check em
		return
		
	for(var/datum/action/action as anything in mob.actions)
		if(action.button?.linked_keybind?.binded_to)
			var/datum/keybinding/mob/trigger_action_button/linked_bind = action.button.linked_keybind
			active_keybindings[linked_bind.binded_to] += list(linked_bind)
```

2023-12-02 23:02 UTC, GDNgit commented on code/modules/input/keybindings_procs.dm
> +				active_keybindings[linked_bind.binded_to] += list(linked_bind)
```suggestion
	if(!mob) // Clients can join before world/new is setup, so we gotta mob check em
		return active_keybindings
	for(var/datum/action/action as anything in mob.actions)
		if(action.button?.linked_keybind?.binded_to)
			var/datum/keybinding/mob/trigger_action_button/linked_bind = action.button.linked_keybind
			active_keybindings[linked_bind.binded_to] += list(linked_bind)
```

2023-12-11 17:33 UTC, S34NW approved these changes
No reported issues in over a week on TM.

2023-12-11 18:56 UTC, merged