Remaps the Lavaland Outpost. Again.
ParadiseSS13/Paradise pull request #22391
Opened 2023-09-13 18:40 UTC by Sadhorizon

## What Does This PR Do
This PR is meant to fix some issues with previous remap, as well as add a bunch of new features, that are meant to make it FEEL like an actual OUTPOST, instead of an elevator.

I'll go more over specific changes under "Images of Changes"

## Why It's Good For The Game
Biggest issue of previous remap was shuttle touching the exit. Most of the outpost never saw the light of day.
By shuffling areas around, it will (hopefully) create more ways for people to go "Hey! Something is happening there! I might check it out! You know, halt gaming for a second and go talk with someone!"

Another big shuffle - medical being near the entrance. This just makes sense, you can stabalize injured faster.

And one huge addition - QM's office! Equipped with a personal locker (in case they go mining and want their items to be safe), a management console (demoting miners on the spot), a crew monitor (handheld one will be removed from QM's locker) and a guest pass console (for ghostroles, engineers, secoffs, etc.).

Another new important feature - working disposals. Not much to say here. Disposaled items burn/get chasmed.

And lastly - working firelocks, including in the windows. A smart miner can press a switch and buy a few seconds against a fauna attack.

For less impactful additions, I added a LOT of fluff stuff.

## Images of changes
![2023-09-13 20 28 01](https://github.com/ParadiseSS13/Paradise/assets/108196626/6e1b5ab3-40a2-4bd5-bd00-a3b47817f6be)
**TO-DO**

## Testing
Spawned in, messed around with:
* disposals
* APCs
* firelocks
* access
* lighting
* a lot of lesser stuff
Nothing seemed to break.

## Changelog
:cl:
tweak: Remapped the mining outpost.
/:cl:

2023-09-14 10:50 UTC, Aylong220 commented
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/4214e285-6f1e-4824-8473-bcc389022ed2)
Unconnected scrubbers pipe

2023-09-16 22:14 UTC, Sadhorizon commented
note for myself: 
wiki updates would be, adding mentions of second office to QM page, adding Brad to station pets page

2023-09-22 03:46 UTC, Oyu-De commented
1. Is this cable here connected?
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/fc96ecbc-4a04-48c9-b1eb-f294c429e151)

2. Why the S turn on the wiring? Just curious
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/57e5c19c-29fa-49ea-afd3-7b59a8dcf4d9)

2023-09-22 13:23 UTC, Sadhorizon commented
Heyo! Thanks for the review!
> 1. Is this cable here connected?
>        ![image](https://user-images.githubusercontent.com/66401072/269823302-fc96ecbc-4a04-48c9-b1eb-f294c429e151.png)
Wire is there, yup!
>     2. Why the S turn on the wiring? Just curious
>        ![image](https://user-images.githubusercontent.com/66401072/269823368-57e5c19c-29fa-49ea-afd3-7b59a8dcf4d9.jpeg)
Tbh, it was leftover from an older design. I will just move the wire up!

2023-10-02 19:32 UTC, S34NW reviewed
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/495f6194-dc0f-40d3-8dd6-54c687b6eba6)
You have some no lava helpers on walls

2023-10-15 12:48 UTC, Sadhorizon commented
NO NO NO NO NO

2023-10-17 20:59 UTC, S34NW requested changes
Changes requested on discord, see from this message onwards https://discord.com/channels/145533722026967040/876666051297935410/1163941823849439374

2023-10-18 21:15 UTC, Henri215 commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
> +	response_help  = "carefully pets"
```suggestion
	response_help = "carefully pets"
```

2023-10-21 18:31 UTC, S34NW requested changes

2023-10-21 18:31 UTC, S34NW commented on _maps/map_files/generic/Lavaland.dmm
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/44d7f120-1a66-4754-b239-bef84fe6dd95)

window spawners and buttons have ID vars, this needs them too

2023-10-21 18:40 UTC, S34NW commented on _maps/map_files/generic/Lavaland.dmm
PR is fine apart from this

2023-10-21 20:28 UTC, S34NW approved these changes

2023-10-21 20:30 UTC, merged