Adds the Central Command bikehorn
ParadiseSS13/Paradise pull request #22418
Opened 2023-09-15 09:46 UTC by BunnyGirlJen

## What Does This PR Do
Adds a new item called the Central Command bikehorn, which makes the infamous "bwoink" noise. You can now find it in maints as loot, aboard the Sol Trader shuttle, or as a member of the Honksquad

## Why It's Good For The Game
Why wouldn't a CC affiliated squad of clowns have their own special bike horn to signify their status? Everyone loves maints loot, and this is a harmless enough addition.

## Images of changes
![bhorn1](https://github.com/ParadiseSS13/Paradise/assets/108263534/bf4ed3ea-88ed-45b6-aab1-79031aebff1e)
![bhorn4](https://github.com/ParadiseSS13/Paradise/assets/108263534/1855d84c-8b46-4a98-9438-b0cd51a2d4ad)
![bhorn5](https://github.com/ParadiseSS13/Paradise/assets/108263534/9a247443-ddff-477f-a474-961cb8939750)

## Testing
Ran debug server, observed, summoned a honksquad, spawned in, looked inside bag. Boom.
Proceeded to abuse Skrell with the bikehorn.

## Changelog
:cl:
add: Added the CC bikehorn
/:cl:

2023-09-15 10:09 UTC, Henri215 commented on code/game/objects/effects/spawners/lootdrop.dm
> +				/obj/item/bikehorn/bwoinkhorn = 5
```suggestion
				/obj/item/bikehorn/bwoinkhorn = 5,
```

2023-09-15 10:09 UTC, Henri215 commented on code/game/objects/effects/spawners/lootdrop.dm
> +				/obj/item/bikehorn/bwoinkhorn = 100
```suggestion
				/obj/item/bikehorn/bwoinkhorn = 100,
```

2023-09-15 10:11 UTC, Henri215 requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/44a5e442-0683-4a8e-93ad-944b1377f1ba)

Ended up removing lots of sprites, probably because you didnt update your branch with the latest cchanges before opening this PR.

2023-09-15 10:24 UTC, BunnyGirlJen commented
Yeah, I noticed that, not sure how to fix it

2023-09-15 22:24 UTC, Christasmurf commented
> Yeah, I noticed that, not sure how to fix it

If you're using VScode

git fetch upstream
git merge upstream/master

It'll tell you the icon files are conflicting, just download the specific file from the codebase on the website here, then replace the file in your local folder.
Then import the new sprites again, and save. File should no longer be deconflicted, then push changes.

2023-09-15 23:33 UTC, BunnyGirlJen commented
I think that fixed it, but a lot of files ended up getting changed

2023-09-19 11:39 UTC, Henri215 commented on code/datums/outfits/outfit_admin.dm
> +		/obj/item/bikehorn/bwoinkhorn = 1,
I would leave the Honksquad with both versions of the bikehorn, extra firepower for them.

2023-09-19 11:39 UTC, Henri215 commented on code/game/objects/items/weapons/clown_items.dm
> +/obj/item/bikehorn/bwoinkhorn/proc/dread(mob/user)
Where is that proc being utilized?

2023-09-19 11:39 UTC, Henri215 commented on code/game/objects/effects/spawners/lootdrop.dm
> +				/obj/item/bikehorn/bwoinkhorn = 5,
I would personally make it a prize counter item instead of maints loot that doesnt even has the base bikehorn on it (just my opinion).

2023-09-20 22:49 UTC, Sirryan2002 commented on code/game/objects/items/weapons/clown_items.dm
> +/obj/item/bikehorn/bwoinkhorn/proc/dread(mob/user)
yeah this proc is unused atm?

2023-09-21 13:43 UTC, BunnyGirlJen commented
The merge conflicts are back, my suffering will never end

2023-09-27 09:49 UTC, SchrodingersWolf commented
Other than the sprite, isn't this extremely similar to how the fake Banhammer works?

2023-09-27 09:51 UTC, BunnyGirlJen commented
It is, yes, but in a format that makes a little more sense.

2023-10-06 14:21 UTC, Henri215 commented on code/game/objects/items/weapons/clown_items.dm
> +/obj/item/bikehorn/bwoinkhorn/proc/dread(mob/user)
(mob/user) is not being utilized for anything?

2023-10-12 14:47 UTC, S34NW requested changes
Please deconflict and address reviews, if you install hooks from `Paradise\tools\hooks\Install.bat` then merge master the icon conflicts should fix themselves :)

2023-10-21 18:22 UTC, S34NW commented
PR stale, please address reviews within a week or the PR will be closed

2023-10-28 13:41 UTC, closed without merging