Fixes anomalies not spawning right
ParadiseSS13/Paradise pull request #22474
Opened 2023-09-18 21:08 UTC by lewcc

## What Does This PR Do
Fixes a bug that prevents anomalies from properly spawning, and causing all sorts of trouble (like trying to delete themselves when they don't really exist).

## Why It's Good For The Game
Less bugs is good.

## Testing
Started some anomaly events, they functioned as intended.

## Changelog
:cl:

fix: Anomalies should now spawn correctly.
/:cl:

2023-09-18 21:15 UTC, Contrabang requested changes
these should probably be still logged as runtimes, just not crash it. I recommend stack_trace

2023-09-18 21:15 UTC, Contrabang commented on code/modules/events/anomaly_event.dm
> +				log_debug("No valid areas for anomaly found.")
```suggestion
				stack_trace("No valid areas for anomaly found.")
```

2023-09-18 21:15 UTC, Contrabang commented on code/modules/events/anomaly_event.dm
> +		log_debug("Anomaly: Unable to find a valid turf to spawn the anomaly. Last area tried: [impact_area] - [impact_area.type]")
```suggestion
		stack_trace("Anomaly: Unable to find a valid turf to spawn the anomaly. Last area tried: [impact_area] - [impact_area.type]")
```

2023-09-18 21:19 UTC, Henri215 commented
changelog has an extra line

2023-09-19 00:34 UTC, Henri215 approved these changes
Lewcs Good To Me

2023-09-19 02:34 UTC, SteelSlayer approved these changes

2023-09-19 02:34 UTC, merged