Fixes missing windoors in Delta security (And a few other places)
ParadiseSS13/Paradise pull request #22565
Opened 2023-09-23 20:29 UTC by Adrer

## What Does This PR Do
Fixes all the windoors that are missing in Deltastation's security department.
Fixes missing windoor at Deltastation's HOP's office.
Fixes: #22536

## Why It's Good For The Game
Missing windoors bad.

## Images of changes
Restores brig windoors to state before #22168 see mapdiffbot for changes.

## Changelog
:cl:
Fix: Added all the windoors that were missing in Deltastation's security department.
Fix: Missing windoor at Deltastation's HOP's office has been replaced.
/:cl:

2023-09-27 00:00 UTC, warriorstar-orion requested changes
Thanks for fixing this. I'm not sure what caused this, my only guess might be it having something to do with multiple windoors on the same tile, but UpdatePaths shouldn't care about that...

2023-09-28 23:03 UTC, SteelSlayer commented on _maps/map_files/Delta/delta.dmm
> +	autolink_sensors = list("burn_sensor"="Burn  Mix");
```suggestion
	autolink_sensors = list("burn_sensor"="Burn Mix");
```

2023-10-01 15:22 UTC, Contrabang requested changes
det's office is missing a windoor here
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/e039377b-9a8c-4da1-b554-43c31aaabbee)

2023-10-01 15:35 UTC, Contrabang approved these changes
LGTM

2023-10-01 15:37 UTC, S34NW approved these changes

2023-10-01 15:38 UTC, merged