Adds Riot Shield Bashing with Combat Knives
ParadiseSS13/Paradise pull request #22571
Opened 2023-09-24 03:58 UTC by Bjamcham

## What Does This PR Do
Adds combat knives alongside batons to the items that can bash riot shields for the text and sound effect. 

## Why It's Good For The Game
Adds a fun bit of noise and interaction if you have a riot shield and a combat knife.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/107899953/51484714-599c-45bc-870b-902acb639f4a)

## Testing
1. Spawned in a riot shield, baton, combat knife
2. Checked that both items could bash the riot shield properly

## Changelog
:cl:
add: You can now bash riot shields with a combat knife to make a sound.
/:cl:

2023-09-24 04:07 UTC, Contrabang requested changes
Can you make this use checking in a list? Either like this, or with typecaches

2023-09-24 04:07 UTC, Contrabang commented on code/game/objects/items/weapons/shields.dm
```suggestion
var/list/allowed_bashers = list(/obj/item/melee/baton, /obj/item/kitchen/knife/combat)
```

2023-09-24 04:07 UTC, Contrabang commented on code/game/objects/items/weapons/shields.dm
> +	if(istype(W, /obj/item/melee/baton) || istype(W, /obj/item/kitchen/knife/combat))
```suggestion
	if(is_type_in_list(W, allowed_bashers))
```

2023-09-24 13:26 UTC, Contrabang approved these changes
LGTM

2023-09-29 10:29 UTC, DGamerL approved these changes

2023-10-09 19:29 UTC, S34NW approved these changes

2023-10-09 19:30 UTC, merged