Adjusting Taj Veils + Masks
ParadiseSS13/Paradise pull request #22773
Opened 2023-10-08 11:55 UTC by K3Licia

## What Does This PR Do
Fixes inconsistencies with the west-facing sprite for the Tajara version of the gas masks and (hopefully) makes Tajara veils more suitable for their new head while also giving them a fresh coat of paint. I found them too long for the smaller face, which made them look awkward.

## Why It's Good For The Game
Better sprite good. (and resolves a mistake i made with an earlier PR)

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/135052649/b52e13a6-4942-415d-b0c5-8fca70589fdd)

## Testing
1. I replace the sprite.
2. It is there.

## Changelog
:cl:
imageadd: Fixed up Tajara gas masks and made veils better.
/:cl:

2023-10-09 20:55 UTC, Henri215 requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/58d204af-31e7-4a3a-8a28-15c1b50c0bf3)

The welding mask sprite is missing some pixels.

2023-10-10 00:36 UTC, K3Licia commented
> ![image](https://user-images.githubusercontent.com/77684085/273695481-58d204af-31e7-4a3a-8a28-15c1b50c0bf3.png)
> 
> The welding mask sprite is missing some pixels.

should be good now!

2023-10-10 14:36 UTC, Henri215 approved these changes
Lewcs Good To Me now

2023-10-12 16:22 UTC, S34NW approved these changes

2023-10-12 16:22 UTC, merged