Ports Condiment Sprites from TG. Ports Mayonnaise, Peanut Butter, Olives, and Olive Oil from TG
ParadiseSS13/Paradise pull request #22796
Opened 2023-10-09 09:11 UTC by Mitchs98

## What Does This PR Do
Freshens up our old condiment sprites from TG, as well as the serving tray(it was also in the same PR so why not).

https://github.com/tgstation/tgstation/pull/74890 - Salt and Pepper Shaker by CoiledLamb.
https://github.com/tgstation/tgstation/pull/75715 - Condiments by MTandi.

Mayonnaise is created with 5 egg, 1 salt, and 5 Olive Oil resulting in 10 Mayonnaise.

Olive Oil is created with 5 Olive Paste and 5 Water resulting in 10 Olive Oil.

Olive Paste is made by grinding up Olives.

Peanut Butter is created by grinding up Peanuts.

## Why It's Good For The Game
Our current condiment sprites are, quite honestly, **very bad**. This PR aims to improve that while also adding a few new condiments that will be used in future recipes I intend on porting from TG. Essentially lays the groundwork and adds a new condiment. Also makes our serving tray look more like a serving tray and less like a baking tray.

## Images of changes
![dreammaker_ZdlDtEqN3d](https://github.com/ParadiseSS13/Paradise/assets/12178527/02aeeb43-049a-4f10-a6b7-1c4a47c868a2)

## Testing
1. Spawned in each and every condiment bottle.
2. Filled condiment bottles with their respective condiments.
3. Grew an Olive tree, cried at the offsetting, and properly offset it by the needed amount.
4. Harvested Olives.
5. Ground Olives and Peanut Butter.
6. Mixed Olive Oil.
7. Mixed Mayonnaise.
8. Ate the Mayonnaise.
9. Drank the excess Olive Oil.

## Changelog
:cl:
add: Added Mayonnaise, created by mixing 5 egg, 1 salt, and 5 Olive Oil resulting in 10 units of Mayonnaise.
add: Adds Olive Oil and Olive Paste. Olive Oil is made from 5 Olive Paste and 5 Water, resulting in 10 units. Olive Paste is acquired by grinding olives.
add: Peanut Butter, Acquired by grinding Peanuts.
add: Olives, growable in botany. Mutates into nothing, provides Olive Paste when ground.
imageadd: Most Condiments have been given new sprites ported from TG.
imageadd: Ported updated Tray sprite from TG.
/:cl:

2023-10-09 10:19 UTC, SynthTwo commented
YES LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2023-10-09 13:32 UTC, Henri215 commented on code/modules/food_and_drinks/food/condiment.dm
> +	"cornoil" = list("cornoil", "corn oil bottle", "A delicious oil used in cooking. Made from corn"),
```suggestion
	"cornoil" = list("cornoil", "corn oil bottle", "A delicious oil used in cooking. Made from corn."),
```
While we are here...

2023-10-09 13:32 UTC, Henri215 commented on code/modules/food_and_drinks/food/condiment.dm
> +	"cornoil" = list("condi_cornoil", "Corn Oil", "A delicious oil used in cooking. Made from corn"),
```suggestion
	"soysauce" = list("condi_soysauce", "Soy Sauce", "A salty soy-based flavoring."),
	"frostoil" = list("condi_frostoil", "Coldsauce", "Leaves the tongue numb in it's passage."),
	"sodiumchloride" = list("condi_salt", "Salt Shaker", "Salt. From space oceans, presumably."),
	"blackpepper" = list("condi_pepper", "Pepper Mill", "Often used to flavor food or make people sneeze."),
	"cornoil" = list("condi_cornoil", "Corn Oil", "A delicious oil used in cooking. Made from corn."),
```

2023-10-09 13:32 UTC, Henri215 commented on code/modules/hydroponics/grown/olive.dm
> +	desc = "These seeds grow into olive trees"
```suggestion
	desc = "These seeds grow into olive trees."
```

2023-10-09 16:49 UTC, Mitchs98 commented
Appended periods to stuff Henri mentioned, also added spawnable bottles of the rest of the condiments because why not? Also finished pathing the honey and etc. on the condiments list because I forgor to do that surprised it compiled properly the first time and worked fine.

> It never dawned on me till now...but we dont have mustard

I honestly don't know *any* server that has mustard. I know TG doesn't, I was going to port it from there but it sadly doesn't exist.

2023-10-09 18:24 UTC, DT2399 commented
YES!!

2023-10-09 18:29 UTC, Mitchs98 commented
Ported TGs updated cleaver, looks much shinier and nicer than ours. Also removed the bloody cleaver that I didn't see used *anywhere*. PR Desc updated shortly.

2023-10-09 18:50 UTC, Migratingcocofruit commented
>A small cylindrical salty fruit
 
I know it's a port but considering this description is would make sense for it to have a small amount of salt as a reagent.

2023-10-09 21:25 UTC, Probablyjay19 commented
Can I use mayonnaise as an instrument?

2023-10-09 21:33 UTC, Henri215 requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/ce57daa2-9c84-4546-abe4-05556ebb7ef1)
Remove that duplicate sprite

2023-10-09 21:50 UTC, Mitchs98 commented
> ![image](https://user-images.githubusercontent.com/77684085/273701809-ce57daa2-9c84-4546-abe4-05556ebb7ef1.png) Remove that duplicate sprite

I did. THat's just a reference picture :p

2023-10-10 01:56 UTC, Mitchs98 commented
> Can I use mayonnaise as an instrument?

Perhaps soon.

2023-10-10 02:06 UTC, Mitchs98 commented
> > A small cylindrical salty fruit
> 
> I know it's a port but considering this description is would make sense for it to have a small amount of salt as a reagent.

Missed this earlier. I'll consider doing that, wanted to try and avoid grinder bloat when trying to make oliveoil...but at the same time it would streamline making oliveoil a bit.

I think I'll push an update for this later tonight.

2023-10-10 20:36 UTC, Migratingcocofruit commented
> > > A small cylindrical salty fruit
> > 
> > 
> > I know it's a port but considering this description is would make sense for it to have a small amount of salt as a reagent.
> 
> Missed this earlier. I'll consider doing that, wanted to try and avoid grinder bloat when trying to make oliveoil...but at the same time it would streamline making oliveoil a bit.
> 
> I think I'll push an update for this later tonight.
> 
> Olives will now have a bit of salt in them.

The grinder has both grind and juice options. IIRC Grind gives the reagents and juice usually gives a reagent that is dependent on the plant. So you can make it give the mahsed olives on juice and the reagents on grind

2023-10-10 20:46 UTC, Mitchs98 commented
> > > > A small cylindrical salty fruit
> > > 
> > > 
> > > I know it's a port but considering this description is would make sense for it to have a small amount of salt as a reagent.
> > 
> > 
> > Missed this earlier. I'll consider doing that, wanted to try and avoid grinder bloat when trying to make oliveoil...but at the same time it would streamline making oliveoil a bit.
> > I think I'll push an update for this later tonight.
> > Olives will now have a bit of salt in them.
> 
> The grinder has both grind and juice options. IIRC Grind gives the reagents and juice usually gives a reagent that is dependent on the plant. So you can make it give the mahsed olives on juice and the reagents on grind

A juicing setting typically wouldn't produce paste, it would mulchify the olive. Going to keep it as is, really.

2023-10-12 16:53 UTC, S34NW approved these changes

2023-10-12 16:53 UTC, merged