Tweak: Removes position randomization for some things
ParadiseSS13/Paradise pull request #22820
Opened 2023-10-10 17:21 UTC by Aylong220

## What Does This PR Do
Removing pixel_x/y = rand() from some things

## Why It's Good For The Game
Most of the things will not "hang" from the table, unless the mapper does not do so, in general gives more space to mappers, because now you can beautifully arrange the items on the tables and they will not turn into a mess

## Images of changes
Before
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/d3a73e8e-8ea2-4435-9a1d-afb0a5b98f88)

After
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/2ee13e78-51c8-439b-b96a-49f4a605138c)

## Testing
Yes.

## Changelog
:cl: Aylong
tweak: Removed randomization of some things at server startup, you probably won't even notice it.
/:cl:

2023-10-10 17:32 UTC, Contrabang commented
While I think this is good for mapping, it means stuff that comes out of things like the autolathe, protolathe, chem masters, and kitchen machines will all be exactly on the same exact spot. 

I think this PR should include randomization for those machines when those things are created from them.

2023-10-10 19:22 UTC, Aylong220 commented
> While I think this is good for mapping, it means stuff that comes out of things like the autolathe, protolathe, chem masters, and kitchen machines will all be exactly on the same exact spot.
> 
> I think this PR should include randomization for those machines when those things are created from them.

I hope I understood you correctly, I made it so that all (almost) things created/issued in autolat/protolat/vendor or cooked, fall out with a random position. Hope the code doesn't make you cry :D

2023-10-10 20:00 UTC, Contrabang commented on code/modules/research/rdconsole.dm
> +					new_item.pixel_y = rand(-5.0, 5)
Personally, I think it would be fine for all of the items to print out with a random position, but thats up to you

2023-10-10 20:00 UTC, Contrabang requested changes

2023-10-10 20:00 UTC, Contrabang commented on code/modules/research/rdconsole.dm
> +					new_item.pixel_y = rand(-5.0, 5)
```suggestion
					new_item.pixel_x = rand(-5, 5)
					new_item.pixel_y = rand(-5, 5)
```

2023-10-10 20:25 UTC, Aylong220 commented on code/modules/research/rdconsole.dm
> +					new_item.pixel_y = rand(-5.0, 5)
Uh, forgot that

2023-10-10 22:35 UTC, Contrabang approved these changes
LGTM

2023-10-13 13:25 UTC, S34NW approved these changes

2023-10-13 13:26 UTC, merged