IPCs can die from low power
ParadiseSS13/Paradise pull request #22846
Opened 2023-10-11 22:02 UTC by BiancaWilkson

## What Does This PR Do

IPCs now begin taking brain damage when their power is low enough. Most of the code was taken from #17993 
## Why It's Good For The Game

It adds consistency to the game, and means IPCs need to actually stay charged like how humans need to actually eat. It will kill you about as quickly as starvation does, so you get plenty of time to fix your power issues.

## Testing

I locked binary bot in a box and he died, then I made sure human nutrition didn't break too
## Changelog
:cl:
tweak: IPCs can die from starvation
/:cl:

2023-10-11 22:06 UTC, Henri215 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +			to_chat(H, "<span class='warning'> Error 74: Positronic brain receiving insufficient power.</span>")
```suggestion
			to_chat(H, "<span class='warning'>Error 74: Positronic brain receiving insufficient power.</span>")
```

2023-10-13 21:53 UTC, Mitchs98 commented
I'm really not sure if brain damage is the best way to handle this. Brute damage or stamina may be a better way to go about it to simulate the chassis locking up? Just makes no sense to me that the positronic works fine outside of the chassis yet would somehow need power while in the chassis.

Though I do agree consistency for needing to "eat" is good.

2023-10-13 23:06 UTC, BiancaWilkson commented
> I'm really not sure if brain damage is the best way to handle this. Brute damage or stamina may be a better way to go about it to simulate the chassis locking up? Just makes no sense to me that the positronic works fine outside of the chassis yet would somehow need power while in the chassis.

I'm glad you made this comment because in hindsight it feels obvious to make the microbattery the organ that takes damage during a power failure.

2023-10-13 23:30 UTC, Mitchs98 commented
> > I'm really not sure if brain damage is the best way to handle this. Brute damage or stamina may be a better way to go about it to simulate the chassis locking up? Just makes no sense to me that the positronic works fine outside of the chassis yet would somehow need power while in the chassis.
> 
> I'm glad you made this comment because in hindsight it feels obvious to make the microbattery the organ that takes damage during a power failure.

Didn't think about that myself, but that does make much more sense with the chassis putting strain on the battery to try and forcibly power itself or what not!

2023-10-14 16:33 UTC, Contrabang commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	if(H.nutrition < NUTRITION_LEVEL_HYPOGLYCEMIA)
```suggestion
	if(H.nutrition >= NUTRITION_LEVEL_HYPOGLYCEMIA)
		return
```

2023-10-14 16:33 UTC, Contrabang commented on code/modules/mob/living/carbon/human/species/machine.dm
> +			H.Slowed(rand(15 SECONDS, 32 SECONDS))
IMO, these should be else ifs. These are going to be firing off every 2 seconds, so theres a non-zero chance that multiple of these get hit at the same time
```suggestion
		if(prob(6))
			H.adjustBrainLoss(4)
			to_chat(H, "<span class='warning'>Error 74: Positronic brain receiving insufficient power.</span>")
		else if(prob(4))
			H.Weaken(6 SECONDS)
			H.Stuttering(20 SECONDS)
			to_chat(H, "<span class='warning'>Power critical, redirecting all power to positronic brain.</span>")
			H.emote("collapse")
			H.adjustBrainLoss(2)
		else if(prob(4))
			to_chat(H, "<span class='warning'>Power critical, redirecting power from servos.</span>")
			H.Slowed(rand(15 SECONDS, 32 SECONDS))
```

2023-10-15 13:42 UTC, Contrabang requested changes
We really shouldnt be mentioning the github really in the code

2023-10-15 13:42 UTC, Contrabang commented on code/modules/mob/living/carbon/human/species/machine.dm
> +/datum/species/machine/handle_life(mob/living/carbon/human/H) //Mostly KittyNoodle's code from PR #17993, handles IPC starvation
```suggestion
/datum/species/machine/handle_life(mob/living/carbon/human/H) // Handles IPC starvation
```

2023-10-15 21:23 UTC, Contrabang commented on code/modules/mob/living/carbon/human/species/machine.dm
> +		H.Slowed(rand(15 SECONDS, 32 SECONDS))
Arent you already slowed if you're starving, even as an IPC?

2023-10-15 21:23 UTC, Contrabang commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	var/obj/item/organ/internal/cell/microbattery = H.get_organ_slot("heart")
Also, can you reword your PR? The microbattery isn't the brain organ. This is technically heart damage

2023-10-22 16:26 UTC, lewcc approved these changes

2023-10-22 16:52 UTC, merged