fixes a runtime with camera signals
ParadiseSS13/Paradise pull request #22848
Opened 2023-10-11 22:52 UTC by GDNgit

## What Does This PR Do
fixes a runtime with camera signals

## Why It's Good For The Game
borgs also got cameras in em, and we don't mind these overriding

## Testing
Compiled and ran

## Changelog
NPFC

2023-10-11 22:57 UTC, Contrabang requested changes
This should really only be left for a final option. Are you sure theres nothing you could do to check before the signal is registered?

2023-10-11 23:03 UTC, GDNgit commented
> This should really only be left for a final option. Are you sure theres nothing you could do to check before the signal is registered? 

A check for this would be both bloated and pretty much unneeded, we don't care if these signals are getting overriden

>Keep in mind, cameras are already pretty intensive, and we dont need 4 more register signal overheads on them unless its completely necessary.

No they aren't, only major cost of camerachunks are related to GCing

2023-10-11 23:26 UTC, Contrabang approved these changes
I meant in general, but LGTM if theres nothing better we can do.

2023-10-13 13:28 UTC, S34NW approved these changes

2023-10-13 13:28 UTC, merged