Adding unloading of botanical discs from boxes
ParadiseSS13/Paradise pull request #22847
Opened 2023-10-11 22:30 UTC by Nlaysi

## What Does This PR Do
'disk compartmentalizer' does not accept unloading discs from boxes, it adds the ability to unload discs from boxes in addition to bags

## Why It's Good For The Game
Helps botanists unload disks from 'plant data disks box' into 'disk compartmentalizer'

## Testing
Checked the unloading of boxes and bags with various items

2023-10-11 23:25 UTC, Henri215 commented
Thanks for opening this here

2023-10-13 15:33 UTC, Henri215 approved these changes
Lewcs Good To Me

2023-10-13 16:17 UTC, Contrabang requested changes
Could you add a changelog to your PR please?

2023-10-13 20:09 UTC, Nlaysi commented
> Could you add a changelog to your PR please?

Fixed it. Is the changelog correct?

2023-10-14 02:50 UTC, Contrabang commented
> > Could you add a changelog to your PR please?
> 
> Fixed it. Is the changelog correct?

I'd say it a tweak, over something being added, but its good enough for me. If you have the chance, I'd appreciate the change. Looks good to me though!

2023-10-14 02:50 UTC, Contrabang approved these changes
LGTM

2023-10-14 18:43 UTC, farie82 approved these changes

2023-10-14 18:45 UTC, merged