Adds HOP beret
ParadiseSS13/Paradise pull request #22919
Opened 2023-10-16 14:35 UTC by Danchi299

## What Does This PR Do
Adds head of personnel's beret to HOP garment bag. 
Sprites included.

## Why It's Good For The Game
Most other heads have a beret that comes with their shawl, I though it would be nice if HOP also had one.
I am aware of https://github.com/ParadiseSS13/Paradise/pull/22350

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/e6093b8f-d519-4fb7-b5dd-f72813b0737a)
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/82e612e9-1928-45f8-a74d-73b45f4c6fcc)
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/f0094ce0-f1b4-4a21-8102-18485d81ed51)
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/8da9dbcd-a4af-4566-9e56-c8112215da31)
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/8a0cbd05-e611-447e-afaa-2e093b47b41c)

## Testing
Joined as HOP, dressed up, spun around, compared to rest of outfit. 

## Changelog
:cl:
add: Added HOP beret
imageadd: Added HOP beret sprite
/:cl:

2023-10-16 14:42 UTC, DGamerL commented
Mirroring from discord:
- The sprite having a red outline looks bad
- With Christa's PR already adding a HOP beret, this seems like needless conflicting with that PR

2023-10-16 15:26 UTC, Danchi299 commented
I'll reconsider this if https://github.com/ParadiseSS13/Paradise/pull/22350 fails

2023-10-16 17:57 UTC, Danchi299 commented
adjusted obj sprite to have better outlines
![HOP - Upscale](https://github.com/ParadiseSS13/Paradise/assets/20885860/1e55fe53-946a-459e-9fcc-008eb75b360b)

2023-10-16 19:52 UTC, Danchi299 commented
now the only question is, should the shiny part be silver per ID and Rank or golden per other parts of outfit?

2023-10-29 11:50 UTC, Henri215 commented on code/modules/clothing/head/job_hats.dm
> +	desc = "For doing paperwork with style."
```suggestion
/obj/item/clothing/head/hopcap/beret
	name = "head of personnel's beret"
	desc = "For doing paperwork with style."
	icon_state = "hop_beret"
```
Style preference of having desc after the name.

2023-10-30 12:40 UTC, Henri215 requested changes
You need to make versions for Drask and Vox species.

2023-11-03 12:41 UTC, Danchi299 commented
right, how do I de-conflict the Image files

2023-11-03 13:25 UTC, Danchi299 commented
ok, what have I done this time

2023-11-03 13:45 UTC, S34NW commented
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/78672d02-35a7-4e60-9ea5-bbd3b8abffa8)
You didn't actually do a proper merge master, you did a "fake" one

2023-11-03 15:15 UTC, Henri215 commented
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/40424581-8d93-4ec6-94dd-f9f505d724e7)
No need for this one the changelog, when you are adding a new item its already expected it would have a sprite for him

2023-11-03 15:36 UTC, Henri215 requested changes
Species sprites have no issues, nice job.

2023-11-03 15:36 UTC, Henri215 commented on code/modules/client/preference/loadout/loadout_hat.dm
> +	display_name = "Beret, head of personnel's"
```suggestion
	display_name = "Beret, head of personnel"
```

2023-11-03 15:36 UTC, Henri215 commented on code/modules/clothing/head/job_hats.dm
> +
```suggestion
	icon_state = "hop_beret"
	sprite_sheets = list(
		"Vox" = 'icons/mob/clothing/species/vox/head.dmi',
		"Drask" = 'icons/mob/clothing/species/drask/head.dmi',
		)

```
Needs these for the species variations

2023-11-05 17:17 UTC, Henri215 approved these changes

2023-11-07 20:30 UTC, Burzah approved these changes

2023-11-08 08:51 UTC, S34NW approved these changes

2023-11-08 08:51 UTC, merged