Adds a confirmation prompt to all OOC events in the secrets panel.
ParadiseSS13/Paradise pull request #22959
Opened 2023-10-19 10:11 UTC by Adrer

## What Does This PR Do
Adds a confirmation prompt to all OOC events in the secrets panel.

## Why It's Good For The Game
One misclick shouldn't cause an entire round to be done for.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/19361017/68e0bd62-fd55-48ca-aed4-abc856e3924a)

## Testing
Go to the secrets panel
Try to turn all sprites into revolvers
Get a confirmation prompt

## Changelog
:cl:
tweak: Added a confirmation prompt to all OOC events in the secrets panel.
/:cl:

2023-10-19 10:25 UTC, Henri215 commented on code/modules/admin/topic.dm
> +		if(alert("Are you sure you want to run this secret?","Confirmation","Yes","Cancel") != "Yes") return
```suggestion
		if(alert("Are you sure you want to run this secret?", "Confirmation", "Yes", "Cancel") != "Yes")
			return
```

2023-11-01 12:52 UTC, DGamerL requested changes
Just this small thing, and see warriorstar's review!

2023-11-01 12:52 UTC, DGamerL commented on code/modules/admin/topic.dm
>  		if(!check_rights(R_SERVER|R_EVENT))	return
I know you didn't touch this, but would you mind making this compliant with our standards?

2023-11-03 20:02 UTC, S34NW reviewed
Outstanding changes with no commits in 2 weeks, please resolve

2023-11-06 08:32 UTC, Adrer commented on code/modules/admin/topic.dm
> +		if(alert("Are you sure you want to run this secret?", "Confirmation", "Yes", "Cancel") != "Yes")
Has been addressed.

2023-11-06 16:23 UTC, Contrabang commented on code/modules/admin/topic.dm
> +					return
Can you make these all into one-liners and turn them into `!= "Yes"` so if they close it without clicking no, it wont go through?
```suggestion
				if(alert(usr, "Are you sure you want to do this?", "Confirmation", "Yes", "No") != "Yes"
					return
```

2023-11-06 19:27 UTC, DGamerL approved these changes
Contra's review addressed, LGTM

2023-11-07 21:08 UTC, Burzah approved these changes

2023-11-14 13:02 UTC, S34NW approved these changes

2023-11-14 13:02 UTC, merged