Restructure Chemical ChemMaster
ParadiseSS13/Paradise pull request #22992
Opened 2023-10-22 04:22 UTC by Arthri

## What Does This PR Do
Rewrote the Container Customization to use buttons instead of modals. Rewrote the production section to separate each production type(pills, patches, bottles) into their own tabs with their own settings which is saved across sessions. Condiment ChemMaster is not changed by this PR

- Added `bottleamount` and repurposed `pillamount` and `patchamount` to track the amount configured through the UI
- Added `production_mode` variable to track currently selected production tab
- Added new `ChemMasterNameInput` component to ChemMaster.js(it is not exported) for pill/patch/bottle name inputs. The component automatically gets the maximum length from `maxnamelength` sent in `ui_data`. Middle clicking on the component will replace the textbox text with the placeholder
- Added new `ui_act` paths for setting production mode, setting bottle/pill style, setting pill/patch/bottle name, setting pill/patch/bottle amount, and creating pills/patches/bottles
- Added new data to `ui_data`
- Added new property `iconStyle` button to allow CSS modification of the `Icon` element
- Added other defines such as `CHEMMASTER_MAX_PILLS`(for patches and bottles too) and `CHEMMASTER_PRODUCTION_MODE_PILLS`(the production mode corresponding to the pills tab)
- Changed Beaker and Buffer's flex-grow from 0 to 1. They can now grow vertically if there is extra space
- Changed Beaker and Buffer's min-height from undefined to 100px to fix height stress
- Changed default interface height from 500 to 600 to accommodate new height requirements
- Changed Production section's flex-grow from 1 to undefined and removed any explicit height set
- Lifted `pill_bottle_wrappers` and `bottle_styles` initialization to the top-level
- Removed `#define MAX_MULTI_AMOUNT 20` and replaced with `CHEMMASTER_MAX_PILLS`(20), `CHEMMASTER_MAX_PATCHES`(20), and `CHEMMASTER_MAX_BOTTLES`(5)
- Removed hardcoded `bottleStyles` variable in ChemMaster.js
- Removed modal code which is rendered obsolete by new `ui_data` and `ui_act` paths

There's a bug where creating 20 pills from 1u should result in 20 0.05u pills but instead results in 19 pills with no contents in them because the minimum reagent amount is 0.09 and the last pill is lost to floating-point math. The bug is already present with the old UI and is not addressed by this PR.

## Why It's Good For The Game
These changes provide a smoother experience for using the ChemMaster. The Container Customization now has color complementing the buttons and the Production tabs now save settings across sessions and allows mass production in a less error-prone manner.

## Images of changes
Note: the Container Customization was not finished at the time of recording

https://github.com/ParadiseSS13/Paradise/assets/41360489/f2b27d7b-e1d3-48a9-8edc-87936434f3c1

| Current | New (Pills) | New (Patches) | New (Bottles) |
|:-:|:-:|:-:|:-:|
| ![current](https://github.com/ParadiseSS13/Paradise/assets/41360489/9dffcb93-585d-41b5-bc1a-0ead14c879e5) | ![pills](https://github.com/ParadiseSS13/Paradise/assets/41360489/61b4000c-1910-46b5-852b-f61b56b1a8aa) | ![patches](https://github.com/ParadiseSS13/Paradise/assets/41360489/5f87e18a-b730-4347-aa84-c13b23090a53) | ![bottles](https://github.com/ParadiseSS13/Paradise/assets/41360489/f1bf69e4-8648-4ca1-a9fe-2cc36e9df762) |

### Height Stress Test
| Current | Proposed |
|:-:|:-:|
| <video src="https://github.com/ParadiseSS13/Paradise/assets/41360489/669f59cf-060d-4ba4-8fe8-62960dfda31d"></video> | <video src="https://github.com/ParadiseSS13/Paradise/assets/41360489/dbf699d7-5bb3-4364-96cb-ba56ea9253f8"></video> |

### Container Customization
| Current | Proposed |
|:-:|:-:|
| <video src="https://github.com/ParadiseSS13/Paradise/assets/41360489/7cf59b51-1355-459f-98b1-c02b66356ce9"></video> | <video src="https://github.com/ParadiseSS13/Paradise/assets/41360489/cebf9f6d-9e99-4c81-8de6-0a94d7511032"></video> |

## Testing
- Stress tested the width and height by loading a beaker filled with different reagents and resizing the window
- Created pills, patches, and bottles under different settings
- Closing and reopening the interface to see if the changes saved

## Changelog
:cl: cdui
tweak: ChemMaster Production section's production modes split into tabs
tweak: ChemMaster Container Customization section uses colored buttons instead of modal select box
/:cl:

2023-10-22 09:54 UTC, Henri215 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	)
```suggestion
		COLOR_MAROON = "Brown"
	)
```

2023-10-22 09:54 UTC, Henri215 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if (new_mode == null)
```suggestion
			if(new_mode == null)
```
Remove that space on the rest of the file please

2023-10-23 07:03 UTC, Danchi299 commented
this combined with https://github.com/ParadiseSS13/Paradise/pull/22915 fully counterweights https://github.com/ParadiseSS13/Paradise/pull/22594 and doubles the overall speed of chemical production
Thanks Andrew

2023-10-26 10:03 UTC, CinnamonSnowball commented
I'd propose to make the Create button smaller, it has no business being te entire width of the window and if anything blends in with the other fields, took me a second to actually realize it's there

Also, since the production tab now contains persistent data, it should probably always show all the buttons, just disable and gray out the Create button

2023-10-28 00:28 UTC, CinnamonSnowball commented
"normal width, indented" looks pretty good to me, tbh

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_value == null)
```suggestion
			if(isnull(new_value))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_mode == null)
```suggestion
			if(isnull(new_mode))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_value == null)
```suggestion
			if(isnull(new_value))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			var/new_value = params["newValue"]
make sure this is sanitized please!

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_value == null)
```suggestion
			if(isnull(new_value))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			var/new_value = params["newValue"]
please make sure user text input is sanitized!

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			bottlesprite = clamp(new_value, 1, bottle_styles.len)
```suggestion
			bottlesprite = clamp(new_value, 1, length(bottle_styles))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_value == null)
```suggestion
			if(isnull(new_value))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(new_value == null)
```suggestion
			if(isnull(new_value))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			var/new_value = params["newValue"]
needs to be sanitized

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(length(pillname) <= 0 || pillname == null)
```suggestion
			if(length(pillname) <= 0 || isnull(pillname))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			while(count--)
```suggestion
			for(var/i in 1 to count)
```
this is the preferred syntax for loops

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			while(count--)
```suggestion
			for(var/i in 1 to count)
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(length(name) <= 0 || name == null)
```suggestion
			if(length(name) <= 0 || isnull(name))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +					to_chat(usr, "<span class='notice'>Not enough reagents to create these pills!</span>")
make this use `ui.user` instead of `usr`

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +					to_chat(usr, "<span class='notice'>Not enough reagents to create these patches!</span>")
same here with `ui.user`

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +					to_chat(usr, "<span class='notice'>Not enough reagents to create these bottles!</span>")
and here

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			while(count--)
```suggestion
			for(var/i in 1 to count)
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(length(name) <= 0 || name == null)
```suggestion
			if(length(name) <= 0 || isnull(name))
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	for(var/i = 1 to MAX_PILL_SPRITE)
```suggestion
	for(var/i in 1 to MAX_PILL_SPRITE)
```

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	var/pill_styles[0]
```suggestion
	var/pill_styles = list()
```
preferred syntax for instantiating an empty list

2023-11-03 19:36 UTC, Sirryan2002 commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	var/bottle_styles_with_sprite[0]
```suggestion
	var/bottle_styles_with_sprite = list()
```

2023-11-03 19:36 UTC, Sirryan2002 commented on tgui/packages/tgui/interfaces/ChemMaster.js
> +          i += 1;
you shouldn't increment i here, `map` increments `i` as the index of its loop automatically

2023-11-20 15:27 UTC, Contrabang requested changes

2023-11-20 15:27 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			var/name = pillname
name is a reserved atom var, you should use a different variable name here

2023-11-20 15:27 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	var/bottlename = ""
There has to be a way to condense all these variables down to 1, right?

2023-11-20 15:27 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	var/production_mode = 1
Can you use defines for this var?

2023-11-20 15:27 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	data["maxnamelength"] = MAX_CUSTOM_NAME_LEN
Can you change the data that uses defines to be a part of a ui_static_data call instead? Along with all the for loops with data that never changes

2023-12-10 17:19 UTC, S34NW approved these changes

2023-12-10 20:04 UTC, Burzah approved these changes

2023-12-11 12:41 UTC, merged