Moves the `can_leave_fibers` var to `/obj/item` instead of being on `/atom`
ParadiseSS13/Paradise pull request #23005
Opened 2023-10-23 20:00 UTC by DGamerL

## What Does This PR Do
Moves a variable to a higher hierarchy, making it not be put on every atom.

## Why It's Good For The Game
Makes VV a bit easier to read, while still working correctly

## Testing
Tried to leave fibers on a door, checked that it still worked with a forensic scanner.

## Changelog
NPFC

2023-10-23 20:03 UTC, DGamerL commented on code/game/atoms.dm
> -	//Detective Work, used for allowing a given atom to leave its fibers on stuff. Allowed by default
Technically you can make items in hand also leave fibers, but this was never implemented. This has been here for 3+ years and never used anywhere else.

2023-10-23 20:16 UTC, GDNgit requested changes

2023-10-23 20:16 UTC, GDNgit commented on code/game/objects/items.dm
> +	var/can_leave_fibers = TRUE
This could be moved farther up to the /obj/item/clothing level or all the way up to the gloves level

2023-10-25 22:19 UTC, Sirryan2002 approved these changes

2023-10-25 22:19 UTC, Sirryan2002 commented on code/modules/clothing/clothing.dm
> +	//Detective Work, used for allowing a given atom to leave its fibers on stuff. Allowed by default
```suggestion
	/// Detective Work, used for allowing a given atom to leave its fibers on stuff. Allowed by default
```

2023-10-26 09:41 UTC, S34NW approved these changes

2023-10-26 09:41 UTC, merged