Fix cyberiad research delivery windoor.
ParadiseSS13/Paradise pull request #23044
Opened 2023-10-26 22:56 UTC by Venuska1117

## What Does This PR Do
Fix research delivery windoor on cyberiad, it was rotated in wrong direction

## Why It's Good For The Game
oversight bad, allow anyone to access research trough delivery.

## Images of changes
this is bad, send help.
![image](https://github.com/ParadiseSS13/Paradise/assets/89580971/c1674bcb-da96-4ea2-955a-4641f41995e4)

## Testing
Rotated, VSC compiled, done.

## Changelog
:cl: Venuska1117
tweak: Rotate Cyberiad research delivery windoor to correct position.
/:cl:

2023-10-27 23:24 UTC, Henri215 approved these changes
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/bb6693fe-eddb-43d4-9736-81df740d6aa7)

LGTM, dont be lazy and add an image next time.

2023-10-28 21:54 UTC, Venuska1117 commented
> ![image](https://user-images.githubusercontent.com/77684085/278777139-bb6693fe-eddb-43d4-9736-81df740d6aa7.png)
> 
> LGTM, dont be lazy and add an image next time.

but... but! this is bad.... :c

2023-11-20 21:04 UTC, S34NW requested changes
the windoor was the correct way already. Departmental windoors face the outer side on cyberiad as a rule of thumb, that was the intention and how they were implemented in crawling PR.
See service: 
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/e7ddf5d6-797e-40c1-ac41-e1d428b2f69a)

2023-11-21 13:05 UTC, S34NW approved these changes

2023-11-21 13:05 UTC, merged