Buffs His Grace
ParadiseSS13/Paradise pull request #23040
Opened 2023-10-26 18:48 UTC by DGamerL

## What Does This PR Do

- Lowers the amount of bodies required for ascension from 25 to 20. This makes the final 5 bodies give you about 30 to 20 seconds of grace time, instead of the 15 to 20 seconds.
- Adds a counter on the status effect hover (That many probably didn't know existed) of how far you are with your ascension.
- Ascension now sets your bloodthirst to 140, greatly buffing the amount you regenerate.
- Buffs the ascended bonus damage by 1, going from 19 per corpse to 20

## Why It's Good For The Game
His Grace is a very decent item, meant for hijacking chaplains. However, as it currently is, it's very hard to get the required bodies to ascend. You get about 15 to 20 seconds per body in the final 5 victims required to ascend, which is very tough as everyone is probably shoving you away, or is trying to bash your skull in.
The ascending buffs are there so you actually have a good reason to. Bloodthirst being at 140 means that you get 7 of each damage type healing, and 14 oxyloss, healing per second, as the amount scales with how much your bloodthirst is.

Resolves #19605 by making it a lot easier and more possible to actually ascend.

During testing I found 2 bugs with this, that I will have to fix before this leaves draft:
- Ascending puts the new toolbox in your other hand, and leaves your overlay sprite looking as if you are holding 2 toolboxes
- Activating does a lot of weird stuff with the buff icon.

## Testing
I beat up a lot of skrell, saw His Grace ascend, and then let it eat me.

## Changelog
:cl:
tweak: His Grace now requires 5 less victims.
tweak: His Grace now gets even stronger on ascension, and the holder gets more regeneration.
fix: Fixed some various His Grace bugs.
/:cl:

2023-10-30 18:36 UTC, Sirryan2002 commented on code/__DEFINES/combat_defines.dm
> -#define HIS_GRACE_FORCE_BONUS 4 //How much force is gained per kill.
why move this out of defines if you're converting the defines back into magic numbers in another file such as `buffs.dm` ?

2023-10-30 18:36 UTC, Sirryan2002 commented on code/game/objects/items/his_grace.dm
> +		force_bonus += HIS_GRACE_FORCE_BONUS
```suggestion
	force_bonus += ascended ? ASCEND_BONUS : HIS_GRACE_FORCE_BONUS
```

2023-11-16 17:10 UTC, Contrabang requested changes
looks pretty good, i spotted this though

2023-11-20 13:10 UTC, Contrabang requested changes
One final thing

2023-11-20 13:10 UTC, Contrabang commented on code/game/objects/items/his_grace.dm
>  		. += "<span class='his_grace'>[src] is latched closed.</span>"
```suggestion
		. += "<span class='his_grace'>[src] is latched closed.</span>"
		return
```

2023-11-20 14:08 UTC, Contrabang approved these changes

2023-11-20 19:22 UTC, lewcc commented on code/datums/status_effects/buffs.dm
> +		victims_needed = HG.victims_needed
I'm not a huge fan of mirroring values from one set of variables to another like this, it feels like there should only be one source of truth. It almost feels to me like it'd be nicer to include a reference to the toolbox in the status effect and just get the values right from it? It shouldn't be too hard to make something like this GC nicely. Regardless, it's probably worth another look.

2023-11-20 20:11 UTC, Contrabang requested changes
See Lewc's comment

2023-11-20 20:56 UTC, lewcc commented on code/game/objects/items/his_grace.dm
> +	if(!(src in held_items))
oh god what happened to that diff

2023-11-20 21:03 UTC, DGamerL commented on code/game/objects/items/his_grace.dm
> +	if(!(src in held_items))
I have no idea and I'm scared

2023-11-20 21:10 UTC, lewcc approved these changes

2023-11-23 20:16 UTC, Contrabang approved these changes

2023-11-24 15:29 UTC, merged