Shadow Demon Sound Rework
ParadiseSS13/Paradise pull request #23052
Opened 2023-10-27 15:55 UTC by Stoniest

Adds custom sounds to majority of the shadow demon.

Death sound, grapple sound, cocooning sound, attacking sounds and
hallucination sounds

## What Does This PR Do

## Why It's Good For The Game

## Images of changes

## Testing

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: Tweaked a few things
fix: Fixed a few things
wip: Added a few works in progress
soundadd: Added a new sound thingy
sounddel: Removed an old sound thingy
imageadd: Added some icons and images
imagedel: Deleted some icons and images
spellcheck: Fixed a few typos
experiment: Added an experimental thingy
/:cl:

2023-10-27 15:59 UTC, Contrabang requested changes
Some small stuff, we dont really want comments on every line, plus some comment standarization/better explanations

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +	death_sound = 'sound/shadowdemon/shadowdeath.ogg'///Adds death sound unique to shadow demon
```suggestion
	death_sound = 'sound/shadowdemon/shadowdeath.ogg'
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +	attack_sound = pick('sound/shadowdemon/shadowattack2.ogg', 'sound/shadowdemon/shadowattack3.ogg', 'sound/shadowdemon/shadowattack4.ogg')///Adds attack sounds unique to shadow demon
```suggestion
	// Pick a random attack sound for each attack
	attack_sound = pick('sound/shadowdemon/shadowattack2.ogg', 'sound/shadowdemon/shadowattack3.ogg', 'sound/shadowdemon/shadowattack4.ogg')
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +	playsound(loc, 'sound/shadowdemon/shadownode.ogg', 5, TRUE, -1) ///plays sound when finished wrapping a body
```suggestion
	playsound(loc, 'sound/shadowdemon/shadownode.ogg', 5, TRUE, extra_range = -1) ///plays sound when finished wrapping a body
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +	playsound(loc, 'sound/shadowdemon/shadownode.ogg', 5, TRUE, -1) ///plays sound when finished wrapping a body
```suggestion
	playsound(loc, 'sound/shadowdemon/shadownode.ogg', 5, TRUE, -1)
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +///custom sounds added to hallucination to be more creepy and unnerving
```suggestion
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +/obj/structure/shadowcocoon/AltClick(mob/user)///Allows you to turn on cocoons making hallucination sounds or not
```suggestion
// Allows you to turn on cocoons making hallucination sounds or not
/obj/structure/shadowcocoon/AltClick(mob/user)
```

2023-10-27 15:59 UTC, Contrabang commented on code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
> +	hitsound = 'sound/shadowdemon/shadowattack1.ogg'///Plays sound when grabbing something living or light
```suggestion
	hitsound = 'sound/shadowdemon/shadowattack1.ogg' // Plays when hitting something living or a light
```

2023-11-14 13:19 UTC, S34NW approved these changes

2023-11-14 13:20 UTC, merged