Reworks xenomorphs
ParadiseSS13/Paradise pull request #23054
Opened 2023-10-27 18:29 UTC by GDNgit

## What Does This PR Do
Reworks xenomorphs
Xenomorph disarm now takes 2 seconds between each strike (You can still get grouped up on)
Xenomorphs deal 40 stamina damage instead of 30 on each strike
Xenomorph disarm no longer disarms them of their active item (I don't think people want to play ping wars anymore)
Alien hunters are slower than they previously were (.5 movement decrease vs 1)
Alien hunter's leap now only stuns them for 3 seconds on miss, immobilizes you while leaping, moves a bit faster, and can be used in zero G
Alien hunters no longer suffer from grab slowdown
Alien sentinels have higher HP (150 -> 175)
Alien drones now have higher HP (100 -> 150)
Alien queens now have higher HP (250 -> 300)
Alien queens now have a "Tail Lash" action, knockdown down everyone around them for a few seconds, 10 second cooldown
Drone and Queen plasma vessels have had their max amount of plasma dropped to 300 from 500
Hunter plasma vessels have their max plasma dropped from 150 to 100
Alien larva plasma vessels have their max plasma dropped from 100 to 50
Neurotoxin now stuns borgs for 10 seconds and has a lower cooldown of 3 seconds
Alien weeds take 2 seconds to be planted now along with alien eggs
Alien resin structures now take 3 seconds to be planted
Resin doors have had their HP decreased from 100 to 60, now cost the same as other structures
Adds a new resin structure, the alien rejuvination pod. Heals aliens a bit faster than weeds do and slowly cures viruses, has dick all integrity, doesn't keep people buckled in it for long, and slowly revives dead aliens in it/Eggmorphs dead carbons in it (unless you're an ipc cuz you're speshal). Retrieving your dead and keeping people alive is a much higher priority now.
Xenos can be infected with viruses again
Transfer plasma now can be used on any xeno on screen, hunters and larva get transfer plasma now
Corrosive acid now has a 15 second cooldown between uses
When implant in humans, xenomorph organs have all new effects instead of the spell that just don't work against xenos.
- Plasmavessel: Syphon plasma
Click on a xeno on your screen to instantly syphon 50 plasma, 10 second cooldown
- Acid Gland: Blazing touch
Click on a resin object in melee range to instantly melt it, Click on a living mob in melee range to deal 35 fire damage and set it ablaze, 15 second cooldown with 200 plasma cost
- Neurotoxin Gland: Neurotoxin spit (human version)
Fires neurotoxin that slows xenos on hit, then if they're still slowed knocks them down for 10 seconds (basically a stun) same cost and delay of normal neurotoxin
- resin spinner: consume resin
Allows you to destroy weeds or resin in melee range, no cooldown with destroying weeds and costs 25 plasma to destroy a structure, 5 second cooldown
- Egg Sac: Combust facehuggers and eggs
Allows you to detonate facehuggers and eggs, they'll glow red and explode in a small explosion after 3 seconds, plasma cost of 75 and a 5 second cooldown.

TODO:
Make acid less wack, remove acid armor on mechs 
Make hulk a bit less silly against xenos 

Stuff I'm rather tempted to do:
Make xenos respect knockdown and stamina to an extent. They won't go into stamcrit but they'll get slowed from it (like stuns did in the past), knockdown will be less severe but it would let oldcrit be a bit less annoying with them along with a lower "extra" healthbar from crit, along with leap being able to be made less punishing
Allow facehuggers to assume multiple forms by a drone. hell might just let drones make them sentient as well
Make hunters loud when moving on surfaces that aren't resin. 
Qwerty mentioned xeno blood actually doing something like being acidic, I think that's based but it could also be just annoying.

## Why It's Good For The Game
Right now xenos are in a pretty weird state, they're fine balance wise but kinda suck to play and play against. They're not tanky at ALL so they end up dying to random stuff, the fact they don't have a baton style cooldown on disarm means that often times you'll have a ping war with someone and they either grab their weapon and shoot ya or you disarm them down and they're just dead. There's also very few differences between each cast, sentinels have an underwhelming projective, drones are hunters but slower, and hunters are just better. This PR seeks to try and give actual roles to each cast.
- Hunters
Focused on taking down unarmed targets and moving aliens/bodies to/from the front lines of combat back to the base, their leap is great for crossing people up too
- Sentinels
Focuses on 1 on 1 combat, their neurotoxin is a great opener which can be spammed down a choke if need be. They can take more punishment than other aliens meaning these are the guys you want to generally be fighting.
- Drones (Still could probably use a bit more to make em different)
A support role focusing on creating a hive to protect larva, the infected, and the dead who are being slowly revived.
- Queen
You are the most efficient way to create eggs by far. With high HP and strong attacks, your job is to serve as an ace in the hole to deal with threats other xenos would struggle with. Be warned however, your death and capture can easily spell doom for a hive if they obtain your egg sack and can't protect from an incoming assault.

If you do manage to kill a xeno as crew, it really doesn't feel impactful as the organs do absolutely nothing except for the hive and plasma vessel. This just gives a lot more to chew on and makes losing a lot of xenos actually hurt. 
This is also pretty straightforward but xenos relying on very hard counters ain't fun to use or to play against.

## Testing
So much clicking on spells....

## Changelog
:cl:
tweak: Aliens have been reworked
/:cl:

2023-10-27 18:58 UTC, matttheficus commented
> Xenomorph disarm no longer disarms them of their active item (I don't think people want to play ping wars anymore)

You would then be able to go prone to fight Xenos with melee (welders) and never get disarmed. This alone is a straight up no from me. Axe this or I cant in good conscious vote for this PR as a whole no matter what the other changes are.

Not a fan of dropping the Queen's plasma to 300. Drones are w/e.

Not a fan of the timer on egg laying - the "fun" part of Queen gameplay is base making and coordinating attacks, this is just tedium that very rarely matters.

The entire implants section is kinda wack and i dont really think it makes sense. Why would organs suddenly give you powers that Xenos themselves dont have? Unless there's more logic applied to these I'm against them. Have it be some weird Bio 8 machine or anything that makes more sense than "here have some MMO powers to fight benos".

I do think the Rejuv Sac is a neat idea. Feels very xeno to me.

Other changes are so-so/okay.

Overall, gonna go with a "**No**" vote as currently implemented ([7318e4a](https://github.com/ParadiseSS13/Paradise/pull/23054/commits/7318e4a50089e456642d5af63b949f8504f25b6c)).

2023-10-27 19:02 UTC, matttheficus commented
Also, this would mean 6 seconds to stun a single person as a Xeno.

That's a bit insane and also needs to be addressed if an approval is wanted.

2023-10-28 04:25 UTC, Rurik123 commented
So if I've read correctly: You are nerfing both hunter speed and time to stamcrit, without any compensating buff to health or removal of the burn modifier? 

The reason hunters are fast and stamcrit fast is because, when accounting for their low HP with burn modifier, they die fast. You cannot touch one without touching the other. You have the right idea with the leap change, but it is not enough to account for both of the above. 

Hard no until the above is adequately addressed.

The MMO organs and rejuv sac is... odd, but I see the minigame you're trying to create (capture the flag, except its the dead alien on the floor) and I don't feel strongly against nor for it. At the very least its limited to the xeno dynamic, and wont bleed into other antag fights. 

Shifting the queen into a combat focus as you're doing is fine.

> Xenos can be infected with viruses again

Its a fucking bioweapon not an elderly patient at the the local ward. I'm aware you made it curable in the pod, but that doesn't change that Xeno sneeze spam is annoyance with 0 benefit.

2023-11-03 03:02 UTC, spacegeese commented
the days of accidentally causing a xeno infestation with an adminspawn eggsac are over xenolads

2023-12-15 19:34 UTC, Fordoxia commented
>Neurotoxin now stuns borgs for 10 seconds and has a lower cooldown of 2 seconds

Bruh they already get instantly put to sleep on melee.

2024-01-16 16:33 UTC, Henri215 reviewed
Looking at icondiff i imagine its showing a bunch of stuff you didnt touch, right?

2024-01-16 16:33 UTC, Henri215 commented on code/_onclick/hud/alien_hud.dm
> +	else if(nightvision)
This else if is necessary?
Could snake_case the proc name too.

2024-01-16 16:33 UTC, Henri215 commented on code/datums/spells/alien_spells/build_resin_structure.dm
> +			to_chat(user, "Got past the istype checks")
Forgot to change these?

2024-01-16 16:33 UTC, Henri215 commented on code/datums/spells/alien_spells/transfer_plasma.dm
> +	desc = "Syphons 50 plasma from a nearby alien"
```suggestion
	name = "Syphon plasma"
	desc = "Syphons 50 plasma from a nearby alien."
```

2024-01-16 16:33 UTC, Henri215 commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +	name = "alien rejuvination nest"
```suggestion
	name = "alien rejuvenation nest"
```

2024-01-16 16:33 UTC, Henri215 commented on code/modules/mob/living/carbon/alien/alien_death.dm
> +	playsound(loc, 'sound/goonstation/effects/gib.ogg', 50, 1)
```suggestion
	playsound(loc, 'sound/goonstation/effects/gib.ogg', 50, TRUE)
```

2024-01-16 16:33 UTC, Henri215 commented on code/modules/mob/living/carbon/alien/larva/larva_inventory.dm
> +//can't unequip since it can't equip anything // why the fuck is this it's own file
😆

2024-01-16 16:33 UTC, Henri215 commented on code/modules/surgery/organs/subtypes/xenos.dm
> +	/// Amount of credits that will be recived by selling this in the cargo shuttle
```suggestion
	/// Amount of credits that will be received by selling this in the cargo shuttle
```

2024-02-04 21:23 UTC, S34NW requested changes
3 weeks without changes, please deconflict and update.

2024-02-04 21:32 UTC, GDNgit commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +	if(ismachineperson(dead_carbon) || isrobot(dead_carbon)) // A potential idea is to make these function like working joes in isolation, but I don't have sprites for em
MOB_ROBOTIC isn't used anymore and isn't frequently updated, I think the istype checks are alright

2024-02-04 21:33 UTC, GDNgit commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +	if(ismachineperson(dead_carbon) || isrobot(dead_carbon)) // A potential idea is to make these function like working joes in isolation, but I don't have sprites for em
Actually screw it let's start using them now

2024-02-04 21:55 UTC, GDNgit commented on code/datums/spells/alien_spells/build_resin_structure.dm
> +			to_chat(user, "Got past the istype checks")
reviews addressed

2024-02-18 17:48 UTC, matttheficus commented
Spamming leap looks REALLY silly/buggy if you do it down long hallways.

2024-02-18 21:55 UTC, spacegeese commented
>Eggmorphs dead carbons in it

what does this mean? like it makes dead carbons into hugger eggs or it makes them into larva like cm does?

2024-02-18 21:56 UTC, spacegeese commented
>Eggmorphs dead carbons in it

what does this mean? like it makes dead carbons into hugger eggs or it makes them into larva like cm does?

2024-02-19 22:15 UTC, silverplatedelta commented
Given I've read this all over and had a chance to play with it, I have some significant concerns. In my personal opinion, the issue with xenos as an antag is the stamina and stun based combat, where a loss means you are pulled into the abyss and removed from the round. Being hit four times then yoinked into the darkness isn't fun to fight against, especially when your attacker is moving at methspeed. 

After this rework, you are now hit with a ranged attack, hit two more times, then pulled into the darkness and removed from the round, with your attackers taking on average another three hits to down. Add in the ability for xenos to revive their dead, a situation in which crew numbers rapidly dwindle while xenos stay at least the same is likely (at least until crew gets some gamer gear). 

These changes have failed to address, in my opinion, the actual issue with xenos: you are hit 3-4 times, pulled into the darkness and removed from the round. This deprives several departments of a gameplay loop, mostly medical here, as they don't get patients until they have literally 40 from the nest being busted, and by then the situation is pretty much sorted. This is a stark contract from something like spiders, and blob, which use mechanics (or the lack thereof) to re-introduce crewmembers into the round to get back in the battle.

I will note, the idea of seizing xeno bodies, removing and hijacking organs to use against them is neat, but I'm unsure if its going to be used often. Being locked behind biotech six is a decently large hurdle especially earlier in the round, and puts these abilities all locked behind botany doing their job (honestly for this, just know its not the most common thing).

The meta I feel this encourages is:
Xenos: Operate in groups of 2-3, take down crew groups of the same size, run them to base, repeat. Spam spit down chokes and run in and grab who you can, given you are tanky enough.

Crew: Getting in close contact is a bad idea. the ideal move is liberal use of fire, fire chemicals, explosives, and spontaneous combustion viruses (apparently we are doing this again, hotpox is BACK baby). Avoid line of sight. Given the removal of acid armor from mechs, as well as there being no real way to combat acid placement, they are significantly reduced in use. Just sit back on a sight line and pew down a hallway.

2024-02-24 18:13 UTC, S34NW approved these changes
Four balance members in favour, a while without major reported issues on TM, it's time to go son.

2024-02-24 18:13 UTC, merged