Changes the powerfist to work off pressure
ParadiseSS13/Paradise pull request #23069
Opened 2023-10-28 18:11 UTC by Bjamcham

## What Does This PR Do
Changes the powerfist to drain a set amount of pressure per hit instead of moles from the attached air tank. This means cooling down tanks will no longer provide additional hits. Pressure drain is kept the same.
Level 1: 58 hits
Level 2: 29 hits
Level 3: 19 hits

## Why It's Good For The Game
Powerfist balance is dubiously based around a gas drain that is supposed to limit the amount of hits per level. This system works off of the moles inside of the tank instead of pressure, which would realistically be what generates the force. Draining moles means that if you cool down the air to increase the moles inside, a tank of the same pressure would provide a drastic increase in hits, effectively nullifying any cost per use and allowing the user to set it to the highest level all the time. At level 3, a tank at room temp(273 K) provides 19 hits, at 73 kelvin, you get 53 hits, and at 3 kelvin, you get 251. This scaling is absurd. With a pressure drain instead of a mole drain, max capacity tanks will all provide the same number of hits per level regardless of how many moles are stored inside. Ideally this will limit the use of level 3 or force the user to sacrifice a significant portion of their inventory to store tanks and require them to swap out more often in combat.

## Testing
Spawned in, used both a room temp and cooled tank, counted hits per level, all added up as intended.

## Changelog
:cl:
tweak: The powerfist now uses a set amount of pressure per hit instead of moles of gas.
/:cl:

2023-11-02 01:38 UTC, SpringSkipper commented
Atmos shenanigans should make a different with an atmos-powered weapon. If you want to nerf the max ammo then at most, make mole cost scale with total moles so that the increase in ammo is logarithmic rather than linear.

> Ideally this will limit the use of level 3 or force the user to sacrifice a significant portion of their inventory to store tanks and require them to swap out more often in combat.

Since combat is generally do-or-die there's actually no reason to use anything other than the highest setting at all times anyways. I've always thought the fist should just have two modes.
Fixed pressure: does a set amount of damage/knockback with a fixed pressure cost. Doing atmos shenanigans increases the ammo.
Modular pressure: does a logarithmically-scaling amount of damage/knockback with pressure, consuming a fixed fraction of the moles in the container (so that each hit is weaker than the last). Doing atmos shenanigans increases the damage/effect.

2023-11-02 17:34 UTC, Bjamcham commented
Frankly, I don't think the `atmos shenanigan` consisting of just minimizing the temp on a thermomachine added anything to this item other than making it impossible to balance the gas cost. Scaling the mole use to some logarithmic function to temperature is both needlessly complicated and a min-maxing balance nightmare that again is nothing more than a check of can you minimize the temperature of a thermomachine. Using the highest setting with this change means that you will either have to sacrifice more storage for spare tanks and open up a small window of vulnerability when swapping tanks in the middle of long fights, lower your pressure fist level, or fully disengage sooner. This is intentionally a nerf to the powerfist.

2023-11-02 23:14 UTC, Sirryan2002 requested changes

2023-11-02 23:14 UTC, Sirryan2002 commented on code/game/objects/items/weapons/powerfist.dm
> +	if(tank && !tank.air_contents.boolean_remove(((gasperfist * fisto_setting) * tank.air_contents.return_volume()) / (8.3145 * tank.air_contents.return_temperature())))
`8.3145` should be converted into a define with documentation as to how that value was reached

2023-11-03 21:51 UTC, Sirryan2002 approved these changes

2023-11-04 20:33 UTC, lewcc approved these changes

2023-11-04 20:35 UTC, merged