markdown to yaml
ParadiseSS13/Paradise pull request #23091
Opened 2023-10-30 23:20 UTC by Oyu07

## What Does This PR Do
PR Templates are only md as far as I can see, it is a shame. if there is a way, I will do it in the future
Changes Bug Report to Yaml with boxes
Gets rid of Issue Report, making it a redirect button
CHECK PICTURES
![size_l_1674018054](https://github.com/ParadiseSS13/Paradise/assets/66401072/8eea435b-c959-42a1-b83c-4ce3f132e214)

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/126dd2e8-eabd-4a97-b997-2815602acc52)
![msedge_U6ku0ZVaBQ](https://github.com/ParadiseSS13/Paradise/assets/66401072/21ffa784-cbc6-4ef4-8c05-af06558d3b7b)

## Changelog
NPFC

2023-10-30 23:24 UTC, Oyu07 commented
![size_l_1674018054](https://github.com/ParadiseSS13/Paradise/assets/66401072/8eea435b-c959-42a1-b83c-4ce3f132e214)

2023-10-30 23:24 UTC, Contrabang requested changes

2023-10-30 23:24 UTC, Contrabang commented on .github/ISSUE_TEMPLATE/config.yml
> +  about: Please place all features requests here
```suggestion
  about: Please place all feature requests here
```

2023-10-30 23:24 UTC, Contrabang commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Discord
Can you add a desc here explaining what this discord input is for, like for a discord account, etc

2023-10-30 23:30 UTC, Oyu07 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Discord
Any suggestions? Going to paraphrase this "You may optionally provide your discord username, so that we may contact you directly about the issue." as its from another repo, but something similar
also updated Discord to Discord ID

2023-10-31 00:09 UTC, Oyu07 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Discord
It is not 
`(OPTIONAL) You may provide your discord in case we need to contact you further`

2023-10-31 01:11 UTC, Oyu07 commented
For reference, these are the elements that we can use
- Checkbox
- Dropdown
- ID (a small texbox)
- Textarea (normal text box)
- Markdown (just text)
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/65b6db0e-dcb7-49bd-8e6e-d9c9c0fddde9)

2023-10-31 13:21 UTC, S34NW commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Create a report to help us improve. If this doesn't look right
If this doesn't look right what?

2023-10-31 13:22 UTC, S34NW commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    description: You may provide your discord in case we need to contact you further
I'm not sure this is a good idea to have publicly displayed. Bots trawl and can send spam if discord settings aren't configured right.
Staff already know what someone's discord is if they've linked it to their github/forum account, so maybe we should avoid it?

2023-10-31 13:23 UTC, S34NW commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Round-ID
I'd lump this in with the extra information, maybe with an example text talking about it?

2023-10-31 17:53 UTC, Oyu07 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Round-ID
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/97e9a6c7-38f1-4cc7-84a3-b52ae9c0db80)
Better?

2023-10-31 17:54 UTC, Oyu07 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    description: You may provide your discord in case we need to contact you further
Discord section gone

2023-11-01 12:11 UTC, S34NW approved these changes

2023-11-03 02:59 UTC, SteelSlayer approved these changes

2023-11-03 12:41 UTC, merged