Morgue tray now updates properly
ParadiseSS13/Paradise pull request #23109
Opened 2023-10-31 13:54 UTC by Adrer

## What Does This PR Do
Morgue tray now updates properly when you re-enter/exit your body.
Fixes: #22876

Currently a draft PR so I can fix some remaining issues

- [x] Update morgue tray state when you DNR
- [x] Use signals to update the morgue tray instead of checking whether we are in a morgue

## Why It's Good For The Game
Morgue trays should accurately represent whether the corpse inside is currently revivable, or could viably be revived in the future.

## Testing
Enter a morgue tray and die.
Morgue tray light is now green.
Exit my corpse.
Morgue tray light is now purple.

## Changelog
:cl:
fix: Morgue tray now updates properly
/:cl:

2023-10-31 14:05 UTC, Contrabang requested changes

2023-10-31 14:05 UTC, Contrabang commented on code/game/objects/structures/morgue.dm
> +	else if(!length(contents))
Please return these to guard-clauses, and just put an update icon in them

2023-10-31 14:05 UTC, Contrabang commented on code/game/objects/structures/morgue.dm
> +			return update_icon(UPDATE_OVERLAYS)
```suggestion
			update_icon(UPDATE_OVERLAYS)
			return
```

2023-10-31 14:05 UTC, Contrabang commented on code/game/objects/structures/morgue.dm
> +	else
```suggestion
```

2023-11-01 11:24 UTC, Contrabang requested changes

2023-11-01 11:24 UTC, Contrabang commented on code/modules/mob/living/living.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_UPDATE_REVIVABILITY)
Could you make this signal name more generalized? Something like `COMSIG_LIVING_GHOSTIZED`

2023-11-01 11:26 UTC, Contrabang commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_LIVING_UPDATE_REVIVABILITY "revivablity"
Also, this needs a comment, something like this
```suggestion
/// sent from the end of mob/living/ghostize: ()
#define COMSIG_LIVING_UPDATE_REVIVABILITY "revivablity"
```

2023-11-03 19:21 UTC, Sirryan2002 approved these changes

2023-11-03 19:21 UTC, Sirryan2002 commented on code/modules/mob/dead/observer/observer_base.dm
> +	SEND_SIGNAL(mind.current, COMSIG_LIVING_REENTERED_BODY)
we love better code :heart:

2023-11-03 19:22 UTC, S34NW approved these changes

2023-11-03 19:22 UTC, merged