Adds hair gradient to DNA
ParadiseSS13/Paradise pull request #23134
Opened 2023-11-02 11:54 UTC by Adrer

## What Does This PR Do
Adds hair gradient to DNA information to DNA, allowing to to persist through cloning and changeling transformation.
Fixes: #22990

## Why It's Good For The Game
Hair gradients should be retained during transfer/transformation of a body.

## Testing
Give myself a weird gradient with an offset.
Hop in the cloner and die.
Get cloned and have a hair gradient.

## Changelog
:cl:
tweak: Hair gradient is now also stored in DNA
fix: Hair gradient is transferred during a transformation or cloning.
/:cl:

2023-11-02 12:11 UTC, S34NW commented
GA's are gonna need sufficient notice of this going in so they can update their characters

2023-11-02 14:35 UTC, Contrabang requested changes

2023-11-02 14:35 UTC, Contrabang commented on code/__DEFINES/dna.dm
> +#define DNA_UI_GRADIENT_R	29
I think these should be DNA_UI_HAIR_GRADIENT_..., because otherwise they could be confused a gradient for something else

2023-11-11 22:10 UTC, Contrabang requested changes

2023-11-11 22:10 UTC, Contrabang commented on code/game/dna/dna2_helpers.dm
> +	var/gradient = GetUIValueRange(DNA_UI_HAIR_GRADIENT_STYLE,GLOB.hair_gradients_list.len)
```suggestion
	var/gradient = GetUIValueRange(DNA_UI_HAIR_GRADIENT_STYLE, length(GLOB.hair_gradients_list))
```

2023-11-11 22:10 UTC, Contrabang commented on code/game/dna/dna2_helpers.dm
> +	if((gradient > 0) && (gradient <= length(GLOB.hair_gradients_list)))
```suggestion
	if(ISINDEXSAFE(GLOB.hair_gradients_list, gradient))
```

2023-11-12 11:15 UTC, Contrabang approved these changes

2023-11-12 11:40 UTC, S34NW approved these changes

2023-11-12 11:40 UTC, merged