removes the fluff item from moonbase, modifies loot
ParadiseSS13/Paradise pull request #23157
Opened 2023-11-04 21:33 UTC by Qwertytoforty

## What Does This PR Do

Removes the fluff item from moonbase.
Moves the anomaly core into the safe, as that is more valuable than the research paper.
Paper moved outside the vault.
Added the experimental item lockbox to the safe. This one requires head or sec door access, so an explorer will have to bribe a head or officer to keep the contents.

Note: The ruin has no way to open a safe. You need to bring a stethoscope from somewhere else.

Contents 10% of the time are a facehugger, which will leap out and infect the person without a proper helmet.
This is unlikely to cause a breakout, as the person will need to not be taken to medbay during this time, and not have a mask on. Combined with sec access or head access needed, rare. As you can not look inside, not going to exactly be easy to prepare a monkey as bait either.

If not the hugger, we move onto other loot. 25% of the time an experimental KA. 25% of the time AI camera upgrade. 25% of the time ninja stealth.
The remaining 25% of the time grants some various organs. This will require medical or robotics helping you, and some of them are going to raise eyebrows if the officer or head looks in the box first.
Dark shard katana, same as mining.
Toolset abductor, good tools or rnd.
Esword arm. Better than straight up giving them an esword as they have to get it implanted, and the officer / heads are going to shut you down.
Pulse heart, bio or charging. 
Eyes of the gods, harder to use xray than the bio 8 implant.
Xeno drone organs WITHOUT hivenode. Could have fun with them, but no stunning neurotoxin, and no hearing xenos spawn.

## Why It's Good For The Game

Fluff items in space ruins are bad.

Moving the stronger loot into the safe is good.

Making a lootbox which many crewmembers could use that requires the explorer to work with a head or officer (or bribe them), with a small chance to go wrong is interesting!

## Testing

Confirm map changed correctly

Confirmed lockbox worked correctly.

## Changelog
:cl:
del: Remove fluff item from moon outpost 19
tweak: Moved anomaly core inside moon outpost 19 safe.
tweak: A lockbox with many experimental items can be found inside the outpost 19 safe.
/:cl:

2023-11-05 02:45 UTC, Sirryan2002 approved these changes

2023-11-05 02:45 UTC, Sirryan2002 commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	name = "class A-113 classified lockbox"
```suggestion
	name = "A-113 classified lockbox"
```
I would just cut down on wordiness here, the presence of a numerical identifier implies some sort of classification or product identifier

2023-11-05 22:10 UTC, kano-dot commented
i never knew eyepro was a fluff item (despite it was literally in type name and i just noticed), sorry. I like the lockbox lootbox idea, also not related but there's an autolathe in engineering wing for explorers to print a stethoscope once the area is powered up.

2023-11-06 11:05 UTC, Henri215 approved these changes
Nice surprise

2023-11-22 23:31 UTC, Contrabang requested changes

2023-11-22 23:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	new /obj/item/clothing/mask/facehugger(src) //Suprise! Storing facehuggers improperly is what lead to this mess.
I think this is more readable using prob and picks, with special cases for the facehugger and dissected drone
```suggestion
		if(prob(10))
		new /obj/item/clothing/mask/facehugger(src) //Suprise! Storing facehuggers improperly is what lead to this mess.
		return
	var/spawn_type = pick(/obj/item/gun/energy/kinetic_accelerator/experimental, /obj/item/surveillance_upgrade, /obj/item/mod/module/stealth/ninja)
	if(prob(25))
		if(rand(1, 6) == 1) //organ time. I want this to be more balanced in distribution, so organs are under a prob 25
			new /obj/item/organ/internal/alien/plasmavessel/drone(src)  //Disected drone before the place got wiped. No hivenode.
			new /obj/item/organ/internal/alien/acidgland(src)
			new /obj/item/organ/internal/alien/resinspinner(src)
			return
		spawn_type = pick(
			/obj/item/organ/internal/cyberimp/arm/katana,
			/obj/item/organ/internal/cyberimp/arm/toolset_abductor,
			/obj/item/organ/internal/cyberimp/arm/esword,
			/obj/item/organ/internal/heart/demon/pulse,
			/obj/item/organ/internal/eyes/cybernetic/eyesofgod
		)
	new spawn_type(src)
```

2023-11-23 20:09 UTC, Contrabang requested changes

2023-11-23 20:09 UTC, Contrabang commented on code/game/objects/items/weapons/storage/lockbox.dm
> +			/obj/item/organ/internal/eyes/cybernetic/eyesofgod)
This really is just stylistic, but for consistency, we have the ) on the same indentation as the declaration, after the last element.
```suggestion
			/obj/item/organ/internal/eyes/cybernetic/eyesofgod
		)
```

2023-11-23 21:15 UTC, Contrabang requested changes

2023-11-23 21:15 UTC, Contrabang commented on code/game/objects/items/weapons/storage/lockbox.dm
> +			)
```suggestion
		)
```

2023-12-05 10:14 UTC, Burzah approved these changes

2023-12-06 15:27 UTC, merged