Metastation: Maintenance Rework [Part 2]
ParadiseSS13/Paradise pull request #23164
Opened 2023-11-05 13:16 UTC by Venuska1117

## What Does This PR Do
Expand maintenances and add little more loot, change some room shapes and orientation to match each others without breaking consistency.

## Why It's Good For The Game
More areas to walk without suffocating, and more optimal room placements (not all but most of them)

## Images of changes
![2023-11-05 14 09 23](https://github.com/ParadiseSS13/Paradise/assets/89580971/d8c680a1-13f1-4e0f-a2a8-0713bbdb1365)

## Testing
Run VSC and it work for now.

## Changelog
:cl: Venuska1117
tweak: Rework and Expand Metastation: Starboard Maintenance, Starboard Secondary Maintenance, Alf-Starboard Maintenance and  Alf Secondary Maintenance.
/:cl:

2023-11-05 16:39 UTC, Venuska1117 commented
I will say it before someone check it, i did some changes with can touch other parts of station in map diff, its because i edited path for cables/pipes, because there was blue pipe with layer 2 (i didnt make it, and missed that in previous PR) and horizontal cable with dir 4 and 8 (they both Look same) so i swapped all 8 to 4dir.... Ah and Universal enzymes in maintenance for some reason have layer 5 (?) so i swapped it to normal one.

2023-12-11 21:03 UTC, Henri215 reviewed
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/6e2934df-b3a2-4f63-acc1-3bca741700ec)

1. You ended up removing that research monitor from xenobio?

![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/3ebb1985-65ef-4ae6-baa5-dce4d5ece395)


2. I would suggest adding a pen and a old drip of blood on a tile next to the paper, adds more to the immersion.

2023-12-20 23:16 UTC, Sirryan2002 commented on code/modules/paperwork/paper.dm
> +/obj/item/paper/crumpled/bloody/hacker
```suggestion
	info = "As the Diona species, we awoke aboard our terraformation vessel with the primary goal of reshaping the alien world. Our endeavors were highly successful, as we cultivated various plant species and made astonishing discoveries throughout our journey. We seeded a remarkable 'special' grass around our ship, which thrived splendidly. However, as time passed, we faced a growing challenge - a shortage of oxygen in our containment tanks hindered our ability to spread the grass further. In response, we embarked on a series of trials and experiments to engineer plants with the capacity to survive in low-oxygen environments, thus extending our breath of life. <br>Through a series of trials, combining failures and successes, we unveiled several plant species with unique attributes. Some proved to be valuable for healing purposes, while others offered addictive properties. Glowing mushrooms emerged as a source of vital light, preventing us from succumbing to the darkness. Among these discoveries, one plant commanded our utmost attention – the 'space tobacco.' While this species did not generate oxygen, it contained a chemical known as Salbutamol, enabling us to respire in low-oxygen conditions when consumed. The only drawback was the need to meticulously extract harmful compounds for its safe utilization. <br>Amid our efforts to expand the greenery, an unexpected encounter transpired. I found myself under assault by an enigmatic creature, and I was forced to flee in haste, straying too far from our vessel. As I stand now, my supplies of life-sustaining plants are dwindling, as is my ability to endure in this low-oxygen environment. Suffocation looms, and I must hasten my return to the safety of our ship to avert this dire fate."
	
/obj/item/paper/crumpled/bloody/hacker
```
spacing

2023-12-31 11:03 UTC, S34NW requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/96d19c1a-ffd1-47c1-afe0-f598212e1ae8)
This concerns me greatly, do both servers work as intended or do we run into issues when one is shut off, destroyed, etc.

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/98dd95f2-3a92-4eb8-85ab-da65c8d138fc)
Nice electrified grilles bro

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/cdfeffc3-4966-4ffe-b1c0-331a913fefe5)
Random wall pipe south of this cooler

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/5d9027e8-249d-4521-b714-90629557c5e3)
Unconnected air vent here

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/786e07c6-6851-49b3-8286-196c9a382feb)
no access on this door meaning anyone can nick this stuff, intended?

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/e802ac83-3133-4495-a880-603f79fec5c9)
No hydroponics access on this door, but there is on the maint door.

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/31af63dd-a35a-437e-8d95-d2a5bfcbe6ea)
Missing manifold here

2023-12-31 11:41 UTC, DGamerL commented
> This concerns me greatly, do both servers work as intended or do we run into issues when one is shut off, destroyed, etc.

Why is there even a second, hidden RnS server there? Wouldn't this make destroying the server in science obsolete?

2023-12-31 14:14 UTC, Henri215 commented
> > This concerns me greatly, do both servers work as intended or do we run into issues when one is shut off, destroyed, etc.
> 
> Why is there even a second, hidden RnS server there? Wouldn't this make destroying the server in science useless?

Reason is simple, decoration.

2024-01-01 17:55 UTC, Venuska1117 commented
> ![image](https://private-user-images.githubusercontent.com/12197162/293501587-96d19c1a-ffd1-47c1-afe0-f598212e1ae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE1ODctOTZkMTljMWEtZmZkMS00N2MxLWFmZTAtZjU5ODIxMmUxYWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYWZkZDAzNWNlNmVjMmY5ZTkyOTc3MmVjOTIwNTgxZjAxZjRiMjk4NGFhMmY1MWFjZmRmMTU2MTYxOGZkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwCzr8QecwN_0GYMxGA8ug6CBjqapACPMN6j_gkuJ8A) This concerns me greatly, do both servers work as intended or do we run into issues when one is shut off, destroyed, etc.
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501684-98dd95f2-3a92-4eb8-85ab-da65c8d138fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE2ODQtOThkZDk1ZjItM2E5Mi00ZWI4LTg1YWItZGE2NWM4ZDEzOGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmY2E0OWU1ZTZhMTc4NTFmMjFmYmE1MGRhNGY2NzI2NzMxMzlkYTNlMTE0NjM2NGYwZmU3NjA5NmQyOGY2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rm5kNSLod2blXsMItM7LJgrsObHR2osz7ev1XdDDmuo) Nice electrified grilles bro
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501735-cdfeffc3-4966-4ffe-b1c0-331a913fefe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE3MzUtY2RmZWZmYzMtNDk2Ni00ZmZlLWIxYzAtMzMxYTkxM2ZlZmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODk1NzVkNmYwNGU4ZmFhYmRhYzc4YWQ5ZmE4YTUyYWIxYTdjZDhjNWYzOTQ2ODIxYTgxMGZmMzQ5YTBlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W56CxaDt3b2S8aBh0vUUMxgZEA9Et61aB_8bfSNvo3s) Random wall pipe south of this cooler
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501790-5d9027e8-249d-4521-b714-90629557c5e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE3OTAtNWQ5MDI3ZTgtMjQ5ZC00NTIxLWI3MTQtOTA2Mjk1NTdjNWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDgxYjViYThmNjY5YmUxMjI2Y2Y1MzA2NTU2NDI2M2FlMzhhMjY4ZDUyZWYwMGZlOTk4NDk5ZmYyYjJhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rf2UJmjw9bHiUFvnN1hR9MNNiOfVB_6h7rEltsxhnaY) Unconnected air vent here
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501821-786e07c6-6851-49b3-8286-196c9a382feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE4MjEtNzg2ZTA3YzYtNjg1MS00OWIzLTgyODYtMTk2YzlhMzgyZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZDA5NGE1MDhkYmJjYTZlODE3ZmRlNDA1YWRkNmM0N2ExZGZkMzNhZDBjMGEyNjQ4OWU1YzEzNTZlYmFlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlkZZ3NqSKjNRxVtWfkEWiYHrCbihDx4MKp26oSsc8k) no access on this door meaning anyone can nick this stuff, intended?
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501874-e802ac83-3133-4495-a880-603f79fec5c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE4NzQtZTgwMmFjODMtMzEzMy00NDk1LWE4ODAtNjAzZjc5ZmVjNWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNzVlNDM0ZGU5NmUxYmRjZjQzNGI0NTViM2U0MTkzYjA2ZjJiNmI2YWU2NmYyODI4ZWEzOGE4MjY4NWRmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dsnCMVcoVfzHxY2uhC0n5_Tp75TdFcQyGnupNHQgLas) No hydroponics access on this door, but there is on the maint door.
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/293501948-31af63dd-a35a-437e-8d95-d2a5bfcbe6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4NzcsIm5iZiI6MTcwNDEwOTU3NywicGF0aCI6Ii8xMjE5NzE2Mi8yOTM1MDE5NDgtMzFhZjYzZGQtYTM1YS00MzdlLThkOTUtZDJhNWJmY2JlNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YjRhOGVmMTg0NmJlMDVmNDY5MDY1ZmM2MDRiNjI0YTkwMTcwYzRiNDA5NDMzN2JmMTgyMDZlMDdiZWFkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iNUO6Z4rc407Mf2Tf5mYL4xMmE3DtfWnMYe6V1o67w) Missing manifold here

I dont know what to do about botany first door, before rework first door didnt have access, so everyone can access "public" vendors (botany have its own vendors)

2024-01-01 22:47 UTC, Aylong220 reviewed
DiffBot shows that almost the entire map is affected, I don't think that's how it was designed, if I were you I would copy all my work into a separate file, take the map from the master branch, and overlay the previously saved work into a separate file, this will minimize the number of conflicts for future PRs, and make DiffBot cleaner
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/bb34cb3a-350a-4e48-965f-ed00313c2f2d)

I think changing this place is beyond the purpose of the PR, but come on, all I can say is that it's a strange decision to take away the tables and components from the room on the right side of the room
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/47308a4b-cec5-4c4e-a8b6-a6132c3fe9b5)

There was a spacewalk here, is there some reason it was removed?
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/ba46063e-b4aa-4cba-8905-7bda5da8e8e7)

I'm shocked at the amount of pipes in the walls, it's a violation of standards and just a headache if you have to change them out
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/67e60a97-e668-4b3d-96d1-7e6c9a1383b2)

I think it would be better to just put tinted windows, although that's not the best solution either, but I don't see any options to make it better without rebuilding everything
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/b837f18c-1ddd-451c-83a9-200936f694b8)

APC can be moved to a more accessible location and without wiring under reinforced tables
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/871cb055-bad8-43bf-a32b-98921243de98)

![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/ac2f8f4e-b06a-4351-8d90-bf2b8ec06000)

Status display under window and light in air
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/800390d4-6cf7-4cab-8662-cf16d992b773)

You forgot to turn shutters?
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/ae5b8879-f818-4667-b3a5-9215c0c7b783)

Exo fab in maint? Strange for me
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/0a02e618-9c6d-4c33-a9b1-7201af3d1c38)

![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/8aa8eb8c-cf0d-423f-974a-1e4ec703a794)

Why are there so many vents on pipes?
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/e95b2dfb-b84f-4752-b0ed-200b6e2adff2)

I'm certainly not from balance team, but I think hydro with biogen in maints is a bit much
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/b0de3d07-3b38-47e8-8c6a-a99f691452f4)

Why not put a normal door here, and where Pun-Pun? 
Plus about the kitchen, I think her floor used to be better, more unique
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/a8d73844-9440-4739-a99e-369aba9c8600)

1 scrubber and 1 vent is very little for room like this
And I don't understand the need for a circle of wires
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/c4d1275a-f74a-487d-a386-28c77383fd8c)

Metal rods in wall
![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/e93afab7-3464-405b-80f5-5f5cfb324dc8)

Other than that, everything else looks fine to me

2024-01-03 22:32 UTC, S34NW commented
> 
> I dont know what to do about botany first door, before rework first door didnt have access, so everyone can access "public" vendors (botany have its own vendors)

Fine to leave as-is then, thanks for checking

2024-01-06 21:54 UTC, S34NW approved these changes

2024-01-06 21:54 UTC, merged