Fix item state of flashlights & cult mirror shield
ParadiseSS13/Paradise pull request #23211
Opened 2023-11-09 19:16 UTC by dj-34

## What Does This PR Do
Fixes item states

## Why It's Good For The Game
No visual bugs

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/20109643/a410011c-2d6f-43e0-bea4-836e004a0ce4)
![image](https://github.com/ParadiseSS13/Paradise/assets/20109643/d69a7ba9-9b43-4014-9de2-6ab7046cd99f)

## Testing
Tested in game

## Changelog
:cl:
fix: Sprite "on" item states on flashlights & cult mirror shield in hands
/:cl:

2023-11-11 11:21 UTC, Henri215 approved these changes
Lewcs good to me

2023-11-11 11:32 UTC, Henri215 requested changes
Yeah :)

2023-11-11 11:32 UTC, Henri215 commented on code/game/objects/items/devices/flashlight.dm
> +		item_state = "[initial(item_state)]"
This causes flashlights that dont have a -on item_state to go invisible, you should probably scope it to only those that have it.

2023-11-14 01:33 UTC, dj-34 commented
fixed

2023-11-14 13:12 UTC, S34NW approved these changes

2023-11-14 13:13 UTC, merged