Removes Ladders
ParadiseSS13/Paradise pull request #23212
Opened 2023-11-09 19:34 UTC by DGamerL

## What Does This PR Do
Fixes #13391
Removes Jacob's ladder.
Removes ladders.

## Why It's Good For The Game
It is a very very silly item, something that was realized in 2020 already. It has been added in 2019, and was removed from tendril loot in 2021. It was only used recently for ladders such as the anchor in the beach gateway ruin.

## Testing
Booted up a server, couldn't spawn it in.

## Changelog
:cl:
del: You can't get Jacob's Ladder out of the nannybag anymore.
/:cl:

2023-11-10 11:07 UTC, spacegeese commented
what did ladders do anyways?

2023-11-10 23:28 UTC, procdrone commented
> what did ladders do anyways?

it allowed you to move between z levels by climbing up and down.

2023-12-04 19:34 UTC, Henri215 commented
The plan to add a ladder for decoration purpose only is still up?

2023-12-07 22:57 UTC, DGamerL commented
> The plan to add a ladder for decoration purpose only is still up?

Yep, forgot about this PR, gimme a bit

2023-12-12 16:58 UTC, Contrabang approved these changes
lgtm

2023-12-12 17:02 UTC, DGamerL reviewed
TODO: fix the fucking althland ruin

2023-12-12 17:02 UTC, Contrabang requested changes
oops, my bad

2023-12-12 19:47 UTC, Sirryan2002 approved these changes

2023-12-25 01:42 UTC, Contrabang requested changes

2023-12-25 01:42 UTC, Contrabang commented on _maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_excavation.dmm
> -	},
I suggest you keep this desc and name for the ladder, and change the name of the path too

2024-01-05 21:49 UTC, Burzah approved these changes

2024-01-09 13:01 UTC, S34NW approved these changes

2024-01-09 13:01 UTC, merged