overhauls verb UI
ParadiseSS13/Paradise pull request #23232
Opened 2023-11-12 00:02 UTC by GDNgit

## What Does This PR Do
overhauls verb UI; a list of verbs that got removed will be placed here later. Right now this cuts a lot of nearly unused verbs and moves preference verbs to a proper menu
complementary to #22224 

## Why It's Good For The Game
verb menus are a mess and a lot of these need shooting, being able to CTRL-F through the pref menu is good and admin menus are an absolute mess.
## Images of changes
![there we go](https://github.com/ParadiseSS13/Paradise/assets/96800819/b0fb1f00-59db-4744-9343-bb62a0556e9d)

## Testing
Clicked on verbs and other menu stuff

## Changelog
:cl:
tweak: The verb panel has been overhauled
/:cl:

2023-11-12 11:24 UTC, Contrabang commented on code/__DEFINES/preferences_defines.dm
> +#define PREFTOGGLE_GENERAL		1
Not gonna get too indepth with a review, but you should probably preface some of these defines, something like category may be good
```suggestion
#define PREFTOGGLE_CATEGORY_GENERAL		1
```

2024-01-17 02:11 UTC, Henri215 commented
Whats left to do here?

2024-01-17 20:01 UTC, GDNgit commented
> Whats left to do here?

Pretty much just UI stuff along with removing the last couple verbs. I'm probably gonna finish this fully post TGUI 4 to benefit from the tgui statpanel

2024-02-04 21:24 UTC, S34NW requested changes
TGUI update is in, please deconflict and update this.

2024-02-04 22:53 UTC, GDNgit commented
pr has been split in two parts

2024-02-04 22:53 UTC, closed without merging