Cleans up a lot of globals
ParadiseSS13/Paradise pull request #23246
Opened 2023-11-13 15:05 UTC by Contrabang

## What Does This PR Do

This removes a lot of unused globals. This means globals that were never referenced, or only written to and never read.

The total list is
<details>
  <summary>... List of all removed globals</summary>
  

- [ ] 

  
</details>

## Why It's Good For The Game
less load on the game

## Images of changes

## Testing

WIP

## Changelog
NPFC

2023-11-13 18:00 UTC, AffectedArc07 approved these changes
Approved ticker stuff

2023-11-19 15:58 UTC, Henri215 approved these changes
LGTM

2023-11-25 17:30 UTC, Sirryan2002 requested changes

2023-11-25 17:30 UTC, Sirryan2002 commented on code/modules/tgui/states/notcontained.dm
> +// GLOBAL_DATUM_INIT(notcontained_state, /datum/ui_state/notcontained_state, new)
for all of these TGUI states, can you just use a multiline comment inside of commenting out each individual line?

2023-11-27 02:47 UTC, Sirryan2002 approved these changes

2023-12-06 15:30 UTC, S34NW approved these changes

2023-12-06 15:30 UTC, merged