feat: add TGUI for stack crafting
ParadiseSS13/Paradise pull request #23253
Opened 2023-11-13 22:27 UTC by Gaxeer

## What Does This PR Do
Adds TGUI for stack crafting (crafts from different sheets e.g metal, glass etc.)
Mostly copy of https://github.com/tgstation/tgstation/pull/53657

## Why It's Good For The Game
Pretty and useful UI with search

## Images of changes
<details>
<summary>Video of UI testing</summary>

https://github.com/ParadiseSS13/Paradise/assets/44334376/f0e565fa-7afd-4c6c-af4d-a7766982fdb7

</details>

## Testing

## Changelog
:cl:
add: TGUI for stack crafting (metal sheets etc.)
/:cl:

2023-11-13 22:30 UTC, DGamerL commented on code/game/objects/items/stacks/stack.dm
> +		else if (istype(recipe, /datum/stack_recipe_list))
```suggestion
		else if(istype(recipe, /datum/stack_recipe_list))
```

2023-11-13 22:33 UTC, GDNgit commented on code/game/objects/items/stacks/stack.dm
> +		ui.set_autoupdate(TRUE)
good lord please do not have this autoupdate

2023-11-13 22:35 UTC, S34NW commented
Nice, will complete https://github.com/orgs/ParadiseSS13/projects/4/views/1?filterQuery=craf&pane=issue&itemId=38641824

2023-11-15 14:39 UTC, DogeDogIs commented
Would be cool if you can put some images, for new players this would be great

2023-11-15 16:26 UTC, Gaxeer commented
> Would be cool if you can put some images, for new players this would be great

ye, why not. Will try to do it

2023-11-25 10:07 UTC, Burzah commented on code/game/objects/items/stacks/stack.dm
> +		if(!do_after(usr, recipe_to_make.time, target = user))
```suggestion
		to_chat(user, "<span class='notice'>Building [recipe_to_make.title]...</span>")
		if(!do_after(user, recipe_to_make.time, target = user))
```
I believe these can be changed to `user`.

2024-02-04 21:24 UTC, S34NW requested changes
TGUI update is in, please deconflict and update this.

2024-02-14 22:55 UTC, S34NW commented
No change in over a week, please feel free to re-open or make a new PR once you find the time to tackle this

2024-02-14 22:55 UTC, closed without merging