fixes being unable to rename paper
ParadiseSS13/Paradise pull request #23269
Opened 2023-11-15 15:10 UTC by GDNgit

## What Does This PR Do
fixes a compiling issue resulting in paper being unable to be renamed, the lower proc would always get called first leading to a no argument runtime

## Why It's Good For The Game
bugs bad

## Testing
renamed a bunch of paper
## Changelog
:cl:
fix: Paper can once again be renamed
/:cl:

2023-11-15 15:39 UTC, Contrabang requested changes

2023-11-15 15:39 UTC, Contrabang commented on code/modules/paperwork/paper.dm
>  		return ..()
```suggestion
		rename(user)
		return
	if(ishuman(user))
		var/mob/living/carbon/human/H = user
		var/obj/item/I = H.is_in_hands(/obj/item/paper)
		if(I)
			ProcFoldPlane(H, I)
			return
	return ..()
```

2023-11-16 17:20 UTC, Contrabang approved these changes

2023-11-19 00:34 UTC, DGamerL approved these changes

2023-11-24 15:34 UTC, S34NW approved these changes

2023-11-24 15:35 UTC, merged