Updated FontAwesome
ParadiseSS13/Paradise pull request #23304
Opened 2023-11-19 04:28 UTC by Arthri

## What Does This PR Do
- Updated FontAwesome from 5.9.0 to 5.15.4. FontAwesome v6 is available but it lacks eot fonts, thus breaking compatibility
- Fixed missing virus icon in medical records console. It's already defined but the virus icon does not exist in the current used version of FontAwesome

## Why It's Good For The Game
More icons for tgui developers to use

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/41360489/fea2a553-1daa-4400-968d-21ab64dc8bbf)

## Testing
Logged into a medical records console and checked that the virus database has a virus icon beside each virus name

## Changelog
:cl: cdui
tweak: Added virus icons beside virus names in Medical Records Console's Virus Database
/:cl:

2023-11-19 08:00 UTC, Contrabang commented
I think that tweak in the CL is technically a fix.

 imo for the virus console, the old way looked better because the icon doesnt tell any information since they all have the same icon. That can be a seperate tweak PR though.

2023-11-20 04:52 UTC, Danchi299 commented
Thanks Andrew
how do I know which icons are in what version?

2023-11-20 16:14 UTC, Burzah requested changes
As per the README located in the `webfonts` folder I wanted to make sure these requirements were met, unless this has changed. 

From the README:
```
Due to the fact browse_rsc can't create subdirectories, every time you update font-awesome you'll need to change relative webfont references in all.min.css
eg ../webfonts/fa-regular-400.ttf => fa-regular-400.ttf (or whatever you call it in asset datum)

Second change is ripping out file types other than woff and eot(ie8) from the css

Finally, removing brand related css.
```

2024-01-20 22:06 UTC, Sirryan2002 approved these changes

2024-01-21 10:02 UTC, S34NW approved these changes

2024-01-21 10:02 UTC, merged