Fix holodeck tables being invisible
ParadiseSS13/Paradise pull request #23318
Opened 2023-11-21 11:51 UTC by CinnamonSnowball

## What Does This PR Do
Replaces the janky "spawn in nullspace then directly overwrite `loc`" solution in `/area/proc/copy_contents_to()` with a parameter the proc already had, `atom/newloc`. This means the loc is set earlier in the duplication code, and lets `.update_icon()` run on an actual turf rather than nullspace.

For tables specifically, this means they won't be invisible in the holodeck anymore, as they can finally smooth properly.

## Why It's Good For The Game
Invisible objects bad

## Images of changes / Testing
![2023-11-21 12_41_33](https://github.com/ParadiseSS13/Paradise/assets/100448493/f666b22b-bc66-4b04-b40d-80ddc25dd66b)

## Changelog
:cl:
fix: Holodeck tables are no longer invisible
/:cl:

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/areas = new
```suggestion
	var/list/areas = list()
```
standard syntax

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/turfs = new
```suggestion
	var/list/turfs = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/refined_src = new
```suggestion
	var/list/refined_src = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/refined_trg = new
```suggestion
	var/list/refined_trg = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/to_update = new
```suggestion
	var/list/from_update = list()
	var/list/to_update = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/refined_src = new
```suggestion
	var/list/refined_src = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/refined_trg = new
```suggestion
	var/list/refined_trg = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +	var/list/copied_objects = new
```suggestion
	var/list/to_update = list()
	var/list/copied_objects = list()
```

2023-11-24 18:05 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> +					var/list/newmobs = new
```suggestion
					var/list/newobjs = list()
					var/list/newmobs = list()
```

2023-11-25 17:22 UTC, Sirryan2002 approved these changes
looks good, nice work

2023-11-25 17:22 UTC, Sirryan2002 commented on code/__HELPERS/unsorted.dm
> -							continue
old coders were surely on some drug

2023-11-29 17:33 UTC, lewcc commented on code/__HELPERS/unsorted.dm
> +	if(length(matches) == 0)
```suggestion
	if(!length(matches))
```

2023-11-29 17:33 UTC, lewcc commented on code/__HELPERS/unsorted.dm
> +	while(length(processing_list) && found == null)
```suggestion
	while(length(processing_list) && isnull(found))
```

2023-11-29 17:41 UTC, DGamerL reviewed
While we are here

2023-12-06 15:32 UTC, S34NW requested changes
Please address reviews

2023-12-06 17:00 UTC, CinnamonSnowball commented on code/__HELPERS/unsorted.dm
> +
There's a conditional qdel call above, so I think it's valid to assume `O` might not exist anymore?

2023-12-06 17:10 UTC, Contrabang commented on code/__HELPERS/unsorted.dm
> +
Use QDELETED(O) instead imo

2023-12-06 17:11 UTC, DGamerL commented on code/__HELPERS/unsorted.dm
> +
Slightly too late, but yes, that is better

2023-12-12 19:57 UTC, S34NW approved these changes

2023-12-12 19:57 UTC, merged