reworks the changeling shield
ParadiseSS13/Paradise pull request #23334
Opened 2023-11-22 20:33 UTC by GDNgit

## What Does This PR Do
reworks the changeling shield
No longer has it's uses scale with the amount of DNA you have, has 6 uses in total. You always would have 5 DNA so it just didn't matter
Auto parries instead of requiring you to parry. 
No longer drains charges if the parry fails

## Why It's Good For The Game
This ability sucks is much worse than a riot shield. With these changes it has the use of being focused on blocking stray shots for a more mobile playstyle.
I am very sad I can't make this disarm someone if they do it in melee

## Testing
Shot at myself from a shuttle wall

## Changelog
:cl:
tweak: Changeling shield has been reworked. Autoparries and has less total charges
/:cl:

2023-11-23 02:00 UTC, Henri215 requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/fba238a6-9df8-46e0-990c-f41a94d7805d)
Forgot to edit the shield helptext with the newest changes.

2023-12-01 15:28 UTC, DGamerL requested changes
Please do Henri's review and this should be good to go

2023-12-12 19:39 UTC, Sirryan2002 approved these changes
address help text review and this is good to go

2023-12-18 17:36 UTC, S34NW requested changes
Outstanding changes unaddressed in over a month, cmon lad. Stale.

2023-12-19 09:59 UTC, farie82 commented
As the above comments mention, please resolve the request within a weeks time else the PR will be closed due to inactivity. If this happens, then you may reopen the PR if the request is resolved

2023-12-19 18:30 UTC, Henri215 commented on code/modules/antagonists/changeling/powers/mutations.dm
> +	helptext = "Organic tissue cannot resist damage forever. The shield will break after it is hit 6 times. Automatically Parries. Cannot be used while in lesser form."
```suggestion
	helptext = "Organic tissue cannot resist damage forever, with the shield breaking after it is hit 6 times. Automatically parries. Cannot be used while in lesser form."
```

2023-12-19 18:32 UTC, Henri215 approved these changes

2023-12-19 18:32 UTC, DGamerL approved these changes

2023-12-24 11:00 UTC, S34NW approved these changes

2023-12-24 11:01 UTC, merged