No more runtimes when a limb takes damage with no owner
ParadiseSS13/Paradise pull request #23341
Opened 2023-11-23 00:55 UTC by Qwertytoforty

## What Does This PR Do

Checks for an owner before checking droplimb from max damage on limbs since limbs don't droplimb with no owner and it causes null check

## Why It's Good For The Game

bugs bad

## Testing

Compiled, now has checks protected via the owner check

## Changelog
:cl:
fix: Limbs no longer runtime when taking damage with no owner
/:cl:

2023-11-23 00:56 UTC, Contrabang requested changes

2023-11-23 00:56 UTC, Contrabang commented on code/modules/surgery/organs/organ_external.dm
> +					droplimb(1) //Clean loss, just drop the limb and be done
imo this is better
```suggestion
			if(owner && dismember_at_max_damage && body_part != UPPER_TORSO && body_part != LOWER_TORSO && !HAS_TRAIT(owner, TRAIT_IPC_JOINTS_SEALED)) // We've ensured all damage to the mob is retained, now let's drop it, if necessary.
				droplimb(1) //Clean loss, just drop the limb and be done
```

2023-11-23 06:15 UTC, Contrabang approved these changes

2023-11-24 08:08 UTC, Burzah approved these changes

2023-11-29 17:18 UTC, lewcc approved these changes

2023-11-29 17:19 UTC, merged