fixes badly tabbed return true on limbs
ParadiseSS13/Paradise pull request #23386
Opened 2023-11-27 20:32 UTC by Qwertytoforty

## What Does This PR Do

fixes badly tabbed return true on limbs that makes attaching limbs to ipcs harder

## Why It's Good For The Game

bugs bad

## Testing

installed limbs

## Changelog
:cl:
fix: fixes badly tabbed return true on limbs that makes attaching limbs to ipcs harder
/:cl:

2023-11-27 20:36 UTC, DGamerL approved these changes
Oops

2023-11-27 20:48 UTC, Burzah approved these changes

2023-11-27 23:01 UTC, Contrabang requested changes

2023-11-29 15:36 UTC, farie82 approved these changes

2023-11-29 15:36 UTC, merged