Fix: Input fields autoselect
ParadiseSS13/Paradise pull request #23394
Opened 2023-11-28 12:29 UTC by Aylong220

## What Does This PR Do
Cleaning my poop

## Why It's Good For The Game
Bugs - bad

## Images of changes
<details>
 <summary>GIF</summary>

![dreamseeker_HDf4mt2PHV](https://github.com/ParadiseSS13/Paradise/assets/69762909/ca77bc36-29e9-4348-b525-55317ebf4f3c)

</details>

## Testing
Yes

## Changelog
:cl:
fix: Fixed autoselection in TGUI input fields
/:cl:

2023-11-28 21:28 UTC, Sirryan2002 requested changes
please fix your PR description, actually describe the changes in a way that showcases the bug, what issues it causes, and then describe the fix you're applying.

2023-11-28 21:43 UTC, Aylong220 commented
> please fix your PR description, actually describe the changes in a way that showcases the bug, what issues it causes, and then describe the fix you're applying.

I think it's done

2023-12-10 17:13 UTC, S34NW approved these changes

2023-12-10 19:10 UTC, Burzah approved these changes

2023-12-10 19:19 UTC, merged