Converts the space heater to tgui
ParadiseSS13/Paradise pull request #23417
Opened 2023-11-30 01:06 UTC by GDNgit

## What Does This PR Do
Converts the space heater to tgui

## Why It's Good For The Game
browser UI bad for this

## Images of changes
![Screenshot 2023-11-29 190307](https://github.com/ParadiseSS13/Paradise/assets/96800819/24b3d4ec-c308-49d0-9c2b-663b91495f2e)

## Testing
opened the tgui menu

## Changelog
:cl:
tweak: Space heater ui is now TGUI
/:cl:

2023-11-30 10:18 UTC, Gaxeer commented on tgui/packages/tgui/interfaces/SpaceHeater.js
> +const GetCellButtons = (props, context) => {
As you can see, other components have names as nouns. And this component always returns just one `button`.
So, the better name in my opinion will be just `CellButton`

2023-11-30 10:22 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +			var/obj/item/stock_parts/cell/C = usr.get_active_hand()
One letter var names are bad

2023-11-30 10:22 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +			set_temperature = dd_range(0, 90, text2num(params["change_temp"]))
0 and 90 - magic numbers

2023-11-30 10:23 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +			usr.visible_message("<span class='notice'>[usr] removes the power cell from [src].</span>", "<span class='notice'>You remove the power cell from [src].</span>")
Will be good to move `remove_cell` and `add_cell` to separate procs, for readability

2023-11-30 10:24 UTC, Gaxeer commented on tgui/packages/tgui/interfaces/SpaceHeater.js
> +        </Section>
Move to separate component, please

2023-11-30 10:28 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +				return
You set . to `TRUE`, which means, that UI update will be performed. But in this case, it's needed. As I can see.
So `return FALSE`

2023-11-30 10:29 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +				return
also `return FALSE`

2023-11-30 10:29 UTC, Gaxeer commented on code/game/machinery/spaceheater.dm
> +				return
`return FALSE`

2023-12-10 17:14 UTC, S34NW requested changes
Please see reviews

2024-01-06 23:26 UTC, S34NW commented
Stale PR, no changes made in requested timeframe. Please re-open this once changes are made or make a new PR.

2024-01-06 23:26 UTC, closed without merging