Added some cameras on NSS Cyberiad
ParadiseSS13/Paradise pull request #23426
Opened 2023-12-01 04:27 UTC by Fluffyzack21

## What Does This PR Do
 Added some cameras around the station to help the AI not to have blind spots

## Why It's Good For The Game
 It will help the AI spot people being bad and tell over the radio who is doing a bad

## Images of changes
 
![Screenshot 2023-11-30 222440](https://github.com/ParadiseSS13/Paradise/assets/98861947/e94b7504-45c1-49b1-a4e7-1492e403e42e)
![Screenshot 2023-11-30 222314](https://github.com/ParadiseSS13/Paradise/assets/98861947/a7dfd063-e9a8-45ad-b794-59a12e494928)
![Screenshot 2023-11-30 222123](https://github.com/ParadiseSS13/Paradise/assets/98861947/931551af-8bf7-42b2-8da1-67f5c4acd67b)
![Screenshot 2023-11-30 220551](https://github.com/ParadiseSS13/Paradise/assets/98861947/c0b64f95-76ee-4686-9bdd-60843d502030)
![Screenshot 2023-11-30 214821](https://github.com/ParadiseSS13/Paradise/assets/98861947/4235e9b0-8bc7-40bc-b452-230868b7762f)

## Testing
 Went as the AI and checked if the cameras were working and they were

## Changelog
:cl:
add: Added only a couple of cameras around the station
/:cl:

2023-12-01 04:47 UTC, Fluffyzack21 commented
I may or may not just close this PR, I don't know

2023-12-01 09:22 UTC, 1080pCat commented
I like this, its always a pain as ai when theres very strange blindspots.
I don't understand the downvotes and 😕 reactions, i assume its honestly just silicon hate.

2023-12-01 10:32 UTC, datlo commented
I think the downvotes are because execution isnt supposed to have a camera.

2023-12-01 11:17 UTC, Fordoxia commented
The custodial closet also lacks a camera. I regularly get asked to "fix the camera in the janitor closet"

2023-12-01 14:26 UTC, matttheficus commented
> I like this, its always a pain as ai when theres very strange blindspots. I don't understand the downvotes and 😕 reactions, i assume its honestly just silicon hate.

> I think the downvotes are because execution isnt supposed to have a camera.

I’m with datlo here, it makes sense that Execution doesn’t have a camera - that and it makes sense in-world that Security doesn’t want video proof of the wacky ways they execute people sometimes. The other spots seem fine though, only one I’m iffy on is Execution.

2023-12-01 17:32 UTC, EmeraldCandy commented
I think I also have issue with the operating theatre camera as well. In my opinion at least, its meant to be the private theatre for things that shouldnt be viewed by outsiders, hence why it has no windows. Its meant to try and help provide an area for medical antags to do some shady shit away from the prying eyes, including the AIs. I think leaving a camera out of it is ok, as I dont believe this one was left out my mistake, but by design. However, the other places are just fine I think. 

On a side note: yeah, the jani closet should probably also get a camera. Little reason to justify that one

2023-12-01 17:41 UTC, Fluffyzack21 commented
> I think I also have issue with the operating theatre camera as well. In my opinion at least, its meant to be the private theatre for things that shouldnt be viewed by outsiders, hence why it has no windows. Its meant to try and help provide an area for medical antags to do some shady shit away from the prying eyes, including the AIs. I think leaving a camera out of it is ok, as I dont believe this one was left out my mistake, but by design. However, the other places are just fine I think.
> 
> On a side note: yeah, the jani closet should probably also get a camera. Little reason to justify that one

I understand fully on the OR not having a camera, it allows for shady stuff to happen but for janitor closet. In Quotes by Hal 9000 "The janitor was intentionally left out because it's a "closet" and not really a room"

2023-12-01 18:21 UTC, meow20 commented
some places have intentional blindspots for antags, this pr is like putting up cameras in maints heh

2024-01-29 23:20 UTC, Denthamos commented
Two things

First if making multiple changes please make sure to detail in words as well what you are changing like saying a list of the cameras to go along with the photos.

Secondly with the OR camera if anything it should match the other OR with chromatic windows facing the lobby with a button inside to black out the windows from AI/characters view.  The objects on the walls there currently would need to be moved elsewhere accordingly as well.

2024-01-30 00:25 UTC, DGamerL commented on _maps/map_files/cyberiad/cyberiad.dmm
> +	c_tag = virology
```suggestion
	c_tag = "virology"
```

2024-01-30 00:26 UTC, Fluffyzack21 commented on _maps/map_files/cyberiad/cyberiad.dmm
> +	c_tag = virology
fixed it

2024-01-30 16:15 UTC, matttheficus commented
Objecting as Balance due to the cameras and windows in OR2.

As said above, some things are blind spots for a reason to allow for antags to have some safe areas to work in.

2024-01-31 08:47 UTC, S34NW requested changes
Please move the light from OR2's window onto the walls.

Your camera name tags are inconsistently capitalised, with inconsistent and sometimes poor names. Please see the mapping standards for camera name tags https://github.com/ParadiseSS13/Paradise/blob/master/.github/CONTRIBUTING.md#mapping-standards

2024-01-31 12:42 UTC, DGamerL commented
> Why It's Good For The Game
It will help the AI spot people being bad on NSS Cyberaid and tell over the radio who is doing a bad

For the next time, this really is too short of an explanation, and not really a strong one. Please put a bit more effort into that section

2024-01-31 16:10 UTC, S34NW requested changes

2024-01-31 16:10 UTC, S34NW commented on _maps/map_files/cyberiad/cyberiad.dmm
> +	c_tag = "Medbay"
More descriptive please, at least include where it is within medbay

2024-02-04 21:19 UTC, matttheficus commented
So, gonna relay some of the Dev Team stuff here:
- Not a fan of the OR2 cam or windows - it’s the one place where Medbay antags can be evil.
- Not a fan atm either, Cameras in OR are agony and there shouldn't be one in Execution either; IMO.

There are currently two objections, one Balance and one Design.

2024-02-04 22:02 UTC, Fluffyzack21 commented
> So, gonna relay some of the Dev Team stuff here:
> 
> * Not a fan of the OR2 cam or windows - it’s the one place where Medbay antags can be evil.
> * Not a fan atm either, Cameras in OR are agony and there shouldn't be one in Execution either; IMO.
> 
> There are currently two objections, one Balance and one Design.

Okay I do not have cameras in the exection room, and no cameras in the OR

2024-02-05 23:52 UTC, SteelSlayer commented
This PR has 3 objections, and will be closed. The consensus from the team is that adding windows to the OR room would destroy a lot of the privacy that medbay antags have.

2024-02-05 23:52 UTC, closed without merging