Bucking incapacitated is fast
ParadiseSS13/Paradise pull request #23478
Opened 2023-12-06 01:35 UTC by HMBGERDO

## What Does This PR Do

This PR adds check to nearby buckle so if target is incapacitated(cuffed, dead, stunned), it wont require 1 second do_after

## Why It's Good For The Game

QOL, fast buckling cuffed person is good, this also doesnt affect "combat buckle" which is still impossible

## Testing

compiled, buckled

## Changelog
:cl:
tweak: Buckling incapacitated person has no delay
/:cl:

2023-12-06 02:35 UTC, Contrabang commented on code/game/objects/buckling.dm
> +	if(M != user && !M.incapacitated() && (!in_range(M, src) || !do_after(user, 1 SECONDS, target = M)))
we're using the HANDS_BLOCKED trait instead of incapacitated calls now, please switch it to that trait

2023-12-07 19:34 UTC, Sirryan2002 approved these changes

2023-12-10 20:13 UTC, Contrabang requested changes

2023-12-10 20:13 UTC, Contrabang commented on code/game/objects/buckling.dm
> +	// TRAI_HANDS_BLOCKED check neccesary to prevent delay when incapacitated but still maintain combat delay
```suggestion
	// TRAIT_HANDS_BLOCKED check is necessary to prevent delay when incapacitated, but still keep a delay in combat
```

2023-12-12 19:53 UTC, Contrabang approved these changes

2023-12-12 20:27 UTC, S34NW approved these changes

2023-12-12 20:27 UTC, merged