Runtime and GC fixes related to orbit UI bluescreens
ParadiseSS13/Paradise pull request #23512
Opened 2023-12-09 18:45 UTC by SteelSlayer

## What Does This PR Do
* Fixes GC issues with `datum/objective_holder` Which was causing mindslaves and thralls to fail GC and have their owners to have a null entry in their `mind.antag_datums` list.

![dreamseeker_0YvUJQOlcj](https://github.com/ParadiseSS13/Paradise/assets/42044220/298f736e-eccb-4a4c-a4ec-8b438ed32aeb)

This was leading to runtimes in the orbit menu:
```dm
[2023-12-09T05:04:10] Runtime in code/modules/mob/dead/observer/orbit.dm,102: Cannot read null.name
   proc name: ui static data (/datum/orbit_menu/ui_static_data)
   usr: Kar-Ski (ckey) (/mob/dead/observer)
   usr.loc: The catwalk (107,144,2) (/turf/simulated/floor/catwalk)
   src: /datum/orbit_menu (/datum/orbit_menu)
   call stack:
   /datum/orbit_menu (/datum/orbit_menu): ui_static_data
   /datum/tgui (/datum/tgui): open
   /datum/orbit_menu (/datum/orbit_menu): ui_interact
   Kar-Ski (/mob/dead/observer): Orbit
   Orbit (/obj/screen/ghost/orbit): Click
```

* Also fixes a runtime where in `/datum/antagonist/mindslave/Destroy` where `master.current` could be null, for example if their master was dusted.

## Testing
1. Got 2 clients/characters
2. Had one be a vampire, then thralled the other.
3. Dusted the vampire, then de-thralled the thrall with holy water
4. Observed GC and runtime logs

## Changelog
Nothing, just GC and runtime fixes.

2023-12-09 18:57 UTC, Contrabang approved these changes
lgtm

2023-12-12 23:03 UTC, Sirryan2002 approved these changes
code is good for merge

2023-12-14 05:18 UTC, Contrabang requested changes
can you also set the `holder` var on objectives to be null'd on destroy? otherwise lgtm

2023-12-20 18:39 UTC, Sirryan2002 approved these changes

2023-12-25 06:07 UTC, Contrabang approved these changes

2023-12-26 19:49 UTC, lewcc approved these changes

2023-12-26 19:49 UTC, merged