Fixes railings mentioning tables on inspect.
ParadiseSS13/Paradise pull request #23554
Opened 2023-12-13 21:53 UTC by 1080pCat

## What Does This PR Do

![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/c9cfcd93-825e-4dd8-9ed6-b080ad0edf64)

## Why It's Good For The Game

![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/2fa4ba33-a1c1-473f-8085-36750594cd56)

## Testing

Checked if it worked
## Changelog
:cl:
fix: Fixed railings mentioning tables in the tip of click-dragging
/:cl:

2023-12-13 21:54 UTC, lewcc approved these changes

2023-12-13 22:29 UTC, CinnamonSnowball commented on code/game/objects/structures.dm
> +		. += "<span class='info'>You can <b>Click-Drag</b> someone to [src] to put them on [src] after a short delay.</span>"
This should probably use a "it" pronoun, repeating the same thing twice is a bit redundant

2023-12-13 23:35 UTC, Contrabang requested changes
You cant actually put people ON a railing, I think you need to put the examine behind a proc on /obj/structure, which returns the text. the railing override could just say you can click drag to climb over it

2023-12-14 16:24 UTC, Contrabang commented on code/game/objects/structures/railings.dm
> +	return "<span class='info'>You can <b>Click-Drag</b> someone to [src] to put them over [src.p_them()] after a short delay.</span>"
You can't actually click drag people onto railings or tables, only yourself. I think we should probably change these two texts

2023-12-16 16:16 UTC, S34NW requested changes
Please address reviews

2023-12-29 05:17 UTC, 1080pCat commented
> Please address reviews

Entirely forgot to actually make the change, sorry

2023-12-30 19:18 UTC, Sirryan2002 approved these changes

2024-01-16 18:02 UTC, Contrabang requested changes

2024-01-16 18:02 UTC, Contrabang commented on code/game/objects/structures.dm
> +	return "<span class='info'>You can <b>Click-Drag</b> someone to [src] to put them on [src.p_them()] after a short delay.</span>"
```suggestion
	return "<span class='info'>You can <b>Click-Drag</b> yourself to [src] to climb on top of [src.p_them()] after a short delay.</span>"
```

2024-01-28 22:24 UTC, lewcc commented on code/game/objects/structures.dm
> +	return "<span class='info'>You can <b>Click-Drag</b> yourself to [src] to climb on top of [src.p_them()] after a short delay.</span>"
We don't really need pronoun code here
```suggestion
	return "<span class='info'>You can <b>Click-Drag</b> yourself to [src] to climb on top of it after a short delay.</span>"
```

2024-01-28 22:24 UTC, lewcc commented on code/game/objects/structures/railings.dm
> +	return "<span class='info'>You can <b>Click-Drag</b> yourself to [src] to climb over [src.p_them()] after a short delay.</span>"
```suggestion
	return "<span class='info'>You can <b>Click-Drag</b> yourself to [src] to climb over it after a short delay.</span>"
```

2024-02-02 18:31 UTC, lewcc approved these changes

2024-02-04 21:37 UTC, S34NW approved these changes

2024-02-04 21:37 UTC, merged