Fix ghost bar character selector breaking when multiple characters share the same name
ParadiseSS13/Paradise pull request #23610
Opened 2023-12-19 14:46 UTC by PIerreLouisH

## What Does This PR Do
Make it so the character selector on ghost bar use index and you know which character slot you are picking.
Meaning, no more bug with same character names.

Gotta follow ACID properties and make sure unique ID (and not names) are used as identifiers.
Therefore Fixes #23608

## Why It's Good For The Game
Bug fix gud

## Testing
Spawned in ghost bar with two different characters having the same name, had no issues.

## Changelog
:cl:
fix: Fix ghost bar character selection - using ID now
/:cl:

2024-01-07 07:23 UTC, warriorstar-orion requested changes
Good fix.

2024-01-07 07:23 UTC, warriorstar-orion commented on code/modules/ruins/ghost_bar.dm
> +			our_character_saves += list("[saves.real_name] (Slot #[index])" = saves)
```suggestion
			var/slot_name = "[saves.real_name] (Slot #[index])"
			our_characters_names += slot_name
			our_character_saves += list(slot_name = saves)
```
That way we're 100% certain the UI and list keys have the exact same string

2024-01-07 07:23 UTC, warriorstar-orion commented on code/modules/ruins/ghost_bar.dm
> +		var/character_index = tgui_input_list(user, "Select a character", "Character selection", our_characters_names)
wouldn't `character_name` still be the appropriate name here? maybe `character_slot`? either way `index` suggests an integer

2024-01-14 12:59 UTC, S34NW approved these changes

2024-01-14 13:00 UTC, merged