Changed airlocks to airlock helpers on NSS, Kerberos, NSS Cyberiad, NSS Cerebron
ParadiseSS13/Paradise pull request #23634
Opened 2023-12-22 22:14 UTC by Fluffyzack21

## What Does This PR Do
 Changed the old airlocks to airlock helpers

## Why It's Good For The Game
 Helps do some stuff, and when the map first boots the button spawn instead just being there

## Testing
 Spawned as explorer and made sure the buttons worked and they were in the right spot

## Changelog
:cl:
Del: I removed all the old airlocks on NSS, Kerberos, NSS Cyberiad, NSS Cerebron
Add: I replaced them with airlock helpers on NSS, Kerberos, NSS Cyberiad, NSS Cerebron
/:cl:

2023-12-24 01:51 UTC, DGamerL commented
> Del: I removed all the old airlocks on NSS, Kerberos, NSS Cyberiad, NSS Cerebron
Add: I replaced them with airlock helpers on NSS, Kerberos, NSS Cyberiad, NSS Cerebron

The changelog is only for player-facing stuff, so only tell things that players will need to know about, something like
`tweak: changed some layouts of ... etc.`

2024-01-09 02:47 UTC, Fluffyzack21 commented
I merged the fix with the merge master, Opps

2024-02-04 21:53 UTC, warriorstar-orion requested changes
Sorry I missed this, looking at it now. You have a CI failure on Delta:
```
FAIL /datum/map_per_tile_test/pipe_vent_checker 0.1s
	84,137,2: pipe on same tile as vent or scrubber
```

2024-02-04 21:53 UTC, warriorstar-orion commented on .vscode/settings.json
> +	"GitHooks.hooksDirectory": "c:\\Users\\User1\\OneDrive\\Documents\\GitHub\\Paradise\\.git\\hooks",
Revert this

2024-02-04 22:16 UTC, warriorstar-orion commented
On Delta:

![2024_02_04__17_00_40__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/3680419e-0944-4b80-95db-73b310e3f670)


This is a docking port and shouldn't use the airlock helper. It also shouldn't use the air canister so if you want to remove that as well, that would be good.

![2024_02_04__17_03_55__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/dae086de-1c93-4efb-9bac-4cd5e519db7a)

This should almost certainly be a new airlock helper type that's gated on security access, not engineering.

Mentioned on Discord, but the CI error is due to this:

![2024_02_04__17_08_45__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/7f6ecdf8-9cb8-4e0a-9e5a-b1c700973269)

You'll have to reroute the atmos pipes leading to minisat because the airlock helper places a vent over them, which isn't permitted.

2024-02-04 22:53 UTC, Fluffyzack21 commented on .vscode/settings.json
> +	"GitHooks.hooksDirectory": "c:\\Users\\User1\\OneDrive\\Documents\\GitHub\\Paradise\\.git\\hooks",
fixed

2024-02-05 04:43 UTC, warriorstar-orion commented
On delta:
![2024_02_04__23_22_11__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/9c56e7e7-9b66-4a94-bf3d-2064a2cc8936)

The airlock helper pipes aren't connected to the canister. I would also prefer you make a new subtype for security access helpers rather than varediting the existing spawner.

---

![2024_02_04__23_27_47__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/9355e420-e149-4515-a7ed-256745a6dade)

This outlet pipe south of virology was changed.

---

![2024_02_04__23_29_49__paradise dme  delta dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/5a2a2d0c-1f50-4e26-9ba8-f13594e0a94c)

I thought you intended on using an airlock helper here? It looks like you rerouted the atmos pipes but put the normal external airlocks back.

---

On Box:

![2024_02_04__23_34_42__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/281ed8fd-c15b-497d-ac38-ad01131f083c)

Fore Port Solar access should be the engineering access subtype.

---

![2024_02_04__23_38_53__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/811a065b-35ff-4dfa-8814-4d62d9f75e42)

Make an engineering access subtype for this helper near perma.

---

![2024_02_04__23_42_46__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/78dcadaf-43c5-449d-a3a6-a53c01512992)

The helper near the AI sat should be engineering access.

2024-02-05 13:34 UTC, Fluffyzack21 commented
> On delta: ![2024_02_04__23_22_11__paradise dme delta dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302174694-9c56e7e7-9b66-4a94-bf3d-2064a2cc8936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzQ2OTQtOWM1NmU3ZTctOWI2Ni00YTk0LWJmM2QtMjA2NGEyY2M4OTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDgyYWFiMzY2ODEzMzNkNWE2ZTMwODYxM2RlNjRjZTU5NjA2Y2UxNDhmNzc2ODk5Zjk2ZTI4MWExMmY1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRLoskHXyOlGynqyXgetJZAhqugkbbJnPmNg4vXYGHM)
> 
> The airlock helper pipes aren't connected to the canister. I would also prefer you make a new subtype for security access helpers rather than varediting the existing spawner.
> 
> ![2024_02_04__23_27_47__paradise dme delta dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302175566-9355e420-e149-4515-a7ed-256745a6dade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzU1NjYtOTM1NWU0MjAtZTE0OS00NTE1LWE3ZWQtMjU2NzQ1YTZkYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZTk0MWQ5N2UyYzQyNWU0Yjc5MzZiMzdiOGE4MTI5NWNlN2ZmMGU1NGUxOTgwZGEyMjZjNmI5M2Y2ODZhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax3h0rSM_Y_uxWCj2S1ohp9d8r4S-JJbevdk45dvzYs)
> 
> This outlet pipe south of virology was changed.
> 
> ![2024_02_04__23_29_49__paradise dme delta dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302175768-5a2a2d0c-1f50-4e26-9ba8-f13594e0a94c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzU3NjgtNWEyYTJkMGMtMWY1MC00ZTI2LTliYTgtZjEzNTk0ZTBhOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjg3ODgwOWE3MDg1YTMyMTY3N2VmODJiN2Y4YjIwYmVlZDVkNDY0MDhhNDRhZDM0MzAzYjJhMDllNTFkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BFmBcpbHCz1sUIgDFuVVCmzLvP7P3pZU3XSlBNQoAH8)
> 
> I thought you intended on using an airlock helper here? It looks like you rerouted the atmos pipes but put the normal external airlocks back.
> 
> On Box:
> 
> ![2024_02_04__23_34_42__paradise dme cyberiad dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302176442-281ed8fd-c15b-497d-ac38-ad01131f083c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzY0NDItMjgxZWQ4ZmQtYzE1Yi00OTdkLWFjMzgtYWQwMTEzMWYwODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmU4YmE3YWExNzZmYzg0ZTkyYzU3Y2U4MDBkYjJmMDQwYTI2N2FkNjExZDE2ODYxYjhlMDNlNjEyZTc4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bHm5ePWOs7CVw9C2AZDje8bYK0Y8ThiqFKMBameKOUk)
> 
> Fore Port Solar access should be the engineering access subtype.
> 
> ![2024_02_04__23_38_53__paradise dme cyberiad dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302177046-811a065b-35ff-4dfa-8814-4d62d9f75e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzcwNDYtODExYTA2NWItMzVmZi00ZGZhLTg4MTQtNGQ2MmQ5Zjc1ZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NDFlMGZhZTRiMGEyYjZkMTM4MmE3ZjA4MThjZTU1MDE2ZTU5MjQyNDNiNTAwNDg0MDMwMjE0ZTJlNWY2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AwDUtGGUNsf_SwAgMwkIMkYPbrk6xt7OtHmYnBFs-5c)
> 
> Make an engineering access subtype for this helper near perma.
> 
> ![2024_02_04__23_42_46__paradise dme cyberiad dmm - StrongDMM](https://private-user-images.githubusercontent.com/59303604/302177550-78dcadaf-43c5-449d-a3a6-a53c01512992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzkzMjcsIm5iZiI6MTcwNzEzOTAyNywicGF0aCI6Ii81OTMwMzYwNC8zMDIxNzc1NTAtNzhkY2FkYWYtNDNjNS00NDlkLWEzYTYtYTUzYzAxNTEyOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZjI1ZTExMTkyZDBjMWJlYzkxZDFlZjUxNTU3ODdmODAyOTdkMzhmOTgyMmM4MTE5MmQyNTlkMzRmODY4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4bEFubEohaEukXZTGhBK9i-tCwsfN5Vge8_qSkSRST0)
> 
> The helper near the AI sat should be engineering access.

should be fixed

2024-02-05 18:45 UTC, warriorstar-orion commented
On Box:

![2024_02_05__13_08_59__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/36dc239f-c64c-4584-8979-70d35488a134)

You deleted a random tile in aft solar maints

---

![2024_02_05__13_31_41__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/01612226-27de-43c4-86ae-3d162192f8a7)

Please create an engineering-access subtype and use it here:

```c
/obj/effect/spawner/airlock/s_to_n/long/engineer
	req_access_txt = ACCESS_ENGINE_EQUIP
	door_name = "engineering external access"
```

---

![2024_02_05__13_34_51__paradise dme  cyberiad dmm  - StrongDMM](https://github.com/ParadiseSS13/Paradise/assets/59303604/17182568-d801-420c-9f2c-b6d0d77bc3f5)

Please create an engineering-access subtype and use it here:

```c
/obj/effect/spawner/airlock/s_to_n/long/square/engineer
	req_access_txt = ACCESS_ENGINE_EQUIP
	door_name = "engineering external access"
```

---

On Delta:

![2024_02_05__13_43_48__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/92e82b6f-1ea3-4672-88dd-0bc3ea6590ff)

The southern inner tile here needs to be a wall, otherwise the airlock controller will be floating in mid-air.

2024-02-06 13:15 UTC, S34NW requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/5c938404-867d-4574-9d81-b1aed7065d56)
There is an air vent under this wall in delta engineering transit tubes
_____
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/0091e254-96a1-4638-b21e-dd2e5091ab4d)
![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/0d7540f3-1a70-4f9a-a67c-efd294d86976)

These pipe are straight and not angled in delta north and south-east solars

_________

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/fbbe34c0-6f57-4363-aed8-b6fdea0a2345)
You deleted something from cyberiad maints

2024-02-06 13:57 UTC, S34NW commented
> > ![image](https://private-user-images.githubusercontent.com/12197162/302634771-5c938404-867d-4574-9d81-b1aed7065d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzQ3NzEtNWM5Mzg0MDQtODY3ZC00NTc0LTlkODEtYjFhZWQ3MDY1ZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNzlkZGIxMjNlNDM1NTlkMDdiOGM5ZjQzMWNmZWI4M2VjNjIwNmI1ZDRkZjg4N2JkZTY3NTU1ZTQ5NGFmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyMqcbGhEEYB_BtoDEyCUPTraIEouGZVDug9OzEmn1U) There is an air vent under this wall in delta engineering transit tubes
> > ![image](https://private-user-images.githubusercontent.com/12197162/302636043-0091e254-96a1-4638-b21e-dd2e5091ab4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzYwNDMtMDA5MWUyNTQtOTZhMS00NjM4LWIyMWUtZGQyZTUwOTFhYjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiODVhZmRjMzE4MWNlMjBkNThjMGRhMTdhYjVjOWQ1NTc4YmM3NjY0YmMxMjI1Y2ZlZGNkYWE4NjcyYzU4YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Us2D_EsAdKBuXFwHftThNG6RodkGD_60r2fKhcZO6M4) ![image](https://private-user-images.githubusercontent.com/12197162/302636296-0d7540f3-1a70-4f9a-a67c-efd294d86976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzYyOTYtMGQ3NTQwZjMtMWE3MC00ZjlhLWE2N2MtZWZkMjk0ZDg2OTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YTE0ZjMwOWQ5NmUxOWU1MjQxYWE1Y2IwOGEwYzljNzE3ZGYzNGUxNzU1MGVjOTk1ZTIxYmVmMTcyOWFmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeLHeQCMWpreFahgO1a8x_pMjo-uYzg2waWEwWpdBZs)
> > These pipe are straight and not angled in delta north and south-east solars
> > ![image](https://private-user-images.githubusercontent.com/12197162/302636661-fbbe34c0-6f57-4363-aed8-b6fdea0a2345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzY2NjEtZmJiZTM0YzAtNmY1Ny00MzYzLWFlZDgtYjZmZGVhMGEyMzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmM5OTRmMTIzYmFiNTEzMzUzMDc1ZTlhMTU2NjVlOWMxM2MzZmZjOTY0OGM5YTVmMWYxZDdhOTg4ZTVlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOsUpz4rWxwUobV4EGBqMmhq47oClag14BKBUaz4u90) You deleted something from cyberiad maints
> 
> fixed

![image](https://github.com/ParadiseSS13/Paradise/assets/12197162/cc432f44-1605-47f1-89f3-864fbc2a3dd2)
That vent is still there on delta

2024-02-06 13:58 UTC, Fluffyzack21 commented
> > > ![image](https://private-user-images.githubusercontent.com/12197162/302634771-5c938404-867d-4574-9d81-b1aed7065d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzQ3NzEtNWM5Mzg0MDQtODY3ZC00NTc0LTlkODEtYjFhZWQ3MDY1ZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNzlkZGIxMjNlNDM1NTlkMDdiOGM5ZjQzMWNmZWI4M2VjNjIwNmI1ZDRkZjg4N2JkZTY3NTU1ZTQ5NGFmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyMqcbGhEEYB_BtoDEyCUPTraIEouGZVDug9OzEmn1U) There is an air vent under this wall in delta engineering transit tubes
> > > ![image](https://private-user-images.githubusercontent.com/12197162/302636043-0091e254-96a1-4638-b21e-dd2e5091ab4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzYwNDMtMDA5MWUyNTQtOTZhMS00NjM4LWIyMWUtZGQyZTUwOTFhYjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiODVhZmRjMzE4MWNlMjBkNThjMGRhMTdhYjVjOWQ1NTc4YmM3NjY0YmMxMjI1Y2ZlZGNkYWE4NjcyYzU4YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Us2D_EsAdKBuXFwHftThNG6RodkGD_60r2fKhcZO6M4) ![image](https://private-user-images.githubusercontent.com/12197162/302636296-0d7540f3-1a70-4f9a-a67c-efd294d86976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzYyOTYtMGQ3NTQwZjMtMWE3MC00ZjlhLWE2N2MtZWZkMjk0ZDg2OTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YTE0ZjMwOWQ5NmUxOWU1MjQxYWE1Y2IwOGEwYzljNzE3ZGYzNGUxNzU1MGVjOTk1ZTIxYmVmMTcyOWFmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeLHeQCMWpreFahgO1a8x_pMjo-uYzg2waWEwWpdBZs)
> > > These pipe are straight and not angled in delta north and south-east solars
> > > ![image](https://private-user-images.githubusercontent.com/12197162/302636661-fbbe34c0-6f57-4363-aed8-b6fdea0a2345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2MjcsIm5iZiI6MTcwNzIyNTMyNywicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2MzY2NjEtZmJiZTM0YzAtNmY1Ny00MzYzLWFlZDgtYjZmZGVhMGEyMzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmM5OTRmMTIzYmFiNTEzMzUzMDc1ZTlhMTU2NjVlOWMxM2MzZmZjOTY0OGM5YTVmMWYxZDdhOTg4ZTVlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOsUpz4rWxwUobV4EGBqMmhq47oClag14BKBUaz4u90) You deleted something from cyberiad maints
> > 
> > 
> > fixed
> 
> ![image](https://private-user-images.githubusercontent.com/12197162/302652849-cc432f44-1605-47f1-89f3-864fbc2a3dd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjgxNTYsIm5iZiI6MTcwNzIyNzg1NiwicGF0aCI6Ii8xMjE5NzE2Mi8zMDI2NTI4NDktY2M0MzJmNDQtMTYwNS00N2YxLTg5ZjMtODY0ZmJjMmEzZGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzQxODYwNTI1N2YxNmIwZWYzMmEzMGVjYzc2NGU1MzhkZjM3MTE5YjIzODgxNzYwYWVkM2ZmODJkNjBmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KI9LVUKmoDmvbwu9O0CK_YJ24k-Kia4ATYaGYHRv5N4) That vent is still there on delta

Well gone now

2024-02-06 14:02 UTC, merged