Intellicard improved description
ParadiseSS13/Paradise pull request #23633
Opened 2023-12-22 20:09 UTC by HMBGERDO

## What Does This PR Do

This PR adds description to intellicard when you examine it with AI inside
If AI has a camera it now informs you about it and notices that you can use tape roll on it

This PR also makes AI not restoring their camera if they cracked it(malf module) after removing duct tape

## Why It's Good For The Game

Hidden mechanics only being known from the code readers is not cool, more information in game is better

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/61080616/6f112add-815c-46f1-a853-ad1c19d05661)

## Testing

Compiled, used duct tape on intellicard, removed tape

## Changelog
:cl:
tweak: Intellicard description improved, added information about using tape roll to tape AI's camera
fix: Malf AI cracked camera no longer get restored after removing duct tape from the intellicard
/:cl:

2023-12-22 20:31 UTC, Contrabang requested changes

2023-12-22 20:31 UTC, Contrabang commented on code/modules/mob/living/silicon/silicon_subsystems.dm
> +	var/cracked_camera = FALSE // will be true if malf AI break its camera
This should be on the ai define in ai_mob.dm

2024-01-15 01:15 UTC, Contrabang approved these changes
code is fine

2024-01-21 20:52 UTC, S34NW approved these changes

2024-01-21 20:52 UTC, merged