LOOC no longer showed on runechat if muted in preferences
ParadiseSS13/Paradise pull request #23640
Opened 2023-12-23 17:30 UTC by PIerreLouisH

## What Does This PR Do
LOOC no longer showed on runechat if muted in preferences. Fixes #23639
Add a smoll check to do so

## Why It's Good For The Game
Oversight fix is always good.

## Changelog
:cl:
fix: LOOC runechat no longer displayed when muted in preferences
/:cl:

2023-12-23 18:26 UTC, Contrabang requested changes

2023-12-23 18:26 UTC, Contrabang commented on code/game/verbs/ooc.dm
> +				if(M.client?.prefs.toggles2 & PREFTOGGLE_2_RUNECHAT) // Check if Runechat is enabled
These two lines should be combined into one. Something like this

```suggestion
				if((M.client?.prefs.toggles2 & (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC) == (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) // Check if Runechat and LOOC is enabled
```

2024-01-07 19:06 UTC, DGamerL reviewed
I think this is what contra meant

2024-01-07 19:06 UTC, DGamerL commented on code/game/verbs/ooc.dm
> +			if(M.client?.prefs.toggles & PREFTOGGLE_CHAT_LOOC) // Check if LOOC is enabled in game preferences
```suggestion
```

2024-01-07 19:06 UTC, DGamerL commented on code/game/verbs/ooc.dm
> +				if((M.client?.prefs.toggles2 & (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) == (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) // Check if Runechat and LOOC is enabled // Check if Runechat and LOO
```suggestion
				if((M.client?.prefs.toggles2 & (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) == (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) // Check if Runechat and LOOC is enabled
```

2024-01-07 19:12 UTC, Contrabang commented on code/game/verbs/ooc.dm
> +				if((M.client?.prefs.toggles2 & (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) == (PREFTOGGLE_2_RUNECHAT|PREFTOGGLE_CHAT_LOOC)) // Check if Runechat and LOOC is enabled // Check if Runechat and LOO
I apologize, I made a mistake PREFTOGGLE_2_RUNECHAT is on toggles2, while PREFTOGGLE_CHAT_LOOC is on toggles. This means these two have to be checked seperately. Basically `(M.client?.prefs.toggles2 & (PREFTOGGLE_2_RUNECHAT) && M.client.prefs.toggles & (PREFTOGGLE_CHAT_LOOC))`

2024-01-20 20:38 UTC, Sirryan2002 requested changes
please address the requested changes or your PR will be closed

2024-02-04 21:38 UTC, S34NW commented
Closing due to staleness. Please reopen or make a new PR when requested changes have been made.

2024-02-04 21:38 UTC, closed without merging