Increase default topic limit to 200
ParadiseSS13/Paradise pull request #23723
Opened 2024-01-05 00:36 UTC by Aylong220

## What Does This PR Do
Just increases default minute topic limit from 100 to 200

## Why It's Good For The Game
I'm sure a lot of people have had situations when in a normal game, you get a warning that you've done too many actions in a minute, without using macros, most often it is noticeable when playing for the AI.
The limit was set 3 years ago, and during this time a lot of things have changed, including the players themselves who could easily learn to click faster plus hotkeys, thanks to which it became possible to cross this threshold many times more easily

The new threshold should save regular players from being annoyingly ignored just because they are faster.

## Images of changes

## Testing
No need, just a number

## Changelog
:cl:
tweak: Message "Your previous action was ignored because you've done too many in a minute." should now not pop up for normal players
/:cl:

2024-01-06 18:48 UTC, Burzah approved these changes

2024-01-14 12:05 UTC, AffectedArc07 requested changes

2024-01-14 12:05 UTC, AffectedArc07 commented on code/modules/client/client_procs.dm
> +	var/mtl = 200 // 200 topics per minute
```suggestion
	var/mtl = 150 // 150 topics per minute
```
This is still 2.5 topics a second.

2024-01-14 12:12 UTC, AffectedArc07 approved these changes

2024-01-21 21:07 UTC, merged