Reboots the CNS implant
ParadiseSS13/Paradise pull request #23813
Opened 2024-01-15 03:37 UTC by Qwertytoforty

## What Does This PR Do

The CNS rebooter no longer runs a life based reduction of stamina every 2 seconds.
Instead, when a person enters stamina crit with the CNS rebooter, it will lower their stamina regen time to 4 seconds. 
This does **not** impact stamina regeneration out of stamina crit. If you take 90 stamina damage, you will take 10 seconds to regenerate your stamina.

EMPing the implant stuns as before. However, it will be disabled for 30 seconds or a minute, depending on EMP severity.

## Why It's Good For The Game

Current CNS rebooter is... niche. It can save your ass. It will take 3 batons to down you, over 2. If you eat a bunch of buckshot rapidly, it can recover a bunch of stamina.

If you are disabled however, it probably won't help you much.

The issue is the implant checks every 2 seconds off life. As such, depending on on when you are hit, it can have a massive impact.
If you are hit slowly by disablers, it will not help you.
An upgraded cybernetic heart will help much better (for more significant risk)

This PR makes the implant work more like old CNS.
It will not help you before stamina crit, but it will help you outside of stamina crit. A person will need to consistently apply stamina to you, or cuff you *right* after stamina critting you, or you will get back up fast. Of course, someone harmbatoning you to death will kill you, but that would kill you with cybernetic heart and old cns with old baton.

This implant will be good for a surprise vs officers, or officers in a group,
For advantages to the heart, while the heart provides constant stamina healing, the CNS implant will fully recover stamina after a stamina crit. People will have to use their resources on you much more often to keep you stamina crit, be it more disablers, or more baton charge.

## Testing

Batoned and disabled my self a bunch, along with other skrells.
Worked as expected.

## Changelog
:cl:
tweak: CNS no longer removes stamina potentially after every 2 seconds. Instead, will shorten stamina crit time to 4 seconds
/:cl:

2024-01-15 05:33 UTC, Contrabang requested changes

2024-01-15 05:33 UTC, Contrabang commented on code/modules/surgery/organs/augments_internal.dm
> +	RegisterSignal(M, COMSIG_CARBON_STAMINA_REGENERATED)
```suggestion
	UnregisterSignal(M, list(COMSIG_CARBON_ENTER_STAMINACRIT, COMSIG_CARBON_EXIT_STAMINACRIT, COMSIG_CARBON_STAMINA_REGENERATED)
```

2024-01-16 17:58 UTC, Contrabang requested changes

2024-01-16 17:58 UTC, Contrabang commented on code/modules/mob/living/carbon/carbon_status_procs.dm
> +	stam_regen_start_time = world.time + STAMINA_REGEN_BLOCK_TIME * stamina_regen_block_modifier
```suggestion
	stam_regen_start_time = world.time + (STAMINA_REGEN_BLOCK_TIME * stamina_regen_block_modifier)
```

2024-01-16 17:58 UTC, Contrabang commented on code/modules/mob/living/damage_procs.dm
> +		stam_regen_start_time = world.time + STAMINA_REGEN_BLOCK_TIME * stamina_regen_block_modifier
ditto

2024-01-16 17:58 UTC, Contrabang commented on code/modules/mob/living/damage_procs.dm
> +		stam_regen_start_time = world.time + STAMINA_REGEN_BLOCK_TIME * stamina_regen_block_modifier
ditto

2024-01-16 17:58 UTC, Contrabang commented on code/modules/surgery/organs/augments_internal.dm
> +	SIGNAL_HANDLER
Mostly a nitpick
```suggestion
	SIGNAL_HANDLER // COMSIG_CARBON_ENTER_STAMINACRIT
```

2024-01-16 17:58 UTC, Contrabang commented on code/modules/surgery/organs/augments_internal.dm
> +	SIGNAL_HANDLER
Mostly a nitpick
```suggestion
	SIGNAL_HANDLER // COMSIG_CARBON_EXIT_STAMINACRIT
```

2024-01-16 17:58 UTC, Contrabang commented on code/modules/surgery/organs/augments_internal.dm
> +	SIGNAL_HANDLER
Mostly a nitpick
```suggestion
	SIGNAL_HANDLER // COMSIG_CARBON_STAMINA_REGENERATED
```

2024-02-04 21:45 UTC, S34NW approved these changes

2024-02-04 21:45 UTC, merged