Refactor machinery hand attack
ParadiseSS13/Paradise pull request #23820
Opened 2024-01-15 20:30 UTC by m-dzianishchyts

## What Does This PR Do
Extract preprocessing of machinery hand attack.

## Why It's Good For The Game
This will make it easier for coders to modify machinery interaction limitations without duplicate code.

## Testing
Works fine.

## Changelog
:cl:
tweak: Refactored machinery hand attack
/:cl:

2024-01-15 20:31 UTC, DGamerL commented on code/game/machinery/machinery.dm
> +	if (attack_result != null)
```suggestion
	if(attack_result != null)
```

2024-01-15 20:40 UTC, Sirryan2002 commented on code/game/machinery/machinery.dm
please document these procs really well, coders should really understand why and when to use `try_attack_hand`

2024-01-29 23:49 UTC, Gaxeer commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/try_attack_hand(mob/user as mob)
as is redundant in procs

2024-01-30 00:11 UTC, GDNgit requested changes

2024-01-30 00:11 UTC, GDNgit commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/try_attack_hand(mob/user as mob)
```suggestion
/obj/machinery/proc/try_attack_hand(mob/user)
```
The AS keyword is only useful for verbs/lists using as anything

2024-01-30 18:16 UTC, GDNgit approved these changes
Looks fine codewise. No need to have a CI though because this isn't playerfacing.

2024-01-31 15:38 UTC, DGamerL approved these changes
LGTM

2024-02-02 17:16 UTC, lewcc approved these changes

2024-02-02 17:16 UTC, merged