Small QOL improvement for (bluespace) light replacers
ParadiseSS13/Paradise pull request #23826
Opened 2024-01-16 11:05 UTC by DGamerL

## What Does This PR Do
Light replacers will now also work when you click on an object on the tile, meaning you don't have to pixelhunt for the turf.

## Why It's Good For The Game
It can be very frustrating that clicking on the light fixture will not work, as it currently doesn't accept any other input than turfs.

## Testing
Could replace the broken light by clicking on the lighter that I dropped on the turf

## Changelog
:cl:
tweak: Light replacers now work on anything on a tile, instead of only working when clicking a tile
/:cl:

2024-01-16 12:04 UTC, Henri215 approved these changes
LGTM

2024-01-16 18:10 UTC, Contrabang requested changes

2024-01-16 18:10 UTC, Contrabang commented on code/game/objects/items/devices/lightreplacer.dm
> +		replace_turf = get_turf(T)
Could make it work for mobs too
```suggestion
	var/turf/replace_turf = get_turf(T)
	if(!istype(T))
		return
```

2024-01-16 18:12 UTC, DGamerL commented on code/game/objects/items/devices/lightreplacer.dm
> +		replace_turf = get_turf(T)
Sounds good

2024-01-19 15:19 UTC, Contrabang requested changes
i missed this

2024-01-19 15:19 UTC, Contrabang commented on code/game/objects/items/devices/lightreplacer.dm
> +	if(!istype(T))
```suggestion
	if(!istype(replace_turf))
```

2024-01-19 15:46 UTC, DGamerL commented on code/game/objects/items/devices/lightreplacer.dm
> +	if(!istype(T))
I did aswell, whoops

2024-01-20 18:44 UTC, Contrabang approved these changes

2024-01-25 19:28 UTC, lewcc commented on code/game/objects/items/devices/lightreplacer.dm
> +	var/turf/replace_turf = get_turf(T)
Can you rename the variable from `T` to something more descriptive here?

2024-01-25 20:18 UTC, lewcc approved these changes

2024-01-25 20:18 UTC, merged