Converts over the missing TGUI input lists
ParadiseSS13/Paradise pull request #23859
Opened 2024-01-20 00:25 UTC by GDNgit

## What Does This PR Do
Converts over the missing TGUI input lists. Admin verbs not included

## Why It's Good For The Game
UI consistency 

## Testing
I tested some of these but there's like a 100 in here and I'm not going to write off three hours to do that.

## Changelog
:cl:
fix: The missing TGUI input lists have been converted over
/:cl:

2024-01-20 11:37 UTC, S34NW requested changes
`I tested some of these but there's like a 100 in here and I'm not going to write off three hours to do that.`

My friend, it is important we don't just kneecap all the input selectors, please do check them or draft help to do so if you are making this change.

2024-02-14 20:11 UTC, S34NW commented on code/modules/mob/living/simple_animal/hostile/terror_spiders/empress_terror.dm
> +	var/numlings = input("How many in the batch?") as null|num
Apart from that, looks fine for merge

2024-02-14 21:13 UTC, GDNgit commented on code/modules/mob/living/simple_animal/hostile/terror_spiders/empress_terror.dm
> +	var/numlings = input("How many in the batch?") as null|num
done

2024-02-14 21:17 UTC, S34NW approved these changes

2024-02-14 21:17 UTC, merged