Refactors composting, allows to compost things again
ParadiseSS13/Paradise pull request #23883
Opened 2024-01-22 16:37 UTC by DGamerL

## What Does This PR Do
Refactors composting so you can compost plants again, instead of only pills.
Fixes #23882

## Why It's Good For The Game
Very old code should absolutely get a cleanup

## Testing
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/574d5bdd-9009-4b96-b34a-d603a9d4b311)

## Changelog
:cl:
fix: Fixed plants and food not being compostable
/:cl:

2024-01-22 23:24 UTC, Burzah requested changes

2024-01-22 23:24 UTC, Burzah commented on code/modules/hydroponics/hydroponics_tray.dm
> +			playsound(loc, 'sound/effects/spray3.ogg', 50, 1, -6)
```suggestion
			playsound(loc, 'sound/effects/spray3.ogg', 50, TRUE, -6)
```

2024-01-22 23:24 UTC, Burzah commented on code/modules/hydroponics/hydroponics_tray.dm
> +			playsound(loc, 'sound/effects/slosh.ogg', 25, 1)
```suggestion
			playsound(loc, 'sound/effects/slosh.ogg', 25, TRUE)
```

2024-02-04 01:30 UTC, lewcc approved these changes
LGTM

2024-02-04 01:31 UTC, merged