TRAIT_TABLE_LEAP Checks Added To under_siege  Judo
ParadiseSS13/Paradise pull request #23905
Opened 2024-01-24 16:37 UTC by Varelion

## What Does This PR Do

This PR closes #23766. 
It checks for the table_leap trait in corporate judo.

## Why It's Good For The Game
Consistency in logic. Corporate judo is inherited through cloning; it stands to reason that table-jumping would as well. Due to where these things are stored, and how cloning works, previously you would only inherit corporate judo. Now, however, you inherit both; this is done by intergrading the ability to jump tables fast into Bartender's corporate judo.

## Testing
 Hosted a test server, got some members to test cloning with bartender, and their judo abilities before and after. 

## Changelog
:cl:
tweak: Add 'TRAIT_TABLE_LEAP' checks to 'under_siege' judo.
fix: closes #23766 
/:cl:

2024-01-24 16:40 UTC, DGamerL reviewed
While this does fix the issue for the bartender, this doesn't fix it for the chef.
You could consider making it a mind trait instead? That way it will transfer upon cloning

2024-01-24 16:40 UTC, DGamerL commented on code/modules/martial_arts/judo.dm
> +	if(HAS_TRAIT(H, TRAIT_TABLE_LEAP) == FALSE)
```suggestion
	if(!HAS_TRAIT(H, TRAIT_TABLE_LEAP))
```

2024-01-24 16:40 UTC, DGamerL commented on code/modules/martial_arts/judo.dm
> +	if(HAS_TRAIT(H, TRAIT_TABLE_LEAP) == TRUE)
```suggestion
	if(HAS_TRAIT(H, TRAIT_TABLE_LEAP))
```

2024-01-24 16:40 UTC, DGamerL commented on code/modules/martial_arts/judo.dm
> +	if(HAS_TRAIT(H, TRAIT_TABLE_LEAP) == FALSE)
```suggestion
	if(!HAS_TRAIT(H, TRAIT_TABLE_LEAP))
```

2024-01-24 16:40 UTC, DGamerL commented on code/modules/martial_arts/judo.dm
> +	if(HAS_TRAIT(H, TRAIT_TABLE_LEAP) == FALSE)
```suggestion
	if(!HAS_TRAIT(H, TRAIT_TABLE_LEAP))
```

2024-01-24 16:42 UTC, Henri215 commented
Change your changelog to something like "fix: bartenders no longer loses their jumping over table skills when cloned". Remember that it should be written considering the average player is going to read it and must understand it.

2024-01-24 19:39 UTC, Contrabang requested changes
Adding the trait onto the martial art is really hacky, instead it should be done through signals or having the trait be on the mind.

Using something like this on a human, will transfer the trait
`RegisterSignal(src, COMSIG_BODY_TRANSFER_TO, PROC_REF(make_a_new_proc))`

```
/mob/living/carbon/human/proc/whatever_proc_name()
    ADD_TRAIT(H, TRAIT_TABLE_LEAP, ROUNDSTART_TRAIT)
```

2024-01-24 19:40 UTC, DGamerL commented
> Adding the trait onto the martial art is really hacky, instead it should be done through signals or having the trait be on the mind.
> 
> Using something like this on a human, will transfer the trait `RegisterSignal(src, COMSIG_BODY_TRANSFER_TO, PROC_REF(make_a_new_proc))`
> 
> ```
> /mob/living/carbon/human/proc/whatever_proc_name()
>     ADD_TRAIT(H, TRAIT_TABLE_LEAP, ROUNDSTART_TRAIT)
> ```

I'd suggest just doing it on the mind yeah, much easier

2024-01-24 21:01 UTC, Varelion commented
> Adding the trait onto the martial art is really hacky, instead it should be done through signals or having the trait be on the mind.
> 
> Using something like this on a human, will transfer the trait `RegisterSignal(src, COMSIG_BODY_TRANSFER_TO, PROC_REF(make_a_new_proc))`
> 
> ```
> /mob/living/carbon/human/proc/whatever_proc_name()
>     ADD_TRAIT(H, TRAIT_TABLE_LEAP, ROUNDSTART_TRAIT)
> ```

I'm looking into the mind implementation, but I'd also be introducing the functionality to add and remove these admin side through the procs present in CQC and Judo's respective siege sides. Why would I go about it through a signal, and not an if statement?

2024-01-24 23:26 UTC, DGamerL approved these changes
Could've sworn we had a helper to add to immediately add to a mob's mind, but LGTM

2024-01-24 23:26 UTC, DGamerL commented on code/__HELPERS/trait_helpers.dm
> +
```suggestion
```

2024-01-27 18:09 UTC, Sirryan2002 approved these changes

2024-01-27 18:26 UTC, Contrabang approved these changes

2024-01-30 14:44 UTC, S34NW approved these changes

2024-01-30 14:44 UTC, merged