The admin outfit "Debug outfit" gets the breathless DNA string active now.
ParadiseSS13/Paradise pull request #23945
Opened 2024-01-26 16:13 UTC by 1080pCat

## What Does This PR Do

Title. 
## Why It's Good For The Game

Reincarnating as a vox and needing to turn breathless on constantly has frustrated me enough to make a pr about it, hopefully im not alone in this frustration. 
Yes im aware that they have a air tank, but for plasmen and vox that cant breath oxygen, they start taking damage, and is just annoying enough to have me make a pr about it.

## Testing

Tested, worked.
## Changelog
:cl:
NPFC
/:cl:

2024-01-26 16:15 UTC, Henri215 commented on code/datums/outfits/outfit_debug.dm
> +	H.dna.SetSEState(GLOB.breathlessblock,1)
```suggestion
	H.dna.SetSEState(GLOB.breathlessblock, 1)
```

2024-01-26 16:17 UTC, DGamerL commented on code/datums/outfits/outfit_debug.dm
> +	H.dna.default_blocks.Add(GLOB.soberblock)
So they're sober aswell?

2024-01-26 16:30 UTC, 1080pCat commented on code/datums/outfits/outfit_debug.dm
> +	H.dna.default_blocks.Add(GLOB.soberblock)
oh woops

2024-01-26 16:49 UTC, Contrabang requested changes

2024-01-26 16:49 UTC, Contrabang commented on code/datums/outfits/outfit_debug.dm
>  		apply_to_card(I, H, get_all_accesses(), "Debugger", "admin")
Just for consistency with how other outfits tend to be
```suggestion
	var/obj/item/card/id/I = H.wear_id
	if(istype(I))
		apply_to_card(I, H, get_all_accesses(), "Debugger", "admin")
		
	H.dna.SetSEState(GLOB.breathlessblock, 1)
	singlemutcheck(H, GLOB.breathlessblock, MUTCHK_FORCED)
	H.dna.default_blocks.Add(GLOB.breathlessblock)
	H.check_mutations = 1
```

2024-01-26 17:16 UTC, Contrabang approved these changes

2024-01-27 00:42 UTC, DGamerL approved these changes
> 🆑
NPFC
/:cl:

Just replace this entire block with `NPFC`

2024-01-27 17:19 UTC, Contrabang approved these changes

2024-02-06 03:00 UTC, lewcc approved these changes

2024-02-06 03:01 UTC, merged