Cyborgs can now choose what type of brain they spawn with.
ParadiseSS13/Paradise pull request #23954
Opened 2024-01-27 05:01 UTC by BiancaWilkson

## What Does This PR Do

This PR adds a new section to character creation, allowing players to choose whether their borg will spawn in with an MMI, a robobrain, or with a positronic brain. It also adds a new column to the SQL database for storing this info.
## Why It's Good For The Game

It adds more options for character customization for a role that is already very difficult to customize a character for.
## Testing

Spawned in with all different types of borg, and gibbed them to make sure the brains were correct. I don't have SQL database set up myself, so I was unfortunately not able to test if the queries work properly. Advice is appreciated.
## Changelog
:cl:
add: Character creation now lets you choose what type of brain a cyborg will spawn with.
/:cl:

2024-01-27 11:23 UTC, 1080pCat commented
this'd probably fix/close https://github.com/ParadiseSS13/Paradise/issues/23582

2024-01-27 11:49 UTC, Fordoxia commented
Whilst you're rooting around in that dark corner of the code, might you also add an option to set cyborg flavour text in the creator (rather than having to manually set it with the verb every round)?

2024-01-27 13:18 UTC, DGamerL commented
> Whilst you're rooting around in that dark corner of the code, might you also add an option to set cyborg flavour text in the creator (rather than having to manually set it with the verb every round)?

Very out of scope

2024-01-28 14:42 UTC, DGamerL requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/3939e120-3e4a-48f8-b214-938330e5ddc2)

2024-01-28 17:19 UTC, AffectedArc07 requested changes

2024-01-28 17:19 UTC, AffectedArc07 commented on SQL/updates/53-54.sql
> +	ADD COLUMN 'cyborg_brain_type' VARCHAR(11) NOT NULL DEFAULT 'MMI' AFTER 'height';
```suggestion
ALTER TABLE `characters`
	ADD COLUMN `cyborg_brain_type` VARCHAR(11) NOT NULL DEFAULT 'MMI' AFTER `height`;
```

2024-01-29 23:08 UTC, AffectedArc07 requested changes
Also you need to bump `#define SQL_VERSION` and the default version in the config.

2024-02-17 19:07 UTC, lewcc reviewed
Little things, mostly looks good!

2024-03-12 10:19 UTC, AffectedArc07 requested changes

2024-03-12 10:19 UTC, AffectedArc07 commented on SQL/paradise_schema.sql
> +  `cyborg_brain_type` varchar(11) NOT NULL DEFAULT 'MMI',
Make this an enum in the DB for the 3 types, saves on disk space and parsing time.

2024-03-12 10:19 UTC, AffectedArc07 commented on code/_globalvars/lists/flavor_misc.dm
> +GLOBAL_LIST_INIT(borg_brain_choices, list(MMI_BORG, ROBOBRAIN_BORG, POSITRONIC_BORG))
Global protect this since it goes in the DB

2024-03-12 10:19 UTC, AffectedArc07 commented on code/modules/client/preference/character.dm
> +	cyborg_brain_type = sanitize_text(cyborg_brain_type, initial(cyborg_brain_type))
This should be a sanitize inlist so that it fails if the type from the DB isn't valid.

2024-03-23 16:50 UTC, AffectedArc07 approved these changes

2024-03-26 11:04 UTC, S34NW approved these changes
Approved, must wait for AA to merge as SQL and config changes required

2024-03-26 21:23 UTC, AffectedArc07 approved these changes
# FULL SEND

2024-03-26 21:23 UTC, merged

2024-03-26 21:24 UTC, AffectedArc07 commented on SQL/updates/53-54.sql
> +	ADD COLUMN `cyborg_brain_type` VARCHAR(11) NOT NULL DEFAULT 'MMI' AFTER `height`;
Oh fuck this should be the enum as well.

# FUCK IT FUTURE PR

2024-03-26 21:58 UTC, streather commented
probably nothing, but if you open the dialog to select what type of brain and hit cancel, it'll set it to no brain.

would it default to a braintype if that box is blank?

2024-03-27 01:24 UTC, Fordoxia commented
> probably nothing, but if you open the dialog to select what type of brain and hit cancel, it'll set it to no brain.
> 
> would it default to a braintype if that box is blank?

I'm pretty sure that even if no brain, there's a piece of code in robot_mob.dm that will give a brain to any borg that spawns without a brain because borgs without brains has happened before and is very bad.