Removes Toxin Damage from Drinking Blood in Virus Culture Bottles
ParadiseSS13/Paradise pull request #23968
Opened 2024-01-28 01:49 UTC by Arthri

## What Does This PR Do
- Tweaked `spawned_disease` to use `Vh Null` blood type instead of no blood type
- Added `Vh Null` as a safe donation blood type for all receiving blood types
- Tweaked Vampire to not gain nutrition from Vh Null blood

## Why It's Good For The Game
Makes virus culture bottles pure carriers of disease and removes the toxin damage from drinking from virus culture bottles

## Testing
Drank a bunch of virus culture bottles and checked the player didn't sustain any toxin damage

## Changelog
:cl: cdui
tweak: Blood from virus culture bottles no longer deal toxin damage
/:cl:

2024-01-28 01:54 UTC, Contrabang approved these changes

2024-01-28 02:34 UTC, GDNgit requested changes
Could you move the Vh Null blood type to a define?

2024-01-28 03:36 UTC, GDNgit commented on code/__DEFINES/reagents_defines.dm
> +// Like O- blood but doesn't contribute to blood_volume or vampire nutrition
```suggestion
/// Like O- blood but doesn't contribute to blood_volume or vampire nutrition
```
Just for autodoc

2024-01-31 17:26 UTC, Contrabang requested changes
Dismissing my approval, I'll review as soon as possible with the new changes

2024-02-22 20:14 UTC, Contrabang approved these changes

2024-03-01 23:22 UTC, S34NW approved these changes

2024-03-01 23:34 UTC, merged