refactor: remove multiple machinery global lists, use SSmachinery's machinery by type, use `all_areas` instead of `world` for all area iterations
ParadiseSS13/Paradise pull request #23997
Opened 2024-01-30 10:59 UTC by Gaxeer

## What Does This PR Do
- Replace `in world` to `in GLOB.all_areas` for area iterations
- Add 2 new lists to SSmachines: `all_machinery` and `machiney_by_type`. `machinery_by_type allows to more efficiently get subset of machinery.
- Replace `GLOB.machinery` with `get_machinery_of_type` calls, which will speed up iteration that were using whole machinery list, instead of subset.
- Remove:
    - GLOB.airlocks
    - GLOB.prisoncomputer_list
    - GLOB.navigation_computers
    - GLOB.apcs
    - GLOB.air_alarms
    - GLOB.power_monitors
    - GLOB.all_vent_pumps
    - GLOB.deliverybeacons

 And replace them with `get_machinery_of_type(specific_type)`

## Why It's Good For The Game
Good for coders, that won't need to create millions of global lists for specific machinery subtype.
Players won't notice, probably.

## Testing
Compiles, nothing special. I am too lazy to fix it locally, so we run Testmerge on downstream to catch runtimes.
Performance shouldn't change much, except cases where GLOB.machinery were used instead of subset. 
Maybe will benchmark later

## Changelog
Nothing player facing

2024-01-31 22:20 UTC, AffectedArc07 approved these changes
Approved what I own

2024-02-17 19:02 UTC, lewcc reviewed
Looks like this is creating some runtimes in CI, might be worth looking at (or re-running CI to see if it was ephemeral).

Also, if this goes in, it might be something worth adding to our contributor documentation since this looks like a good change to keep in mind down the line.

2024-02-17 22:45 UTC, DGamerL commented
> Looks like this is creating some runtimes in CI, might be worth looking at (or re-running CI to see if it was ephemeral).
> 
> Also, if this goes in, it might be something worth adding to our contributor documentation since this looks like a good change to keep in mind down the line.

It's failing CI because the science burn chamber is kinda fucked on Metastation, and this PR somehow kinda fixes the logic on that or something? Hopefully after #24156 is merged it'll pass CI

2024-03-01 13:43 UTC, Contrabang requested changes
Minor things I spotted, looks pretty good

2024-03-01 13:43 UTC, Contrabang commented on code/game/machinery/magnetic_module.dm
> -		// GLOB.machines is populated in /machinery/Initialize
This should still be mentioned, but have it say something like
```
The global machinery associated list is populated in /machinery/Initialize
```

2024-03-01 13:43 UTC, Contrabang commented on code/modules/mob/living/silicon/robot/drone/maint_drone.dm
> +		if(atoms_share_level(drone_fabricator, src))
```suggestion
		if(!atoms_share_level(drone_fabricator, src))
```

2024-03-10 20:45 UTC, Gaxeer commented
> Looks like this is creating some runtimes in CI, might be worth looking at (or re-running CI to see if it was ephemeral).
> 
> Also, if this goes in, it might be something worth adding to our contributor documentation since this looks like a good change to keep in mind down the line.

Will add it tomorrow and finish this stuff

2024-03-20 20:20 UTC, Contrabang commented
Any updates on this?

2024-03-24 18:31 UTC, closed without merging

2024-03-24 18:33 UTC, Contrabang commented
🫡