[BORG UPDATE] cyborg storage upgrade
ParadiseSS13/Paradise pull request #24018
Opened 2024-01-31 16:48 UTC by PhantornRU

## What Does This PR Do

Port of the refactor and new tools from "SS220 WyccStation".
We played with these changes for 2 years and don’t touch them anymore, since we fully tested them for balance, usability and user response. We hope you will like them too and improve the gameplay of robots.

- Improved ability to carry more materials via upgrade.

## Why It's Good For The Game

Late game unit development.

## Images of changes

![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/41e7d797-c0a4-44af-aa00-0164cc9d763c)

## Testing

Tested for 2 years on the SS220 WyccStation on live servers.

## Changelog
:cl:
add: Added Cyborg storage upgrade
/:cl:

2024-01-31 18:46 UTC, matttheficus commented
Does this simply allow them to "charge up" more metal/glass when theyre in a recharger?

If so, we're likely looking to move EngiBorgs toward requiring to resupply at an ORM, so with that in mind, not really a fan of giving them MORE metal for "free".

2024-01-31 18:54 UTC, matttheficus commented
#23944 is the direction I'm referring to.

2024-03-01 13:57 UTC, S34NW commented
Although this has passed the threshold for closure with 3 Balance objections and nobody in favour, objection reasons indicate that the problem areas are mitigated by changes following https://github.com/ParadiseSS13/Paradise/pull/23944.
As such this PR will stay open beyond the usual threshold to allow Balance to re-review once https://github.com/ParadiseSS13/Paradise/pull/23944 is merged.

We will reach out to you when this is the case for further discussion.

2024-03-14 19:44 UTC, Henri215 commented on code/modules/research/designs/mechfabricator_designs.dm
> +	materials = list(MAT_METAL=15000, MAT_BLUESPACE=2000, MAT_SILVER=6000)
```suggestion
	materials = list(MAT_METAL = 15000, MAT_BLUESPACE = 2000, MAT_SILVER = 6000)
```

2024-03-14 19:44 UTC, Henri215 commented on code/game/objects/items/robot/robot_upgrades.dm
> +	var/recharge_rate_multiplication = 2
autodoc these

2024-03-14 19:44 UTC, Henri215 commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Improves cyborg storage with bluespace technology."
Improves how? The description could be expande

2024-03-14 20:16 UTC, DGamerL requested changes
Please do a merge master, it has a stealth conflict

2024-03-24 18:30 UTC, SteelSlayer commented
Author does not have time to work on this at the moment. Closing for now.

![image](https://github.com/ParadiseSS13/Paradise/assets/42044220/b74f0a44-2ced-47cf-8915-28143d9d5714)

2024-03-24 18:30 UTC, closed without merging