Pepper Spray update
ParadiseSS13/Paradise pull request #24033
Opened 2024-02-01 16:33 UTC by HMBGERDO

## What Does This PR Do

This PR changes reagent effects
It doesnt check mask existance anymore
It checks for internals on or off

If it hits target with eyes not covered, it will do those effects:
0.5 seconds stun
20 seconds blurry eye
8 seconds blind

If it hits target with internals off, it will apply refreshable status effect with those effects:
lasts 10 seconds

on_apply(first hit):
12 seconds confused
4 seconds slowed
40 stamina damage

on_refresh(second and more hits until status effect is applied):
12 seconds confused
4 seconds slowed
20 stamina damage

## Why It's Good For The Game

Currently pepper spray is either completely useless or completely OP weapon. You either stunlock target in first hit or cant do anything to them. This design is bad. 
Im trying to make it useful in most situations here, so those are changes.
Discussed those with two balance guys.

## Testing

Compiled, used pepper spray on self, on other man, checked that it works as intended

## Changelog
:cl:
tweak: Pepper spray hitting eyes now stuns for 0.5 seconds, blinds for 8 seconds and blurs for 20 seconds. If target has no internals on, that will do 40 stamina damage, 4 seconds slowed and 12 seconds confused. Hitting one target twice will make second stamina damage 20 instead of 40.
/:cl:

2024-02-01 16:37 UTC, DGamerL commented on code/datums/status_effects/debuffs.dm
> +	to_chat(owner, "<span class='danger'>You inhale pepper spray!</span>")
```suggestion
	to_chat(owner, "<span class='danger'>Your throat burns!</span>")
```
Seems a bit more what you'd feel, in my opinion

2024-02-01 16:37 UTC, DGamerL commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
>  			var/eyes_covered = 0
```suggestion
			var/eyes_covered = FALSE
```

2024-02-01 16:37 UTC, DGamerL commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
>  				eyes_covered = 1
```suggestion
				eyes_covered = TRUE
				safe_thing = victim.wear_mask
			if(victim.head && victim.head.flags_cover & MASKCOVERSEYES)
				eyes_covered = TRUE
				safe_thing = victim.head
			if(victim.glasses)
				eyes_covered = TRUE
```

2024-02-01 17:35 UTC, HMBGERDO commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +				to_chat(victim, "<span class='bolddanger'>Your eyes burns!</span>")
```suggestion
				to_chat(victim, "<span class='danger'>Your eyes burns!</span>")
```

2024-02-01 19:02 UTC, Contrabang requested changes

2024-02-01 19:02 UTC, Contrabang commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +			if(eyes_covered && victim.internal)
Please mention in the changelog too, that having a mask no longer counteracts pepperspray

2024-02-05 01:58 UTC, Rurik123 commented
After seeing this in action against masked victims, I'll say I don't think internals requirement is for the better. Chaining into a quick baton hit for an immediate stun on anyone who doesn't have a tank on feels terrible.

I'd prefer it to be a mask check instead of an internals check. Gasmasks and such blocking it, things like cigs or the fake mustache not it.

2024-02-28 13:22 UTC, HMBGERDO commented
alright, reverted internals check, it now checks mask as before. 
not exactly what i wanted but still better than hard stun for 6 seconds.

2024-03-01 19:55 UTC, S34NW approved these changes

2024-03-01 19:56 UTC, merged

2024-03-03 00:54 UTC, Dafrek commented
The effects of pepper spray currently seem to go through modsuits (doesn't protect mouth or eyes) and sunglasses, (doesnt protect eyes) is this intended?

2024-03-03 11:22 UTC, HMBGERDO commented
fixed here https://github.com/ParadiseSS13/Paradise/pull/24403
thanks for report