Multi-tile doors fix
ParadiseSS13/Paradise pull request #24113
Opened 2024-02-08 18:02 UTC by MrRomainzZ

## What Does This PR Do
Fixes #23392 and removes "custom" pod door function by adapting 
https://github.com/Baystation12/Baystation12/commit/7e6cd000e7750b749fd217198d5075ef707cf24a
to us

## Why It's Good For The Game
Bug fix + possible multi-tile doors support (?)

## Images of changes
https://youtu.be/EvNVM94Eg_o

## Testing
Localhost

## Changelog
:cl:
tweak: Replaced pod door opacity code with new solution
fix: Fixed issue with "glassless" multi-tile doors
/:cl:

2024-02-08 19:17 UTC, MrRomainzZ commented
Also can remove `dir = EAST` in airlock_types.dm to fix admin spawned multi-tile airlocks 
(after you click spawn it creates a door with `dir = EAST` and puts filler on the east but then rotates the door to south, leaving filler in the air)
```
/obj/machinery/door/airlock/multi_tile
	name = "large airlock"
	dir = EAST <-
	width = 2
	icon = 'icons/obj/doors/airlocks/glass_large/glass_large.dmi'
	overlays_file = 'icons/obj/doors/airlocks/glass_large/overlays.dmi'
	note_overlay_file = 'icons/obj/doors/airlocks/glass_large/overlays.dmi'
	assemblytype = /obj/structure/door_assembly/multi_tile
	paintable = FALSE
```

2024-03-06 15:00 UTC, S34NW requested changes
Just a minor thing

2024-03-06 15:00 UTC, S34NW commented on code/game/machinery/doors/door.dm
> +/obj/machinery/door/proc/update_bounds()
If the door somehow moves this is going to cause issues as we don't reset the contents of `fillers` before adding to it. As such, please do a loop to delete all the contents of the `fillers` list and remove them from the list.

2024-03-18 18:36 UTC, S34NW approved these changes

2024-03-18 18:55 UTC, merged