Fixes Cyberiad Issues
ParadiseSS13/Paradise pull request #24131
Opened 2024-02-09 19:33 UTC by Fluffyzack21

## What Does This PR Do
 Fixes major on mapping issues that we forgot

 Fixes #23319 

## Why It's Good For The Game
 fixes most of the issues on box station

## Images of changes
 still getting worked on

## Testing
 Still getting worked on

## Changelog
:cl:
add: new area for the courtroom on NSS cyberid
:cl:

2024-02-15 02:03 UTC, warriorstar-orion requested changes
You need to put the forward slash back in front of the second :cl: icon, so it looks like "/:cl:".

I know hallways are listed in the bug as areas missing light switches but we don't use light switches in hallways. The contribution guide specifies that every _room_ needs a lightswitch, and hallways aren't rooms in that sense.

Also, I know the map has a lot of existing instances of multiple bumps being on the same wall, like lights next to air alarms, or doors colliding with bumps, like firelocks and cameras, but we're trying to discourage that and should probably have contributor guidelines mentioning it specifically. Wherever you can, try and avoid it.

I'm not entirely sure we want a request console in every room, especially less trafficked or important ones like Garden, Tool Storage, Office Supplies and the like. @S34NW might be able to chime in here.

Arrivals:

![2024_02_14__20_57_29___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/7661ce14-d579-46c9-8e40-aca5781a5046)

- Don't put lights on glass. There's no explicit guideline for this, and I know we have a lot of pre-existing instances of it, but it's not something we want to continue doing.

- I know there's a lot of instances already on Box, but we want to avoid having wall bumps directly under firelocks and airlocks.

Auxilliary Tool Storage:

![2024_02_14__20_57_42___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/0e16991c-5541-4183-9434-094255e985d4)

- Move this request console to the bottom-right corner, next to the air alarm, to avoid placing it on the same wall as the light.

Port Primary Hallway:

![2024_02_14__20_54_35___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/5877711f-41ce-4a16-9fb4-4f7516e38a4a)

- I don't know if this was a merging error or what, but there are too many scrubbers and vents here, and they are too close together. The Port West Hallway only needs one of each, and the Port East Hallway only needs one of each.

Central West Primary Hallway:

![2024_02_14__20_57_47___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/200776ba-ebde-46a9-87e6-df52586a816b)

- Move either the wall bump or the light off of this wall.

Cargo Lobby:

![2024_02_14__20_57_53___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/d9c4f47b-45dd-47bb-ae10-8b4031738730)

- For the purposes of our guidelines, lobbies are public areas and extensions of the hallways, so shouldn't have lightswitches.

Delivery Office:

![2024_02_14__20_57_50___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/034b4e83-29ec-4e5b-842f-63425862c225)

- Move either the wall bump or the light off of this wall.

Brig Processing:

![2024_02_14__20_23_42__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/c4e5ddfd-7adc-49d8-b9de-f209a64e17f5)

![2024_02_14__20_58_29___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/b91c20ce-b336-438f-980b-c756b19f26f9)

- These two wallbumps will overlap each other when viewed from any angle in processing.
- The request console name is mispelled, there's an extra "c" in Processing.

Courtroom Gallery:

![2024_02_14__20_58_01___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/ba700559-73e6-459b-98cc-8245820bcc7a)

- There are two wallbumps and a light here, I know there's no only one more free wall left but could you move one of the bumps to south of the cola vendor?

Magistrate's Office:

![2024_02_14__21_01_49__Settings](https://github.com/ParadiseSS13/Paradise/assets/59303604/801383bd-f675-4906-9c14-28199c31b4ac)

- The request console is named "Courtroom Request Console".

Library:

- If we do take the route of adding more request consoles, the Library should probably have one.

AI Sat:

![2024_02_14__21_02_23___C__Users_warriorstar_Desktop_0-after xcf-1 0 (RGB color 8-bit gamma integer, GI](https://github.com/ParadiseSS13/Paradise/assets/59303604/2818a8b7-90ec-4124-98b7-e1e628d3bcfa)

- There's no need for a light switch in the AI turret hallway, and the one you've placed can't be reached without breaking electrified windows. If the AI wants to turn off those lights they can do so with the APC.

2024-02-15 02:53 UTC, Fluffyzack21 commented on code/game/area/ss13_areas/legal_areas.dm
> +/area/station/legal/Courtroom/gallery
fixed

2024-02-16 13:04 UTC, S34NW approved these changes
Looks fine enough, we still have some stacking of wall furniture but that is unavoidable due to space constraints. We also have a lot of new requests consoles, but I'm indifferent to those

2024-02-18 01:39 UTC, warriorstar-orion requested changes
The request console in the Magistrate's office is still named "Courtroom Requests Console. Otherwise the rest of the changes look good.

2024-02-18 11:28 UTC, Fluffyzack21 commented
> The request console in the Magistrate's office is still named "Courtroom Requests Console. Otherwise the rest of the changes look good.

fixed

2024-02-19 11:48 UTC, merged