Adds a global spark limit
ParadiseSS13/Paradise pull request #24197
Opened 2024-02-16 16:28 UTC by lewcc

## What Does This PR Do
Limits the total number of active spark effects to a high, yet hopefully reasonable, amount (500).

## Why It's Good For The Game
Sparks are *expensive*. We've had more than a few cases where spawning too many would have some pretty nasty consequences, so it'll be a good thing to put a bit of a cap on that.

## Testing
Broke all lights through the secrets tab, the spark limit was quickly exhausted (and it happened noticeably quicker).
Shot a few walls with a taser, noted that we still saw sparks.

## Changelog
:cl:
tweak: Added a global spark limit.
/:cl:

2024-02-16 16:42 UTC, Contrabang approved these changes
i like it (LGTM)

2024-02-16 16:53 UTC, DGamerL requested changes

2024-02-16 16:53 UTC, DGamerL commented on code/game/objects/effects/effect_system/effects_sparks.dm
> +	sparks.set_up(sparks_allowed, c, source)
Undefined var

2024-02-16 17:40 UTC, lewcc commented on code/game/objects/effects/effect_system/effects_sparks.dm
> +	sparks.set_up(sparks_allowed, c, source)
addressed

2024-02-17 00:08 UTC, DGamerL approved these changes

2024-02-17 08:17 UTC, meow20 commented
sad day for plasma flooded turrets in ai sat.

2024-02-17 14:19 UTC, S34NW approved these changes

2024-02-17 14:20 UTC, merged