Removes a couple of area's that are no longer being used
ParadiseSS13/Paradise pull request #24196
Opened 2024-02-16 15:52 UTC by Fluffyzack21

## What Does This PR Do
 Removed. couple of things, in service, medical, science, legal, security, and command

## Why It's Good For The Game
 Introduced back when we had the old map of all the stations

## Testing
Compiled

## Changelog
:cl:
NPFC
/:cl:

2024-02-16 18:45 UTC, DGamerL requested changes
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/e693a511-7a26-4b3d-a2ec-33174a9eb414)

Remove the emojis if you don't have a changelog.

2024-02-16 20:45 UTC, Fluffyzack21 commented
> ![image](https://private-user-images.githubusercontent.com/108773801/305526921-e693a511-7a26-4b3d-a2ec-33174a9eb414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMTY1NzksIm5iZiI6MTcwODExNjI3OSwicGF0aCI6Ii8xMDg3NzM4MDEvMzA1NTI2OTIxLWU2OTNhNTExLTdhMjYtNGIzZC1hMmVjLTMzMTc0YTllYjQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQyMDQ0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZlZjMyNWEwMjk3YmUyY2Q0NTUxYjk1YzdlZmM2ZDBhYjMwODUwZDFjMDE5ZDJhYjQ0ZmJiOWE5M2ZiMDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e0VRv1CB_m4kuPHjoociRSysghH11wRHWEZATf3RWI4)
> 
> Remove the emojis if you don't have a changelog.

fixed

2024-02-19 18:41 UTC, Henri215 approved these changes
LGTM

2024-02-19 19:05 UTC, S34NW approved these changes

2024-02-19 19:06 UTC, merged