Adds Hand Raising
ParadiseSS13/Paradise pull request #24223
Opened 2024-02-18 17:31 UTC by matttheficus

## What Does This PR Do
Pointing to a slapper in your hand now states:

`**John Doe** raises their hand!`

It still shows the slapper in the little point blurb that goes above your head, for added attention grabbing.

## Why It's Good For The Game
Little fluff things are nice.

## Testing
Pointed at my hand.

## Changelog
:cl:
add: Added the ability to raise your hand.
/:cl:

2024-02-18 17:33 UTC, Furrior commented
Don't like the code, but the idea is nice

2024-02-18 17:56 UTC, Christasmurf commented
![image](https://github.com/ParadiseSS13/Paradise/assets/25437893/6f800b5d-e421-4457-b924-ba68d14b3c91)

2024-02-18 20:37 UTC, Furrior commented
> ![image](https://private-user-images.githubusercontent.com/25437893/305735874-6f800b5d-e421-4457-b924-ba68d14b3c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODg5MjgsIm5iZiI6MTcwODI4ODYyOCwicGF0aCI6Ii8yNTQzNzg5My8zMDU3MzU4NzQtNmY4MDBiNWQtZTQyMS00NDU3LWI5MjQtYmE2OGQxNGIzYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDIwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzlkZjM0NDUxZTgzMDdhNjkyNTg1NmQ1YTM5YWM3NWNkNGI3YjEyZTA2OTcwZWI2N2JkMzc0MzNmYzQxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lel2C9MqvpJOYTtk9IOIW3Ra26F5HqCqLKuvlAQTghY)
![cooltext452578215788095](https://github.com/ParadiseSS13/Paradise/assets/68264134/5f75b26d-f39f-493d-b198-189a1fa3b5e1)

2024-02-24 18:07 UTC, Henri215 approved these changes

2024-02-27 23:36 UTC, lewcc reviewed
Personally I'm fine with the way this is done, but it's worth looking into a cleaner way to do it.

2024-02-27 23:36 UTC, lewcc commented on code/modules/mob/living/living.dm
> +		visible_message("<b>[src]</b> raises their hand!")
```suggestion
		visible_message("<b>[src]</b> raises [p_their()] hand!")
```

2024-03-21 01:08 UTC, Contrabang requested changes

2024-03-21 01:08 UTC, Contrabang commented on code/modules/mob/living/living.dm
> +	if(istype(hand_item, /obj/item/slapper))
Assuming you only want it to happen while the slapper is in your active hand while you point to it, and not just any time you're holding a slapper as your active hand and you point
```suggestion
	if(istype(hand_item, /obj/item/slapper) && hand_item == A)
```

2024-03-24 16:35 UTC, Contrabang commented on code/modules/mob/living/living.dm
> +		visible_message("<b>[src]</b> points to [pointed_object]")
```suggestion
	visible_message("<b>[src]</b> points to [pointed_object]")
```

2024-03-24 16:41 UTC, Contrabang approved these changes
LGTM

2024-03-24 18:08 UTC, Henri215 approved these changes

2024-03-24 18:14 UTC, merged