Fixes cigars being lightable by everything
ParadiseSS13/Paradise pull request #24235
Opened 2024-02-19 16:30 UTC by DGamerL

## What Does This PR Do
Makes cigars not being lit by everything
Resolves #24219

## Why It's Good For The Game
Cigars can only be lit by civilized means.

## Testing
Couldn't light a cigar with a cheap ligher, could with a zippo

## Changelog
:cl:
fix: Fixed cigars being lightable by everything that emitted heat
/:cl:

2024-02-19 16:53 UTC, Contrabang requested changes

2024-02-19 16:53 UTC, Contrabang commented on code/game/objects/items/weapons/cigs.dm
> +		return COMPONENT_CANCEL_ATTACK_CHAIN
```suggestion
	if(can_light_cigar(lighting_item))
		return ..()
```

2024-02-19 16:53 UTC, Contrabang commented on code/game/objects/items/weapons/cigs.dm
> +	return FALSE
```suggestion
	return (istype(lighting_item, /obj/item/match) || istype(lighting_item, /obj/item/lighter/zippo))
```

2024-02-20 17:46 UTC, Contrabang approved these changes

2024-02-20 17:47 UTC, Contrabang requested changes

2024-02-20 17:47 UTC, Contrabang commented on code/game/objects/items/weapons/cigs.dm
> +
Actually, do we want to do this too?
```suggestion
	if(can_light_cigar(lighting_item))
		return ..()
	if(lighting_item.get_heat())
		to_chat(user, "<span class='notice'>[src] straight out REFUSES to be lit by such uncivilized means.</span>")
```

2024-02-20 21:32 UTC, Contrabang approved these changes
lgtm

2024-02-21 09:04 UTC, S34NW approved these changes

2024-02-21 09:04 UTC, merged