Datumizes spells
ParadiseSS13/Paradise pull request #24242
Opened 2024-02-19 20:53 UTC by GDNgit

## What Does This PR Do
Datumizes spells. Spells are no longer objects and are now datums. Fixes a bunch of niche issues with spells. Most of this was just done through regex replace. Removes some spell types that didn't need to exist.

## Why It's Good For The Game
Memory optimization, function holders should just be datums

## Testing
Tested alien spells, vampire spells, and some wizard spells that were changed
## Changelog
:cl:
fix: Bloodcrawl consistently makes a chat message when used
fix: Night cloak now mentions if it's activated or not
/:cl:

2024-03-21 17:21 UTC, Contrabang requested changes
This took me like a good 1.5 hours.

Somethings I spotted, and hopefully we can put this on a short TM after TG action buttons

2024-03-21 17:22 UTC, GDNgit commented on code/datums/spells/alien_spells/build_resin_structure.dm
> +									"Resin door (80)" = image(icon = 'icons/obj/smooth_structures/alien/resin_door.dmi', icon_state = "resin"))
merge conflict gaming

2024-03-21 17:23 UTC, GDNgit commented on code/datums/spells/alien_spells/transfer_plasma.dm
> +/datum/spell/alien_spell/transfer_plasma/create_new_targeting()
Other way around actually!

2024-03-21 17:23 UTC, GDNgit commented on code/datums/spells/alien_spells/transfer_plasma.dm
> +/datum/spell/touch/alien_spell/transfer_plasma
```suggestion
/datum/spell/alien_spell/transfer_plasma
```

2024-03-24 17:09 UTC, Contrabang approved these changes
lgtm, TM time

2024-03-29 09:47 UTC, AffectedArc07 approved these changes
Approved unit test

2024-03-30 11:07 UTC, Burzah requested changes
Some minor stuff, and a _bit_ of the classic 'while we are here' as well.

2024-03-30 11:07 UTC, Burzah commented on code/modules/awaymissions/mission_code/ruins/wizardcrash.dm
>  	info = "To the Magnificent Z.A.P.<BR>A small mining base has been created within our territory by wandless scum. Send them a message from the wizard federation they will not forget. I know your kind
```suggestion
	info = "To the Magnificent Z.A.P.<br>A small mining base has been created within our territory by wandless scum. Send them a message from the wizard federation they will not forget. I know your kind is rather fragile, but a group of lightly armed miners should not pose any threat to you at all. Just be warned they have a security cyborg for self defence, you might want to tune your spells to that threat. I look forward to hearing of your success.<br>Grand Magus Abra the Wonderous"
```

2024-03-30 11:07 UTC, Burzah commented on code/modules/mob/living/carbon/superheroes.dm
>  	selection_activated_message		= "<span class='notice'>You start preparing a mindblowing monologue. <B>Left-click to cast at a target!</B></span>"
```suggestion
	selection_activated_message		= "<span class='notice'>You start preparing a mindblowing monologue. <b>Left-click to cast at a target!</b></span>"
```

2024-03-30 11:07 UTC, Burzah commented on code/modules/research/xenobiology/xenobiology.dm
>  	playsound(get_turf(src), 'sound/magic/timeparadox2.ogg', 100, 1, -1)
```suggestion
	playsound(get_turf(src), 'sound/magic/timeparadox2.ogg', 100, TRUE, -1)
```

2024-03-30 18:36 UTC, GDNgit commented on code/datums/spell_handler/alien_spell_handler.dm
>  		return 0
I actually got shit for doing this in the original PR because this is technically a numerical return value lmao, time to finally get rid of this

2024-03-31 07:24 UTC, Burzah approved these changes

2024-04-01 07:45 UTC, merged