Photos can be burnt with hot items
ParadiseSS13/Paradise pull request #24257
Opened 2024-02-21 05:08 UTC by cybercapitalism

## What Does This PR Do

Makes photos able to be burnt with any hot/lit item (i.e. flare, welder, cigarette).

## Why It's Good For The Game

I think that a 2000 C welding torch should probably be able to make a polaroid burn.

## Testing

Burnt photos with lighters, things that were hot but not lighters, and verified that these things do not burn photos if they are not hot.

## Changelog
:cl: Chuga
tweak: Photos can now be burnt with any lit item
/:cl:

2024-02-21 11:13 UTC, CinnamonSnowball requested changes
Begone, useless text macro

2024-02-21 11:13 UTC, CinnamonSnowball commented on code/modules/paperwork/photography.dm
> +	user.visible_message("[class][user] holds \the [P] up to \the [src], it looks like [user.p_theyre()] trying to burn it!</span>", \
```suggestion
	user.visible_message("[class][user] holds [P] up to [src], it looks like [user.p_theyre()] trying to burn it!</span>", \
```

2024-02-21 11:13 UTC, CinnamonSnowball commented on code/modules/paperwork/photography.dm
> +			"[class]You burn right through \the [src], turning it to ash. It flutters through the air before settling on the floor in a heap.</span>")
```suggestion
			user.visible_message("[class][user] burns right through [src], turning it to ash. It flutters through the air before settling on the floor in a heap.</span>", \
			"[class]You burn right through [src], turning it to ash. It flutters through the air before settling on the floor in a heap.</span>")
```

2024-02-21 11:13 UTC, CinnamonSnowball commented on code/modules/paperwork/photography.dm
> +			to_chat(user, "<span class='warning'>You must hold \the [P] steady to burn \the [src].</span>")
```suggestion
			to_chat(user, "<span class='warning'>You must hold [P] steady to burn [src].</span>")
```

2024-02-21 13:31 UTC, DGamerL commented on code/modules/paperwork/photography.dm
> +			to_chat(user, "<span class='warning'>You must hold \the [P] steady to burn \the [src].</span>")
Make this an early return please

2024-02-21 22:51 UTC, DGamerL approved these changes

2024-02-21 22:51 UTC, DGamerL commented on code/modules/paperwork/photography.dm
```suggestion
```

2024-02-26 17:05 UTC, DGamerL approved these changes

2024-02-27 22:20 UTC, lewcc commented on code/modules/paperwork/photography.dm
> +	user.visible_message("[class][user] holds [P] up to [src], it looks like [user.p_theyre()] trying to burn it!</span>", \
Can you change this to only store the actual class name itself in the var, instead of lugging around the whole span declaration?

2024-03-01 12:39 UTC, S34NW approved these changes

2024-03-01 12:39 UTC, merged