Revival nests description updated, heals hivenoded humans
ParadiseSS13/Paradise pull request #24299
Opened 2024-02-24 19:57 UTC by Qwertytoforty

## What Does This PR Do

Removes outdated line about them turning humans into eggs.
No longer hurts humans in it, since that is pointless and did not work on huggered people.
Heals humans with hivenodes, will not revive them.
Non hivenoded can not get in it or unbuckle people.

## Why It's Good For The Game

Descriptions being accurate is good.
Hivenoded being able to use xeno structures is good, but we don't need humans reviving from death with it.
No point in a damaging function when it only works on unhugged crew, or dead crew. You want to hugger crew before killing them, and there is no point in damaging a dead body.

## Testing

Buckled / unbuckled hivenoded alien
Buckled a human with hivenode.
Unbuckled alien with hivenode
unbuckled human with hivenode, etc

## Changelog
:cl:
tweak: Revival nest no longer mentions it being able to turn people into eggs.
tweak: Revival nests now heal anyone with a hivenode
tweak: Revival nests no longer hurt humans inside of them, people without hivenodes can no longer be put in

/:cl:

2024-02-24 20:04 UTC, Contrabang requested changes

2024-02-24 20:04 UTC, Contrabang commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
>  			return
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/15eca039-46a8-4339-abc5-bd3676dec0ba)

2024-02-24 20:11 UTC, Contrabang approved these changes

2024-02-27 22:21 UTC, lewcc approved these changes

2024-02-27 22:21 UTC, merged