Fixes patch packs dont work
ParadiseSS13/Paradise pull request #24302
Opened 2024-02-24 23:03 UTC by Fluffyzack21

## What Does This PR Do
 Healing people is good with working patch packs,

 Fixes #24070 

## Why It's Good For The Game
You can now heal your fellow crew with working patch pads

## Testing
Harmed a vox and healed them with patch packs

## Changelog
:cl:
tweak: Patch pads now heal your hurting crew
/:cl:

2024-02-25 02:55 UTC, DGamerL requested changes
Change your Changelog to this:
fix: Patch packs can now apply patches again

2024-02-25 04:01 UTC, Fluffyzack21 commented
> Change your Changelog to this: fix: Patch packs can now apply patches again

fixed

2024-02-25 04:47 UTC, 1080pCat approved these changes
>Harmed a vox and healed them with patch packs 

:'(

2024-02-25 04:59 UTC, Fluffyzack21 commented
> > Harmed a vox and healed them with patch packs
> 
> :'(

Now its a skrell

2024-02-27 23:27 UTC, lewcc approved these changes

2024-02-27 23:28 UTC, merged