Fixes runtime adding/editing laws in law manager
ParadiseSS13/Paradise pull request #24331
Opened 2024-02-26 14:34 UTC by Adrer

## What Does This PR Do
Fixes a bug where you would be unable to edit the text of laws in the law manager as a borg/AI/admin.

Fixes: #24314
Fixes: #24292

## Why It's Good For The Game
Runtime bad.

## Testing
Be an emagged borg.
Edit a law and add it, it works.

## Changelog
:cl:
fix: Law manager can once again edit and add laws properly.
/:cl:

2024-02-26 14:35 UTC, GDNgit approved these changes
[oh yeah woo yeah oh yeah woo t](https://www.youtube.com/watch?v=6a-tnmyXjAE)

2024-02-26 14:37 UTC, Contrabang requested changes
These should all be ui.user, which you need to pull from `ui_act(action, list/params, datum/tgui/ui)

2024-02-26 14:37 UTC, Contrabang commented on code/modules/tgui/modules/law_manager.dm
> +			var/new_law = tgui_input_text(usr, "Enter new law Zero. Leaving the field blank will cancel the edit.", "Edit Law", zeroth_law)
```suggestion
			var/new_law = tgui_input_text(ui.user, "Enter new law Zero. Leaving the field blank will cancel the edit.", "Edit Law", zeroth_law)
```

2024-02-26 14:54 UTC, Contrabang approved these changes
lgtm

2024-02-27 22:26 UTC, lewcc approved these changes
LGTM

2024-02-27 22:26 UTC, merged