makes it clear that central command has called the shuttle when cance…
ParadiseSS13/Paradise pull request #24355
Opened 2024-02-28 09:17 UTC by Code-Lyoko0

## What Does This PR Do
Adds a check to see if the Cancel Shuttle is used from the admin panel, and displays "Shuttle has been recalled by Central Command." to the recall announcement. 

## Why It's Good For The Game
It should be clear to the crew that the shuttle was recalled by Central Command, as before the only way to know is to know it did not show a signal traced message, this could lead to confusion from the crew that the shuttle was recalled by the captain.

## Images of changes

![recall](https://github.com/ParadiseSS13/Paradise/assets/13879982/a7f221b5-c2cd-4008-af1c-5eaf3e8cd3c1)

## Testing
Joined as Captain, Called the Shuttle, Recalled with Admin Verb, "shuttle has been recalled by Central Command" message shown, called the shuttle again, recalled as Captain, "Recall has been traced" message shown.

## Changelog
:cl:
tweak: Made it clearer that Central Command had recalled the shuttle.
/:cl:

2024-02-28 10:53 UTC, Furrior commented on code/modules/shuttle/emergency.dm
> +/obj/docking_port/mobile/emergency/cancel(area/signalOrigin, byCC)
```suggestion
/obj/docking_port/mobile/emergency/cancel(area/signalOrigin, byCC = FALSE)
```

2024-02-28 10:53 UTC, Furrior commented on code/controllers/subsystem/SSshuttles.dm
> +		emergency.cancel(get_area(user), FALSE)
```suggestion
		emergency.cancel(get_area(user))
```

2024-02-28 10:53 UTC, Furrior commented on code/modules/admin/topic.dm
>  						message_admins("<span class='adminnotice'>[key_name_admin(usr)] called the Emergency Shuttle to the station</span>")
Move
`
SSshuttle.emergency.cancel(null, TRUE)
`
before the switch statement

2024-02-28 11:50 UTC, DGamerL commented on code/modules/shuttle/emergency.dm
> +		"The emergency shuttle has been recalled.[byCC ? " Shuttle has been recalled by Central Command." : SSshuttle.emergencyLastCallLoc ? " Recall signal traced. Results can be viewed on any communicati
```suggestion
		"The emergency shuttle has been recalled[byCC ? " by Central Command." : SSshuttle.emergencyLastCallLoc ? ". Recall signal traced. Results can be viewed on any communications console." : "." ]",
```
Test this first, but this should make the sentence look a bit more natural

2024-02-29 03:27 UTC, DGamerL requested changes
Please change all mentions of `cancel(null, TRUE)` to `cancel(byCC = TRUE)`

2024-03-11 18:28 UTC, lewcc approved these changes

2024-03-11 18:28 UTC, merged