Fix syringe being sharp
ParadiseSS13/Paradise pull request #24388
Opened 2024-03-02 15:34 UTC by m-dzianishchyts

## What Does This PR Do
Syringe should be stopped being sharp.

## Why It's Good For The Game
 No more tomato slices and goat butchering.

## Testing
Syringe seems to be still functional but can no longer cut things.

## Changelog
:cl: Maxiemar
tweak: Syringe can no longer be used as a knife
/:cl:

2024-03-02 17:07 UTC, Contrabang requested changes
This isn't really a fix, its more of a tweak. Its currently intended that syringes are sharp. Please change your changelog from a fix to a tweak.

2024-03-10 11:59 UTC, Henri215 approved these changes
LGTM

2024-03-10 16:54 UTC, Contrabang approved these changes

2024-03-10 18:05 UTC, S34NW approved these changes

2024-03-10 18:05 UTC, merged