Added an autoresponse system for mentorhelp, using the existing button.
ParadiseSS13/Paradise pull request #24384
Opened 2024-03-02 06:09 UTC by FunnyMan3595

## What Does This PR Do
Adds an autoresponse system to mentorhelp, directly equivalent to the adminhelp version, but with a different set of messages.  It uses the existing (AUTO) button.

## Why It's Good For The Game
Autoresponses are useful for mentors, too!

## Testing
Filed a mentor ticket.  Gave a couple autoresponses.
Filed an admin ticket.  Gave a couple autoresponses. 

## Changelog
:cl:
add: Mentors now have some canned responses for common mentorhelp situations.
/:cl:

2024-03-02 06:11 UTC, spacegeese commented
> you forgot the "experiment" response
HOLY SHIT HE FUCKING DID NOT

2024-03-02 06:29 UTC, spacegeese commented
![image](https://github.com/ParadiseSS13/Paradise/assets/136994596/6c0b4ebb-2128-4b34-87fd-13ac1e376475)
HRRNNGNNHH

2024-03-02 08:42 UTC, meow20 commented
It needs an autoresponse explaining how to evoluate as a blob without oxigen.

2024-03-02 12:05 UTC, Henri215 commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		"Clear Cache" = "To fix a blank screen, go to the 'Special Verbs' tab and press 'Reload UI Resources'. If that fails, clear your BYOND cache (instructions provided with 'Reload UI Resources'). If t
```suggestion
		"Clear Cache" = "To fix a blank screen, go to the 'Special Verbs' tab and press 'Reload UI Resources'. If that fails, clear your BYOND cache (instructions provided with 'Reload UI Resources'). If that still fails, please ask for help again, stating you have already done these steps.",
```

2024-03-02 12:05 UTC, Henri215 commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		"Experiment!" = "Experiment! Part of the joy of this game is trying out various things, and dealing with the consequences if/when they go horribly wrong.",
```suggestion
		"Experiment!" = "Experiment! Part of the joy of this game is trying out various things, and dealing with the consequences if/when they go horribly wrong."
```

2024-03-02 22:50 UTC, Henri215 commented on code/__DEFINES/tickets_defines.dm
> +#define TICKET_DUPLICATE_COOLDOWN 3000 // 5 minutes
Remember to adjust the comments above later

2024-03-02 23:53 UTC, FunnyMan3595 commented on code/__DEFINES/tickets_defines.dm
> +#define TICKET_DUPLICATE_COOLDOWN 3000 // 5 minutes
Done.

2024-03-11 18:24 UTC, lewcc reviewed
Little nits. Given the fact that this touches admin/mentor stuff, I would prefer to see it test-merged.

2024-03-11 18:24 UTC, lewcc commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		response_phrases["Exploit Report"] = "That sounds like it could be an exploit! To report it, please go to our <a href='[GLOB.configuration.url.exploit_url]'>Exploit Report page</a>. Then 'Start New
This should be moved to ahelps. We (as mentors) generally just want to convert exploit reports/suggestions to adminhelps, since there can be some other baggage coming along with them.

2024-03-11 18:24 UTC, lewcc commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +	var/sorted_responses = list()
Make this a static list that only needs to be populated (and sorted) once.

2024-03-11 18:24 UTC, lewcc commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +	to_chat_safe(returnClient(N), "<span class='[span_class]'>[key_name_hidden(C)] is autoresponding with: <span/> <span class='adminticketalt'>[response_phrases[message_key]]</span>")//for this we want
```suggestion
	to_chat_safe(returnClient(N), "<span class='[span_class]'>[key_name_hidden(C)] is autoresponding with:</span> <span class='adminticketalt'>[response_phrases[message_key]]</span>") //for this we want the full value of whatever key this is to tell the player so we do response_phrases[message_key]
```

2024-03-11 18:24 UTC, lewcc commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		response_phrases["New Bug"] = "That sounds like a bug! To report it, please go to our <a href='[GLOB.configuration.url.github_url]'>Github page</a>. Then go to 'Issues'. Then 'New Issue'. Then fill
```suggestion
		response_phrases["New Bug"] = "That sounds like a bug! To report it, please go to our <a href='[GLOB.configuration.url.github_url]'>Github page</a>. Then go to 'Issues', click 'New Issue', and fill out the report form. If the report would reveal current-round information, file it after the round ends."
```

2024-03-12 18:31 UTC, FunnyMan3595 commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +	var/sorted_responses = list()
Done for mentor and admin tickets both.

2024-03-19 06:46 UTC, Danchi299 commented
wonder if this is a good auto-response
![image](https://github.com/ParadiseSS13/Paradise/assets/20885860/d457bfda-8d47-4509-bed6-c6d7982eae01)
https://discord.com/channels/145533722026967040/185561440697057291/854412554323361834

2024-03-27 11:46 UTC, S34NW requested changes
Add the above message and this is good to go

2024-03-27 12:10 UTC, FunnyMan3595 commented
![image](https://github.com/ParadiseSS13/Paradise/assets/98381/7d2de91f-dc82-4347-80be-bc73b19133aa)

2024-04-01 07:49 UTC, S34NW approved these changes

2024-04-01 07:52 UTC, merged