Makes weeping angel blindness not affect other angels
ParadiseSS13/Paradise pull request #24385
Opened 2024-03-02 07:59 UTC by cybercapitalism

## What Does This PR Do

Slightly refactors the blindness spell and adds a check for other weeping angels. 

## Why It's Good For The Game

Being able to blind other angels during a wizard round that contains multiple angels is not very fun or intuitive.

## Testing

It selects the correct targets and blinds them.

## Changelog
:cl: Chuga
tweak: Weeping angels no longer blind other weeping angels
/:cl:

2024-03-02 17:02 UTC, Contrabang requested changes

2024-03-02 17:02 UTC, Contrabang commented on code/modules/mob/living/simple_animal/hostile/angel_statue.dm
> +	for(var/mob/living/M in orange(10, user))
Ideally, you keep this an AOE spell, and just iterate through targets, and just check at they're living, and not a weeping angel

2024-03-02 20:21 UTC, Contrabang requested changes

2024-03-02 20:21 UTC, Contrabang commented on code/modules/mob/living/simple_animal/hostile/angel_statue.dm
>  	return targeting
We have can have the above code give living targets direction by changing this code to be
```
	var/datum/spell_targeting/aoe/targeting = new()
	targeting.range = aoe_range
	targeting.allowed_type = /mob/living
	return targeting

2024-03-02 20:21 UTC, Contrabang commented on code/modules/mob/living/simple_animal/hostile/angel_statue.dm
> +	for(var/turf/T in targets)
and then we can just iterate through the targets as living

2024-03-03 01:36 UTC, Contrabang approved these changes

2024-03-10 18:04 UTC, S34NW approved these changes

2024-03-10 18:04 UTC, merged