fixes the error where chicks lose their custom name when growing into chickens
ParadiseSS13/Paradise pull request #24409
Opened 2024-03-03 17:25 UTC by Hollow1364781653786

## What Does This PR Do

Fixes #23778 
## Why It's Good For The Game

you can make funny names for chicks and NOT expect them to dissapear when they grow into chickens now!
## Images of changes

## Testing

2024-03-03 17:29 UTC, Contrabang requested changes

2024-03-03 17:29 UTC, Contrabang commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +			C.name = src.name
```suggestion
			if(name != initial(name)
				C.name = name
```

2024-03-03 17:55 UTC, Contrabang commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +			if(name != initial(name)
I forgot a second parenthesis
```suggestion
			if(name != initial(name))
```

2024-03-03 18:05 UTC, S34NW approved these changes

2024-03-04 02:45 UTC, DGamerL approved these changes

2024-03-04 02:45 UTC, Contrabang approved these changes

2024-03-06 13:22 UTC, merged