Bear update, part 2
ParadiseSS13/Paradise pull request #24506
Opened 2024-03-08 14:19 UTC by Henri215

## What Does This PR Do

* Adds the black, brown (as a proper mob now), polars bear and combat bear (icon added to Hudson bear). Bear pelt hats included.
* The space bear no longer changes icons depending if you are on space or not.
* Added a polar bear to the lavaland_biodome_winter.
* Changed the type of bear that would spawn on a few other places.

* The polar bear pelt hat is no longer a fluff item.

Sprites by @ATP-Engineer 
## Why It's Good For The Game

The brown bear was only an icon used for hallucinations, now hes a proper mob that can be used in other places.
More variation to the bears one can find is good, the pelt hats are also pretty cool and would be an desirable things for players to collect.

The Hudson bear and space bear could probably be added as enemies from space with the explorer redux PR that is currently open.
## Images of changes

![bearsss](https://github.com/ParadiseSS13/Paradise/assets/77684085/910e9aeb-c498-4512-b6a8-3eadecdcafe3)
![pelts](https://github.com/ParadiseSS13/Paradise/assets/77684085/6db36e54-46ec-4d44-b97c-9f07b8ac7072)
![onmob](https://github.com/ParadiseSS13/Paradise/assets/77684085/3e5cbe39-99a6-424b-a66b-1674169fb33b)

## Testing

- See images above
## Changelog
:cl: Henri215, ATP-Engineer
imageadd: Hudson, the bear now has a unique icon
add: Added the polar, black and brown bears into the game, pelt hats included
del: Space bears no longer change icons depending if they are on space or not
/:cl:

I could use suggestions for cool brown/black bear descriptions, maybe their pelts too.

2024-03-14 06:48 UTC, ATP-Engineer commented
will the polar bear attack the arctic guys in the biodome?

2024-03-18 17:58 UTC, S34NW approved these changes

2024-03-20 20:32 UTC, Contrabang requested changes

2024-03-20 20:32 UTC, Contrabang commented on code/modules/mob/living/simple_animal/hostile/bear.dm
> +	return 1	//No drifting in space for space bears!
```suggestion
	return TRUE	//No drifting in space for space bears!
```

2024-03-20 21:16 UTC, Contrabang commented
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/b840f566-f53b-4340-837c-4eee44e9e3da)

2024-03-20 21:18 UTC, Contrabang approved these changes
Lets do this

2024-03-20 21:33 UTC, Contrabang approved these changes

2024-03-20 21:36 UTC, merged