Blob Overminds can now ghost.
ParadiseSS13/Paradise pull request #24523
Opened 2024-03-09 16:48 UTC by PIerreLouisH

## What Does This PR Do
Blob Overminds can now ghost. Therefore Fixes #23549

## Why It's Good For The Game
Oversight fix gud

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/44984704/88076713-06ab-4094-be2e-d08c421959bb)

## Changelog
:cl:
fix: Blob Overminds can now ghost.
/:cl:

2024-03-09 19:28 UTC, Contrabang requested changes
making observers shouldnt be done manually, use ghostize instead

2024-03-09 19:28 UTC, Contrabang commented on code/modules/events/blob/overmind.dm
> +	src.ckey = null
```suggestion
	ghostize(FALSE)
```

2024-03-11 16:28 UTC, lewcc requested changes
The main `ghost()` verb is scoped under /mob/living, and this skips a few checks that we would probably like to be sure are accounted for (like respawnability). 

I think it'd be better if you were move the existing ghost verb up to `/mob`, and add overrides for the different mob types that wouldn't use the base type (such as `/mob/dead`, and `/mob/camera/aiEye`)?

2024-03-26 09:59 UTC, S34NW requested changes
PR is stale, please continue working on it or address any comments within 7 days or we will close the PR.

2024-04-03 01:08 UTC, closed without merging