Service borg tray no longer drap inventory version of items (stack count number)
ParadiseSS13/Paradise pull request #24521
Opened 2024-03-09 16:19 UTC by PIerreLouisH

What Does This PR Do
Service borg tray no longer drap inventory version of items.
Fixes #23825

## Why It's Good For The Game
Bug fix gud

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/44984704/e5fb0462-92ca-40f4-ae9e-30728e11a9a5)

## Changelog
:cl:
fix: Service borg tray no longer drap inventory version of items (stack count number)
/:cl:

2024-03-09 19:31 UTC, Contrabang requested changes

2024-03-09 19:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/bags.dm
> +			qdel(I) // Delete the old item
Deleting an item and replacing it with the same type is a terrible solution for this. This should use something like `remove_from_storage` to properly remove the maptext.

2024-03-19 16:45 UTC, Contrabang requested changes
These should be the correct changes, instead of making duplicate items, try this. Please make sure to test this also

2024-03-19 16:45 UTC, Contrabang commented on code/game/objects/items/weapons/storage/bags.dm
> +			var/obj/item/newItem = new I.type(dropspot)
```suggestion
			remove_from_storage(I)
```

2024-03-19 16:45 UTC, Contrabang commented on code/game/objects/items/weapons/storage/bags.dm
> +			remove_from_storage()
```suggestion
```

2024-03-19 16:45 UTC, Contrabang commented on code/game/objects/items/weapons/storage/bags.dm
> +							step(newItem, pick(NORTH,SOUTH,EAST,WEST))
```suggestion
						if(I)
							step(I, pick(NORTH,SOUTH,EAST,WEST))
```

2024-03-19 16:55 UTC, PIerreLouisH commented
> These should be the correct changes, instead of making duplicate items, try this. Please make sure to test this also

Thank you for your time. The code does work without error technically, but the sodas cans will be put on an odd location. Will fix soon with a new commit.

2024-03-26 10:00 UTC, S34NW commented
PR is stale, please continue working on it or address any comments within 7 days or we will close the PR.

2024-03-30 17:29 UTC, Contrabang approved these changes
LGTM

2024-04-03 14:35 UTC, merged