Ports the NTSS Raven from TG station. Slightly remaps delta escape / faragus escape
ParadiseSS13/Paradise pull request #24567
Opened 2024-03-11 18:54 UTC by Qwertytoforty

## What Does This PR Do

Ports the NTSS Raven from TG station. 4500 credits. Well defended with AI turrets, and shield generators. If you got a shuttle approved on biohazard, or cult summoning, this is the shuttle for you.

Lowers military shuttle cost / speed, to make it the cheaper version of this shuttle, since it is much less well defended.

Adds custom shield generators to the Raven, with 4 tile range instead of 2 tile.

Adjusts delta escape / viro to fit the raven, viro now has a toxin medkit and a pet mouse, to fill the extra space.

Faragus disposals moved farther out on east side so shuttle can be boarded from east side / doesnt crush it

## Why It's Good For The Game

More shuttle options are good. This option is very expencive, but still has a reasonable ammount of room, and is very well defended against biohazards, via shields or turrets.

Turrets will not fire through shields well. As such, crew will have to chose whichever is better to keep the ship safe!

## Images of changes

I'll post some in a moment.

## Testing

Ordered shuttle on each map, confirmed it could dock right.

## Changelog
:cl:
add: Added the NTSS Raven shuttle, a heavily armed and shielded shuttle, perfect for biohazards, simple mobs, and others!
tweak: Military shuttle is slower and cheaper now.
tweak: Tweaked delta virology and escape.
tweak: Tweaked faragus escape disposals
/:cl:

2024-03-12 12:47 UTC, 1080pCat requested changes
Delta:
Theres a random stray cable here (doors removed for visibility)
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/2493fbd9-065a-40ba-ac0c-2a47d5b04dd0)

Missing a cable in viro here
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/d02823c4-f19e-4278-ba1f-79c588af9125)

Stray pipes here
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/ddefe561-bdd7-434d-99ea-e8c4355f62a4)

Up here too
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/2ccf00f5-beae-4e28-90bf-4c3031e48897)

Faragus:
This isn't a space facing window, shouldn't be grilled
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/c98e7ab6-990d-483a-b91e-1ed62c505c06)

Raven:
Missing wall here
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/1c984bcf-84ae-40aa-aadd-78ef9a77478d)

These two tesla coils aren't anchored, and they'd probably be better as grounding rods imo
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/afa52441-617d-4c13-bf01-5d5042d0b8f5)

These crates could probably do with being the o2 ones, im not personally sure if the o2 ones already have contents however.
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/045ed9dc-5196-4697-a1d0-932eb03c26d6)
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/33383329-f016-43b7-9191-9d91dbc94515)
 
Do the docking side doors *really* need tiny fans?
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/489d40cf-d298-425b-a581-c2fde0c103bd)

Just a general suggestion, but for 4500 credits, maybe putting a blood bag crate in here would be a good idea?
![image](https://github.com/ParadiseSS13/Paradise/assets/96908085/abe24e74-17eb-414e-8aa7-7657ef7d489b)

2024-03-12 18:45 UTC, Kholdstare2 commented
For the medical section it would be less cluttered if the defib was inside a wall unit instead, behind the surgery table. Maybe a blood crate in its place?

2024-03-12 18:46 UTC, Qwertytoforty commented
> For the medical section it would be less cluttered if the defib was inside a wall unit instead, behind the surgery table. Maybe a blood crate in its place?

appologies, need to update the image, there is now a blood crate and medical vendor. Defib is on the table where the syringes are, though I may mount it to a wall, yes

2024-03-16 00:15 UTC, Henri215 reviewed
Took a look on the shuttle too, its looking good

2024-03-16 00:15 UTC, Henri215 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +/mob/living/simple_animal/mouse/brown/Brain/update_desc()
```suggestion
/mob/living/simple_animal/mouse/white/Brain/update_desc()
```

2024-03-19 17:54 UTC, Henri215 reviewed
Everything else is lewcing good

2024-03-19 17:54 UTC, Henri215 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	response_disarm = "gently pushes aside"
```suggestion
```
Inherited.
And do you think the response_harm should be better as "splats" or "stamps on"?

2024-03-19 17:54 UTC, Henri215 commented on code/modules/supply/supply_packs/pack_shuttle.dm
> +
```suggestion
```

2024-03-21 00:52 UTC, 1080pCat approved these changes
lookinnnn good!

2024-03-21 00:57 UTC, AyIong approved these changes
Look's Good To Henri

2024-03-21 01:57 UTC, Henri215 approved these changes
Looks good to Aylong

2024-03-21 21:21 UTC, Contrabang approved these changes

2024-03-21 21:25 UTC, merged