Made storage nesting better, improved consistency between storage types.
ParadiseSS13/Paradise pull request #24699
Opened 2024-03-19 23:39 UTC by FunnyMan3595

## What Does This PR Do
* Adds a new trait (applied to all storage objects by default) that causes Adjacent() to pass through them without decreasing its recursion limit.
* Stopped moving the internal bag of mod suits and the paradox bag around. It now stays in the object, and checks adjacency properly from there.
* Used Adjacent() a bit more consistently for checking if the storage object is in range.
* Made the storage UI close more reliably when the object or its parent moves away from you.
* Alt clicking works on paradox bags now.
* Observers can peer into suit storage, paradox bags, and modsuits sitting on the floor now.

## Why It's Good For The Game
It's nice to be able to see and interact deeply into nested storage.
Consistency good, hacky code bad.

## Testing
Put a pill bottle of happiness into my internals box, and moved it around between backpack, both halves of a paradox bag, and a modsuit, and ensured I could interact with each level of each root container whether it was on my back or on the ground.

Threw around all of the above and saw that their UIs closed properly.

Put some trash into trash bags on both kinds of janicart.

## Changelog
:cl:
fix: Made the storage UI close more reliably when the container moves away from you.
tweak: A mysterious force no longer prevents you from peering deeply into nested containers.
tweak: Alt clicking works on paradox bags now.
tweak: Observers can peer into suit storage, paradox bags, and modsuits sitting on the floor now.
/:cl:

2024-03-22 17:21 UTC, Daylight2 commented
Does this mean you can now, for example, look into and take stuff out of a pill bottle stored inside a medkit stored inside a backpack? If so, very nice.

2024-04-10 11:22 UTC, Burzah requested changes

2024-04-10 11:22 UTC, Burzah commented on code/_onclick/adjacent.dm
> +		if(T.Adjacent(neighbor,src)) return TRUE
```suggestion
		if(T.Adjacent(neighbor, src)) return TRUE
```

2024-04-10 11:22 UTC, Burzah commented on code/game/objects/items/weapons/storage/backpack.dm
>  		playsound(src.loc, "rustle", 50, 1, -5)
```suggestion
		playsound(src.loc, "rustle", 50, TRUE, -5)
```

2024-04-10 12:23 UTC, Burzah approved these changes

2024-04-10 18:59 UTC, lewcc approved these changes

2024-04-10 19:03 UTC, merged