Datumizes Wizards
ParadiseSS13/Paradise pull request #24702
Opened 2024-03-20 00:54 UTC by Contrabang

## What Does This PR Do

Datumizes wizards and apprentices. Yeah. Technically wizard constructs are apprentices now too.

## Why It's Good For The Game

Code quality.

## Images of changes

Wizard:
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/004b7da1-c860-45ab-9168-d25ffe952af0)

Wizard Apprentice:
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/3da62244-d92e-42f2-8349-8817d0e5f090)

Magic Construct: (Yes, I know it says apprentice as the role)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/d18a0840-4df0-42d1-aa05-485dc631db15)

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/ac39d56d-533f-4b45-9675-27e0360f34ed)

## Testing

2 clients, started the wizard game mode, summoned an apprentice. Killed a non-wizard to soulstone it, and made a wizard construct.
Used admin traitor panel stuff and it worked correctly also.

## Changelog
NPFC, I think.

2024-03-20 22:01 UTC, GDNgit requested changes
first batch

2024-03-20 22:01 UTC, GDNgit commented on code/modules/clothing/shoes/magboots.dm
> +	if(!user.mind.has_antag_datum(/datum/antagonist/wizard))
```suggestion
	if(!iswizard(user))
```

2024-03-20 22:08 UTC, Contrabang commented on code/game/gamemodes/wizard/wizard.dm
> +	// wizard.set_original_mob(wizard.current)
I forgot

2024-03-20 22:10 UTC, Contrabang commented on code/modules/admin/verbs/randomverbs.dm
> +			wizard.equip_wizard()
Admins have a button to fix it if they're a wizard, I'll just add an istype check

2024-03-20 22:12 UTC, Contrabang commented on code/modules/antagonists/wizard/datum_wiz_construct.dm
> +	i_have_mugwort = FALSE
It only really applies to non-apprentice wizards, since they actually have mugwort. I'll make it a proc.

2024-03-21 20:37 UTC, Contrabang commented on code/game/gamemodes/wizard/wizard.dm
> +				i++
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/b0b4006b-eb31-4898-8f1b-30fb786fc71a)

2024-03-21 21:01 UTC, merged