Makes RND and PDA servers quieter and not wall-penetrating
ParadiseSS13/Paradise pull request #24700
Opened 2024-03-19 23:45 UTC by Contrabang

## What Does This PR Do

I hate these things, they're so loud.
Turns their volume from 50 to 10, so its still there, but ACTUALLY ambience.

## Why It's Good For The Game

This is one of the loudest sounds in the game, for no reason. I can't stand being near these things with the volume this loud, and theres others that agree with me.

## Testing

Before

https://github.com/ParadiseSS13/Paradise/assets/91113370/bb8f9ee9-d64f-449f-8cc1-2c0383245f4c

After

https://github.com/ParadiseSS13/Paradise/assets/91113370/897c3724-0ec8-40a2-887e-55f8f15473b5

## Changelog
:cl:
tweak: RND and PDA servers are 80% quieter and no longer make noises through walls.
/:cl:

2024-03-20 00:33 UTC, Henri215 approved these changes

2024-03-20 13:49 UTC, Burzah requested changes

2024-03-20 13:49 UTC, Burzah commented on code/modules/research/message_server.dm
> +		playsound(loc, "computer_ambience", 10, 1, ignore_walls = FALSE)
```suggestion
		playsound(loc, "computer_ambience", 10, TRUE, ignore_walls = FALSE)
```

2024-03-20 13:49 UTC, Burzah commented on code/modules/research/server.dm
> +		playsound(loc, "computer_ambience", 10, 1, ignore_walls = FALSE)
```suggestion
		playsound(loc, "computer_ambience", 10, TRUE, ignore_walls = FALSE)
```

2024-03-20 22:15 UTC, Burzah approved these changes

2024-03-26 10:56 UTC, S34NW approved these changes

2024-03-26 11:05 UTC, merged