Adds the Alien Organ Extractor
ParadiseSS13/Paradise pull request #24737
Opened 2024-03-21 23:55 UTC by DGamerL

## What Does This PR Do
Adds the Alien Organ Extractor, purchaseable for abductors for 4 tokens.
Advantages:
- It doesn't deal damage to the person to be operated on
- It's significantly faster; 3 seconds on other people, 1 second on yourself
- You can put organs in it manually

Outstanding issues I'm fixing:
- [ ] It doesn't move the organ out of my hand
- [ ] It might not work, because I haven't tested with 2 clients yet
Also adds the price in tokens between brackets for the abductor console

## Why It's Good For The Game
Gives abductors a fancy new tool, to help with any mass abductions they might do

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/574705c6-5de9-4be4-9416-ecc6e8bb2c92)

I can't sprite so I just made it blue
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/e910e255-7d2f-4921-b0b9-cdd5ccfdcbbe)

## Testing

## Changelog
:cl:
add: Adds the Alien Organ Extractor
/:cl:

2024-03-22 00:09 UTC, Burzah requested changes

2024-03-22 00:09 UTC, Burzah commented on code/game/gamemodes/miniantags/abduction/machinery/console.dm
>  		dat += "<a href='?src=[UID()];dispense=tool'>Science Tool</A><br>"
```suggestion
		dat += "<a href='?src=[UID()];dispense=baton'>Advanced Baton (2)</a><br>"
		dat += "<a href='?src=[UID()];dispense=helmet'>Agent Helmet</a><br>"
		dat += "<a href='?src=[UID()];dispense=vest'>Agent Vest</a><br>"
		dat += "<a href='?src=[UID()];dispense=silencer'>Radio Silencer</a><br>"
		dat += "<a href='?src=[UID()];dispense=tool'>Science Tool</a><br>"
```

2024-03-22 00:09 UTC, Burzah commented on code/game/gamemodes/miniantags/abduction/machinery/console.dm
> +		dat += "<a href='?src=[UID()];dispense=organ_extractor'>Organ Extractor (2)</A><br>"
```suggestion
		dat += "<a href='?src=[UID()];dispense=mind_device'>Mental Interface Device (2)</a><br>"
		dat += "<a href='?src=[UID()];dispense=organ_extractor'>Organ Extractor (2)</a><br>"
```

2024-03-23 15:29 UTC, SchrodingersWolf commented
A bit concerned about this, especially the fact you can manually put organs in them - Wouldn't that allow abductors to give themselves multiple implants easily? (I know it is possible even now, but it is a longer process compared to 1 second.)

2024-03-23 19:09 UTC, DGamerL commented
> A bit concerned about this, especially the fact you can manually put organs in them - Wouldn't that allow abductors to give themselves multiple implants easily? (I know it is possible even now, but it is a longer process compared to 1 second.)

I rarely ever see abductors do this, and this really won't enable the strategy more. I see this as more of a faster sidegrade to doing normal surgery on humanoids

2024-03-26 02:43 UTC, Henri215 commented on code/modules/surgery/organs/organ_extractor.dm
> +	w_class = WEIGHT_CLASS_SMALL
```suggestion
```
That one too

2024-03-26 14:21 UTC, Henri215 approved these changes
Lewcs good to me

2024-04-12 18:34 UTC, S34NW approved these changes

2024-04-12 18:38 UTC, merged