Makes tesla movement pretty
ParadiseSS13/Paradise pull request #24786
Opened 2024-03-24 06:55 UTC by FunnyMan3595

## What Does This PR Do
Building off of #24736, I gave the tesla a "targeting beam" for its movement, and made it move rapidly along the beam.

## Why It's Good For The Game
Pretty stuff is pretty.

## Images of changes
https://github.com/ParadiseSS13/Paradise/assets/98381/fd8432d6-7fe2-4f39-ae02-7c99607a6c6b

## Testing
See video.

## Changelog
:cl:
tweak: When loose, the Tesla will now telegraph its movement and move smoothly along the telegraphed path.
/:cl:

2024-03-24 16:06 UTC, Contrabang commented on code/modules/mob/mob_movement.dm
> +
```suggestion
	if(istype(mover, /obj/singularity/energy_ball))
		dust()
	. = ..()

```

2024-04-23 22:11 UTC, GDNgit requested changes

2024-04-23 22:45 UTC, FunnyMan3595 commented on code/modules/mob/mob_movement.dm
> +
Bump doesn't trigger if the player is laying down, but Crossed does, so this is important.

Otherwise, done.

2024-04-23 23:03 UTC, Burzah commented on code/modules/power/engines/tesla/energy_ball.dm
> +		pre_corner_dist = abs(start.y - end.y)
Would it be feasible to calculate the absolute between the start and end positions once and just store and reuse that variable?

2024-04-23 23:26 UTC, Burzah commented on code/modules/power/engines/tesla/energy_ball.dm
> +		pre_corner_dist = abs(start.y - end.y)
Discussed via Discord. Resolving.

2024-04-23 23:33 UTC, Burzah approved these changes

2024-05-02 00:04 UTC, DGamerL approved these changes

2024-05-02 00:07 UTC, merged