Move default restart timeout to config
ParadiseSS13/Paradise pull request #24827
Opened 2024-03-26 18:34 UTC by m-dzianishchyts

## What Does This PR Do
Title says for itself.

## Why It's Good For The Game
Better configurability.

## Testing
Set `restart_timeout` to 75 in config, world rebooted after 75 seconds.
Set `restart_timeout` to 15 in config, world rebooted after 15 seconds.
Set `restart_timeout` to -10 in config, world rebooted after 0 seconds.
Removed `restart_timeout` from config, world rebooted after 75 seconds.

## Changelog
NPFC

2024-03-26 18:36 UTC, GDNgit commented on code/controllers/configuration/sections/general_configuration.dm
> +	var/restart_timeout = 75
probably would be for the best if this was a protected var as well
```suggestion
	/// Default timeout for world reboot. Measured in seconds
	var/restart_timeout = 75
```

2024-03-26 22:08 UTC, GDNgit requested changes

2024-03-26 22:08 UTC, GDNgit commented on code/controllers/configuration/sections/general_configuration.dm
> +	. = ..()
```suggestion
	return ..()
```
minor styling thing. After this you're good to go

2024-03-27 02:26 UTC, GDNgit approved these changes

2024-04-03 18:04 UTC, AffectedArc07 commented on code/controllers/configuration/sections/general_configuration.dm
> +	return ..()
Remove the protection, no need for it.

2024-04-03 18:18 UTC, AffectedArc07 approved these changes

2024-04-03 18:23 UTC, merged