Corrected a bunch of over-escaping.
ParadiseSS13/Paradise pull request #24876
Opened 2024-03-29 17:07 UTC by FunnyMan3595

## What Does This PR Do
1. Corrects a bunch of over-escaping that led to HTML code appearing in various places.
2. Permits ghosts and ghost bar occupants to use symbols banned from IC speech (e.g. >), with proper escaping.
3. Permits emotes to use symbols banned from IC speech (e.g. >), with proper escaping.

The only place that actually removed escaping entirely was the admin-only fax creation interface, because it had falsely claimed to allow HTML in its message. Happy to change the message instead if we're not comfortable with that.

Known limitation: The right click menu and alt-click view still show HTML escapes.

## Why It's Good For The Game
The over-escaping just looks ugly and makes it harder to read stuff.
Ghosts aren't IC and shouldn't be bound by IC rules.
Emotes aren't spoken, so there are reasonable uses for symbols that you can't speak, e.g. *makes a > with their hand."

## Testing
Went around typing `<br> don't` into a lot of different places, saw it come back as expected, without turning into actual HTML or being double-escaped.

## Changelog
:cl:
fix: Corrects a bunch of over-escaping that led to HTML code appearing in various places.
tweak: Permits ghosts and ghost bar occupants to use symbols banned from IC speech, e.g. >
tweak: Permits emotes to use symbols banned from IC speech, e.g. >
/:cl:

2024-03-30 10:02 UTC, 1080pCat commented
> Went around typing `<br> don't` into a lot of different places, saw it come back as expected, without turning into actual HTML or being double-escaped.

Just a heads up, _some_ html works in the telepathic messages, not `:^` on greys, but the actions they get.
Does this change that behavior at all? Because being able to telepathically bald and italicize text is rather nice to have

2024-03-30 10:20 UTC, FunnyMan3595 commented
> Just a heads up, _some_ html works in the telepathic messages, not `:^` on greys, but the actions they get. Does this change that behavior at all? Because being able to telepathically bald and italicize text is rather nice to have

Tested with [b] in greys' project mind, and it seems to work as expected.

2024-03-31 08:00 UTC, Burzah requested changes
Just some HTML tag fixes.

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/carbon/carbon_procs.dm
> +	<tr><td><B>Right Hand:</B></td><td><A href='?src=[UID()];item=[SLOT_HUD_RIGHT_HAND]'>[(r_hand && !(r_hand.flags&ABSTRACT)) ? r_hand : "<font color=grey>Empty</font>"]</A></td></tr>
```suggestion
	<tr><td><b>Left Hand:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_LEFT_HAND]'>[(l_hand && !(l_hand.flags&ABSTRACT)) ? l_hand : "<font color=grey>Empty</font>"]</a></td></tr>
	<tr><td><b>Right Hand:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_RIGHT_HAND]'>[(r_hand && !(r_hand.flags&ABSTRACT)) ? r_hand : "<font color=grey>Empty</font>"]</a></td></tr>
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/carbon/carbon_procs.dm
>  		dat += "&nbsp;<A href='?src=[UID()];internal=[SLOT_HUD_BACK]'>[internal ? "Disable Internals" : "Set Internals"]</A>"
```suggestion
	dat += "<tr><td><b>Back:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_BACK]'>[(back && !(back.flags&ABSTRACT)) ? back : "<font color=grey>Empty</font>"]</a>"
	if(istype(wear_mask, /obj/item/clothing/mask) && istype(back, /obj/item/tank))
		dat += "&nbsp;<a href='?src=[UID()];internal=[SLOT_HUD_BACK]'>[internal ? "Disable Internals" : "Set Internals"]</a>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/carbon/carbon_procs.dm
> +	dat += "<tr><td><B>Head:</B></td><td><A href='?src=[UID()];item=[SLOT_HUD_HEAD]'>[(head && !(head.flags&ABSTRACT)) ? head : "<font color=grey>Empty</font>"]</A></td></tr>"
```suggestion
	dat += "<tr><td><b>Head:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_HEAD]'>[(head && !(head.flags&ABSTRACT)) ? head : "<font color=grey>Empty</font>"]</a></td></tr>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/carbon/carbon_procs.dm
> +	dat += "<tr><td><B>Mask:</B></td><td><A href='?src=[UID()];item=[SLOT_HUD_WEAR_MASK]'>[(wear_mask && !(wear_mask.flags&ABSTRACT)) ? wear_mask : "<font color=grey>Empty</font>"]</A></td></tr>"
```suggestion
	dat += "<tr><td><b>Mask:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_WEAR_MASK]'>[(wear_mask && !(wear_mask.flags&ABSTRACT)) ? wear_mask : "<font color=grey>Empty</font>"]</a></td></tr>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/simple_animal/friendly/dog.dm
>  	dat += "<br><B>Collar:</B> <A href='?src=[UID()];[pcollar ? "remove_inv=collar'>[pcollar]" : "add_inv=collar'>Nothing"]</A>"
```suggestion
	var/dat = "<br><b>Head:</b> <a href='?src=[UID()];[inventory_head ? "remove_inv=head'>[inventory_head]" : "add_inv=head'>Nothing"]</a>"
	dat += "<br><b>Back:</b> <A href='?src=[UID()];[inventory_back ? "remove_inv=back'>[inventory_back]" : "add_inv=back'>Nothing"]</a>"
	dat += "<br><b>Collar:</b> <a href='?src=[UID()];[pcollar ? "remove_inv=collar'>[pcollar]" : "add_inv=collar'>Nothing"]</a>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/simple_animal/parrot.dm
> +	dat += "<tr><td><B>Headset:</B></td><td><A href='?src=[UID()];[ears?"remove_inv":"add_inv"]=ears'>[(ears && !(ears.flags&ABSTRACT)) ? ears : "<font color=grey>Empty</font>"]</A></td></tr>"
```suggestion
	dat += "<tr><td><b>Headset:</b></td><td><a href='?src=[UID()];[ears?"remove_inv":"add_inv"]=ears'>[(ears && !(ears.flags&ABSTRACT)) ? ears : "<font color=grey>Empty</font>"]</a></td></tr>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/simple_animal/parrot.dm
> +		dat += "<tr><td><B>Collar:</B></td><td><A href='?src=[UID()];[pcollar ? "remove_inv" : "add_inv"]=collar'>[(pcollar && !(pcollar.flags&ABSTRACT)) ? pcollar : "<font color=grey>Empty</font>"]</A></t
```suggestion
		dat += "<tr><td><b>Collar:</b></td><td><a href='?src=[UID()];[pcollar ? "remove_inv" : "add_inv"]=collar'>[(pcollar && !(pcollar.flags&ABSTRACT)) ? pcollar : "<font color=grey>Empty</font>"]</a></td></tr>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/dat = "<table><tr><td><B>Collar:</B></td><td><A href='?src=[UID()];item=[SLOT_HUD_COLLAR]'>[(pcollar && !(pcollar.flags & ABSTRACT)) ? pcollar : "<font color=grey>Empty</font>"]</A></td></tr></t
```suggestion
	var/dat = "<table><tr><td><b>Collar:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_COLLAR]'>[(pcollar && !(pcollar.flags & ABSTRACT)) ? pcollar : "<font color=grey>Empty</font>"]</a></td></tr></table>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/living/simple_animal/simple_animal.dm
>  	dat += "<A href='?src=[user.UID()];mach_close=mob\ref[src]'>Close</A>"
```suggestion
	dat += "<a href='?src=[user.UID()];mach_close=mob\ref[src]'>Close</a>"
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/mob.dm
> +	<tr><td><B>Right Hand:</B></td><td><A href='?src=[UID()];item=[SLOT_HUD_RIGHT_HAND]'>[(r_hand && !(r_hand.flags&ABSTRACT)) ? r_hand : "<font color=grey>Empty</font>"]</A></td></tr>
```suggestion
	<tr><td><b>Left Hand:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_LEFT_HAND]'>[(l_hand && !(l_hand.flags&ABSTRACT)) ? l_hand : "<font color=grey>Empty</font>"]</a></td></tr>
	<tr><td><b>Right Hand:</b></td><td><a href='?src=[UID()];item=[SLOT_HUD_RIGHT_HAND]'>[(r_hand && !(r_hand.flags&ABSTRACT)) ? r_hand : "<font color=grey>Empty</font>"]</a></td></tr>
```

2024-03-31 08:00 UTC, Burzah commented on code/modules/mob/mob.dm
>  	<A href='?src=[user.UID()];mach_close=mob\ref[src]'>Close</A>
```suggestion
	<a href='?src=[user.UID()];mach_close=mob\ref[src]'>Close</a>
```

2024-04-06 14:14 UTC, Burzah approved these changes

2024-04-07 09:50 UTC, S34NW approved these changes

2024-04-07 09:59 UTC, merged