Adds the brainalyzer! New psychiatrist advanced machine!
ParadiseSS13/Paradise pull request #24904
Opened 2024-03-31 11:16 UTC by Henri215

## What Does This PR Do

Adds the brainalyzer, a machine found over the psych office that is capable of analyzing the brain of patients.. maybe one day it will replace bald therapists...

Sounds by BlackDog
## Why It's Good For The Game

More accurate diagnosis on the mental station of the crew!
## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/77684085/e69770b1-1019-46f3-978b-4f7f36c29e25

## Testing

- Its a research station, like NT would do.. lets test it live!
## Changelog
:cl: Henri215, BlackDog
add: The brainalyzer machine has been added to all psychiatrist offices, place your patients there to receive an accurate diagnosis on their mental state!
/:cl:

2024-03-31 15:32 UTC, Contrabang requested changes
oh dear lord, can you make this not a subtype of the bodyscanner

2024-04-01 00:05 UTC, Henri215 commented on code/game/machinery/adv_med.dm
> +		visible_message("[user] climbs into the body scanner.")
```suggestion
		visible_message("[user] climbs into [src].")
```

2024-04-01 00:05 UTC, Henri215 commented on code/game/machinery/adv_med.dm
> +		visible_message("[user] puts [H] into [src].")
```suggestion
		visible_message("[user] puts [H] into the body scanner.")
```

2024-04-01 00:07 UTC, Contrabang approved these changes
FISI

2024-04-01 00:09 UTC, merged