[AFD] Adds Mghost
ParadiseSS13/Paradise pull request #24917
Opened 2024-03-31 12:44 UTC by DGamerL

## What Does This PR Do
Adds mghost

## Why It's Good For The Game
I think we can trust mentors at this point, this helps them complete tickets properly

https://github.com/ParadiseSS13/Paradise/assets/108773801/a3ac0c1a-4978-4ea5-bd37-209b9f5659ad

## Testing
See above

## Changelog
:cl:
add: [MENTOR] Adds Mghost
/:cl:

2024-03-31 13:45 UTC, FunnyMan3595 commented on code/modules/admin/admin_verbs.dm
> +		mob.gib()
```suggestion
		mob.gib()
		to_chat(src, "You are now a ghost!")
```

SMH, can't believe you would make such a mistake.

2024-03-31 14:14 UTC, Protointerwebs commented
As a mentor I must say this is a mistake and I will abuse it in order to get the number 1 victory royal.

2024-03-31 15:36 UTC, Contrabang requested changes

2024-03-31 15:36 UTC, Contrabang commented on code/modules/admin/admin_verbs.dm
> +		mob.gib()
```suggestion
	if(isnewplayer(mob))
		to_chat(src, "You can't ghost while you're still in the lobby! Join or observe first.")
		return
	to_chat(src, "You are now a ghost!")
	mob.gib()
```

2024-03-31 15:36 UTC, Burzah approved these changes

2024-03-31 15:38 UTC, Burzah commented
Good to go after Contra's review.

2024-03-31 15:40 UTC, Contrabang requested changes

2024-03-31 15:40 UTC, Contrabang commented on code/modules/admin/admin_verbs.dm
> +	if(isobserver(mob))
```suggestion
	if(!isliving(mob))
```

2024-03-31 16:01 UTC, Contrabang commented
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/857e2271-924b-4e0d-811c-18ef3856f3bc)

2024-03-31 16:03 UTC, Contrabang requested changes

2024-03-31 16:03 UTC, Contrabang commented on code/modules/admin/admin_verbs.dm
> +		return
```suggestion
	if(isnewplayer(mob))
		to_chat(src, "You can't ghost while you're still in the lobby! Join or observe first.")
		return
	if(!isliving(mob))
		to_chat(src, "You're already a ghost!")
		return
```

2024-03-31 16:28 UTC, Contrabang approved these changes

2024-03-31 16:28 UTC, merged

2024-04-01 14:53 UTC, Coolrune206 commented
I'm disappointed this doesn't immediately kill you upon use.