Spells with charges show recharging status again
ParadiseSS13/Paradise pull request #24953
Opened 2024-04-01 00:29 UTC by HMBGERDO

## What Does This PR Do

This is not april fools PR

This PR fixes action buttons for spells with charges not showing recharging progress when you have charges > 0

## Why It's Good For The Game

Spells with charges should show its recharge process as it was before. It was broken in https://github.com/ParadiseSS13/Paradise/pull/24482

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/61080616/9afd5ac8-4f79-407b-93a8-b35271d8de6e)

## Testing

Compiled, glared people

## Changelog
:cl:
fix: Spells with charges show recharge progress all the recharge time once again
/:cl:

2024-04-01 22:44 UTC, lewcc commented on code/datums/action.dm
> +	return !ready
```suggestion
	return !IsAvailable()
```

2024-04-03 18:04 UTC, Contrabang requested changes

2024-04-03 18:04 UTC, Contrabang commented on code/datums/action.dm
> +	return draw
```suggestion
	return S.cooldown_handler.should_draw_cooldown()
```

2024-04-03 18:24 UTC, Contrabang approved these changes

2024-04-03 18:29 UTC, merged