Many botany QoL changes.
ParadiseSS13/Paradise pull request #25031
Opened 2024-04-06 21:44 UTC by FunnyMan3595

## What Does This PR Do
Many QoL changes, see changelog.
Standardizes the code on "nutrient" for plants, as shown to the user, rather than overloading "nutriment".
(Split from #24342.)

## Why It's Good For The Game
Quality of life is good.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/98381/4236eae4-3c7b-455d-b110-30de51b996f4)

## Testing
* Pulled the core stats off of tower caps and placed them onto wheat.
* Scanned an empty tray, saw EZ Nutrient.
* Grabbed Mutrient from a vendor, used on tray, scanned, saw Mutrient.
* Planted grass in Mutrient and EZ Nutrient. Plant in Mutrient mutated, plant in EZ did not.
* Biogenerator recycled a grass stalk and a grass seed.
* Cmagged a plant data disk, put it back in the plant DNA manipulator.
* Shot skrell with the floral somatoray in both modes, did minor cellular damage.
* Shot a diona with the floral somatoray in mutate mode, gave it Empath.
* Punched a diona in the chest, then shot it there with the floral somatoray in yield mode. Bruise healed.
* Extracted seeds from 10 default wheat at once.
* Shot a tray with the floral somatoray, at point blank, in both modes.
* Planted 7 plots of starthistle, got 7 batches of starthistle seeds.
* Planted 8 plots of default Ambrosia Gaia. Waited for the weed indicator to show before weeding. All 8 survived to harvest.

## Changelog
:cl:
add: There's an additional ability to extract all core plant stats onto one data disk. When using this mode, core plant stats no longer have caps based on part level, but part level will determine how many seeds with the same stats you need to produce a usable core stats disk (1 to 5).
add: The plant analyzer now reports next harvest time and nutrient in use.
add: Mutriment has been added, duplicating old EZ (green, causes stat mutations)
imageadd: Sprite for Mutriment jug
tweak: EZ-Nutriment (and the tray default) no longer causes plant stat mutations.
tweak: EZ-Nutriment is now brown, and slightly less toxic to people.
tweak: Descriptions for plant nutrient chemicals and their jugs have been adjusted to match the changes.
tweak: The biogenerator will now accept all the same items as a plant bag.
tweak: The biogenerator's time to process is now based around the amount of biomass produced, not the item count. This generally makes the biogenerator faster, especially with small items. Process time is capped at 20s, the same as a full, unupgraded biogenerator before this.
tweak: Cmagged plant data disks now show as "nuclear authentication disk?" in the plant DNA manipulator.
tweak: The floral somatoray now does mild cellular damage to non-dionae.
tweak: The floral somatoray in mutation mode now does a short stun and a genetic mutation (usually bad, never monkey) to dionae.
tweak: The floral somatoray in yield mode now slightly heals dionae.
tweak: Seeds no longer spread quite as far on creation. This should make it somewhat easier to continue clicking the seed extractor when processing multiple plants.
fix: The floral somatoray can now be used on plant trays at point blank.
fix: The floral somatoray now produces an on-hit effect in both modes, not just one.
fix: Starthistle no longer randomly refuses to drop anything on harvest.
remove: Weed invasion can no longer replace plants without warning.
/:cl:

2024-04-07 04:40 UTC, FunnyMan3595 commented
> So this will still clamp tobacco yield (10) to 5?

The intent of #24122 was to clamp ALL yield to 5. The PR just forgot to update starting seeds to respect the new limit.

It's technically a bug, but since #24342 plans to return the cap to 10, I'm not too fussed about fixing it.

2024-04-14 22:06 UTC, Burzah requested changes

2024-04-14 22:06 UTC, Burzah commented on code/modules/hydroponics/growninedible.dm
> +	var/msg = "<span class='info'>This is \a <span class='name'>[src]</span>\n"
```suggestion
	var/msg = "<span class='info'>This is \a </span><span class='name'>[src]</span>\n"
```

2024-04-14 22:06 UTC, Burzah commented on code/modules/hydroponics/hydroponics_tray.dm
> +		to_chat(user, "*** <B>[myseed.plantname]</B> ***")
```suggestion
		to_chat(user, "*** <b>[myseed.plantname]</b> ***")
```

2024-04-14 22:06 UTC, Burzah commented on code/modules/hydroponics/hydroponics_tray.dm
> +		to_chat(user, "<B>No plant found.</B>")
```suggestion
		to_chat(user, "<b>No plant found.</b>")
```

2024-04-15 19:57 UTC, S34NW reviewed
I've had the highest assurances this works fine, if it does not Funnyman gets lashes

2024-04-15 19:58 UTC, S34NW approved these changes

2024-04-15 19:59 UTC, Burzah approved these changes

2024-04-15 20:01 UTC, merged