Removes floor from flip message when falling over in space
ParadiseSS13/Paradise pull request #25136
Opened 2024-04-14 22:31 UTC by Social-Moth

## What Does This PR Do

Adds a message for failing a flip while on a space tile.

## Why It's Good For The Game

There is no floor in space, so crashing into the floor shouldn't happen there.

resolves #24471 

## Testing

Compile, spam *flip until it fails on station, then repeat in space. Works as intended in both scenario's

## Changelog
:cl:
tweak: Changed text for falling over during a flip while in space
/:cl:

2024-04-14 22:34 UTC, Contrabang requested changes

2024-04-14 22:34 UTC, Contrabang commented on code/modules/mob/mob_emote.dm
>  		message = "flops and flails around on the floor."
```suggestion
			message = "flops and flails around on the floor."
```

2024-04-14 22:34 UTC, Contrabang commented on code/modules/mob/mob_emote.dm
> +			return ..()
```suggestion
		return ..()
```

2024-04-14 22:34 UTC, Contrabang commented on code/modules/mob/mob_emote.dm
>  			L.Weaken(4 SECONDS)
We're trying to get rid of sleeps, you can instead use a timer here. This should work the same
```suggestion
			addtimer(CALLBACK(L, TYPE_PROC_REF(/mob/living, Weaken), 4 SECONDS), 0.3 SECONDS)
```

2024-04-14 22:46 UTC, Contrabang commented on code/modules/mob/mob_emote.dm
> +			return ..()
I fucked this up, my bad
```suggestion
		return ..()
```

2024-04-15 11:20 UTC, Henri215 commented on code/modules/mob/mob_emote.dm
> +			message = "flops and flails around in space"
```suggestion
			message = "flops and flails around in space."
```

2024-04-15 14:01 UTC, DGamerL reviewed
Ternaries my beloved

2024-04-15 14:01 UTC, DGamerL commented on code/modules/mob/mob_emote.dm
> +			message = "attempts a flip and crashes to the floor!"
```suggestion
		message = "attempts a flip and [isspaceturf(turf) ? "loses balance" : "crashes to the floor"]!"
```

2024-04-15 14:01 UTC, DGamerL commented on code/modules/mob/mob_emote.dm
> +			message = "flops and flails around on the floor."
```suggestion
		message = "flops and flails around [isspaceturf(turf) ? "in space" : "on the floor"]."
```

2024-04-16 00:29 UTC, DGamerL approved these changes

2024-04-18 13:11 UTC, S34NW approved these changes

2024-04-19 14:13 UTC, Contrabang approved these changes

2024-04-19 14:25 UTC, merged