[s] Encryption key trick no more
ParadiseSS13/Paradise pull request #25137
Opened 2024-04-14 22:44 UTC by m-dzianishchyts

## What Does This PR Do
Fixes #17498.

## Why It's Good For The Game
Less tricks fair.

## Testing
Trick unavailable on local server.

## Changelog
:cl: Maxiemar
fix: Encryption keys cannot be inserted into headsets when anti-drop is active.
/:cl:

2024-04-14 22:46 UTC, Henri215 commented on code/game/objects/items/devices/radio/headset.dm
> +			to_chat(usr, "<span class='warning'>[key] is stuck to your hand, you can't insert it in [src]</span>")
```suggestion
			to_chat(user, "<span class='warning'>[key] is stuck to your hand, you can't insert it in [src].</span>")
```

2024-04-15 12:59 UTC, DGamerL approved these changes

2024-04-16 00:36 UTC, Contrabang requested changes

2024-04-16 00:36 UTC, Contrabang commented on code/game/objects/items/devices/radio/headset.dm
> +		if(!user.drop_item())
```suggestion
		if(!user.unEquip(key))
```

2024-04-16 13:20 UTC, Contrabang approved these changes

2024-04-19 14:16 UTC, merged