Removes all mentions of `return .` where they would be unnecessary
ParadiseSS13/Paradise pull request #25142
Opened 2024-04-15 01:39 UTC by DGamerL

## What Does This PR Do
Removes all mentions of `return .` where they would be unnecessary. Either outright removes them if they are at the end of a proc, or just removes the `.` if it didn't return anything else

Also:
- Removes an 8 year old comment in `shuttle.dm`
- Standardizes the `if()      return` in `sanitize_values` to what we should have because it bothered me

## Why It's Good For The Game
It's all unnecessary, so let's remove the explicit stuff

## Testing
It compiled without errors

## Changelog
NPFC

2024-04-15 12:15 UTC, DGamerL commented
> There's one more `return .` at
> 
> https://github.com/ParadiseSS13/Paradise/blob/95efc8fbda7ae52d83b7f5169746d5134a5c0eaf/code/modules/mob/living/carbon/human/species/_species.dm#L318-L323

Applied!

2024-04-17 18:06 UTC, Burzah requested changes

2024-04-17 18:06 UTC, Burzah commented on code/__HELPERS/sanitize_values.dm
> +				. += ascii2text(ascii+32)	//letters A to F - translates to lowercase
```suggestion
				. += ascii2text(ascii + 32)	//letters A to F - translates to lowercase
```

2024-04-18 00:45 UTC, Sirryan2002 approved these changes

2024-04-18 00:45 UTC, Sirryan2002 commented on code/__HELPERS/sanitize_values.dm
> +	if(List && List.len)
could just be shortened to `if(length(List)` since it null checks it

2024-04-22 22:56 UTC, Burzah approved these changes

2024-04-23 00:54 UTC, merged