TGUI input for paper strikes again
ParadiseSS13/Paradise pull request #25164
Opened 2024-04-17 11:08 UTC by m-dzianishchyts

## What Does This PR Do
Enables TGUI input for paper. Works properly now with customizable trim.
We reverted this in #24270, it is better now, I think.

Add one more argument for `/proc/tgui_input_text()` and `/datum/tgui_input_text` constructor, I didn't find any consequences of this. 

## Why It's Good For The Game
We all praise TGUI.

## Testing
Tested for all cases, fine trim, tgui input detected.

![image](https://github.com/ParadiseSS13/Paradise/assets/39908528/51cea7f2-dca7-4547-9a23-398e429a6d5d)

## Changelog
:cl: Maxiemar
tweak: TGUI input is enabled for paper again, works properly now.
/:cl:

2024-04-17 12:05 UTC, CinnamonSnowball commented
This doesn't seem to actually address the reasons paper's TGUI input was reverted
> TGUI Input Text in the paper was partly a mistake, as many people are used to indenting on Enter rather than Shift - Enter
Plus it had a 1024 character limit, which is pretty silly for paper.

2024-04-17 12:08 UTC, Scribble-Sheep commented
Are the two issues mentioned in 24270 still present, out of curiosity?

2024-04-17 17:46 UTC, Burzah requested changes

2024-04-17 17:46 UTC, Burzah commented on code/__HELPERS/text.dm
> +	for(var/i = 1, i <= length_char(text), i++)
```suggestion
	for(var/i in 1 to length_char(text))
```

2024-04-18 12:08 UTC, FunnyMan3595 commented
> TGUI Input Text in the paper was partly a mistake, as many people are used to indenting on Enter rather than Shift - Enter
> Plus it had a 1024 character limit, which is pretty silly for paper.

I'm with the other commenters on this one, both of these need to be addressed before I'm comfortable with this change.

2024-05-26 01:19 UTC, closed without merging