Add Variety of Food secondary goal, small tweaks.
ParadiseSS13/Paradise pull request #25173
Opened 2024-04-18 03:13 UTC by FunnyMan3595

## What Does This PR Do
Adds a new secondary goal: Variety of Food, for the Kitchen.
More foods are now labelled with new difficulty categories that exempt them from specific food goals, but allow them in Variety of Food if the chef wants to send them..
A few reagent difficulties have been tweaked, including using a similar exemption mechanism.
Request console messages from the supply shuttle are now batched together, and duplicates are compressed.

## Why It's Good For The Game
More secondary goal variety is nice.
Better food/reagent labelling makes for better goals.
Less request console spam is good.

## Testing
Completed variety of food, saw less request console spam.

## Changelog
:cl:
add: New secondary goal for Kitchen: Variety of Food.
tweak: A few reagents have been tweaked to more fitting secondary goal difficulties.
tweak: Secondary Goals will no longer spam request consoles with multiple messages when the supply shuttle reaches CC.
/:cl:

2024-04-18 03:26 UTC, GDNgit requested changes
quick lookover

2024-04-18 03:26 UTC, GDNgit commented on code/modules/shuttle/supply.dm
> +	var/list/department_messages = new
```suggestion
	var/list/credit_changes = list()
	var/list/department_messages = list()
```
list() is generally preferred over new/list /new on lists. Just for readability

2024-04-18 03:26 UTC, GDNgit commented on code/modules/shuttle/supply.dm
> +		var/list/rc_message = new
```suggestion
		var/list/rc_message = list()
```

2024-04-18 03:26 UTC, GDNgit commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +
```suggestion
```

2024-04-18 03:26 UTC, GDNgit commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +/datum/secondary_goal_progress/variety_food/update(atom/movable/AM, datum/economy/cargo_shuttle_manifest/manifest = null)
```suggestion
/datum/secondary_goal_progress/variety_food/update(/obj/item/food/food, datum/economy/cargo_shuttle_manifest/manifest = null)
```

2024-04-18 03:26 UTC, GDNgit commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +	var/obj/item/food/food = AM
```suggestion
	if(!check_personal_crate(food))
		return

	// Not food? Ignore.
	if(!istype(food))
		return
```

2024-04-18 03:26 UTC, GDNgit commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +	SSblackbox.record_feedback("nested tally", "secondary goals", 1, list(goal_name, "foods", initial(food_type.name)))
```suggestion
	SSblackbox.record_feedback("nested tally", "secondary goals", 1, list(goal_name, "foods", initial(food.name)))
```

2024-04-18 03:50 UTC, DGamerL commented on code/modules/shuttle/supply.dm
> +
```suggestion
```

2024-04-18 03:50 UTC, DGamerL commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +	var/datum/economy/line_item/item = new
```suggestion
	var/datum/economy/line_item/item = new()
```

2024-05-03 22:51 UTC, Henri215 commented on code/modules/station_goals/secondary/botany/kudzu_goal.dm
> +	three_way_reward(manifest, "Hydroponics", GLOB.station_money_database.get_account_by_department(DEPARTMENT_SERVICE), SSeconomy.credits_per_kudzu_goal,  "Secondary goal complete: [needed] samples of
```suggestion
	three_way_reward(manifest, "Hydroponics", GLOB.station_money_database.get_account_by_department(DEPARTMENT_SERVICE), SSeconomy.credits_per_kudzu_goal, "Secondary goal complete: [needed] samples of kudzu seeds.")
```

2024-05-03 22:51 UTC, Henri215 commented on code/modules/station_goals/secondary/kitchen/variety_food.dm
> +	abstract = FALSE
```suggestion
	department = "Kitchen"
	abstract = FALSE
	var/different_types = 10
	var/amount_per = 3
	var/department_account
	var/generic_name_plural = "dishes"
	var/reward
```
Could probably add comments to "amount_per" and "different_types".

2024-05-17 12:54 UTC, merged