Made turf contents listing more performant.
ParadiseSS13/Paradise pull request #25188
Opened 2024-04-19 01:20 UTC by FunnyMan3595

## What Does This PR Do
The turf contents listing (AKA listedturf, client obj view, alt-click view) has been replaced with a high-performance version, easily able to handle tiles with thousands of items on them.
Fixed #24549
Fixes images not loading and causing lag.

## Why It's Good For The Game
Performance and bug fixes are good.

## Images of changes
https://github.com/ParadiseSS13/Paradise/assets/98381/6c4e6b47-8d63-422e-b478-c8cd04fceb26

## Testing
See above.

## Changelog
:cl:
tweak: The alt-click view of tile contents has been rewritten to have better performance, especially with large numbers of items on a tile.
fix: The same view should no longer steal your tab, frequently fail to load images, or cause lag when images fail to load.
/:cl:

2024-05-05 17:28 UTC, Contrabang requested changes
byond side review, I'm not confident enough in js to accurately say anything about it but it looks good.

2024-05-05 17:28 UTC, Contrabang commented on code/__HELPERS/iconprocs.dm
>   * * extra_clases - string of extra css classes to use when returning the icon string
while you're here
```suggestion
 * * extra_classes - string of extra css classes to use when returning the icon string
```

2024-05-05 17:28 UTC, Contrabang commented on code/controllers/subsystem/SSstatpanel.dm
> +		i++
I believe this is logically equivalent, and should give us super worthwhile bytecode improvements
```suggestion
		i++
		if(i <= min_index || i > max_index)
			continue
```

2024-05-05 17:28 UTC, Contrabang commented on code/modules/client/client_procs.dm
> +			log_debug(payload)
We probably don't want this on live. An href exploit could potentially use this to write anything to debug log, and therefore write with `rustg_log_write`, which to my knowledge, writes to the disk

2024-05-06 19:17 UTC, Contrabang reviewed
dm side looks good

2024-05-10 12:57 UTC, DGamerL approved these changes
Same with contra. Approving DM side

2024-05-12 10:59 UTC, Burzah approved these changes

2024-05-12 11:07 UTC, merged