Makes the Supermatter Announcements More Noticeable.
ParadiseSS13/Paradise pull request #25191
Opened 2024-04-19 04:21 UTC by Fordoxia

## What Does This PR Do
C and B class events, delamination warning announcements, critcal mass/charge inertia/unsafe power level/integrity restored messages and most of the SM detonation countdown are now in bold text.

Class A events, delamination danger announcements, and failsafe deactivation are now in big text.

S class events, 0% integrity, and the final 5 seconds of the detonation countdown are now in megaphone-sized text.

## Why It's Good For The Game
It's harder to accidentally miss SM announcements. If there's a lot going on, an S class event that only gets one warning can be missed. Makes the crystal more scary!

## Testing
Shot the crystal a bunch. Watched the messages.

## Changelog
:cl:
tweak: Supermatter announcements are now generally bigger so they're harder to miss.
/:cl:

2024-04-19 11:41 UTC, Contrabang requested changes
Hallucinations need to be changed also to support this

2024-04-19 17:26 UTC, lewcc commented
Is there a sound effect for this currently? I feel like it might make sense to pair these announcements with an alarm so it's less likely for them to disappear silently in chat, like the sound played when a delam is inbound.

2024-04-19 22:16 UTC, Fordoxia commented
> Is there a sound effect for these events currently? I feel like it might make sense to pair these announcements with an alarm so it's less likely for them to disappear silently in chat, like the sound played when a delam is inbound.

Most SM events do not have sounds. Only the delamination announcements and the "Oh god it's blowing up" announcement.

These sounds don't actually play except in proximity to the crystal, because it's actually a thing that you can mute the crystal on Telecomms to allow it to silently delaminate if engineering doesn't check up on the crystal.

2024-04-19 22:31 UTC, Fordoxia commented
> Hallucinations need to be changed also to support this

The hallucination is now louder.

2024-04-20 01:19 UTC, FunnyMan3595 commented
Images of the new announcement formatting, please.

2024-04-20 18:08 UTC, Fordoxia commented
> Contributor

Done.

2024-05-03 14:25 UTC, DGamerL commented on code/modules/power/engines/supermatter/supermatter.dm
> +			speaking = "<span class='reallybig'>[i*0.1]...</span>"
```suggestion
			speaking = "<span class='reallybig'>[i * 0.1]...</span>"
```

2024-05-03 14:29 UTC, DGamerL approved these changes
LGTM

2024-05-03 17:02 UTC, merged