Allows better setting of action button keybinds
ParadiseSS13/Paradise pull request #25209
Opened 2024-04-19 21:43 UTC by GDNgit

## What Does This PR Do
Allows better setting of action button keybinds, you can now bind these in the keybind menu and they persist through rounds.
reliant on #24060
TODO:
~~- [ ] Improve blob's action button UI so that things can be binded to it~~
too much stuff to refactor, will do it eventually
- [x] Clear out some of the actions that aren't properly named
- [x] Finish up the missing action descs, there's a lot of them for item actions
- [x] Test this with SQL enabled. Should work fine but better safe than sorry
- [x] Add keybinds to the new player menu, very important so they shouldn't be hidden
- [x] Make sure spells work with this when client is already present

The backend of this is ENTIRELY string based to prevent the need to dynamically create subtype objects/manage a non runtime generated associated list

## Why It's Good For The Game
QOL + generally easier to understand UI
## Images of changes
![Screenshot 2024-04-19 154242](https://github.com/ParadiseSS13/Paradise/assets/96800819/8ba143f4-046b-4dd5-9536-3518636335f1)

## Testing
Compiled, ran, used a few actions in game

## Changelog
:cl:
tweak: Action button binds can now be set in the keybinds menu
tweak: a few action buttons have been renamed 
tweak: many action buttons have had their descriptions expanded detailing their use
/:cl:

2024-04-19 22:01 UTC, GDNgit commented on code/__DEFINES/preferences_defines.dm
> +    #define SUBTAB_ACTION_KEYBINDS 1
```suggestion
	#define SUBTAB_NORMAL_KEYBINDS 0
	#define SUBTAB_ACTION_KEYBINDS 1
```

2024-04-20 07:38 UTC, ZephyrTFA requested changes
you have a lot of changes in here, such as removing some admin verbs, that are either very unintended or from a bad master merge

2024-04-20 07:38 UTC, ZephyrTFA commented on code/controllers/configuration/sections/general_configuration.dm
> -	CONFIG_LOAD_BOOL(respawn_enabled, data["respawn_enabled"])
why are you removing this

2024-04-20 07:38 UTC, ZephyrTFA commented on code/controllers/subsystem/non_firing/SSchangelog.dm
> +	set category = null
is this intended

2024-04-20 07:38 UTC, ZephyrTFA commented on code/game/jobs/job_exp.dm
> -
:thonk:

2024-04-20 16:28 UTC, Scribble-Sheep commented
Wait, is this gonna replace the temporary binds creatable by ctrl-shift clicking action buttons?
Idk if diving into the preferences menu every time I needed to change F from my clown recorder to something else would be ideal.

2024-04-20 17:17 UTC, GDNgit commented
> Wait, is this gonna replace the temporary binds creatable by ctrl-shift clicking action buttons? Idk if diving into the preferences menu every time I needed to change F from my clown recorder to something else would be ideal.

you can do both

2024-05-10 12:08 UTC, Henri215 commented on code/_globalvars/lists/keybindings_lists.dm
> +	"Martial Arts Actions" = AKB_CATEGORY_MARTIAL_ART,
Duplicated?

2024-05-10 12:10 UTC, Henri215 commented on code/game/mecha/mecha_actions.dm
> +	desc = "Toggles your mecha's lights"
```suggestion
	desc = "Toggles your mecha's lights."
```

2024-06-03 01:50 UTC, DGamerL commented on code/_globalvars/lists/keybindings_lists.dm
> +	"Martial Arts Actions" = AKB_CATEGORY_MARTIAL_ART,
```suggestion
```

2024-07-24 01:19 UTC, closed without merging