Adds CI for SQL versions
ParadiseSS13/Paradise pull request #25226
Opened 2024-04-21 17:17 UTC by Contrabang

## What Does This PR Do

Adds CI for robustly checking the SQL version

## Why It's Good For The Game

Catches some stupid errors

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/33237473-c0e6-4179-bedd-6563514e1b65)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/2d29f156-fb87-4cda-bbad-5de5f499c2a6)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/174a71cc-27d3-46f8-abb4-6c36b3f31753)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/6d05f0ec-e995-4129-aa3b-ad487581dd58)

## Testing

See above

## Changelog
NPFC

2024-04-21 17:24 UTC, AffectedArc07 approved these changes
Well we have a check that makes sure code matches SQL itself. 

The lack of checking for SQL version based on update file is its own issue. That said, off me.

2024-05-04 23:02 UTC, Burzah approved these changes

2024-05-05 02:01 UTC, warriorstar-orion requested changes

2024-05-05 02:01 UTC, warriorstar-orion commented on tools/ci/verify_sql_version.py
> +def get_sql_folder_version():
can you annotate the return types?

2024-05-05 02:01 UTC, warriorstar-orion commented on tools/ci/verify_sql_version.py
> +    if updates_folder_sql <= 0 or not isinstance(updates_folder_sql, int) or updates_file == None:
`not updates_file` or `update_files is None`

2024-05-05 16:39 UTC, Contrabang commented on tools/ci/verify_sql_version.py
> +    folder_path = "SQL/updates"
Because I'm clueless with python, updateed to use pathlib

2024-05-05 16:50 UTC, warriorstar-orion approved these changes
LGTM (Let's Guarantee These Migrations)

2024-05-05 19:56 UTC, merged