Splits Up Chameleon Kit
ParadiseSS13/Paradise pull request #25238
Opened 2024-04-22 20:20 UTC by matttheficus

## What Does This PR Do
Chameleon Kit is now cut down a little and broken up for Traitor Uplinks

**Traitors**
Cham Kit: `10TC` - removed Voice Changer + Stamp
Cham Voice Changer: `10TC`

The net TC cost for everything is the same at `20TC`.

_(Sidenote: If you still want a stamp, its 1TC)_

**Nukies**
Cham Kit is still 30TC for everything in the old kit (Changer + Stamp)

## Why It's Good For The Game
Allows for Traitors to be more modular with their TC, allowing them to spend some of it on stealth items without breaking the TC bank for builds that might need some firepower. We should be encouraging Antagonists to re-integrate after goals are done to avoid the giga-spiral of fighting and escalation.

This also removes all Class C from the kit, meaning you can buy this and not immediately being a criminal unless you want a mask.

## Testing
Bought some stuff using the uplink.

## Changelog
:cl:
tweak: Split Chameleon Kit and Chameleon Mask from each other.
tweak: Removed Chameleon Stamp from the Chameleon Kit.
tweak: No change to Nuclear Operative Chameleon Kit.
/:cl:

2024-04-23 00:33 UTC, Fordoxia commented
Also good for contractors that want the kit, since they don't end up with a duplicate voice changer.

2024-04-25 12:58 UTC, Henri215 commented
Mention that you decreased the Chameleon Voice Modulator Mask TC cost from 8 to 5.

2024-04-25 13:07 UTC, Henri215 requested changes

2024-04-25 13:07 UTC, Henri215 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +/obj/item/storage/box/syndie_kit/chameleon_nuke/populate_contents()
```suggestion
/obj/item/storage/box/syndie_kit/chameleon_nuke
	name = "operative's chameleon kit"

/obj/item/storage/box/syndie_kit/chameleon_nuke/populate_contents()
```
Incorrect path

2024-05-04 18:52 UTC, Henri215 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +/obj/item/storage/box/syndie_kit/chameleon_nuke/populate_contents()
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/65d0db8f-3f48-4bfc-ab30-02610b6f8585)

2024-05-05 19:53 UTC, Henri215 approved these changes

2024-05-06 19:30 UTC, lewcc approved these changes

2024-05-06 19:35 UTC, merged