Renames most processing SS' to the convention of `SS[SS name here]`
ParadiseSS13/Paradise pull request #25302
Opened 2024-04-28 23:30 UTC by DGamerL

## What Does This PR Do
Renames a few SubSystem files so they are a **lot** easier to find via file searcher

## Why It's Good For The Game
Naming them after their Subsystem makes them 10x easier to find

## Testing
It compiled

## Changelog
NPFC

2024-04-28 23:31 UTC, GDNgit approved these changes

2024-04-28 23:52 UTC, Contrabang requested changes
can you do the ticket subsystems too?

2024-04-28 23:54 UTC, DGamerL commented
> can you do the ticket subsystems too?

Done

2024-04-29 03:36 UTC, Contrabang approved these changes

2024-05-01 23:54 UTC, Burzah approved these changes

2024-05-01 23:59 UTC, merged