Vetus Speculator now tell you what type he is
ParadiseSS13/Paradise pull request #25316
Opened 2024-04-30 11:27 UTC by ErdGinalD

## What Does This PR Do
Now when you examine Vetus, you can see a postscript telling you the type of its core.

## Why It's Good For The Game
Sometimes Vetus' appearance is not obvious, especially to people with color blindness, so being able to understand the core type by inspection can be a lifesaver, as each core type should ideally have different equipment, such as magboots vs cryo, fire protection for fire type, and so on.

## Images of changes
Cryo core example. Now air cold around him 
![image](https://github.com/ParadiseSS13/Paradise/assets/114731039/9cea200c-f092-4622-b59a-271daad0e53b)

## Testing
do code, try again, do correct

## Changelog
:cl:
tweak: Examination of Vetus now tells us its core type
/:cl:

2024-04-30 12:05 UTC, Henri215 commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +			desc += "You can see the strong wind around him"
```suggestion
			desc += "It emits sparks of blue energy."
		if(GRAV)
			desc += "There's a distorted gravity around him."
		if(PYRO)
			desc += "You see the flames around him."
		if(FLUX) // Main attack is shock, so flux makes it stronger
			melee_damage_lower = 25
			melee_damage_upper = 25
			desc += "He looks overflowing with energy."
		if(VORTEX)
			desc += "You can see the strong wind around him."
```

2024-04-30 14:09 UTC, Scribble-Sheep commented
Vetus gender confirmed?

2024-04-30 20:07 UTC, ErdGinalD commented
> Real talk tho, there's a missing space between 'combatant." and "The air" at the end that looks janky in that screencap. I'm not sure how this would normally be handled, but if that's still in the game then there needs to be a space added at the start of those ending messages or something.

Done new version, should be fine like that

2024-04-30 21:05 UTC, Henri215 commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +			desc += "The air surrounding it cold and listless."
```suggestion
			desc += "The air surrounding it is cold and listless."
```

2024-05-01 16:40 UTC, Henri215 commented
> > Real talk tho, there's a missing space between 'combatant." and "The air" at the end that looks janky in that screencap. I'm not sure how this would normally be handled, but if that's still in the game then there needs to be a space added at the start of those ending messages or something.
> 
> Done new version, should be fine like that

It still lacks that space he talked about, caused by it not being done over the /examine proc that would add it automatically, since you are doing it on initialize you would have to add a space at the start for all mode descriptions.

2024-05-01 23:37 UTC, Scribble-Sheep commented
I can't work out how to do multiline suggestions, sorry

2024-05-02 14:12 UTC, Scribble-Sheep requested changes

2024-05-02 14:12 UTC, Scribble-Sheep commented on code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
> +			desc += "The air surrounding it is cold and listless."
```suggestion
			desc += " It emits sparks of blue energy."
		if(GRAV)
			desc += " Gravity seems to distort around it."
		if(PYRO)
			desc += " You see flames burning around it."
		if(FLUX) // Main attack is shock, so flux makes it stronger
			melee_damage_lower = 25
			melee_damage_upper = 25
			desc += " It seems to overflow with energy."
		if(VORTEX)
			desc += " You see space bend and distort around it."
		if(CRYO)
			desc += " The air surrounding it is cold and listless."
```

2024-05-03 22:45 UTC, Henri215 approved these changes

2024-05-03 23:19 UTC, DGamerL approved these changes

2024-05-03 23:22 UTC, merged