Adds a bone tumor specific to slime people
ParadiseSS13/Paradise pull request #25320
Opened 2024-04-30 15:51 UTC by Social-Moth

## What Does This PR Do

 Adds Crystalized Slime Jelly, a specific kind of bone tumor that slime people get when they overdose on osseous reagent

## Why It's Good For The Game
Slime People don't have bones, them getting bone tumors challenges everything we know about their biology.

## Testing
OD skrell, OD slime, both get the right organs, and the server doesn't crash

## Changelog
:cl:
add: Slime People now get crystalized slime jelly instead of bone tumors
/:cl:

2024-04-30 15:54 UTC, DGamerL requested changes

2024-04-30 15:54 UTC, DGamerL commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +		else if	(!H.get_int_organ(/obj/item/organ/internal/bone_tumor))
```suggestion
		if(!H.get_int_organ(/obj/item/organ/internal/bone_tumor))
			if(isslimeperson(H))
				new /obj/item/organ/internal/bone_tumor/slime_tumor(H)
			else
```

2024-04-30 15:54 UTC, DGamerL commented on code/modules/reagents/chemistry/reagents/medicine.dm
>  			new/obj/item/organ/internal/bone_tumor(H)
```suggestion
				new/obj/item/organ/internal/bone_tumor(H)
```

2024-04-30 15:54 UTC, DGamerL commented on code/modules/surgery/organs/bone_tumor.dm
> +/obj/item/organ/internal/bone_tumor/slime_tumor
```suggestion

/obj/item/organ/internal/bone_tumor/slime_tumor
```

2024-04-30 15:54 UTC, DGamerL commented on code/modules/surgery/organs/bone_tumor.dm
> +	destroy_on_removal = TRUE //Changed in New to be dependent on amount of osseous reagent in the system when formed, determines damage done
```suggestion
```

2024-04-30 15:54 UTC, DGamerL commented on code/modules/surgery/organs/bone_tumor.dm
> +			I.receive_damage(rand(5, 15) + tumor_damage_modifier)
```suggestion
```
I think this is all just the same as the normal bone tumor?

2024-05-04 14:11 UTC, Henri215 commented on code/modules/reagents/chemistry/reagents/medicine.dm
> +				new/obj/item/organ/internal/bone_tumor(H)
```suggestion
				new /obj/item/organ/internal/bone_tumor(H)
```

2024-05-06 16:11 UTC, Henri215 approved these changes

2024-05-10 13:36 UTC, DGamerL approved these changes

2024-05-10 13:39 UTC, merged