Lets you attach signalers to desk bells
ParadiseSS13/Paradise pull request #25375
Opened 2024-05-04 18:45 UTC by lewcc

## What Does This PR Do
Allows you to attach signalers to desk bells. With a bell in hand, use a signaler on it.
If a signaler attached to a desk bell is on receive mode and is activated by a radio pulse, it'll ring the bell.
If a desk bell with a signaler attached is rung, it'll act like you just hit transmit on the radio.

Have fun!

## Why It's Good For The Game
This gives a fun way to add a little button for triggering signals. Maybe you could set something like this up with toxins, or give someone a big red button to push?
Either way, I think it'll make for some fun interactions.

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/89928798/30c611bb-1b9e-4a72-b36b-632139136478

## Testing
Tried ringing bells and 

## Changelog
:cl:
add: Desk bells can now have remote signalers attached to them.
add: If a desk bell is rung with a signaler attached, it'll send a signal on the signaler's frequency.
add: If a signaler attached to a desk bell is signaled, it'll ring the bell (if it's not broken).
/:cl:

2024-05-04 18:46 UTC, SynthTwo commented
I watched this idea come into fruition. Awful.

2024-05-04 20:40 UTC, ATP-Engineer commented
Does this also apply to wheelchair bells?
Last chance to look at me hector...

2024-05-04 22:16 UTC, lewcc commented
> Does this also apply to wheelchair bells? Last chance to look at me hector...

Do we even have wheelchair bells on our codebase, or is that /tg/ only?

2024-05-04 22:39 UTC, ATP-Engineer commented
I thought there was a PR got merged for it here.

2024-05-04 22:52 UTC, Burzah requested changes

2024-05-04 22:52 UTC, Burzah commented on code/modules/paperwork/desk_bell.dm
> +		audible_message("<span class='notice'>You hear [src]'s clapper fall off its hinge.")
```suggestion
		audible_message("<span class='notice'>You hear [src]'s clapper fall off its hinge.</span>")
```

2024-05-05 02:35 UTC, DGamerL commented
> I thought there was a PR got merged for it here.

Doesn't seem like it

2024-05-05 04:34 UTC, ATP-Engineer commented
Guess not (but when someone adds it for wheelchairs, it needs to be signaler compatible)

Can it be attached to bicycle bells? thats the one I probably mistook it for.

2024-05-07 04:41 UTC, 1080pCat reviewed
Does this work vise versa? being able to trigger the bell with a signaler? or just the bell triggering the signaler

2024-05-07 04:41 UTC, 1080pCat commented on code/modules/paperwork/desk_bell.dm
> +	// can only attach it while in hand
```suggestion
	// can only attach its on your person
```
pretty sure hands =/= inventory. solely atleast

2024-05-07 04:41 UTC, 1080pCat commented on code/modules/paperwork/desk_bell.dm
> +
```suggestion

```

2024-05-10 10:36 UTC, Burzah commented on code/modules/assembly/assembly.dm
>  	var/wires = ASSEMBLY_WIRE_RECEIVE | ASSEMBLY_WIRE_PULSE
Can you change cooldown to `var/cooldown = 0` 
It probably got changed log ago by mistake.

2024-05-10 23:44 UTC, lewcc commented
> Does this work vise versa? being able to trigger the bell with a signaler? or just the bell triggering the signaler

This works both ways, you can ring the bell with a signaler as well

2024-05-25 19:53 UTC, lewcc commented
I will address this I swear

2024-05-26 13:37 UTC, Burzah approved these changes

2024-05-30 12:13 UTC, DGamerL approved these changes
LGTM

2024-05-30 12:13 UTC, DGamerL commented on code/modules/paperwork/desk_bell.dm
> +	if(!isnull(attached_signaler))
```suggestion
	if(attached_signaler)
```

2024-05-30 12:13 UTC, DGamerL commented on code/modules/paperwork/desk_bell.dm
> +	if(!isnull(attached_signaler))
```suggestion
	if((attached_signaler)
```

2024-05-30 12:13 UTC, DGamerL commented on code/modules/paperwork/desk_bell.dm
> +		if(!isnull(attached_signaler))
```suggestion
		if((attached_signaler)
```

2024-06-01 21:32 UTC, merged