Nukes nanomob
ParadiseSS13/Paradise pull request #25417
Opened 2024-05-07 19:01 UTC by AffectedArc07

## What Does This PR Do
Removes Nanomob.

- It hasn't been improved since its inception
- Most the maps are missing the friggin battle terminals which cause a debug log each round, and its such a low priority issue no one has even bothered to fix it
- The last time this was used was the 12th of January this year
- This was added during the hype of said popular mobile game, and is just old hype content

## Why It's Good For The Game
Broken code bad, missing things from maps bad, lets put it to rest.

## Images of changes
See MDB for the tiny changes, there is barely anything visible since this was missing from a lot of the maps.

## Testing
- Compiled all maps to make sure theres no remnants of this
- Tested using a PDA
- Tested using the holodeck

## Changelog
:cl: AffectedArc07
del: Removed Nanomob, you probably didnt even know it existed
/:cl:

2024-05-07 19:03 UTC, AffectedArc07 commented
THIS THING USED DIRECTIONS FOR THE COLOUR STATES THIS NEEDS PURGING IN HELLFIRE
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/a7efe9a2-48b7-4667-a7de-684b08a5bd4c)

2024-05-07 19:03 UTC, GDNgit requested changes
this will cut down on like 10% of the timer usage

2024-05-07 19:03 UTC, GDNgit commented on code/modules/client/preference/loadout/loadout_general.dm
```suggestion
```

2024-05-07 19:05 UTC, warriorstar-orion approved these changes
One less subsystem good, deleting code good, less JavaScript good.

Let's Gut These ~~(not actually)~~ Mobs

2024-05-07 19:12 UTC, DGamerL approved these changes
Doing the thing I never had courage for

2024-05-07 19:17 UTC, AffectedArc07 commented
> this will cut down on like 10% of the timer usage

Are you serious?

2024-05-07 19:21 UTC, DGamerL commented
> > this will cut down on like 10% of the timer usage
> 
> Are you serious?

They are, nanomobs my beloathed

2024-05-08 01:51 UTC, spacegeese commented
noooo
![th-3779027762](https://github.com/ParadiseSS13/Paradise/assets/136994596/7f0938ce-d3dc-458d-91d2-2ca2afec4017)

2024-05-08 11:09 UTC, Cress67 commented
Rest in peace, sweet nanomobs. I have never actually had a nanomob fight, but collecting them was a fun distraction as an Assistant for a brief time.

2024-05-09 06:57 UTC, tipoima commented
I tried playing with them, never figured out how they work. 

It was also kinda strange for NT to have dedicated terminals for it, when all other games they host are interchangeable arcade cabinets.

2024-05-14 09:32 UTC, merged