Updates tips.
ParadiseSS13/Paradise pull request #25428
Opened 2024-05-08 03:37 UTC by Fordoxia

## What Does This PR Do
Clarifies some tips. Adds some brand new tips. Removes an old tip that is not true anymore.

## Why It's Good For The Game
Tips good.

## Testing
It compiled.

## Changelog
:cl:
add: Adds some new tips.
del: Removes an incorrect tip.
tweak: Tweaks some tips.
/:cl:

2024-05-08 03:55 UTC, Scribble-Sheep requested changes
Great argument. Unfortunately, I have spotted a minor typo!

2024-05-08 03:55 UTC, Scribble-Sheep commented on strings/tips.txt
> +To crack the safe in the vault, use a stethoscope or thermal drill. You can also steal the combonation paper from the captain's office, if they didn't secure it.
```suggestion
To crack the safe in the vault, use a stethoscope or thermal drill. You can also steal the combination paper from the captain's office, if they didn't secure it.
```

2024-05-08 03:55 UTC, Scribble-Sheep commented on strings/sillytips.txt
> +Solars probably gives radiation poisoning or something, considering the other power sources are deadly in their own ways.
```suggestion
Solars probably give radiation poisoning or something, considering the other power sources are deadly in their own ways.
```

2024-05-08 03:56 UTC, Scribble-Sheep commented on strings/sillytips.txt
> +Solars probably gives radiation poisoning or something, considering the other power sources are deadly in their own ways.
This one prolly isn't a typo, but it feels like it flows more naturally to me.

2024-05-16 13:16 UTC, Burzah approved these changes

2024-05-16 22:16 UTC, DGamerL approved these changes

2024-05-17 03:50 UTC, merged