Adds Holy Water Darts to Cargo
ParadiseSS13/Paradise pull request #25468
Opened 2024-05-14 03:14 UTC by ItsMarmite

## What Does This PR Do
Adds a new crate to Cargo, containing a new type of shotgun shell- holy water darts. These darts contain 10u of holy water per dart. The crate itself costing 400 credits for two boxes, the same as tranquilisers.

## Why It's Good For The Game
Vampires were balanced with the usage of holy water offensively by Security in mind, however since the removal of the RSG from RND- Security has had to turn to shotgun darts to make use of this intended counter to vampires. These darts, which contain 20u less holy water than shotgun darts should allow for Security to still make use of this advantage without significantly over-watering the vampires they come across.

## Testing
Ordered a crate, opened it, shot it, health scanned the skrell. Correct holy water amount.

![image](https://github.com/ParadiseSS13/Paradise/assets/85680653/e12009c3-cef5-471e-a961-51147683c794)

## Changelog
:cl:
add: Adds 10u Holy Water dart boxes as cargo orderables.
/:cl:

2024-05-14 07:09 UTC, Erikos66 commented
Makes sense to have this, as said syringes/reagent shells aren't easily accessible. Having NT made shells for this exact purpose feels better than making them yourself.

I also love that gives more use to the shotgun 👍

2024-05-16 03:29 UTC, TravisAngeI commented
prepare to receive some holy spirit, bitch
- holy inquisitor charles moments before blowing up the door to a cultist base

2024-05-16 12:33 UTC, Dafrek commented
With how strong a single shot of holy water will be when compared to something like the immolator, it may need a bit of tweaking, similar to how https://github.com/ParadiseSS13/Paradise/discussions/16268 removed some of its more oppressing aspects because of the predicted increase of offensive holy water use against vampires.

Having a more easily accessible weapon that limits powerful vampires steamrolling sec by stealing their weapons and using it against them will be nice, especially if its slightly weaker overall than most other anti-vamp guns.

2024-05-16 18:51 UTC, spacegeese commented
> prepare to receive some holy spirit, bitch -holy inquisitor charles moments before blowing up the door to a cultist base

![image](https://github.com/ParadiseSS13/Paradise/assets/136994596/92af6ea8-b9b9-4b4a-bfb6-48f0f6508b0d)

2024-05-23 04:03 UTC, Burzah commented on code/modules/projectiles/ammunition/ammo_casings.dm
> +
```suggestion
```

2024-05-23 17:12 UTC, Sirryan2002 requested changes

2024-05-23 17:12 UTC, Sirryan2002 commented on code/modules/projectiles/projectile/bullets.dm
> +	reagents.add_reagent("holywater", 10)
does this need to be in New() or can you put it into Initialize()???

2024-05-29 17:15 UTC, Sirryan2002 approved these changes

2024-05-29 20:59 UTC, Burzah approved these changes

2024-05-30 16:01 UTC, merged