Removes the Sheet Snatcher 9000
ParadiseSS13/Paradise pull request #25496
Opened 2024-05-16 15:07 UTC by Fordoxia

## What Does This PR Do
Removes the Sheet Snatcher 9000 and its (unused) parent.

## Why It's Good For The Game
The SS9000 is a holdover of when the ORM didn't exist and ores had to be refined on Lavaland (or so I am told). It's not really useful for the mining cyborg's job.

## Testing
Game compiled. Mining borg didn't have the SS9000.

## Changelog
:cl:
del: Removed the Sheet Snatcher 9000.
/:cl:

2024-05-16 15:19 UTC, 1080pCat approved these changes

2024-05-16 15:19 UTC, 1080pCat commented on code/game/objects/items/weapons/storage/bags.dm
> -/// what is this even used for
mfw

2024-05-16 17:07 UTC, spacegeese commented
this means borgs can't pick up sheets made by ash drake battles, which sucks because those are hard to lug around as borgs

2024-05-16 23:25 UTC, Fordoxia commented
> this means borgs can't pick up sheets made by ash drake battles, which sucks because those are hard to lug around as borgs

Do drakes not drop a chest that you can use to haul stuff once you've killed them as a borg?

2024-05-18 07:02 UTC, Oyu07 commented
aw. I use this when I smelt at ORM and then bring some mats to robotics. 
Definetly outdated and not used. o7

2024-05-19 10:26 UTC, Burzah requested changes
The icon needs to be removed from `mining.dmi`

2024-05-20 02:54 UTC, Fordoxia commented
> The icon needs to be removed from `mining.dmi`

It is done.

2024-05-20 09:38 UTC, Burzah approved these changes

2024-05-20 17:22 UTC, DGamerL approved these changes

2024-05-25 15:51 UTC, merged