The CMO's Advanced Hypospray Can Now Inject Through Hardsuits
ParadiseSS13/Paradise pull request #25629
Opened 2024-05-25 21:55 UTC by Fordoxia

## What Does This PR Do
Allows the CMO's Advanced Hypospray to work through hardsuits.

Also does some documentation, and renames a really badly named variable.

## Why It's Good For The Game
The CMO's hypo is actually kind of lame. We have a modsuit hypo that can inject through hardsuits, and regular hypos can also do it if they are emagged (the advanced hypo, however, cannot be emagged).

In the hands of a non-antag, the CMO hypo is pretty much identical to the vendor hypo, and antags have access to better options for covertly filling you with drugs. It's lame.

## Testing
It compiled.
I injected myself through a hardsuit.

## Changelog
:cl:
tweak: CMO hypo can now pierce hardsuits.
/:cl:

2024-05-26 10:05 UTC, Adrer commented
I forsee an issue regarding nukies.

2024-05-26 22:57 UTC, Butlerblock commented
> I forsee an issue regarding nukies.

Could snowflake it so it doesn't inject through certain hardsuits

2024-05-29 02:29 UTC, Fordoxia commented
> I forsee an issue regarding nukies.

The issue is gone.

2024-06-02 16:51 UTC, DGamerL commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	/// List of OSHA-approved medicines.
```suggestion
	/// List of SOSHA-approved medicines.
```
Alternatively,
```suggestion
	// List of SOSHA-approved medicines.
	/// List of reagents that are allowed to go into a hypospray with active safeties
```

2024-06-02 16:52 UTC, DGamerL requested changes
Also add your trait to `traits.dm`

2024-06-02 17:42 UTC, Fordoxia commented
> Also add your trait to `traits.dm`

Done.

2024-06-03 01:36 UTC, DGamerL approved these changes

2024-06-06 19:36 UTC, lewcc approved these changes

2024-06-06 19:40 UTC, merged