Add colors to pill bottles and patch packs
ParadiseSS13/Paradise pull request #25650
Opened 2024-05-27 09:55 UTC by Arthri

## What Does This PR Do
- Pill bottle boxes and patch pack boxes now spawn with colored contents
- Changed ChemMaster container colors
  - Added indigo, violet, and purple
  - Removed blue
  - Replaced red with light red
- Made patch pack color overlay lighter

## Why It's Good For The Game
Great for marking different meds, such as emergency meds in red pill bottles

Pure red and blue on patch packs/pill bottles is an eye sore, so I've made red lighter and removed blue(light blue replacing it)

Colored patch packs are now more saturated, making them easier to discern

## Images of changes
![Pill Bottles](https://github.com/ParadiseSS13/Paradise/assets/41360489/8ab41c67-f71a-4aec-b46c-492d0cb1d1ab)
![Patch Packs](https://github.com/ParadiseSS13/Paradise/assets/41360489/c533edc7-dc58-442a-a624-bc9eef677b48)

## Testing
Spawned in, opened a few boxes and checked that they have color.

## Changelog
:cl: cdui
add: ChemMaster can now paint pill bottles and patch packs indigo, violet, and purple
del: ChemMaster can no longer paint pill bottles and patch packs pure blue. Light blue is still an option, however
tweak: ChemMaster's "Red" color for pill bottles and patch packs is now lighter
tweak: Colored patch packs are now lighter
tweak: Pill bottle boxes and patch pack boxes now spawn with their contents colored
/:cl:

2024-05-27 10:47 UTC, Scribble-Sheep commented
Interesting. Is there any way to change it for crafted/empty pillbottles, or is it entirely at the mercy of the roundstart contents? How is the maints floor pills bottle handled?

2024-05-27 11:09 UTC, CinnamonSnowball commented
> Some of the colors used here are exclusive to the boxes

I'm fairly sure ChemMaster UI should have enough colors for this? We shouldn't really be creating unreplicable items for no reason, if avoidable

2024-05-30 17:06 UTC, Sirryan2002 requested changes

2024-05-30 17:06 UTC, Sirryan2002 commented on code/game/objects/items/weapons/storage/boxes.dm
> +	bottle.apply_wrap()
could this proc be attached to pill bottles instead of as a global proc?

2024-05-31 16:07 UTC, Sirryan2002 approved these changes

2024-06-03 01:38 UTC, DGamerL reviewed
LGTM - I agree with snowball here, can you update the TGUI so you can pick all colors for the packs/bottles?

2024-06-06 13:08 UTC, DGamerL approved these changes

2024-06-06 13:11 UTC, merged