[TWEAK/FIX] Fixes hurting people you intend to help while performing surgery or repairing IPCs
ParadiseSS13/Paradise pull request #25704
Opened 2024-05-30 21:30 UTC by Spaghetti-bit

## What Does This PR Do

Addresses https://github.com/ParadiseSS13/Paradise/issues/25655

## Why It's Good For The Game

If I intend to help someone, I should help them, not maim them with a welder, brain, organ, circular saw, etc.

## Testing

Removed an IPC's arm, tried to apply welder. Got the funny "WHY WOULD YOU DO THAT?!" message.
Cycled intents, burn baby burn.
Also worked on organics. No more hurting people that are lying down and you're on help intent. 

## Changelog
:cl:
tweak: Help mode while intending to do a surgery or help a person on an operable surface now longer maims the person.
/:cl:

2024-05-30 21:31 UTC, iceberg112 commented
Wow!

2024-05-31 15:12 UTC, Burzah approved these changes

2024-06-06 19:00 UTC, lewcc requested changes
These feel like a bunch of arbitrary checks here. If a surgery is ongoing, there are already checks there which you can tie into, rather than having all of this handled on item attack and *guessing* if they're undergoing surgery.
Please see if you can't look into surgery code to at least make the surgery checks fit in there.

2024-06-06 19:04 UTC, Spaghetti-bit commented
> These feel like a bunch of arbitrary checks here. If a surgery is ongoing, there are already checks there which you can tie into, rather than having all of this handled on item attack and _guessing_ if they're undergoing surgery. Please see if you can't look into surgery code to at least make the surgery checks fit in there.

This is intended for a catch all for help intent on tools used for the surgeries. If we're only checking DURING a surgery we'll have cases where someone is on the help intent and thwacks a person with a tool that can't start a surgery. Bone setter etc.

2024-06-06 19:14 UTC, lewcc reviewed
Just one thing, I think this message feels a little more consistent with general IC messages.

2024-06-06 19:14 UTC, lewcc commented on code/_onclick/item_attack.dm
> +		to_chat(user, "<span class='warning'>You lower the [name] and look at it, thinking to yourself... 'why would I hurt someone I'm trying to help?'</span>")
```suggestion
		to_chat(user, "<span class='info'>You don't want to harm the person you're trying to help!</span>")
```

2024-06-06 19:26 UTC, lewcc approved these changes

2024-06-06 19:30 UTC, merged