[DRAFT] Adds the ability to save various AI and cyborg variables between rounds
ParadiseSS13/Paradise pull request #25728
Opened 2024-05-31 21:15 UTC by Daylight2

## What Does This PR Do

Adds these options to the character creation screen:
- [x] Save default AI name
- [x] Save default cyborg name
- [ ] Save default AI core display
- [ ] Save default hologram
- [ ] Save default arrivals announcement
- [ ] Add optional pronouns for cyborgs
- [ ] Make a submenu to hold all this, since the main panel is getting quite crowded

## Why It's Good For The Game
A QOL change that means AIs and borgs don't have to go trough the rigmarole of typing out the same name they always use, hunting trough the menu for their core display and hologram, and then pasting their preferred arrivals message literally every shift. It's not engaging and doesn't have any balance implications, so why not make it more convenient? Also, CRUNCH has been complaining about not having borg pronouns for a while now. 

The name change doesn't set your name to the one you choose on character creation, but autofills the namepick box, so you can still change it if you wish to have a different name this shift.

## Images of changes
- [ ] Add images of changes

## Testing
Spawned in as borg, AI. Spawned soulless borgs. Spawned ERT borgs.

## Changelog
:cl:
add: You can now change and save your default settings for AI and cyborg in the character creation menu.
add: Cyborgs can now choose pronouns for themselves.
/:cl:

2024-05-31 21:52 UTC, Fordoxia commented
Hello yes, is this the based department?

2024-06-04 08:53 UTC, Roachesintrenchcoat commented
Yes this is the based department!

2024-06-24 23:13 UTC, Fordoxia requested changes

2024-06-24 23:13 UTC, Fordoxia commented on config/example/config.toml
> +sql_version = 57
```suggestion
sql_version = 58
```
We have moved on to 58 now.

2024-07-10 03:43 UTC, Sirryan2002 commented
No progress on this PR in over a month, closing as stale. You're welcome to reopen this when you wish to continue progress, good luck!

2024-07-10 03:43 UTC, closed without merging