Zombie cure bottles / injectors for admins, no synth cures, updates comments
ParadiseSS13/Paradise pull request #25733
Opened 2024-05-31 22:24 UTC by Qwertytoforty

## What Does This PR Do

Zombie cure effects comments updated.
Adds 4 zombie cure bottles for admins to spawn.
Adds 4 zombie cure autoinjectors for admins to spawn. These can not be drained out of, so you can give them to crew without them being able to duplicate it.
Zombie cures are no longer no_synth. Sorry bee cure methods, you will be missed.

## Why It's Good For The Game

Accurate comments good.

Being able as admins to easily spawn the cure bottles good.
Being able as admins to spawn autoinjectors, be it as loot, ERT, balancing, preperation, or other is good, without letting crew cheese cures out of it.
Blocks the chemicals from being duplicated by ody / bees, as part of the above. Sorry.

## Testing

Spawning them, checking they had the right reagents

## Changelog
:cl:
tweak: Admins can now directly spawn vials of the zombie cures.
tweak: Admins can now spawn injectors of the 4 zombie cures. Players can *not* duplicate a virus cure out of these, and are safe to give out without them being able to duplicate it.
tweak: Zombie virus cures can no longer be duplicated by bees or ody mechs.
/:cl:

2024-06-10 14:51 UTC, Sirryan2002 approved these changes

2024-06-10 14:51 UTC, Sirryan2002 commented on code/modules/reagents/reagent_containers/hypospray.dm
> +		playsound(loc, 'sound/weapons/smg_empty_alarm.ogg', 20, 1) //Sucker for sounds, also gets zombies attention.
```suggestion
		playsound(loc, 'sound/weapons/smg_empty_alarm.ogg', 20, TRUE) //Sucker for sounds, also gets zombies attention.
```

2024-06-12 18:45 UTC, lewcc requested changes

2024-06-12 18:45 UTC, lewcc commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	desc = "A small autoinjector containing 15, units of Anti-Plague Sequence Alpha. Prevents infection, cures level 1 infection."
```suggestion
	desc = "A small autoinjector containing 15 units of Anti-Plague Sequence Alpha. Prevents infection, cures level 1 infection."
```

2024-06-12 18:45 UTC, lewcc commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	desc = "A small autoinjector containing 15, units of Anti-Plague Sequence Beta. Weakens zombies, heals low infections."
Fix all the commas here

2024-06-12 18:49 UTC, lewcc approved these changes
lgt--braaaains

2024-06-12 18:59 UTC, merged