Removes all `locate()` calls in `block()`
ParadiseSS13/Paradise pull request #25772
Opened 2024-06-02 19:52 UTC by DGamerL

## What Does This PR Do
Removes `locate()` calls from `block()`
Adds performance

## Why It's Good For The Game
Performance go brrrrr

## Testing
It compiled + manually went through all of the changed lines

## Changelog
NPFC

2024-06-18 17:20 UTC, Sirryan2002 requested changes
can we get fixes to Pass CI on this?

2024-06-22 22:24 UTC, DGamerL commented
> can we get fixes to Pass CI on this?

Fixed!

2024-06-23 17:02 UTC, Sirryan2002 approved these changes

2024-06-26 21:15 UTC, Burzah approved these changes

2024-06-28 18:44 UTC, AffectedArc07 approved these changes

2024-06-28 20:33 UTC, lewcc approved these changes

2024-06-28 20:37 UTC, merged