Update to restraints
ParadiseSS13/Paradise pull request #25831
Opened 2024-06-06 04:53 UTC by FaronCD

## What Does This PR Do

Updates restraint code to fix #25802 

## Why It's Good For The Game

Updated code is good. IPC's cant eat food, now IPC's break twimst cuffs

## Testing

It was tested on a localhost.

## Changelog
:cl: EOD501
fix: IPC's now break twimst cuffs instead of eating them
/:cl:

2024-06-06 05:08 UTC, Scribble-Sheep commented
Does this also apply to species with a mouth, but who're muzzled? Could see a similar "eating through duct tape" bug.

2024-06-06 06:58 UTC, 1080pCat commented on code/game/objects/items/weapons/handcuffs.dm
> +/obj/item/restraints/finish_resist_restraints(mob/living/carbon/user, break_cuffs, silent) //you only want to break hand or legcuffs, not any type of restraint
```suggestion
/obj/item/restraints/finish_resist_restraints(mob/living/carbon/user, break_cuffs, silent) // you only want to break hand or legcuffs, not any type of restraint
```

2024-06-06 06:58 UTC, 1080pCat commented on code/game/objects/items/weapons/handcuffs.dm
> +		if(!human_user.check_has_mouth()) //I have no mouth but I must eat twimsts
```suggestion
		if(!human_user.check_has_mouth()) // I have no mouth but I must eat twimsts
```

2024-06-06 21:42 UTC, Burzah commented on code/game/objects/items.dm
> +			user.visible_message("<span class='warning'>[user] attempts to [break_cuffs ? "break" : "remove"] [src]!</span>", "<span class='notice'>You attempt to [break_cuffs ? "break" : "remove"] [src]...")
```suggestion
			user.visible_message("<span class='warning'>[user] attempts to [break_cuffs ? "break" : "remove"] [src]!</span>", "<span class='notice'>You attempt to [break_cuffs ? "break" : "remove"] [src]...</span>")
```

2024-06-06 21:42 UTC, Burzah commented on code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
>  	playsound(src, 'sound/voice/hiss5.ogg', 40, 1, 1)  //Alien roars when starting to break free
```suggestion
	playsound(src, 'sound/voice/hiss5.ogg', 40, TRUE, 1)  //Alien roars when starting to break free
```
While we are here.

2024-06-07 13:14 UTC, chuga-git commented on code/game/gamemodes/cult/blood_magic.dm
> +	breakouttime = 450
```suggestion
	breakouttime = 45 SECONDS
```

2024-06-10 15:28 UTC, Sirryan2002 requested changes

2024-06-10 15:28 UTC, Sirryan2002 commented on code/game/objects/items.dm
> +/obj/item/proc/attempt_resist_restraints(mob/living/carbon/user, break_cuffs, effective_breakout_time, silent)
why isn't this scoped to `/obj/item/restraints` ???

2024-06-10 15:28 UTC, Sirryan2002 commented on code/game/objects/items.dm
> +/obj/item/proc/finish_resist_restraints(mob/living/carbon/user, break_cuffs, silent)
same here, why not scoped to `/obj/item/restraints` ?

2024-06-11 18:11 UTC, Sirryan2002 commented on code/game/objects/items.dm
> +/obj/item/proc/attempt_resist_restraints(mob/living/carbon/user, break_cuffs, effective_breakout_time, silent)
would you just duplicate the code on the straight_jacket? Duplicate code isn't ideal, but this also really doesn't need to be scoped to such a low level type

2024-06-17 03:55 UTC, Sirryan2002 approved these changes

2024-06-17 03:55 UTC, Sirryan2002 commented on code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-06-17 03:55 UTC, Sirryan2002 commented on code/modules/mob/living/carbon/human/human_mob.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-06-17 16:01 UTC, Sirryan2002 approved these changes

2024-07-01 02:13 UTC, lewcc approved these changes

2024-07-01 02:18 UTC, merged