Fixes blob diagonal expansion
ParadiseSS13/Paradise pull request #25848
Opened 2024-06-07 20:50 UTC by chuga-git

## What Does This PR Do

Fixes diagonal expansion sometimes breaking when the blob tile does not have an assigned overmind. I don't know why blob tiles sometimes don't get assigned an overmind when `Pulse()` is called. They just do. This antag needs serious help.
## Why It's Good For The Game

It was broken (sometimes) and now it's not

## Testing

Didn't runtime. I can't check how the overmind assignment works with a second overmind and there is a small chance something wonky will happen.
## Changelog
:cl:
fix: Made blob diagonal expansion less buggy
/:cl:

2024-06-07 22:38 UTC, Contrabang requested changes

2024-06-07 22:38 UTC, Contrabang commented on code/modules/events/blob/theblob.dm
> +	dirs.Remove(dirn)
```suggestion
	var/dirn = pick_n_take(dirs)
```

2024-06-07 22:38 UTC, Contrabang commented on code/modules/events/blob/theblob.dm
> +	var/obj/structure/blob/B = (locate(/obj/structure/blob) in T)
```suggestion
	var/obj/structure/blob/B = locate(/obj/structure/blob) in T
```

2024-06-07 22:38 UTC, Contrabang commented on code/modules/events/blob/theblob.dm
> +	B.Pulse((pulse+1),get_dir(src.loc,T), a_color)
```suggestion
	B.Pulse(pulse+1, get_dir(loc, T), a_color)
```

2024-06-08 01:27 UTC, DGamerL approved these changes

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
>  	if(height==0)
```suggestion
	if(height == 0)
```

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
>  	if(istype(mover) && mover.checkpass(PASSBLOB))
```suggestion
	return istype(mover) && mover.checkpass(PASSBLOB)
```

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
> +	return FALSE
```suggestion
```
Github wasn't allowing me to do both of these in one comment

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
>  /obj/structure/blob/proc/expand(turf/T = null, prob = 1, a_color, _overmind = null, turf/double_target = null)
```suggestion
/obj/structure/blob/proc/expand(turf/T, prob = TRUE, a_color, _overmind, turf/double_target)
```

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
>  		var/list/dirs = list(1,2,4,8)
```suggestion
		var/list/dirs = list(1, 2, 4, 8)
```

2024-06-08 01:27 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
> +/obj/structure/blob/proc/double_expand(turf/T = null, prob = 1, a_color, mob/camera/blob/incoming_overmind = null)
```suggestion
/obj/structure/blob/proc/double_expand(turf/T, prob = TRUE, a_color, mob/camera/blob/incoming_overmind)
```

2024-06-08 19:07 UTC, DGamerL approved these changes
LGTM

2024-06-08 19:07 UTC, DGamerL commented on code/modules/events/blob/theblob.dm
> +	B.Pulse(pulse+1, get_dir(loc, T), a_color)
```suggestion
	B.Pulse(pulse + 1, get_dir(loc, T), a_color)
```

2024-06-09 19:17 UTC, Sirryan2002 approved these changes

2024-06-12 21:56 UTC, Contrabang approved these changes
Send it

2024-06-12 21:59 UTC, DGamerL approved these changes
Send it

2024-06-12 22:03 UTC, merged