Unwrenching a pressurized pipe now flings you in a random direction
ParadiseSS13/Paradise pull request #25878
Opened 2024-06-11 01:04 UTC by PollardTheDragon

## What Does This PR Do
Tweaks unsafe pressurized pipe unwrenching so that standing ontop of the pipe, instead of making you do a flip, will instead fling you in a random direction.

## Why It's Good For The Game
Magboots are required to work with atmos pipes to prevent being tossed, unless you stand directly ontop of the pipe as it is currently. This makes it so that you need magboots even while standing on the unsafe pipe.

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/144391971/391249ff-a1b2-469d-a259-81dd6a49f5e3

## Testing
See above. Spawned as CE, made a pressure problem, did not follow OSHA.

## Changelog
:cl:
tweak: Pressurized pipes now fling you in a random direction when stood on and wrenched unsafely.
/:cl:

2024-06-11 04:39 UTC, Contrabang requested changes

2024-06-11 04:39 UTC, Contrabang commented on code/modules/atmospherics/machinery/atmospherics.dm
> +		fuck_you_dir = pick(NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST, NORTHWEST)
```suggestion
		fuck_you_dir = pick(GLOB.alldirs)
```

2024-06-12 00:11 UTC, Contrabang approved these changes

2024-06-20 11:33 UTC, DGamerL approved these changes

2024-06-20 11:42 UTC, merged