Removes an Evil Corner Window From the Luxury Survival Pod
ParadiseSS13/Paradise pull request #25899
Opened 2024-06-12 23:43 UTC by Fordoxia

## What Does This PR Do
Removes a corner window from the luxury survival pod that blocked movement despite not visibly blocking anything.

## Why It's Good For The Game
Blocking bad. The window is tiny and I don't recall any place where corner windows are used, so no one will bat an eye at this.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/143041327/1456fc25-fa07-495e-980b-fd8fd7e075ad)

## Testing
There was no window.

## Changelog
:cl:
tweak: Removed an evil window from the luxury capsule.
/:cl:

2024-06-12 23:58 UTC, Contrabang commented
Why not just fix it instead of removing it?

2024-06-14 00:42 UTC, Fordoxia commented
> Why not just fix it instead of removing it?

This window kept me up and night and I want to kill it.

2024-06-21 13:54 UTC, Sirryan2002 approved these changes

2024-06-21 14:15 UTC, Contrabang requested changes
I still think this should be properly fixed instead of removing it and ignoring it

2024-07-08 00:23 UTC, closed without merging