Adds Tarot to the Chaos Staff
ParadiseSS13/Paradise pull request #25918
Opened 2024-06-14 21:11 UTC by datlo

## What Does This PR Do

Adds three new effects to the chaos staff 
- Spawns and immediately use a random tarot card (Neutral effect)
- Spawns a tarot card pack in your backpack (Gift)
- Spawns a traitor-tier tarot deck generator in your backpack (Great gift)
## Why It's Good For The Game

![yodawg](https://github.com/ParadiseSS13/Paradise/assets/22121511/aa284825-6584-403c-adc3-09da4b4a9ede)

## Testing

![it just works](https://github.com/ParadiseSS13/Paradise/assets/22121511/64f309e5-cba5-443b-a157-c9ffb06f5164)
~~Tweaked the probs to make the effects more likely to happen and checked that everything worked as intended~~
## Changelog
:cl:
add: Added new Tarot-related effects to the chaos staff.
/:cl:

2024-06-21 13:48 UTC, Sirryan2002 commented
Me with PRs that don't have a properly filled out testing section

![giphy-ezgif com-webp-to-gif-converter](https://github.com/ParadiseSS13/Paradise/assets/80364400/e7ea749e-50c9-4181-a59f-266e98fd3968)

2024-06-21 13:49 UTC, Sirryan2002 requested changes

2024-06-21 13:49 UTC, Sirryan2002 commented on code/modules/projectiles/guns/chaos_bolt.dm
> +		if("tarot card")
```suggestion
		if("tarot card")
			#warn TEST ME!
```

2024-06-21 13:50 UTC, Sirryan2002 requested changes
Does "everything works" mean that you were able to generate all added effects in-game without runtimes or bugs?

2024-06-22 13:55 UTC, datlo commented
Thats correct yeah, all effects were triggered without runtime or bug

I'll do another round of tests with https://github.com/ParadiseSS13/Paradise/pull/25919 changes included to make sure there's no unexpected behaviour

2024-06-24 04:28 UTC, Sirryan2002 approved these changes

2024-06-28 03:19 UTC, DGamerL approved these changes

2024-06-28 03:35 UTC, merged