Hit and Run Teleporter - Explorer specific traitor item
ParadiseSS13/Paradise pull request #25938
Opened 2024-06-16 12:19 UTC by PopGamer45

## What Does This PR Do
Adds the hit and run teleporter which is basically a syndicate version of the abductors teleporter minus the abduction related actions and it having a 2.5 second teleport time instead of the 8 seconds, leaving only the action for teleporting people on the telepad onto the station and it teleports you back in 45 seconds unless you are handcuffed and (buckled or being pulled).
It is purchased as a kit for 60TC which includes a beacon for spawning the teleporter console, beacon for spawning the telepad itself and insulated gloves for forcing power on APCs (it has a high power use, so without forcing the power it would last you only like 2 uses) similar to how the experimental teleporter provides you with mesons.
It has a 3 minute cooldown starting from when you teleport onto the station not back and the telepad releases a "Suspicious Bluespace Signal" into the sector, the telepad cant be deconstructed while it is on cooldown.

Both the teleporter console and telepad can be deconstructed and give both illegal and alien research levels, since it is a syndicate adaptation of the abductors teleporter IC wise too.
The console gives illegals 3 and alien 2, and the telepad illegals 2 and alien 1. Which can in total bring research to illegals 3 and alien 3.

Iam not entirely sure about the price and not so much about the research levels, iam not very good when it comes to balance, also i should note that it can teleport multiple mobs but uses more power and it can be used when no one is standing on the telepad, so its just gonna scare people around the spot where you wanted to teleport, i thought of removing this but honestly it seems kinda funny to me that you can spare people this way.

## Why It's Good For The Game
I think its obvious that every job should have atleast one job specific traitor item and this adds a in my opinion a job specific traitor item which is pretty on theme with the job. While it is pretty powerful i think the suspicious signal and 3 minute cooldown makes it almost quaranteed that security is gonna be waiting for you near the teleporter if you want to use it for the second time.

## Images of changes
![TM54KA7JCW](https://github.com/ParadiseSS13/Paradise/assets/97299061/1d40a00f-07bf-4568-ad68-5081b4bfd906)

## Testing
Buy teleporter, setup teleporter, use teleporter, get teleported back with teleporter.
Repeat process but now handcuff yourself and get pulled by a helpful vulp and dont get teleported back.
Try various combinations of depowering/deconstruction both machines and try using the machine.
Read this testing log in the past tense.

## Changelog
:cl:
add: Adds the hit and run teleporter, a syndicate version of the abductors teleporter which teleports you back minus that it cant abduct other people with you.
/:cl:

2024-06-16 12:22 UTC, Coolrune206 commented
Cor Blimey they're givin' traitors unassisted Cult recall!

2024-06-16 16:35 UTC, HMBGERDO commented
i'd say remove power usage to let explorers place it anywhere they want. It already has a beacon, making it more difficult is kinda.. uncool
you would need a big preparation to make this thing, i like more the idea of preparation not taking half round time

2024-06-16 18:12 UTC, PopGamer45 commented
gonna remove those 2 black topright "sticks" from the telepad sprite tomorrow because they look off when there is not a adjacent wall like in the abductor ship, saying this just that anyone who was gonna mention that knows that iam already on it

2024-06-17 18:08 UTC, Sirryan2002 requested changes

2024-06-17 18:08 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +	for(var/mob/living/target in src.loc)
```suggestion
	for(var/mob/living/target in loc)
```

2024-06-18 00:47 UTC, PopGamer45 commented on code/game/machinery/syndicate_teleporter.dm
> +/obj/machinery/syndi_telepad/proc/Teleport_Out(mob/living/carbon/target)
isnt it already used there? By snake case you mean underscores between words if iam not wrong, right?

2024-06-24 04:12 UTC, Sirryan2002 requested changes

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +	desc = "A syndicate teleporter \"inspired\" by the abductor's teleportation technology."
```suggestion
	desc = "A syndicate teleporter \"inspired\" by alien abductor teleportation technology."
```

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +		return
```suggestion
```
unnecessary return statement

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +	if(target.handcuffed && (target.buckled || target.pulledby))
maybe some sort of feedback to the target would be helpful. I.e. "You feel a force trying to pull you back to your telepad... etc"

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +	about_to_retrieve = FALSE
this doesn't get set back to `FALSE` if the above if statement is met

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/machinery/syndicate_teleporter.dm
> +	new/obj/effect/temp_visual/teleport_abductor/syndi(T)
```suggestion
	new /obj/effect/temp_visual/teleport_abductor/syndi(T)
```

2024-06-24 04:12 UTC, Sirryan2002 commented on code/game/objects/items/devices/radio/beacon.dm
> +/obj/item/beacon/syndicate/bomb/syndi_teleporter
is there a reason this isn't just a subtype of `/obj/item/beacon/syndicate` ?

2024-06-24 04:12 UTC, Sirryan2002 commented on icons/obj/abductor.dmi
is there a better file you could put these sprites in? Yeah they're repainted abductor sprites but they're used for a completely different category of items

2024-06-24 05:49 UTC, PopGamer45 commented
I have switched to Linux and i thought i could run Paradise except it not being able to run TGUI on Linux and continue this PR, but i cant run Paradise at all so iam gonna close this PR because i cant do any bug testing

2024-06-24 05:49 UTC, closed without merging