Adds a Waste and Distribution Monitor to DeltaStation
ParadiseSS13/Paradise pull request #25955
Opened 2024-06-17 16:19 UTC by haydenredacted

## What Does This PR Do

Deltastation for whatever does not have a  computer to monitor the distribution pressure and air mix tanks. This PR adds that while also fixing various air sensors and meters to have the proper variable so they get detected by the monitor.

## Why It's Good For The Game

Monitoring atmos is good and you'll know if the crew will yell at you when there's vent crawling antagonists because the vents are bursting.

## Images of changes

In game:
![image](https://github.com/ParadiseSS13/Paradise/assets/91229275/cdef38f5-d38b-462f-a892-23dddf41cb63)

StrongDMM:
![image](https://github.com/ParadiseSS13/Paradise/assets/91229275/c7814926-3206-460b-b19b-b24a702a1434)

## Testing

Loaded Deltastation and looked at the pressure of the distro
## Changelog
:cl:
add: Added Waste and Distribution monitor to atmospherics on Deltastation
tweak: Changed variables of air meters/sensors to be detectable by the monitor
/:cl:

2024-06-17 16:21 UTC, haydenredacted commented
Please excuse my constant brawling with this config file, my other PR had the same issue.

2024-06-18 08:33 UTC, HMBGERDO commented
you have `config/config.toml` added in PR files, you should remove it

2024-06-18 17:17 UTC, Sirryan2002 requested changes

2024-06-18 17:17 UTC, Sirryan2002 commented on config/config.toml
this needs to be removed from your changes :)

2024-06-18 17:34 UTC, haydenredacted commented
config.toml removed.

2024-06-19 20:22 UTC, AffectedArc07 approved these changes

2024-06-20 15:54 UTC, Sirryan2002 approved these changes

2024-06-29 18:23 UTC, lewcc approved these changes

2024-06-29 18:28 UTC, merged