Fixes Headset Sprites
ParadiseSS13/Paradise pull request #25979
Opened 2024-06-20 02:10 UTC by FaronCD

## What Does This PR Do

Fixes the right ear onmob sprite from overriding the left ear onmob sprite

## Why It's Good For The Game

Fixes #7514 

## Images of changes

## Testing

## Changelog
:cl:
fix: Fixed right ear onmob sprite overriding left ear onmob sprite
/:cl:

2024-06-20 02:12 UTC, Contrabang requested changes

2024-06-20 02:12 UTC, Contrabang commented on code/modules/mob/living/carbon/human/human_update_icons.dm
> +			right_ear_icon = l_ear.icon_override
```suggestion
			right_ear_icon = r_ear.icon_override
```

2024-06-21 13:15 UTC, Sirryan2002 approved these changes

2024-06-21 14:16 UTC, Contrabang approved these changes

2024-06-22 22:36 UTC, DGamerL approved these changes

2024-06-22 22:57 UTC, merged