Fixes clones being stuck mindslaved
ParadiseSS13/Paradise pull request #25981
Opened 2024-06-20 04:38 UTC by FaronCD

## What Does This PR Do

Fixes clones being stuck mindslaved after the original body had a mindslave implant

## Why It's Good For The Game

Fixes #11514 

## Images of changes

## Testing

Hosted two instances of paradise, mind slaved someone then killed them. Put the mind slave in a cloner and they popped out as a non slaved human.  Tested with mind shielded mind slave as well.
## Changelog
:cl:
fix: Fixed mobs being stuck mindslaved if cloned after receiving a mindslave bio-chip implant
/:cl:

2024-06-20 04:40 UTC, Contrabang requested changes

2024-06-20 04:40 UTC, Contrabang commented on code/game/machinery/clonepod.dm
> +	if(clone.mind.has_antag_datum(/datum/antagonist/mindslave)) //The Mindslave Bio-chip wont persist through cloning, but the mindslave would, becoming unremovable
Put this on `/datum/antagonist/proc/on_body_transfer` instead, and check that its mindslave biochip and not a thrall vampire

2024-06-21 13:14 UTC, Sirryan2002 approved these changes

2024-06-21 14:15 UTC, Contrabang approved these changes

2024-06-22 22:37 UTC, DGamerL approved these changes

2024-06-22 22:52 UTC, DGamerL requested changes
Empty testing section

2024-06-25 10:04 UTC, Burzah approved these changes

2024-06-25 10:34 UTC, DGamerL approved these changes

2024-06-25 10:37 UTC, merged