Pandemic no longer shows heart failure/shock
ParadiseSS13/Paradise pull request #25992
Opened 2024-06-21 05:12 UTC by LetXxx

## What Does This PR Do
Fixes #25987 

## Why It's Good For The Game
Fixes something that shouldn't show up.

## Testing
Hopped in, punched a monkey until it was crit, it developed shock/CF that showed up on scanners but not on the pandemic.

## Changelog
:cl:
fix: Shock and Cardiac Failure shouldn't show up on the pandemic anymore.
/:cl:

2024-06-21 05:16 UTC, Contrabang requested changes

2024-06-21 05:16 UTC, Contrabang commented on code/datums/diseases/critical.dm
> +	visibility_flags = HIDDEN_PANDEMIC
Put this on `/datum/disease/critical`, none of the critical viruses should be seen

2024-06-21 10:58 UTC, DGamerL approved these changes

2024-06-21 14:16 UTC, Contrabang approved these changes

2024-06-24 05:06 UTC, Sirryan2002 approved these changes

2024-06-28 03:27 UTC, merged