Do Not Resuscitate Status, Mechanics, and SoP
ParadiseSS13/Paradise pull request #26002
Opened 2024-06-22 00:41 UTC by matttheficus

# SoP Stuff (SUBJECT TO CHANGE VIA ITERATION W/ DEV/ADMIN TEAM)

### Do Not Resuscitate - Security (DNR-S)
1. All DNR-S notices must be authorized by a proper adjudicator. Any unauthorized DNR-S notices are to be considered Murder. If no authorized adjudicator is available as stated in these Standards, authorization must be given by Central Command.
2. DNR-S authorization for Prisoners who have confirmed via evidence to have committed a 5XX - Capital Crime and succumbed to injuries in conflict with Security must be given by the Magistrate. If there is no active Magistrate, the Captain may give authorization. In the events of a Code Red Alert and no active Captain, the Head of Security may authorize the notice.
3. DNR-S authorization for Prisoners who have escaped Permanent Confinement and Executed may be given by the Warden, Head of Security, Magistrate or Captain.
4. DNR-S authorization for Prisoners who have been Executed for all other legal reasons are authorized automatically by setting the Prisoner to Execute.
5. All DNR-S bodies must be placed in a Red DNR-S Bodybag. Upon storage, the name of the Prisoner and the approving adjudicator must be placed on the name tag.
6. The revival of any individual who is denoted as DNR-S status is considered Grand Sabotage.

### Do Not Resuscitate - Medical (DNR-M)
1. All DNR-M notices must be authorized by the proper adjudicator. Any unauthorized DNR-M notices are to be considered Murder. If no authorized adjudicator is available as stated in these Standards, authorization must be given by Central Command.
2. DNR-M authorization for suicide victims may be approved by the Coroner. The Chief Medical Officer may, at their discretion, override this decision. In the absence of any authorized Medical staff, the Captain may approve the DNR-M notice instead.
3. All DNR-M bodies must be placed in a Blue DNR-M Bodybag. Upon storage, the name of the patient and the approving adjudicator must be placed on the name tag.
4. The revival of any individual who is denoted as DNR-M status is not considered a crime. However, as per the Chief Medical Officer, it can be treated as misappropriation of Medical Supplies and dealt with via reprimand, removal of Morgue access, or demotion.

### Kill on Sight (KoS) Orders
1. All KoS notice must be authorized by a proper adjudicator by setting their status as DNR-S, regardless of their current medical status. Any unauthorized KoS notices are to be considered Murder. If no authorized adjudicator is available as stated in these Standards, authorization must be given by Central Command.
2. A KoS notice may only be considered in the case active large-scale mass casualty events, the widespread and purposeful destruction of the Station or Emergency Escape Shuttle’s integrity, or any threat listed under “Kill on Sight” within the Space Law Lethal Force chart.
3. KoS authorization for individuals who have confirmed via evidence to have met the requirements above must be given by the Magistrate. If there is no active Magistrate, the Captain may give authorization. In the events of a Code Red Alert and no active Captain, the Head of Security may authorize the notice.

---

## What Does This PR Do
Adds mechanics and systems to allow for more easily tracked and adjudicated DNR Notices to be placed by Security/Medbay.

These include:
- Separate bodybags for Medical and Security DNR Notices, as per SoP. New Morgue Tray lights as well.
- Security HUD Status for DNR-S. DNR-S is automatically applied to Medical Records when Execute status is set.

## Why It's Good For The Game
There is currently no real DNR SoP for the Crew. As such, some has been written up and approved provisionally, but needs some items added to the game.

## Images of changes
TBD

## Testing
TBD as I finish coding it up this weekend

## Changelog
:cl:
add: added DNR-S and DNR-M statuses and mechanics
add: added DNR-S and DNR-M bodbags
/:cl:

2024-06-22 02:14 UTC, Contrabang requested changes

2024-06-22 02:14 UTC, Contrabang commented on code/game/objects/items/bodybag.dm
> +	var/obj/structure/closet/body_bag/medical_dnr/R = new /obj/structure/closet/body_bag/medical_dnr(user.loc)
This should be a var on `/obj/item/bodybag` so that attack_self doesn't have to be copied 3 times

2024-06-24 02:09 UTC, matttheficus commented on code/game/objects/items/bodybag.dm
> +	var/obj/structure/closet/body_bag/medical_dnr/R = new /obj/structure/closet/body_bag/medical_dnr(user.loc)
yeahhhhh I copy/pasted for proof of concept - Ill avoid coding warcrimes once i do a pass over with the sprites coming up :xdd:

2024-06-24 05:09 UTC, Sirryan2002 commented on code/game/data_huds.dm
> +					holder.icon_state = "MMTODO"
:O

2024-06-25 23:06 UTC, Spaghetti-bit commented on code/game/data_huds.dm
> +					holder.icon_state = "MMTODO"
:OOOO

2024-08-17 23:44 UTC, Daylight2 commented
Small nitpick on the SOP: Setting someone to KOS without proper authorization should probably be attempted murder not murder, unless the person actually dies as a result.

2024-09-04 01:08 UTC, matttheficus commented
I currently dont have time to finish this, have some placeholder-esque sprites, and dont have the motivation to really do this in general with work + WoW xpac and some other games with IRL buddies.

Someone is fully free to take this PR if they so desire (I can give ya the sprites I do have) and/or go for the SoP changes alone in some form.

2024-09-04 01:08 UTC, closed without merging