add usesound to glass_containers
ParadiseSS13/Paradise pull request #26011
Opened 2024-06-23 00:25 UTC by pwbokie

## What Does This PR Do

Fixes #24553 by adding a sound to the /obj/item/reagent_containers/glass object. It's the same sound as all other components.

## Why It's Good For The Game

Building stuff that requires beakers is more satisfying now!

## Testing

Built a Protolathe. My ears were met with a glorious noise when adding beakers of any kind.

## Changelog
:cl:
add: beakers have a usesound now and will clunk when using them to build a machine
/:cl:

2024-06-24 05:12 UTC, Sirryan2002 requested changes

2024-06-24 05:12 UTC, Sirryan2002 commented on code/modules/reagents/reagent_containers/glass_containers.dm
> +	usesound = 'sound/items/deconstruct.ogg'
this needs to go above the `var/` declaration. Inherited vars -> Vars defined on this type

2024-07-01 22:14 UTC, Sirryan2002 commented
@pwbokie 
:)

2024-07-12 22:29 UTC, pwbokie commented
moved, sorry for delay!

2024-07-13 15:01 UTC, Burzah approved these changes

2024-07-13 20:42 UTC, Sirryan2002 approved these changes

2024-07-14 13:44 UTC, merged