[FEATURE/BALANK] Parrying with Chairs and Fighting Lions!
ParadiseSS13/Paradise pull request #26039
Opened 2024-06-26 02:15 UTC by Spaghetti-bit

## What Does This PR Do

Allows chairs, stools, and other bar brawling essential sitting devices to be wielded and allows them to parry melee attacks.

Wielding a chair allows you to do... ~20% more damage, parrying with a chair is god awful and will drain you of stamina... very fast unless you perfectly parry it.

You now set down chairs by Alt-clicking them.
## Why It's Good For The Game

Adds more finesse to that random assistant denizen. Makes bar brawls more interesting.
## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/f62aa6b7-c40e-4d36-a7d9-38419fe78774)

## Testing

Loaded an offline server, angered pete, kept him at pay with a bar stool.

## Changelog
:cl:
add: Chair parrying!
add: Chair wielding!
tweak: Chairs now have to be alt-clicked to be placed down, but also do not have to be held to upright them
/:cl:

2024-06-26 02:18 UTC, Ionward commented
you could always wield them before, chairs had a good knockdown chance and also could break when you swung em, but parrying is fun and a very classic visual

2024-06-26 02:23 UTC, Spaghetti-bit commented
> you could always wield them before, chairs had a good knockdown chance and also could break when you swung em, but parrying is fun and a very classic visual

Wield as in two handed wielding.

2024-06-26 02:30 UTC, Fordoxia approved these changes
Aside from this one thing, looks good.

2024-06-26 02:30 UTC, Fordoxia commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	/// Likely hood of smashing the chair.
```suggestion
	/// Likelihood of smashing the chair.
```

2024-07-09 18:06 UTC, Sirryan2002 requested changes

2024-07-09 18:06 UTC, Sirryan2002 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
>  	plant(user)
Did you test to make sure that players can't remotely (i.g. from more than 1 tile away) plant the chair just by alt clicking it from a distance?

2024-07-09 18:06 UTC, Sirryan2002 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +
Perhaps you should check the typepath here :)

2024-07-26 18:02 UTC, Sirryan2002 commented
@Spaghetti-bit

2024-07-28 20:20 UTC, Sirryan2002 approved these changes

2024-07-30 13:47 UTC, S34NW approved these changes

2024-07-30 13:53 UTC, merged