Necromantic Stone Refactor / Buff
ParadiseSS13/Paradise pull request #26035
Opened 2024-06-25 23:51 UTC by FaronCD

## What Does This PR Do
Updates necromantic stone code to fix #11205 
Buffs necromantic stones to let the wizard revive more skeletons past the cap, but with a cooldown
Updated mindslave to support different master hudicons for the wizard

## Why It's Good For The Game
Bugs bad
It was already easy to bypass the necromantic stones skeleton cap, I asked about changing it, and was told it was fine to replace it with this instead.

## Testing
Tested the code with multiple clients, it worked

## Changelog
:cl: EOD501
fix: Necromantic stones properly mindslave the thrall
tweak: The necromantic stone can thrall more mobs past its cap, but with a cooldown between use
tweak: Mindslaves can support unique maser hud icons
/:cl:

2024-06-28 03:03 UTC, DGamerL commented on code/game/gamemodes/wizard/artefact.dm
>  		return ..()
```suggestion
	if(!istype(victim) || !istype(necromancer))
		return ..()
```

2024-06-28 03:03 UTC, DGamerL commented on code/game/gamemodes/wizard/artefact.dm
>  		return
```suggestion
```

2024-07-07 19:28 UTC, Sirryan2002 requested changes

2024-07-07 19:28 UTC, Sirryan2002 commented on code/game/gamemodes/wizard/artefact.dm
> +		to_chat(necromancer, "<span class='notice'>The amount of skeleton thralls risen by [src] strains its power.")
```suggestion
		to_chat(necromancer, "<span class='notice'>The amount of skeleton thralls risen by [src] strains its power.</span>")
```

2024-07-07 19:28 UTC, Sirryan2002 commented on code/game/gamemodes/wizard/artefact.dm
> +			to_chat(necromancer, "<span class='warning'>[src] cannot rise another thrall for [DisplayTimeText(COOLDOWN_TIMELEFT(src, additional_thralls_cooldown))].")
```suggestion
			to_chat(necromancer, "<span class='warning'>[src] cannot rise another thrall for [DisplayTimeText(COOLDOWN_TIMELEFT(src, additional_thralls_cooldown))].</span>")
```

2024-07-07 19:28 UTC, Sirryan2002 commented on code/game/gamemodes/wizard/artefact.dm
> +	var/greet_text = "<span class='userdanger'>You have been revived by <B>[necromancer.real_name]!\n[necromancer.p_theyre(TRUE)] your master now, assist them even if it costs you your new life!</span>"
unclosed bold tag and HTML tags should be lowercase

2024-07-07 21:11 UTC, Sirryan2002 approved these changes

2024-07-09 06:31 UTC, Burzah commented on code/game/gamemodes/wizard/artefact.dm
> +		. += "[src] is being strained by the amount of risen skeletons thralls. It cannot be used to rise another skeleton thrall for <b>[DisplayTimeText(cooldown_time_left)]</span>."
Missing a span tag and class here.

2024-07-09 06:46 UTC, Burzah commented on code/game/gamemodes/wizard/artefact.dm
> +		. += "[src] is being strained by the amount of risen skeletons thralls. It cannot be used to rise another skeleton thrall for <b>[DisplayTimeText(cooldown_time_left)]</span>."
Fair enough. Thanks for taking care of it, either way.

2024-07-12 17:08 UTC, Burzah commented on code/game/gamemodes/wizard/artefact.dm
> +		. += "[src] is being strained by the amount of risen skeletons thralls. It cannot be used to rise another skeleton thrall for <b>[DisplayTimeText(cooldown_time_left)]."
Well you took care of the span which I thank you for. Though now the `<b>` needs to either be removed, or given a closing tag.

2024-07-12 22:37 UTC, Burzah approved these changes

2024-07-12 22:37 UTC, Burzah commented on code/game/gamemodes/wizard/artefact.dm
> +	victim.visible_message("<span class='warning'> A massive amount of flesh sloughs off [victim] and a skeleton rises up!</span>")
```suggestion
	victim.visible_message("<span class='warning'>A massive amount of flesh sloughs off [victim] and a skeleton rises up!</span>")
```

2024-07-12 22:37 UTC, Burzah commented on code/game/gamemodes/wizard/artefact.dm
> +		to_chat(necromancer,"<span class='warning'>There is no soul connected to this body...</span>")
```suggestion
		to_chat(necromancer, "<span class='warning'>There is no soul connected to this body...</span>")
```

2024-07-15 21:51 UTC, DGamerL commented on code/game/gamemodes/wizard/artefact.dm
> +		. += "[src] is being strained by the amount of risen skeletons thralls. It cannot be used to rise another skeleton thrall for <b>[DisplayTimeText(cooldown_time_left)]</b>."
`DisplayTimeText` works properly, but it can be heavily simplified here as the cooldown in 99% of cases won't exceed a minute

2024-07-17 20:40 UTC, DGamerL approved these changes
Last things!

2024-07-17 20:40 UTC, DGamerL commented on code/game/gamemodes/wizard/artefact.dm
> +	if(unlimited || living_skeletons < max_skeletons)
Can you put the `unlimited` check at the top?

2024-07-17 20:40 UTC, DGamerL commented on code/game/gamemodes/wizard/artefact.dm
> +	listclearnulls(active_skeletons)
```suggestion
/obj/item/necromantic_stone/proc/check_skeletons()
	. = FALSE
	listclearnulls(active_skeletons)
```
To make it clear that we're returning `FALSE` if we don't succeed the check

2024-07-19 23:47 UTC, DGamerL approved these changes

2024-07-19 23:51 UTC, merged