Pimp coat remaster
ParadiseSS13/Paradise pull request #26040
Opened 2024-06-26 04:40 UTC by McRamon

## What Does This PR Do
Resprites pimp coat and adds 2 more:
White one, 2 times cheaper and available in clothes vendor, contraband section.
Tan one - unique coat, that can be found in QM locker, with following stats:
![image](https://github.com/ParadiseSS13/Paradise/assets/31545294/836c990a-7ea4-402b-8590-fa9f4f499a1e)
Can hold same items as otehr QM suits.

## Why It's Good For The Game
Better lookign drip, more of it and a unique item for QM to feel special. Out of all head jobs QM is the one that feels like could have not exactly regulated attire by corporate standards.

If design team decides that QM shouldn't have this additional unique piece of clothes or balance team somehow thinks that armor is bad balance wise, it can be changed.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/31545294/bec8f75f-c8fe-4fdf-a83d-7286621e559e)

## Testing
Dressed up some humanised monkeys.

## Changelog
:cl:
add: 2 new pimp coats - one in vendor and 1 specially for QM.
imageadd: New sprites for existing pink coat.
/:cl:

2024-06-26 16:19 UTC, PopeDaveThe3th requested changes
Some minor grammar and sentence flow issues but the coats look very nice.

2024-06-26 16:19 UTC, PopeDaveThe3th commented on code/modules/clothing/suits/misc_suits.dm
> +	desc = "Very fluffy white coat, made out of quality synthetic fur."
```suggestion
	desc = "A very fluffy white coat, made out of high-quality synthetic fur."
```

2024-06-26 16:19 UTC, PopeDaveThe3th commented on code/modules/clothing/suits/misc_suits.dm
> +	desc = "Very fluffy tan coat, made out of the finest fur from the Earth. Gifted to Quartermaster of Nanotrasen. Has additional layer of protection against harsh environment of Lavaland and a strap t
```suggestion
	desc = "A very fluffy tan coat, made out of real fur imported from Earth. A symbol of status often given to Nanotrasen Quartermasters. Has an additional layer of protective materials for defense against harsh environments, and a strap to hold equipment."
```

2024-06-27 12:41 UTC, PopeDaveThe3th approved these changes

2024-06-27 13:23 UTC, Fordoxia approved these changes
Proper pimpin'. Taken through the hood, approved, and then taken out to dinner.

2024-06-28 16:46 UTC, Sirryan2002 approved these changes

2024-07-02 17:21 UTC, closed without merging