Adds cult action bar
ParadiseSS13/Paradise pull request #26052
Opened 2024-06-26 23:40 UTC by HMBGERDO

## What Does This PR Do

This PR adds back cult action bar that was removed after https://github.com/ParadiseSS13/Paradise/pull/24482
This bar will automatically contain cult actions and may be used for any other actions like default bar on the top
fixes https://github.com/ParadiseSS13/Paradise/issues/24863

## Why It's Good For The Game

Bugs bad. More userfriendly UI good

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/61080616/36891cd6-43b7-4cfe-88cb-2d4dfe10ef5c)

## Testing

Compiled, moved around some action buttons, made sure no runtimes pop up

## Changelog
:cl:
add: Cult spell bar is available for any actions you want
fix: Cult spells buttons once again in the bottom part of the screen
/:cl:

2024-06-28 04:42 UTC, Spaghetti-bit requested changes
Minor request, ping me in discord when you do this and I'll approve ASAP. <3

2024-06-28 04:42 UTC, Spaghetti-bit commented on code/__DEFINES/action_button_defines.dm
> +#define SCRN_OBJ_CULT_LIST "cultlist"
```suggestion
#define SCRN_OBJ_CULT_LIST "cult_list"
```
for readability, change to `cult_list`.

2024-06-28 17:01 UTC, Spaghetti-bit approved these changes

2024-06-29 20:50 UTC, Sirryan2002 requested changes
one thing, otherwise this looks good

2024-06-29 20:50 UTC, Sirryan2002 commented on code/game/gamemodes/cult/blood_magic.dm
> +	default_button_position = SCRN_OBJ_CULT_LIST
this needs to go above the variables defined on it's type
Type Definition -> Inherited Vars -> Newley Defined Vars

2024-06-29 21:02 UTC, Spaghetti-bit approved these changes
Re-approving after new review due to new commits.

2024-06-29 23:28 UTC, Sirryan2002 approved these changes

2024-07-01 02:30 UTC, lewcc approved these changes
Thanks for handling this 👍

2024-07-01 10:55 UTC, HMBGERDO commented
this PR doesnt touch 
![image](https://github.com/ParadiseSS13/Paradise/assets/61080616/4499a0f1-d620-4d43-928a-96158ac248f8)

2024-07-01 23:18 UTC, merged