Prevent maintenance drones from using chem dispensers.
ParadiseSS13/Paradise pull request #26058
Opened 2024-06-27 05:09 UTC by FunnyMan3595

## What Does This PR Do
Prevent maintenance drones from using chem dispensers.

## Why It's Good For The Game
It's only a vector to break their laws and/or the rules.

## Testing
Spawned as drone. Couldn't use.
Reincarnated as chemist. Could use.
Transformed to robot. Could use.

## Changelog
:cl:
del: Maintenance drones can no longer use chem dispensers.
/:cl:

2024-06-27 11:26 UTC, Contrabang requested changes

2024-06-27 11:26 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	if(isdrone(user))
Emagged drones should probably be allowed to access them

2024-06-27 11:26 UTC, Contrabang commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		// There's nothing a drone can do here that wouldn't violate their laws and/or the rules.
There should probably be a to_chat here explaining to the drone they cant use a chem dispenser, probably with a warning span class

2024-06-28 04:51 UTC, Spaghetti-bit approved these changes

2024-06-28 13:33 UTC, Contrabang approved these changes

2024-07-01 06:18 UTC, lewcc approved these changes

2024-07-01 06:22 UTC, merged