Slightly Tweaks the Cyberiad AI Satellite
ParadiseSS13/Paradise pull request #26067
Opened 2024-06-27 21:41 UTC by Fordoxia

## What Does This PR Do
Reduces the number of overlapping wallbumps.

Makes the vent system's pipes not set off my pain receptors.

Makes the foyer and maintenance rooms slightly larger and rearranges the furniture.

Moves the portable scrubbers into the maintenance halls.

Removes two racks with crowbars and welding masks. There's already a set of toolboxes and a mask in the east maintenance room.

All of the cheap nasty metal tables have been replaced with nice expensive reinforced tables.

Two new tables added to the AI sat antechamber.

Relocated the Red Phone from the foyer to the antechamber.

Gave the AI a strong windoor.

## Why It's Good For The Game
Nicer distribution of wallbumps.

The west maint room was a cluttered to hell.

p i p e   p a i n.

Most light switches are now located by the doors so you can easily flick them on when you walk in. Like in real life.

Antechamber now more strongly resembles GLaDOS' antechamber.

The empty spot where you exit the transit tubes was just BEGGING for the O2 locker to be slot in there.

AI windoor should be stronk. It's fuckin' expensive.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/143041327/60d603b7-23a2-4572-9ccf-2fe4c80f5f54)
![image](https://github.com/ParadiseSS13/Paradise/assets/143041327/1fe163d9-9965-43b9-bde9-e9578d9fa879)

## Testing
Visited and did a tour of the sat.

## Changelog
:cl:
tweak: Tweaked the Cyberiad AI sat. See the full changelog for details.
/:cl:

2024-07-30 15:44 UTC, Burzah requested changes
The PR description and what it does needs to be updated properly. Enough is enough with this. I want to see what the PR does from the title, and from the description. The Change log also needs to be updated properly for all the changes you have made. All the changes need to be documented properly. Leave the memes for coding chat and off your PRs. We want to know what the changes are without having to read through and decipher it.

2024-07-30 15:47 UTC, FunnyMan3595 requested changes

2024-07-30 15:50 UTC, DGamerL commented on _maps/map_files/stations/boxstation.dmm
> +/obj/machinery/door/window/reinforced/reversed{
(It doesn't)

2024-07-30 16:01 UTC, Fordoxia commented on _maps/map_files/stations/boxstation.dmm
> +/obj/machinery/door/window/reinforced/reversed{
Change made.

2024-08-02 21:17 UTC, warriorstar-orion approved these changes
LGTM

2024-08-04 04:13 UTC, Burzah approved these changes
Lgtm

2024-08-11 17:40 UTC, FunnyMan3595 approved these changes

2024-08-11 21:59 UTC, merged