Adds Nightvision Chameleon Glasses
ParadiseSS13/Paradise pull request #26075
Opened 2024-06-28 17:10 UTC by HMBGERDO

## What Does This PR Do

This PR adds nightvision chameleon glasses, similar to nightvision googles but chameleon, to traitor uplink for 5 TC

## Why It's Good For The Game

While we have nightvision module with cost of 5 TC for a modsuit, we have nothing for people who dont wear modsuit. You can buy thermals for 15 TC but like, sometimes you dont have 15 TC and thermal doesnt provide as good nightvision as actual nightvision googles.

## Testing

Compiled, checked traitor uplink, bought glasses.

## Changelog
:cl:
add: Nightvision Chameleon Glasses is now available in all uplinks with cost of 5 TC. Its same as nightvision googles, but chameleon. Watch your eye damage, agents.
/:cl:

2024-06-28 17:18 UTC, Spaghetti-bit requested changes
code looks good.

2024-06-28 17:18 UTC, Spaghetti-bit commented on code/datums/uplink_items/uplink_general.dm
> +/datum/uplink_item/stealthy_tools/thermal
```suggestion
/datum/uplink_item/stealthy_tools/thermal/chamnightvision
```

Your new datum had the exact same path as regular thermals. I don't think these new glasses are thermals ^v^

2024-06-28 17:21 UTC, Spaghetti-bit commented on code/datums/uplink_items/uplink_general.dm
> +/datum/uplink_item/stealthy_tools/thermal
Good to resolve, outdated. @HMBGERDO

2024-06-28 17:42 UTC, 1080pCat approved these changes

2024-06-28 17:42 UTC, 1080pCat commented on code/datums/uplink_items/uplink_general.dm
> +/datum/uplink_item/stealthy_tools/thermal
why is this under thermals? 
should really be pathed `...stealthy_tools/nightvision`

2024-07-01 19:29 UTC, Sirryan2002 approved these changes

2024-07-11 02:23 UTC, DGamerL approved these changes

2024-07-11 02:27 UTC, merged