Lets the players know that they can steal just the photo of the blueprints instead of the entire thing.
ParadiseSS13/Paradise pull request #26086
Opened 2024-06-29 18:36 UTC by tipoima

## What Does This PR Do
Theft objectives that accept a photo of an item (currently only being the blueprints) now state that outright

## Why It's Good For The Game
As far as I know, the only place mentioning this is the "High-Risk Items" page on the wiki. It's good to explain a mechanic in-game.

## Testing
Turned myself into a traitor until I rolled blueprints theft. Saw the new message. Did not see the message on any other objective.

## Changelog
:cl:
tweak: Blueprints theft objective now explains that a photo of the blueprints also counts.
/:cl:

2024-06-29 18:39 UTC, Contrabang requested changes

2024-06-29 18:39 UTC, Contrabang commented on code/game/gamemodes/objective.dm
> +	if(/obj/item/photo in steal_target.altitems)
I'd rather you make this a var on steal_target, something like
```suggestion
	explanation_text += steal_target.extra_information
```

2024-06-30 09:05 UTC, Spaghetti-bit approved these changes

2024-06-30 10:14 UTC, S34NW commented
Hey there, although this is technically not a fix or refactor and thus should fall under the freeze rules, we have decided to permit it. This is due to the fact the freeze has only just begun and the size of this change.
Please familiarise yourself with the freeze rules for the coming month before making another PR. ❤️

2024-06-30 10:21 UTC, tipoima commented
> Hey there, although this is technically not a fix or refactor and thus should fall under the freeze rules, we have decided to permit it. This is due to the fact the freeze has only just begun and the size of this change. Please familiarise yourself with the freeze rules for the coming month before making another PR. ❤️

I've seen the announcement, it's just that I wasn't sure if it would qualify as a fix or an addition; and people on discord said it's fine. I suppose I should've just waited instead.

2024-06-30 20:35 UTC, Fordoxia requested changes

2024-06-30 20:35 UTC, Fordoxia commented on code/game/gamemodes/steal_items.dm
> +	extra_information = "Stealing a photograph of the item is also an option."
```suggestion
	extra_information = "Obtaining a photograph of the blueprints is also an option."
```
Minor wording change + explicitly saying it's the blueprints you want to photograph.

2024-07-01 14:21 UTC, Contrabang approved these changes

2024-07-02 00:19 UTC, lewcc approved these changes

2024-07-02 00:23 UTC, merged