Fixes eyestabbing not dealing a correct amount of damage
ParadiseSS13/Paradise pull request #26095
Opened 2024-06-30 20:18 UTC by BiancaWilkson

## What Does This PR Do

Changes eyestabs from dealing a flat 7 damage to dealing damage based on the force of the object you're stabbing with. Fixes #25161
## Why It's Good For The Game

Damage should be consistent

## Testing

Used health scanner to check how much damage each item was dealing
## Changelog
:cl:
fix: Stabbing someone in the eye now deals the correct amount of damage
/:cl:

2024-06-30 20:21 UTC, Fordoxia approved these changes
Code looks good to me.

RIP the +2 bonus damage tho.

2024-06-30 20:34 UTC, DGamerL approved these changes
This entire proc is a fucking sin, this is due a refactor

2024-06-30 20:35 UTC, DGamerL requested changes

2024-06-30 20:35 UTC, DGamerL commented on code/game/objects/items.dm
> +				head.receive_damage(force)
```suggestion
				head.receive_damage(force, TRUE)
```
Actually it still needs this

2024-07-01 00:42 UTC, DGamerL approved these changes

2024-07-01 18:58 UTC, merged