Fixed telekinesis putting beaker in hand when swapped
ParadiseSS13/Paradise pull request #26130
Opened 2024-07-03 00:19 UTC by EmeraldCandy

## What Does This PR Do
fixes #24684

Doesnt put a beaker in hand when swapping it out with telekinesis

## Why It's Good For The Game
bugs bad

## Testing
spawned in as chemist
stepped near a chem dispenser and placed in/swapped beakers
stepped away and couldnt insert beakers
gave telekinesis to self
inserted beaker into machine, beaker popped out on top of dispenser

## Changelog
:cl:
fix: Fixed telekinesis putting beaker in hand when swapped
/:cl:

2024-07-05 17:48 UTC, Sirryan2002 approved these changes
I recommend adding a comment about telekinesis next to your checks

2024-07-05 21:43 UTC, EmeraldCandy commented
> I recommend adding a comment about telekinesis next to your checks

Done! :>

2024-07-07 13:12 UTC, DGamerL requested changes

2024-07-07 13:12 UTC, DGamerL commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +			if(Adjacent(usr) && !issilicon(usr)) //Prevents telekinesis from putting in hand
Use `user` not `usr` here

2024-07-07 13:12 UTC, DGamerL commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			if(Adjacent(usr) && !issilicon(usr)) //Prevents telekinesis from putting in hand
Same here

2024-07-08 20:01 UTC, DGamerL approved these changes

2024-07-08 20:05 UTC, merged