Changes even more uses of `stat` comparisons to use the defines
ParadiseSS13/Paradise pull request #26154
Opened 2024-07-06 00:11 UTC by DGamerL

## What Does This PR Do
Makes even more checks of `stat` use the defines instead of magic numbers
Example
```js
if(stat < 2) -> if(stat != DEAD)
if(stat > 0) -> if(stat != CONSCIOUS)
if(stat > 1) -> if(stat == DEAD)
etc
```

## Why It's Good For The Game
This is more readable and according to our standards

## Testing
It compiled
There is a chance that I may accidentally have left a change in for machinery, but I've looked at the changed lines aswell

## Changelog
NPFC

2024-07-06 00:15 UTC, DGamerL reviewed
Sloppy

2024-07-06 00:15 UTC, DGamerL commented on code/game/machinery/doors/door.dm
> +	if(stat == CONSCIOUS) //So that only powered doors are closed.
```suggestion
	if(!stat) //So that only powered doors are closed.
```

2024-07-06 00:15 UTC, DGamerL commented on code/game/machinery/doors/door.dm
> +	if(stat == CONSCIOUS) //Opens only powered doors.
```suggestion
	if(!stat) //Opens only powered doors.
```

2024-07-06 00:15 UTC, DGamerL commented on code/game/machinery/machinery.dm
> +	if(power_state && stat == CONSCIOUS)
```suggestion
	if(power_state && !stat)
```

2024-07-06 00:15 UTC, DGamerL commented on code/modules/power/engines/singularity/particle_accelerator/particle_control.dm
> +	else if(stat == CONSCIOUS && construction_state <= 3)
```suggestion
	else if(!stat && construction_state <= 3)
```

2024-07-06 00:15 UTC, DGamerL commented on code/modules/power/engines/singularity/particle_accelerator/particle_control.dm
> +	if((stat & NOPOWER) || (stat == CONSCIOUS && construction_state <= 3)) //Only update the part icons if something's changed (i.e. any of the above condition sets are met).
```suggestion
	if((stat & NOPOWER) || (!stat && construction_state <= 3)) //Only update the part icons if something's changed (i.e. any of the above condition sets are met).
```

2024-07-06 00:15 UTC, DGamerL commented on code/modules/power/generators/treadmill.dm
> +	if(speed && stat == CONSCIOUS && anchored && powernet)
```suggestion
	if(speed && !stat && anchored && powernet)
```

2024-07-07 19:20 UTC, Sirryan2002 approved these changes

2024-07-07 22:11 UTC, hal9000PR requested changes
then it can be merged

2024-07-07 22:56 UTC, hal9000PR approved these changes

2024-07-07 23:00 UTC, merged