Various Rollie Refactors and Midori Tabako Cigarettes
ParadiseSS13/Paradise pull request #26165
Opened 2024-07-06 09:51 UTC by wanderso

Gave custom-made rollies a smoke_time so that they could be used again as cigarettes.

Changed the smoketime variable to smoke_time, as per snail_case naming convention used elsewhere in the code.

Removed marijuana chems from Midori Tabako cigarettes and re-added nicotine. Changed their trash left over after smoking to a cigarette butt rather than a roach because the description text on roach implies marijuana.

## What Does This PR Do
Fixes #26160. Changes Midori Tabako cigarettes, available from a vending machine and the loadout menu, to contain nicotine as they originally did rather than marijuana - 'Tabako' is in the name, after all. They also leave behind a cigarette butt instead of a roach because the roach's description text implies marijuana. (While I'm not as familiar with what the Midori Tabako designers originally intended, I believe they're just supposed to be Foreign.) 

Also changed the smoketime variable to be named smoke_time, as per our naming conventions.

## Why It's Good For The Game
Re-enables custom cigarette production, and allows nicotine-addicted smokers to use weird foreign cigarettes, just like in their Japanese animes.

## Testing
Burnt everything with a smoke_time variable to make sure that it took approximately the same amount of time. Smoked a Midori Tabako before and after the change - verified that it now contains tobacco again instead of cannabis. Made a bunch of custom cigarettes and found that the smoke_time variable now appropriately causes the cigarette to burn out when it's out of reagents.

## Changelog
:cl:
fix: Fixed hand-rolled cigarettes
tweak: Made Midori Tabako cigarettes, you know, contain Tabako
/:cl:

2024-07-06 09:51 UTC, wanderso commented
Thanks to DGamerL for making a better 'create custom cigarette' code than I did - I included the code from his refactor in his own pull request after I noticed that he did it at the same time I did.

2024-07-06 12:06 UTC, Fordoxia commented
I am reasonably that Midori Tabako (lit. "Green Cigarette") are supposed to contain weed, given both the name and the fact that the description says that they smell funny.

2024-07-06 14:06 UTC, Fordoxia approved these changes
Smokes good to me.

2024-07-07 19:15 UTC, Sirryan2002 approved these changes

2024-07-09 01:30 UTC, wanderso reviewed
Removed tab

2024-07-09 22:44 UTC, wanderso commented
God. Okay, actually tested this, unlike the other branch this one should actually work. There's probably still bugs in it - some of the stuff seems suspicious - but this actually does allow for the smoking of custom cigarettes

2024-07-10 03:34 UTC, Sirryan2002 requested changes

2024-07-10 03:34 UTC, Sirryan2002 commented on code/game/objects/items/weapons/cigs.dm
> +			var/obj/item/clothing/mask/cigarette/rollie/custom/custom_rollie  = new /obj/item/clothing/mask/cigarette/rollie/custom(user.loc)
```suggestion
			var/obj/item/clothing/mask/cigarette/rollie/custom/custom_rollie = new /obj/item/clothing/mask/cigarette/rollie/custom(user.loc)
```

2024-07-10 03:36 UTC, DGamerL approved these changes
Please do a merge master!

2024-07-10 03:36 UTC, DGamerL requested changes
Wrong button, my bad

2024-07-26 16:16 UTC, Sirryan2002 commented
@wanderso

2024-07-30 12:35 UTC, DGamerL commented
PR has been a few weeks since last activity, this PR will be closed for now.
Feel free to DM/Ping me on discord when you've made the changes and deconflicted the PR!

2024-07-30 12:35 UTC, closed without merging