Makes faragus actually playable (fixes a few tiles that were misaligned decal wise)
ParadiseSS13/Paradise pull request #26259
Opened 2024-07-19 14:45 UTC by 1080pCat

## What Does This PR Do

title
closes #26253

## Why It's Good For The Game

decals were misaligned, making faragus completely unplayable.
this'll hopefully make it a liked map
## Images of changes

![StrongDMM_qaQTj9L4v7](https://github.com/user-attachments/assets/923c5fd4-cdaa-45b0-ac1b-9a26e08e4a47)

## Testing

compiled into faragus, looked at tiles
## Changelog
:cl:
fix: Fixed a few misaligned tile decals on faragus
/:cl:

2024-07-19 22:20 UTC, Fordoxia commented
LGTM.

2024-07-19 22:20 UTC, Fordoxia approved these changes

2024-07-30 14:00 UTC, Burzah requested changes
Please change the title so its clear and add additional information to the `What Does This PR Do` section. Pointing at the title is not sufficient. Reviewers need to know what the PR does by looking at it from those two things. Thanks.

2024-07-30 21:47 UTC, 1080pCat commented
> Please change the title so its clear and add additional information to the `What Does This PR Do` section. Pointing at the title is not sufficient. Reviewers need to know what the PR does by looking at it from those two things. Thanks.

done

2024-08-01 12:07 UTC, Burzah approved these changes

2024-08-01 13:09 UTC, merged