Getting Medieval - Snakesfang
ParadiseSS13/Paradise pull request #26296
Opened 2024-07-26 02:27 UTC by PollardTheDragon

## What Does This PR Do
This PR adds a new melee weapon - the snakesfang sword. The sword comes with its own scabbard as well, to carry them. It does sharp damage and can be sharpened with a whetstone. It costs 25 TC to purchase.

This PR is part of #25282 that was made more atomic to each item, per development team request.

## Why It's Good For The Game
More variety of weapons is good.  Provides the budgeting traitor with a decent melee weapon option at lower cost than an esword.

## Images of changes
![image](https://github.com/ParadiseSS13/Paradise/assets/144391971/a2a9b2b3-60ee-46f8-8281-42b9568eaa1c)

## Testing
Chopped up a lot of skrell. Bought a lot of swords. Was in TM for a fairly long time.

## Changelog
:cl:
add: Snakesfang
/:cl:

2024-07-28 20:06 UTC, Sirryan2002 requested changes

2024-07-28 20:06 UTC, Sirryan2002 commented on code/game/objects/items/weapons/storage/belt.dm
> +	update_icon()
```suggestion
	update_appearance(UPDATE_ICON_STATE)
```

2024-07-28 20:06 UTC, Sirryan2002 commented on code/game/objects/items/weapons/storage/belt.dm
> +	update_icon()
```suggestion
	update_appearance(UPDATE_ICON_STATE)
```

2024-07-28 22:06 UTC, Sirryan2002 approved these changes

2024-07-29 17:09 UTC, DGamerL approved these changes

2024-07-29 17:09 UTC, DGamerL commented on code/game/objects/items/weapons/melee/melee_misc.dm
> +	needs_permit = TRUE
```suggestion
```
Every `/melee` needs a permit!

2024-07-30 13:50 UTC, merged