Corrects the price comments for the bundles
ParadiseSS13/Paradise pull request #26293
Opened 2024-07-25 21:35 UTC by 1080pCat

## What Does This PR Do

Pretty much the title, corrects alot of the prices for the syndicate bundles, as alot of them were outdated
## Why It's Good For The Game

correct prices for referencing is good
## Testing

compiles, just comment changes

## Changelog
NPFC

2024-07-26 04:31 UTC, Contrabang requested changes

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/clothing/under/chameleon, // 1TC 10tc divided over 10 items.
More readability, and standardized tc to TC
```suggestion
		/obj/item/clothing/under/chameleon, // 1TC. 10TC divided over 10 items from the chameleon kit.
```

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/storage/box/syndie_kit/stechkin, // 26TC 20tc for stech, plus the 2 mags at 3 tc
```suggestion
		/obj/item/storage/box/syndie_kit/stechkin, // 26TC. 20TC for stechkin, plus the 2 mags at 3TC
```

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/storage/box/syndie_kit/stechkin, // 26TC 20tc for stech, plus the 2 mags at 3 tc
ditto

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/storage/box/syndie_kit/stechkin, // 26TC 20tc for stech, plus the 2 mags at 3 tc
ditto

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/autosurgeon/organ/syndicate/oneuse/hardened_heart, // 0TC decent stamina regen.
```suggestion
		/obj/item/autosurgeon/organ/syndicate/oneuse/hardened_heart, // 0TC decent stamina regen, but no speed/healing.
```

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/storage/belt/utility/full/multitool, // 0TC normal toolbelt, normal tools.
```suggestion
		/obj/item/storage/belt/utility/full/multitool, // 0TC
```

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
>  		/obj/item/clothing/shoes/combat) // 0 TC
All of these should be standized to `0TC` format too.

2024-07-26 04:31 UTC, Contrabang commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/pinpointer/advpinpointer, // 10tc, get dat fuckin disk
While you're here, can you capitalize all these into the `10TC` format?

2024-07-26 18:03 UTC, Sirryan2002 approved these changes

2024-07-29 11:47 UTC, DGamerL approved these changes

2024-07-29 11:47 UTC, DGamerL commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		/obj/item/clothing/under/chameleon, // 1TC 10tc divided over 10 items.
```suggestion
		/obj/item/clothing/under/chameleon, // 1TC. 10TC divided over 10 items.
```

2024-07-30 15:04 UTC, Contrabang approved these changes

2024-07-30 16:19 UTC, Burzah approved these changes

2024-07-30 16:23 UTC, merged