Fixes invisible TTV tanks
ParadiseSS13/Paradise pull request #26307
Opened 2024-07-26 21:06 UTC by FaronCD

## What Does This PR Do
If there isnt an icon state for the tank, itll default to "oxygen"

I would add sprites but I hate sprites and I cant do sprites on my phone, i might get to it eventually
## Why It's Good For The Game
Fixes #12802 

## Testing
Put a tank in the defines list in the TTV, overlay updated to tanks icon state, put a tank not in the defines list in the TTV, overlay updated to "oxygen" icon state

## Changelog
:cl: EOD501
fix: Fixes invisible TTV tank overlays
/:cl:

2024-07-28 19:27 UTC, Sirryan2002 requested changes

2024-07-28 19:27 UTC, Sirryan2002 commented on code/game/objects/items/devices/transfer_valve.dm
> +			tank_one_icon_state = "oxygen"
please put a stack_trace in here, we want this to runtime if there's icon fuckery afoot

2024-07-29 04:11 UTC, Sirryan2002 approved these changes

2024-07-29 14:45 UTC, Burzah approved these changes

2024-07-29 15:03 UTC, S34NW approved these changes

2024-07-29 15:07 UTC, merged