Fixes medical grippers not being usable in surgery
ParadiseSS13/Paradise pull request #26311
Opened 2024-07-27 03:30 UTC by Migratingcocofruit

## What Does This PR Do
fixes  #24594

## Why It's Good For The Game
fixes stuff

## Images of changes

## Testing
Spawned human mob, dragged it over a bunch of shrapnel and removed them via surgery as a medborg.

## Changelog
:cl:
fix: Medical grabber now works in surgery
/:cl:

2024-07-28 19:50 UTC, Sirryan2002 requested changes
Putting a hold on this PR. This is not the way to fix this issue... yes technically... this makes medical grippers work and doesn't break other things. However, this is snowflaking a type check into a very nicely written surgery system.

The problem is that the gripper is considered the `tool` here instead of just being treated as a standard hand like it would be for carbon surgeons. What needs to happen is that a tool should not be passed here (i.g. the gripper) and some procs like `put_into_hand()` should be refactored for silicons to be able to accept shrapnel.

2024-07-28 19:51 UTC, Sirryan2002 commented
@lewcc I would definitely like your two sense here

2024-07-28 21:09 UTC, Migratingcocofruit commented
> Putting a hold on this PR. This is not the way to fix this issue... yes technically... this makes medical grippers work and doesn't break other things. However, this is snowflaking a type check into a very nicely written surgery system.
> 
> The problem is that the gripper is considered the `tool` here instead of just being treated as a standard hand like it would be for carbon surgeons. What needs to happen is that a tool should not be passed here (i.g. the gripper) and some procs like `put_into_hand()` should be refactored for silicons to be able to accept shrapnel.

This check existed already for normal surgery steps, but was missing from proxy surgery steps specifically. I do agree, however.

As things stand the tool used in surgery is given from get_active_hand(), which is used everywhere. If a gripper returns null like a hand would that would break a lot of code. 
Maybe have a typecache of all things considered a hand for the purpose of surgery, then set tool to null if it's one of those?
It's still not very pretty and only covers surgery, but at least it condenses everything to one check against a list.

2024-07-29 21:52 UTC, lewcc requested changes
Given that this is the Specialized Surgery tool, and we really only want to scope its behavior to surgery so it doesn't do more hand-like things than it should, I don't think we should really bring this further up the chain. In principle, I mostly agree with this change.

I'd suggest adding a roundstart trait to the gripper which gets checked here, something like `TRAIT_SURGICAL_OPEN_HAND`, instead of just checking the raw typepath.

2024-07-30 00:53 UTC, Fordoxia commented
Remember also that the Universal Gripper exists, and should also be capable of performing surgery.

2024-07-30 12:30 UTC, Migratingcocofruit commented
> Given that this is the Specialized Surgery tool, and we really only want to scope its behavior to surgery so it doesn't do more hand-like things than it should, I don't think we should really bring this further up the chain. In principle, I mostly agree with this change.
> 
> I'd suggest adding a roundstart trait to the gripper which gets checked here, something like `TRAIT_SURGICAL_OPEN_HAND`, instead of just checking the raw typepath.

Added the traits and tested again; it works. Could you have a look at the code just to make sure it's up to standard?

2024-07-30 15:51 UTC, Sirryan2002 approved these changes

2024-08-07 00:01 UTC, lewcc approved these changes

2024-08-07 00:05 UTC, merged

2024-08-07 00:26 UTC, BAGELMENSK commented
If you can make it so that the Mediborg can pick up organs for surgery, that'd really complete the experience. Engiborg already has their part gripper so its not without precedent.

2024-08-07 03:29 UTC, Fordoxia commented
> If you can make it so that the Mediborg can pick up organs for surgery, that'd really complete the experience. Engiborg already has their part gripper so its not without precedent.

Feature freeze.

Also outside of that, design doesn't like the idea of mediborgs being able to grab organs.