Fixes tether module being able to tether yourself
ParadiseSS13/Paradise pull request #26403
Opened 2024-08-05 18:31 UTC by BiancaWilkson

## What Does This PR Do

Fixes #23414 by checking if the target and source are on the same turf.
## Why It's Good For The Game

I promise no one is _trying_ to grapple their own modsuit that they're already wearing.

## Testing

Made sure trying to tether myself or any of my items didn't work, made sure failing to tether myself didn't put the module on cooldown.
## Changelog
:cl:
fix: Modsuit tether module can no longer tether to anything already on your tile
/:cl:

2024-08-06 01:07 UTC, 1080pCat commented on code/modules/mod/modules/modules_engineering.dm
> +	if(get_turf(target) == get_turf(src)) //Put this check before the parent call so the cooldown won't start if it fails
```suggestion
	if(get_turf(target) == get_turf(src)) // Put this check before the parent call so the cooldown won't start if it fails
```

2024-08-06 17:28 UTC, Spaghetti-bit approved these changes

2024-08-06 20:04 UTC, Spaghetti-bit requested changes
Fix up the change log fix, there's a typo. `long` -> `longer`

2024-08-06 20:43 UTC, Burzah commented
> Fix up the change log fix, there's a typo. `long` -> `longer`

Should be good now, if you want to take a look again.

2024-08-06 23:29 UTC, lewcc approved these changes

2024-08-07 07:53 UTC, Burzah approved these changes

2024-08-07 07:57 UTC, merged