IPC Clowns and Mimes now heal from the Clown and Mime drinks.
ParadiseSS13/Paradise pull request #26533
Opened 2024-08-18 17:07 UTC by WenlockTheBritishHobo

## What Does This PR Do
This PR makes it so the Clown and Mime drinks heal IPCs in addition. Said drinks are: Banana Juice, Banana Honk, Nothing, Silencer.

## Why It's Good For The Game
The drinks in question heal based on the Organic being a Clown or Mime, depending on the drink. So it seems like an oversight for the drinks to not heal IPCs too.

## Testing
I spawned in as a Drask Mime, applied brute and burn damage to myself, drank Nothing, watched the drink heal me. I used the same Drask Mime, dealt brute and burn damage to myself, drank Silencer, watched the drink heal me.
I spawned in as an IPC Mime, applied brute and burn damage to myself, drank Nothing, watched the drink heal me. I used the same IPC Mime, dealt brute and burn damage to myself, drank Silencer, watched the drink heal me.

I spawned in as a Drask Clown, applied brute and burn damage to myself, drank Banana Juice, watched the drink heal me. I used the same Drask Clown, dealt brute and burn damage to myself, drank Banana Honk, watched the drink heal me.
I spawned in as an IPC Clown, applied brute and burn damage to myself, drank Nothing, watched the drink heal me. I used the same IPC Clown, dealt brute and burn damage to myself, drank Banana Honk, watched the drink heal me.

<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
<hr>

## Changelog
:cl:
tweak: Tweaked Nothing so that it applies itself to IPCs Mimes too.
tweak: Tweaked Silencer so that it applies itself to IPCs Mimes too.
tweak: Tweaked Banana Juice so that it applies itself to IPCs Clowns too.
tweak: Tweaked Banana Honk so that it applies itself to IPCs Clowns too.
/:cl:

2024-08-18 17:38 UTC, WenlockTheBritishHobo commented
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

Account now linked.

2024-08-18 18:13 UTC, Fordoxia requested changes
This should fix CI failing.

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +		update_flags |= M.adjustBruteLoss(-1, FALSE, robotic = is_robot)
```suggestion
		update_flags |= M.adjustBruteLoss(-1, FALSE, robotic = TRUE)
```
`is_robot` is a check on omnizine to check if it's the liquid metal variant or not. These should all just be set to `TRUE`.

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +		update_flags |= M.adjustFireLoss(-1, FALSE, robotic = is_robot)
```suggestion
		update_flags |= M.adjustFireLoss(-1, FALSE, robotic = TRUE)
```

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +		update_flags |= M.adjustBruteLoss(-1, FALSE, robotic = is_robot)
```suggestion
		update_flags |= M.adjustBruteLoss(-1, FALSE, robotic = TRUE)
```

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +		update_flags |= M.adjustFireLoss(-1, FALSE, robotic = is_robot)
```suggestion
		update_flags |= M.adjustFireLoss(-1, FALSE, robotic = TRUE)
```

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +	var/is_robot = ((process_flags & SYNTHETIC) > 0)
```suggestion
```
Not needed here. This is used in omnizine because there is a synthetic subtype (it cuts down on duplicated code).

2024-08-18 18:13 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
> +	var/is_robot = ((process_flags & SYNTHETIC) > 0)
```suggestion
```

2024-08-18 18:26 UTC, Fordoxia commented on code/modules/reagents/chemistry/reagents/drinks_reagents.dm
>  /datum/reagent/consumable/drink/banana/on_mob_life(mob/living/M)
```suggestion
/datum/reagent/consumable/drink/banana/on_mob_life(mob/living/carbon/human/M)
```
All the drinks need to be re-scoped to this.

2024-08-18 18:44 UTC, Fordoxia approved these changes
All LGTM.

2024-08-18 19:14 UTC, WenlockTheBritishHobo commented
Second round of testing after changes were made has been completed. Method same as before.

2024-08-19 08:33 UTC, S34NW commented
Arguably an oversight as opposed to a direct species balance PR, so exemption to pre-approval stands.

2024-08-19 09:00 UTC, S34NW commented
User has linked their account

2024-08-25 18:33 UTC, DGamerL approved these changes

2024-08-27 20:37 UTC, lewcc approved these changes

2024-08-27 20:41 UTC, merged