Makes Indestructible Titanium Walls Into an Indestructible Wall Subtype
ParadiseSS13/Paradise pull request #26565
Opened 2024-08-21 17:56 UTC by Fordoxia

## What Does This PR Do
Makes indestructible titanium walls into a subtype of indestructible walls rather than being their own thing, with all the additional strengthening to their indestructibility this brings.

The Wizard and USSP ruins have been remapped with the new walls.

## Why It's Good For The Game
This prevents two entire ruins from being completely bypassed by using the RCD to deconstruct a single wall. This is clearly not intentional given the effort that was put into making the walls resist other methods of destruction.

## Testing
Visited the wizard shuttle and USSP ruin.
Verified that I couldn't deconstruct them with the RCD.
Made sure that there were no weird smoothing issues with the walls at either location.

<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](../CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog
:cl:
fix: You cannot deconstruct indestructible titanium walls with an RCD anymore.
/:cl:

2024-08-26 01:54 UTC, BiancaWilkson commented
Code-wise looks good

2024-08-28 19:09 UTC, PopeDaveThe3th approved these changes

2024-09-08 16:15 UTC, warriorstar-orion requested changes
One minor nit, good cleanup otherwise

2024-09-08 16:15 UTC, warriorstar-orion commented on code/game/turfs/simulated/walls_indestructible.dm
> +	fixed_underlay = list("icon"='icons/turf/floors.dmi', "icon_state"="darkredfull")
```suggestion
	fixed_underlay = list("icon" = 'icons/turf/floors.dmi', "icon_state" = "darkredfull")
```

2024-09-08 17:49 UTC, Fordoxia commented on code/game/turfs/simulated/walls_indestructible.dm
> +	fixed_underlay = list("icon"='icons/turf/floors.dmi', "icon_state"="darkredfull")
Change made.

2024-09-11 17:29 UTC, lewcc approved these changes

2024-09-20 19:55 UTC, warriorstar-orion approved these changes

2024-09-20 19:57 UTC, Burzah approved these changes

2024-09-20 20:01 UTC, merged