Make Gravitational Anomaly above the items.
ParadiseSS13/Paradise pull request #26683
Opened 2024-09-04 18:37 UTC by leboucliervert

## What Does This PR Do
Makes it so the Gravitational Anomalies now appear above any item such as glass shards, potted plants, etc. Mobs such as players' corpses are still above the anomaly for easy rescuing.

## Why It's Good For The Game
QOL. I deeply dislike trying to scan a gravitational anomaly only to scan the glass shards and potted plants until the anomaly detonates.

## Images of changes

Items under the anomaly :
<img width="98" alt="Items under" src="https://github.com/user-attachments/assets/2ec23722-61a3-4b8b-8f35-50dd0fc2ccac">

Skrell above the anomaly :
<img width="70" alt="Skrell above" src="https://github.com/user-attachments/assets/36dda496-1b88-4b5d-a77b-5f6cac8a1f9a">

## Testing

Spawned a skrell. Spawned a Gravitational Anomaly in the same room. Checked that the skrell was above the anomaly and that the items were under the anomaly.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
<img width="505" alt="Gravitational Anomaly Approval (Komrad)" src="https://github.com/user-attachments/assets/e7986f50-67b4-4093-a28f-ce0ca31e79b9">

  <hr>

## Changelog

:cl: leboucliervert
tweak: Gravity anomalies now exist above items for easier scanning. Mobs will still cover the gravitational anomalies.
/:cl:

2024-09-04 18:38 UTC, Contrabang requested changes

2024-09-04 18:38 UTC, Contrabang commented on code/game/objects/effects/anomalies.dm
> +	layer = OBJ_LAYER //QOL. Only mobs such as dead players will be above the anomaly.
```suggestion
	layer = OBJ_LAYER // Mobs will appear above this
```

2024-09-06 11:38 UTC, Contrabang approved these changes

2024-09-13 10:50 UTC, Miraviel approved these changes

2024-09-16 02:58 UTC, Burzah approved these changes

2024-09-16 14:46 UTC, merged