Adds the new R&D boards to secure tech storage on all maps
ParadiseSS13/Paradise pull request #26722
Opened 2024-09-08 21:23 UTC by AffectedArc07

## What Does This PR Do
Adds a board for the R&D Network Controller and R&D Backup Console to secure tech storage on all maps

## Why It's Good For The Game
Having R&D bricked isn't fun.

## Images of changes
See MDB.

## Testing
None.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  <hr>

## Changelog
:cl: AffectedArc07
add: Added RND backup console and RND network controller boards to secure tech storage.
/:cl:

2024-09-08 23:16 UTC, 1080pCat requested changes
you forgot farragus :(

2024-09-09 00:19 UTC, AffectedArc07 commented
> you forgot farragus :(

I forgot to click stage.

However it's also 1AM here so it's gonna have to wait.

2024-09-09 16:52 UTC, AffectedArc07 commented
> you forgot farragus :(

![image](https://github.com/user-attachments/assets/b4ba4165-84ca-447d-8aaf-56fee23d6118)

2024-09-09 21:40 UTC, 1080pCat approved these changes

2024-09-11 17:39 UTC, lewcc approved these changes
Looks good. 
Might wanna make sure this ends up on emerald as well.

2024-09-12 16:57 UTC, Burzah approved these changes

2024-09-12 17:00 UTC, merged