Update alien_nests.dm
ParadiseSS13/Paradise pull request #26735
Opened 2024-09-10 01:21 UTC by Erikos66

## What Does This PR Do

## Why It's Good For The Game

## Images of changes

## Testing

<hr>

### Declaration

- [ ] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Added new things
del: Removed old things
tweak: Tweaked a few things
fix: Fixed a few things
wip: Added a few works in progress
soundadd: Added a new sound thingy
sounddel: Removed an old sound thingy
imageadd: Added some icons and images
imagedel: Deleted some icons and images
spellcheck: Fixed a few typos
experiment: Added an experimental thingy
/:cl:

2024-09-10 01:43 UTC, Contrabang requested changes
I think this will make it even clearer

2024-09-10 01:43 UTC, Contrabang commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +			to_chat(buckled_mob, "<span class='ghostalert'>You may now ghost by clicking on the ghost prompt on your screen. You will be alerted when you're removed from the nest.</span>")
```suggestion
			to_chat(buckled_mob, "<span class='ghostalert'>You may now click on the ghost prompt on your screen to leave your body. You will be alerted when you're removed from the nest.</span>")
```

2024-09-10 01:45 UTC, Erikos66 commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +			to_chat(buckled_mob, "<span class='ghostalert'>You may now ghost by clicking on the ghost prompt on your screen. You will be alerted when you're removed from the nest.</span>")
Very agreed.

2024-09-12 17:32 UTC, lewcc commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +			if(tgui_alert (buckled_mob, "You may now ghost and keep respawnability, you will be notified if you leave the nest, would you like to do so?", "Ghosting", list("Yes", "No")) != "Yes")
```suggestion
			if(tgui_alert(buckled_mob, "You may now ghost and keep respawnability, you will be notified if you leave the nest, would you like to do so?", "Ghosting", list("Yes", "No")) != "Yes")
```

2024-09-13 17:42 UTC, lewcc approved these changes

2024-09-15 16:28 UTC, Burzah approved these changes

2024-09-15 23:22 UTC, Erikos66 reviewed
No idea how to resolve these request changes xD

2024-09-20 20:29 UTC, Contrabang approved these changes

2024-09-22 23:03 UTC, merged