[TWEAK/BALANCE] Destroyed monkey cube box now destroys monkey cubes inside
ParadiseSS13/Paradise pull request #26816
Opened 2024-09-18 11:47 UTC by Adrer

## What Does This PR Do
When a monkey cube box (Or any of their variants) is destroyed by acid/fire, the cubes inside are also destroyed.

## Why It's Good For The Game
Prevents cheesing by biohazards

## Testing
Burn a monkey cube box by blowing up a weldertank next to it, monkey cubes are destroyed
Spray acid on monkey cube box as a xeno queen, monkey cubes are destroyed

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

![image](https://github.com/user-attachments/assets/a55a135a-26b5-46f5-a2ab-02d16df55f7a)

  
  
  <hr>

## Changelog

:cl:
tweak: Destroyed monkey cube box now destroys monkey cubes inside.
/:cl:

2024-09-18 11:50 UTC, Contrabang requested changes

2024-09-18 11:50 UTC, Contrabang commented on code/game/objects/items/weapons/storage/boxes.dm
> +			mkc.obj_destruction(FIRE)
```suggestion
	if(damage_flag == ACID || damage_flag == FIRE)
		for(var/obj/item/food/monkeycube/mkc in contents)
			mkc.obj_destruction(damage_flag)
```

2024-09-19 06:00 UTC, Burzah approved these changes

2024-09-19 12:53 UTC, Contrabang approved these changes

2024-09-23 22:50 UTC, merged