Makes RemoveComponent more sane
ParadiseSS13/Paradise pull request #26877
Opened 2024-09-22 14:44 UTC by DGamerL

## What Does This PR Do
Our current way to properly remove a component from something is to `qdel` it. This does work fully as intended, but it doesn't make a lot of sense.
To make it a bit more logical I renamed `RemoveComponent` to `UnlinkComponent`. It "unlinks" the component from the parent so it can be reassigned. This seemed more logical to me.

`RemoveComponent` has been changed into a wrapper for `qdel(src)`. Same functionality, but now it looks more logical.

## Why It's Good For The Game
It makes more sense now

## Testing
To test some various ones:
- Xeno eggs 
- Admin/normal outfits

None of these runtimed when tested

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

NPFC

2024-10-03 21:06 UTC, lewcc approved these changes

2024-10-04 14:53 UTC, DGamerL commented on code/datums/components/surgery_initiator.dm
>  		RemoveComponent()
Is this needed? IIRC deleting the component also calls the unlinking procs. It'd also mean that all other places that use `RemoveComponent` should unlink first unless GC issues, but they don't

2024-10-04 15:00 UTC, Contrabang commented on code/datums/components/surgery_initiator.dm
>  		RemoveComponent()
I think its best for parity, just in case

2024-10-04 21:24 UTC, Contrabang commented on code/datums/components/_component.dm
> +	if(istype(removing))
```suggestion
	if(istype(removing, component_to_nuke)
```

2024-10-05 22:10 UTC, DGamerL commented on code/datums/components/_component.dm
> +	if(istype(removing, component_to_nuke)
```suggestion
	if(istype(removing, component_to_nuke))
```

2024-10-08 15:40 UTC, Contrabang requested changes
Last things

2024-10-08 15:40 UTC, Contrabang commented on code/datums/components/_component.dm
> +	if(istype(removing, component_to_nuke))
```suggestion
	if(istype(removing, component_to_nuke) && !QDELETED(removing))
```

2024-10-08 15:40 UTC, Contrabang commented on code/datums/components/_component.dm
> +	qdel(src)
```suggestion
	if(!QDELETED(src))
		qdel(src)
```

2024-10-08 16:14 UTC, Contrabang approved these changes

2024-10-09 18:45 UTC, lewcc approved these changes

2024-10-09 18:49 UTC, merged