Adds a Collection of Spent Ballistic Casings With Random Rotation and Offsets
ParadiseSS13/Paradise pull request #26958
Opened 2024-10-01 23:58 UTC by Fordoxia

## What Does This PR Do
Adds a selection of casings for use in mapping:
* Buckshot, slugs, rubbershot, beanbag, dragonsbreath, stun.
* small, large, and .50 cal bullet casings.
* Spent IK casings.

The USSP station ruin has been remapped with these new spent casings, replacing the varedits it was previously using.

## Why It's Good For The Game
Allows mappers to place down randomly scattered casings without needing to varedit. The random offset and rotation makes them actually look like they've been shot. Good for environmental storytelling.

## Images of changes
![image](https://github.com/user-attachments/assets/e87266f4-b056-49c9-b1e6-7aeec9f04f97)

## Testing
Spawned into USSP ruin, saw the cartridges were now randomly scattered.
Mapped in a pile of all the casing types, they all got scattered on their tiles randomly.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: mapped-in spent casings are now randomly scattered.
/:cl:

2024-10-03 13:13 UTC, lewcc commented on code/game/objects/items/trash.dm
> +	desc = "A spent shotgun shell. It smells like cordite, burnt plastic, and a hint of petrolium."
```suggestion
	desc = "A spent shotgun shell. It smells like cordite, burnt plastic, and a hint of petroleum."
```

2024-10-03 21:27 UTC, Fordoxia commented on code/game/objects/items/trash.dm
> +	desc = "A spent shotgun shell. It smells like cordite, burnt plastic, and a hint of petrolium."
Done.

2024-10-03 21:49 UTC, warriorstar-orion requested changes
Could you add all the new casing subtypes to the ammo casings list in the trash spawner table?

2024-10-03 23:43 UTC, Fordoxia commented
> Could you add all the new casing subtypes to the ammo casings list in the trash spawner table?

Done.

2024-10-04 06:31 UTC, warriorstar-orion approved these changes

2024-10-22 09:24 UTC, S34NW approved these changes

2024-10-22 09:35 UTC, merged