fixing depot
ParadiseSS13/Paradise pull request #26979
Opened 2024-10-03 21:24 UTC by kyunkyunkyun

## What Does This PR Do

Fixes #26975
Adds new var, `spawn_inside` for random spawners' code (I just stole it from old one).

## Why It's Good For The Game

Fix. Hope i'm not breaking something with this.

## Images of changes

![image](https://github.com/user-attachments/assets/0f5e0fa2-f3b4-4994-a809-00299bff13d6)

## Testing

On a local. Checked out depot, no issues.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
fix: Depot now properly spawns lockers.
/:cl:

2024-10-03 21:47 UTC, warriorstar-orion requested changes
Thanks for snagging this, just one tiny change

2024-10-03 21:47 UTC, warriorstar-orion commented on code/game/objects/effects/spawners/random/random_spawner.dm
> +	var/obj/spawn_inside = null
This is just a typepath so we don't cast it, and vars are initialized to `null` by default so it's not necessary to specify it

```suggestion
	var/spawn_inside
```

2024-10-03 21:52 UTC, warriorstar-orion requested changes
Also, could you make the PR title a bit more descriptive? Something like:

> fix: Only spawn Syndie Depot lockers when there's loot.

2024-10-04 07:43 UTC, warriorstar-orion approved these changes

2024-10-06 09:27 UTC, DGamerL approved these changes

2024-10-06 09:31 UTC, merged