Makes powerfist and wallbashing not ignore armor
ParadiseSS13/Paradise pull request #26981
Opened 2024-10-03 23:53 UTC by DGamerL

## What Does This PR Do
- Makes the powerfist respect armor
- Makes wallbashing respect armor

## Why It's Good For The Game
The powerfist fully ignores armor. This makes it just as effective to fight it with riot armor and as if you were naked. This now works intuitively with the rest of the armor system.

The wallbashing change is included here because they go hand in hand with the powerfist changes.

## Testing
![image](https://github.com/user-attachments/assets/c86ccf47-f862-4b07-a231-010adfd429e7)

<hr>

### Declaration
![image](https://github.com/user-attachments/assets/211b6ac8-b8b0-4452-9d80-412d8e093e76)

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: the Powerfist now respects armor
tweak: wallbashing now respects armor
/:cl:

2024-10-04 02:10 UTC, Inferno1882 commented
Why did it ignore armor in the beginning? That seems like a massive oversight.

2024-10-09 10:27 UTC, Dafrek commented
Good change, would also be nice if it didn't ignore shields (unless this PR already does that).

2024-10-10 17:07 UTC, lewcc commented on code/game/objects/items/weapons/powerfist.dm
> +	var/armor_block = target.run_armor_check(affecting, MELEE)
What happens if `affecting` is null, e.g. they're missing a leg?

2024-10-16 02:17 UTC, Spaghetti-bit approved these changes

2024-10-23 16:54 UTC, lewcc requested changes

2024-10-23 16:54 UTC, lewcc commented on code/game/objects/objs.dm
> +		var/obj/item/organ/external/affecting = C.get_organ(ran_zone(throwingdatum.target_zone))
Need the same null check both here

2024-10-23 16:54 UTC, lewcc commented on code/modules/mob/living/living.dm
> +		var/obj/item/organ/external/affecting = C.get_organ(ran_zone(throwingdatum.target_zone))
and here

2024-10-23 20:39 UTC, lewcc approved these changes

2024-10-29 17:28 UTC, merged