Fix for #25458
ParadiseSS13/Paradise pull request #26994
Opened 2024-10-06 09:33 UTC by PGrayCS

## What Does This PR Do
Changes Made:
Modified the rename function in photo object:
Added scribble = n_name to ensure the scribble is set when renaming a photo.
Added max_length = 128 to the input to prevent excessively long labels.
Updated the show function:
Separated the scribble HTML generation for better readability and consistency.
Ensured the scribble is always displayed, regardless of photo size.

## Why It's Good For The Game
Provides a fix for #25458
Consistency Across Photo Sizes: This fix ensures that writing on the back of photos works consistently for all photo resolutions, including the 7x7 size. Players can now expect the same behavior regardless of the camera settings they use.
Improved User Experience: Players will no longer face the frustration of being unable to add or view text on larger photos. This enhances the overall photography feature in the game.
3. Bug Resolution: Addresses a specific bug that was affecting player enjoyment, particularly for those exploring photography as a new in-game hobby.
Encourages Feature Usage: With the fix in place, players are more likely to use and enjoy the photo labeling feature across all photo sizes, potentially increasing engagement with the photography aspect of the game.
Code Clarity: The changes improve code readability and maintainability, making it easier for future developers to understand and modify the photo functionality if needed.
6. Prevents Potential Exploits: By adding a maximum length to the input, it prevents potential issues or exploits related to extremely long photo labels.
7. Maintains Immersion: Ensuring that all game features work as expected helps maintain player immersion and the overall quality of the game experience.
These changes contribute to a more polished and consistent gameplay experience, addressing a specific user-reported issue while potentially improving the system for all players engaging with the photography feature.

## Images of changes

## Testing

<hr>

### Declaration

- [ ] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:

fix: Fixed a few things

/:cl:

2024-10-06 23:40 UTC, silverplatedelta requested changes

2024-10-06 23:40 UTC, silverplatedelta commented on code/modules/paperwork/photography.dm
> +    var/n_name = tgui_input_text(user, "What would you like to label the photo?", "Photo Labelling", max_length = 128)
Please change your indentations to tab from line 118 through line 125

2024-10-09 18:57 UTC, lewcc reviewed
Hey, thanks for the PR!

It looks like something might have gone wrong with a merge, you've got a lot of unrelated changes included. I'd also advise not PRing off of your master branch, and to instead make a new branch in the future.

Beyond that, please rework the body of your PR description. You should have something in the testing section, the changelog should describe the impact your change has on the game, and it's currently all in all a bit hard to read.

2024-10-19 13:42 UTC, Henri215 commented
@PGrayCS We are here to help you with anything, just gotta contact us, i can even make step by step videos for you.

2024-10-26 19:25 UTC, closed without merging