Fixes eternal candle boxes appearing empty on spawn
ParadiseSS13/Paradise pull request #27008
Opened 2024-10-07 03:05 UTC by 1080pCat

## What Does This PR Do
Fixes the eternal candle box appearing empty on spawn, also changes how the normal candle box handles it slightly.

## Why It's Good For The Game
The boxes looked empty, the whole point of fancy storage is you can /see/ how full/empty it is

## Images of changes
![dreamseeker_W9ywE6r8a7](https://github.com/user-attachments/assets/69fa58d4-6525-4bab-92b5-90b49df99a13)
![dreamseeker_FQwpDC4SAs](https://github.com/user-attachments/assets/59d37afa-d94d-47ad-be5a-e39de51f37db)
(trust me)

## Testing
Spawned every candle box type, all appeared correctly. swapped candles around the boxes, no issues seen

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

fix: Fixed eternal candle boxes appearing empty when they spawn
/:cl:

2024-10-07 03:05 UTC, 1080pCat commented on code/game/objects/items/weapons/storage/fancy.dm
> +
```suggestion
```

2024-10-07 03:06 UTC, Contrabang requested changes

2024-10-07 03:06 UTC, Contrabang commented on code/game/objects/items/weapons/storage/fancy.dm
> +	update_icon_state()
```suggestion
	update_icon(UPDATE_ICON_STATE)
```

2024-10-09 19:03 UTC, lewcc approved these changes

2024-10-09 19:07 UTC, merged