Adds CI for missing icon_states
ParadiseSS13/Paradise pull request #27063
Opened 2024-10-11 10:21 UTC by Contrabang

## What Does This PR Do

Ports CI for missing icon_states (from #71908)

## Why It's Good For The Game

Another step towards improving the codebase

## Testing

WIP

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

NPFC (hopefully)

2024-10-11 10:32 UTC, DGamerL requested changes

2024-10-11 10:32 UTC, DGamerL commented on code/game/objects/items/weapons/storage/belt.dm
> +	icon_state = "[initial(base_icon_state)]_[length(contents)]"
Does the base iconstate ever change? Do we need to use `initial` here?

2024-10-11 10:32 UTC, DGamerL commented on code/modules/customitems/item_defines.dm
> +	icon_state = "chaps" // ctodo
TODO

2024-11-14 14:04 UTC, DGamerL approved these changes
Just needs a TM

2024-11-14 17:53 UTC, AffectedArc07 approved these changes

2024-11-14 18:01 UTC, merged