Supermatter events are now announced by "supermatter crystal" instead of "the supermatter crystal"
ParadiseSS13/Paradise pull request #27176
Opened 2024-10-23 03:57 UTC by Truls20

## What Does This PR Do

Fixes #27172

## Why It's Good For The Game

Consistency is good, and you do not have to mute two different supermatter crystals to mute it in comms.

## Images of changes

## Testing
I caused a supermatter event, checked it was announced by "supermatter crystal", I then caused a supermatter integrity alert to double-check they were the same name. I then muted "supermatter crystal" via telecomms and confirmed both integrity alerts and supermatter event alerts were muted.
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
fix: Fixed supermatter radio name inconsistency
/:cl:

2024-10-23 04:13 UTC, Truls20 commented
It seems the simple solution sadly leaves the supermatter **shards** inconsistent in radio. Not desirable, I shall find a better way to fix both

2024-10-23 04:16 UTC, Contrabang requested changes
This is how the normal supermatter autosay is done in supermatter.dm

2024-10-23 04:16 UTC, Contrabang commented on code/modules/power/engines/supermatter/supermatter_event.dm
> +	supermatter.radio.autosay(text, "supermatter crystal", "Engineering")
```suggestion
	supermatter.radio.autosay(text, supermatter.name, "Engineering")
```

2024-10-23 04:16 UTC, Contrabang commented on code/modules/power/engines/supermatter/supermatter_event.dm
> +	supermatter.radio.autosay(text, "supermatter crystal", null)
```suggestion
	supermatter.radio.autosay(text, supermatter.name, null)
```

2024-10-23 12:20 UTC, Contrabang approved these changes

2024-10-23 12:45 UTC, Henri215 approved these changes

2024-10-27 01:40 UTC, DGamerL approved these changes

2024-10-27 01:44 UTC, merged