Black boxes his grace ascentions.
ParadiseSS13/Paradise pull request #27221
Opened 2024-10-27 18:45 UTC by 1080pCat

## What Does This PR Do
Logs when/if his grace ascends to the black box

## Why It's Good For The Game

Data is good, i'm going to attempt to balance this in the future, and knowing if they've ascended is a must for this
## Images of changes

## Testing
removed the mind check for his grace, ate 25 bodies two separate times, checked the blackbox controller, seemed to have worked. however i lack a DB to make 100% sure.

![image](https://github.com/user-attachments/assets/a1daee99-d5f5-4f5f-8f52-a22f39ec59f4)

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
NPFC
/:cl:

2024-10-27 19:32 UTC, DGamerL approved these changes

2024-10-27 20:27 UTC, Contrabang requested changes
Also want to possibly implement blackbox ledger tracking for amount of victims, discussed on discord

2024-10-27 20:27 UTC, Contrabang commented on code/game/objects/items/his_grace.dm
> +	SSblackbox.record_feedback("tally", "his_grace", 1, "Ascended")
```suggestion
	SSblackbox.record_feedback("tally", "his_grace", 1, "ascended")
```

2024-10-29 11:31 UTC, Contrabang approved these changes

2024-10-29 13:39 UTC, DGamerL approved these changes

2024-10-29 13:43 UTC, merged