Language Changes & Lore Pt. 1
ParadiseSS13/Paradise pull request #27257
Opened 2024-11-01 15:54 UTC by PopeDaveThe3th

## What Does This PR Do
- Renames Neo-Russkiya to Zvezhan
- Reworks the syllable structure of Zvezhan and Sol Common.
- Updates the descriptions of Sol Common, Zvezhan, and Galactic Common

## Why It's Good For The Game
- Neo-Russkiya is one of the last holdouts of the long-dead Space Russia meme. The USSP is becoming a lot more nuanced soon, so its language will also be so.
- Sol Common didn't have a very interesting gimmick to it, while this rework makes it more interesting as a language and story device.
- GalCom needed a better description.

## Testing

- Entered game
- Observed language descriptions
- Set telecomms to changed languages
- Languages work as advertised.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
 
  <hr>

## Changelog

:cl:
tweak: Altered names and descriptions of Zvezhan, GalCom, and SolCom
/:cl:

2024-11-01 17:02 UTC, DGamerL requested changes
Please rebuild TGUI and merge master

2024-11-01 17:12 UTC, AyIong commented
> Please rebuild TGUI and merge master

Merge master and rebuild TGUI* 🤓

2024-11-01 17:39 UTC, Somniworld commented
This PR has the Lore Team Seal of Quality (TM) 

![Capture d'écran 2024-11-01 183122](https://github.com/user-attachments/assets/0bc1a3c9-1e40-475b-8a3d-6e2950b2d08d)

![Lore Team Seal](https://github.com/user-attachments/assets/5fd3c19b-7f0e-4563-b232-daaa72cdf9a1)

2024-11-01 21:11 UTC, dj-34 commented
As a native Russian speaker, I can say that it has absolutely nothing related to my language, perhaps even to the rest of the Slavic languages.
The syllables seem to me to be purely Chinese, and with the "naming" of the language I can't find any connection at all, neither with Chinese nor with Slavic languages, unfortunately.

2024-11-01 22:56 UTC, PopeDaveThe3th commented
> As a native Russian speaker, I can say that it has absolutely nothing related to my language, perhaps even to the rest of the Slavic languages. The syllables seem to me to be purely Chinese, and with the "naming" of the language I can't find any connection at all, neither with Chinese (i tried my best to find something related in Chinese language) nor with Slavic languages, unfortunately.

The name doesn't really have any basis in any existing words.

In regards to the language itself, it was a lot harder to find syllables for Russian than it was for Chinese and Vietnamese that I used for the rest of the syllables, so if you'd like to provide some extra Russian ones I'd be glad to slot them in.

2024-11-02 00:13 UTC, PopeDaveThe3th commented
In response to earlier critique, new syllables from Russian, Romanian, Polish, Thai, and Ukrainian have been added to Zvezhan to further flesh it out.

2024-11-15 18:08 UTC, lewcc commented on code/modules/mob/language.dm
> +	desc = "The language of revolution across the stars, intially formed as a hybrid of Russian and Mandarin Chinese by early Cygni settlers before incorporating additional influences from across Eurasi
```suggestion
	desc = "The language of revolution across the stars, initially formed as a hybrid of Russian and Mandarin Chinese by early Cygni settlers before incorporating additional influences from across Eurasia."
```

2024-11-25 11:29 UTC, merged