Death alarms have a SLIGHT cooldown on when they send another message
ParadiseSS13/Paradise pull request #27287
Opened 2024-11-04 12:01 UTC by 1080pCat

## What Does This PR Do
Adds small cooldown(0.1 seconds) to the death alarm emp message to prevent spamming when ion scatter shot is used.

## Why It's Good For The Game
Having common flooded with 7 death alarm messages is really not ideal.
![image](https://github.com/user-attachments/assets/749cdf78-5e18-4f21-9942-070454eb41cb)

## Testing

Compiled, shot a target with a death alarm with a regular ion rifle, no dropped messages noticed.
shot a target with ion scatter, only one message was sent per shot
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
is very tweaky fix, lemme know if i should've gotten approval first.
  <hr>

## Changelog

:cl:
fix: ion scatter no longer floods common radio with death alarm messages if the target has one
experiment: Added an experimental thingy
/:cl:

2024-11-04 12:57 UTC, Contrabang requested changes

2024-11-04 12:57 UTC, Contrabang commented on code/game/objects/items/weapons/bio_chips/bio_chip_death_alarm.dm
> +			addtimer(VARSET_CALLBACK(src, emp_spam_lock, FALSE), 0.1 SECONDS, TIMER_UNIQUE | TIMER_OVERRIDE) // shamelessly stolen from pulse demon code
use the cooldowns from tg_cooldowns.dm instead (COOLDOWN_FINISHED, COOLDOWN_START, COOLDOWN_DECLARE)

2024-11-05 13:30 UTC, Contrabang approved these changes

2024-11-07 18:42 UTC, DGamerL approved these changes

2024-11-07 18:46 UTC, merged