Syndicate Research Base Mega Fix Pack
ParadiseSS13/Paradise pull request #27369
Opened 2024-11-16 10:07 UTC by SchrodingersWolf

## What Does This PR Do

Adds an APC to the Syndicate Research Base, allowing the lights outside to work again. Also added a maintenance closet to house said APC, as well as a plushie - Say hi to Forks-the-Outlet, the unsung hero of the Syndicate, maintainer of the Base! Fixes #27233

Adds two light fixtures to the Dressing Room as it is extremely dark in there.

Adds a Syndicate variant of the Claw Game with Freeplay enabled so Syndicate Researchers can waste their time gaming instead of conducting unethical experiments. Fixes #26687

## Why It's Good For The Game

Let there be light, so the Researchers may be able to use their camera consoles to watch out for intruders and to make themselves look pretty in the Dressing Room.

Cute plushies are good.

Claw Game being usable by Syndies is good.

## Images of changes
APC for exterior lights
![Screenshot 2024-11-16 034955](https://github.com/user-attachments/assets/cc03becd-40da-4c68-a76f-5083b15f2ee6)

New lights for Dressing Room
![Screenshot 2024-11-16 045300](https://github.com/user-attachments/assets/4b477349-0a99-4dfe-b777-849bfe92f305)

No screenshot for the Claw Game fix. Sorry.
## Testing
It compiles.

Spawned in, checked that everything I changed did indeed change.

Spawned a bunch of skrells, turned off the new Syndicate Space Base Cave APC, verified that the turrets mowed down the skrells just fine.

Tried it again with a destroyed APC.

Checked Claw Game, verified Freeplay is on and that Syndicate Officers can enjoy the game.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Additional lights in the Syndicate Space Base Dressing Room
fix: Syndicate Space Base exterior lights now have an APC connected
fix: Syndicate Space Base now has a Syndicate variant of Claw Game which does not require credits or an account
/:cl:

2024-12-02 14:59 UTC, warriorstar-orion commented
@SchrodingersWolf could you merge to master and run UpdatePaths script 27386?

2024-12-23 23:10 UTC, silverplatedelta approved these changes
Code looks good! Still needs a mapping pass.

2024-12-30 09:38 UTC, Bm0n commented
It seems like the syndi claw game isn't in the newest version

2025-01-01 22:51 UTC, SchrodingersWolf commented
> It seems like the syndi claw game isn't mapped in the latest commit version

Resolved in latest commit

2025-01-06 14:29 UTC, FunnyMan3595 requested changes
Please revert the changes to the station maps. If needed (and it probably is), that should be done as a separate PR. Probably by @warriorstar-orion , since it's his script that's adjusting them.

2025-01-16 18:08 UTC, DGamerL requested changes
Getting stale, please adress requested changes or your PR will be closed

2025-01-21 03:28 UTC, warriorstar-orion approved these changes

2025-01-21 17:13 UTC, Burzah approved these changes

2025-01-21 17:17 UTC, merged