Remaps Delta's Brig and Courtroom
ParadiseSS13/Paradise pull request #27385
Opened 2024-11-18 13:46 UTC by Contrabang

## What Does This PR Do

Remaps delta brig and courtroom. The courtroom has become much smaller, the magi's office much larger, and the IAAs got put in a broom closet (literally, theres a broom in their locker). Brig specifically was designed with how NT would design a good security brig in mind, but it still has quite a few flaws.
- Detective's office has new experimental shutters, allowing them to talk to the public.
- Execution has new experimental shutters, allowing perma prisoners to watch executions. Cameras have been carefully places so that the AI cannot see inside the execution room when the shutters are open.
- Perma has had items added to make it more fun to be in there, stuff like crayons and new kitchen machines. This perma may be easier to escape from than before, but security has a better observatory to watch you from.
- Evidence is still nearby maint, but is now only behind 2 doors of protection, but it can be seen from processing. I think its about the same difficulty as old delta evidence. The maint door has a metal sheet covering over it, so it requires welding or emagging.
- The Warden keeps their Crew Monitor Console in this remap, but the HOS does not.
- Processing is right next to all the cells, which makes it convenient when the prisoners are not fighting back. But if they shove you while you're taking someone to processing, they're very likely to run away.
- Cell 5 is mashed inbetween the HOS office and warden office, and is totally run down. All it contains is a space law book. Read up.

## Why It's Good For The Game

Delta brig really had "long empty hallway" syndrome. This remap removes the majority of that while keeping some unique features and adding others.

## Images of changes

Old brig: https://webmap.affectedarc07.co.uk/maps/paradise/deltastation/

New brig: 
![StrongDMM-2024-11-18 08 32 20](https://github.com/user-attachments/assets/1b71456e-896c-4a30-a39d-8a9a846cff39)
Walkthrough:

https://github.com/user-attachments/assets/2d89c82d-977e-464f-a160-e7a1df2f880c

## Testing

Ran around a lot, tbh can use more testing!

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>
  
  
![image](https://github.com/user-attachments/assets/080e4385-0510-4d2f-bdb7-d5f7201f6cbd)

## Changelog

:cl:
tweak: NSS Kerberos' brig, courtroom, magistrate's office, and IAA office have been remapped.
/:cl:

2024-11-30 16:38 UTC, Burzah approved these changes
Did a walk through only at this point. 
Nothing was out of place, and it was looking good!
Made one optional recommendation via Discord.
Would like a mapping team member to review and sign off.
Nice work!

2024-12-01 06:02 UTC, warriorstar-orion requested changes
This is a really solid remap, some small things:

Briefing room has too many vents/scrubbers for its size:

![image](https://github.com/user-attachments/assets/b8f8a8c5-bd0a-4fae-a3bc-e6ad8ce5d4c7)

Can you reroute these atmos pipes so they're not visible under the windows on the plating?

![image](https://github.com/user-attachments/assets/e5913363-acda-4b45-a901-8d0b99fb1668)

This floor is missing one of its red decorative tiles:

![image](https://github.com/user-attachments/assets/0a4472d6-99b0-4f81-a831-90da3c5ecff0)

Having these beds right next to the workout area feels awkward and out-of-place:

![2024_12_01__00_40_35__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/8883c22d-3416-4f90-89e6-66904009e3d6)

Noisy floor/wallbump clumping here, specifically the line of bumps from lightbulb to fire alarm:

![2024_12_01__00_41_04__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/01aed732-f4fe-41a3-a539-8457d9127baf)

Protruding area designation here:

![2024_12_01__00_41_29__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/c3545446-67b1-4778-947a-a9a8dc599a7e)

Duplicate Cell 3 treadmill monitor here:

![2024_12_01__00_42_07__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/b277f9e7-71ea-4c5e-8a7b-149ce6118127)

Some of these floor bumps are aligned, some aren't, it's up to you how you want to arrange them but they should be a bit more consistent running down the hall:

![image](https://github.com/user-attachments/assets/dba2b249-cb9e-4338-acb9-5f76d44d33c8)

Designate this tile's area as maintenance; we're not enviously consistent about this but having the maintenance door in maintenance seems to be the more common style on this map:

![2024_12_01__00_43_40__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/d048c37e-87e6-4d8d-a50d-77ec13c198f1)

Can you move this vent/scrubber pair so they're not on the same tile as the decals?

![2024_12_01__00_44_00__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/44a15cb0-0e0e-43f9-805b-87b19cdb1cea)

Could you put a pod directional poster here?

![2024_12_01__00_44_35__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/32f6f0e3-2708-4685-87d8-34fd84159dc3)

Could you add fence caps to the fences surrounding the stairs to the courtroom?

![2024_12_01__00_46_15__paradise dme  deltastation dmm  - StrongDMM](https://github.com/user-attachments/assets/8aa1f582-a7f5-4ca1-b0ff-3cc5bdb0d14f)

2024-12-03 05:17 UTC, spacegeese commented
little nitpick, but can you add reinforced windoors to the det's shutters so he doesn't get jumped?

2024-12-10 00:04 UTC, Contrabang commented
> little nitpick, but can you add reinforced windoors to the det's shutters so he doesn't get jumped?

I dont think I will, they can close the shutters if someone is climbing over or deconstructing the table

2024-12-11 21:11 UTC, warriorstar-orion approved these changes
LGTM

2024-12-11 22:04 UTC, Burzah approved these changes
Did another walkthrough after review changes. Looks great!

2024-12-11 22:08 UTC, merged