Makes the traitor after you warning an objective
ParadiseSS13/Paradise pull request #27389
Opened 2024-11-18 21:07 UTC by Qwertytoforty

### This is not a new thing. You currently get warned if a traitor needs you dead **and they have the objective that tells them you are an agent.** This does **not** warn you if someone has a normal kill objective on you.

## What Does This PR Do

Makes the traitor is out to kill you and knows warning an objective, so it is harder to miss.
Ensures it is only sent once, and that you always get it, vs the current not getting it on autotraitor or sometimes just not getting it period.
Gives it a bit of a random delay before it is announced, vs right away. Might remove this, but also covers a bit of admins having to swap out traitors that cryo roundstart or have to go or don't want it.
Removes the variable that covers what the message is, since only traitors get this.
Renames the variable to be related to the new proc names.

## Why It's Good For The Game

It is very easy to miss this, as it is a warning text outside the giant block of textbox objectives, and doesnt always trigger!
By adding it to your objectives, and making your objectives pop up again, it is very hard to miss this.

## Images of changes
![image](https://github.com/user-attachments/assets/74bc0207-abca-493d-a300-ca5fb516c25c)

## Testing
See above, but also testing that paranoia works, testing that you get it mid round if someone gets an objective on you, tested to make sure you couldn't get it twice, tested to make sure the objective worked.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: The notification as an agent that another agent knows you are a traitor and is after you, is now an objective, making it very hard to miss.
/:cl:

2024-11-18 21:17 UTC, Contrabang requested changes
few more things

2024-11-18 21:17 UTC, Contrabang commented on code/game/gamemodes/objective.dm
> +	return FALSE
```suggestion
	return TRUE
```

2024-11-18 21:17 UTC, Contrabang commented on code/modules/antagonists/_common/antag_datum.dm
> +	var/sending_backstab = FALSE
move this up to traitor please

2024-11-18 21:49 UTC, Qwertytoforty commented on code/modules/antagonists/_common/antag_datum.dm
> +	var/sending_backstab = FALSE
sure one sec

2024-11-18 21:51 UTC, Qwertytoforty commented on code/modules/antagonists/_common/antag_datum.dm
> +	var/sending_backstab = FALSE
done

2024-11-18 21:51 UTC, Contrabang commented on code/game/gamemodes/objective.dm
> +	return FALSE
Yea, it should return true by default imo

2024-11-22 14:44 UTC, Contrabang approved these changes

2024-11-27 17:08 UTC, merged