Recounts `rise_number` and related variables every once in a while
ParadiseSS13/Paradise pull request #27393
Opened 2024-11-19 02:42 UTC by DGamerL

## What Does This PR Do
Every 5 minutes, the rise and ascend thresholds are recalculated, to account for people leaving the round / joining late

## Why It's Good For The Game
This helps a lot when a lot of people leave the game, or a lot of people latejoin

## Images of changes
![image](https://github.com/user-attachments/assets/58f1cf7c-c86c-4036-967c-e3c1aeddcd64)

**This image should say `-1` but I accidentally closed my instance before taking a screenshot**
![image](https://github.com/user-attachments/assets/95df33a5-5190-4abd-aed3-57c66049fe11)

## Testing
See above

<hr>

## Changelog

:cl:
fix: Cult will now be a little more consistent when a lot of people latejoin / leave the round early
/:cl:

2024-11-19 02:43 UTC, Contrabang requested changes

2024-11-19 02:43 UTC, Contrabang commented on code/modules/antagonists/cult/team_cult.dm
> +	QDEL_NULL(recount_timer)
```suggestion
	deltimer(recount_timer)
	return ..()
```

2024-11-19 02:44 UTC, DGamerL commented on code/modules/antagonists/cult/team_cult.dm
> +	QDEL_NULL(recount_timer)
Oops

2024-11-19 04:29 UTC, Contrabang requested changes
can ya remove `addtimer(CALLBACK(src, PROC_REF(cult_threshold_check)), 2 MINUTES) // Check again in 2 minutes for latejoiners` please?

2024-11-19 10:09 UTC, DGamerL commented
> can ya remove `addtimer(CALLBACK(src, PROC_REF(cult_threshold_check)), 2 MINUTES) // Check again in 2 minutes for latejoiners` please?

Done!

2024-11-23 13:51 UTC, Burzah approved these changes

2024-11-23 13:56 UTC, merged