Tweak: Magma-ale and space beer are now a bottle subtype
ParadiseSS13/Paradise pull request #27407
Opened 2024-11-20 17:20 UTC by Toastical

## What Does This PR Do
fixes #27354
Moves magma-ale and space beer to bottle from cans and updates the paths in code and maps. Upped the volume limit from 30 to 50.

## Why It's Good For The Game
Magma-ale and space beer now behave like glass bottles rather than soda cans. 

## Testing
Successfully forced a mob to drink on help intent
Smashed both bottles over mobs head in harm intent
Checked booze-o-mat bottles
Checked bar secure closet
Tested service borg emagged beer
Map tests:
- [x] Boxstation
- [x] Metastation
- [x] Deltastation
- [x] Cerestation
- [x] Emeraldstation
- [x] Lavaland outpost
- [x] Centcomm
- [x] Space  bar
- [x] Meatpackers
- [x] Moon outpost 19
- [x] Syndie Space Base
- [x] Syndie Depot
- [x] Althland Facility

- [x] Biodome Beach

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: Magma-ale and space beer are now bottles
tweak: Magma-ale and space beer bottles now hold 50u
/:cl:

2024-11-20 17:26 UTC, Toastical commented
Uhh, I forgor that override_map will prevent it from checking other maps. I will fix them once im home.

2024-11-28 23:43 UTC, silverplatedelta reviewed
Code looks good, mapping pass is going to be required. 

I will note that this will remove the functionality of opening beer cans and hearing the "hiss" sound effect.

2024-11-29 01:59 UTC, Toastical commented
> Code looks good, mapping pass is going to be required.
> 
> I will note that this will remove the functionality of opening beer cans and hearing the "hiss" sound effect.

Well, sprite-wise it wasn't a can to begin with. I could sprite beer cans and perhaps add an opening functionality to bottles? Like a cap pop for the beer bottle. A champagne pop for wine?

2024-12-05 03:34 UTC, warriorstar-orion requested changes

2024-12-05 03:34 UTC, warriorstar-orion commented on code/game/objects/structures/crates_lockers/closets/secure/bar.dm
> +	new /obj/item/reagent_containers/drinks/bottle/beer(src)
```suggestion
	for(var/i in 1 to 10)
		new /obj/item/reagent_containers/drinks/bottle/beer(src)
```

2024-12-05 14:00 UTC, Toastical commented on code/game/objects/structures/crates_lockers/closets/secure/bar.dm
> +	new /obj/item/reagent_containers/drinks/bottle/beer(src)
Oh, that's a whole lot sleeker. Damn

2024-12-05 14:14 UTC, warriorstar-orion approved these changes
Code LGTM

2024-12-07 22:16 UTC, DGamerL approved these changes

2024-12-07 22:23 UTC, merged