[FIX] You can knock climbers off of tables again
ParadiseSS13/Paradise pull request #27423
Opened 2024-11-21 10:04 UTC by Adrer

## What Does This PR Do
You can once again knock people that are trying to climb onto a table off by clicking on the table with an empty hand.

## Why It's Good For The Game
This feature was unintentionally removed during a fix

## Testing
Try and climb onto a table.
Click on the table.
I knock myself off.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
fix: You can knock people climbing onto tables off by clicking on the table with an empty hand
/:cl:

2024-11-21 12:38 UTC, Adrer commented on code/game/objects/structures.dm
> +		if(get_turf(user) == get_turf(src))
It is possible for the forcemove to fail (Eg. Windoor closes in front of you)

2024-11-22 13:09 UTC, DGamerL approved these changes

2024-11-22 13:11 UTC, Contrabang requested changes

2024-11-22 13:11 UTC, Contrabang commented on code/game/objects/structures.dm
> +	climbers += user
register a signal here to listen if the user gets deleted please, and remove them from the list if they do

2024-11-22 13:32 UTC, Contrabang requested changes

2024-11-22 13:32 UTC, Contrabang commented on code/game/objects/structures.dm
> +	UnregisterSignal(user, COMSIG_PARENT_QDELETING)
maybe unregister in remove_climber too

2024-11-23 13:56 UTC, Burzah approved these changes

2024-11-23 22:11 UTC, Contrabang approved these changes
looks climbable to me

2024-11-24 02:43 UTC, DGamerL approved these changes

2024-11-24 02:43 UTC, DGamerL commented on code/game/objects/structures.dm
> +	SIGNAL_HANDLER
```suggestion
	SIGNAL_HANDLER // COMSIG_PARENT_QDELETING
```

2024-11-24 20:03 UTC, merged