Adds hallucination managers
ParadiseSS13/Paradise pull request #27482
Opened 2024-11-29 12:46 UTC by DGamerL

## What Does This PR Do
Adds a framework to use hallucinations with, `hallucination managers`!
These will automatically spawn hallucinations and do special behaviour at certain points, alongside allowing for special spawning placement.
They are made to work alongside normal hallucination effects, so these can easily be put in the global `hallucinations` list.

## Why It's Good For The Game
Our hallucinations are very old and bad, adding this framework will make it easier to add better hallucinations. I'm not sure if moving every (visual) hallucination as they currently are over to this is worth it, and it is probably better to improve what they do first.

## How do I use this?
The first and most important step is to decide what you want your hallucination to do.
After you've done that, you should start with making your `/obj/effect/hallucination/no_delete`. This is what will show up in-game.
The reason we use the `/no_delete` subtype is because the manager will handle deleting the hallucinations.
For example, this is a simple hallucination that will look like a NAD:
```js
/obj/effect/hallucination/no_delete/nad
	hallucination_icon = `icons/obj/module.dmi'
	hallucination_icon_state = "nucleardisk"
```
**If you want an effect to trigger when doing something with the hallucination, you have to define it on the hallucination.**

Now we have our hallucination! To make sure the manager spawns it, do:
`initial_hallucination = /obj/effect/hallucination/no_delete/nad`
This will automatically spawn in the nad hallucination, and change `initial_hallucination` into a reference.
To decide where to spawn the hallucination, the manager uses `get_spawn_location()`. By default this chooses a random turf in a 5 tile radius.

After your hallucination is spawned, you can give it any effects like sparks or sounds by overriding `on_spawn()`, like so for example:
```js
/datum/hallucination_manager/nad/on_spawn
	playsound(get_turf(initial_hallucination), "sparks", 50, TRUE)
	do_sparks(4, FALSE, initial_hallucination)
```

If you want extra effects to trigger some time after spawning, `first_callback` has your back! By default it will delete the hallucination after 10 seconds, but you can override the proc (and the time variable) to do other things.
If you want your hallucination to start an extra timer, you can define a second callback proc on your manager like this for example:
```js
/datum/hallucination_manager/nad/proc/second_callback
```
**Disclaimer: if you override `first_callback`, you must add a proc that will delete the manager**

And that is pretty much all that there is to it! If you have any questions or clarifications, please ask them and I'll update this description! Once others think it's good enough aswell, I'll add it to the devdocs!

## Images of changes
![image](https://github.com/user-attachments/assets/d7823832-df6a-4a14-9d7d-3905c5be809f)

## Changelog

NPFC

2024-11-29 22:16 UTC, Contrabang requested changes

2024-11-29 22:16 UTC, Contrabang commented on code/modules/hallucinations/hallucination_manager.dm
> +	if(!called_by_destroy)
```suggestion
	if(!QDELETED(src))
```

2024-12-02 05:58 UTC, Burzah approved these changes

2024-12-02 21:29 UTC, Contrabang approved these changes

2024-12-02 21:45 UTC, merged