Attack Chain Migration: Screwdriver
ParadiseSS13/Paradise pull request #27563
Opened 2024-12-06 13:01 UTC by Toastical

## What Does This PR Do
Migrates the screwdriver to the new attack chain

## Why It's Good For The Game
New attack chain

## Testing
- [x] Attack mob
- [x] Eye-stab mob on non-help intents and correct targeting
- [x] Did not eye-stab non carbons
- [x] Did surgery (human and machine)
- [x] Applied screwdriver to AI
- [x] Applied screwdriver to open borg
- [x] Screwed/unscrewed machinery
- [x] Screwed/unscrewed structures
- [x] Screwed/unscrewed turf
- [x] Interacted with items (radio, stunbaton, hailer, medbeam, disabler seclite)
- [x] Constructed mech
- [x] Fed to an autolathe on harm intent

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

NPFC

2024-12-18 18:27 UTC, BiancaWilkson approved these changes
Was slightly worried about powerfists/pneumatic cannons, but I tested them and they worked fine. LGTM

2024-12-18 23:41 UTC, BiancaWilkson requested changes
Unnoticed bug popped up, quick un-approval while author sorts it out.

2025-01-06 16:31 UTC, Toastical commented
waiting on the aforementioned PR

2025-01-17 22:49 UTC, FunnyMan3595 approved these changes

2025-01-19 04:15 UTC, BiancaWilkson approved these changes

2025-01-19 17:18 UTC, Burzah approved these changes

2025-01-19 17:22 UTC, merged