[LORE] Radio Lore Update & Subspace Purge
ParadiseSS13/Paradise pull request #27566
Opened 2024-12-06 15:03 UTC by PopeDaveThe3th

## What Does This PR Do

Updates the descriptions of most radio-related objects in the game.

Removes the word subspace from most radio-related systems since it didn't mean anything. (subspace swap is unchanged because alliteration is cool.)

## Why It's Good For The Game
Radios needed a bit of lore sprucing.

Subspace was referenced basically nowhere in a player-facing manner and doesn't exist in lore.

## Testing

- spawned in
- observed items
- observed telecom core
- checked the circuit imprinter
- checked AI radio
- all good here boss

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  <hr>

## Changelog

:cl:
tweak: Updated radio lore (removing subspace while i was at it)
/:cl:

2024-12-06 23:09 UTC, Fordoxia requested changes
Probably also add a description to the phone, as it exists in the world and lacks one - and will inherit the station bounced radio description otherwise.

2024-12-06 23:09 UTC, Fordoxia commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "An intimidating tactical headset used by senior Asset Protection personnel."
```suggestion
	desc = "An intimidating tactical headset used by senior Asset Protection personnel. Protects against loud noises."
```

2024-12-06 23:09 UTC, Fordoxia commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "A tactical headset used by Nanotrasen magistrates."
```suggestion
	desc = "A tactical headset used by Nanotrasen magistrates. Protects against loud noises."
```

2024-12-06 23:09 UTC, Fordoxia commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "An advanced tactical headset used by high-ranking Nanotrasen PMCs. Equipped with an advanced transmission array and ear protection."
```suggestion
	desc = "An advanced tactical headset used by high-ranking Nanotrasen PMCs. Equipped with an advanced transmission array that doesn't require a telecom core, and protects against loud noises."
```

2024-12-23 03:49 UTC, closed without merging

2024-12-23 03:50 UTC, PopeDaveThe3th commented
Laziness hit hard with this one. Probably going to remake it in the future but can't be bothered right now.