Removes Vampire From Explorer
ParadiseSS13/Paradise pull request #27589
Opened 2024-12-08 20:42 UTC by RufusVanilee

## What Does This PR Do

Removes vampires from explorer by adding them to the protected_jobs list.

## Why It's Good For The Game

Vampires are unable to do their role as an explorer via reasonable means, leaving them to just roam the station like an assistant with teleporter access. If they were to even attempt going to where this job requires them to, they will be round removed.

## Testing

<hr>

### Declaration

- [ ] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: added explorer to protected_jobs
del: 
tweak: 
fix:
wip:
soundadd: 
sounddel:
imageadd: 
imagedel: 
spellcheck: 
experiment: 
/:cl:

2024-12-08 20:53 UTC, Burzah commented
Account has been linked.

2024-12-08 20:54 UTC, Qwertytoforty requested changes

2024-12-08 20:54 UTC, Qwertytoforty commented on code/game/gamemodes/vampire/traitor_vamp.dm
> +	protected_jobs = list("Security Officer", "Warden", "Detective", "Head of Security", "Captain", "Blueshield", "Nanotrasen Representative", "Magistrate", "Internal Affairs Agent", "Nanotrasen Navy Of
This will block traitors from being explorers, but not vampires.

2024-12-08 21:03 UTC, Qwertytoforty requested changes

2024-12-08 21:03 UTC, Qwertytoforty commented on code/game/gamemodes/vampire/vampire_chan.dm
> +	protected_jobs = list("Security Officer", "Warden", "Detective", "Head of Security", "Captain", "Blueshield", "Nanotrasen Representative", "Magistrate", "Chaplain", "Internal Affairs Agent", "Nanotr
This will block clings from being explorer on vampire changeling.

2024-12-08 21:50 UTC, Burzah commented on code/game/gamemodes/vampire/traitor_vamp.dm
> +	secondary_restricted_jobs = list("AI", "Chaplain", "Exporer")
```suggestion
	secondary_restricted_jobs = list("AI", "Chaplain", "Explorer")
```
Small typo.

2024-12-08 22:14 UTC, Scribble-Sheep commented
Wouldn't this also cause IPC explorers to be unable to roll mindflayer half the time?

2024-12-08 22:15 UTC, RufusVanilee commented on code/game/gamemodes/vampire/traitor_vamp.dm
> +	secondary_restricted_jobs = list("AI", "Chaplain", "Exporer")
typo fixed

2024-12-09 02:21 UTC, Contrabang commented
> Wouldn't this also cause IPC explorers to be unable to roll mindflayer half the time?

antag rolls before job. you wont be able to be an explorer sometimes though as IPC.

Also, this will affect clings because of how poorly gamemodes are coded

2025-01-01 04:16 UTC, Qwertytoforty commented
Alas, forgot to comment it on here, though did on discord.
Against this. Jobs should only be blocked if they cause issues for the gamemode, (HOP cult, chaplain vampire), and explorer doesnt meet that case. They can switch jobs, but also use the white ship and teleporters effectively, or the space bar.

2025-01-01 05:31 UTC, Komrad822 commented
Access is important and explorer is one of the only non-head job that grants access to the main station teleporter which can be super useful (and hilariously detrimental) to an antag that can ONLY survive on tiles that shield them from the deadly laser that is the sun. Its not needed and vamp doesnt lose out on gear depending on their job like tots do with department specific items.

2025-01-01 18:20 UTC, Stoniest commented
I honestly don't see much point in blacklisting the role from that antag type, you can either change roles at HoP if you really don't feel comfortable or as Komrad pointed out, actually utilise the extra access you have.

2025-01-08 04:41 UTC, Burzah commented
I will be closing this PR at this time, as it is now past the 30 day time period and has failed the vote. Listed below are objections registered by both the balance and design teams. If you have any questions, please reach out to the members of this team or any maintainer. 

```
Against this. Jobs should only be blocked if they cause issues for the gamemode, (HOP cult, chaplain vampire), and explorer doesnt meet that case. They can switch jobs, but also use the white ship and teleporters effectively, or the space bar.

Access is important and explorer is one of the only non-head job that grants access to the main station teleporter which can be super useful (and hilariously detrimental) to an antag that can ONLY survive on tiles that shield them from the deadly laser that is the sun.

I honestly don't see much point in blacklisting the role from that antag type, you can either change roles at HoP if you really don't feel comfortable or as Komrad pointed out, actually utilise the extra access you have.

It was basically no different with old vampires with space shaft miners. Learn to work around your job with its positives and negatives.

I'm convinced by the others. While it's a bit of a newbie trap, there's no reason to lock them out of it.

Against this as stated above by others, you can request a new job and work or work around it but no need to blacklist them from it

The points raised by others are fair, we should reach out to the author about potentially closing the PR.
```

2025-01-08 04:41 UTC, closed without merging