[PORT] Add mantis blades (new traitor item)
ParadiseSS13/Paradise pull request #27594
Opened 2024-12-09 14:13 UTC by MiraHell

## What Does This PR Do
Adds a new traitor item acquirable through any uplink for an 60 TC. For your TC you get a box.  Inside of it is 2 autodoc, 1 for each arm. Once used they will implant in your body a set of 2 retractable blades. The blades do 20 damage and have 30 armor pen. Can parry non-projectile attacks. With a cooldown of 1.5 seconds (every second attack), both blades will attack at once, dealing a total of 40 damage. A Nanostrasen version included, but it is currently unobtainable.

## Why It's Good For The Game

A new traitor item with cyberpunk vibes and new double attack mechanics, a more stealthy but weaker weapon than the dsword or chainsaw.

## Images of changes

![image](https://github.com/user-attachments/assets/1f1be130-ee03-4adb-abf9-208c6b3c0478)
On the right is the NT version and the left is syndie
![image](https://github.com/user-attachments/assets/f2c46863-013d-4984-b373-c5b40c095363)

## Testing

Spawned uplink, bought mantis blades kit, implanted myself, spawned dummy, killed it with blades

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
![image](https://github.com/user-attachments/assets/be6a7c6e-d830-42df-ba71-97873b8eabe6)

  
  
  
<hr>

## Changelog

:cl:
add: Added new traitor item: mantis blades
/:cl:

original author: EdgeLordExe
https://github.com/tgstation/tgstation/pull/55936
author of yogstation port: enkidienne
https://github.com/yogstation13/Yogstation/pull/11946

2024-12-09 14:34 UTC, Toastical commented
Is the double attack cooldown intended to be separate to each arm? Switching your attacking hand allows you to do 2 double attacks back to back consistently.

https://github.com/user-attachments/assets/9bf9af2c-64c3-45a2-b401-66e752745c6a

2024-12-09 14:53 UTC, MiraHell commented
> Is the double attack cooldown intended to be separate to each arm? Switching your attacking hand allows you to do 2 double attacks back to back consistently.

It's not intended, thanks for noticing. I'll try to redo the double attack, linter doesn't like the attack call in pre_attack

> I cannot tell if the video works.

Works

2024-12-10 02:18 UTC, DGamerL commented
I'll try to help tomorrow!

2024-12-10 09:26 UTC, MiraHell commented
Thanks Warriorstar for the help with nested types. I'm also planning to add the ability to open doors with two blades, and then the PR will be ready for review.

2024-12-10 10:04 UTC, MiraHell commented
Ready for review ✨

2025-01-01 04:21 UTC, DGamerL commented
Sorry that it's taken so long, I'll take a proper look tomorrow, happy new years!

2025-01-01 13:25 UTC, Burzah requested changes

2025-01-01 13:25 UTC, Burzah commented on code/game/machinery/doors/airlock.dm
> +			to_chat(user, "<span class='warning'>You need a second [I] to pry open doors!")
```suggestion
			to_chat(user, "<span class='warning'>You need a second [I] to pry open doors!</span>")
```

2025-01-01 13:25 UTC, Burzah commented on code/modules/surgery/organs/augments_arms.dm
> +////////////////////////////////////////
Remove MARK from here. We do not use it for individual items anymore, just to mark sections.

2025-01-01 13:25 UTC, Burzah commented on code/modules/surgery/organs/augments_arms.dm
> +	var/double_attack_cd = (3 / 2) // so every second attack
Not a big fan of using an expression here like this. It should be represented as 1.5 if anything. Unless I am missing something here?

2025-01-01 13:25 UTC, Burzah commented on code/modules/surgery/organs/augments_arms.dm
> +	AddComponent(/datum/component/parry, _stamina_constant = 2, _stamina_coefficient = 0.35, _parryable_attack_types = NON_PROJECTILE_ATTACKS, _parry_cooldown = (4 / 3) SECONDS, _no_parry_sound = TRUE)
I would mention the parry uptimes in your PR description somewhere, as the different versions have varying ones.

2025-01-02 13:15 UTC, Drsmail commented on code/modules/surgery/organs/augments_arms.dm
> +	transform = matrix(-1, 0, 0, 0, 1, 0)
What does this line do?

2025-01-02 15:32 UTC, PopeDaveThe3th requested changes
Lore & description pass.

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/datums/uplink_items/uplink_general.dm
> +	desc = "Comes with 2 G.O.R.L.E.X. Mantis blades. All packaged with autosurgeons."
```suggestion
	desc = "A pair of devastating 'Naginata' concealable mantis blades, which retract into the arms of the user. \
	Their monomolecular edges will easily tear through flesh and armor alike, and can even pry open airlocks when used together. \
	Can be used to parry incoming melee attacks."
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/datums/uplink_items/uplink_general.dm
> +	name = "G.O.R.L.E.X. Mantis Blades Kit"
```suggestion
	name = "'Naginata' Mantis Blades Kit"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	desc = "A box labeled with the letters G.O.R.L.E.X."
```suggestion
	desc = "A sleek box marked with a Cybersun logo. The label says it contains a pair of CX-12 'Naginata' mantis blades and accompanying autosurgeons."
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/research/designs/weapon_designs.dm
> +	desc = "Mantis blades reverse engineered by NT engineers. Energy actuators makes the blade a much deadlier weapon."
```suggestion
	desc = "A reverse-engineered mantis blade implant. While the monomolecular edge was lost, they remain deadly weapons."
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/research/designs/weapon_designs.dm
> +	name = "H.E.P.H.A.E.S.T.U.S. mantis blade implant"
```suggestion
	name = "'Scylla' mantis blade implant"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	name = "H.E.P.H.A.E.S.T.U.S. mantis blade"
```suggestion
	name = "'Scylla' mantis blade"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	name = "G.O.R.L.E.X. mantis blade"
```suggestion
	name = "'Naginata' mantis blade"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	name = "G.O.R.L.E.X. mantis blade implants"
```suggestion
	name = "'Naginata' mantis blade implants"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	desc = "Modernized mantis blade designed and coined by Tiger operatives. Energy actuators makes the blade a much deadlier weapon."
```suggestion
	desc = "A powerful and concealable mantis blade with a monomolecular edge, produced by Cybersun Industries. Cuts through flesh and armor alike with ease."
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	name = "H.E.P.H.A.E.S.T.U.S. mantis blade implant"
```suggestion
	name = "'Scylla' mantis blade implant"
```

2025-01-02 15:32 UTC, PopeDaveThe3th commented on code/modules/surgery/organs/augments_arms.dm
> +	desc = "Mantis blade reverse engineered by NT engineers. Energy actuators makes the blade a much deadlier weapon."
```suggestion
	desc = "A reverse-engineered mantis blade design produced by Nanotrasen. While still quite deadly, the loss of the monomolecular blade has drastically reduced its armor penetration capability."
```

2025-01-02 16:36 UTC, Drsmail approved these changes
LGTM

2025-01-02 17:23 UTC, PopeDaveThe3th approved these changes

2025-01-08 20:03 UTC, lewcc commented on code/modules/surgery/organs/augments_arms.dm
> +/obj/item/melee/mantis_blade/attack(mob/living/target, mob/living/user, params, second_attack = FALSE)
Could you move the actual attacking logic out to a proc other than `attack()`, and handle the double-attack stuff there? I'm not a huge fan of how it's being given an argument like this, as well as how you're calling it recursively outside of the attack chain.

2025-01-08 20:03 UTC, lewcc commented on code/datums/uplink_items/uplink_general.dm
> +	Their monomolecular edges will easily tear through flesh and armor alike, and can even pry open airlocks when used together. \
I think you should probably include in some in-game item description somewhere (either in the uplink, the examine, and/or in flavor text when first implanted) that note that you need to have both equipped in order to get the full benefits of them.

2025-01-10 21:18 UTC, lewcc commented on code/modules/surgery/organs/augments_arms.dm
> +/obj/item/melee/mantis_blade/attack(mob/living/target, mob/living/user, params, second_attack = FALSE)
Looks good, thanks! I just didn't want attack being recursive.

2025-01-10 21:26 UTC, lewcc reviewed
One thing, though it's not tiny.

2025-01-10 21:26 UTC, lewcc commented on code/game/machinery/doors/airlock.dm
> +			return
Hmm, this feels a bit snowflakey. I think it'd be best to make a quick door-forcing a component with some signals, if you could, and have it applied to items that can force doors.
Feel free to reach out on discord if you have any questions.

2025-01-10 23:32 UTC, Toastical commented on code/modules/surgery/organs/augments_arms.dm
> +	tool_behaviour = TOOL_CROWBAR // to pry open doors
tool_behaviour will make it behave entirely like a crowbar, including prying tiles.

2025-01-14 16:01 UTC, lewcc reviewed
Great job with the component! I have a few pieces of feedback, but in general it looks good.

2025-01-16 18:11 UTC, Burzah approved these changes

2025-01-17 18:21 UTC, merged