[PTBF] Adds grenade hallucinations
ParadiseSS13/Paradise pull request #27605
Opened 2024-12-10 07:35 UTC by BeagleGaming1

## What Does This PR Do
Adds 3 types of grenade hallucinations
A basic one with no effect, a flashbang, and a space carp spawner grenade

Also moved chasing hallucinations to their own file

## Why It's Good For The Game
More hallucination variety

## Testing
Compiled, Used the hallucinate proc in the vv dropdown to test each.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  <hr>

## Changelog

:cl:
add: Adds grenade-related hallucinations
/:cl:

2024-12-12 00:22 UTC, PollardTheDragon commented on code/modules/hallucinations/hallucinations.dm
> +		/obj/effect/hallucination/fake_grenade/spawner = 10,
I feel like if this is a major hallucination, it should be defined in `major.dm`, to keep things organized.

2024-12-12 16:44 UTC, lewcc commented on code/modules/hallucinations/effects/chaser_hallucinations.dm
> +/**
I appreciate moving this out to a new file for organization sake, but I think it'll probably just end up causing conflicts for others. I appreciate the fix, but do you think you could do it in a later PR?

2025-01-03 22:09 UTC, lewcc requested changes
Keeping with what @PollardTheDragon mentioned, could you move the grenade hallucinations out to their own file? Particularly since they're straddling two different categories.

2025-01-03 22:09 UTC, lewcc commented on code/modules/hallucinations/effects/moderate.dm
> +	. = ..()
```suggestion
	return ..()
```

2025-01-03 22:09 UTC, lewcc commented on code/modules/hallucinations/effects/moderate.dm
> +	return TRUE
```suggestion
	return distance <= 4
```

2025-01-08 21:38 UTC, FunnyMan3595 approved these changes

2025-01-09 19:29 UTC, lewcc approved these changes
Thanks for moving them out!

2025-01-10 03:19 UTC, Burzah approved these changes

2025-01-10 03:23 UTC, merged