Make the Cyborg PKA identical to a stock PKA
ParadiseSS13/Paradise pull request #27670
Opened 2024-12-18 05:36 UTC by Cress67

## What Does This PR Do
This PR modifies the max_mod_capacity of the Borg PKA to be inherited directly from the stock PKA rather than having its own lower value. This makes it 100 (for now) instead of 80, allowing for extra mods to be fit in there.

## Why It's Good For The Game
We've been doing a lot of changes to borgs to make them more fair to deal with, but haven't been changing their capacities to match. In this case, I believe borg PKAs were made to have less space because they had no damageslow, and that could allow them to do some unfair things. Now, they have damageslow. More than that, Miners have gotten a _lot_ of buffs that make them even better at mining over the years, so this will in no way allow the Mining borgs to outperform actual Miners. It will allow them to perform equally to a Miner with a single PKA, but Miners have access to other, more effective tools (such as the Advanced Plasma Cutter) while still being able to use their own PKA -- dual wielding PKAs even, if they want to.

This has no effect on the Malf PKA, which is its own item with its own max_mod_capacity. It shouldn't have much, if any, effect on emagged Mining Borgs, as they still can't fit enough mods in there to be properly lethal at good range in-pressure. If a Syndicate Agent is willing to blow TC on a pressure mod for an emagged borg, well, more power to them, but that's going to end with a locked borg and a sad (and now poor) agent.

## Testing
I booted up a private server, transformed my aghost into a Borg, and loaded the Mining module. The PKA works as expected, and has 100 potential mod space rather than 80. I then confirmed that it actually had that much space by aghosting, becoming the RD, and stuffing mods into it. This confirmed that it did actually have 100 mod space.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: Gave the Mining Borg PKA the same mod capacity as a standard PKA
/:cl:

2024-12-18 05:37 UTC, 1080pCat approved these changes
LGTM

2024-12-18 07:52 UTC, Burzah commented
Account has been linked.

2024-12-18 16:03 UTC, Komrad822 commented
Was this PR pre-approved by a balance team member?

2024-12-19 01:48 UTC, Cress67 commented
> Was this PR pre-approved by a balance team member?

No, because it didn't seem like it fell under any of the classifications that'd require pre-approval. It's not security, antagonist, or species content, it's not a large change, and it's not wide-ranging in terms of implications. If it actually is one of those things, then that's my bad and I'll need to get one of them to look over it.

2024-12-28 01:37 UTC, Komrad822 commented
> No, because it didn't seem like it fell under any of the classifications that'd require pre-approval. It's not security, antagonist, or species content, it's not a large change, and it's not wide-ranging in terms of implications. If it actually is one of those things, then that's my bad and I'll need to get one of them to look over it.

It affects malf ai. It affects paladin borgs, emagged borgs. and It affects biohazards. PKA projectile is instant damage if they hit. Theres no dodging, just praying they dont cant aim.

2024-12-28 16:10 UTC, Burzah requested changes
It was brought to my attention that this would be a balance change that affects one or more antagonists. I am putting this on hold for now, until a member of the balance team has given pre-approval. Please contact them via Discord when you have the chance.

2025-01-06 05:09 UTC, FunnyMan3595 approved these changes

2025-01-07 08:27 UTC, Cress67 commented
As of a handful of minutes ago, this now how approval from a Balance Team member, and a screenshot of the approval has been appended to the original message.

2025-01-08 09:59 UTC, Burzah commented
Pre-approval has begin given. Hold removed.

2025-01-08 21:33 UTC, lewcc approved these changes
Changes LGTM

2025-01-08 21:50 UTC, merged