[PTBF] Wavy Vision
ParadiseSS13/Paradise pull request #27674
Opened 2024-12-18 18:12 UTC by BiancaWilkson

## What Does This PR Do

Adds a hallucination that adds a random amount of wave filters to the player's screen. The strength of each individual instance of the hallucination will be random.
## Why It's Good For The Game
More hallucinations are cool, and having everything look like it's slightly moving is pretty accurate to tripping IRL.

## Images of changes

https://github.com/user-attachments/assets/0435f96d-3284-4494-862f-c9aa708967d0

## Testing

See above
<hr>

### Declaration

- [X] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: A hallucination that makes the screen look wavy.
/:cl:

2025-01-02 00:03 UTC, Drsmail approved these changes
LGTM! Realy clean code, i like it!

2025-01-02 00:03 UTC, Drsmail commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	amount_spawned = roll("4d3-3") // Results in a normal distribution from 1-9. 5 is the most likely result at ~23%
Woud not the lowest value be 1+1+1-3 = 0? Is this important?

2025-01-02 05:07 UTC, BiancaWilkson commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	amount_spawned = roll("4d3-3") // Results in a normal distribution from 1-9. 5 is the most likely result at ~23%
It's rolling 4d3, so the lowest would be 1+1+1+1-3 = 0

2025-01-02 10:10 UTC, Drsmail commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	amount_spawned = roll("4d3-3") // Results in a normal distribution from 1-9. 5 is the most likely result at ~23%
Oh, yeah, you are right, my bad

2025-01-03 21:59 UTC, lewcc reviewed
Does what it needs to do, and looks good doing it. LGTM

2025-01-03 21:59 UTC, lewcc commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	orientation = pick(WAVE_SIDEWAYS, null)
What's this pick doing?

2025-01-06 03:19 UTC, BiancaWilkson commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	orientation = pick(WAVE_SIDEWAYS, null)
The wavy lines can either be vertical, or horizontal. This picks between those for each wave.

2025-01-06 15:14 UTC, lewcc commented on code/modules/hallucinations/effects/waves_hallucination.dm
> +	orientation = pick(WAVE_SIDEWAYS, null)
Could you add a define for `WAVE_HORIZONTAL`, even if it's just `0`? Would make this a lot clearer.

2025-01-08 22:04 UTC, FunnyMan3595 approved these changes

2025-01-09 19:06 UTC, lewcc approved these changes

2025-01-10 19:13 UTC, lewcc requested changes
This hallucination needs to be added to the hallucination list, otherwise it'll never show.

2025-01-10 20:34 UTC, lewcc approved these changes
good to go

2025-01-10 20:41 UTC, Burzah approved these changes

2025-01-10 20:44 UTC, merged