Fixes Deltastation's Huge Power Draw
ParadiseSS13/Paradise pull request #27671
Opened 2024-12-18 05:41 UTC by haydenredacted

## What Does This PR Do

Fixes the extreme amount of power that deltastation's atmos eating way too much power. This was done by turning off the heaters by default and making the Atmospherics desk its own new area.
The Atmospherics Desk is now Atmospherics Canister Storage and has an APC now.

## Why It's Good For The Game

Atmospherics eating a lot of power is unnecessary and seeing the draw be upwards of 22k is a tad too much.

## Images of changes

![image](https://github.com/user-attachments/assets/f5f6a542-1501-4bc8-a203-0e4b674d2d95)
![image](https://github.com/user-attachments/assets/385ccdb5-1e2d-4dc3-b6fb-61bcb00eace1)

## Testing

Booted up test server, power draw was in the understandable range, close to the bridge and medbay's. Atmospheric's Cannister Storage APC, airlock, and air alarm all had correct names.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
fix: fixed deltastation's power draw by turning off heaters and adding a new area
/:cl:

2024-12-18 14:53 UTC, Contrabang requested changes

2024-12-18 14:53 UTC, Contrabang commented on code/game/area/ss13_areas/engineering_areas.dm
> +/area/station/engineering/atmos/cannisterstorage
```suggestion
/area/station/engineering/atmos/canister_storage
```

2024-12-18 14:53 UTC, Contrabang commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Atmospherics Cannister Storage"
```suggestion
	name = "Atmospherics Canister Storage"
```

2025-01-06 14:17 UTC, FunnyMan3595 requested changes
1. We already have /area/station/engineering/atmos/control, which is what should be used here. No need for a new area type.
2. Please don't reroute the pipe in the same PR; that's unrelated.

2025-01-06 14:34 UTC, Fordoxia commented
> 1. We already have /area/station/engineering/atmos/control, which is what should be used here. No need for a new area type.
> 2. Please don't reroute the pipe in the same PR; that's unrelated.

The pipe would go under the wall that got added to hold the new APC if not rerouted.

2025-01-16 19:57 UTC, FunnyMan3595 commented
> The pipe would go under the wall that got added to hold the new APC if not rerouted.

I see your point on that one, but you should still switch to /area/station/engineering/atmos/control over making a new area type.

2025-01-17 03:29 UTC, FunnyMan3595 approved these changes

2025-01-17 14:39 UTC, silverplatedelta commented
In the attached screenshot, it appears that you have two pipes on the same layer mapped over each other, this will result in horrible awful pain and suffering as distro connects to that waste line. Can you make it so the pipes are not overlapping like that?

2025-01-31 17:52 UTC, haydenredacted commented
![image](https://github.com/user-attachments/assets/a66d4232-b985-466d-a3e5-df4eec3dd2be)
Apologies, didn't realize this was still open but the piping was fixed.

2025-02-07 11:19 UTC, merged