Fixes the tiles in the space bar being broken
ParadiseSS13/Paradise pull request #27685
Opened 2024-12-20 07:21 UTC by 1080pCat

## What Does This PR Do
Swaps the floortiles in the space bar from a non existing `/mineral` type to the actual plasteel type thats meant to be used

## Why It's Good For The Game
the floortiles were broken, the name was quite literally "broken floor tile"

## Images of changes
not visual, heres what it was like before though

![Code_NC4opOIxr4](https://github.com/user-attachments/assets/a8fc62ad-ddea-4e87-9f6d-6ac431efed53)
![StrongDMM_ni51YKEz7e](https://github.com/user-attachments/assets/bd95b38b-9481-4ae6-a106-fd5626ea384a)

## Testing
Compiled, checked if i could use the floor tiles

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog
:cl:
fix: Fixes the flooritles in the spacebar being broken.
/:cl:

2024-12-20 14:31 UTC, warriorstar-orion requested changes
It looks like there's a few on Box too:

![2024_12_20__09_31_12___maps_map_files_stations_boxstation dmm - Paradise (Workspace) - Visual Studio C](https://github.com/user-attachments/assets/814cc769-b656-45c8-b2c3-503e548f54ff)

Could you also add a maplint to prevent this from being used?

2024-12-21 05:28 UTC, 1080pCat commented
> It looks like there's a few on Box too:
> 
> ![2024_12_20__09_31_12___maps_map_files_stations_boxstation dmm - Paradise (Workspace) - Visual Studio C](https://private-user-images.githubusercontent.com/59303604/397769888-814cc769-b656-45c8-b2c3-503e548f54ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTg4OTYsIm5iZiI6MTczNDc1ODU5NiwicGF0aCI6Ii81OTMwMzYwNC8zOTc3Njk4ODgtODE0Y2M3NjktYjY1Ni00NWM4LWIyYzMtNTAzZTU0OGY1NGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA1MjMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxM2FmZTA5MDAyMmNjOGYyYjNlZDRjN2I4M2IzNGJjOTliYTVmNmU0NjA4ZDI1MzEwYTk4ZjQyYTE2YTdjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DdxFBP_Q88IWtTmxHtdFLP8GwLhG_uZmMvQkebf_tvQ)
> 
> Could you also add a maplint to prevent this from being used?

Done, also got a couple on another ruin :)

2024-12-21 13:28 UTC, warriorstar-orion approved these changes

2024-12-24 02:18 UTC, DGamerL approved these changes

2024-12-24 02:30 UTC, merged