[PTBF] Hallucination: The Backrooms
ParadiseSS13/Paradise pull request #27710
Opened 2024-12-22 09:40 UTC by pwbokie

## What Does This PR Do

Adds a new Major hallucination: the Backrooms. It has a weight of 1, meaning one in every (currently) 41 Major hallucinations will be this one.
This is a new area on the centcom z-level.
A player that experiences this hallucination sees that they are in the Backrooms: a strange, liminal area. While inside, their actual body onstation moves the same way that their body in the backrooms does. This lasts for ten seconds.

## Why It's Good For The Game

Rare new hallucination spices up gameplay and is a cool reference to a pop culture thing.

## Images of changes

![image](https://github.com/user-attachments/assets/4cc4df25-fc1c-4259-8f0f-51df666bd66d)
![image](https://github.com/user-attachments/assets/f43dc158-a3af-405b-9972-4a8a23a9fa70)

## Testing

Triggered the hallucination with VV, joined as an observer and made sure that the original body was also moving. Got naked in the backrooms, cloned items were still deleted.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Added a very rare Major hallucination
/:cl:

2024-12-22 09:55 UTC, pwbokie commented
I've created this PR so that I don't miss the deadline, but it has some cosmetic issues that I'm not going to be able to fix in time. The vast majority of the gameplay work itself is done and ready for review. I am also noticing this is failing automated tests as I'm typing this so that's fuuuun.

I am quite confident I can fix all of these problems on Monday, but if it's in poor taste to submit a PR with this many issues in order to meet the deadline, please let me know and I can withdraw it and submit it as its own thing later.

- The four rotations of corner walls are not working and just appear black. I don't know why, I have done some investigating and the sprites seem fine to me. You can see the issue in this image.
![image](https://github.com/user-attachments/assets/aad48a2a-536d-473d-8edb-eaa060d92c74)

- Player movement back on the station (or wherever the original is) is a bit scuffed. I adapted the human relaymove function to actually work properly and relay movement (it was just originally just 100% some vore stuff contingent on being in someone's stomach, sir this is a Wendy's), but I'm using the wrong Move proc and I don't know how to access the normal glide movement, so the original player body moves more like a mech than a person. I dug for this for a WHILE and couldn't figure it out.

- I want to use a different carpet texture, here is the mockup I did a bit ago that fits a lot better IMO. This would be a quick fix.
![image](https://github.com/user-attachments/assets/bf9b4257-8352-434c-95b3-3bfb40d193b7)

The goal is to make it as smooth of a transition there and back as possible to make it a fairly immersive and seamless experience. The following issues are interfering with that.

- The player clone itself has some problems. Right now I clone the player into the backrooms with the same logic as Envy's Knife, which is... not perfect and kind of breaks the illusion. I spent a while trying to find a better analog somewhere else in the code and couldn't come up with anything quite right. Not sure if there is a better solution than just manually cloning a ton of player attributes (hair, skin color, racial features etc.)

- I included code for copying item attributes on the clothing items that are cloned onto the player, but joining ingame with a default jumpsuit reveals pretty quickly that items aren't cloning correctly either (dye rerolls, which I'm sure has farther reaching implications).

Hopefully this all makes sense, I am taking this down as notes for myself when I can get back to working on it on Monday, but I am running on fumes right now.

2024-12-23 20:07 UTC, pwbokie commented
![image](https://github.com/user-attachments/assets/3bf47c8c-5eab-41fa-9bb8-0fc93033dec2)

New carpet, I'm going to leave the lights as-is

2024-12-24 01:53 UTC, pwbokie commented
@BeagleGaming1 suggested a different method of doing the backrooms clone which is much simpler and solves a few problems. I'll update the original post to better reflect the current state of the PR

2025-01-01 18:31 UTC, FunnyMan3595 commented
Cool idea, but I'm not fond of using up z1 space for it, since that's a limited resource.

2025-01-06 06:59 UTC, BiancaWilkson requested changes

2025-01-06 06:59 UTC, BiancaWilkson commented on code/modules/hallucinations/hallucinations.dm
> +		/obj/effect/hallucination/no_delete/backrooms = 1
I tried forcing the event to spawn the backrooms hallucination, and nothing ended up happening. The behavior of the hallucination is on the manager itself, so I'd ask DGL how he wants to handle the mass hallucination event spawning these new ones.

2025-01-06 06:59 UTC, BiancaWilkson commented on code/modules/hallucinations/effects/backrooms.dm
> +	SIGNAL_HANDLER
Could you please add a comment for what signal is calling this proc?

2025-01-10 02:06 UTC, pwbokie commented on code/modules/hallucinations/effects/backrooms.dm
> +	SIGNAL_HANDLER
added!

2025-01-10 02:09 UTC, pwbokie commented on _maps/map_files/generic/centcomm.dmm
> +/obj/structure/closet/secure_closet/bar,
this was an oversight, I think it maybe had something to do with me misusing mapmerge, it is gone now! :)

2025-01-10 02:40 UTC, pwbokie commented on code/modules/hallucinations/hallucinations.dm
> +		/obj/effect/hallucination/no_delete/backrooms = 1
Switched to how the xeno pounce does it and tested it via the event and it's working nicely. Thanks for catching this!

2025-01-10 19:25 UTC, lewcc commented on code/modules/hallucinations/effects/backrooms.dm
> +	. = ..()
```suggestion
	return ..()
```

2025-01-10 19:25 UTC, lewcc commented on code/modules/hallucinations/effects/backrooms.dm
> +	SIGNAL_HANDLER
This is how we'd prefer you document the signals, as per our style guides
```suggestion
	// signal is called above in on_spawn so that whenever our human moves, we also move the clone
	SIGNAL_HANDLER  // COMSIG_MOVABLE_MOVED
```

2025-01-15 17:40 UTC, DGamerL commented on code/modules/hallucinations/effects/backrooms.dm
> +/datum/hallucination_manager/backrooms/Destroy(force, ...)
```suggestion
/datum/hallucination_manager/backrooms/Destroy(force)
```

2025-01-15 17:42 UTC, DGamerL commented on code/modules/hallucinations/effects/backrooms.dm
> +	initial_hallucination = /obj/effect/hallucination/no_delete/backrooms
Reminder from what we discussed in discord

2025-01-15 17:43 UTC, DGamerL commented on code/modules/hallucinations/effects/backrooms.dm
> +	var/obj/item/clone_base
Please autodoc these!

2025-01-15 17:43 UTC, DGamerL commented on code/modules/hallucinations/effects/backrooms.dm
> +	human_owner = owner
Do we need to use `human_owner` here as a var on the manager? Why not just typecast it here instead so we can remove line 21?

2025-01-15 18:18 UTC, pwbokie commented on code/modules/hallucinations/effects/backrooms.dm
> +	human_owner = owner
Removed and typecasted in both methods

2025-01-15 18:19 UTC, pwbokie commented on code/modules/hallucinations/effects/backrooms.dm
> +	initial_hallucination = /obj/effect/hallucination/no_delete/backrooms
removed the initial_hallucination and added a clause to check if it exists in hallucination manager

2025-01-15 18:19 UTC, pwbokie commented on code/modules/hallucinations/effects/backrooms.dm
> +/datum/hallucination_manager/backrooms/Destroy(force, ...)
done

2025-01-18 19:57 UTC, pwbokie commented
https://github.com/user-attachments/assets/b55efc1c-83e7-4aab-a9ed-0a265fefd9ab

Added a nice fade to this at the suggestion of DLG which increased the complexity of the code but also made the transition less jarring.

2025-01-24 02:45 UTC, DGamerL approved these changes
LGTM

2025-01-24 02:45 UTC, DGamerL commented on code/game/objects/structures/false_walls.dm
> +
Is this needed/used?

2025-01-24 02:52 UTC, pwbokie commented on code/game/objects/structures/false_walls.dm
> +
Not used anywhere. I was considering adding hidden walls to the layout at one point. I can remove it if desired.

2025-01-24 02:52 UTC, DGamerL commented on code/game/objects/structures/false_walls.dm
> +
Please do!

2025-01-24 02:53 UTC, DGamerL commented on code/game/objects/structures/false_walls.dm
> +
Nvm just keep it

2025-01-25 01:10 UTC, BiancaWilkson approved these changes
Concerns addressed, code looks good!

2025-01-25 13:31 UTC, merged