[PTBF] Traitor stealing a high risk item
ParadiseSS13/Paradise pull request #27718
Opened 2024-12-22 20:59 UTC by DGamerL

## What Does This PR Do
Adds a new major hallucination:
A traitor will jump in with the syndicate teleporter and steal a nearby highrisk item! If the item is on the owner, it will also stun them
[Video coming soon]

## Why It's Good For The Game
Cool new hallucination, aimed primarily at heads of staff or traitors who stole highrisk items. Therefore it will automatically reroll itself into a different major hallucination if it fails to find a target

Current list of known bugs:

- [ ] For some reason the override image isn't being removed properly, causing the item to be invisible forever
- [ ] Hallucination doesn't move towards owner if they move away (easy fix)
- [ ] Add backpack support

## Testing
See above, the rest works

<hr>

### Declaration
This has been requested for a long time by Qwerty
- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Added a new hallucination that steals one of your high risk items
/:cl:

2024-12-22 21:23 UTC, Contrabang requested changes

2024-12-22 21:23 UTC, Contrabang commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		GLOB.high_risk_items |= UID()
We already use a global list for high value items from the antag menu. Please use that instead.

2024-12-22 21:23 UTC, Contrabang commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +			continue
also check z level please

2024-12-29 14:15 UTC, Drsmail commented
Sound like a fun idea, could you perhaps make agent use Chameleon Counterfeiter on stolen iteam, so when hallucination ends it's looks like a fake iteam?
![image](https://github.com/user-attachments/assets/4ec9d2bf-0a15-4d75-9cc5-4a4c7e02a74a)

2024-12-31 15:15 UTC, Qwertytoforty commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +		if(ishuman(risky_thing.loc) && risky_thing.loc == owner)
This will fail if the item is in a backpack or modsuit, vs a pocket

2024-12-31 15:15 UTC, Qwertytoforty commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +	if(ishuman(target.loc) && target.loc == owner)
Same here

2024-12-31 15:15 UTC, Qwertytoforty commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +		if(ishuman(risky_thing.loc) && risky_thing.loc == owner)
Then again, they would have to strip off the backpack. Could be interesting.

2025-01-03 21:55 UTC, lewcc commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +		if(ishuman(risky_thing.loc) && risky_thing.loc == owner)
We probably have some `check_contents_recursive` procs you could use here instead

2025-01-03 21:55 UTC, lewcc commented on code/modules/hallucinations/effects/stealing_traitor.dm
> +	new/obj/effect/temp_visual/teleport_abductor/syndi_teleporter(spawn_turf)
```suggestion
	new /obj/effect/temp_visual/teleport_abductor/syndi_teleporter(spawn_turf)
```

2025-01-10 19:27 UTC, lewcc reviewed
Code mostly looks good, just pending deconflicting and addressing outstanding reviews!

2025-02-11 01:36 UTC, closed without merging