Give USSP traders the Zvezhan language
ParadiseSS13/Paradise pull request #27747
Opened 2024-12-26 04:01 UTC by pwbokie

## What Does This PR Do

Makes it so commie traders know the Zvezhan language.

## Why It's Good For The Game

Gives them a language to speak between each other, good for RP, also it just makes sense.

## Testing

Forced USSP trader odds in the code, forced a trader event, made sure I could speak Zvezhan.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: USSP traders can speak their home language
/:cl:

2024-12-26 14:23 UTC, Miraviel requested changes
Consider adding the language in `/datum/outfit/admin/trader/commie/post_equip()` instead of these 3 separate places; it makes more sense there and it makes adminspawns inherit the language too.

Something like this:

```
/datum/outfit/admin/trader/commie/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
	. = ..()
	if(visualsOnly)
		return
	H.add_language("Zvezhan")
```

2024-12-27 16:28 UTC, pwbokie commented
@Miraviel I don't believe `post_equip` is invoked when spawning traders, reason being that the admin spawns not only already gain the language, but also have it set to their default language in that method.

```
/datum/outfit/admin/soviet/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
	. = ..()
...
	H.add_language("Zvezhan")
	H.set_default_language(GLOB.all_languages["Zvezhan"])
```

2024-12-31 13:36 UTC, Miraviel commented
> @Miraviel I don't believe `post_equip` is invoked when spawning traders, reason being that the admin spawns not only already gain the language, but also have it set to their default language in that method.
> 
> ```
> /datum/outfit/admin/soviet/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
> 	. = ..()
>         ...
> 	H.add_language("Zvezhan")
> 	H.set_default_language(GLOB.all_languages["Zvezhan"])
> ```

It gets called. The outfit you are posting is a different path to what you are editing, look at `traders.dm` line 163, the datum you are editing:

```
/datum/traders/commie
	trader_type = "USSP"
	trader_location = "Belastrav"
	dock_site = "Belastrav Station"
	trader_species = /mob/living/carbon/human
	trader_outfit = /datum/outfit/admin/trader/commie
	trader_minor_special = /obj/effect/spawner/random/traders/ussp_minor
	trader_major_special = /obj/effect/spawner/random/traders/ussp_major
```

The outfit you are looking for is `/datum/outfit/admin/trader/commie` not the `soviet` one you posted.

I tested the code snippet I gave you:

![image](https://github.com/user-attachments/assets/28dc5104-25e2-47c4-ab4f-ef11ba7b5a0f)

Here it is spawned in:

![image](https://github.com/user-attachments/assets/dc69ab43-236c-45f5-9659-37c35d8b0f53)

You can test spawning in editing the list on line 39 in `traders.dm`:

```
	var/datum/traders/T = pick(/datum/traders/sol,
								/datum/traders/cyber,
								/datum/traders/commie,
								/datum/traders/unathi,
								/datum/traders/vulp,
								/datum/traders/ipc,
								/datum/traders/vox,
								/datum/traders/skrell,
								/datum/traders/grey,
								/datum/traders/nian)
```

Just remove everything that is not the commie one and it will only spawn that. (After that, start up a server, Event -> Event Manager Panel -> Major -> Traders -> and keep pressing `--` until it spawns. Just make sure you have spawning in as a Trader enabled in your game prefs.)

2025-01-02 23:03 UTC, pwbokie commented
Yup, this is a better approach. I'm testing locally and pushing shortly.

2025-01-05 13:16 UTC, Miraviel approved these changes

2025-01-06 07:04 UTC, Burzah approved these changes

2025-01-06 07:08 UTC, merged