Reduces slowdown on Security Biosuits
ParadiseSS13/Paradise pull request #27768
Opened 2024-12-29 20:14 UTC by SchrodingersWolf

## What Does This PR Do

Reduces slowdown for Security Biosuits from 1 to 0.45, same as Security MODsuits.

Other biosuits are not affected by this PR.

## Why It's Good For The Game

Everyone is familiar with the dreaded Botany gaming with their fluorosulphuric acid + deathmix tomatos, which melts away most protection that you would have - While you can get breathing tubes to counter breathing in the toxic fumes, most injectproof clothing are not acidproof and will still melt from the acid.

Biosuits on the other hand are currently extremely underused due to their crippling slowdown, and the Security biosuit is usually left forgotten in the Armoury even when a Botany war criminal is out and about - While I'm hesistant in making all the biosuits move faster, I feel like the Security variant could use a little boost, especially since it is one of a kind and not purchasable from Cargo. (Which I do want to change, but that is for another PR)

## Images of changes

![image](https://github.com/user-attachments/assets/aaa86495-513b-4058-9b9a-5c2effafb7cf)

## Testing

Loaded up the game, it compiles, checked variables and confirmed that only Sec biosuit has reduced slowdown, wore the biosuits and confirmed that I move normally in Sec biosuits but not in Janitor biosuit.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>
![image](https://github.com/user-attachments/assets/ad0dd290-aad7-412b-aa4a-1e3d9480ba51)

## Changelog

:cl:
tweak: Security Biosuits now have a less severe slowdown
/:cl:

2024-12-30 10:57 UTC, Miraviel requested changes
I had a nagging feeling that slowdown below 0.5 is simply not doing... Much? I edited the janitor biosuit's slowdown from 1 to 0.5 and tested it against no slowdown vs 0.45 slowdown (the proposed change) vs 0.5.

On the video, obviously with my slow ass clicking, the stopwatch is not exactly accurate, so I opened the recording in a video editor to see the exact timestamps for when movement starts and ends occurring.

| Slowdown | Time | Difference |
| --- | --- | --- |
| 0 | 00:01:28 - 00:03:57 | 2 seconds 29 millisecond |
| 0.45 | 00:09:01 - 00:11:30 | 2 seconds 29 milliseconds |
| 0.5 | 00:17:31 - 00:20:30 | 2 seconds 999 milliseconds |

At least based on my testing, this PR doesn't reduce the slowdown on the suit but simply removes it. (Which can be your intended change but you have to change the wording then)

https://github.com/user-attachments/assets/76ed8f52-55c8-4587-a5d8-bdaa627b8b1c

2024-12-30 11:15 UTC, Fordoxia commented
> At least based on my testing, this PR doesn't reduce the slowdown on the suit but simply removes it. (Which can be your intended change but you have to change the wording then)

The slowdown comes into play when you take damage, it stacks with painslow. A secoff in a modsuit that has been toolbox'd will move noticeably slower than a toolbox'd secoff without a modsuit.

2024-12-30 11:28 UTC, Miraviel commented
> > At least based on my testing, this PR doesn't reduce the slowdown on the suit but simply removes it. (Which can be your intended change but you have to change the wording then)
> 
> The slowdown comes into play when you take damage, it stacks with painslow. A secoff in a modsuit that has been toolbox'd will move noticeably slower than a toolbox'd secoff without a modsuit.

Aware, I posted the proc above which calculates the slowdown - but on a 100% healthy mob with no other slowdowns, 0.45 does absolutely nothing as opposed to the sec modsuit as it was likened to, which has a base slowdown even when you are fully healthy.

2024-12-30 11:39 UTC, Burzah commented
At this point, I am not sure why we don't change the slowdown on the parent type for all biosuits. High slowdowns usually tend to stop players from using those items. I would say it should be considered whether making the change on all biosuits is more feasible.

2024-12-31 01:16 UTC, SchrodingersWolf commented
> At this point, I am not sure why we don't change the slowdown on the parent type for all biosuits. High slowdowns usually tend to stop players from using those items. I would say it should be considered whether making the change on all biosuits is more feasible. 

I can do that, but as mentioned in the PR, I'm hesitant in introducing injectproof clothing that is wildly available, which would curtail blowpipe/syringe gun/Botany plants/shotgun darts with wildly available suits with no slowdown.

While that was previously achievable with MODsuits, an antag still has to go through a few hoops to get them (And other than BRM and Elite MOD, which costs TC, they gain a vulnerability to EMPs instead), which would likely impact Holy Water darts and tranq darts.

I'm totally fine with lowering slowdown on all biosuits, but I only secured approval for Sec biosuits so I do want to make sure first.

2024-12-31 01:31 UTC, SchrodingersWolf commented
> > > At least based on my testing, this PR doesn't reduce the slowdown on the suit but simply removes it. (Which can be your intended change but you have to change the wording then)
> 
> > 
> 
> > The slowdown comes into play when you take damage, it stacks with painslow. A secoff in a modsuit that has been toolbox'd will move noticeably slower than a toolbox'd secoff without a modsuit.
> 
> 
> 
> Aware, I posted the proc above which calculates the slowdown - but on a 100% healthy mob with no other slowdowns, 0.45 does absolutely nothing as opposed to the sec modsuit it was likened to, which has a base slowdown even when you are fully healthy.

Security MODsuit's activated base slowdown is 0.45, the same as new Security biosuit, so unless there is some weird MODsuit code that makes MODsuit slowdown more prominent, the two should operate the same.

2025-01-06 06:42 UTC, FunnyMan3595 approved these changes

2025-01-08 21:49 UTC, lewcc approved these changes

2025-01-08 22:05 UTC, merged