Increase Required Hours for Command and AI
ParadiseSS13/Paradise pull request #27775
Opened 2024-12-30 21:16 UTC by PollardTheDragon

## What Does This PR Do

This PR increases the requires hours to play in each department to unlock its respective command role from 20 to 40. Captain is 50 hours, and AI is 20 hours.

This PR also standardizes the job time requirements to using time defines instead of integers for better readability.

## Why It's Good For The Game

It's all too often that one encounters a chief engineer whos only experience is setting up solars, or a CMO who's only ever done basic medicine and doesn't know how to work on vox or do chemistry/virology. By increasing the number of required hours, we can hope that players have more opportunity to work in more diverse areas within a department before getting to lead it.

## Testing

Compiled. Wasn't able to accurately test hours in debug environment.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>
![image](https://github.com/user-attachments/assets/87a52b6f-c13b-4a00-b93e-fe055f5947b8)
![image](https://github.com/user-attachments/assets/cd81cb91-d451-41ca-8405-1b8fd233e9f0)

## Changelog

:cl:
tweak: Increased required hours for Command roles
/:cl:

2024-12-31 17:04 UTC, Drsmail requested changes
Now looks like those comment are redundant.

2024-12-31 17:04 UTC, Drsmail commented on code/game/jobs/job/supervisor.dm
> +	exp_map = list(EXP_TYPE_COMMAND = 50 HOURS) // 50 hours baby
```suggestion
	exp_map = list(EXP_TYPE_COMMAND = 50 HOURS)
```

2024-12-31 17:04 UTC, Drsmail commented on code/game/jobs/job/supervisor.dm
> +	exp_map = list(EXP_TYPE_COMMAND = 50 HOURS) // 50 hours baby
```suggestion
	exp_map = list(EXP_TYPE_COMMAND = 50 HOURS)
```

2024-12-31 17:04 UTC, Drsmail commented on code/game/jobs/job/supervisor.dm
> +	exp_map = list(EXP_TYPE_SECURITY = 100 HOURS) // 100 hours baby
```suggestion
	exp_map = list(EXP_TYPE_SECURITY = 100 HOURS)
```

2025-01-01 03:50 UTC, PollardTheDragon commented
> Now looks like those comment are redundant.

Just leftovers from whoever made the original hour requirements. They're gone now.

2025-01-01 18:42 UTC, FunnyMan3595 commented
I'm honestly not convinced this does anything other than punish people who don't play as much. I've seen 500+ hour players be bald as heck, and 3h players who are quite competent. Even a complete newcomer who learns actively can be a good CMO after 10h, and someone who's not trying won't be competent after 100h.

2025-01-02 08:45 UTC, Code-Lyoko0 commented
Making the hours requirement higher will not make command better, it will just makes us have less command. I've noticed that the biggest problem with command is that they don't know how to be a leader and less that they don't know their department. I agree with Funnyman here, this wont improve command, this will just make us have less command in general. 

Raising hours has been brought up before and we have said MANY time that raising the hours will not improve command like people think it will, as we have seen 1200h players who know everything about their department be VERY bad command members, and we have also had 20h players who are some of the best command we have had.

2025-01-05 16:25 UTC, Gatchapod commented
While I agree with Lyoko and Funny that it won't affect the command quality much, I think it is absolutely a good call for AIs.

Back when the original time requirement was set, I don't think we actually had anything beyond Crewsimov on roundstart, maybe the core three at worst.
With station traits letting you roll really bizarre lawsets, getting even one round under experimental lawset can give some vague idea of what's fine and what isn't as a cyborg, actually preparing you better for the same scenario as an AI.

2025-01-14 22:42 UTC, PopeDaveThe3th approved these changes
code's fine

2025-01-29 22:20 UTC, Burzah commented
At this time the PR has failed the vote between the balance and design team, 6 to 4 and the PR will be closed. Below are comments from the tracker about the PR in general. If you want to continue this work, or implement it another way, please contact both the design and balance teams. Thank you for contributing regardless. Discussion that come from a PR like this are important for molding opinions and sparking ideas on how we can improve our project.

I'm honestly not convinced this does anything other than punish people who don't play as much. I've seen 500+ hour players be bald as heck, and 3h players who are quite competent. Even a complete newcomer who learns actively can be a good CMO after 10h, and someone who's not trying won't be competent after 100h.

I stated on my pre-approval why I think this is a good idea. I also think this'll allow players to take a bit more time to understand their department before being swamped (potentially) by command related responsabilities.

Im approving this from an admin perspective and round balence perspective. Yes, gametime does not make someone less bald but it does increase their odds AND they are more likely to act like command rather than new players going for new toys and power trips.

Against this as stated on my comment on the PR, I dont think this will improve the quality of command.

I do think as [REDACTED] said that this will have minimal impact on command player quality.

I dont think a flat increase to the hours will do anything, ie someone that just plays one role for the entire timer, and does not know the rest of their department

AI and captain I can see it being raised. The rest of the heads seems a bit much.

No opinion either way. I understand increasing the statistical odds that someone competent will be present with a higher req. time of experience. But I've never really seen such a correlation between play-time and experience that it's proven and obvious. End of the day, it's a video game and people will be good/bad at whatever role/class/antag they decide to play.

2025-01-29 22:20 UTC, closed without merging