[DNM] Attack chain migration: /obj/machinery
ParadiseSS13/Paradise pull request #27784
Opened 2024-12-31 17:11 UTC by warriorstar-orion

## What Does This PR Do
This PR migrates the `/obj/machinery` type tree to the new attack chain.

Yes, the PR could have been smaller by not renaming the arguments that were passed in to the legacy methods but 1) not that smaller and 2) it helps me keep track of the code paths that actually interact with the passed in objects.
## Why It's Good For The Game
Critical part of attack chain migration.
## Testing

The plan is to implement as many of these as possible into game tests without the tests being flaky or taking way too long to run.

<details>

<summary>Test Plan</summary>

- [ ] `/obj/machinery/dna_scannernew/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/computer/scan_consolenew/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/abductor/console/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/abductor/gland_dispenser/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/abductor/experiment/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/nuclearbomb/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/pdapainter/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/sleeper/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/bodyscanner/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/access_button/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/autolathe/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/camera/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/cell_charger/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/clonepod/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/readybutton/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/computer/card/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/computer/cloning/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ] Test UI interactions/lockouts work as expected.
    - [ ] Test non-relevant item interactions work as expected.
    - [ ] Test relevant item interactions work as expected.
- [ ] `/obj/machinery/computer/borgupload/item_interaction(...)`
    - [ ] Test construction and deconstruction works as expected.
    - [ ] Test damage-based destruction works as expected.
    - [ ] Test upgrading components works as expected.
    - [ ]  [...]

2024-12-31 17:18 UTC, Drsmail commented
Are you finishing all your work before the new year? I can't imagine how to review this.

2024-12-31 19:04 UTC, warriorstar-orion commented
> Are you finishing all your work before the new year? I can't imagine how to review this.

Sadly this is the work that needs to be done before I can start next year's projects. In this particular case, I'm not PRing the kitchen rework before this PR, because the kitchen rework introduces a bunch of additional machines I don't want on the old attack chain.

2025-01-01 17:04 UTC, Drsmail requested changes
Only did 1/3 will finish later + wanna here if i am doind a good job here with my review, please give me feedback so i can adjust.

2025-01-01 17:04 UTC, Drsmail commented on code/game/machinery/suit_storage_unit.dm
> +			return ITEM_INTERACT_COMPLETE
```suggestion
		return ITEM_INTERACT_COMPLETE
```
in case shock fails? And maybe` if(shock(user, 100))` ->` shock(user, 100)`?

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/gamemodes/miniantags/abduction/machinery/dispenser.dm
> +		return ITEM_INTERACT_COMPLETE
That would stop the attack chain no matter what item was used, which we don't want; if other items are used on the the machine we want the parent types to handle the interaction.

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/spaceheater.dm
> +	if(istype(used, /obj/item/stock_parts/cell))
Fixed.

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/shieldgen.dm
> +	else if(istype(used, /obj/item/card/id) || istype(used, /obj/item/pda))
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/shieldgen.dm
> +	else if(istype(used, /obj/item/stack/cable_coil) && malfunction && is_open)
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/portable_turret.dm
> +
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/iv_drip.dm
> +
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/guestpass.dm
>  		return
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/firealarm.dm
> +				return ITEM_INTERACT_COMPLETE
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/computer/law.dm
>  	return
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/camera/camera.dm
>  			return
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/gamemodes/miniantags/abduction/machinery/console.dm
> +	else if(istype(used, /obj/item/clothing/suit/armor/abductor/vest) && AddVest(used))
Fixed

2025-01-10 00:41 UTC, warriorstar-orion commented on code/game/machinery/suit_storage_unit.dm
> +			return ITEM_INTERACT_COMPLETE
If the shock fails, we want the user's interaction to continue, we don't want to stop here unconditionally

2025-01-20 19:30 UTC, FunnyMan3595 requested changes

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/game/gamemodes/nuclear/nuclearbomb.dm
>  			return attack_hand(user)
This needs to become 
```
attack_hand(user)
return ITEM_INTERACT_COMPLETE
```

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/game/machinery/portable_turret.dm
>  					return
Blank return

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/modules/food_and_drinks/kitchen_machinery/cooker.dm
> +/obj/machinery/cooker/item_interaction(mob/living/user, obj/item/used, list/modifiers)
Multiple returns here that should be `return ITEM_INTERACT_COMPLETE`

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
>  			return
Two blank returns here.

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/modules/paperwork/faxmachine.dm
> +		return
Blank return

2025-01-20 19:30 UTC, FunnyMan3595 commented on code/modules/power/engines/supermatter/supermatter.dm
>  		return
Two blank returns

2025-01-20 20:41 UTC, Burzah commented on code/modules/power/engines/supermatter/supermatter.dm
>  		return
does this need the return updated?

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/food_and_drinks/kitchen_machinery/cooker.dm
> +/obj/machinery/cooker/item_interaction(mob/living/user, obj/item/used, list/modifiers)
Fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
>  				"You hear a splash, and a sizzle."
Yeah, I've already gone overboard with this PR, I'll come around for a cleanup when I try and make the machinery messages more consistent.

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
> +			var/obj/item/tank/T = used
yup, good catch

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
>  			return
fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/hydroponics/biogenerator.dm
> +	// TODO: This feels off, no where else do we have a blanket "print a
later, this would be a lot of code shuffling

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/hydroponics/hydroponics_tray.dm
> +		playsound(src, used.usesound, 50, 1)
as above, going to hold off on more tweaks to existing code like funnyman suggested, but will circle back to these

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/hydroponics/hydroponics_tray.dm
> +		if(!do_after(user, 25 * used.toolspeed, target = src) || (!myseed && !weedlevel))
as above

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/hydroponics/hydroponics_tray.dm
> +		playsound(src, used.usesound, 50, 1)
as above

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/paperwork/faxmachine.dm
> +		return
yup, fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/paperwork/faxmachine.dm
> +		return
fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/power/engines/supermatter/supermatter.dm
>  		return
fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/power/engines/supermatter/supermatter.dm
>  		return
yup, fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/research/scientific_analyzer.dm
> +	// TODO: Almost positive this doesn't need to do the same exchange parts shit as /obj/machinery
yup.

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/telesci/telesci_computer.dm
> +		// TODO: Provide some kind of message if there's already an inserted GPS.
yup. when i add TODOs to PRs it's always for later, anything in scope to the PR i always mark with a `#warn` so i don't forget to do it.

2025-01-20 22:47 UTC, warriorstar-orion commented on code/game/machinery/portable_turret.dm
>  					return
fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/game/gamemodes/nuclear/nuclearbomb.dm
>  			return attack_hand(user)
fixed

2025-01-20 22:47 UTC, warriorstar-orion commented on code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
> +			if(do_after(user, 20 * used.toolspeed, target = src))
will address these in some later cleanups

2025-01-20 22:56 UTC, warriorstar-orion commented on code/modules/atmospherics/machinery/airalarm.dm
> +				playsound(get_turf(src), used.usesound, 50, 1)
as above

2025-01-20 23:38 UTC, FunnyMan3595 approved these changes

2025-01-21 00:08 UTC, Burzah approved these changes

2025-01-26 00:29 UTC, merged